### ISSUE TITLE
API docs?

### ISSUE THREAD

**Issue by Charuru** [SillyTavern/SillyTavern#1000]
Is there API docs for the basic generate etc commands? I only see docs for the image generation on the extras. I know I can directly connect to the backend but if I want to take advantage of sillytavern's niceties is that available? If not I'll just connect directly to backend...

**Comment by Cohee1207** [comment]
No it is not possible. Most of the fluff is done on the frontend. There is no public API, except for UI extensions. Backend is mainly for handling files.
