### ISSUE TITLE
[Feature Request] Persona depth unlinked from Character Card/AN

### ISSUE THREAD

**Issue by Verias4** [SillyTavern/SillyTavern#1003]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
Currently the depth at which persona information is inserted is linked to the Character Card or Authors Note/Scenario. 
This sometimes causes confusion with which character the AI should choose to reply with. 

**Describe the solution you'd like**
Unlinking the depth and allowing it to be a free form field in the prompt manager, similar to the current prompt fields in the manager. This would allow a great variety of solutions [JBs] to adress the character reply confusion. 

**Describe alternatives you've considered**
An override of the Persona description field, as well as a text replacement macro.

- Persona description would not be sent. Any information written in the field could be replaced using {{persona description}} similar to {{user}}
- User could then create a seperate prompt, that sends {{persona description}} at a specifed depth.

**Additional context**
![image](https://github.com/SillyTavern/SillyTavern/assets/90230738/b3adf131-680f-4eef-bb5e-7d3bd1459339)

**Comment by Cohee1207** [comment]
This is in the works already.

**Comment by Cohee1207** [comment]
Merged to staging. Feel free to try it out
