### ISSUE TITLE
[Feature Request] Re add support for dragable prompts in presets.

### ISSUE THREAD

**Issue by imesha10** [SillyTavern/SillyTavern#1005]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes, searched for drag and nothing matched my request.

**Is your feature request related to a problem? Please describe.**
So a little while on the staging branch when this was added,
![image](https://github.com/SillyTavern/SillyTavern/assets/16441743/7862c302-de00-4607-b01c-3c7eeed24ecc)
When this was first released it was possible to move individual items around and reorder then by clicking and holding. 
I thought this was a really nice and quick feature, however in the most recent commits, that feature since seem to have been disabled.

What are scenarios where this is advantagous:
When testing advanced jailbreaks sometimes you want to quickly change the position of one thing. So then I would just reorder it with this new feature.

**Describe the solution you'd like**
Re add the ability to drag these around or have a setting in the option for 'draggable preset items'.

**Describe alternatives you've considered**
The current solution to the problem is to just rewrite each one. However the temp solution that was added was a more 'neat' solution.

**Comment by Cohee1207** [comment]
It is draggable on my end, checked just couple of minutes ago. See your browser console for any errors. Also on phone you need to hold the part for a second to drag

**Comment by Cohee1207** [comment]
Also if you have a touchscreen on your computer you may also need to hold it longer. Just thought about that.

**Comment by imesha10** [comment]
I'm on my laptop with touch screen. So I tried the touchscreen as you said and it worked, however the mouse does not seem to work.

**Comment by imesha10** [comment]
I do see the drag mouse icon but it does not drag with the mouse.
![image](https://github.com/SillyTavern/SillyTavern/assets/16441743/8609f194-a55b-495d-b6fd-1fc570094f16)

**Comment by imesha10** [comment]
Also
> Documents\AI\GitApps\SillyTavern> git pull
> Already up to date.

On staging branch.

**Comment by imesha10** [comment]
# Here is my log.

``` console
Device type: desktop
moment.js:287 Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: August 23, 2023 3:42pm, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (http://localhost:8000/lib/moment.min.js:1:3257)
    at Nt (http://localhost:8000/lib/moment.min.js:1:21587)
    at Pt (http://localhost:8000/lib/moment.min.js:1:22164)
    at W (http://localhost:8000/lib/moment.min.js:1:22247)
    at f (http://localhost:8000/lib/moment.min.js:1:207)
    at timestampToMoment (http://localhost:8000/scripts/utils.js:492:9)
    at addOneMessage (http://localhost:8000/script.js:1405:24)
    at sendSystemMessage (http://localhost:8000/script.js:1837:5)
    at Object.<anonymous> (http://localhost:8000/script.js:692:5)
    at e (http://localhost:8000/lib/jquery-3.5.1.min.js:2:30005)
B @ moment.js:287
(anonymous) @ moment.js:319
Nt @ moment.js:2550
Pt @ moment.js:2943
W @ moment.js:3041
f @ moment.js:16
timestampToMoment @ utils.js:492
addOneMessage @ script.js:1405
sendSystemMessage @ script.js:1837
(anonymous) @ script.js:692
e @ jquery-3.5.1.min.js:2
t @ jquery-3.5.1.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.5.1.min.js:2
c @ jquery-3.5.1.min.js:2
fireWith @ jquery-3.5.1.min.js:2
fire @ jquery-3.5.1.min.js:2
c @ jquery-3.5.1.min.js:2
fireWith @ jquery-3.5.1.min.js:2
l @ jquery-3.5.1.min.js:2
(anonymous) @ jquery-3.5.1.min.js:2
load (async)
send @ jquery-3.5.1.min.js:2
ajax @ jquery-3.5.1.min.js:2
S.<computed> @ jquery-3.5.1.min.js:2
(anonymous) @ script.js:689
openai.js:2553 OpenAI model changed to gpt-3.5-turbo-16k
power-user.js:416 applying bubblechat
elevenlabs.js:53 Using default TTS Provider settings
elevenlabs.js:73 Settings loaded
thumbnail:1     GET http://localhost:8000/thumbnail?type=avatar&file=Terra.png 404 (Not Found)
```

**Comment by Cohee1207** [comment]
I don't have any desktop devices with a touchscreen to test this, but I hope it is fixed again.

**Comment by imesha10** [comment]
@Cohee1207 Yes it's fixed, thank you!🎉
