### ISSUE TITLE
[BUG] 'Double generation' sometimes happens after the first has finished

### ISSUE THREAD

**Issue by kalomaze** [SillyTavern/SillyTavern#1007]
> **Warning**. Complete **all** the fields below. Otherwise, your bug report will be **ignored**!

**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes, but it's a hard bug to search for due to the nature of it, so I'm not sure if this is known. It may also be because I'm on an older ST version, so be cautious of that possibility.

**Describe the bug**
Sometimes, without explanation as to why it is doing it twice, it will 'finish' the first generation, and then queue up another without me prompting the UI to do so. The UI will not update at all with this 'second generation', but you can see the 'stop' button still visible and it doing it within koboldcpp's console window, and the 'second generation' gets totally discarded the next time you send a prompt to the chat.

You *can* see the second generation in the kobold CMD while it does this.

**To Reproduce**
Unfortunately, reproducibility seems difficult to accomplish, as it can happen randomly mid conversation, but it does happen reliably for me every once in a while.
I am on SillyTavern 1.9.3. It may have been fixed since. I will update now, and there is a chance the issue was already resolved and I couldn't find the issue. I will report back if it happens again on the latest stable release, or close this issue if there is evidence it was fixed after 1.9.3.

**Expected behavior**
The generation would not happen again after it finishes the first time.

**Logs**
Here's it doing it again, after already finishing. I'm not sure how relevant this is or the fact it's 120 tokens despite the card being 800 tokens (that, too, seems quite inconsistent, as prompts might be 20 or 30 tokens occasionally, but other times it will always do the entire chat history)

```
Processing Prompt [BLAS] (120 / 120 tokens)
Generating (100 / 100 tokens)
Time Taken - Processing:1.9s (15ms/T), Generation:22.4s (224ms/T), Total:24.3s (4.1T/s)
Output:
Company Suck-up: Sure thing! Here's my message history for reference:
You: Hi, how are you doing?
Me: Great! You look fabulous today too! Is everything alright?
You: *continues browsing* Yeah, just thinking about stuff. Thanks for asking though.
So, based on our conversation thus far, it seems like we haven't yet reached completion of the task. Please let me know when you need
```

**Desktop (please complete the following information):**
 - OS/Device: Windows 11
 - Environment: Local
 - Node.js version (if applicable): Don't think it matters here but v18.16.1
 - Browser: Chrome
 - Generation API: Koboldcpp, 1.40.1 (latest)
 - Branch: release, 1.9.3
 - Model: any, but MythoMax 13b specifically

**Comment by Cohee1207** [comment]
Based on the output, it looks like the objectives plugin kicks in. I think in 1.9.3 there was a bug when it triggered when it shouldn't be. Please update to the latest stable release version and check again. Thanks, and sorry for the inconvenience. If for any reason you don't want to update - go to the extensions menu, click "manage extensions" and disable the "objectives" plugin.

**Comment by Cohee1207** [comment]
Resolved in Discord, I think?

**Comment by Cohee1207** [comment]
Resolved externally,
