### ISSUE TITLE
[BUG/Feature Request] Unable to produce Vicuna 1.1-style prompts (missing newline)

### ISSUE THREAD

**Issue by alicat22** [SillyTavern/SillyTavern#1009]
**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
Unable to produce Vicuna 1.1-style prompts. There should be a newline before ASSISTANT:

**To Reproduce**
Default settings for Vicuna 1.1 with `Always add character's name to prompt`:
![image](https://github.com/SillyTavern/SillyTavern/assets/86847834/5c40de1b-1acb-4051-a4ae-13a85c7499e5)
```
    "ASSISTANT: (This is Bot's First Message)\n" +
    "(This is Bot's First Message)</s>\n" +
    "USER: User: (This is User's First Message)\n" +
    "(This is User's First Message)ASSISTANT:",
```
Default settings for Vicuna 1.1 with`Include Names`:
![image](https://github.com/SillyTavern/SillyTavern/assets/86847834/d11b3b9e-245c-4bcb-8cd3-dc4db88d9846)
```
    "ASSISTANT: DEBUG: (This is Bot's First Message)\n" +
    "(This is Bot's First Message)</s>\n" +
    "USER: User: (This is User's First Message)\n" +
    "(This is User's First Message)ASSISTANT: DEBUG:",
```
**Expected behavior**
There should be a newline before `ASSISTANT:`
```
    "ASSISTANT: DEBUG: (This is Bot's First Message)\n" +
    "(This is Bot's First Message)</s>\n" +
    "USER: User: (This is User's First Message)\n" +
    "(This is User's First Message)
    "ASSISTANT: DEBUG:",
```
**Logs**
https://gist.github.com/alicat22/a117370c1ac46eb148c6ad00787c1b3d

**Desktop (please complete the following information):**
 - OS/Device: Windows 10
 - Environment: Local
 - Browser: Chrome
 - Generation API: ooba (87442c6d)
 - Branch: Staging (4aa31fcba)
 - Model: PuddleJumper-13B-GPTQ-32g
 
**Additional Context**
Wrap newlines does *not* fix the issue.
![image](https://github.com/SillyTavern/SillyTavern/assets/86847834/464cb11b-1923-494b-a9c9-54da1ed62312)
```
    'USER: \n' +
    "User: (This is User's First Message)\n" +
    "(This is User's First Message)\n" +
    'ASSISTANT: \n' +
    'DEBUG:',
```

**Comment by alicat22** [comment]
Here are the three popular versions of Instruct. I'm attempting to do the first one:
![image](https://github.com/SillyTavern/SillyTavern/assets/86847834/ed5141cb-bfb7-4a8c-8397-4e350680ade4)

**Comment by Cohee1207** [comment]
You need to put a newline as the first line of the sequence box
![image](https://github.com/SillyTavern/SillyTavern/assets/18619528/c96b1641-da86-4aba-adea-7505ecc63b3a)

**Comment by alicat22** [comment]
With the updated template, it works perfectly. Thank you!

As a side note, I'm unsure what uses "BEGINNING OF CONVERSATION:" as a system sequence.

Template:
https://github.com/lm-sys/FastChat/blob/d578599c69d060e6d40943f1b5b72af98956092a/fastchat/conversation.py#L286-L299
