### ISSUE TITLE
[Feature Request] Character pagination fixing

### ISSUE THREAD

**Issue by Woisek** [SillyTavern/SillyTavern#1016]
When using the pagination, we then have multiple pages, When we now browse the pages and at say, page 4 we click a character, we face the first "problem": There is no back button who brings us back to the previous pagination page.
The second problem is, we then have to click the select/create button on top and this brings us to page 1 again. Strangely, I found myself one time on the previous pagination page like before selecting the character, but mainly, it gets to page 1.
This is really annoying when browsing multiple pages in, check an character, and then be back at page 1 again.

I would highly appreciate to either have a back button, that brings us to the page we were before selecting a character or
when click the select/create button on top, we are again be back on the page were we selected a character before.
🙂

**Comment by Cohee1207** [comment]
Are you sure you are on the latest staging? I made these changes a day or two ago:

1. Returning back to the characters list from a character card saves your previous pagination position.
2. Clicking the list button again sends you back to the first page.

Just checked and confirmed it's still in place. Looks like exactly what you need.

**Comment by Woisek** [comment]
SillyTavern 1.9.7 'staging' (3e25c3f5) is my version, didn't update today, tho.

**Comment by Cohee1207** [comment]
It was added here: https://github.com/SillyTavern/SillyTavern/commit/b7516433644c7f5d9ce128b09ee2d24e5232188a

**Comment by Woisek** [comment]
Ah, okay ... will update then. Thanks! 👍

Update:
Did the update, but now the following occurs:
Paging to i.e. page 3 -> select char -> click list button -> page 3 -> click a different char -> click list button -> first page

I tried it several times. It looks like, it works only on the first time. Selecting another char or paging to another page, clicking a char and then click list button, returns to the first page again. 😐

**Comment by Woisek** [comment]
Another thing to mention with pagination: When we scroll down a page to the bottom and click for the next page, the list stays at the bottom instead of going up to the top. So after clicking to the next page, we have always to scroll up. Would be nice if this gets also fixed. Thanks! 🙂

**Comment by Cohee1207** [comment]
Thanks, I did both.

**Comment by Woisek** [comment]
Wonderful, all working as it should now, many thanks! 🎉🎉👍
