### ISSUE TITLE
[Feature Request] Add option to unlock Rep pen and add third decimal place for Typical so that some NovelAI presets can be used. 

### ISSUE THREAD

**Issue by bucketcat** [SillyTavern/SillyTavern#1018]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
I can't use my sampler configuration, as it uses a repetition penality of 1.97 while the limit is 1.5 in Silly Tavern. Some other issues are rounding of TFS and Typical. My config uses 0.975, but it gets rounded to either 0.97 or 0.98.

**Describe the solution you'd like**

Add an option to unlock the repetition penalty and temperature sliders, like what already exists with token length. This should also be added to repetition penalty range, as it's seemingly limited to 2048 tokens currently.

Add %.3f to allow for another decimal place for Typical.

**Describe alternatives you've considered**
I've benchmarked various sampler configurations, and the one I use is by far the most useful for prose, though that is subjective. So, there are sadly no alternatives that can reproduce the level of output for me.

**Additional context**
While I use a custom pruned sampler config, it was initially based on a NAI preset. Some of their presets have a repetition penalty as high as 8 (Usually, this is when you put rep pen as the last sampler in the sampler order).

It would be nice to have the option to use any Novel ai sampler, the current ones are all old sampler presets. Importing the newer ones, for larger context models, don't work due to various settings being limited to a very narrow range.

**Comment by Cohee1207** [comment]
Have you tried the staging branch? It has a repetition penalty going as high as 8, and other controls synchronized with Novel in terms of min/max/step. Also, other settings are visible, including logit bias, banned tokens, and samplers order.

**Comment by bucketcat** [comment]
I have not, that is good to know, thank you! I'll swap over to it a bit later today, I'll close this if all works fine and dandy. 

Can you configure Typical & TFS to the third decimal place there?

**Comment by Cohee1207** [comment]
Already did for TFS. Applied to Typical

**Comment by bucketcat** [comment]
That was quick! I'll close this for now, and reopen it if I find any issues in the staging branch.

**Comment by bucketcat** [comment]
Rep pen is still hardcapped at 1.5, rep pen range is hardcapped at 4096 (previously 2048, I need 16k) and everything else previously mentioned seems to not work.

Used `git checkout remotes/origin/staging`  -> commit c91ab3b5 "_Add Kobold tokenization to best match logic. Fix not being able to stop group chat regeneration_".

Edit: Should probably have pulled first...

**Comment by bucketcat** [comment]
Alright, on commit f50db430. Getting constant stream of CSRF errors in the console, and all the previous issues. I might have messed something up, not entirely sure. 

Edit: Seems to still work, despite the stream of errors. Nevertheless, specifying 0.975 for Typical or 1.97 for repetition penalty will change it to 0.97 Typical and 1.00 for repetition penalty on generation based on console output.

**Comment by Cohee1207** [comment]
After you pull, restart the ST server and clear the browser cache and cookies or start in Incognito mode.

**Comment by bucketcat** [comment]
Ah, silly me! I really should start using Firefox containers for anything relying on browser cache... Maybe there's a way to tie each branch in a remote to its own container or browser profile. Either way, back to the topic.                                                                                                                                                                  

The things I mentioned initially seem to all work from my very hasty test.
