### ISSUE TITLE
[BUG] Permanent 400 Bad request on KoboldAI Horde

### ISSUE THREAD

**Issue by Teashrock** [SillyTavern/SillyTavern#1031]
**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
Whenever I try using any model of KoboldAI Horde, it gives me 400 Bad Request error.

**To Reproduce**
1. Go to ST
2. Connect to whatever KoboldAI Horde model
3. Try to send send any request to it
4. Get a 400 Bad Request thrown at your face

**Expected behavior**
Getting output as a response to input on KoboldAI Horde models.

**Screenshots**
![Screenshot_20230827_120849_Termux](https://github.com/SillyTavern/SillyTavern/assets/12483854/22140d8a-8210-4312-857f-25326a6d9d3a)

**Tablet:**
 - OS/Device: Android 13/Samsung Galaxy Tab S6 Lite
 - Environment: local
 - Node.js version: v19.9.0
 - Browser: Chrome
 - Generation API [e.g. KoboldAI, OpenAI]
 - Branch: release, 1.9.7 (e4d1463a)
 - Model: Whatever

**Additional context**
None

**Comment by Cohee1207** [comment]
I think 512 tokens is max value for Horde response length. You have set 700

**Comment by Teashrock** [comment]
@Cohee1207 
Yes, I've already figured this out by lowering the output. Thanks, issue closed.
