### ISSUE TITLE
[Feature Request] Make sortorder of tags independent of case

### ISSUE THREAD

**Issue by Woisek** [SillyTavern/SillyTavern#1034]
Just a quickie I noticed just now.
The tag are sorted alphabetical ascending which is perfect. But I noticed, that it differences between the case.
So, if I have a list of tags, all beginning uppercase, then a tag with lower case will be on the end of the list.
Is it possible to make this independent of the tag case, please? 🙂

**Comment by Cohee1207** [comment]
Okay.

**Comment by Woisek** [comment]
Many thanks! 👍
