### ISSUE TITLE
[BUG] Edit button occasionally not working 

### ISSUE THREAD

**Issue by Ktrcoyote** [SillyTavern/SillyTavern#1036]
**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes
**Describe the bug**
Sometimes the edit button doesn't respond. You either need to refresh the page or generate more text to fix.

**To Reproduce**
I don't know. It seems random, but is more frequent with longer conversations.

**Comment by Cohee1207** [comment]
Please fill out the entire bug report template. We're missing some critical information
