### ISSUE TITLE
[Feature Request] Security Settings

### ISSUE THREAD

**Issue by nacho00112** [SillyTavern/SillyTavern#1038]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
No, i believe that would be difficult

**Is your feature request related to a problem? Please describe.**
[Yes]

**Describe the solution you'd like**
Being able to set the access to the server to determinated IPs and passwords both specified by the user.
This become useful when SillyTavern is running in a public url for some reason,
I think having both methods with IPs and passwords would be the ideal
Because with passwords you can share access to a different IP but with IPs it's easier to access and is more secure

**Describe alternatives you've considered**
There's not option for this in SillyTavern that i'm aware of

**Additional context**

**Comment by wereretot** [comment]
@nacho00112 This already exists with whitelist.txt using basicAuthMode.

**Comment by Cohee1207** [comment]
Please see the documentation on how to setup public instances:
https://docs.sillytavern.app/usage/remoteconnections/
