### ISSUE TITLE
[Feature Requests] Insert empty message. Message ownership change. Convert to group.

### ISSUE THREAD

**Issue by Yuugirihime** [SillyTavern/SillyTavern#104]
**Hello, thank you very much for your work!** I would like to suggest a few features that you might find useful:

1. "Insert an empty message". It seems that this was done on a classic tavern or one of its forks, I don't remember exactly, but it was an extremely useful stuff :)
2. Based on the previous message, it will be useful to choose who sent any selected message, AI or you.
3. "Continue this chat as a group chat" - the feature I dream about! :) Transfers this chat with the bot to the group chat mode, where you can add another bot.

Thank you for reading this text!

**Comment by RossAscends** [comment]
1. you can always send an generation request without providing additional user prompts. It will not display in chat of course, as nothing was added. If you wish to add a user message into the chat without any meaningful content, you can try just typing a period and sending that.
2. to clarify, you want the ability change the entity (change the name and avatar) that made any given message in chat? 
3. dynamically switching between individual chat and group chat is not currently supported, and could be difficult as the two things are stored in different ways. you CAN make a group chat with only one bot to start..and add/remove other bots later whenever you like, but it needs to be a 'group chat' from the beginning to do so.
