### ISSUE TITLE
[Question] Unlink world from character 

### ISSUE THREAD

**Issue by Woisek** [SillyTavern/SillyTavern#1040]
Sorry to ask this maybe stupid question but ... how do we unlink a world info from a character? 🤔
When a character has a WI linked, I haven't found a way to unlike it, just change it. Any hint on that, please?

**Comment by Cohee1207** [comment]
Pick a character 
"More..." dropdown 
"Link lore to card" (don't remember the name by heart)
Unselect the selection

**Comment by Woisek** [comment]
Ah ... there it is! 😳 Many thanks

But, wouldn't it be better then to always keep this "Select a World Info file for" popup? Because editing the world info is done anyway via the WI icon, so ... I guess it would help prevent the 'problem' that I had with it finding it and it would be more consistent logically wise. IMHO. 🙂

Thanks again for the hint. 👍
