### ISSUE TITLE
Autobalance for Italics/Quotes when AutoFix Markdown is selected

### ISSUE THREAD

**Issue by akexter** [SillyTavern/SillyTavern#1041]
Currently, some models will do the following when replying and prompted to "italicise narration/actions/blocks of text between dialogue":

```
*blah blah blah narration.

blah blah blah more narration.*
```

This is an issue as italics do not cross line breaks in markdown formatting, which means when AutoFix Markdown is selected, the rest of the message gets affected and messed up. This only happens in the case when there are two paragraphs of narration or actions, so two things need to be added:

1. When a line break is sent through and there is an open asterisk at the start of the line, insert an asterisk before the line break
2. If a line ends in an asterisk, and there is no asterisk at the start of the line, insert an asterisk at the start of the line.

This same function could be applied to quotes, although I don't think I've ever seen a model fail to quote something properly.

Adding to this, there would also have to be something for the case of:

```
*blah blah blah narration.

blah blah blah more narration.

blah blah blah even narration.*
```

For 3+ lines of text that needs to be italicised.

**Comment by Cohee1207** [comment]
Added in the latest release
