### ISSUE TITLE
[BUG] We lost swipes

### ISSUE THREAD

**Issue by nothingsuspiciousright** [SillyTavern/SillyTavern#1046]
Hello, mates.
It seems swipes function was broken somewhere in the last updates; we can't swipe anymore while we generate a new response, so we can't read the previous AI's output while generating another in background -> all the process takes more time.
Can it be fixed?

**Comment by Cohee1207** [comment]
It was intentional because it causes conflicts with the "continue" function and causes data corruption. So swipes on generation have to be disabled as if during streaming.

**Comment by nothingsuspiciousright** [comment]
Man, this sucks... Do you plan to return this function?

**Comment by Cohee1207** [comment]
I need to plan it carefully so it doesn't break something else (last time it was overwriting the last swipe with a continue).
But sometimes the sacrifice needs to be made. Is streaming not an option in your case?

**Comment by Crozzwise** [comment]
I just updated from an older version. Generating a new message while reading previous ones was a critical feature for me, no other feature was worth loosing that functionality over. Without it you just halved(or worse) the speed I can use ST with. What am I supposed to do, copy/paste the old message first? At that point I'd be better off with a basic webui and a text box.

And assuming everyone can just switch to streaming is a horrible development approach.

**Comment by Metalhead33** [comment]
I don't get it, swipes and streaming always worked well for me. What gives? I guess I'll just abstain from updating for now.

**Comment by KurLance** [comment]
I registered just to write this.

I never use the "continue" function.
And I always use "swipes".

I'm just used to generating and viewing large texts via swipes, leisurely reading and editing them, instead of constantly chatting in real time streaming in small pieces
I can use streaming mode... But I don't want to,

I can only ask you to fix this, please?
