### ISSUE TITLE
[BUG] llama.cpp special token handling

### ISSUE THREAD

**Issue by mll59** [SillyTavern/SillyTavern#1049]
> **Warning**. Complete **all** the fields below. Otherwise, your bug report will be **ignored**!

**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
Using koboldcpp: "< /s >" (without the spaces) in Separator field of Instruct Mode settings doesn't get converted to a single EOS token but to 3 separate tokens (829 "</", 29879 "s" and 29958 ">") encoding the 4 character string. This occurs for example in the Vicuna 1.1 Preset.
Also, when using the Token Counter, the string </s> is treated as a string (resulting in general in 3 tokens) instead of as a single EOS token.
Tokenizer used is Sentencepiece(LLaMA) (or Best match since I'm using Llama-2 based model).

Oops: just realized that this is most likely a koboldcpp bug, not a SillyTavern bug???

**To Reproduce**
1. Start koboldcpp with --debugmode parameter and some model, e.g. vicuna-13b-v1.5-16k.ggmlv3.q6_K.bin.
2. Have a few question/answer rounds.
3. Look at the input token dump from koboldcpp.
4. Note that the separator is not a single EOS token but 3 tokens, as described above.

**Expected behavior**
The separator should be a single EOS token, not 3 tokens that encode the string "</s>"

**Screenshots**

**Logs**

Providing the logs from the browser DevTools console (opened by pressing the F12 key) or SillyTavern command line window will be highly appreciated.

**Desktop (please complete the following information):**
 - OS/Device: Windows 11
 - Environment: local, koboldcpp
 - Node.js version (if applicable): [run `node --version` in cmd]
 - Browser chrome
 - Generation API KoboldAI
 - Branch release
 - Model: Not model specific, but e.g. use vicuna-13b-v1.5-16k.ggmlv3.q6_K.bin.

**Additional context**

**Comment by Cohee1207** [comment]
> Oops: just realized that this is most likely a koboldcpp bug, not a SillyTavern bug???

I think so. Because we don't tokenize stop strings for Kobold, and send them as plain text. The conversion to token ids is done on the Koboldcpp side.

**Comment by mll59** [comment]
You are right. I should have checked better.
Found this: https://github.com/ggerganov/llama.cpp/issues/1812
Special token handling is a new feature under development at llama.cpp.
