### ISSUE TITLE
[Feature Request] Use something besides commas for random tag separator, and add message count based choices

### ISSUE THREAD

**Issue by Disgustiosa** [SillyTavern/SillyTavern#1055]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
Yes, having the separator for the random tag be a comma shuts out what would otherwise be endless possibilities.

**Describe the solution you'd like**
The separator should be something uncommon in writing (perhaps "|") rather than a comma.

I have been experimenting with the random tag a lot to make more complex cards. I've realized it can be extremely useful for fitting more ideas into a smaller context size, but the fact that the random choices I provide cannot include commas is frustrating. I would like to be able to do things like having entire example messages be selected at random, allowing an essentially infinite amount of example messages which can drastically change results for each swipe (which can be great for some characters).

Additionally, it would be amazing to have certain choices only be available before or after a certain number of messages have been sent in the chat. I'm picturing something similar to the Automatic1111 format. Example:
{{random:He does a backflip.[:5]|He does a frontflip.[3:]|He sits down.}}
With this, for the first three messages there would be a 50/50 chance the text would be either "He does a frontflip" or "He sits down". The fourth message (maybe also the fifth, no idea if the message counts would be inclusive or not) would be guaranteed to be "He sits down" as it is the only option. And then from the 5th onward its 50/50 between "He does a backflip" and "He sits down".

Maybe the average person wouldn't use this, but I can assure you if I got my hands on something like this I would make some insanely complex bots with it. It's a relatively small change that opens up endless possibilities.

**Comment by Cohee1207** [comment]
Alternative syntax for random implemented:
`{{random::1::2::3}}`
