### ISSUE TITLE
[Feature Request] Intelligent chat truncation for ChromaDB / Smart context

### ISSUE THREAD

**Issue by stho90** [SillyTavern/SillyTavern#1056]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I am using SillyTavern in v1.9.7 from the release branch and the last version of SillyTavern-extras. My settings for the smart context are:
- Replace non-kept chat items
- Recall only from this chat
- Sort memories by date
- Keep 10 messages
- Number of ChromaDB memories to inject: 2
- Max length for each memory pulled from the history: 1024
- Max length for each memory pulled from imported text: 1024

I am using a model that supports 16k token. While i discovered a strange behavior of my RP char, i looked into the console output and detected that only the last 10 messages will be sent. I am using only 120-160 tokens output for the model to store as many messages as possible into the "hot memory" (part of the context that will be sent for each request). Only sending 10 messages because of the smart context settings (keep 10 messages) is a waste of free possible tokens that the 16k model supports. Maybe this could be handled more dynamic?

Here is my request:
Do you think its possible to add a feature that only truncates the chat (that is sent to the model) if the sending context will be expected to be bigger than the models allows? And only then, inject the messages from ChromaDB?
It would help not to waste the free available tokens. A calculation of the size of each message could be stored as part of the meta data for each chat message, if you want to be that accurate. In the smart context settings, it could be possible to give a percentage of tokens that should always be free (to handle wrong token count).

**Describe alternatives you've considered**
Or at least, add a hint to the settings of smart context to understand the implication of each setting. (Example for "How many original chat messages to keep" could be: _Limit the number of message that will be sent to the model. Previous chat messages will be skipped_)

Another alternative would be to update the wiki. In your wiki here (https://docs.sillytavern.app/extras/extensions/smart-context/), there is the following message: 
`Once the chat has accumulated 10 messages, it will begin recording all messages into the database, and recalling messages as needed.`
There is not information about artificial limiting the sending messages to that amount. Its Just telling me that it starts to store the messages in the database. The only containing reference that could explain this is not clear enough: `By default, ChromaDB will keep as many recent natural chat history messages as specified in the slider. Any messages beyond this amount will be removed from your sent prompt`

**Additional context**
n/a

**Comment by Cohee1207** [comment]
No improvements are currently planned for ChromaDB / Smart Context.
