### ISSUE TITLE
[Feature Request] Card Deck System

### ISSUE THREAD

**Issue by Elthial** [SillyTavern/SillyTavern#1058]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**

Yes, I would like a fast and intuitive way of creating scenarios with characters and multiple characters without having to rewrite multiple character cards to fulfil the scenario. I would also like to take advantage of some of the work done in describing other characters, locations or scenarios without having to copy and paste that information.

The problem is character cards are not just character cards but also contain location and scenario information which makes it difficult to place that character in a different situation.

**Describe the solution you'd like**

I'm proposing a change or addition to the character card system by seperating into at least three card types.
* Character
* Location
* Scenario

A Scenario card can be something like "Duel" - "Two rivals engage in a one on one dual to the death".
The scenario can specify the number of characters and locations allowed.
Restrictions can be added as recommendation but allow override.

A location card can be something like a room with its own description or perhaps superlocation that contains multiple rooms with notes on how to traverse between them and whether that room is public, private or hidden.

A character card is a cutdown version of the current character cards with just the characters physical, mental and material descriptions but minus any alternative greetings or current situation information.

The envisioned usage is to be able to start a new chat.
This chat would be a blank chat without any characters, the old cards could be dragged and dropped to maintain original functionality. (Behaving as scenario cards with built-in location and character info)

The interesting part comes with the new cards.
Drag and drop the "Duel" card down, it shows up visually with it's description and graphic but has imprints for the missing location and character cards to be dropped into.

Depending on what cards you drop down you can create:
"Darth vader" and "Obi-Wan" on "Deathstar landing bay" duel
"Neo" vs "Agent Smith" on "Subway station" duel
"Potter" vs "Malfroy" on "Hogwarts" duel
As well as "Master Chief" vs "Kirby" on "The orient express"  duel

Obviously this can become pretty powerful and allows the community a big reusability component for creating new chats.

The core functionality is based around starting with a new Scenario card type which accepts multiple {{ Character }} and {{ Location }} card types which can be attached to the card. 

Drag and drop seems the most intuitive as i'm envisioning a table top card game approach but other UI features could be used.

**Describe alternatives you've considered**

I've also considered "Item" cards as an additional card type.
I've noticed people are starting to create lore books for items which change the chat behaviour "Love potions", "Teleporters", "Shrink Rays" etc etc and giving the same drag and drop functionality to a chat would be nice.

Additionally, since this approach leans heavily into the mental concept of "cards" I thought about allowing organisation of these cards into packs called "decks" since this seemed intuitive again.

**Additional context**
Scenario cards: A generic story telling device sepeated from fictional universe. A duel, a date, a wedding, a revenge scheme, a bank heist etc

Location cards: A character card for a location giving the AI a description of the location and things contained within. Normal room cards are a "room" which is a singular location but I'm pondering if having a superset location card with sub rooms might be useful for dungeon, murder mystery or any other scenario that requires room traversal.

"new" Character cards: Can remain similar, the new system just needs removal of information.

Existing charcter cards: Can just be added to the system as scenario cards with inbuilt, unchangable location and character as backwards compatibility. No changes would be needed.

---

I'm interested in feedback on this idea from the rest of the community.

**Comment by Cohee1207** [comment]
This is essentially a use for utility world info / lorebooks. By making entries constant you can switch certain parts of the card's content using the WI/lore selector. Globally active WI would apply to all characters, and embedded lores would apply only to one character.

**Comment by Elthial** [comment]
It's functionally possible to implement a number of ways, the idea was less about the mechanics of how it works and the intuitive presentation to the end users. Most people understand the concept of card stack as per board games vs tag editing and attaching multiple lorebooks.

It's really a suggestion to make the concept more user accessible.
