### ISSUE TITLE
[Feature Request] Add Dropdown Model select for Mancer

### ISSUE THREAD

**Issue by EliEron** [SillyTavern/SillyTavern#1059]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
Currently to use a Mancer model you have to manually copy the API endpoint from Mancer's website. Which is inconvenient if you are changing models frequently to compare them or due to one model handling certain situations and scenarios better than another. Especially now that Mancer has 5 different models to choose from.

It also means you have to check the site regularly to know when a new model has been added.

**Describe the solution you'd like**
Mancer does have an API endpoint that exposes all of the models on the site and their IDs, costs, and the like. Which is located here:
https://mancer.tech/internal/api/models

And the API URL is predictable:
https://neuro.mancer.tech/webui/{{MODEL_ID}}/api

Using those two things it should be trivial to add a dropdown to select a model which would also get auto-updated when new models are added. I could potentially do it myself but I've not familiarize myself with the code yet so I figured I'd make a feature request first.

**Comment by Cohee1207** [comment]
I've talked to the mancer dev about this. We will figure it out.
