### ISSUE TITLE
[Feature Request] How to add alternative chat APIs

### ISSUE THREAD

**Issue by TNT3530** [SillyTavern/SillyTavern#1063]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
I host an API for language models and SillyTavern support would make adoption and usage much more streamlined

**Describe the solution you'd like**
A simple explanation of the steps required to add a backend API to SillyTavern, or a way to manually add HTTP headers

**Describe alternatives you've considered**
Currently myself and other users implement a Discord chatbot or other method of prompting

**Additional context**
Even an option to add additional http headers to the requests would be enough, as my api is standard Ooba but with an api key expected

**Comment by Cohee1207** [comment]
Related: #1066

**Comment by Cohee1207** [comment]
The feature in question has been merged into staging. To begin using this feature you need to delete your config.conf and restart the ST server to have it recreated with a new custom headers object. Then you can start adding your custom headers in the config.conf file. One more restart may be needed to pick it up.

**Comment by TNT3530** [comment]
Works great!

For those wondering, formatting for entries is
`
{
	hosts: [
		"<url>"
	],
	headers: {
		<header>: "<value>"
	}
}
`
