### ISSUE TITLE
[BUG] Kobold generation works, but never gets streamed/passed to SillyTavern

### ISSUE THREAD

**Issue by kalomaze** [SillyTavern/SillyTavern#1065]
**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes, but the ones I looked at seem unrelated.

**Describe the bug**
Sometimes, when I queue up a generation, I can notice it in kobold generating. However, when it finishes, the output never gets passed to SillyTavern. It's present in the console for koboldcpp, so I can just copy the response and paste it in even though the streaming failed, but it's weirdly inconsistent and I'm not sure why it happens. 

**To Reproduce**
1. Use koboldcpp latest version with latest SillyTavern (was happening before latest update days ago)
2. Generate until you see kobold generating tokens that aren't streaming or appearing in SillyTavern. Stopping works, and the generation is present in the cmd console.

**Expected behavior**
Consistent generation behavior that doesn't require me to stop and requeue or copy paste the kobold window. 

**Desktop (please complete the following information):**
 - OS/Device: Win 11
 - Environment: local 
 - Node.js version (if applicable): v18.16.1
 - Browser: Chrome
 - Generation API: koboldcpp API
 - Branch: release
 - Model: mythomax 13b
 - 
**Additional context**
Strangely, it only happens on my laptop. GPU driver version on there is from 8/14. My other PC is using a driver version from March 8th. Both machines are NVIDIA GPU equipped. Is this a known issue where modern driver versions are less reliable or fail to stream to ST?

**Comment by Tacx79** [comment]
Same issue here, for me it happens in group chats (didn't test normal chats), tavern running on PC, koboldcpp with streaming running on both PC and laptop, driver version on both is 531.41. I noticed it mostly happens after longer prompt processing or when chat stays idle for some time and you swipe the message, message for one character stays empty and after model stops generating, the chat moves to the next character leaving the empty message

**Comment by Dekimori** [comment]
Hi, similar on MacOs. Macbook pro m1 pro 16gb
Reply generating in terminal and i see it for a second, after that dissapear and starting new cycle. After 5 atempts terminating. Nothing appear in Tavern web interface. I made an examle on a screenshot, as it is impossible to copy script within a second.
<img width="1273" alt="screen 18:10" src="https://github.com/SillyTavern/SillyTavern/assets/50846494/5c1e0fb5-12c5-44b1-a3ba-41d1894454fc">

**Comment by Cohee1207** [comment]
It is cut because the model generated the text as "You". As you can tell, it's not exactly what the program expects.

**Comment by Cohee1207** [comment]
Check if "Always add character's name to prompt" is enabled in formatting settings. If not - enable it.

**Comment by Dekimori** [comment]
> Hi, similar on MacOs. Macbook pro m1 pro 16gb Reply generating in terminal and i see it for a second, after that dissapear and starting new cycle. After 5 atempts terminating. Nothing appear in Tavern web interface. I made an examle on a screenshot, as it is impossible to copy script within a second. <img alt="screen 18:10" width="1273" src="https://user-images.githubusercontent.com/50846494/276244513-5c1e0fb5-12c5-44b1-a3ba-41d1894454fc.png">

Upd.: Setting "Always add character's name to prompt" don't help. Still generating reply, after that just dissapear from terminal and start new attempt in cycle. If run koboldcpp build in web ui - reply appears, but for some reason much slower.

**Comment by Cohee1207** [comment]
What is "corrupted paradise" exactly in your case? Is that some multi-character card? It gets trimmed because your model gets confused and generates for "You". Once again I'm asking you to take a closer look at the screenshot you've posted.

**Comment by Dekimori** [comment]
> What is "corrupted paradise" exactly in your case? Is that some multi-character card? It gets trimmed because your model gets confused and generates for "You". Once again I'm asking you to take a closer look at the screenshot you've posted.

Its a name for {{char}} card i just donwloaded to test.  "You" is for {{user}}. Now it's not terminating if i do input first (not just push generate prompt), the text is there in the terminal but not appearing in web ui (it keeps waiting forever). I used Horde earlier, it just works, perhaps im too dumb for this.
Thx for your time anyway!

UPD: recreated same on different pc with windows, works without any bugs. Seems it something with silly/kobold files or required tools like node, idk. Silly on windows even looks different, I just abbandon it on mac.
