### ISSUE TITLE
[Feature Request] A Token Counter for each AI reply

### ISSUE THREAD

**Issue by ahmed-elj** [SillyTavern/SillyTavern#1068]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

Description:
much like every other fields that has a token counter on top of it.
Add a token counter for each AI reply below the timer counter

![vivaldi_fjFT4uaICU](https://github.com/SillyTavern/SillyTavern/assets/31710770/219ec305-2802-4a69-bd6e-a2989260b17f)

To provide more information about your current budget spending.

**Comment by Cohee1207** [comment]
Interestingly enough, I thought about the same thing just a couple of minutes ago!

**Comment by ahmed-elj** [comment]
oh and if you could add on the hover panel that shows X t/s (token per second), can you?

**Comment by Cohee1207** [comment]
If you want to display token counts on existing messages after enabling the toggle: open a debug menu and execute "Backfill token counters"

**Comment by Cohee1207** [comment]
Currently "X t/s" display has a bug that ramps up the token rate on continuing. I'm not sure how to handle it yet, but will make something out

**Comment by ahmed-elj** [comment]
yeah, perfect!
