### ISSUE TITLE
[BUG] Possible race condition on cold start from slow disk (HDD).

### ISSUE THREAD

**Issue by valden80** [SillyTavern/SillyTavern#1071]
**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes.

**Describe the bug**
When I load ST for first time (cold start from HDD) and open page in the browser, it's seem's to try and start loading chat data before the all system libraries is loaded and ready for it (option "Auto-load Last Chat" is on). 
As the result previous chat is not load, ST show pop-up error about "can't access character files, can't save config" - or something like this.
After reloading page (F5 in the browser) all loaded without any errors - GUI, character, chat - all (this time it's load from memory cache so it's fast enough).

**To Reproduce**
1. Cold start ST from the HDD.
2. See error pop-up and chat is not loaded.

**Expected behavior**
Normal loading, without need to reload page for the full start.

**Screenshots**
Can't catch it - in cold start screenshot program reacting too late.

**Logs**
No error in the logs.

**Desktop (please complete the following information):**
 - OS/Device: Manjaro Linux
 - Environment: local
 - Node.js: version 20.2.0
 - Browser: Firefox
 - Generation API: Oobaboga
 - Branch: staging
 - Model: any local

**Additional context**
My setup of AI stuff (not only ST and Ooba) on the separate HDD, as it's need really many space for models. And I don't really mind to one time waiting for startup.

Also I'm not sure, but maybe it's also kill or mess my ST configuration file once - all options dropped to default, including the setup of  regexp and quick reply extensions (most annoying - lost good config for them).

**Comment by Cohee1207** [comment]
What is the latest commit in your branch? I think I fixed this here: https://github.com/SillyTavern/SillyTavern/commit/44f88c61f
This should prevent saving settings before they are properly loaded.

**Comment by valden80** [comment]
I update every time before start, right now it updated about hour ago: dce959f72dc3aa9dd51afd244231fdd23c609058

**Comment by Cohee1207** [comment]
That must have been a very unfortunate turn of events, sorry about that. I adjusted the app init procedure to make sure that settings and characters are loaded before trying to auto-open a chat or auto-connect to an API.

P.S. You can restore lost settings from an automatic backup. Check out the /backups/ folder.
