### ISSUE TITLE
[BUG]Prompt manager bug when switching presets

### ISSUE THREAD

**Issue by randomtester01** [SillyTavern/SillyTavern#1074]
**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
When switching between presets in SillyTavern, the prompt manager can fail to load properly, leaving it just blank as per screenshot. This messes up insertion order, so that example messages are inserted after chat history, leading to the AI response being heavily impacted by Example chats no matter the actual chat history, which just wastes tokens. The rest of the prompts do seem to be inserted properly in order.

When prompt manager fails to load, tokens are not counted properly, leading to only chat history being accounted for, though this is a minor issue.
Reloading the page does fix the issue with prompt manager and example chats, but only as long as one keeps using the same preset, when changing presets again, this bug can occur again.

Having no example messages negates effects from this bug entirely, though it is not tested what it would do with presets that use prompts.

Note that prompt manager does not always bug out when switching, it is not clear what is the logic behind some presets being not affected by the bug, when others are, there does not seem to be any apparent rhyme or reasoning behind this. Its likely this can greatly complicate reproduction of the issue. 

**To Reproduce**
1. Start a chat with a preset selected, bug most evident if using a character with example chats.
2. Switch between presets, if prompt manager remains blank when having selected one, the bug has occurred. 
3. (optional) Receive a message from the AI with the bugged preset selected, example chats if they are present will be inserted after chat history in command prompt, which is unwanted behavior.

**Expected behavior**
A simple switch between presets, with prompt manager loading properly, and example messages being inserted before chat history as is default. Plus tokens being counted properly. As per first screenshot.

**Screenshots**

![image](https://github.com/SillyTavern/SillyTavern/assets/143759860/f0216874-9330-47f8-83ec-37c258dbe099)

![image](https://github.com/SillyTavern/SillyTavern/assets/143759860/589a15ac-5546-4b2d-af40-cc29de0e42c4)

![image](https://github.com/SillyTavern/SillyTavern/assets/143759860/bb0039a8-d448-4261-b6c3-fd9c37cdeb4d)

![image](https://github.com/SillyTavern/SillyTavern/assets/143759860/d8fecbc1-f0a7-4a8f-a26d-2e6880e9fb36)

**Logs**
Have no clue where to look for, as nothing springs up in either the browser DevTools console or cmd console regarding this bug.

**Desktop:**
 - OS/Device: Windows 10
 - Environment: [local]
 - Node.js version 19.1.0
 - Browser Firefoxn but most likely does not matter
 - Generation API [Claude, though not sure it matters for this bug.]
 - Branch [staging]
 - Model [Claude 2, but does not matter
 
 ** Additional Details**
None.

**Comment by Cohee1207** [comment]
Could you try this branch with the proposed fixes?
https://github.com/SillyTavern/SillyTavern/tree/prompt-manager-configuration-fixes

**Comment by randomtester01** [comment]
Seems to work properly now when switching presets. Prompt manager doenst go blank anymore.

**Comment by Cohee1207** [comment]
Thank you for checking! I merged the branch into staging now.
