### ISSUE TITLE
[BUG] Output Sequence has char limit of 100

### ISSUE THREAD

**Issue by practical-dreamer** [SillyTavern/SillyTavern#1076]
> **Warning**. Complete **all** the fields below. Otherwise, your bug report will be **ignored**!

**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes<-

**Describe the bug**
I have long string
String doesn't fit into field
how to .size++?

**To Reproduce**
Self Explanatory
![image](https://github.com/SillyTavern/SillyTavern/assets/78515588/0bb22f70-29a9-4029-92a4-0a34117611bd)

**Expected behavior**
Self Explanatory

**Screenshots**
![image](https://github.com/SillyTavern/SillyTavern/assets/78515588/3fc73ff7-6471-4233-ac02-f0a1134dd145)

**Comment by Cohee1207** [comment]
You didn't specify the version you use, but I see from the template that this is outdated. Update to have it increased

**Comment by Cohee1207** [comment]
Updated to 2000 characters in the most recent release
