### ISSUE TITLE
[Feature Request] Extensions: Default TTS character voice in Voice Map

### ISSUE THREAD

**Issue by Jasonnor** [SillyTavern/SillyTavern#1077]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
At present, every time you use a new character, the default TTS voice will be `disabled`, which needs to be set to a commonly used voice.

**Describe the solution you'd like**
Support default TTS character voice in Voice Map.

**Describe alternatives you've considered**
When switching to any new character, you don't have to select a voice every time.

**Additional context**
A possible interface design: add one setting to specify the default voice (it can be `disabled`). Thanks!

**Comment by Cohee1207** [comment]
Good suggestion, I can try implementing that, thanks.

**Comment by Cohee1207** [comment]
Added to staging. Feel free to try it out.

**Comment by Jasonnor** [comment]
@Cohee1207 
Thanks a lot, I just tested it, because the default voice of the character is still `disabled`, so I cannot receive the voice specified by `[Default Voice]`.
So I made some changes (#1081) to make it work, can you take a look? 👍

**Comment by Cohee1207** [comment]
Released.
