### ISSUE TITLE
[Feature Request] (v1.10) When using Mirostat, darken parameters that have no effect.

### ISSUE THREAD

**Issue by SabinStargem** [SillyTavern/SillyTavern#1082]
As I understand it, some parameters like temperature can change the results of Mirostat, while others do not.  It isn't clear to me which options can change output, so it would be nice if inapplicable parameters are shaded when Mirostat is enabled.  This would make it easier to tweak Mirostat.

**Comment by Cohee1207** [comment]
I need a list. I don't use Mirostat and have no slightest clue on its effects.

**Comment by SabinStargem** [comment]
AmbientXeno in a Reddit thread said they copied the following from...somewhere.  As ever, lack of documentation is bit a pain.  :P

> 
> AmbientXeno
> When mirostat is enabled, llama.cpp will sample new tokens in the following order: 1) Repetition penalties are applied 2) Frequency and presence penalties are applied 3) Temperature is sampled 4) mirostat is sampled Everything else is ignored. tau, eta, repeat-last-n, repeat-penalty, presence-penalty, and frequency-penalty parameters will affect generation.

Sorcy (Ycros?) on Discord also says that Rep Penalty and Temp are used, everything else ignored.  


This is all anecdotal information, unfortunately.  Hopefully, an expert will save the day on this topic.

**Comment by EliEron** [comment]
I'm far from an expert but skimming llama.cpp's [source code](https://github.com/ggerganov/llama.cpp/blob/afc43d5f82588d2ed71ea104e8262f5e5da13980/examples/main/main.cpp#L685-L736) (Which I imagine is also what AmbientXeno did) it does indeed look like their claims are correct.

When Mirostat 2 is active the following sampling methods are called:
`llama_sample_repetition_penalty`
`llama_sample_frequency_and_presence_penalties`
`llama_sample_temperature`
`llama_sample_token_mirostat_v2`

The following are all skipped:
`llama_sample_top_k`
`llama_sample_tail_free`
`llama_sample_typical`
`llama_sample_top_p`

Similar logic is found in text-generation-webui's [code](https://github.com/oobabooga/text-generation-webui/blob/4affa088214b59a8bbefbd0f956523a396486bd7/modules/sampler_hijack.py#L166-L176) where all samplers other than temperature is disabled when Mirostat is enabled.
