### ISSUE TITLE
[BUG] Copy char file naming broken

### ISSUE THREAD

**Issue by IkariDevGIT** [SillyTavern/SillyTavern#1084]
> **Warning**. Complete **all** the fields below. Otherwise, your bug report will be **ignored**!

**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**

**To Reproduce**
1. copy a character (via copy button)
2. copy the copy of the character (via copy button)
3. "char_1_1.png" comes out

**Expected behavior**
The copy of the copy should be named Miko_2.png, not Miko_1_1.png

**Screenshots**
![grafik](https://github.com/SillyTavern/SillyTavern/assets/90197782/5b1e803a-1a81-4e53-b6b6-c63190a88cc9)

**Logs**
not needed

**Desktop (please complete the following information):**
 - OS/Device: [e.g. Windows 11]: windows 10
 - Environment: [cloud, local]: local
 - Node.js version (if applicable): [run `node --version` in cmd]: v18.15.0
 - Browser [e.g. chrome, safari]: firefox
 - Generation API [e.g. KoboldAI, OpenAI]: not needed
 - Branch [staging, release]: Dev
 - Model [e.g. Pygmalion 6b, LLaMa 13b]: not needed

**Additional context**
not needed

**Comment by Cohee1207** [comment]
Should be fixed now
