### ISSUE TITLE
[BUG] Macro do not replaced in the custom stopping strings.

### ISSUE THREAD

**Issue by valden80** [SillyTavern/SillyTavern#1088]
**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
(For all data here, my avatar name "My_Avatar_Name" and character name - "My_Character")
In custom stopping string I have this:
``["\n{{User:}}", "\n{{Char:}}", "</s>"]``
When I look in the log of the ST console I see:
```
stopping_strings: [
   ...
    '\n{{User:}}',
    '\n{{Char:}}',
    '</s>'
  ],
```
And it's not stop generation at the new string beginning with ``My_Avatar_Name:`` as it should by the custom stopping string. 
Switching option "Replace Macro in Custom Stopping Strings" don't change anything.

**To Reproduce**
1. Setup custom stopping string as above.
2. Start generation.
3. Look in console.

**Expected behavior**
```
stopping_strings: [
   ...
    '\nMy_Avatar_Name:',
    '\nChar_Name:',
    '</s>'
  ],
```
And stopping generation when model produce "My_Avatar_Name:" or "Char_Name:" in the begin of the new string.
(I need to suppress too "chatlog happy" model behavior who add these to it's output quite often.)

**Screenshots**
Text console output.

**Logs**
No error in logs.

**Desktop (please complete the following information):**
 - OS/Device: Manjaro Linux
 - Environment: local
 - Node.js: version 20.2.0
 - Browser: Firefox
 - Generation API: Oobaboga
 - Branch: staging
 - Model: any local

**Additional context**
None.

**Comment by Cohee1207** [comment]
Sorry, but these are not valid macros. They should be like this:
```
["\n{{user}}:", "\n{{char}}:", "</s>"]
```
Notice the position of the colon. The capitalization of macro doesn't usually matter (these are case-invariant), but's better to have them uniform.

**Comment by valden80** [comment]
Yes, you are right, I'm sorry. 
I spent about a hour for testing before this reporting, and still missed it. Thank you for helping.
I'm feeling like idiot now. :)
