### ISSUE TITLE
[Feature Request] Multiple imagesets for a character (for example for different outfits)

### ISSUE THREAD

**Issue by Woipi** [SillyTavern/SillyTavern#1089]
I would love if it would be possible to create subfolders in the /characters/{charname} folder for different imagesets/outfits. Like for example /characters/{charname}/formal and /characters/{charname}/casual and then make these outfits easily selectable in the UI. Of course, the expressions addon should still work with this addition. Miku.gg has something similar implemented but has tied the outfit to a specific scenario. I would prefer if the outfit would be independantly selectable - similar to the background selection. 

This fantastic feature would also allow for so many possibilities. For example it would allow seperate image-sets for a certain mood like "very angry" where you possibly don't want the character to look very happy even if the classification model returned something like "joy". Or it would allow to display imagesets of the character with certain items like "backpack" or "weapon".

**Comment by Cohee1207** [comment]
This is already supported in the form of a per-character sprite folder override. Look into it and see if it fits your purpose

**Comment by Woipi** [comment]
Thanks for this suggestion. It works pretty well and does the job indeed. Maybe in the future, something like a dropdown menu with one character's available sets could be implemented to speed up the sprite-selection process. It would also give a nice overview over the existing sprite-sets for one character.

**Comment by Woipi** [comment]
A dropdown menu would it also make easier to change imagesets while being in a group chat (I'm really grateful btw. that the override only applies to the last active character).
![Select](https://github.com/SillyTavern/SillyTavern/assets/55447010/dc0ee725-25fb-4425-9d8c-ade0ec3ce0ba)

**Comment by Cohee1207** [comment]
You can create quick reply buttons for "costume" command to quickly change outfits.
https://docs.sillytavern.app/usage/st-script/#quick-replies-script-library-and-auto-execution
