### ISSUE TITLE
[Feature Request] Connection manager for WebUI and KoboldAI API endpoints

### ISSUE THREAD

**Issue by mtibke** [SillyTavern/SillyTavern#1090]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
If I'm running multiple instances of the TextGen WebUI or KoboldAI (see additional context) I have to manually change the URL every time I want to change to a different server. This is a bit annoying and prone to typos.

**Describe the solution you'd like**
Have a connection manager for the WebUI or KoboldAI API endpoints so that a user can easily switch between multiple servers for the same endpoint type. It would be great if we could configure an endpoint and then have a dropdown list from which we could select the endpoint server.

**Describe alternatives you've considered**
I'm not aware about any alternative solutions.

**Additional context**
I'm running the LLM API endpoints sometimes on my PC (RTX 4090) or on my server (GTX 1080) when the PC is switched off.

**Comment by Cohee1207** [comment]
Added a dropdown list for recent servers (5 at most). If you have the ability to test it in staging - let me know if that matches your expectations.

**Comment by mtibke** [comment]
I've tested it on staging and for me it was working fine and it matches my expectations. It's way easier now to switch between two or more hosts. Well done & thank you very much!

**Comment by aetherwu** [comment]
In addition to this feature, can SillyTavern automatically switch between endpoints? I've discovered that it could be the most effective way to avoid repetition after a certain period of time. Currently, I always have to manually switch my models in my TUI, which is time-consuming. However, it might be feasible to switch on SillyTavern between my local llm/mancer or other alternatives.

**Comment by Cohee1207** [comment]
@aetherwu 
Automatically switch based on what exactly? You can quicky switch between APIs with a slash command
