### ISSUE TITLE
I don't know where to put --api

### ISSUE THREAD

**Issue by PortalTom** [SillyTavern/SillyTavern#1096]
If you are using:
[oobabooga/text-generation-webui](https://github.com/oobabooga/text-generation-webui)
Make sure you run it with --api flag

My install of SillyTavern says the above, but I have no Idea where to put --api.
I'm assuming it's somewhere in webui.py, but where?
Thanks for any help.

**Comment by mtibke** [comment]
There are multiple ways to launch this. If you are using Windows you can create a batch file in **text-generation-webui** root folder (where the server.py file is) the with the following content:

```
@echo off
call python server.py --api
```

You can add more options if needed so you don't have to manually change it for every session:

```
@echo off
call python server.py --loader exllama --verbose --model <model-name> --listen-port 7862 --api --listen
```

Make sure you start the batch file in the correct virtual Python environment (Conda, Anaconda, etc.).

**Comment by Woipi** [comment]
Alternatively, you can load the interface, change to the "session" tab, select "api" and then press the "Save UI defaults to settings.yaml" button.
