### ISSUE TITLE
[BUG] Multiple Zoomed Avatars Overlapping on click

### ISSUE THREAD

**Issue by anmelus** [SillyTavern/SillyTavern#1097]
> **Warning**. Complete **all** the fields below. Otherwise, your bug report will be **ignored**!

**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
Users currently can click on avatars to open a zoomed view of the avatar. Clicking on multiple avatars overlaps them, with the most recent one being in front. To remove all zoomed avatars, users must click onto each one again. Issue is exacerbated with group chats.

**To Reproduce**
1. Open any chat
2. Click on your avatar to bring up the zoomed view
3. Click on the character in the chat's avatar to bring up their zoomed view
4. If you click on their character avatar again, your avatar will appear
5. If you click on your avatar, their avatar will continue to stay. You need to click your avatar a second time to get it to overlap.

**Expected behavior**
Whoever's avatar is clicked should appear. Zoomed avatars should be removed from the view.

**Screenshots**
As you select avatars, more divs appear. The divs will close if you select the avatar that is already zoomed in. 
[Link](https://prnt.sc/778J6XMZ91D1)

**Logs**

Providing the logs from the browser DevTools console (opened by pressing the F12 key) or SillyTavern command line window will be highly appreciated.

**Desktop (please complete the following information):**
 - OS/Device: Windows 10
 - Environment: local
 - Node.js version (if applicable): v18.13.0
 - Browser brave
 - Branch staging, release

**Additional context**
I fixed this on my side. I will submit a pull request to staging. https://github.com/anmelus/SillyTavern_anm/commit/fd33bb65fce01f226106f7f2d02ae13dd06bf218

**Comment by Cohee1207** [comment]
There's a use case for opening multiple avatars and aligning them manually with moving UI.

**Comment by anmelus** [comment]
Changed to include a check if power_user.movingUi is enabled, let me know if it needs more work.
