### ISSUE TITLE
[Feature Request] Multiple profile pictures

### ISSUE THREAD

**Issue by IkariDevGIT** [SillyTavern/SillyTavern#1099]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
I really like my own oc, i have multiple pics of her(they are not with different emotions, they are different poses, or clothing... and so on). Currently you cant have multiple pfp's and easily swap them around.

**Describe the solution you'd like**
I would like 2 buttons to easily swap the pfp's around

It also would be very nice, if the "big" version of the pfp(the one that appears when you click a pfp) would be updated on swapping the image.

You could introduce maybe a folder or some sort of gallery where the pics are stored in your Sillytavern folder.

**Describe alternatives you've considered**
You can do it manually but its not really user friendly, and it takes long + overrides the chars pfp.

**Additional context**
Concept:

![Inkedsadwdgtnhfdas_censored_via_10015_io](https://github.com/SillyTavern/SillyTavern/assets/90197782/c27e4a54-ceff-4dc3-a650-c4524eb794c3)

**Comment by Cohee1207** [comment]
Check this out: https://github.com/SillyTavern/SillyTavern/pull/987
