### ISSUE TITLE
[Feature Request] Scripting API Proposal

### ISSUE THREAD

**Issue by BasadoBased** [SillyTavern/SillyTavern#1106]
Greetings! First of all, great program. For a while I have been pondering what feature would take ST to the next level with the minimum amount of work required to implement. I thereby propose this scripting feature for your consideration. I have seen a lot of users requesting things that can't be done with LLMs alone, but are too small to justify adding each and every one into the program. I think such a system would in the long haul simplify the program while making it more extendable.

**What is it?**
The ability for users to create JS scripts and attach them to lorebooks and characters. Said scripts would have the capability to modify prompts and responses on the fly, extending the capabilities of LLMs.

**Uses**
Here is a non-exhaustive list of some of the things that could be done by bot creators with such a system:
- proper stat tracking systems (rpg style) 
- interactive games and combat systems that work consistently and with weaker LLMs
- more dynamic events based around time, for example a themed lore entry that is inserted during Halloween in real life, change mood based on time of day
- more complex dynamic events in general 
- optionally, functions to hook into the more off-to-the-side features of ST like generating an SD image at a specific time or manually setting the character expression based on some event

**Security**
Obviously, executing arbitrary Javascript presents a security concern. While I am not an expert on web security, it seems many sandboxing tools for JS are available. Here's one example, there are many: https://github.com/nyariv/SandboxJS

**API**
If this feature is considered, I can take time to write up a full interface proposal that would cover almost all bases, but the rough outline is that user scripts will define event functions, for example consider an onPrompt() function that takes the prompt as an argument and returns a new prompt as a return value. ST passes strings through these functions at the appropriate times. The size of an API that gives the creator wide control should be fairly small, I would estimate less than a dozen event functions and other functions for calling into ST.

**Handlebars?**
I find Handlebars.js to be limited to the point that it would expand the capabilities very little. 

That's all, thank you for considering this proposal.

**Comment by Cohee1207** [comment]
Not a big fan of sharing scripts with the characters. It could lead to ecosystem fragmentation. But we could work at improving the third party extensions API.
@city-unit developed a couple of plugins and also had some ideas to improve it. Mainly on how to share main functions with extensions.

**Comment by Cohee1207** [comment]
Scripting was implemented. Scripts are not shared with characters still, but there are QR preset JSON files that can be shared.
https://docs.sillytavern.app/usage/st-script/
