### ISSUE TITLE
[Feature Request] Add an option to append the bot's jailbreak to your current one without replacing it.

### ISSUE THREAD

**Issue by ahmed-elj** [SillyTavern/SillyTavern#1107]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

I found out that adding small information about the character in the jailbreak can alter the AI response very much, but including a whole new jailbreak can change your personal preset, and everyone has their own Jailbreak style that they don't want to change.

Solution:
By adding a checkbox under Jailbreak text-box In the Advanced Character Definitions, we can add a small details for the ai in the jailbreak to respond a certain way. 
![vivaldi_TsDIZhwjjn](https://github.com/SillyTavern/SillyTavern/assets/31710770/bbbbfda6-2cd3-4db4-9f8c-5549cbd66411)

by doing this every shared bot can include important information to your current jailbreak. and since author's note is not sharable (yet).

**Comment by Cohee1207** [comment]
Already possible. Use `{{original}}` replacement macro. It will insert JB from a prompt manager in its place.

**Comment by ahmed-elj** [comment]
Sorry, but i don't see this in the list of macros in the docs.
is there any other place to know these macros?

**Comment by Cohee1207** [comment]
You can see it in a placeholder of characters jailbreak when you clear it of all text. Maybe should also be in the doc, you're right

**Comment by Cohee1207** [comment]
Added to docs.
