### ISSUE TITLE
[Feature Request] Custom translation provider

### ISSUE THREAD

**Issue by toby3d** [SillyTavern/SillyTavern#1111]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
Having [discovered a way to use the DeepL translation without a token](https://github.com/OwO-Network/DeepLX) I've run into the fact that I can't change the URL of an instance through the interface, as is possible with the Libre provider. Even changing the IP `deepl.com` to `localhost` via hosts doesn't change the fact that SillyTavern still refuses to make translation requests without a token and under the hood makes requests to the `/v2/translate` URI rather than to `/translate` and non-standard port `:1188` as DeepLX expects.

**Describe the solution you'd like**
Add a button similar to Libre provider, allowing to change the URL for all translation requests. Soften the API key requirement and make it optional if a non-standard URL is specified. 

**Describe alternatives you've considered**
This is a very messy fix that ignores the presence of a token using a hard-coded local API URL. I have very little experience in JavaScript, so I did the following changes.

Remove these lines:
https://github.com/SillyTavern/SillyTavern/blob/da7bf636467c9477b09f47f1f60bccd67228d000/public/scripts/extensions/translate/index.js#L200-L202

Then, update code in this section:
https://github.com/SillyTavern/SillyTavern/blob/da7bf636467c9477b09f47f1f60bccd67228d000/server.js#L3862-L3907

To these:
```javascript
app.post('/deepl_translate', jsonParser, async (request, response) => {
    const text = request.body.text;
    const lang = request.body.lang;

    if (!text || !lang) {
        return response.sendStatus(400);
    }

    console.log('Input text: ' + text);

    try {
        const result = await fetch('http://0.0.0.0:1188/translate', {
            method: 'POST',
            // NOTE(toby3d): DeepLX uses JSON payload, also 'source_lang' is required
            body: JSON.stringify({
                text: text,
                source_lang: 'auto',
                target_lang: lang,
            }),
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json',
            },
            timeout: 0,
        });

        if (!result.ok) {
            return response.sendStatus(result.status);
        }

        const json = await result.json();
        console.log('Translated text: ' + json.data);

        return response.send(json.data);
    } catch (error) {
        console.log("Translation error: " + error.message);
        return response.sendStatus(500);
    }
});
```

**Additional context**
I have a lot of experience in Golang and by making small changes to the DeepLX source code I can achieve to duplicate the official route behavior without changing the API in SillyTavern: accept QueryParams instead of JSON, painlessly ignore the token header, require only `target_lang` and `text` and return the translation not in the `data` string but in the `translations` array as SillyTavern expects. With this in mind, you won't need to make the changes I described above, except to allow setting your own URL instance via interface (for example, to `https://localhost:1188/v9999/translate`) and not require the token necessarily, allowing requests without it.

SillyTavern's behavior may still need to be slightly adapted to the translation server's responses: this method bombards the provider with requests quite aggressively and may encounter a 429 status. It would be nice to take into account the provider timeout headers in some way, but I'm not sure how.

**Comment by Cohee1207** [comment]
It basically could be a separate API provider. Since it relates to DeepL only by name.

**Comment by toby3d** [comment]
> It basically could be a separate API provider. Since it relates to DeepL only by name.

Like "Custom" provider?

Might also need to build in a simple payload editor as already in the prompt settings, so I can explicitly specify the form of the JSON body for the requests. For example:
![изображение](https://github.com/SillyTavern/SillyTavern/assets/5412322/aa225fa7-f746-40b4-855b-f1a2d6e8b299)

I don't think there are providers unable to accept JSON in favor of some other channel like form or query.

**Comment by Cohee1207** [comment]
This looks okay, I think.

**Comment by toby3d** [comment]
In such a case, you should also provide a response protocol between the provider and SillyTavern. Either something fixed ("I expect this in this form"), or something customizable ("specify what to expect and in what form"). And not only for successful responses, but also for errors.

If I need to test all of this for you -- let me know. As I said, I have enough experience in Golang to customize DeepLX to meet SillyTavern's expectations, but not the other way around.

**Comment by Cohee1207** [comment]
I didn't bother with custom translation providers and brought DeepLX as a native provider. It's now on staging, feel free to test it out. I tried it once and it worked.

**Comment by toby3d** [comment]
> I tried it once and it worked.

Can confirm.

I think saving the input value in the popup field instead of resetting it completely every time a popup is opened would be useful. I suspect that this is a privacy issue for SillyTavern instances that look outward to the internet and information about the URLs it accesses is not disclosed for this reason. But this is a topic for a separate issue.
