### ISSUE TITLE
[BUG] Mobile UI Broken for Group Chats in 1.10.2 

### ISSUE THREAD

**Issue by Nyanana** [SillyTavern/SillyTavern#1117]
**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**

When using SillyTavern on an android mobile device, the group chat becomes unusable whenever a character replies, with the chat being pushed off the screen.

**To Reproduce**
1. Open silly tavern on a mobile browser in android
2. Start a new group chat with a couple of characters
3. Talk and wait for them to reply
4. Observe

Observation: Group chat becomes unusable as the chat has gone off screen.
Also seems to happen when creating the group chat.

Does not occur for 1 on 1 chat

**Expected behavior**

Chat remains on screen

**Screenshots**

![Screenshot_2023-09-08-13-44-23-72_3aea4af51f236e4932235fdada7d1643](https://github.com/SillyTavern/SillyTavern/assets/144454315/682fcd66-4858-4f31-9073-2ed9f3d5f538)

**Comment by Cohee1207** [comment]
Thank you, this has been fixed in both branches. Please git pull to get an update.
