### ISSUE TITLE
[Feature Request] Add {{char}} and {{user}} formatting to Example Separator & Chat Start

### ISSUE THREAD

**Issue by kalomaze** [SillyTavern/SillyTavern#1120]
<img width="500" alt="image" src="https://github.com/SillyTavern/SillyTavern/assets/66376113/31e8452d-bdec-4497-94d2-4fb8a66530ce">

I'm trying to make a preset that replicates 1.9.7 style SillyTavern prompting. This is making that not possible; {{char}} and {{user}} are not converted when you add them to the example separator.

**Comment by kalomaze** [comment]
This also applies to Chat Start; as it currently stands, you cannot recreate how SillyTavern used to prompt before the 1.10.0 update.

**Comment by IkariDevGIT** [comment]
#1116

**Comment by kalomaze** [comment]
Oh sick! Didn't see it on the issues but I should've checked the PRs as well. Will close when that gets merged

**Comment by IkariDevGIT** [comment]
got merged into staging, you can close
