### ISSUE TITLE
[Feature Request] Commentators for Group Chats

### ISSUE THREAD

**Issue by Nyanana** [SillyTavern/SillyTavern#1123]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Commentators are characters that provide running commentary in a group chat (Think of like sports games).

The commentator can read what all characters have written in the group chat, but anything the commentator writes is only visible to itself and you the user - Think of it like an out of character observer who is just there to provide running commentary of the roleplay for your entertainment.

As for implementation one idea is that it could be toggled with a button next to the group chat member with an icon similar to a sports commentator

![commentator-icon-vector-isolated-white-background-logo-conce-commentator-icon-vector-isolated-white-background-logo-concept-125790186-4228288333](https://github.com/SillyTavern/SillyTavern/assets/144454315/9008eb2f-d0fc-4f51-9892-986355714aad)

Something like this? would appear alongside the generate/disable message buttons?

**Describe alternatives you've considered**
I tried to do a character that gives running commentary for a group chat, but the trouble is that because the other characters can read it, the commentator's comments, jokes and quips affected the other characters roleplay, when really I didn't want the other characters to know of the commentator's existence at all.

**Additional context**
Can't think of anything else

**Comment by ghost** [comment]
Sounds a bit similar to what NovelAI does with its HypeBot, a bit niche but interesting.

**Comment by OgalFinklestein** [comment]
@Nyanana would the `/sys` macro work for this purpose?
