### ISSUE TITLE
[Feature Request]  Expand 3 dots menu always.

### ISSUE THREAD

**Issue by Ph0rk0z** [SillyTavern/SillyTavern#1128]
I get tired of clicking the dots to generate SD among other things. Is it possible to expand the 3 dots menu all the time. Perhaps I missed it in docs?

**Comment by valden80** [comment]
I'm second this, possibility to switch it to always expanded will be nice.

**Comment by Cohee1207** [comment]
Done. Look for "Auto-Expand Message Actions" under the User Settings
