### ISSUE TITLE
[BUG]Does format of example dialog really conform with Openai api?

### ISSUE THREAD

**Issue by hengjiUSTC** [SillyTavern/SillyTavern#1129]
> **Warning**. Complete **all** the fields below. Otherwise, your bug report will be **ignored**!

**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
No

**Describe the bug**
I realize the example dialog sending to openai is replaced with:
```
    {
      role: 'system',
      name: 'example_user',
      content: '"Describe your body and features."'
    },
    {
      role: 'system',
      name: 'example_assistant',
      content: `*Seraphina chuckles softly, a melodious sound that dances through the air, as she meets your coy gaze with a playful glimmer in her rose eyes.* "Ah, my physical form? Well, I suppose that's a fair question." *Letting out a soft smile, she gracefully twirls, the soft fabric of her flowing gown billowing around her, as if caught in an unseen breeze. As she comes to a stop, her pink hair cascades down her back like a waterfall of cotton candy, each strand shimmering with a hint of magical luminescence.* "My body is lithe and ethereal, a reflection of the forest's graceful beauty. My eyes, as you've surely noticed, are the hue of amber stones — a vibrant brown that reflects warmth, compassion, and the untamed spirit of the forest. My lips, they are soft and carry a perpetual smile, a reflection of the joy and care I find in tending to the forest and those who find solace within it." *Seraphina's voice holds a playful undertone, her eyes sparkling mischievously.*`
    },
```
<img width="1407" alt="截屏2023-09-14 上午9 11 02" src="https://github.com/SillyTavern/SillyTavern/assets/25971665/d66790cf-c7d0-4e79-af26-66daa9303be8">

**To Reproduce**
Dialog is defined as:
```
{{user}}: "Describe your body and features."
{{char}}: *Seraphina chuckles softly, a melodious sound that dances through the air, as she meets your coy gaze with a playful glimmer in her rose eyes.* "Ah, my physical form? Well, I suppose that's a fair question." *Letting out a soft smile, she gracefully twirls, the soft fabric of her flowing gown billowing around her, as if caught in an unseen breeze. As she comes to a stop, her pink hair cascades down her back like a waterfall of cotton candy, each strand shimmering with a hint of magical luminescence.* "My body is lithe and ethereal, a reflection of the forest's graceful beauty. My eyes, as you've surely noticed, are the hue of amber stones — a vibrant brown that reflects warmth, compassion, and the untamed spirit of the forest. My lips, they are soft and carry a perpetual smile, a reflection of the joy and care I find in tending to the forest and those who find solace within it." *Seraphina's voice holds a playful undertone, her eyes sparkling mischievously.*
```
![截屏2023-09-14 上午9 17 40](https://github.com/SillyTavern/SillyTavern/assets/25971665/06ad2ec9-e404-457e-b16d-6a06369264ee)

**Expected behavior**
From openai document: 
The role of the messages author. One of system, user, assistant, or function. But Tavern is using `example_user` `example_assistant`.

**Screenshots**
![截屏2023-09-14 上午9 13 43](https://github.com/SillyTavern/SillyTavern/assets/25971665/2aefe121-d49e-4e5d-b4e3-ecbe3fcd00fc)

**Logs**

Providing the logs from the browser DevTools console (opened by pressing the F12 key) or SillyTavern command line window will be highly appreciated.

**Desktop (please complete the following information):**
 - OS/Device: [All device]
 - Environment: [cloud, local]
 - Node.js version (if applicable): [run `node --version` in cmd]
 - Browser [chrome] 
 - Generation API [OpenAI]
 - Branch [release]
 - Model [OpenAI]

**Additional context**
So my question is does sending example dialogs, like using `example_user` `example_assistant`, is correct?? What is expected benefit of sending this way?

**Comment by Cohee1207** [comment]
This is from the OpenAI cookbook. Note that `example_user` and `example_assistant` are names rather than roles.
https://github.com/openai/openai-cookbook/blob/main/examples/How_to_format_inputs_to_ChatGPT_models.ipynb
The benefit is that the model is less likely to assume that the events from the example dialogue actually happened in the story.

**Comment by hengjiUSTC** [comment]
Thanks for explaining, that sounds pretty reasonable!
BTW, just curious, in Tavern I found we also send multiple system messages for character, jailbreak, nswf...
```
send multiple system messages
{
      role: 'system',
      content: 'character/description/scenario'
}
{
      role: 'system',
      content: 'character/description/scenario'
}
```
Compared with sending all in one big system, this there any special reason for sending in multiple? or they are similar? 
```
send one big system messages
{
      role: 'system',
      content: 'character + description + scenario + ..'
}
```

**Comment by Cohee1207** [comment]
They are split to allow you reordering them in any order you like, as well as creating custom prompt injections

**Comment by hengjiUSTC** [comment]
Thanks!
