### ISSUE TITLE
[BUG?] (Staging v1.10.3) ->  "Hi, looks like you are running TensorFlow.js in Node.js."

### ISSUE THREAD

**Issue by SabinStargem** [SillyTavern/SillyTavern#1130]
I am trying out the latest staging, and this message came up when I initialized the Vector Storage feature.  Since it claims that it will run slowly with its current version, I figured that I should mention this.   My guess is that it is intentional on the part of the Silly team.

Following the link, it goes to a deprecated repository, which in turn goes to a newer version of the project.

> C:\Users\Janus\Documents\SillyTavern>pushd C:\Users\Janus\Documents\SillyTavern\
> 
> C:\Users\Janus\Documents\SillyTavern>call npm install --no-audit
> 
> up to date in 733ms
> 
> 53 packages are looking for funding
>   run `npm fund` for details
> Running from source
> SillyTavern 1.10.3 'staging' (c4c962ae)
> Stats loaded from files.
> Launching...
> SillyTavern is listening on: http://0.0.0.0:8000/
> 
> 0.0.0.0 means SillyTavern is listening on all network interfaces (Wi-Fi, LAN, localhost). If you want to limit it only to internal localhost (127.0.0.1), change the setting in config.conf to "listen=false". Check "access.log" file in the SillyTavern directory if you want to inspect incoming connections.
> 
> New connection from 127.0.0.1; User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0
> 
> Platform node has already been set. Overwriting the platform with node.
> (node:222128) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:222128) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
> (node:222128) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
> (node:222128) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
> (node:222128) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
> (node:222128) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
> (node:222128) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
> 
> ============================
> Hi, looks like you are running TensorFlow.js in Node.js. To speed things up dramatically, install our node backend, visit https://github.com/tensorflow/tfjs-node for more details.
> ============================

**Comment by Cohee1207** [comment]
TensorFlow vectors calculation will be replaced with a faster alternative
