### ISSUE TITLE
[Feature Request] Stable diffusion on every prompt

### ISSUE THREAD

**Issue by thijsi123** [SillyTavern/SillyTavern#1133]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes (maybe I looked over it)

**Describe the solution you'd like**
I was thinking about having stable diffusion generate a character expression for every prompt.

**Describe alternatives you've considered**
I tried to use the default system and talkinghead just doesn't show anything at all so I decided to ask if this was possible.

**Additional context**
Well, for now, I'd like to just have '/sd you' called every prompt and shown in the same position as the expressions, I don't know if that's something I'd like to do myself but I don't know how everything runs nor am I a programmer (just know the basics of basic python)

**Comment by Cohee1207** [comment]
Now possible with STscript:
https://docs.sillytavern.app/usage/st-script/
Create a script that will autorun `/sd face` on every message

**Comment by thijsi123** [comment]
> Now possible with STscript: https://docs.sillytavern.app/usage/st-script/ Create a script that will autorun `/sd face` on every message

Thank you very much.
