### ISSUE TITLE
Android and iOS Apps

### ISSUE THREAD

**Issue by kaiser-chris** [SillyTavern/SillyTavern#1137]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes and I haven't found any existing request.

**Is your feature request related to a problem? Please describe.**
Currently there are no real mobile apps of SillyTavern

**Describe the solution you'd like**
Support mobile platforms using tools like cordova to provide apps of the current application.
The application itself is already running in mobile browsers fine so a full app is possible.

**Describe alternatives you've considered**
Using Termux is possible but more of a hack compared to real apps.

**Additional context**
I personally already played around with converting the application to cordova but that requires major changes to the current folder structure.
It will still be runnable as a normal node app but still this is a major rework.
This will also require major testing after implementation.

If this is a feature you guys are interested in I could do the porting work, but since this would be a massive pull request with major changes to the repository structure (probably no or few real code changes) I want to ask permission first.

**Comment by Cohee1207** [comment]
What exact structural changes are needed? Could you outline your plan?
And is it possible to have it done gradually step-by-step not to block the work in other departments?

**Comment by easychen** [comment]
Cordova does not support the Node.js runtime directly, which is essential for SillyTavern. I’ve searched for a Node.js runtime that can run on mobile devices, but the results were unsatisfactory. In the end, I developed OMate Chat using Flutter, but it can only partially support SillyTavern’s features—it’s just too powerful.
