### ISSUE TITLE
[BUG]下载的储存库似乎被和谐了，cmd下载不了，浏览器也打不开。

### ISSUE THREAD

**Issue by JiangKaslana** [SillyTavern/SillyTavern#1138]

**Comment by Cohee1207** [comment]
Use a bug report template. Also, I don't speak your language, sorry

**Comment by XXpE3** [comment]
下载的储存库是什么意思？你是指 Git 仓库吗？

**Comment by XXpE3** [comment]
> _No description provided._


下载的储存库是什么意思？你是指 Git 仓库吗？
