### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JiangKaslana** [SillyTavern/SillyTavern#1139]
_1694868160855](https://github.com/SillyTavern/SillyTavern/assets/130233273/88814cca-fe1c-4009-8066-8d2d0f25301f)
Why?
![image](https://github.com/SillyTavern/SillyTavern/assets/130233273/059fe094-50bb-4cdc-80fe-cd22c9c926ef)
I think it is a Bug

**Comment by Cohee1207** [comment]
You don't have git installed. It's not a bug.
Install git first. And use the install guide in the docs.
https://docs.sillytavern.app/installation/windows/
