### ISSUE TITLE
[Feature Request] Ability to replace use of {{user}} in the example messages of a card with a custom name

### ISSUE THREAD

**Issue by kalomaze** [SillyTavern/SillyTavern#1140]
I want to replace the {{user}} mentions that people put in the example chats with "Example Character" or similar strings; this would make that easier than modifying the card directly

**Comment by Woisek** [comment]
Why don't you just create a persona called "Example Character" and use this for the chat ... ? 🤔

**Comment by kalomaze** [comment]
Because I want to tell the card that the {{user}} in the example isn't necessarily the {{user}} that is chatting.

**Comment by Woisek** [comment]
> Because I want to tell the card that the {{user}} in the example isn't necessarily the {{user}} that is chatting.

Who else should it be then? 🤪
