### ISSUE TITLE
[Feature Request] Miltiple Sessions on interface

### ISSUE THREAD

**Issue by submaroon** [SillyTavern/SillyTavern#1151]
**Describe the solution you'd like**
I would like to be able to have multiple interface sessions so that I can run one instance of SillyTavern on my server, and I and my friends can connect to it, having our “own” interfaces

**Describe alternatives you've considered**
I could run multiple instances on separate ports so that each person has their own interface, but this is very inconvenient on our system

**Comment by Cohee1207** [comment]
Impossible with the current architecture. Please take a look at similar software like Agnai that can handle multiple users setup.

**Comment by submaroon** [comment]
> Impossible with the current architecture. Please take a look at similar software like Agnai that can handle multiple users setup.

Okay, thank you!
