### ISSUE TITLE
[BUG] Vector Storage inserts every entry twice

### ISSUE THREAD

**Issue by GeorgarP** [SillyTavern/SillyTavern#1152]
Vector Storage inserts every memory twice like this in the prompt:

Past events: User: Entry 1

User: Entry 1

Bot: Answer 1

Bot: Answer 1

User: Entry 2

User: Entry 2

Bot: Answer 2

Bot: Answer 2

**Expected behavior**
It should just insert every memory once
User: Entry 1
Bot: Answer 1
User: Entry 2
Bot: Answer 2
User: Entry 3
Bot: Answer 3

**Desktop (please complete the following information):**
 - OS/Device:  Windows 10
 - Environment: local
 - Node.js version (if applicable): v20.7.0
 - Browser: Firefox
 - Generation API: Novel AI
 - Branch: staging
 - Model: Kyra

**Comment by Cohee1207** [comment]
What's the latest commit hash in your branch?

**Comment by GeorgarP** [comment]
I think it's: 3de5cdd7e8b4c664fe3beb2bb7f7829ac28f33fc (?)

**Comment by Cohee1207** [comment]
Can you confirm by looking into console window or user settings menu?

**Comment by Cohee1207** [comment]
I think I fixed this, please pull and check again.

**Comment by GeorgarP** [comment]
Now it's: 
Bot: Answer 1
Bot: Answer 2
Bot: Answer 3

Is it intended to only have the Answers inserted and not the the User Input?

**Comment by Cohee1207** [comment]
Yes. It inserts only related messages, not pairs of interactions.

**Comment by GeorgarP** [comment]
I've checked again with some more inputs and it does indeed also insert User Messages. 
Then i think it's fixed. Thank you.
