### ISSUE TITLE
[Feature Request] Impersonate should not trigger cards' Prompt Overrides

### ISSUE THREAD

**Issue by AnonCardMaker** [SillyTavern/SillyTavern#1156]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
When using Impersonate with cards that use Prompt Override, the custom Prompt Override will mess with Impersonate. The point of Prompt Override is to make a complex card function, it shouldn't matter to Impersonate.

**Describe the solution you'd like**
Just ignore any of the card Prompt Overrides when using Impersonate. Of course the normal Jalibreak or Main Prompt should still function.

**Describe alternatives you've considered**
That's it.

**Additional context**
I'm not sure if this should count as a bug. Also I've never seen any card overriding the Main Prompt, it's always the Jailbreak. LOL.

**Comment by qwertea** [comment]
Impersonation 'prompt' should actually be a whole different preset IMHO. LLMs can get confused when the rest of the prompts talk at length about not controlling {{user}}. Especially now that gpt-4-0125 is so prone to reject you simply for contradictory instructions.
