### ISSUE TITLE
[Feature Request] Custom Macros

### ISSUE THREAD

**Issue by Dalethium** [SillyTavern/SillyTavern#1157]
Was hoping to be able to use macros in commands for things like stable diffusion -- the /sd command is great but having to type out the same details over and over gets annoying -- it would be great to have character specific macros in the advanced definitions along with system wide ones. The uses of custom macros go beyond just sd, obviously, so it may be a good feature to have.

**Comment by Cohee1207** [comment]
Basically variables in STscript: https://docs.sillytavern.app/usage/st-script/#variables
