### ISSUE TITLE
[Feature Request]: Can we have an ability to choose the depth for custom created prompts in prompt manager?

### ISSUE THREAD

**Issue by nothingsuspiciousright** [SillyTavern/SillyTavern#1159]
Hello! That's it,  hey. Is it possible?

**Comment by Cohee1207** [comment]
Possible, but requires implementation. Use Author's Note for now.

**Comment by Cohee1207** [comment]
Basically covered by new feature in staging - World Info at custom depth.

**Comment by Cohee1207** [comment]
Added to staging.
