### ISSUE TITLE
[Feature Request] Random prompt injections

### ISSUE THREAD

**Issue by theq1234** [SillyTavern/SillyTavern#1160]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
It isn't related to any problems, feature requests, or bugs that I've seen.

**Describe the solution you'd like**
From what I could gather, lore books might be able to do this, but I've used lore books before and it doesn't seem to work the same way as what I have in mind. What this is more like is essentially a prompt that you can add to the prompts list that allows you to add a custom percent chance of being sent to the API(e.g. there is a 50% chance that the prompt will be sent, but unlike world info, it doesn't require a keyword to be injected. A proper dice roll to a written down random event, like what some reverse proxies have used). Perhaps it can automatically turn off after a set number of uses to save tokens.

As an alternative, perhaps a new macro could be added(something like {{rand_0.37:[Some random event]}} with the percentage taped to it, where if the complement is rolled then it will be ignored), that way it can be added to post-history instructions so people can add random events unique to individual characters. The downside to this is that it _might_ be sent every time(depending on how it's implemented, if it's implemented), among other things, as opposed to a fresh prompt in the prompt manager that doesn't necessarily get added to the list of what is sent. In any case, both options would be more token-efficient than doing something like '{{random:1,2,3,4,5,6,7,8,9,word,10,11,12}}'('word' is 1/13 chance to get picked, this is just a low number example) to achieve a similar effect.

_I made a mockup in Paint.NET of what this could potentially look like(see below), with the percent chance of what might be sent(nothing in that particular prompt, though) to the API in decimal form._

I don't expect this to be prioritized, as to me, it's purely a gimmick. Some might find uses in it(like a scenario change or sporadic personality shifts that are meant for certain characters), but I just thought it was a cool idea. It will likely need implementation, though... Maybe this is better suited for a third-party addon, or an addon for Extras.

![ExampleMockup](https://github.com/SillyTavern/SillyTavern/assets/145595305/0331dd74-705b-413a-9822-1aa1aa79c7c2)

**Comment by TismKing** [comment]
Have you tried setting making a lorebook entry and setting it to constant and changing the probability?

**Comment by theq1234** [comment]
> Have you tried setting making a lorebook entry and setting it to constant and changing the probability?

Doesn't it still require the keyword to be present in the prompt(or any text, really) to activate the entry in this configuration?

Edit: Just checked the documentation. Turns out this _is_ what I had in mind, but does it affect the results as much as a custom prompt(as I've described) placed just before(or after) the jailbreak?

Edit 2: Never mind, you can place the insertion depth of the entry. Still would be a nice feature, though.
