### ISSUE TITLE
[Feature Request] More control in the context template (some models need it).

### ISSUE THREAD

**Issue by valden80** [SillyTavern/SillyTavern#1167]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
There is still new types of prompt format for the local models being created. For example this one: https://huggingface.co/Tostino/Inkbot-13b-4k
Right now context template manager can't be used to fully follow it, as it's need a history of chat and current last user input being place ABOVE the some other context - like WI and extensions output for reaching full potential.

**Describe the solution you'd like**
More control in the context template with these tags:
{{chat_history}} - previous chat messages.
{{extensions}} - to place extensions output here. (Ideally - separate tags for every extension, but this will be a pain for support in future, IMHO, so the single tag for all is suitable too.)
{{user_input}} - where to place last user input. (Yes, there is now models, that don't expect it to be in the end of the given context.)

**Describe alternatives you've considered**
Nothing that I can think now.

**Additional context**
With these additions default template should look like this:
```
{{#if system}}{{system}}
{{/if}}{{#if wiBefore}}{{wiBefore}}
{{/if}}{{#if description}}{{description}}
{{/if}}{{#if personality}}{{char}}'s personality: {{personality}}
{{/if}}{{#if scenario}}Scenario: {{scenario}}
{{/if}}{{#if wiAfter}}{{wiAfter}}
{{/if}}{{#if persona}}{{persona}}
{{/if}}{{#if extensions}}{{extensions}}
{{/if}}{{#if chat_history}}{{char_history}}
{{/if}}{{#if user_input}}{{user_input}}
{{/if}}
```
But for the model above template should be:
```
<#meta#>
- Date: 2077-07-20
- Task: roleplay
<#system#>
{{#if system}}{{system}}{{/if}}
<#chat#>
{{#if chat_history}}{{char_history}}{{/if}}
{{#if user_input}}<#user#>
{{user_input}}{{/if}}
<#user_context#>
{{#if wiBefore}}{{wiBefore}}
{{/if}}{{#if description}}{{description}}
{{/if}}{{#if personality}}{{char}}'s personality: {{personality}}
{{/if}}{{#if scenario}}Scenario: {{scenario}}
{{/if}}{{#if wiAfter}}{{wiAfter}}
{{/if}}{{#if persona}}{{persona}}
{{/if}}{{#if extensions}}{{extensions}}
<#bot#>

```

**Comment by Cohee1207** [comment]
I can't add chat_history placeholder as the story string is rendered before arranging chat messages into the context space. The only thing I could theoretically offer is reorderable story/history/examples.
