### ISSUE TITLE
[BUG?] WI tokens added to Auhtor's note extension token counter in prompt report.

### ISSUE THREAD

**Issue by valden80** [SillyTavern/SillyTavern#1172]
### Environment

Self-Hosted (Bare Metal)

### System

Firefox 115.2.0esr, Manjaro current.

### Version

SillyTavern 1.10.4 staging

### Desktop Information

 - Node.js: version 20.2.0
 - Generation API: Oobaboga
 - Branch: staging
 - Model: any.

### Describe the problem

When you see report of the tokens counts generated after the clicking on the button "Prompt" in actions, ("Prompt Itemization" window) you can see incorrect calculation.

Source of the problem: The tokens from the triggered WI entries whose insertion place "before AN" not added to WI tokens count, but they go to the Author's Note extension tokens count. This is confuse me for long time already, but I not reported it before as I can't find a way to reproduce it with guarantee before. 
I manage to catch from where it getting those tokens even on empty AN only today.

If it's intended behavior, I suggesting to change option text "Before AN" to "As AN (in begin)" or "In the begin of AN" in the WI editor. As is it's just confusing.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Just don't use A/N positions, custom depth from the newest update makes it essentially obsolete.

**Comment by valden80** [comment]
Custom depth is not equal. Some times I using WI in synergy with AN, and custom depth don't allow me to predict position of inserted text so easy as simple "Before AN" and "After AN".

Example (simple case):

AN = "Describe scene in the details."
WI (Before) = "Main focus of this scene is..."
This way if WI is not triggered - AI just describe in the details all in general. But with triggered WI things changed, as it get different instruction: "Describe scene in the details. Main focus of this scene is..." 
As result AI describing what is most important. But this trick working good only if these sentences in WI and AN in context injected directly one after another. With custom depth - it's harder to predict injection place and get this result.
