### ISSUE TITLE
[FEATURE_REQUEST] Append X + automatic continue, on X not found

### ISSUE THREAD

**Issue by IkariDevGIT** [SillyTavern/SillyTavern#1173]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Yes, for example:

The AI writes a message without something you want... like an asterisk.

### Describe the solution you'd like

A textbox where you can input the character/word you want the Ai to always type. When the AI generates a message without that it appends the specific character/word and continues the message with that. 

Optionally a "append" textbox would be nice, where you can replace the thing that gets appended

### Describe alternatives you've considered

You can of course do it manually but tbh its a pain in the ass to do it everytime

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

Yes!

**Comment by IkariDevGIT** [comment]
for people not getting what i want:

```
this feature would be for that messages like this:

hey.. im char balablabalüpdfk

dont exist, for example, that message above is annoying because she just talks.. no actions, so with that feture enabled it would see "ahh.. there is no action/asterisk in the text, ill add one and continue the message", it adds teh missing asterisk:

hey.. im char balablabalüpdfk *

and continues the message from there, so that the final message looks like this:

hey.. im char balablabalüpdfk *i jump and throw a toilet at his face*
```

+ some pseudo code:

```
x = "*"
if (!message.has(x)){
    message.text = "{message.text} {x}"
    triggerevent(continue_message)
}
```

**Comment by Tony-sama** [comment]
Did a small prototype of the feature here: https://github.com/Tony-sama/SillyTavern/tree/enforce-extension

![Capture d'écran 2023-09-25 030536](https://github.com/SillyTavern/SillyTavern/assets/48798118/a37fc477-16ba-4f88-ba7f-abeb4f571da1)

It's kinda like a conditional "Start Reply With". Maybe too specific to be a general extension. It could be done by a more general purpose extension that allow user to kinda scripts around message received to enforce content or do step by step generation. Kinda langchain type of thing.

**Comment by Cohee1207** [comment]
Doable with STscript or the extension from Tony-sama.
https://docs.sillytavern.app/usage/st-script/
