### ISSUE TITLE
[FEATURE REQUEST] Auto mode in individual chats too

### ISSUE THREAD

**Issue by xNissX233** [SillyTavern/SillyTavern#1176]
### Have you searched for similar requests?

Yes

### Describe the solution you'd like

The auto mode in group chats is great, and I think it would be good to have it in individual chats too, using the "impersonate" option automatically to simulate a conversation between the user and the character that goes on automatically.
Could be useful to make stories or to continue a conversation when you already gave enough context about yourself to allow the AI to generate a response for you close to what you would say, saving you the effort to write it yourself. 

### Describe alternatives you've considered

Could use the new Idle plugin too, setting it to minimum time, and then we would just need a way to trigger the impersonate option automatically every X character responses for example.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
Have you tried the idle extension?

**Comment by xNissX233** [comment]
> Have you tried the idle extension?

Yes, as I said in the alternatives. The thing is that this extension doesn't trigger the "impersonate" as far as I know, so the character is the only one that keeps talking.
