### ISSUE TITLE
[BUG] Open-ai GPT4 repeating messages/sending exact same messages from the chat

### ISSUE THREAD

**Issue by subwolf22** [SillyTavern/SillyTavern#1179]
### Environment

Self-Hosted (Bare Metal)

### System

Windows 10, Chrome browser

### Version

1.10.5

### Desktop Information

updated to latest version of staging

using official openai api key

tried new installations, fixed it for a little bit but seems to come back

tried main same thing

### Describe the problem

so for the past week or so, i have had this problem where gpt4 has been repeating messages, sometimes its not to bad and the general sayings and phrases are copied, but sometimes it just straight sends the same message from earlier in the chat, also sends the first message sometimes but that's rare, i have attached screenshots of my settings and also a small video showing what's happening, ignore most of the chat that's how i have to get it to respond with something new i have to send a second message.
i have tried a new installation and it seemed to fix it for a while then it started happening again. i have also tried changing the temp and other settings and still nothing. it happens with any character i use, at first its fine then a few messages in it starts it again, it doesn't happen with local and gpt3.5 somehow.
please let me know if i need to add something else, or if I'm just dumb

### Additional info

![advanced formating](https://github.com/SillyTavern/SillyTavern/assets/117887342/1ddee392-812c-4a93-a371-06f3ab538e40)

![user settings](https://github.com/SillyTavern/SillyTavern/assets/117887342/a81e3f08-0e1a-46c3-9be6-8b3f1c32ec21)

![ai settings](https://github.com/SillyTavern/SillyTavern/assets/117887342/d8b8709f-9573-4e1f-aaa4-441e9ebdfd96)

[prompt being sent.txt](https://github.com/SillyTavern/SillyTavern/files/12709484/prompt.being.sent.txt)

https://github.com/SillyTavern/SillyTavern/assets/117887342/c2dc3991-87b6-47a2-a1d7-b801c4a847c4

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
No idea, doesn't look a software bug if the generated prompts are correct. Try using different main prompts without XML, the one you attached is for Claude.

**Comment by subwolf22** [comment]
> No idea, doesn't look a software bug if the generated prompts are correct. Try using different main prompts without XML, the one you attached is for Claude.

so i have done some more testing and it still happens with a more simple prompt no xml. also someone i know says it has happened to them as well so I'm not sure what's going on

**Comment by subwolf22** [comment]
also it seems even when it re sends one of the same messages it doesn't even acknowledge it as a response in the cmd window it still just shows the last user response, i just noticed this that's my bad

**Comment by subwolf22** [comment]
also i don't really know if this will help or not, but i tested out same settings same card same prompts on risuai and it never even once repeated messages and even stopped re-using certain words, like i said I'm not sure if me mentioning it helps at all but i thought i would
