### ISSUE TITLE
[custom_token_ban] Please add Custom Token Ban to ST

### ISSUE THREAD

**Issue by Menthols426** [SillyTavern/SillyTavern#1180]
### Have you searched for similar requests?

None

### Is your feature request related to a problem? If so, please describe.

One of the main problems with ChatRP for many, many users(especially Local model users) is models forming the bad habit of speaking for {{user}} during replies. It's extremely annoying and ruins the experience. 

### Describe the solution you'd like

It was recently discovered that banning a certain custom token in Oobabooga completely prevents this from happening, if ST would also add this feature, it could solve this incredibly annoying issue, please add this feature.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

None

**Comment by theunstableman** [comment]
Is this even possible in normal ooba api?
Edit: Not possible.

**Comment by Menthols426** [comment]
What? Yes it is. In Ooba's interface, Parameters > Generation, bottom right corner. "Custom Token Bans"

**Comment by theunstableman** [comment]
Not in API atleast

**Comment by theunstableman** [comment]
:( i was wrong i guess

**Comment by theunstableman** [comment]
Oh yeah close this issue!
