### ISSUE TITLE
[BUG] Mathjax support no longer working?

### ISSUE THREAD

**Issue by vintner-coder** [SillyTavern/SillyTavern#1183]
### Environment

Self-Hosted (Bare Metal)

### System

Windows 10, Chrome browser

### Version

1.10.5

### Desktop Information

Updated Staging after a while
Using personal GPT-4 key

### Describe the problem

The double dollar sign and single dollar sign notation for showdown-katex no longer appears to be displaying mathematical formulas as displayed in the output in this issue: https://github.com/SillyTavern/SillyTavern/issues/26

Has this feature been disabled? Is it possible to reenable it?

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
You have to enable it in User Settings with "Render formulas" toggle.

**Comment by vintner-coder** [comment]
Fantastic, thanks.
