### ISSUE TITLE
[FEATURE_REQUEST] "Always add user's name to user inputs" or a "Always add user's name to prompt" checkbox

### ISSUE THREAD

**Issue by alicat22** [SillyTavern/SillyTavern#1188]
### Have you searched for similar requests?

None

### Is your feature request related to a problem? If so, please describe.

When using ST as an adventure companion, I'd like to send messages like the following:
```
> You look around
```
However, currently, you can only do this via a `/sys`. `/sys` is very inconvenient when every message you send needs to be sent with a `/sys` prepended, as many adventure models want the adventure format:
```
> You action stuff
```
or
```
> You say "Dialogue"
```

### Describe the solution you'd like

Add the option to disable the user's name being prepended on user inputs.

Some examples could be:
- "Always add user's name to user inputs" checkbox
- "Always add user's name to prompt" checkbox

Of course this should be default ON. And only for advanced users if they'd wish to disable this.

This would also lead into it being something neat to be included with presets, because an adventure mode preset would have this and "Always add character's name to prompt" disabled.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

Maybe

**Comment by OgalFinklestein** [comment]
I thought when performing an action it was enclosed in asterisks?  Or is that just more of a personal preference?

**Comment by alicat22** [comment]
> I thought when performing an action it was enclosed in asterisks? Or is that just more of a personal preference?

Models typically perform better when using a "novel-style". Which is formatted like this:
```
"Dialogue," action.
```
Only a few models perform better with "markdown-style" (like Pyg). Which is formatted like this:
```
Dialogue *action*.
```
Adventure-mode model's datasets usually contain dialogue/actions like the following:
```
> You look around
As you look around you notice a goblin. The goblin looks to you and says, "Are you here for the festival?"
```

**Comment by OgalFinklestein** [comment]
Ah, so like the old MUDs of yore.

**Comment by alicat22** [comment]
So it looks like you can actually do this via Instruction Mode (credit Cohee).
![image](https://github.com/SillyTavern/SillyTavern/assets/86847834/500b08f5-be67-4a0f-a5a7-42e2aeece985)
Simply have the instruct mode empty and it works perfectly for my use-case for adventure mode. (System prompt isn't needed. I just added it for experimental purposes)
Then the user just needs to remember to add `>`.
Feel free to close now or with a preset addition (if you'd like).

**Comment by alicat22** [comment]
Will follow-up with a separate quick bug report issue, as `\n` as a "Stop Sequence" doesn't actually seem to work.
![image](https://github.com/SillyTavern/SillyTavern/assets/86847834/de850d82-8519-4e8d-818d-79fe9c130bf3)
![image](https://github.com/SillyTavern/SillyTavern/assets/86847834/9d4369ba-3295-4454-ae07-62e035d78ebc)
But the custom stop sequence option works perfectly, so super low priority:
![image](https://github.com/SillyTavern/SillyTavern/assets/86847834/7402ca98-bf66-4bfe-b508-aa798e8a4210)
![image](https://github.com/SillyTavern/SillyTavern/assets/86847834/b030a0d6-d0b0-40c2-a6f3-213627119011)

**Comment by Cohee1207** [comment]
The last is not a bug. Instruct sequences do not use encoded entities. Just press enter in the box to input a line break.

**Comment by alicat22** [comment]
Added -> 4fbbd34db972b5fd4d25bb59e71f837e413a5d02
Thank you!
