### ISSUE TITLE
[BUG] screen displacement after send message

### ISSUE THREAD

**Issue by MetalNymeria** [SillyTavern/SillyTavern#1192]
### Environment

Android (Termux)

### System

Latest chrome, also tested on opera and Firefox 

### Version

1.10.4

### Desktop Information

Since it's a css problem, the only thing it should matter it's that it's on the release branch

### Describe the problem

You start typing and the screen gets repositioned above the android keyboard, that's ok, it's normal. But when you press on send message, the chat container doesn't reposition itself down again, it stays there as if the keyboard is still active, rendering the upper half of the screen useless.

### Additional info

![Screenshot_2023-09-27-21-35-10-956_com fevdev nakedbrowser](https://github.com/SillyTavern/SillyTavern/assets/35712803/1e8a8f63-be88-4d3e-a13a-2c94eddc6109)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Wolfsblvt** [comment]
This exact issue was fixed recently.
