### ISSUE TITLE
[FEATURE_REQUEST] Tag for adding to the Banned Tokens from any place in context

### ISSUE THREAD

**Issue by valden80** [SillyTavern/SillyTavern#1193]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

New "Banned Tokens" feature for the Ooba's backend is extremely useful. I Already tested and just LOVE it. It's working perfectly and without significant VRAM usage. (This is why I still can't use CFG - it's need too much VRAM with 13B models together my card can't process it - OOM.)
But as it's working only with exact text phrases, this feature have much bigger potential, if only there will be a possibility set it per character, and/or manipulate with WI triggering.

### Describe the solution you'd like

Solution for the maximum flexibility - a tag to include string to banned token from any part of context. 
Example: {{ban:I'm too lazy}} placed in character card will effectively prevent him to talk that he is too lazy for anything. 
So this tag will can be placed anywhere, where other tags like {{char}} working (AN, WI, character description, extensions, etc) and works based on context.

### Describe alternatives you've considered

None of such flexibility that I can think of.

### Additional context

Expected logic/mechanic of code:
When processing the tags, after pulling all found {{ban: ... }} tags and adding their strings to the Banned Tokens, these tags should be removed from the context as if they just not exist, before sending request to the backend. Even if maximum possible context size will be lost with deleted tags - it's still a good price to pay for the such flexibility (but warning in help page will be good in description of this tag usage).

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?
Yes!

**Comment by valden80** [comment]
@Cohee1207 
This idea don't go from my mind, so I tried to make those changes by myself. And this time I manage to do working code.
The issue - I was pretty bad with modern JS (learned it very long ago, and don't has much experience from these times), so I don't sure if it's has enough quality for modern JS.
I can make pull request, but do you interested in this addition? 
I tested - it's works, but my understanding of modern JS is very limited, and it's can be far from optimal...

**Comment by Cohee1207** [comment]
Go ahead, if you feel it's a good addition.
