### ISSUE TITLE
[BUG] Slide bar "Chat Width (PC)" does not use the correct value for UI resizing

### ISSUE THREAD

**Issue by stho90** [SillyTavern/SillyTavern#1194]
### Environment

Self-Hosted (Bare Metal)

### System

Windows 11

### Version

SillyTavern 1.10.4 'release' (6203d82f)

### Desktop Information

Node.js: **v18.17.1**
Backend: **KoboldCPP v1.42.1**
Branch: **release**
Model: **n.a.**

### Describe the problem

I am using FireFox v117.0.1 with 200% font size. (Font size does not have impact on this issue. I can reproduce it with regular 100% zoom.)

The issue is in the slide bar in the "User Settings" menu if i want to change the "Chat Width (PC)".
I grab the slide bar and slide it left or right, but the selected value will not be used correctly.
From my point of view, there is a wrong order of the methods and functions.

**Here an example for reproducing the issue:** 
- I have selected 100% of "Chat Width (PC)" (Just to make sure the issue is more understandable)
- Then i grab the slide bar and move it to 80% UI size
- After i let the slide bar go, it changes the displayed value to 58% (not 80% as i expected). The UI correctly changed to 80% but it writes 58% in the text box.
- If i press F5 and reload the site, the UI resizes from 80% to 58% and still shows 58% in the text box.

Note:
If i write the value in the text field, everything works fine. The issue seems to be only in the event handler of the slide bar.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Thanks for reporting. Pushed the fix to staging. Other browsers were not affected, the slider issue was only reproduced in the Firefox browser.

**Comment by stho90** [comment]
Bug seems to be fixed in **1.10.5 'release' (15c81749)**

Thank you very much!
