### ISSUE TITLE
[BUG] Edit button not working when regenerating (Random)

### ISSUE THREAD

**Issue by YulienPohl** [SillyTavern/SillyTavern#1195]
### Environment

Self-Hosted (Bare Metal)

### System

Edge

### Version

1.10.4

### Desktop Information

- Node v18.17.1

### Describe the problem

This has happened to me about 3 times already, after which I pressed the regenerate message button in a group chat and then wanted to edit the message.
It happens completely randomly, would say 1/20.

### Additional info

Windows terminal output:
No Error

Browser console output:
```
script.js:5094  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'trim')
    at updateMessage (script.js:5094:21)
    at messageEditDone (script.js:5154:41)
    at HTMLDivElement.<anonymous> (script.js:8030:23)
    at HTMLDocument.dispatch (jquery-3.5.1.min.js:2:43090)
    at v.handle (jquery-3.5.1.min.js:2:41074)
updateMessage @ script.js:5094
messageEditDone @ script.js:5154
(anonymous) @ script.js:8030
dispatch @ jquery-3.5.1.min.js:2
v.handle @ jquery-3.5.1.min.js:2
await in v.handle (asynchron)
dispatch @ jquery-3.5.1.min.js:2
v.handle @ jquery-3.5.1.min.js:2
```

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Don't know if that's related, but while looking into it I found another one: if regenerating when the message editor is open on the regenerated message, then the next edit click will render the message empty. Fixed that by force-closing the editor before regenerating.
