### ISSUE TITLE
[BUG] Stable Horde prompt is too long, truncating...

### ISSUE THREAD

**Issue by Teashrock** [SillyTavern/SillyTavern#1199]
### Environment

Android (Termux)

### System

Android 13, Samsung Galaxy Tab S6 Lite

### Version

1.10.4

### Desktop Information

Node.js version: v19.9.0
Generation API: Stable Horde
Branch: release
Model: any model

### Describe the problem

When I try to generate images using Stable Diffusion, I use ST prompt generation like "Pause the roleplay, then provide {{char}}'s detailed description.". Then, after reviewing and editing it, I paste it into Stable Diffusion plugin named "Character prompt". Then, I generate an image using one of my prompts, wanting to illustrate current situation. Finally, I press "Generate", expecting my request fulfilled.
But guess what?
Everything is ruined by this one line in the logs: "Stable Horde prompt is too long, truncating..."
I'd understand if the prompt were really too long, but the thing is I already did this with the same character. The prompt then has not been truncated, and everything was generated fine. And this thing now just meaninglessly interferes with what I want to do.

**What I expect to happen:**
1. I enter all the data into the Stable Diffusion plugin.
2. I press "Generate".
3. I get the expected image.

**What actually happens:**
1. I enter all the data into the Stable Diffusion plugin.
2. I press "Generate".
3. I don't get the expected image by any means due to the prompt being truncated _**with no possibility to avoid this**_ (I thought the token amount is the case, so I tried raising it, but it didn't help).

**Possible solutions:**
1. Let the user choose the token amount ST will truncate. This will be much more convenient if user could adjust truncation depending on a Stable Diffusion model or a Horde worker.
2. Remove the truncating mechanism completely. Seriously, why is it even needed? Things were just beautiful without it, everything worked as intended. With it, things don't work at all in some cases.

### Additional info

**The prompt I expected to be generated:**
`best quality, absurdres, masterpiece, full body portrait, catgirl, female, eighteen, 18 years old, pink hair, two pigtails, brown eyes, pink dress, yellow bow tie, cat ears, tail`

**The prompt that actually got generated:**
![Screenshot_20230930_100238_Termux](https://github.com/SillyTavern/SillyTavern/assets/12483854/734d958f-668b-4128-a337-7ead6840d5f8)

Like I said earlier: I already tried the same with the same characted on earlier ST versions, and it worked perfectly. That means the prompt isn't _really_ too long, it's just SillyTavern itself thinking it's "too long" for some reason.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
> Seriously, why is it even needed?

Yes, seriously. AI Horde has a limit of 1000 characters in the prompt they don't mention it anywhere. Mind your attitude.

**Comment by Teashrock** [comment]
@Cohee1207 
I'm sorry if I sounded a bit angry, I was just frustrated by the bug, I guess. No offence meant or intended.
Still, does it mean Stable Horde changed their prompt limits? Because, as I said, this wasn't the case earlier.

**Comment by Cohee1207** [comment]
I raised the limit in staging. I don't know when exactly it hits.

**Comment by Teashrock** [comment]
@Cohee1207 
Okay, then I'll clone staging version for myself, and test it out there.

**Comment by Teashrock** [comment]
@Cohee1207 
It's late, but the bug has gone, so I'm closing the issue. Thank you for your hard work, and sorry for sounding too angry.
