### ISSUE TITLE
[FEATURE_REQUEST] Translate only quoted text

### ISSUE THREAD

**Issue by chuliorasch** [SillyTavern/SillyTavern#1201]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

when the text is translated by google, the result don't have quotes, they are changed by a commonly used Japanese symbol, so the TTS engine takes everything to read or nothing depending of the option

### Describe the solution you'd like

I would like an option to translate only quoted text, so we could have only the dialog voice in other language

### Describe alternatives you've considered

try to do myself but I never work with node.js, only python

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

Yes!

**Comment by Cohee1207** [comment]
How do you imagine this implemented? There's no way to mark a text for translation and leave anything else intact. If translating only some text, how to stitch it back with the original text? This sounds more like a TTS improvement to consider your Japanese quote symbol. Extend this regex:
https://github.com/SillyTavern/SillyTavern/blob/release/public/scripts/extensions/tts/index.js#L439
