### ISSUE TITLE
Add the feature of chat history.

### ISSUE THREAD

**Issue by 258039** [SillyTavern/SillyTavern#1205]
### Have you searched for similar requests?

None

### Is your feature request related to a problem? If so, please describe.

Deleting individual chat records one by one is too tedious and cumbersome.

### Describe the solution you'd like

Add a feature that allows for the deletion of multiple chat records at once.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

Maybe

**Comment by Cohee1207** [comment]
If you mean files, you can delete them via file explorer
