### ISSUE TITLE
Conditional Italicization

### ISSUE THREAD

**Issue by kalomaze** [SillyTavern/SillyTavern#1210]
### Have you searched for similar requests?

Yes

### Describe the solution you'd like

Essentially, I would just like an option that renders all text that's not wrapped in quotation marks with italics visually

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

Maybe

**Comment by Cohee1207** [comment]
This is basically a custom CSS thing

```
.mes_text :not(q) {
font-style: italic;
}
```
