### ISSUE TITLE
[FEATURE_REQUEST] CUSTOM ENDPOINT FOR CHATGPT-4 API

### ISSUE THREAD

**Issue by aicynide** [SillyTavern/SillyTavern#1213]
### Have you searched for similar requests?

None

### Is your feature request related to a problem? If so, please describe.

CUSTOM ENDPOINT FOR CHATGPT-4 API

### Describe the solution you'd like

CUSTOM ENDPOINT FOR CHATGPT-4 API

### Priority

High (The app does not function without it)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
Reverse proxy field.

**Comment by aicynide** [comment]
> Reverse proxy field.

How? Please tell the steps or screenshot
