### ISSUE TITLE
GIF support for character cards

### ISSUE THREAD

**Issue by kalomaze** [SillyTavern/SillyTavern#1215]
### Have you searched for similar requests?

None

### Is your feature request related to a problem? If so, please describe.

N/A

### Describe the solution you'd like

Animated gifs for character cards could be fun

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

Maybe

**Comment by Cohee1207** [comment]
GIFs are not supported. But APNG are

**Comment by kalomaze** [comment]
I see, I was able to get apng working but it was inconsistent with the two images I tested, could just be the gif was corrupted tho before I converted to apng

**Comment by Cohee1207** [comment]
Important to note that Jimp library does not support resizing and crop for APNG, so you have to do it yourself
