### ISSUE TITLE
[BUG] After last changes, WI entries bug on open-close clicks.

### ISSUE THREAD

**Issue by valden80** [SillyTavern/SillyTavern#1217]
### Environment

Self-Hosted (Bare Metal)

### System

Firefox 115.2.0esr, Manjaro current.

### Version

SillyTavern 1.10.5 staging

### Desktop Information

- OS/Device: Manjaro Linux
 - Environment: local
 - Node.js: version 20.2.0
 - Browser: Firefox
 - Generation API: Oobaboga
 - Branch: staging
 - Model: any local

### Describe the problem

After the [30e5a315915eb4675b629ac2d984a42891735b67](https://github.com/SillyTavern/SillyTavern/commit/30e5a315915eb4675b629ac2d984a42891735b67) commit, there is bug with WI entries open-closing clicks. It's reverse-reacting when entry is **already opened** and user clicking on the first selector switch (Depth position - Before char, After char, etc) Selector opens normally, but entry is **CLOSING** (should stay open). 

### Additional info

No logs, no errors, screenshot is useless being static.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
@RossAscends, should add these moved inputs to the ignore list for closing the drawer.

**Comment by Cohee1207** [comment]
This was fixed.
