### ISSUE TITLE
[FEATURE_REQUEST] Separate main text color of the UI from the chat main text in the theme option

### ISSUE THREAD

**Issue by ahmed-elj** [SillyTavern/SillyTavern#1220]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

I wanted to changed the color of the main text in the chat, but i didn't like that it change the whole ui color, even the buttons colors

### Describe the solution you'd like

It would be better if the main text color of the chat, is separate from the base UI main color in the theme option menu 

```
[ ]  Main Text
[ ]  Chat Main Text
```

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

No

**Comment by Cohee1207** [comment]
Can be done with custom CSS. Use `.mes_text` selector

```
.mes_text {
  color: orange;
}
```
