### ISSUE TITLE
[FEATURE_REQUEST] Button to reload WI list

### ISSUE THREAD

**Issue by valden80** [SillyTavern/SillyTavern#1221]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

After recent changes in the WI editor I started to make new big LoreBook for the first time, and found extremely frustrating thing:
Setting up the order of the entries now very unergonomic. Yes it's possible to set filter to "order" (or other condition) and it's should make sorting by itself, but problem is: sorting is done only when you setting filter! To apply it after you done something to entries you need:
1. Set new order though "order", (depth, position, etc) fields.
2. Set filter pull-down list to other regime.
3. Set filter to desired order regime again.
Only then you will see new entries order. Frustrating.

### Describe the solution you'd like

Simple "Reload" button in interface, to apply currently set sorting filter again. To avoid 2 and 3 with single click.
Important! Please, do not try to make reload/reapply automatic - it will be even more confusing! (Sudden change of entries place will make hard to edit entries.)  
Just add the "reload" button please.

### Describe alternatives you've considered

None that I can think.

### Additional context

None.

### Priority

High (The app does not function without it)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
There you go

**Comment by valden80** [comment]
This is perfect! Thank you!
