### ISSUE TITLE
[FEATURE_REQUEST] add the ability to attach text files to messages

### ISSUE THREAD

**Issue by official-anato** [SillyTavern/SillyTavern#1222]
### Have you searched for similar requests?

None

### Is your feature request related to a problem? If so, please describe.

The reason i wish for this to be added is because i've noticed that pasting text in the chat results in a ton of lag (I am on mobile, so the wait times are a little... frustrating? I don't really know the word for this.), i believe that this feature would solve this problem as there would no need to paste the text inside the file, you just drag and drop (or, use the hamburger menu on the down left side, where the button is perfectly hidden until needed.)

### Describe the solution you'd like

Now, I didn't really think of any solutions to this, and i don't really understand what to type here since it's a feature request, but i assume it means what are some methods of implementing it, if that is the case, i'll go ahead and list down some methods of implementing it:

- (this one was already mentioned) the hamburger menu, you click the button and it appears, after, you can go ahead and select your file.
- a command (e.g "/importtext {file_name.txt}") (update: kinda just realized this is a really bad idea because you can't include other text.)

as for how the menu (for uploading/selecting files) should look like, i assume it could be like - there are two buttons in the top left corner, one for selecting files, and one importing them, underneath the selecting button, it could show the name of the file, while the rest of the menu is just a preview of the file's contents.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
How long are the files in question? And what is your model's context size? The content of the message should fit into the context, otherwise it won't be inserted.

**Comment by official-anato** [comment]
> How long are the files in question? And what is your model's context size? The content of the message should fit into the context, otherwise it won't be inserted.

im currently using gpt4-0613 (8k context), the files im pasting is code, it's not too long (around 3-5kb of code), im sure it can fit into the context easily

(sorry for the weird wording, im kinda bad at english-)

**Comment by Cohee1207** [comment]
Added to Release 1.10.10 (attach files in wand menu).

**Comment by Charuru** [comment]
Can we get this on a character?
