### ISSUE TITLE
[BUG] Transparent chat background after changing "Theme Preset" from "Ross v2" to "Default (Dark) 1.7.1"

### ISSUE THREAD

**Issue by stho90** [SillyTavern/SillyTavern#1225]
### Environment

Self-Hosted (Bare Metal)

### System

Windows 11

### Version

SillyTavern 1.10.5 'release' (15c81749)

### Desktop Information

Node.js: v18.17.1
Backend: KoboldCPP v1.42.1
Branch: release
Model: n.a.

### Describe the problem

I am having the "Theme Preset" set to "Default (Dark) 1.7.1". If i switch from that to "Ross v2", the chat background went transparent.
I saw that change and i did not like it and changed it back. After that, the background of the chat messages does not change its transparent value back to black.

Interesting to see is also the change of the Char image from round to square, but thats not the topic of the issue here, even if i have decided to display char images as square.

See the following example:

---

**Default (before changing):**
![grafik](https://github.com/SillyTavern/SillyTavern/assets/143583451/7bda2331-a34b-4204-a205-2c1e5913d59f)

**After changing to "Ross v2", as expected**
![grafik](https://github.com/SillyTavern/SillyTavern/assets/143583451/1ccf315a-4f41-4dc0-9165-6a8c2afeed87)

**Issue with the background after changing back to Default**
![grafik](https://github.com/SillyTavern/SillyTavern/assets/143583451/431ccd91-0897-4f30-a240-b3efbaca6723)

### Additional info

I have updated from v1.10.4 to v1.10.5 (but i dont know if that issue happened before or not).

_**In my opinion, this is a absolutely low priority bug.**_

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by stho90** [comment]
Before you ask: Here are my user settings (if required):

![grafik](https://github.com/SillyTavern/SillyTavern/assets/143583451/f628ea40-b0a6-498d-8294-f4be275b9218)

**Comment by Cohee1207** [comment]
I think the default themes were not updated with the latest changes to colors
@RossAscends possibly it's time to update or create a new theme for 1.10.5
