### ISSUE TITLE
[FEATURE_REQUEST] Chat Bound Lore Book + Dynamic lore book entries from chat messages (for manually selected long term memory)

### ISSUE THREAD

**Issue by stho90** [SillyTavern/SillyTavern#1226]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

See below

### Describe the solution you'd like

Some chat histories are really long. So far I have worked with ChromaDB, Vector Storage or Summarize.
In most cases, the Summarize function still works best, even though I usually write the summaries by hand. (I know that this is not the intended use case.) In it, I summarize most of the important events in short sentences.
But sometimes, the summary gets so long that I tried working with usual Lore Books to relieve its token size. However, lore books in its current implementation are not bound to the chat (local) but are always created across the board (global).

A lore book that would be bound to the chat with a character would be perfect for this: **Chat Bound Lore Book**
Its a lore book that contains some important information about

You could even **expand this feature** with the following features and fill the chat bound lore book with new entries:
- Entries in the Chat Lore Book could be created/extended manually.
- An icon on a chat message (like the translate / copy / edit icons). A lore book entry would then be created automatically after defining certain keywords. Optionally, the text could be filled automatically using certain keywords by using the existing “Summarize Main API” for filling the text of the lore book entry.
- Perhaps you could also bind one (or more) complete chat messages to a chat lore book entry and create a longer context in this way, if required.
- An existing chat bound lore book entry could also be extended by certain specific situations. Example: At the start there is an NPC named Greg. At the beginning all we know is that Greg is my brother. (The Lore Book entry is minimal) After a certain amount of time it is revealed that Greg is 26 years old and works as a musician. The expansion of a lore book entry would be a good idea here.

The following **technical reasons** may speak for this feature:
- "ChromaDB" is not used (for whatever reason)
- "Vector Storage" does not provide the correct entries. In addition, Vectore Storage only allows saving and searching for individual entries. Related chat messages before or after them would not be correctly recorded and related.
- "Summarize" will eventually become too large to store all relevant content

Here are my **personal reasons** for the feature:
- My AI has difficulty remembering certain recurring situations. For example, I come back to my apartment (where I live with Char) for the third or fourth time after a trip and each time the AI tells me in amazement that it is the first time in this place.
- I often abandon conversations with a character because the context becomes too strange. If I have to recalculate an answer 20-30 times after 600 chat messages, then it hurts me to have to cancel the entire story that has developed over many hours.

For me, the feature is a great addition to storing particularly relevant information.
- Summarize is great for summarizing the latest news. (This is enough for most scenarios)
- ChromaDB and Vector Storage deliver good results when it comes to single selective messages
- (Global) Lore Books are great when it comes to describing a mostly unchanging world and can be reused frequently.
- (Local) chat-bound lore books would be more of a combination of "Summarize" and "ChromaDB/Vector Storage", which enable the selective storage of particularly relevant events

Now, its your turn to decide what you think about it 👍 

### Additional context

n.a.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

No

**Comment by valden80** [comment]
Also very useful will be ability to bind the lorebooks to the group chat itself (to store common info for the all characters - like global WI, but without need to manually switch this lorebook on entering this group chat). Right now for the similar effect you need to use global lorebook, or add it to each character in the group chat separately. 
And ability to bind lorebook to the player Personas will be useful too.  
These two is only QoL features, but they will be nice to have.

**Comment by stho90** [comment]
It seems that this feature may have been misunderstood. If I see correctly, then a character-bound lorebook was inserted in the commit "https://github.com/SillyTavern/SillyTavern/commit/6a1b230c7eb261c0cdbc28a05e9cf800f1b58fa8", which represents a character-bound link to the globally available lorebooks.
This is basically a cool feature, but it already existed under the name “Character Lore”. Or did I get this wrong?

What I actually wanted to suggest was a chat-linked lorebook. Here's another example of the structure I had in mind:

```
- World Lore book (Already exists, contains global information of the world)
- Character "Max" -> Character-bound Lore book (Already exists, contains background information about the character)
--- Chat A -> Chat A Lore book (Does not exist, for example contains a merchant called "Thomas")
--- Chat B -> Chat B Lore book (Does not exist, for example contains a merchant called "Maria")
```

Of course, this would also have the advantage that these lore books can also be used for group chats if they are chat-linked.

**Comment by Cohee1207** [comment]
Chat-bound lorebooks were implemented and they should work exactly as you described. Look for the button in the character/group panel when a chat is open.

**Comment by stho90** [comment]
I am sorry, i did not understand how this worked or was intended to be used.
But you are absolutely right! It works!!! 
Thank you very much!

Edit:
Am i allowed to suggest some improvements to that feature in separate Issues?
And, should we close this issue then?

**Comment by Cohee1207** [comment]
Closing this one, move separate improvements to other issues.
