### ISSUE TITLE
[FEATURE_REQUEST] Hierarchical Lore Book Entries / Multi Level Lore Book Entries

### ISSUE THREAD

**Issue by stho90** [SillyTavern/SillyTavern#1227]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

No ( its more an extention of #1226 )

### Describe the solution you'd like

While i described #1226, i thought about hierarchical lore book entries.

Imagine you have a lore book with the entry “Alice”. However, as the conversation progresses, more and more details emerge. At first there is only the following information: "Alice is Bob's sister". As the conversation progresses, more and more details about Alice are added. For example, "Work,Cake : Alice works in a bakery and sells cakes". Then "Childhood, Past: Alice wanted to be an astronaut when she was a child." And so on.

Theoretically I should now create 3 Lore Book entries. But I don't want my Lore Book entries to be accidentally selected incorrectly. After all, there could also be a Lore Book entry for Bob. It could read: "Cake: Bob doesn't like cake."

One solution would be **hierarchical lore book entries** that build on each other.

Technically it could look like this when it comes to storage (although the number of levels could theoretically be lower):
```
Level 0 - Alice : Alice is Bob's sister
Level 1 --- Work,Cake : Alice works in a bakery and sells cakes
Level 1 --- Childhood,Past : Alice wanted to be an astronaut when she was a child
Level 0 - Bob : Bob is Alice's brother
Level 1 --- Cake : Bob doesn't like cake
Level 2 ----- Note like cake, reason : Bob has diabetes
Level 3 ------- Diabetes : Bob has had diabetes since childhood
```

If you now analyze the Hierarchical Lore Book entries, it could work like this:
1.) Search for keyword at “Level 0”
2.) If entry at "Level 0" is found, read out the entry at "Level 0" and all entries at "Level 1". (This could be sensibly implemented with simple Lore Book entries without needing hierarchical Lore Book entries)
3.) The output would now be: "Bob is Alice's brother. Bob doesn't like cake."
4.) If I now ask why Bob doesn't like cake, the lore book would go from "Bob" (Level 0) -> "Cake" (Level 1) -> "Reason" (Level 2)
5.) The output would now be: "Bob is Alice's brother. Bob doesn't like cake. Bob has diabetes."
6.) If I now ask how long Bob has had diabetes, "Level 3" would also be included and the information "Bob has had diabetes since childhood" would be available.

Conclusion:
These types of hierarchical lore book entries would theoretically allow for an almost infinite depth of information and only provide relevant information when requested in ever greater detail.

### Describe alternatives you've considered

n.a.

### Additional context

n.a.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

No

**Comment by Cohee1207** [comment]
This is already possible with the use of recursion when you use some kind of easily identifiable selective key (best with full word key matching) in the top-level entry that will also activate the lower-level entry using the recursive scan. All are within your budgets and according to priority but require careful planning.
