### ISSUE TITLE
[FEATURE_REQUEST] group chats feature request

### ISSUE THREAD

**Issue by equivalentx** [SillyTavern/SillyTavern#1231]
### Have you searched for similar requests?

None

### Is your feature request related to a problem? If so, please describe.

Bots don't see each other bots' descriptions when you send the prompt and context for them to write a message. For example, if there's something that applies to both bots, you can't just include it in one, you either copy the same info in both of them, doubling the tokens, or one of them won't have that info in their context. Even worse if there's more than two bots. Also breaks scenario when one of the bots is narrator, or mind reader, or prophet etc. who can't function without access to other bot's description.

### Describe the solution you'd like

Please add the option to make bots in group chat "see" each other's descriptions and sending all of them in the context, no matter who is typing.

### Describe alternatives you've considered

Stuff all of different characters' description into one bot? Kinda works, but instead of having two bots like Aqua and Darkness, you have to put both their descriptions into one bot and name is something like KonoSubaRP or Aqua and Darkness? It just feels wrong, like a crutch or workaround.

### Additional context

Personally, my "disco elysium skills" narrator bot doesn't function as intended without access to other bots' descriptions, I would love to see this feature implemented asap.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

Yes!

**Comment by Cohee1207** [comment]
Arrange group members' info as WI entries instead of group chat.

**Comment by equivalentx** [comment]
But I want the dialogue between characters, not all of them acting/talking in the same message, so it has to be group chat. Or do i make empty bots and put ALL the info in WI? Again, sounds like a crutch. Also WI is inconvenient to edit. And all these sliders and numbers in WI are intimidating.
![image](https://github.com/SillyTavern/SillyTavern/assets/127750474/f2434099-cd7b-4cf6-97a8-27579b0af775)

**Comment by Cohee1207** [comment]
Empty cards with the definitions in the lorebook will be your solution. You don't need to use every field of the WI editor, just the content and the key being the name. This is much more flexible and have been proven to be working by the community members.

**Comment by equivalentx** [comment]
So if I want to make a chat like this, I need to duplicate the bot, set up new WI entry, move definitions, repeat with each bot, for every new chat? A crutch. Oh well, that's the solution at least. Thanks.

**Comment by equivalentx** [comment]
Oh wait but then you have two bots with the same name and picture, but one is for group chat with empty defs while the other is normal, and you can't {{char}} in WI, in both entries for different character it becomes whoever is typing the message right now, so you have to manually change {{char}} for a name. And the order of entries is fixed in the console even if you swap them in WI. There's no fucking way that's a solution.

**Comment by equivalentx** [comment]
Oh wait but then you have two bots with the same name and picture, but one is for group chat with empty defs while the other is normal, and you can't {{char}} in WI, in both entries for different character it becomes whoever is typing the message right now, so you have to manually change {{char}} for a name. And the order of entries is fixed in the console even if you swap them in WI. And WI windows are still too small to conveniently edit. There's no fucking way that's a solution.

**Comment by ramenramen22** [comment]
That would be nice. I put two cards with the same characters and they don't understand that they're the same person.

**Comment by Cohee1207** [comment]
Added to release 1.10.6
https://docs.sillytavern.app/usage/core-concepts/groupchats/#join-character-cards
