### ISSUE TITLE
[BUG] <error importing from chub>

### ISSUE THREAD

**Issue by stl3** [SillyTavern/SillyTavern#1232]
### Environment

Self-Hosted (Bare Metal)

### System

Vivaldi	6.2.3105.58 (Stable channel) (64-bit)  Revision	160afb130e98d47754ca92d477dfe950a5c0b4c1 OS	Windows 10 Version 21H2 (Build 19044.3324) JavaScript	V8 11.6.189.22

### Version

SillyTavern 1.10.5 'release' (15c81749)

### Describe the problem

I'm trying to import a chub character from it's url. In Termux it's working fine and adding the character but on my windows machine using Vivaldi I'm getting:
```
Importing custom content failed Error: Failed to download character
    at downloadChubCharacter (F:\Programming\GitHub\SillyTavern\src\content-manager.js:125:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async F:\Programming\GitHub\SillyTavern\src\content-manager.js:196:26
```
Console log does show a bunch of stuff but I don't know if I can post it without getting into trouble but it does say `Chub returned error Forbidden` with a bunch of html I think most importantly the part that says "Enable JavaScript and cookies to continue". I tried this in OperaGX and Brave as well with same results. However it works fine in Termux using Vivaldi and Samsung Internet browser (on Android) so I don't know where the issue stems from. 
If anyone has an idea let me know thanks.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)
PS - chub servers also look down atm

**Comment by Cohee1207** [comment]
Not a bug. You got blocked from Chub API by Cloudflare. This happens mostly when your PC is behind a public VPN.

**Comment by stl3** [comment]
Oh that's strange. I'm just connecting directly from my own ip, both my desktop and android are on same local network but only the android can add ext urls.

**Comment by Cohee1207** [comment]
I can't help you here, this is out of my control. If you are on PC, downloading the file will be easier anyway than using the link.

**Comment by stl3** [comment]
Yeah I will just add the card manually, no worries. 
Ahh I found the issue. Apparently node.exe was being routed through TOR (I had it setup like this for some other programs and reasons). Initially I thought that the requests would've been made through the browser which didn't have any special routing so node.exe being the culprit running through TOR didn't cross my mind earlier. This can be closed now. Sorry!
