### ISSUE TITLE
[FEATURE_REQUEST] Entry Title Placeholder should show Lorebook keyword

### ISSUE THREAD

**Issue by digiwombat** [SillyTavern/SillyTavern#1233]
Currently, most lorebooks do not have a specific entry title and, lacking any sort of unified standard for lorebook styling, I think it would be valuable to have the Lorebook Entry Title/Memo display the main keyword as the placeholder as currently it is just a big list of boxes saying the same thing.

**Comment by Cohee1207** [comment]
There's a button to use the entry key as a title. Look closely at the editor toolbar

**Comment by digiwombat** [comment]
Ah, yeah. Had to hover for tooltip. That icon and button location doesn't read as having that purpose, I don't think, so it might be worth a UX pass on that either way. I'll close this regardless since that's workable.
