### ISSUE TITLE
[FEATURE_REQUEST] group chats swipes for non-last messages

### ISSUE THREAD

**Issue by equivalentx** [SillyTavern/SillyTavern#1234]
### Have you searched for similar requests?

None

### Describe the solution you'd like

in group chats messages from different bots are generated one after another, but you can only swipe the last message (bot 2 on pic). it you want to swipe bot 1 message or any message that's not the last one, you have to delete all the messages before it and then swipe. so can you please add swipe button to the messages between the last user's message and the last message in chat (bot 1 message on pic), so if you swipe not last message, it automatically deletes all the messages after it, and then generates them again based on the new swipe. it would be more convenient than manually deleting messages after the one you want to swipe, then swiping, then pressing "trigger the message from the character" at the right.
![image](https://github.com/SillyTavern/SillyTavern/assets/127750474/c89743df-759c-4e13-8bdb-58c334750449)

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

None

**Comment by equivalentx** [comment]
please? someone..?

**Comment by Cohee1207** [comment]
Superseded by #1731
