### ISSUE TITLE
[FEATURE_REQUEST] Map for Adventures/RolePlay with Characters.

### ISSUE THREAD

**Issue by 4Waifu** [SillyTavern/SillyTavern#1235]
### Have you searched for similar requests?

No

### Describe the solution you'd like

-

### Additional context

Honestly i have to clue how to explain, but i will give it a go.
I also want to point out that mine English is broken and i am not a coder or anything related to that, prolly just an average user.

In "Advanced Definitions" add a section/label(preferably a button) with name "Map" (Map is just what i thought of, it could have any related name to this feature)
![breh](https://github.com/SillyTavern/SillyTavern/assets/147554916/42641af8-19d0-4f9d-9d8f-b88fb07831f0)

In "Map" section/button editor/user could open a image, after which they could slice it to multiple sections or just one, either by tapping + to add another section or - to delete previous one.
![breh3](https://github.com/SillyTavern/SillyTavern/assets/147554916/2e08d479-70df-4c9b-9f7a-791ef5c7d731)
OR if editor/user could choose the areas themselves.
![breh4](https://github.com/SillyTavern/SillyTavern/assets/147554916/1094560f-77ed-4538-ab6e-5b20200782d9)
The section will have a Title AKA "School" and Prompt AKA "{{user}} heads to School" that will be sent to AI. (Title and prompt could be edited by editor/user.)
Whenever user will click on that section area in Roleplay menu, the prompt will be sent to AI.
![breh2](https://github.com/SillyTavern/SillyTavern/assets/147554916/d2b3314f-5593-432e-b2d8-ecb55c90bbc4)
(And it would be good if there would be option/setting to hide this type of messages from user for better experience) 

With this feature it's possible to present for Users various locations w/o spending any tokens in character description, cause the prompt will be sent only by user.
Also this is another way to trigger "Worlds/Lorebooks".
There could be a lot of ways to use this feature, for example:
Dungeons with multiple floors.
Home - map with various rooms to click on.
Or just any Roleplay scenario that relates to specific locations, which is also once again could trigger Worlds/Lorebooks w/o spending any tokens in character description.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

None

**Comment by Elthial** [comment]
I was considering trying to make an extension similar in concept to this.

1 Image for the base image then co-ordinates to define a shape for a room, 
OnHover highlight or alternative image swap for that co-ordinates. 
OnClick send a text message (configurable) about the user moving to that location, drop the location lorebook entry for that location into context whilst there.

If possible, track character last mentioned locations and display as icons on the map.
Possibly just an extension that uses and modifies Lorebooks for its own tracking? (Or maybe new json file?)

**Comment by Cohee1207** [comment]
This idea, while sounding interesting, is not something that the project developers are interested in implementing. If someone wants to make it as an extension - it will be fine, we could even make it official by including it in the extensions index.

**Comment by underscorex86** [comment]
@4Waifu you might wanna check out https://github.com/LenAnderson/SillyTavern-Codex
If you're on the discord ping me (underscore).
