### ISSUE TITLE
[FEATURE_REQUEST] Proper summarization(with main API)

### ISSUE THREAD

**Issue by IkariDevGIT** [SillyTavern/SillyTavern#1238]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

yes, the current approach works like this:

```
chatlog...
username: [Summarize the most important facts and events that have happened in the chat so far. If a summary already exists in your memory, use that as a base and expand with new facts. Limit the summary to {{words}} words or less. Your response should include nothing but the summary.]
```

Which is.. very suboptimal to say the least.

### Describe the solution you'd like

A way better approach would let you define something like this:

```
### Instruction: 
Summarize the most important facts and events that have happened in the chat so far. If a summary already exists in your memory, use that as a base and expand with new facts. Limit the summary to {{words}} words or less. Your response should include nothing but the summary.

### Input:
{
{{chat}}
}

### Response:
generated response...
```

There could be multiple other macros such as: wiBefore, wiAfter and so on

### Describe alternatives you've considered

Alternatives are the current ones but almost all models fail at the task or do it very VERY poorly(such as acting as a char)

### Additional context

i stated the idea back in juli(#569) but it was rejected because of the lack of a raw generate dunction, which is now implemented(c4fbc8373d9e4b8ab7eebbf09278fa99326ce10a)

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

Yes!

**Comment by Crozzwise** [comment]
After I had to use summarization recently I had the same experience as the OP; with extremely good prompting and a cooperative model it's possible to get a decent summary right now, but for best results I had to copy the entire prompt and replace the system prompt at the start.
Also I had to set main API temperature very low or zero for no hallucinations, turn off example messages to save tokens and disable repetition penalty for best results.

**Comment by Cohee1207** [comment]
Doable with STscript.
https://docs.sillytavern.app/usage/st-script/
