### ISSUE TITLE
[FEATURE_REQUEST] list of proxy presets within one chat completion preset

### ISSUE THREAD

**Issue by equivalentx** [SillyTavern/SillyTavern#1241]
### Have you searched for similar requests?

None

### Describe the solution you'd like

all presets I have are the same main/nsfw/jailbreak prompts but just different proxy/password/moder, so can you allow to change proxy address and password quickly from drop-out list or something within one preset and without having to change presets so if you've changed your main prompt, for example, you don't have to change it for each preset if you want to switch proxies.
![image](https://github.com/SillyTavern/SillyTavern/assets/127750474/3be06667-15fd-4f00-857a-a1161c312bcb)

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
Keep in mind that proxies are very unlikely to get any additional features from the dev team besides keeping them barely functional. If someone wants to contribute it - welcome.

**Comment by equivalentx** [comment]
of course the won't if you label it low-priority, that's a self-fulfilling prophesy
