### ISSUE TITLE
[FEATURE_REQUEST] Can we have the option to change the "Character Version" display in the Character List to "Created by"?

### ISSUE THREAD

**Issue by CounterfeitMonk** [SillyTavern/SillyTavern#1242]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

n/a

### Describe the solution you'd like

In the Character List, it displays the `Avatar`, `Name`, `Creator's Notes`, and `Character Version` fields:

![botvers](https://github.com/SillyTavern/SillyTavern/assets/147885913/010578dc-57dd-45d2-a656-61ddb8b80fb0)

Could we have the option to change the `Character Version` display to the `Created by` field instead?

![botmaker](https://github.com/SillyTavern/SillyTavern/assets/147885913/51a2830d-e2ba-4d23-adc1-3f03c61dbf8e)

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

None

**Comment by StatuoTW** [comment]
Think this would be a great implementation. The general user does not frequently have multiple of the same cards with differing versions and an option to display the creator (Or, hyper-mode, _sort by creator_) would be amazing.

**Comment by Woisek** [comment]
It's not about having multiple versions from a card, but the latest. Seeing the version number for a quick compare makes more sense and has more value than the display of the creator. But if it's an optional switch, why not.

**Comment by CounterfeitMonk** [comment]
Thanks for adding it in the latest release!
