### ISSUE TITLE
[FEATURE_REQUEST] <World Editor - Scan Depth: box toggle within each entry?>

### ISSUE THREAD

**Issue by AltHeaven001** [SillyTavern/SillyTavern#1244]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

I'm currently experimenting adding example dialogue to the World Editor for a character, as to prevent tokens from piling up within the characters from one response. Although the scan depth plays a big part in this, as it keeps on scanning the message despite it being already over. And there are other keywords that needed to be scanned too.

### Describe the solution you'd like

My solution to this is to add an individual Scan Depth toggle to each entry in the World Editor with a 0-100 range. So when using a scan depth of 1 for that entry, it will use the example dialogue as a reference and never again once it passes the original response so save up on prompt tokens.

### Describe alternatives you've considered

I've considered an idea to revamp the entire Examples of dialogue in the advanced definition section in the character, but I know the Devs don't have time for that. So I considered the Scan Depth toggle as a quicker method for the devs.

I also considered just a Scan Depth: 1 box toggle when I made this request, but I thought of more possibilities that could be made if it were more than just 1 after posting this.

### Additional context

Of course this can be used for something else except for example dialogue like telling the language model to change their writing style temporary when texting or having the character do an action when something present itself and never again.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
I think you're referring to recursive scanning rather than scan depth. This is configurable per entry indeed - look for the "disable recursion" checkbox in the entry editor. It won't insert other entries connected by keywords if recursion is enabled globally.

**Comment by AltHeaven001** [comment]
> I think you're referring to recursive scanning rather than scan depth. This is configurable per entry indeed - look for the "disable recursion" checkbox in the entry editor. It won't insert other entries connected by keywords if recursion is enabled globally.

Recursive scanning is entries can activate other entries by mentioning their keywords in the content text while scan depth defines how many messages in the chat history should be scanned for World Info keys. 

I am referring to scan depth in this, and with the feature request is being able to enable via checkbox on scan depth to a single entry with a 0-100 range (or lower). So some entries can be temporary while others can stay. I'm not speaking of the Non-recursable option and being connected to other entries you speak of. Apologies for any confusion.
