### ISSUE TITLE
[FEATURE_REQUEST] allow to change persona when editing a message

### ISSUE THREAD

**Issue by equivalentx** [SillyTavern/SillyTavern#1246]
### Have you searched for similar requests?

None

### Describe the solution you'd like

so i accidentally used wrong persona in the chat and now i can't change my name for my previous messages without deleting big part of the chat history. would be nice to be able to change persona or at least edit the name when editing the message.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
You can force synchronization of the persona to assign it to every user message in the chat. There's a button in the persona management or /sync slash command.
