### ISSUE TITLE
[FEATURE_REQUEST] Multiple choice world entries driven by probability

### ISSUE THREAD

**Issue by GentlemanOfCulture** [SillyTavern/SillyTavern#1247]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

There seems to be no multiple choice system for world entries. For example, if I want to have the key words "enters the portal" linked to four different possibilities, the best I can do is create four different world entries. I can set the probability of all four world entries to 25%, and have them all trigger with the key words "enters the portal", but the probability of each world entry being selected is calculated independent of the others, so there's a chance that no world entry will be triggered, or that multiple world entries will be triggered.

### Describe the solution you'd like

I suggest creating a tagging system for world entries, similar to the tagging system used for characters. With such a tagging system, world entries that share tags could be linked together in a 'probability group'. If shared key words are triggered within a group, then probability would be calculated for the group as a whole, as opposed to calculating the probability of each entry independently.

So, to use my above example, if the key words "enters the portal" were to be triggered for a probability group, then the combined probability of my four possibilities would amount to 100%, and one single world entry would be chosen from the group every single time, with each having a 25% chance of being chosen.

If the combined probability of a group is lower than 100%, then there will simply be a chance that no possibility is chosen.

If the combined probability of the group exceeds 100%, then the probability that the user set for each world entry in the group will be multiplied by whatever fraction is necessary to bring the total probability of the group down to 100% for the multiple choice selection. For example, if the combined probability of the group equals 200%, then the probability of each individual world entry in that group would be halved for the selection.

### Describe alternatives you've considered

Another solution would be to allow for multiple content boxes within each world entry, and allow the user to assign a probability value for each content box, though I imagine that would be far more tedious to implement than a tagging system.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

No

**Comment by underscorex86** [comment]
You can achieve this in existing WI with a couple of extra steps.

Parent Entry 001 - "Enters a Portal"

001 Child A - 100% probability, NOT criteria (a phrase from Child B entry, a phrase from Child C entry)
001 Child B - 66% probability, NOT criteria (a phrase from Child C entry)
001 Child C - 33% probability.

And ensure recursive scanning is enabled and all child entries are recursable.

**Comment by GentlemanOfCulture** [comment]
Thank you. I never thought of that method. Though, it does appear to have its downsides. For bigger multiple choice selections, it's very tedious. Adding a new entry to an existing multiple choice selection requires editing all other entries. The wording of entries cannot be freely changed without carefully ensuring that the NOT phrase used by other entries has not been infringed on.

For those reasons, I'd still press for the above solution.

**Comment by Cohee1207** [comment]
Implemented 

<img width="321" alt="image" src="https://github.com/SillyTavern/SillyTavern/assets/18619528/1bc68af8-165a-481a-9771-93d2b6e72795">
