### ISSUE TITLE
[BUG] <UI Border cut off at the top>

### ISSUE THREAD

**Issue by Daviljoe193** [SillyTavern/SillyTavern#1251]
### Environment

Self-Hosted (Bare Metal)

### System

Brave 1.57.64, Ubuntu 23.04

### Version

SillyTavern 1.10.6 'staging' (59af85ce)

### Desktop Information

- Node.js version (if applicable): [v18.13.0]
- Generation API [Not applicable]
- Branch [staging]
- Model [Not applicable]

### Describe the problem

The UI Border on the chat window is kinda cut off at the top. It looked fine in commit [61f164b](https://github.com/SillyTavern/SillyTavern/commit/61f164b5ff860f0615ce90e13978cf7676ac6c19), but the moment I updated to commit [658701a](https://github.com/SillyTavern/SillyTavern/commit/658701a9437495ae5a84d654deb6fb33989bdb62), the top part of the outline vanished completely. Latest commit [59af85c](https://github.com/SillyTavern/SillyTavern/commit/59af85ce1c7505df239dfb031008c38b70b90397) still has this issue as well. This happens exactly the same on Firefox too.

### Additional info

![127 0 0 1_8000_ (27)](https://github.com/SillyTavern/SillyTavern/assets/67191631/b23dcb6d-52cc-4d5e-975c-72106be04d79)
![127 0 0 1_8000_ (28)](https://github.com/SillyTavern/SillyTavern/assets/67191631/2ec2e8a7-db93-4cdc-a201-800d0e9751fb)
![127 0 0 1_8000_ (29)](https://github.com/SillyTavern/SillyTavern/assets/67191631/763b7117-6baa-4695-9274-690f89851447)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [x] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
@RossAscends was this intended? The line of styles that adds the border in question was commented out, I suppose on purpose

**Comment by Daviljoe193** [comment]
It's a bit odd though that it would be intentional if it makes the border incomplete. It honestly looks like it shouldn't be like this.

**Comment by Cohee1207** [comment]
The border you see might actually come from the message block, not the top bar. Here is how it looks in my UI theme colors (welcome message scrolled all the way to the top). Notice there's no border at all around the top bar. The top border of the message block is actually obstructed by the top bar shadow, but it's still there.
<img width="739" alt="image" src="https://github.com/SillyTavern/SillyTavern/assets/18619528/7386adc4-1834-486c-a6ec-5ece0213fa83">

**Comment by Daviljoe193** [comment]
Sorry for not being able to respond sooner. I'm specifically talking about when the browser window is narrow enough that the chat window is made to fill the entire width, rather than have negative space to the left and right. When it's narrow enough, the border color should surround the whole window, as shown below with the worst color scheme I could possibly cook up (For border visibility).

![127 0 0 1_8000_ (31)](https://github.com/SillyTavern/SillyTavern/assets/67191631/592d79df-2083-447c-bb0c-67521c6127ac)

VS how it's wrong in commits after 61f164b (Same exact theme, but there are other differences, like how separators aren't the right color)

![127 0 0 1_8000_ (30)](https://github.com/SillyTavern/SillyTavern/assets/67191631/bee4b2db-ca4f-4a87-8fcb-eb4780598599)

Also, browser maximized, the outline that should be there...

![127 0 0 1_8000_ (32)](https://github.com/SillyTavern/SillyTavern/assets/67191631/ad1cb9d9-9852-4e8e-9b70-d0e9920f3d62)

...is completely gone, not just on the top, but all around the chat part. (And the grab handle thing also uses the wrong color)

![127 0 0 1_8000_ (33)](https://github.com/SillyTavern/SillyTavern/assets/67191631/658ab6bc-b9a9-4206-9134-cf83c46f1bd9)

Just seems like this was an accident, and not intentional.

**Comment by luimu64** [comment]
This can be fixed very easily by uncommenting these lines
https://github.com/SillyTavern/SillyTavern/blob/1d32749ed26a6d2916f5b1b98380019c50215d0b/public/style.css#L579
https://github.com/SillyTavern/SillyTavern/blob/1d32749ed26a6d2916f5b1b98380019c50215d0b/public/style.css#L580
https://github.com/SillyTavern/SillyTavern/blob/1d32749ed26a6d2916f5b1b98380019c50215d0b/public/style.css#L581
https://github.com/SillyTavern/SillyTavern/blob/1d32749ed26a6d2916f5b1b98380019c50215d0b/public/style.css#L484
which leads me to believe this is intentional design choice rather than a bug.
