### ISSUE TITLE
[BUG] Character search is very innacurate

### ISSUE THREAD

**Issue by Avroboros** [SillyTavern/SillyTavern#1259]
### Environment

Self-Hosted (Bare Metal)

### System

Windows 11

### Version

1.10.5

### Describe the problem

Searching for character's names or adding characters into groups are worthless due to the innacuracy of searches not matching with the characters inputed. 

EXAMPLE : You create a One Piece RP group, then you go add-in the members and let's say you wanna add Monkey D. Luffy first. So you type : "Monkey" "Mo" "M" "Mon" "Luffy"... and the search pulls out every single character imaginable EXCEPT the one you're looking for by its name. 

This is very problematic when you have hundreds of characters, and you have to scroll across the entire alphabet just to get one character.

THEN, the process restarts all over again.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Disable "Advanced search" in user settings.

**Comment by Avroboros** [comment]
That fixed it, thanks.

**Comment by Cohee1207** [comment]
I updated the advanced search to add more bias for the character name compared to other fields.
