### ISSUE TITLE
Telling the AI to generate World Info by itself

### ISSUE THREAD

**Issue by trihardseven** [SillyTavern/SillyTavern#126]
**Is your feature request related to a problem? Please describe.**
Having to type out world info is a pain, so almost no one uses it.

**Describe the solution you'd like**
Make it so you only need to write the keywords and a prompt. The AI then takes the context of the story in consideration to make the content for you and automatically inserts it there. (novelAI has a similar system you can check out.) 

How it works in NovelAI: 
<img width="587" alt="example" src="https://user-images.githubusercontent.com/54422205/233535481-ab842e68-025f-437a-b95a-95996315f910.PNG">

**Comment by Miraihi** [comment]
This! I often switch to the koboldcpp lite interface just to generate the world info entry. I'm sure it's entirely possible to have this as a built-in function.
