### ISSUE TITLE
[FEATURE_REQUEST] LM Studio for Local Inference Server?

### ISSUE THREAD

**Issue by ProjCRys** [SillyTavern/SillyTavern#1264]
### Have you searched for similar requests?

None

### Describe the solution you'd like

I know there is oobabooga text gen as an API for models, but can you add more alternatives for oobabooga such as LM Studio? 

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
LM Studio provides an inference endpoint compatible with OpenAI. Use it.

**Comment by ProjCRys** [comment]
Oh sorry what I mean is that it can use local language models like oobabooga. I tried Autogen and connecting it to LM Studio using Mistral 7b model.

**Comment by Cohee1207** [comment]
I mean it provides an inferencing endpoint compatible with the OpenAI proxy format. 
Overall, the community looks down on LM Studio as it's not open source, so stay on koboldcpp or oobabooga.

**Comment by Cohee1207** [comment]
Try Kobold, it is compatible with SillyTavern natively. Provides the same functionality (both are based on llamacpp) and is open source.
https://github.com/LostRuins/koboldcpp

**Comment by Cohee1207** [comment]
Supported if used as a Custom endpoint for chat completions, I tested and it works. No need for a separate option.
https://docs.sillytavern.app/usage/api-connections/openai/#proxy
