### ISSUE TITLE
[BUG] Missing top control buttons on the messages

### ISSUE THREAD

**Issue by valden80** [SillyTavern/SillyTavern#1272]
### Environment

Self-Hosted (Bare Metal)

### System

Firefox 115.2.0esr, Manjaro current.

### Version

SillyTavern 1.10.6 staging

### Desktop Information

 - OS/Device: Manjaro Linux
 - Environment: local
 - Node.js: version 20.2.0
 - Browser: Firefox
 - Generation API: Oobaboga
 - Branch: staging
 - Model: any local

### Describe the problem

At current commit (b41bf7cf4e7dac17eec780bf8ced19c6dbc4e981) header of the messages become this:
![No control buttons](https://github.com/SillyTavern/SillyTavern/assets/111227649/00ed6246-ccd3-4a89-a89e-dd47a5bb02c3)
No other options (translate, SD, etc.)

### Additional info

The only error I see in the browser console is:
```
Uncaught (in promise) Error: HTTP 401: {"detail":{"status":"invalid_api_key","message":"Invalid API key: ''"}}
    fetchTtsVoiceObjects http://127.0.0.1:8000/scripts/extensions/tts/elevenlabs.js line 2 > importedModule:169
```
Maybe completely unrelated.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by valden80** [comment]
UPD: In commit 7f8df9533b28159e233a10cab2a3cddd0d318949 still ok.

UPD2: Maybe related to the "Expand Message Actions" option - I have it turned on.

**Comment by Cohee1207** [comment]
> UPD2: Maybe related to the "Expand Message Actions" option - I have it turned on.

Yes, it is. I fixed it, thanks for bringing it up.
