### ISSUE TITLE
[FEATURE_REQUEST] Add ability to manually move the context cutoff line.

### ISSUE THREAD

**Issue by Barafu** [SillyTavern/SillyTavern#1276]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

The way to notably improve the speed of chatting with a large (30b-70b) model running on a consumer PC. 

### The idea
You know the yellow dotted line which denotes the part of the message history that actually goes into the context? Please add the ability to manually move it forward. At least as a slash-command to move it to the current chat end. It would mean clearing the message history from the prompt, but not from the user's view. 

### The use case
I am running a 70b model locally, on a single 4090 GPU, using KoboldCPP.  The reply in a long chat with a full context takes a lot of time: First, three minutes to read the prompt, then two minutes to type an answer. I have found that waiting for a reply is not annoying when the machine is already typing, but waiting for the first token for three minutes is what is really annoying. 

Luckily, there is a way to avoid that part : before the chat history fills completely,  the system only needs to read the added text between replies, so it takes only a few seconds instead of few minutes. Once the chat length reaches the context size, I use "summarize" feature to compress the chat history, delete all messages and can continue again. 

This is where my request comes: please add the ability to delete all messages only from the machine's view, but leave them on the screen for the user's reference. 

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
Why not just decrease the context size?

**Comment by Barafu** [comment]
If you decrease it to 512 it won't work, and anything bigger is still longer to wait than the way I use it. If have a small context size and leave it alone, it slides with every message (once it is full) and has to be reevaluated fully with every message. If have a long context size and allow it to grow, the system only needs to evaluate the new text (200-500 tokens) per message untill the context fills up. Once the context is filled, instead of letting the context to start sliding, I just start a new one. 

It is a very fast method, allowing to get a response in a minute from a 70b model. With only 10 seconds to wait for a first token. I just want it to become more seamless, and with less manual upkeep when starting a new context.

**Comment by GentlemanOfCulture** [comment]
I second this request, because I think this feature would be very useful for group chats, adventures, and long roleplay sessions. For example, lets say I have a conversation with a character in the lobby of a hotel before leaving the hotel and entering a bar. When I enter the bar, I strike up a conversation with a different character.

The problem is the character in the bar pulls from the context of the first conversation that I had in the hotel even though the character in the bar should not be aware of any of that stuff. There are obvious ways to stop this from happening but it would be much easier to be able to just set a context cutoff point that begins the moment I enter the bar.

**Comment by Woisek** [comment]
> There are obvious ways to stop this from happening but it would be much easier to be able to just set a context cutoff point that begins the moment I enter the bar.

And if you return to the previous character, he doesn't know anything about your conversation you had with it earlier ... does it?

**Comment by Cohee1207** [comment]
You can use `/hide` command or the message action to manually remove messages or a range of messages from the context.
