### ISSUE TITLE
[FEATURE_REQUEST] Notepad to safekeep information that can be used later on that doesn't consuming tokens

### ISSUE THREAD

**Issue by Avroboros** [SillyTavern/SillyTavern#1279]
### Have you searched for similar requests?

None

### Describe the solution you'd like

A notepad of sorts attached to a character's profile to safekeep information that could be used later on.

Whenever i RP with characters, i have the habit of cutting or adding information inside the {{char}}'s description, attributes, personality, memory... etc to match up with the current "stage" of the RP. Such as "After {{user}} and {{char}} did this..., {{char}} is more attached to {{user}}." or "{{user}} and {{char}} are now doing this after this something happened" or "Whenever {{user}} does this to {{char}}, {{char}} behaves this way ever since this something happened" and other similar strips of information and descriptions that enhance the RP after the occurance of facts, for the character to remember and keep inside their "memory" (thus increasing the amount of tokens in one's character).

However, sometimes i remove these strips whenever i start a new chat (or begin a new scenario or modifying the {{char}} in some way), and it can be annoying to rewrite them again over and over again. (or to keep them inside a separate notepad as a text file so that i can reuse these strips of information later on).

So what i thought : Make a little button to access some sort of notepad that you can keep any sort of information in inside the specific character's profile, which doesn't consume any tokens since its a place only meant to keep information that you can safely access and modify to then implement into the {{char}}'s "memory" or features later-on and etc. So therefore the ai model will not take into account these tokens, since it will not "apply" them (unlike how it applies any token found in description, personality summary, scenario, character's note.. etc). This place to write in all this additional information could also prove to be useful to already write and predict events, traits and etc of the {{char}} later on depending on how the RP goes.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
You can use the "Character Author's Note (Private)" section in the Author's Note menu without enabling it ("Use character author's note" should be off). This part is unique to your install (saved to settings.json and won't be part of the exported cards).

**Comment by Avroboros** [comment]
Oh i didn't think about that. However sadly when i create a new persona the "persona description", constantly keeps the same one across different personas even if i click on different ones to try modifying them.

**Comment by Cohee1207** [comment]
Personas and character notes are not related, so I assume you're facing a different problem.
But it seems that you are trying to add a description to an avatar that doesn't have a name bound to it. It would make the changes temporary. To save you changes, you first add a name to the image (converting it to persona), and then add a description.

**Comment by Avroboros** [comment]
Oh nevermind i just saw what you meant, thanks. Okay then that solves the issue concerning the strings of information in one's character. Here's a screenshot for any future people looking where you can find this (since i still don't know very much about SillyTavern's interface yet)
![image](https://github.com/SillyTavern/SillyTavern/assets/146421595/70073aca-26cd-40c7-8fbf-001eb49969bb)
