### ISSUE TITLE
[BUG] Vector storage not injecting the correct context

### ISSUE THREAD

**Issue by xNissX233** [SillyTavern/SillyTavern#1280]
### Environment

Self-Hosted (Bare Metal)

### System

Firefox 118.0.2, EndeavourOS

### Version

1.10.5

### Desktop Information

-Node 20.1.8
-KoboldAI
-Brach release
-Model MLewd-ReMM-L2-Chat-20B.q5_K_M

### Describe the problem

Vector storage works weird. First of all, it injects a random amount of messages even if I tells it to inject a particular amount, it uses that amount more like a max number of things to inject. I mention that because it may be related (or maybe not) with the main issue I have, which is that it doesn't inject what's needed at all. 
You can tell the character something with a very specific phrase, and if you say a similar phrase again after some time, vector storage won't inject the old phrase in the context, so if for example I say:
-"you like the color blue a lot"
and then after a while I say:
-"what color do you like a lot?" (or even the exact same phrase)
the previous phrase won't be injected, instead some random context will...

I tried setting the Query variable to 1 so only my last message is considered, and same result.

### Additional info

It happens with all characters and models. It's something that didn't happen with the old smart context plugin from extras.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
> that amount more like a max number of things to inject

Yes, you're right. It is reduced if the vector matches with some messages from the Retain# of the latest messages. It serves two purposes:

1. Prevent displacing recent messages from the context, as this is the most important thing when generating text, and doing so may break the logical flow.
2. Prevent inserting unrelated past messages. For example, if you queried 3 messages and all of them are in the latest retained messages, then it instead of inserting the next 3, which are less related to the input, it inserts nothing at all, as the most important information is already included in the prompt.

**Comment by xNissX233** [comment]
> > that amount more like a max number of things to inject
> 
> Yes, you're right. It is reduced if the vector matches with some messages from the Retain# of the latest messages. It serves two purposes:
> 
>     1. Prevent displacing recent messages from the context, as this is the most important thing when generating text, and doing so may break the logical flow.
> 
>     2. Prevent inserting unrelated past messages. For example, if you queried 3 messages and all of them are in the latest retained messages, then it instead of inserting the next 3, which are less related to the input, it inserts nothing at all, as the most important information is already included in the prompt.

If it's intended then it's fine, but I still don't think that the main problem I said I have is an intended thing or a feature.

**Comment by Cohee1207** [comment]
As for the next question - vector DB is very hard to debug if issues like this arise, impossible even, I'd say. As there is no logic that could be unwrapped, it all depends on the outputs of the embedding model (I assume you're using the local source).

**Comment by xNissX233** [comment]
> As for the next question - vector DB is very hard to debug if issues like this arise, impossible even, I'd say. As there is no logic that could be unwrapped, it all depends on the outputs of the embedding model (I assume you're using the local source).

do it depends on the model I use then?

**Comment by Cohee1207** [comment]
Yes. What the plugin does is compare the raw numbers between the historical data and recent inputs. The actual numbers are determined by the model. If you have an opportunity - try the OpenAI's model and see if it's any better.
