### ISSUE TITLE
[FEATURE_REQUEST] Insert response into past context

### ISSUE THREAD

**Issue by GentlemanOfCulture** [SillyTavern/SillyTavern#1282]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Lets say there are five characters sitting in the stadium of an arena watching two fighters clash on the arena floor. One of the fighters in the arena lands a critical hit, and I, the user, want the five characters in the audience to react to that event.

Here's the problem. The first character reacts without issue, but the fifth character may not strongly react to the event, because the event is buried behind 4 other responses and those 4 responses have a much higher weight than the now buried event.

I can manually fix this by deleting, copying, and pasting messages, but doing so is slow and tedious.

### Describe the solution you'd like

I would like an option to highlight a past message in the context and have new replies be generated from that point on, with each new reply being inserted into the context directly after the highlighted response. The highlighted message should be treated as the last response in the context, ignoring any messages that come after it.

To go back to my above example, I could highlight the critical hit that happened on the arena floor, and then click on all 5 of my characters to see their immediate response to that event. I could then un-highlight the critical hit to have my characters engage in normal discussion amongst themselves.

### Describe alternatives you've considered

Giving the user the ability to manually highlight responses or whole characters that are to be ignored in the generation of the next response could work as well.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

No

**Comment by Cohee1207** [comment]
I usually don't like the idea of being able to misplace messages out of their intended order as it breaks the logical flow of the conversation. Right now there's a built-in ability to move messages up and down from the message edit menu. Have you tried it out? Does it perhaps suit your purpose?

**Comment by GentlemanOfCulture** [comment]
I have tried that function out. I could repeatedly move the critical hit event in my example down before clicking on each respective character to give the critical hit event more importance in the context, but that doesn't really do what I want it to do, because the responses of the other characters are still being factored in, which often leads to cross dialogue between characters.

In my example, the goal was to get the immediate reaction of every character to the event itself before allowing dialogue between characters to begin.

**Comment by Cohee1207** [comment]
Would you maybe also try out adding that particular event to the chat lorebook and placing the entry at a specific depth, while also making it constant? Chat lorebooks are currently only available at the staging branch.

**Comment by GentlemanOfCulture** [comment]
I suppose I could try copying the event to a lore entry at depth 0 or 1, and repeating the message a few times to drown out the responses of the other characters in group chat. Then I could disable the lore entry when I want my characters to engage in normal dialogue again.

**Comment by Cohee1207** [comment]
> Giving the user the ability to manually highlight responses or whole characters that are to be ignored in the generation of the next response could work as well.

This was done. Use "eye" icon or /hide command on the message you'd like to hide.
