### ISSUE TITLE
[BUG] RVC not working after "Convert to group"

### ISSUE THREAD

**Issue by m1nuzz** [SillyTavern/SillyTavern#1284]
### Environment

Self-Hosted (Bare Metal)

### System

Win 11

### Version

1.10.5

### Describe the problem

If there is a chat history with a character and you want to connect another character to this history through the "Convert to group" function, RVC stops working on the character on which this function was applied, to fix this it helps to change the name of the character to another and add RVC to it again. 

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Should have been fixed in 1.11.2, please check.
