### ISSUE TITLE
[BUG] Issues with mobile SillyTavern

### ISSUE THREAD

**Issue by Orion-jpeg** [SillyTavern/SillyTavern#1286]
### Environment

Android (Termux)

### System

OS Android 12, Client: Firefox and Chrome

### Version

1.10.5

### Desktop Information

- v20.2.0
- NovelAI
- Release
- Kayra 13b

### Describe the problem

I was using 1.10.3 up until recently, which I had experienced no issues with, nor have I experienced this bug in any previous version. But after I had recently swapped to 1.10.5 it has been quite difficult to use, and I haven't seen anyone with this particular issue. My best description of what happens is that SillyTavern fails to load in. Backgrounds and Characters won't load in, unless I turn off and on my phone, or exit chrome itself. Same for story generation, which will freeze if I enter any {{user}} input. Expanding a character image suffers from the same thing strangely enough. I doubt it is a browser issue, as I tested with chrome and firefox, and got the same issues.  

Though my pc version of SillyTavern does not have any these issues. And up until this recent update I've had no issues until now with any previous model of mobile SillyTavern. 

### Additional info

Not sure how to check chrome logs on mobile, though nothing particularly out of place popped up in the console.
1. SillyTavern screen was frozen after I clicked the send, which didn't give any kind of pressed response.
![IMG_20231025_162011](https://github.com/SillyTavern/SillyTavern/assets/67085001/e67229a7-9f57-4271-98f5-e9d9138e7831)
2. I found that when I exited the chrome screen, it would finally pop up, which would be counted in the Char. Gen. Also expanding the image will often require the same thing.
![IMG_20231025_161246](https://github.com/SillyTavern/SillyTavern/assets/67085001/585ba936-3155-4e4e-970d-494bda291704)
3. This is how quickly it would work when I used it recently in the 1.10.3
![IMG_20231025_161907](https://github.com/SillyTavern/SillyTavern/assets/67085001/63058d63-e479-43c4-bf14-67d5dbdf233a)
4. Characters and backgrounds will sometimes fail to load in. 
![Screenshot_2023-10-25-16-11-56-89_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/SillyTavern/SillyTavern/assets/67085001/089bfd2b-d3ba-4663-8944-baa52020e282)
5. When they don't load in and you choose them, they won't appear.
![IMG_20231025_161831](https://github.com/SillyTavern/SillyTavern/assets/67085001/887918fd-fd15-468d-9419-b0512407fff5)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Does it reproduce on the clean install? Or is it specific to your instance? Are there any extensions you use?

**Comment by Orion-jpeg** [comment]
Will try a clean install tomorrow, but aside from NAI hypebot, no I am not using an extension.

**Comment by Orion-jpeg** [comment]
I've done 2 clean installs, moved to the newest update, and swapped between release and staging branches. No luck so far, but at this point I assume the issue is with my specific instance.

**Comment by Cohee1207** [comment]
Make sure you're not copying the entire public folder between the instances. Have you tried a completely clean install?

**Comment by Orion-jpeg** [comment]
I cut and moved a lot of the data(Couldn't remember what held the character data) to my phone's download inside of a new unaffiliated folder, and used Termux to delete what couldn't be transferred, then deleted Termux itself. I reinstalled termux and had to reinstall the normal method including git and everything. So I believe it was a clean install, I have not done more aside from readd the api, but testing with a character the issues seem to persist.
