### ISSUE TITLE
[FEATURE_REQUEST] Custom CSS Presets

### ISSUE THREAD

**Issue by kalomaze** [SillyTavern/SillyTavern#1287]
### Have you searched for similar requests?

None

### Is your feature request related to a problem? If so, please describe.

N/A

### Describe the solution you'd like

A feature for Custom CSS presets that people can submit to be included with SillyTavern itself.
For example, "Italicized Prose" could be a preset which just recreates the asterisks visual effect for all text that's not seen in quotation marks.

```
.mes_text {
    font-style: italic;
    color: grey;
}

.mes_text q {
    font-style: normal;
}
```

### Additional context

I might implement this myself.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

Maybe

**Comment by Cohee1207** [comment]
Custom CSS is already a part of UI theme. Also people can submit their custom CSS as scripts for stylus browser extension.

**Comment by Woisek** [comment]
> Custom CSS is already a part of UI theme.

@Cohee1207 If you refer to the CSS box ... As I already mentioned on the discord, the use of a 'user.css' would be much more convenient. 🙂

**Comment by Cohee1207** [comment]
@Woisek 
I just added a user.css. Don't know how exactly it solves kalomaze's issue tho.

**Comment by Woisek** [comment]
@Cohee1207 Many thanks for this, I really appreciate it. 👍

@ kalomaze issue: It can help in that case, that, even if there aren't such presets as he wants offered by ST natively (yet?), he (or everybody else de facto) could create his own 'preset' and then either write and add it into the user.css or, if organization is a thing, write it as a css file and @import it into the user.css, making the user.css a 'hub' for all styling needs one has.
I use this system with A1111/SD:Next for some time now, and it works perfect.
