### ISSUE TITLE
[BUG] open multiple listening ports on  Mac?

### ISSUE THREAD

**Issue by DoshideDK** [SillyTavern/SillyTavern#1293]
### Environment

Self-Hosted (Bare Metal)

### System

macOS

### Version

1.10.5

### Describe the problem

Hello, author. May I inquire how to open multiple listening ports on a Mac? 

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
ST can only listen on one port. If you need several instances - run multiple instances and change the hosting port in config.conf file of each one. This is true for all operating systems.
