### ISSUE TITLE
[BUG] NOT Character Lorebook Entries do not export correctly 

### ISSUE THREAD

**Issue by vintner-coder** [SillyTavern/SillyTavern#1294]
### Environment

Self-Hosted (Bare Metal)

### System

Microsoft Edge, my friend's Chrome

### Version

1.10.7

### Describe the problem

NOT clauses do not seem to export correctly for Character Lorebook selective entries. Instead, it seems to export as an AND. 

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Reproduced and fixed in staging, many thanks.

**Comment by vintner-coder** [comment]
Confirmed that this is fixed on the latest version of staging. Thanks!
