### ISSUE TITLE
[BUG] Tokens are different between versions 1.10.5 and 1.10.7 (and version 1.10.7 adds tokens for no reason)

### ISSUE THREAD

**Issue by Avroboros** [SillyTavern/SillyTavern#1295]
### Environment

Self-Hosted (Bare Metal)

### System

Windows 11

### Version

1.10.5 and 1.10.7

### Describe the problem

Hi, I created the following character (Katsuki Bakugo) with SillyTavern 1.10.7 (i managed to compress all his attributes, traits and etc to 1.250 tokens). However, after RPing with him for a bit as a test drive, the tokens out of nowhere went to 1.311 while i added nothing. I reverted back to SillyTavern 1.10.5 and found out that the tokens remain at 1.250 in that version, with the new one adding more tokens for no reason.

Pic 1 = character tokens in SillyTavern 1.10.5 and in 1.10.7 before i started RPing
Pic 2 = character tokens in SillyTavern 1.10.7 AFTER i started the test RP

![image](https://github.com/SillyTavern/SillyTavern/assets/146421595/f77c5458-3d8f-4642-a94c-d52276d9610b)
![image](https://github.com/SillyTavern/SillyTavern/assets/146421595/b0494e0d-001a-41ec-8a8b-5ea378ff6387)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Added tokens are the result of replacing macro in the character data before counting. That would make it more accurate to what is actually being sent to the model.

**Comment by Avroboros** [comment]
Is there a way to check the number of tokens involved in that? (to see how many you'd have to take into account and etc)

**Comment by Cohee1207** [comment]
This is just the way of counting. Doesn't mean that "this version adds more tokens to the prompt", but "this version does accurately represent the number of tokens after the transformation of macro into the prompt".

**Comment by Cohee1207** [comment]
For example `{{user}}` is just 4 tokens always, no matter how many tokens there are in your actual user name. The count will go up or down depending on how long is the current user name.

**Comment by Avroboros** [comment]
Understandable, but thanks for the clarification, it made me confused seeing the number go up out of nowhere unexpectedly after a few messages. From what i've counted the transformation of the macro adds up 61 (~100) tokens to the number, so i'll keep that in mind now.
