### ISSUE TITLE
[FEATURE_REQUEST] Autogen Implementation

### ISSUE THREAD

**Issue by rosx27** [SillyTavern/SillyTavern#1296]
### Have you searched for similar requests?

Yes

### Describe the solution you'd like

Implementation of autogen within the user interface. I think this is the only missing features of sillytavern to be an all-in-one user interface for both online and offline inference.

### Describe alternatives you've considered

A implementation of [UI ](https://github.com/victordibia/autogen-ui) is already being developed, however, a one-stop UI is absolutely preferable (at least for me).

### Additional context

https://github.com/microsoft/autogen

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
This tool is not something I'm familiar with. If it could be implemented as an extension plugin with help from someone intelligible about agents/langchains/autogen - that would be great.

**Comment by rosx27** [comment]
I was trying to create a UI for this earlier but found that there is already a ui and thought that why not use sillytavern for this since its way more feature-rich frontend. I'm searching on how to create a extension for this but failing.

**Comment by Cohee1207** [comment]
There's a doc page for SillyTavern extension authors with links to some examples:
https://docs.sillytavern.app/for-contributors/writing-extensions/

**Comment by rosx27** [comment]
yeah i'm reviewing it right now. looking at an [existing proxy ](https://github.com/anon998/simple-proxy-for-tavern) for sillytavern gave me an idea on how to implement this.

**Comment by rosx27** [comment]
i think other way of implementing this feature would be [this](https://github.com/SillyTavern/SillyTavern/issues/1402#issuecomment-1851335338)
