### ISSUE TITLE
[FEATURE_REQUEST] MemGPT Implementation - True Unlimited Memory

### ISSUE THREAD

**Issue by amantuer** [SillyTavern/SillyTavern#1297]
### Have you searched for similar requests?

Yes

### Describe the solution you'd like

Implementation of memgpt within the user interface. I think this is the only missing features of sillytavern to be an all-in-one user interface of true unlimited memory for both online and offline inference.

### Describe alternatives you've considered

No UI implementation is currently being developed, furthermore, a one-stop UI is highly preferred.

### Additional context

https://github.com/cpacker/MemGPT

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

None

**Comment by rosx27** [comment]
Funny, i was going to request this alongside with autogen. Reading your request kinda makes me think that you copy-pasted my request for autogen haha

**Comment by amantuer** [comment]
@rosx27 Yeah, I did copy and paste your autogen request, but I specifically requested it for memgpt since I noticed no one else had done so. Additionally, your request aligns closely with what I had in mind, and considering my limited English proficiency, I hope you understand my reasoning.

**Comment by rosx27** [comment]
no no, by all means dude! did you come across the vids of [matthew berman](https://www.youtube.com/@matthew_berman) from youtube too? he was going to release a vid about intigrating autogen with memgpt. that is why I requested for autogen first, thinking that when he finally released the vid, I'd be able to try and intigrate it too (provided that, by that time, this request is implemented).

**Comment by amantuer** [comment]
@rosx27 Yeah, I watched that guy's videos. He created some good tutorials about LLMs, and I learned a lot from him. I also hope that the integration of autogen and memgpt can be completed soon. By that time, SillyTraven having all these features would be a work of art.

**Comment by Cohee1207** [comment]
MemGPT the same summary and vectors that are already implemented and proven not viable for its intended purpose with our specifics. 

See here for my detailed statement on similar request: https://github.com/SillyTavern/SillyTavern/issues/1212#issuecomment-1743648032

**Comment by amantuer** [comment]
@Cohee1207 I'm not very familiar with vector storage, so I consulted chatGPT (GPT4 with Bing search plugin) to find evidence that disproves your claim. Here is what it provided:

The comments you shared express skepticism regarding vector storage in the context of MemGPT, primarily focusing on its potential limitations in simulating memory for chat-based role play (RP) beyond a simple question and answer format. The commenter suggests that the vector storage won't effectively handle the retrieval of past conversational context unless directly triggered by recent inputs. However, based on the information gathered from various sources, it appears that MemGPT has been designed to address the mentioned concerns to a considerable extent. Here are the key points:

1. **Memory Management in MemGPT**:
   MemGPT is designed to intelligently manage different memory tiers in Large Language Models (LLMs) to effectively provide extended context within the limited context window of the model. This management system enables MemGPT to decide when to store critical information to a vector database and when to retrieve it later in the chat, facilitating perpetual conversations【https://github.com/cpacker/MemGPT#:~:text=What%20is%20MemGPT%3F%20Memory,the%20LLM%27s%20limited%20context%20window】【https://archive.org/details/github.com-cpacker-MemGPT_-_2023-10-23_08-14-53#:~:text=Memory,the%20chat%2C%20enabling%20perpetual%20conversations】.

2. **Hierarchical Memory Architecture**:
   MemGPT introduces a hierarchical memory architecture, similar to the memory systems used in traditional operating systems. This architecture divides the memory into two primary components: the Main Context, analogous to an OS's main memory or RAM, and the External Context, serving as secondary storage. The model can selectively transfer information between these two components through explicit function calls, enabling it to work with contexts far exceeding its limited input capacity【https://notes.aimodels.fyi/memgpt-towards-llm-as-operating-system/】.

3. **Performance in Conversational Agents**:
   MemGPT has been tested on conversational agents and shown to significantly outperform fixed-context baselines in the Multi-Session Chat (MSC) dataset. The evaluation highlighted the model's capability in achieving consistency by answering questions requiring inference from older sessions and engagement by crafting personalized conversation openers based on long-term knowledge. This indicates that MemGPT can handle coherent, long-term conversations in scenarios similar to chat RP, addressing the concern of forgetting past contextual information over time【https://notes.aimodels.fyi/memgpt-towards-llm-as-operating-system/】.

4. **Innovative Techniques**:
   MemGPT incorporates operating system-inspired techniques, like hierarchical memory management and interrupts, to overcome the constraints of fixed context lengths. These techniques enable a more effective management of context, moving beyond the simple vector storage approach. MemGPT stands as a groundbreaking innovation in the realm of artificial intelligence, showcasing its potential in revolutionizing language models【https://cognitivecreator.medium.com/memgpt-by-uc-berkeley-ff2062c83c39#:~:text=MemGPT%20stands%20as%20a%20groundbreaking,testament%20to%20the%20boundless】.

5. **Potential Improvements**:
   There's recognition in the community that MemGPT can further be improved by integrating it with other techniques such as attention scaling or retrieval-augmented generation. This suggests an ongoing effort in the research community to enhance MemGPT's capabilities in handling extended context and memory simulation, which might address the concerns raised in the comments【[9†(LinkedIn)](https://www.linkedin.com/pulse/memgpt-new-way-make-chatbots-smarter-more-flexible-neurogai#:~:text=They%20suggest%20that%20MemGPT%20can,code%20and%20data%20for%20their)】.

6. **Relevance to Chat RP**:
   Although the exact scenario of chat RP wasn't explicitly discussed in the sources, the demonstrated improvements in handling extended conversational context and maintaining coherence over multiple sessions indicate that MemGPT could potentially provide a more "effective" way to manage context in chat RP scenarios, contrary to the skepticism expressed in the comments.

These points suggest that MemGPT has been developed with mechanisms aimed at effectively managing and retrieving contextual information, which could be applicable and beneficial in chat RP scenarios.

**Comment by underscorex86** [comment]
I believe the above comment was sincere...

But please just trust the dev, m8; instead of asking a largelanguagemodel about it.

**Comment by amantuer** [comment]
@Cohee1207 My apologies, bro. Although GPT-4 is on a large scale, we should still have faith in our developers. However, I believe that long-term memory is the most crucial feature of RP webui, and we should closely monitor the latest technological advancements in this area. If I were only allowed to use one feature of SillyTavern (after connecting to textgen), I would choose long-term memory. I'lI will closely monitor new developments and similar technologies.

**Comment by Cohee1207** [comment]
Have you tried using the reference implementation of MemGPT for the purpose you suggest? Presumably with a proper blind test with / without the plugin and in a normal environment when you do not just make a pop quiz of past events?

I understand the appeal of hype, but YouTube videos are not the type of research we should trust. So far all our evidence suggests that vector storages have very limited use outside of expert systems.

**Comment by amantuer** [comment]
@Cohee1207, I haven't tried implementing MemGPT yet, and I admit that I'm not very familiar with vector storage. As a newcomer to ML research, I respect your point that a video alone is insufficient as research evidence. I completely agree with you. However, since MemGPT is a recent development, perhaps we can wait and observe some use cases before making any judgments. Additionally, I believe that not all YouTube videos should be dismissed as untrustworthy research. There are serious CS researchers who produce high-quality content on the platform that we can rely on.
