### ISSUE TITLE
Jailbreak prompt

### ISSUE THREAD

**Issue by GuyfromGit** [SillyTavern/SillyTavern#13]
**Jailbreak prompt** Redoing this since SillyLossy said OAI it's in the dev branch.
Someone from /aids/ made this jailbreak prompt.

![TurboJailbreak](https://user-images.githubusercontent.com/86452999/228327282-e202a2ff-a848-443f-98d1-0e53cc286d8c.png)

Need testing to see its efficiency but with the right tweaking it can work great. If not, a toggle for this would be great too.

**Comment by kingzork** [comment]
Didn't know this didn't have OAI support. I appologize.
