### ISSUE TITLE
[BUG] Somehow created an character that cannot be deleted

### ISSUE THREAD

**Issue by DeltaJupiterChi** [SillyTavern/SillyTavern#1300]
### Environment

Self-Hosted (Bare Metal)

### System

Opera GX 104.0.4944.28

### Version

SillyTavern 1.10.5 'release'

### Desktop Information

v18.16.1

### Describe the problem

Unsure how but I somehow made an AI that's unable to be deleted, attempting to delete or look at past chats with it just crashes silly tavern entirely. Though interestingly I can still interact with it, being able to continue chatting with the current chat.
If anything figuring out some way to at least delete it would be nice.

### Additional info

![Screenshot 2023-10-29 134515](https://github.com/SillyTavern/SillyTavern/assets/149288611/e6ae6031-3317-4813-b6c1-47efeb7d18a6)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Delete it via the file manager

**Comment by DeltaJupiterChi** [comment]
I don't know what that is, I may be stupid but can you explain what that is?

**Comment by Cohee1207** [comment]
/public/characters folder in the ST installation path. Open with file explorer of your operating system

**Comment by DeltaJupiterChi** [comment]
Alright that got rid of the character, thanks.
