### ISSUE TITLE
[BUG] Updating Dockerfile to support GCP CloudRun deployment

### ISSUE THREAD

**Issue by kfarr** [SillyTavern/SillyTavern#1302]
### Environment

Other (Specify below)

### System

GCP CloudRun via Dockerfile (node:19.1.0-alpine3.16)

### Version

Latest (1.10.7)

### Describe the problem

* Attempting to deploy in GCP using Dockerfile
* Encountering a few issues and wanted to document for others attempting the same thing
* First, I had to swap order to COPY "Bundle app source" before COPY+RUN "Install app dependencies" ([see Line 15 here](https://github.com/kfarr/SillyTavern/blob/release/Dockerfile#L15) for the working order)
* Second, I am now encountering an issue related to "Copy default chats, characters ..." RUN step in Docker, see additional info below

I am having a hard time understanding the "ideal case" -- what is supposed to happen with settings copying between `/default` `/public` and `/config` dirs? My lack of understanding contributes to difficulty of debugging remote deployment, apologies.

### Additional info

The Docker build fails at this step of creating symbolic links as part of the next to last RUN command in Dockerfile:
```
> *** Create symbolic links to config directory ***
> [91mln: config.conf: File exists
> The command '/bin/sh -c IFS="," RESOURCES="characters,chats,groups,group chats,User Avatars,worlds,OpenAI Settings,NovelAI Settings,KoboldAI Settings,TextGen Settings" &&     echo "*** Store default $RESOURCES in <folder>.default ***" &&   for R in $RESOURCES; do mv "public/$R" "public/$R.default"; done &&     echo "*** Create symbolic links to config directory ***" &&   for R in $RESOURCES; do ln -s "../config/$R" "public/$R"; done &&   ln -s "./config/config.conf" "config.conf" &&   ln -s "../config/settings.json" "public/settings.json" &&   ln -s "../../config/bg_load.css" "public/css/bg_load.css" &&   mkdir "config"' returned a non-zero code: 1
```

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by kfarr** [comment]
I noticed some others attempting Docker-based deployment and thought I would add this ticket showing some progress made but challenges remaining with deploying on GCP CloudRun. If this is out of scope for this repo, feel free to close this ticket.

**Comment by entmike** [comment]
Same thing happens on Ubuntu 22.04 Desktop:

```sh
> [7/8] RUN   IFS="," RESOURCES="characters,chats,groups,group chats,User Avatars,worlds,OpenAI Settings,NovelAI Settings,KoboldAI Settings,TextGen Settings" &&     echo "*** Store default $RESOURCES in <folder>.default ***" &&   for R in $RESOURCES; do mv "public/$R" "public/$R.default"; done &&     echo "*** Create symbolic links to config directory ***" &&   for R in $RESOURCES; do ln -s "../config/$R" "public/$R"; done &&   ln -s "./config/config.conf" "config.conf" &&   ln -s "../config/settings.json" "public/settings.json" &&   ln -s "../../config/bg_load.css" "public/css/bg_load.css" &&   mkdir "config":
0.149 *** Store default characters,chats,groups,group chats,User Avatars,worlds,OpenAI Settings,NovelAI Settings,KoboldAI Settings,TextGen Settings in <folder>.default ***
0.150 mv: can't remove 'public/characters': Invalid argument
0.150 mv: can't remove 'public/chats': Invalid argument
0.151 mv: can't remove 'public/groups': Invalid argument
0.151 mv: can't remove 'public/group chats': Invalid argument
0.152 mv: can't remove 'public/User Avatars': Invalid argument
0.152 mv: can't remove 'public/worlds': Invalid argument
0.153 mv: can't remove 'public/OpenAI Settings': Invalid argument
0.155 mv: can't remove 'public/NovelAI Settings': Invalid argument
0.157 mv: can't remove 'public/KoboldAI Settings': Invalid argument
0.160 mv: can't remove 'public/TextGen Settings': Invalid argument
------
Dockerfile:25
--------------------
  24 |     # Copy default chats, characters and user avatars to <folder>.default folder
  25 | >>> RUN \
  26 | >>>   IFS="," RESOURCES="characters,chats,groups,group chats,User Avatars,worlds,OpenAI Settings,NovelAI Settings,KoboldAI Settings,TextGen Settings" && \
  27 | >>>   \
  28 | >>>   echo "*** Store default $RESOURCES in <folder>.default ***" && \
  29 | >>>   for R in $RESOURCES; do mv "public/$R" "public/$R.default"; done && \
  30 | >>>   \
  31 | >>>   echo "*** Create symbolic links to config directory ***" && \
  32 | >>>   for R in $RESOURCES; do ln -s "../config/$R" "public/$R"; done && \
  33 | >>>   # rm "config.conf" "public/settings.json" "public/css/bg_load.css" && \
  34 | >>>   ln -s "./config/config.conf" "config.conf" && \
  35 | >>>   ln -s "../config/settings.json" "public/settings.json" && \
  36 | >>>   ln -s "../../config/bg_load.css" "public/css/bg_load.css" && \
  37 | >>>   mkdir "config"
  38 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c IFS=\",\" RESOURCES=\"characters,chats,groups,group chats,User Avatars,worlds,OpenAI Settings,NovelAI Settings,KoboldAI Settings,TextGen Settings\" &&     echo \"*** Store default $RESOURCES in <folder>.default ***\" &&   for R in $RESOURCES; do mv \"public/$R\" \"public/$R.default\"; done &&     echo \"*** Create symbolic links to config directory ***\" &&   for R in $RESOURCES; do ln -s \"../config/$R\" \"public/$R\"; done &&   ln -s \"./config/config.conf\" \"config.conf\" &&   ln -s \"../config/settings.json\" \"public/settings.json\" &&   ln -s \"../../config/bg_load.css\" \"public/css/bg_load.css\" &&   mkdir \"config\"" did not complete successfully: exit code: 1
ERROR: Service 'sillytavern' failed to build : Build failed
```

**Comment by Cohee1207** [comment]
I'm not very knowledgeable in Docker or GCP, so will appreciate some help to fix it.

**Comment by kfarr** [comment]
Happy to help fix this, however I am confused by why all these files are copied around in the first place -- is there any documentation or a flow process diagram to show what is the intention with this setup script?

Like in other words, is there a simpler setup that involves less copying / directory creation?

**Comment by Cohee1207** [comment]
Okay, so there are two layers of "default files" going on.

1. What is known as default in the Dockerfile are volumes connecting certain files and directories in /public to the container, so that user data could be persisted across sessions. Since we only have a file system as a storage and no centralized DB, folders need to be mounted individually. A deeper architectural problem is that UI files are mixed with the user data is something that I want to fix eventually because that's the reason that there are many folders that need to be linked/copied. Unfortunately, currently, I have no capacity to do so.

2. The setting files that need to be accessible to the frontend or server, but added to .gitignore, are copied with an npm post-install script from the /default/ folder in the repository. You can see them here: 

https://github.com/SillyTavern/SillyTavern/blob/064d33111038f16c28b16c7d9d4e7b65e0fe72c8/post-install.js#L12-L16

I wonder if there's a way to rewrite the Dockerfile to get rid of the docker-compose entry point, and instead expose the persistent folders from a container, rather than symlinking or moving them from the builder's repo directory like shown here.

https://github.com/SillyTavern/SillyTavern/blob/064d33111038f16c28b16c7d9d4e7b65e0fe72c8/Dockerfile#L26-L37

Hope that makes sense.
