### ISSUE TITLE
[FEATURE_REQUEST] Separate Scenarios for Alternate Greetings

### ISSUE THREAD

**Issue by BurnTattoo** [SillyTavern/SillyTavern#1304]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

When putting information into the scenario box, it applies to the greeting and the alternate greetings all the same. If I wanted to change the situation a character is in in an alternate greeting, it might not match what I put in for the scenario. This is fine if I wanted to generally describe things that are always true, but it is annoying if I'm describing the scenario of a specific greeting.

### Describe the solution you'd like

If there are alternate greetings on a card, an option to input a unique scenario for each of the greetings would be appreciated. Maybe the default could be how it is now, with the scenario applying to all greetings, only using an alternate scenario if there is one. 

### Describe alternatives you've considered

I've been copying and pasting the alternate scenarios for each chat into the author's note, but it is a bit annoying to have to do it for every new chat. I also tried explaining the scenario in the greeting but I find it clunky to try to explain the plot and have good writing.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

No

**Comment by Cohee1207** [comment]
Have you tried the "Chat Override Scenario" feature?

**Comment by IkariDevGIT** [comment]
> Have you tried the "Chat Override Scenario" feature?

i think he rather meant per card, so that card creators can set that, not you(the user)

**Comment by Cohee1207** [comment]
New card fields should be aligned with other frontends and character-sharing platforms, so I try to avoid adding them if there are alternatives.
But anyway I don't see the practicality in Scenario field use at all. The LLMs are smart enough to infer the scenario from the context of the first message. They stop referring to the scenario at all if the conversation derails from it entirely.

**Comment by DanHoelck** [comment]
> The LLMs are smart enough to infer the scenario from the context of the first message. They stop referring to the scenario at all if the conversation derails from it entirely.

They are, but they'll pull style and narrative cues from the first message as well.

If the first message heavily focuses on what the user's character has done to lead up to the chat - (e.g. "You get out of the car and walk into the store, where you overhear {{char}} ask for a phased plasma rifle in the 40-watt range.") - then weaker LLMs will take that as an indication to continue taking actions for the user.

Scenarios are a clean workaround for this, as the scenario is clearly separate from assistant response format.
