### ISSUE TITLE
[FEATURE_REQUEST] Discord Bot

### ISSUE THREAD

**Issue by TimyIsCool** [SillyTavern/SillyTavern#1306]
### Have you searched for similar requests?

Yes

### Describe the solution you'd like

I would like a discord bot of sorts that uses sillytavern (Because of the Characters, and possibly continuing chats between discord and the sillytavern UI)

### Describe alternatives you've considered

Ive searched for something but haven't found what I am looking for

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

No

**Comment by Cohee1207** [comment]
Not something I'm keen on developing as SillyTavern is a self-contained frontend and communicating with it without having a browser tab open is not possible. If someone wants to make it a downloadable extension/plugin - will consider including that in the extensions list.
