### ISSUE TITLE
[FEATURE_REQUEST] Ability to hide a single message without deleting it.

### ISSUE THREAD

**Issue by imesha10** [SillyTavern/SillyTavern#1308]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

The problem: Sometimes in the middle of a chat, I get the ai to critique or give me ideas to continue. I want to be able to disable that message so that it does not pass into the ai and stays there as a note to myself.

### Describe the solution you'd like

In the icons for each message (ex. below), it might be good to add an eye icon that will disable the message being sent to the ai and show a closed eye icon after it's disabled, pressing it again will enable it making the eye come up.

![image](https://github.com/SillyTavern/SillyTavern/assets/16441743/bac7fd5a-4b92-4d6c-a520-02d5b2a27c56)

### Describe alternatives you've considered
I could copy this text into notepad and delete the message however the counter point to that is that this is text that is relative to the chat so it will be good to organize it with it.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

No

**Comment by Cohee1207** [comment]
Did that in staging yesterday.
https://github.com/SillyTavern/SillyTavern/commit/eab25c73e7a16b667f63adb54d67ee52d0071885

**Comment by imesha10** [comment]
> Did that in staging yesterday. [eab25c7](https://github.com/SillyTavern/SillyTavern/commit/eab25c73e7a16b667f63adb54d67ee52d0071885)

@Cohee1207 Thanks, it seems to work well  🎉!
