### ISSUE TITLE
[FEATURE_REQUEST] Ollama backend

### ISSUE THREAD

**Issue by korewaChino** [SillyTavern/SillyTavern#1309]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Currently, setting up an LLM is kind of a tedious task for a normal user, Ollama provides a Docker-like interface for managing LLMs, with a simple HTTP API.

### Describe the solution you'd like

Add an [Ollama](https://ollama.ai/) backend for SillyTavern

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

Maybe

**Comment by Fel-2** [comment]
This needs to be a thing.

**Comment by mysticfall** [comment]
This would be especially good for those who use LangChain or Arch/Manjaro Linux.

I have SillyTavern installed on my Manjaro desktop which I also use for working on a LangChain project.

Although I can use Oobabooga as a backend for both (with some hacks), it's not as hassle-free as with Ollama, and it requires a Python venv. of its own.

Manjaro has an Ollama package so it can just use system CUDA libs instead, which can be good if you don't want to see your drive cluttered with multiple installations of the same dependencies.

**Comment by Cohee1207** [comment]
Added.
