### ISSUE TITLE
[FEATURE_REQUEST] Transparent background cards support.

### ISSUE THREAD

**Issue by SimplyKillMe** [SillyTavern/SillyTavern#1313]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Good day, so... I have a little issue and a suggestion about it, let me explain, after updating from 1.10.3 (iirc) to 1.10.7 around 4 days ago, I noticed that .pngs without a background used as character cards now get a background in the tavern interface, that's apparently just a part of the UI background, (and thus tied to its transparency), at least it's not that it actually changes the picture per se.
![bandicam 2023-11-04 16-19-42-755](https://github.com/SillyTavern/SillyTavern/assets/149542130/4bc284d3-1ffc-490a-bdaf-54c775f2970b)
My guess is that it's necessary for the Moving UI to work or something, but I might be wrong, since I can swear that wasn't there in older ST versions, and the Moving UI still worked. Well, anyways, the problem is that that background is not only ugly IMO, but pretty disrupting, especially in the VN mode, the obvious solution would beto lower the UI background transparecy, but alas, that creates another issue.
![bandicam 2023-11-04 16-20-05-572](https://github.com/SillyTavern/SillyTavern/assets/149542130/f8238fbb-5f7e-449b-b2ce-d5d9186757d6)
Since the rest of the UI background disappears too, the text of the menus overlaps with the chat and makes pretty difficult to read anything, and if having a completely transparent UI wasn't bad enough, tbh, it just looks bad.

### Describe the solution you'd like

I'd like to have the option to change the transparency of the card background on its own, unrelated and unaffecting the rest of the UI background.

### Describe alternatives you've considered

... or you could just remove the card's background entirely. Whatever works better for you and has less chances to break something.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

No

**Comment by Cohee1207** [comment]
Fixed in staging: https://github.com/SillyTavern/SillyTavern/commit/583c737106a399fe6c88f559c83a51d3f487b5fa
You can cherry-pick that commit to your release branch if you wish

**Comment by SimplyKillMe** [comment]
Oh, I see, it was apparently a simple thing to change for the little I can understand of the changes in the file. I'm sorry for bothering you with this when it's something someone more tech-savvy would do pretty quick for himself, but I'm afraid I can't be described as one such person. Many, many thanks for your time and the work done, I'll mark this as closed.
