### ISSUE TITLE
[FEATURE_REQUEST] Script Runner (python)

### ISSUE THREAD

**Issue by imesha10** [SillyTavern/SillyTavern#1314]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

I have a prompt(jb) that adds the scene specific information to the end of a chat. (look at the end of this example).
![image](https://github.com/SillyTavern/SillyTavern/assets/16441743/6676308a-50da-4aa9-a7bf-e6b0a9695e3b)

This is very good for keeping a story consistent or highlighting certain things.

Now the **<ins>problem</ins>** is that when the chat history gets long there are too many of these status messages inflating the token count. I would like to run a python script that will get rid of all but the last few of these. 

However the script should not modify the chatlog. The chatlog should keep the messages as they are. The script should only affect the messages that are sent (this is because sometimes I want to replay from a previous point in the chat and I would like to have the status messages so it works as expected)

### Describe the solution you'd like

This is a rough idea of it.

In the extensions section on st add a menu called "Script Runner (python)".
![image](https://github.com/SillyTavern/SillyTavern/assets/16441743/c3695c44-e315-417f-8ce2-733db20a7bba)

This menu will allow users to add their custom python scripts that will be run when the user sends a message.
This extension tab should also be able to manage multiple scripts that can be turned on and off, edited.
For debugging, it should also have a button to view "processed messages" that will either show the output of the application of the script (via the dev console or a popup).
<ins>Most importantly this extension tab will expose the "messages" variable</ins> right before it is sent to openai or other api and allow the user to modify it to their desire before finally sending it.

For example, I should be able to paste the following script and it should remove all the messages that has the words "asdfawesadf" before sending it to the ai. 
``` python
for message in messages:
    if 'asdfawesadf' in message['content']:
        message['content'].replace('asdfawesadf', '')
```

This is a very simple example for the sake of being an example but there are many things that could be solved such as the problem that I was describing above.

### Describe alternatives you've considered
Regexes can work but as someone who barely knows how to use regexes, it's much more complicated that string1.strip() .. or intuitive python commands/operations like that.
With the current regexes it seems to be also permanent change to the messages, which is undesirable.
Also significantly more people use python than know regex so this would make scripting the end more accessible.

### Additional context

There are security concerns regarding this but if you were to just expose the messages variable, it should be fine ig.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

No

**Comment by Cohee1207** [comment]
Not sure I'd prefer having a full-fledged Python interpreter in ST. Something like user scripts - maybe. You can use a user scripts manager like ViolentMonkey and interact with the SillyTavern's state via the context object window['SillyTavern'].getContext(), the same way as UI extensions do. The only limitation - you can't import functions from code files. But everything else will be available.

**Comment by imesha10** [comment]
ViolentMonkey could work. I would have to find a way to attach an eventlistner to every time the send button is called and modify the context.
User scripts in st might be better.
However I guess I will stick to my current work around wich is to host a flask application that will intercept the api calls and modify them and then send it to the real api.
I'm closing this, maybe if there is more intrest in the futre this might be a good idea.

**Comment by kainatquaderee** [comment]
I mean there can be some command like /OS-execute etc so with linux bash or windows cmd command support

**Comment by Cohee1207** [comment]
That sounds very insecure to be included into the base package.

**Comment by intari** [comment]
Possible option: integration of something like https://github.com/open-webui/open-terminal (basically docker container with linux with http api).
