### ISSUE TITLE
[BUG] Option "Remove Empty New Lines from Output" - unintended behavior, or wrong option name.

### ISSUE THREAD

**Issue by valden80** [SillyTavern/SillyTavern#1317]
### Environment

Self-Hosted (Bare Metal)

### System

Firefox 115.2.0esr, Manjaro current.

### Version

SillyTavern 1.10.8 staging

### Desktop Information

 - OS/Device: Manjaro Linux
 - Environment: local
 - Node.js: version 20.2.0
 - Browser: Firefox
 - Generation API: Oobaboga
 - Branch: staging
 - Model: any local

### Describe the problem

Option "Remove Empty New Lines from Output" currently removing empty lines not only from OUTPUT, but also from the INPUT that going to backend and model to process. This is cause corrupt formatting of the instruct/context templates - for some model it's important.

If this is intended behavior, IMHO, this option should be renamed, as it's just confusing user like this.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
I can rename it back to "Collapse newlines" as it was previously called before being renamed

**Comment by valden80** [comment]
Please do - to at least avoid confusion. (I spend few hours to find why templates not working with desired formatting.)

But if possible, better solution to really make it affect only output form model to ST.

**Comment by Cohee1207** [comment]
Ok, rename is pending, but affecting inputs is important too for some models. NovelAI's namely, which behave better when there is no more than one consequent newline.
