### ISSUE TITLE
[FEATURE_REQUEST] Stable Horde image captioning

### ISSUE THREAD

**Issue by Teashrock** [SillyTavern/SillyTavern#1324]
### Have you searched for similar requests?

Yes

### Describe the solution you'd like

Right now, to captionize images, SillyTavern allows either Extras or local pipeline. But these are not the only options: Stable Horde as a network has so-called "Alchemist models", which can captionize images, check them for NSFW, and interrogate them (e.g., calculate the most probable tags this or similar image can be generated with). And, of course, these capabilities are available from Stable Horde API, as well the other its options.
I think it would be a wonderful thing to implement, as this way, people won't have to use Extras for something available in the Horde out of the box.

### Additional context

An example demo:
![60c7db0efce35eb0afa12f184580f3bc](https://github.com/SillyTavern/SillyTavern/assets/12483854/996f475e-23b7-401f-84f5-7d6dbe850094)
![d0706cf1a6f6cf903d5f234c746fd385](https://github.com/SillyTavern/SillyTavern/assets/12483854/e4601dfb-2566-4ec6-97fb-846b76073d51)

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
Done (as a caption)

**Comment by Teashrock** [comment]
@Cohee1207 
It works. Thank you very much.
