### ISSUE TITLE
[FEATURE_REQUEST] More precision on sampler settings.

### ISSUE THREAD

**Issue by bucketcat** [SillyTavern/SillyTavern#1325]
### Have you searched for similar requests?

Yes

### Describe the solution you'd like

Let me set 0.11 Repetition penalty slope, thanks. Currently, rounds to %.1f again, revert to %.2f. 

%.3f for Typical (0.976)
%.3f for Top A (0.017)

Currently, my kobold AI sampler settings do not function as intended due to it once more rounding the values.

### Describe alternatives you've considered

Manually managing my own fork, merge conflicts and what not. Rather not.

### Additional context

I asked for more precision on the sampler settings ages ago, it was added. Now, it's super restrictive once more. 

Don't think there should be anything wrong with increasing precision. Currently, many NAI presets are also broken, as they also use similarly precise values, which get rounded in silly tavern. (Including a few of the ones included as default presets in origin/release)

Cheers!

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
Reverted/adjusted where seen necessary. Let me know if I missed something.

Regarding freq/pres penalty in NovelAI, it is an interesting case. The preset values are impossible to set manually on their sites since the slider has a 0.05 step, so unnecessary precise values like 0.00621 seem redundant.

> Manually managing my own fork, merge conflicts and what not. Rather not.

You're always welcome to send pull requests though.

**Comment by bucketcat** [comment]
@Cohee1207 Typical seems to be missing, but other than that it seems like all of them.

You can go ahead and close this after that.

---
I haven't used NAI for a long while, but they used to have some intermittent issues where the sliders broke (but defaults were precise). It was usually quickly fixed with a quick ping in their discord server. Maybe some auto-refractoring in the back end? That was my suspicion, seems like just the thing an IDE would try to 'solve' *Cough* _JetBrains_ *Cough*.

The 3 samplers/decoders/ranges and levels of precision I personally use were specified above. For most, it's not really necessary. Top K, will never have decimals as an example, unless you want to add probabilistic outcome for an extra token 15.5 having a (50% chance for 16 and 15). But, %3f for the majority of the other samplers and decoders seems like a reasonable level of precision, imo.

As for making a pull request, you're right. The codebase has become a bit daunting, especially since JS is not my ballpark at all, but I probably shouldn't be so lazy. Sorry, will try to do better!

**Comment by Cohee1207** [comment]
> Typical seems to be missing

Got it too.

**Comment by bucketcat** [comment]
> Got it too.

You are a saint.
