### ISSUE TITLE
[FEATURE_REQUEST] Re add an option to disable use_default_badwordsids...

### ISSUE THREAD

**Issue by bucketcat** [SillyTavern/SillyTavern#1326]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

https://github.com/SillyTavern/SillyTavern/pull/1208 has completely dry fisted my workflow, to put it crudely. Making a few issues for the minor things that were options before, but were removed in this big lump of changes. (Or had the default value flipped, without any setting before or after, like the parameter mentioned in the title)

### Describe the solution you'd like

Add an intuitive way to disable this, without having to modify the API request manually. Easiest way would be to either modify the API-request, or to convince @LostRuins to add it as a launch arg for koboldCPP.

### Describe alternatives you've considered

I have tried to convince @Lostruins to add a launch argument to disable it for KoboldCPP to allow for an easy way to return to the old hidden default value. (No success so far.)

Permanently staying on a late July branch that didn't up end my workflow, settings and everything in an absurd amount of ways.

The nuclear option would be changing my workflow _shivers_.

### Additional context

My workflow is a bit unique... I want my generations to overflow. I want no stop sequences. Not the model, not character names, no EOS, no mystery stop signs. Power outage, custom defined stop sequences or user prompted abort only. Let me, not the AI decide when it can take a break.

I use sillytavern for a ghetto Story mode, so I don't have much use for the whole chat format and the benefits character prefix stop sequences and such provide. There are ways to graphically make the UI look like story mode.... But you can't actually have a story mode without any stops whatsoever. My previous workaround was to simply let the generations overflow into different character 'chat bubbles'. No big deal, might look a bit funky, but it worked and allowed me to use the rigorous extension and API support that Silly Tavern provides while still using it as I would AI dungeon, NAI or Kobold United. Through prompting, it quickly learns to ignore the character name stop sequences by simply removing the colon (like I said, ghetto). This previously meant that, with a tiny bit of manual editing at the very start of a new 'chat', I could get true story mode without artificial abortions.

I want the model to be forced to generate, even if it doesn't want to. Then I can manually edit it post facto. That's been my general workflow since gpt-2.

Now, that's not really possible. Due to the model stop logic being enabled, having never been so previously (koboldcpp defaulted it to false previously). I understand that my use case is... Unique, and that this might be the lowest of low priority changes. But it would make me happy! And yes, this work flow is a bit stupid, I know. Put this at the very bottom of the pile so to say, it's not a pressing issue nor one that affects nearly anyone but me (I assume).

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
I'm not quite sure what's the proposed change here. Could you clarify a concrete solution or change to your problem? Nothing really changed in that PR except the default value for the flag that controls the use_default_badwordsids parameter. It is still available in the UI and can be flipped however you like to properly be transferred to KoboldAI API. The meaning of this flag or its actual interpretation by the Kobold (either United or CPP) is out of the scope of ST's responsibilities.

**Comment by bucketcat** [comment]
It's not the same as the old unban_end_of_string or whatever it was called, to my knowledge. Or, it keeps triggering some weird stop sequence with ban EOS enabled on SillyTavern's end, at the very least. The link to the actual format on the huggingface model card leads to a deleted python script, so can't exactly verify. There might be something else happening here... 

Currently, with ban EOS enabled, it seems to trigger on /N at times.

**Comment by bucketcat** [comment]
To further clarify, on KoboldCPP wiki, it's referred to as "End of Stream", on Sillytavern it's referred to as End of Sequence.

I now realize that this might be a tokenizer issue... Using the NAI Clio tokenizer.

Edit:
The default Nerdstash tokenizer has changed in SillyTavern with some past update, changing from [Nerdstash v2](https://huggingface.co/NovelAI/nerdstash-tokenizer-v2) 
[To Nerdstash V1](https://huggingface.co/NovelAI/nerdstash-tokenizer-v1) based on the names. Separate issue though.


Edit 2: 
I can tell you that "use_default_badwordsids": true, at all times, and I can't find a way to disable it through sillytavern. Those are the custom model specific stop sequences. That is also what defaulted to false historically in KoboldCPP until a recent release. 

Edit 3:
 Either the ban EOS toggle in sillytavern is broken, or the [KoboldCPP wiki is wrong ](https://github.com/LostRuins/koboldcpp/wiki#my-ai-continues-rambling--writing-rambling-after-it-should-have-stopped-generating--what-does-unban-tokens-do)

I might be missing something, though. @Cohee1207

**Comment by LostRuins** [comment]
`use_default_badwordsids` has been added to Horde, KoboldAI and KoboldCpp since about 2 months ago. If its set to true, EOS is banned, otherwise EOS is unbanned. You can tell from the console output. If the parameter is missing, it is false by default.

Can you see the submitted payload in ST if this parameter is set in the submitted payload?

**Comment by bucketcat** [comment]
The problem is that it's always "True" in console, and the ban EoS in sillytavern seems to have no effect on it. 

"No payload on this request" for Generate.

Edit: 

No header either. Firefox seems to be acting up.
![image](https://github.com/SillyTavern/SillyTavern/assets/91589201/64df25d6-691b-421e-8217-424fa3f62114)

Both the debug generate and regular generate results in empty posts. Header, payload, etc.

**Comment by bucketcat** [comment]
I figured out the issue, the KoboldCPP docs has the logic for the flag inverted... False enables it, true disables it...
