### ISSUE TITLE
[FEATURE_REQUEST] Allow multiple humans to participate in a group chat

### ISSUE THREAD

**Issue by allo-** [SillyTavern/SillyTavern#1327]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

It would be nice if multiple humans could take part in a group chat.

### Describe the solution you'd like

In the end, it basically boils down treat connections from two browsers as two users with an own personality.

### Describe alternatives you've considered

- Two SillyTavern instances could connect to each other.
- External Userscripts could emulate the same user switching personalities back and receive the second user's messages over a connection that is not related to SillyTavern

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
Out of scope of this project.
