### ISSUE TITLE
[FEATURE_REQUEST] oobabooga via OpenAI API

### ISSUE THREAD

**Issue by cal066** [SillyTavern/SillyTavern#1328]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

oobabooga is moving to OpenAI compatible APIs.
```
The current API is deprecated and will be replaced with the OpenAI compatible API on November 13th.
To test the new API, use "--extensions openai" instead of "--api".
For documentation on the new API, consult:
https://github.com/oobabooga/text-generation-webui/wiki/12-%E2%80%90-OpenAI-API
```
Currently, there's no way to use the new APIs with ST.

### Describe the solution you'd like

A new OpenAPI backend option, eg pointing to a local LLM that is OpenAI compatible, or a new option for oobabooga to use OpenAI APIs.

### Additional context

Putting as high priority since the old API will be dropped within a week.

### Priority

High (The app does not function without it)

### Is this something you would be keen to implement?

Maybe

**Comment by Ph0rk0z** [comment]
Heh, main issue with these is lack of parameters and instruction templates. For instance llama.cpp python also has an OAI server and it's often faster than running it another way but I get no templates and nothing so the models are worse.

So I think in general, it would be nice to be able to use the same stuff on OAI endpoints that support it as was on the kobold/old textgen.

**Comment by Cohee1207** [comment]
I've been told that this new endpoint does support both raw prompt ingestion and the full set of generation parameters as the old one, as well as more reliable token streaming (no need for WebSockets and two URLs anymore). Will take it as a priority soon.

**Comment by cal066** [comment]
And the old API is gone:
https://github.com/oobabooga/text-generation-webui/commit/4aabff3728e00ee2a4afa5e6ee8079bab0523dbd

**Comment by Cohee1207** [comment]
The transition to new API was done in the recent release, you should check it out.

**Comment by cal066** [comment]
Thanks, I already am, works pretty well. The message about --extensions openai should probably be changed to --api now that it is the only supported mode.

**Comment by Ph0rk0z** [comment]
Can confirm it works like it did before as well.

**Comment by Cohee1207** [comment]
> Thanks, I already am, works pretty well. The message about --extensions openai should probably be changed to --api now that it is the only supported mode.

Already did. Can close now I suppose. 
https://github.com/SillyTavern/SillyTavern/commit/fc17f42f93ca5c6e12d0151a163bd15fb4999324
