### ISSUE TITLE
[FEATURE_REQUEST] Could you release support for OpenAI's Dev Day API Updates please?

### ISSUE THREAD

**Issue by brunsonator3** [SillyTavern/SillyTavern#1329]
### Have you searched for similar requests?

Yes

### Describe the solution you'd like

OpenAI just released a couple of new APIs. GPT-4 Turbo with 128k context length. gpt-4-1106-preview. GPT4Vision. And gpt-3.5-turbo-1106. Please add support for these new API's, as they will help bring these characters to life. Thank you.

![GPT4 Turbo](https://github.com/SillyTavern/SillyTavern/assets/115924424/a97cdf2b-4b04-41ab-a1c5-5d3f59baef90)
![GPT3 5 Turbo 1106](https://github.com/SillyTavern/SillyTavern/assets/115924424/4b17e727-3e91-4bc3-970a-765f19df06ff)

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

None

**Comment by SkySlider** [comment]
There's also a new TTS capability available + dalle-3 is now available through API

**Comment by Cohee1207** [comment]
Everything is done in staging already (except for TTS).

**Comment by qwertea** [comment]
Also Dall-E support in place of Stable Diffusion would be very nice. I don't know if that's better suited as an extension.

**Comment by Cohee1207** [comment]
> Also Dall-E support in place of Stable Diffusion would be very nice. I don't know if that's better suited as an extension.

@qwertea DALL-E too. Check staging branch

**Comment by qwertea** [comment]
Thanks, was having trouble finding it but finally saw it under the Stable Diffusion extension if anyone else was confused.

**Comment by Cohee1207** [comment]
Yeah, I agree. I've just renamed the "Stable Diffusion" plugin to "Image Generation" to accommodate the new contender.

**Comment by Cohee1207** [comment]
All done. Whisper via STT plugin will come some time later.
