### ISSUE TITLE
Current state of the memory extension

### ISSUE THREAD

**Issue by sinoth** [SillyTavern/SillyTavern#133]
I've been trying to understand how the memory extension works and saw this:

https://github.com/Cohee1207/SillyTavern/blob/2e5ce1485bc27929178f91bf33937173028fac7d/public/scripts/extensions/memory/index.js#L237

Looks like currently the Buffer parameter is ignored, so the only real tweak we have is the maximum size of summary it will generate.

In general I'm curious about the current state of the memory extension and if you have any plans or wishes for it. I'm interested in this because it solves a HUGE problem in current generation LLMs with losing the state of a conversation. A well tuned chunk of long term memory could help tremendously.

All of this will become less of a problem as 32k+ context become common, but it's an interesting problem nonetheless!

**Comment by Omniphantasm** [comment]
> Everyone has their preferences but for me personally OpenAI GPT outputs lack something. Free models could give me genuine laughs because of how wacky and unpredictable the outputs may be.

Fall in the same category here, OAI is nice but it quickly becomes highly predictable in my experience when compared to the 'lesser'  models which kind of removes part of the fun of 'chatting' with the AI.
