### ISSUE TITLE
[BUG] Interrupting chat save dupes the chat and stats to the root of linked Google Drive

### ISSUE THREAD

**Issue by Xabab** [SillyTavern/SillyTavern#1330]
### Environment

Other (Specify below)

### System

Google Colab Notebook

### Version

SillyTavern 1.10.7 'release' (064d3311)

### Describe the problem

I use Google Colab to run Silly and use a symlink to folders at Google Drive to preserve my data.

The bug arises when saving the chat gets interrupted (eg "Your chat is still saving... Please wait until the chat is saved before switching characters." etc), which causes a dupe of the chat's jsonl and chat stat's json to appear at the root of Google Drive, sometimes corrupting original files.
In addition, additional dupes get saved with a postfix, which causes clutter at GDrive (when I discovered this I had to delete about 5000 files; no wonders why it have been taking, like, 40 seconds to mount the drive xD)

Most often it happens just using the silly with my laggy smartphone.

Notebook snippet:
https://pastebin.com/UXAMLJH0

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Sorry, but we don't support GDrive / Colab deployment and it is unlikely that I can provide help with it.
Extra files are from the atomic write package that creates a copy and then renames it.
You can try rising it to the library owners: https://github.com/npm/write-file-atomic
