### ISSUE TITLE
[BUG] Group chat "Create branch" going blank.

### ISSUE THREAD

**Issue by imesha10** [SillyTavern/SillyTavern#1332]
### Environment

Self-Hosted (Bare Metal)

### System

Windows 11, Chrome

### Version

SillyTavern 1.10.8 'staging' (00a1eaab)

### Desktop Information

Node JS: v18.15.0
Generation: OpenAI reverse proxy
Branch: Staging
Model: any gpt version

### Describe the problem

When I went to create a branch from a group chat, I press the branch button and then it goes blank. Below is a visualization of it. This seems to only happen in group chats.

Press this.
![image](https://github.com/SillyTavern/SillyTavern/assets/16441743/64cb47a5-51f0-4d9f-8fbd-796ee716d105)
Then the entire chat area turns like this.
![image](https://github.com/SillyTavern/SillyTavern/assets/16441743/03c2b1ad-8640-418f-ac91-80a0eb6f37bc)

### Additional info

This error pops up when this crashes.
```
script.js:4823 Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'chat')
    at openCharacterChat (script.js:4823:35)
    at async branchChat (script.js:6834:5)
```

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Thanks, fixed
