### ISSUE TITLE
[BUG] Checkboxes weirdly low-vis

### ISSUE THREAD

**Issue by majick** [SillyTavern/SillyTavern#1333]
### Environment

Self-Hosted (Bare Metal)

### System

Darwin hostname 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:31 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8112 arm64 // Safari Version 17.1 (19616.2.9.11.7)

### Version

commit bda15ef007a347aad6598343869f8af0de58cb9b

### Describe the problem

19c0100 makes checkboxes in the default theme nearly impossible to see (and, speaking personally, kinda ugly) tying them to `var(--SmartThemeBlurTintColor);` which doesn't appear to be UI configurable (yet?).

<img width="467" alt="Screenshot 2023-11-07 at 6 51 37 PM" src="https://github.com/SillyTavern/SillyTavern/assets/125657/ee4d4282-29a9-48f1-86c1-3fbbe575d9e9">

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
This was reverted.

**Comment by majick** [comment]
The revert fixes this for me.
