### ISSUE TITLE
[FEATURE_REQUEST] Aisekai's Knowledge Base

### ISSUE THREAD

**Issue by Avroboros** [SillyTavern/SillyTavern#1340]
### Have you searched for similar requests?

None

### Describe the solution you'd like

Aisekai has a cool feature in which the character has a knowledge base on information that it should know, which doesn't consume tokens at all, it allows the user to fully dedicate all tokens to personality, physical traits... etc while at the same time giving the character information that it should know (very useful when it comes to defining other personality/physical traits from the character, but also the user and other characters aswell).

I don't really know how this system works, but it probably can be done by having the AI model read this piece of information regarding things it should know right after "taking in" the personality and physical traits of the specific character, and using this strip of information selectively depending on the chat history or information that it retains. 

(Example, in this Knowledge base part let's say i input that the user has a 1 kilometer nose, and everytime the character sees the nose it get flashed with an image of ryan gosling caressing his pinky toes in the middle of Amsterdam on the character's mind. So as consequence it would make the character say something like : "*As i look at your face and see your nose, i immediately look away and recompose myself after seeing that same image of Ryan Gosling's pinky toes being massaged in my head*" before talking to the user like normal and answering the user.)

This works mighty fine on Aisekai, not consuming tokens at all and it would be revolutionary if that could be implemented into SillyTavern, because that would mean that pieces of information that aren't important or CRUCIAL to the character won't be consuming tokens constantly (saving up overwhelming and tremendously big amounts of tokens), and these pieces of information can still be used randomly in the appropriate or right situation, just like in my example, since its not always that the character will look onto the user's face, so its not always that the character will see ryan gosling giving a happy ending to his pinky toes, therefore saving all the tokens that would've been consumed if you were to implement that example onto the character's personality or something.

![image](https://github.com/SillyTavern/SillyTavern/assets/146421595/cc76b977-c2d0-4fc9-afc7-13771492cdcc)

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

Maybe

**Comment by ghost** [comment]
Pretty sure this data can be already added through Persona Management or Author's Note though. And I probably should note that any data the bot has to know that is given by you, uses tokens. Even the system in Aisekai uses some tokens to give the crucial data to the AI.

**Comment by Cohee1207** [comment]
> which doesn't consume tokens at all

Big doubt. If it's not in the prompt (i.e. not consuming tokens) - it doesn't exist for the model. This whole thing just looks like an Author's Note pinned to the prompt at all times. You can even check that by asking it to repeat the whole prompt verbatim.

**Comment by Avroboros** [comment]
>"Even the system in Aisekai uses some tokens to give the crucial data to the AI."

Correct to a certain degree, however if you go create your character on Aisekai, you'll notice that any amount of information in the Knowledge Base is practically inexistant, and in the total tokens used out of 2.048 you'll notice that it'll just add 1 to 10 tokens, when it would add 100 or more if you input that data in the normal personality section

After this, when you create your character and talk to it, you get a lot of chat context + the character itself remembers and actually knows any information that you input in the Knowledge Base, while at the same time not consuming hundreds of tokens more just to remember that information (only pulling that information by "reading it" and extracting it in the right context, instead of constantly copying that information).

**Comment by Avroboros** [comment]
>This whole thing just looks like an Author's Note pinned to the prompt at all times. You can even check that by asking it to repeat the whole prompt verbatim.

Perhaps but again, the Aisekai system allows you to economize and utilize more tokens than usual with this system.

**Comment by Cohee1207** [comment]
Can I kindly ask you to analyze how exactly this system works and then come back with a defined solution that could be implemented? I haven't used this app so have no idea how it is implemented, so I'd expect some insights from you.

**Comment by Avroboros** [comment]
I'll demonstrate what i mean first because i don't really excel at describing things with words :

Below is an example i'm gonna use with a character info i'm creating right now (Tsunade from Naruto)

Below is a screenshot of all the data being input into the personality traits section (in the same way as if you were to put that information inside the character's description on SillyTavern).

![image](https://github.com/SillyTavern/SillyTavern/assets/146421595/72b6679f-f225-47e3-a54b-20cc758295a7)

It registered 1.507 tokens.

Now, i will demonstrate below what happens if i put non-essential information (that the character should know, but doesn't need to constantly keep repeating or keeping into its "core" description : 

![image](https://github.com/SillyTavern/SillyTavern/assets/146421595/d19ec78f-b950-4786-aa39-4e6f0073ae36)

As you can see, all i did is cut 3 paragraphs that aren't essential information from the character's description, and put it into the Knowledge Base, saving up to 300 tokens!

Now, i will demonstrate that despite this, she will know all the information that i input into the Knowledge Base : 

![image](https://github.com/SillyTavern/SillyTavern/assets/146421595/374a550b-65d6-40bb-86d5-8ee1c7181fe7)

![image](https://github.com/SillyTavern/SillyTavern/assets/146421595/ff84b454-2558-4e83-8fa8-bf7c781860a0)



And there you go, as you can see all i did now is add a pfp, the short description and 300 tokens were still saved up, allowing for more chat context aswell as more information to be used (while keeping non-essential info in the "background" of the character's priority).

I don't know how the mechanism or system behind this works, but my theory is maybe a separate prompt/plugging whatever temporarily keeps this information while the character keeps its main base of data that consumes token. Afterwhich, when reading the chat and its description, the ai will read from this temporary prompt to check if there is any info that coincides with what's under the context of the chat. (like i asked her for her "Chakra Natures", which she accurately gave me what i input into the Knowledge Base, since it matched the context of my question.. And as you noticed, she also expressed her mistrust due to the mention of Orochimaru, which is a feeling she has that i input into the Knowledge Base aswell, therefore proving it works). Iirc there's a similar function like this from the SillyTavern Extras called "Memory", although its been quite a long time that i used that plugin so i don't remember its functionality, but it might work under the same principle, temporary and non-essential information that is only called when the context is right.

Does this have a limit? Definetly, everything has one, however i'm not sure what is the limit of this Knowledge Base, since so far i've never ran into it.

**Comment by gustrd** [comment]
Probably it's a RAG for references. SillyTavern already uses ChromaDB's extension RAG for memories, but this seens to be a different use of it.

**Comment by kevATin** [comment]
I think the knowledge base system is very powerful and I'd like to see more platforms improve upon that concept.

Aisekai isn't very straightforward with how exactly their models work, but there is a lot of information on their discord, both from developers and crafty users. 
I can't remember the details but their base character personality supports 2048 token and through trial and error the knowledge base was estimated to be around 2048 too i believe. The user input and chat history go into the first 2048t so if you don't leave enough space your character won't care about your chats.
I believe overfilling the KB just cuts off the additional content without any warning.

If i had to guess, then the way it works in the background is the model calculates the usual response and then checks that response for matches with the KB content. If there are matches then those are taken into account for re-generating the response which is then given to the user. I don't believe Aisekai ever made clear statements on how it works.

If anyone wants to know it in more depth then you should check out their discord, ideally soon, with all their drama going on I wouldn't make any bets on how long until all that gets deleted too.



Personally I think the perfect knowledge base would work differently and use bank switching.
So you would have one main "index"-knowledge base (of 512 tokens or so) which the character should always keep in mind, and then multiple specific modular knowledge bases (each up to 512t) which can be loaded on demand, but only one at a time.
This would be great for narrative AIs or characters with in-depth lore. The index would point towards the KB modules and have certain triggers for them. Maybe one module for the animals of the world, one for the magic spells, one for history of continentXYZ, one describes the house of a character in detail, etc.
I don't think I've seen anything like that yet.

**Comment by Cohee1207** [comment]
May be related and used to solve this: https://docs.sillytavern.app/usage/core-concepts/data-bank/
