### ISSUE TITLE
[FEATURE_REQUEST] Openai Connect Bypass Button 

### ISSUE THREAD

**Issue by imesha10** [SillyTavern/SillyTavern#1343]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

I use free proxies for openai. Sometimes these proxies arn't set up correctly, and their status check isn't set up. I want to bypass the check (turn the circle green from red) so I can just send messages even if the api is not being detected (which it will work for these proxies).

I know silly tavern does not support random third party openai proxies, however these proxies work, the only thing they fail is the check that it works.

For example the current one that I'm using gives me the following when I press "connect"
![image](https://github.com/SillyTavern/SillyTavern/assets/16441743/a46dc2a1-9b28-4207-899c-629247822a25)

however the circle stays red.
![image](https://github.com/SillyTavern/SillyTavern/assets/16441743/dec108d3-9d9f-4ff7-8526-53438b2b1fd9)

### Describe the solution you'd like

Next to the "Connect", "Cancle" "Test Message" buttons a "Bypass" button which will just enable me to send messages.
![image](https://github.com/SillyTavern/SillyTavern/assets/16441743/446f2cd6-8c8e-4d8a-a824-25742dcd9f9f)

Currently the messages are locked and I can't send:
![image](https://github.com/SillyTavern/SillyTavern/assets/16441743/65fc90e5-cb48-4023-bf8f-d1f0b50dcc8d)

After the bypess button is pressed, it should reset the next time "connect" would be pressed so it goes back to working as normal.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

No

**Comment by Cohee1207** [comment]
Done.

**Comment by imesha10** [comment]
> Done.

@Cohee1207 it works thanks, but there is a small bug.
I have to press it multiple times for it to work (but it works).

https://github.com/SillyTavern/SillyTavern/assets/16441743/909f61eb-01b9-485b-885c-2bfdeda68c4c

**Comment by imesha10** [comment]
Sorry if I'm confusing you, the flow should be like with the checkbox:

    1️⃣. Check if the "bypass API status check" is checked
    2️⃣. If checked then when connect is pressed make it green and other related stuff
    2️⃣. If not checked then go the normal route

Forget about what I said about pressing the connect button would reset this bypass check thing. Since a checkbox was chosen (which is better) you only need to check the checkbox.

**Comment by Cohee1207** [comment]
There's a problem with the logic you proposed. If the endpoint exists and bypass is checked, it won't load a model list. I made it so the status sets immediately but we'll still be pinging the endpoint for the models and will gracefully continue if it doesn't respond.

**Comment by imesha10** [comment]
> There's a problem with the logic you proposed. If the endpoint exists and bypass is checked, it won't load a model list. I made it so the status sets immediately but we'll still be pinging the endpoint for the models and will gracefully continue if it doesn't respond.

@Cohee1207 Ok, thank you it works very well now.
