### ISSUE TITLE
[FEATURE_REQUEST] Google Search through SillyTavern?

### ISSUE THREAD

**Issue by iChristGit** [SillyTavern/SillyTavern#1345]
### Have you searched for similar requests?

None

### Is your feature request related to a problem? If so, please describe.

My initial issue was trying to run web_search extension (oogabooga) https://github.com/simbake/web_search
to pass to SillyTavern, but the extensions do not effect Silly.
The extension is very helpful to get new information or anything that is found on the web.

### Describe the solution you'd like

Either a way to enable the context of the extension to show on sillytavern and that way get current news and information.
Or maybe port that extension to sillytavern or any other way to connect to the web.
I have no code knowledge so i wonder what is the way to achieve this.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

No

**Comment by Cohee1207** [comment]
Added 
https://docs.sillytavern.app/extras/extensions/websearch/#web-search

**Comment by iChristGit** [comment]
> Added https://docs.sillytavern.app/extras/extensions/websearch/#web-search

Wow that was really fast thank you!
Is there a chance it will support fetching the information locally as opposed to API? I rather it all run locally without relying on any provider.
There are couple of open source projects that include that, like Chat-UI, LOLLLms and web_search for oobabooga.
