### ISSUE TITLE
update error?

### ISSUE THREAD

**Issue by feastp** [SillyTavern/SillyTavern#1346]
### Environment

Self-Hosted (Bare Metal)

### System

19045.3570

### Version

SillyTavern 1.10.4

### Desktop Information

I have no clue, and seems very much time consuming learning how to provide such info, so just ask which are needed??

### Describe the problem

not sure, it said there were 3 vulnerabilities when running updatestart.bat so want to fix them for the sake of fixing them. the discord said to just reinstall and report here so went out what happened?

### Additional info

![Screenshot (54)](https://github.com/SillyTavern/SillyTavern/assets/150604258/06dc270e-6baf-48db-a84b-8e090aa08cbd)
tired to take go to the log in that image but sas it's missing, ig it was tied to the cmd app that I closed.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Fixed in release branch already: https://github.com/SillyTavern/SillyTavern/commit/5331b5dc8a9a15c0776ccf49bf5deae24a8ea37a

**Comment by feastp** [comment]
> Fixed in release branch already: [5331b5d](https://github.com/SillyTavern/SillyTavern/commit/5331b5dc8a9a15c0776ccf49bf5deae24a8ea37a)

so I just go about my day? do nothing?

**Comment by Cohee1207** [comment]
https://docs.sillytavern.app/usage/update/#how-to-update-sillytavern

**Comment by feastp** [comment]
> https://docs.sillytavern.app/usage/update/#how-to-update-sillytavern

it only support the fact it broke something? but no solution. might as well give me a link to google bud.

**Comment by Cohee1207** [comment]
This is not a software problem. You are running npm commands outside of the repository folder.

**Comment by feastp** [comment]
> This is not a software problem. You are running npm commands outside of the repository folder.

srry idk how 2 not do da.
