### ISSUE TITLE
In version 1.10.8, the parameters become  invisible and unmodifiable when the interface language is set to a non-English language.

### ISSUE THREAD

**Issue by Songofzhe** [SillyTavern/SillyTavern#1347]
### Environment

Self-Hosted (Bare Metal)

### System

win 10  /  chorme 119

### Version

1.10.8

### Describe the problem

When the interface language is set to a non-English language, and the API type is set to 'oobabooga webui', the parameters in the AI response configuration cannot be fully displayed or adjusted. This problem happens in ver1.10.8.
![Snipaste_2023-11-13_01-02-50](https://github.com/SillyTavern/SillyTavern/assets/133586578/025a1c4b-fda7-495c-8212-713726b1fa16)
![Snipaste_2023-11-13_01-03-08](https://github.com/SillyTavern/SillyTavern/assets/133586578/7371aa71-f43d-4349-b012-be4f488eb756)
![Snipaste_2023-11-13_01-03-25](https://github.com/SillyTavern/SillyTavern/assets/133586578/1c1bade5-8045-4666-93fb-6acc78ae77b3)
![Snipaste_2023-11-13_01-04-40](https://github.com/SillyTavern/SillyTavern/assets/133586578/909d9bc0-97fa-49bf-ac0a-1e3249082ee6)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Hi. This was fixed in both branches. Thanks.

**Comment by Songofzhe** [comment]
Got it. Thanks for the work！
