### ISSUE TITLE
Optimize batch deletion function

### ISSUE THREAD

**Issue by qw1642190428** [SillyTavern/SillyTavern#1348]
### Have you searched for similar requests?

None

### Is your feature request related to a problem? If so, please describe.

When using batch deletion, batch deletion often fails due to accidentally touching or entering character cards.

### Describe the solution you'd like

The improvement plan I proposed is to lock the selection interface when clicking the batch delete button to prevent access to the character card. Click on the character card to directly select the character card for easy deletion.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

Yes!

**Comment by Cohee1207** [comment]
Added a full-screen loader that will block any accidental clicks.

**Comment by Cohee1207** [comment]
Released.
