### ISSUE TITLE
[FEATURE_REQUEST] Decouple chat UI and character management UI so that both are independently resizeable.

### ISSUE THREAD

**Issue by bucketcat** [SillyTavern/SillyTavern#1353]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

The character management UI is currently way too small to actually use for writing in. The only way to expand the text areas (Greeting, persona etc) inside this sidebar is by changing the slider of the main UI. You can't resize individual text areas of the character management, either, so it's still too small even when the chat is at minimum width.

A possible solution is to make the character management/editing sidebar an overlay, that you can open and resize freely over a chat. Currently, writing in text file is more effective than using the character management feature. This didn't use to be as bad historically, but there were UI changes that made the character tab text areas not scale properly.

Currently, the description_textarea is 293x222 pixels with 56 width scale on 4:3 and 399x222 pixels on 16:9. There is no scrollbar and no way to resize without offsetting everything else. Even then, you can only resize it horizontally, rather than both. It is unusable, both for writing in, editing or just reading through an existing card. You can't expand it vertically, you can't scroll, you can't center it.

### Describe the solution you'd like

Make the character editing a resizeable, centralised overlay/pop-up rather than pinning it to the sidebar, decoupled from the main chat UI scaling.

An alternate option would be to add an option to embed/fullscreen the textareas so that they're actually usable.  (Character description/greeting)

### Describe alternatives you've considered

I currently use an alternative. I use a text editor and a text file to read or edit any part of a character card due to a better UX. It's simply less effort than manoeuvring the semi-static text areas, having to resize everything etc. It would be nice to have the ability to do this in ST easily.

### Additional context

Firefox Desktop v.119

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

No

**Comment by bucketcat** [comment]
Also, in regards to https://github.com/SillyTavern/SillyTavern/issues/73, the accepted answer is wrong. There is no icon on Firefox nor option to resize. 
![image](https://github.com/SillyTavern/SillyTavern/assets/91589201/5e1ed9f5-22ca-4596-a5be-4228be0afa8d)

**Comment by Cohee1207** [comment]
The option to resize is under the "Moving UI" toggle.

**Comment by bucketcat** [comment]
The only thing under that is custom CSS, I am not writing my own CSS stylesheet to make a UI functional, if that is what you are referring to. I'd just use Stylus if I had time for that (Using a text file + copy paste is faster). If you mean that it's a setting that appears after you toggle "Moving UI", then I suggest renaming it to "resizeable UI" as that name makes it sound like it's some dynamically changing thing, I.e. a moving UI.

Searching "Resize" in the search bar has 0 results also.

![image](https://github.com/SillyTavern/SillyTavern/assets/91589201/3652d122-60de-4845-92a0-7883cc59881f)

**Comment by Cohee1207** [comment]
It's called "MovingUI", right above Custom CSS
This does exactly what you propose.

**Comment by bucketcat** [comment]
Oh yea, it works for the main chat window. Something is fucked with the sidebar on firefox. Scrollbars are 1 pixel wide and look like alignment offsets rather than a scrollbar, a bunch of missing ui elements and icons etc (Such as resize point, on the main window with moving UI enabled and always for the text areas).

**Comment by Cohee1207** [comment]
You first need to move it left and then resize to the right, otherwise it may shrink. It doesn't do that in Chromium, maybe something is different in Firefox. If you messed up the windows - use "Reset moving UI" button or /resetui slash command.

**Comment by bucketcat** [comment]
Yea I've already figured that out, there are separate issues with the UI independent of that. As in, there are no dots to show where the resize point is for the mouse. The scrollbars on the text areas are bugged (just a 1-2 pixel wide line of nothing, look at one of the images above). You can go ahead and close this, do look into that though.

It's completely missing this on all text areas and the main sidebar. 
![image](https://github.com/SillyTavern/SillyTavern/assets/91589201/60fbf056-6a8b-456b-9b7b-67602bb94c8b)

**Comment by bucketcat** [comment]
I also want to add that after using "Moving UI" for 2 weeks, I can confidently say that it is the worst experience I have ever had with an UI. Volatile piece of shit that breaks on minimizing/resizing windows, moving between monitors. It is one of the most frustrating experiences I've had in a long time.

**Comment by RossAscends** [comment]
@bucketcat It is possible to resize the character editing panel, as well as the individual text areas. See the image below.  You will notice that I have moved the character editing panel into the center of the screen to be as large as the main chat window.

MovingUI is not breaking when you resize the window. That is a intended safety feature to prevent resize events from sending UI elements out of the window into places the user can't interact with them anymore.

Regarding the Firefox scrollbars - please send a screenshot of what you're seeing. 

![opera_WULlI6qz4f](https://github.com/SillyTavern/SillyTavern/assets/124905043/074ce877-223f-4d7e-8b74-44d46c9c96ba)

**Comment by Cohee1207** [comment]
Resolved with author by adding expand description
