### ISSUE TITLE
[FEATURE_REQUEST] Add Summarization Prompt to the "Utilty Prompts"

### ISSUE THREAD

**Issue by imesha10** [SillyTavern/SillyTavern#1355]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

The problem is that I want to modify the summarization prompt (the prompt that is passed into the ai to create the summary). I have searched around the ui for the summarization prompt and I can't find it anywhere.

### Describe the solution you'd like

Add the summarization prompt to the Utility prompts section in the AI Response Configuration tab.

### Describe alternatives you've considered

None.

### Additional context

These are all the options currently.
![image](https://github.com/SillyTavern/SillyTavern/assets/16441743/3f33eb68-8b92-4b09-a111-fd8c1c6ef002)

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

No

**Comment by Cohee1207** [comment]
It's hidden by default to free some vertical space. Press "Settings" to see it.

**Comment by imesha10** [comment]
Strange, I pressed "Settings" before while having alot of vertical space. and it didn't come up. 
However after your latest commit it works.
Thank you! 🎉🎉
