### ISSUE TITLE
SillyTavern not working properly on iPhone's Safari

### ISSUE THREAD

**Issue by Efah-Dev** [SillyTavern/SillyTavern#1358]
### Environment

Self-Hosted (Docker)

### System

iOS14.3 and 14.4.1

### Version

1.10.9

### Desktop Information

I use 1panel to run SillyTavern,in server

### Describe the problem

After I set up SillyTavern, it worked normally on the Windows Edge browser and the Android emulator. However, I had a problem when I used it on Safari. The normal loading animation could not be displayed. It felt like the web was only loading. Safari stopped loading after halfway through, and I couldn't use any of SillyTavern's features on Safari.The components of the page are loaded, but if you try to click on it, nothing happens, as are all the buttons. I think Safari stops loading a portion of the web components. I guarantee that there is no problem on the server side, because the tests on other devices all worked, except for Safari on the iPhone... ..

### Additional info

![IMG_4094](https://github.com/SillyTavern/SillyTavern/assets/95695102/9e2c65ef-6263-4eea-9f95-4b3c4d2c9efa)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Efah-Dev** [comment]
I thought about it, maybe Safari’s kernel version may be lagging behind, causing some web components not to load properly.

**Comment by Cohee1207** [comment]
I think so. I recommend to use the latest available iOS version. Since ST works fine on iOS 16, iPhone 13.

**Comment by Efah-Dev** [comment]
Well, I'm using a friend's iPhone with iOS 15.4 running fine, and the problem occurs in the Safari kernel, but I have no way to test or debug it, and I can't figure out the specific cause.

**Comment by fluviusmagnus** [comment]
It's strange. I have exactly the same problem, although my phone is running the latest iOS 17.1.1.

**Comment by QuantumEntangledAndy** [comment]
I had a look into this debugging on my old phone and it is the missing `findIndexLast` function (which was added to safari >ios 15.4)

This pollyfill seems to work and now it runs on my old phone

```js
// From https://github.com/vercel/next.js/discussions/46724
if (typeof window !== 'undefined' && !Array.prototype.findLastIndex) {
  // eslint-disable-next-line no-extend-native -- Polyfill for older browsers eg. Safari 15.1
  Array.prototype.findLastIndex = function (callback, thisArg) {
    for (let index = this.length - 1; index >= 0; index--) {
      if (callback.call(thisArg, this[index], index, this)) return index;
    }
    return -1;
  };
}
```

**Comment by Cohee1207** [comment]
@QuantumEntangledAndy

Added the polyfill to staging branch.

**Comment by QuantumEntangledAndy** [comment]
Thanks for adding to staging

I've also noticed some buttons seemed to be unresposnsive, however, when I probed deeper it seems to just be the size of them is too small on my screen, once I alter the css to enlarge them them, they're working as intended. I'll keep testing but at least core functionality works now.
