### ISSUE TITLE
[SOLVED] How to connect ooba booga new openai API to sillytavern ?

### ISSUE THREAD

**Issue by 777kevindesbiens** [SillyTavern/SillyTavern#1360]
### Environment

Self-Hosted (Bare Metal)

### System

Vast.ai or runpod.io

### Version

1.10.9

### Desktop Information

https://cloud.vast.ai/template/readme/fd5fef808279cdf0af0e44399d034808

### Describe the problem

Before the ooba booga gave 2 url links to plug in silly tavern (Blocking API URL & Streaming API URL) but now it gives only one url, namely the openai API URL ex: (OpenAI compatible API URL: https://fox-dietary-collection-lyrics.trycloudflare.com)

So how to how to connect ooba booga new openai API to sillytavern ? I am using a renting GPU from vast.ai or runpod.io

![streaming](https://github.com/SillyTavern/SillyTavern/assets/137124029/14facaf4-8b04-48a9-93e8-be7991c5f5bc)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
First, update your SillyTavern. This has been already resolved in the newest version.

**Comment by Cohee1207** [comment]
The UI you see doesn't look like a 1.10.9 install. If you copied over the entire public folder previously, you now have a broken install. Please confirm and do a git reset

**Comment by JaymanJuuzou01** [comment]
> The UI you see doesn't look like a 1.10.9 install. If you copied over the entire public folder previously, you now have a broken install. Please confirm and do a git reset

Really? I'm on 1.10.9 myself and I'm having the same issue.

**Comment by 777kevindesbiens** [comment]
It worked after I did a fresh install for Staging Branch: git clone https://github.com/SillyTavern/SillyTavern -b staging

Then it worked. Only need one URL link now instead of the previous 2.
