### ISSUE TITLE
[FEATURE_REQUEST] Allowing more than 1024 response tokens?

### ISSUE THREAD

**Issue by iChristGit** [SillyTavern/SillyTavern#1363]
### Have you searched for similar requests?

None

### Is your feature request related to a problem? If so, please describe.

I have been using the deepseek coder model from time to time and in long code responses it stop and then i need to "continue" the proccess until the code is finished.

Is it possible to edit a line in the code and change it to 4096 or higher?

Thanks!

### Describe the solution you'd like

Would like to have longer responses.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
Use "unlock context" to allow responses up to 16k tokens
