### ISSUE TITLE
[BUG] Win install goes sideways from Powershell on non-C: drive

### ISSUE THREAD

**Issue by kfsone** [SillyTavern/SillyTavern#1365]
### Environment

Self-Hosted (Bare Metal)

### System

Windows 11, Powershell 7.3.9

### Version

8ae245c from main branch

### Desktop Information

- Node: not installed yet (expected it to be part of the installer.bat)
- Generation API: n/a
- Branch: main
- Model: n/a

### Describe the problem

My boot disk is intentionally relatively small, all my AI experiments are on a dedicated E: drive. When I tried running the installer.bat from within the default Windows 11 shell the script runs into problems that result in various red text messages before it displays the initial menu, and a red-text error at the end:

![image](https://github.com/SillyTavern/SillyTavern/assets/323009/2951e2ff-6e1b-435c-99b3-fbecbbf456df)

As a former *nix shell evangelist, I can't believe I'm suggesting this but ... Writing the installer in Powershell might have been the better option. I'll revert to bash/dash/zsh command line golf in a heartbeat, but when I'm writing a script that needs to work across at least the big 3 and I'm fairly sure python isn't the answer, I've relucantly had to admit the last few years that the now-open-source/cross-platform pwsh can actually do the job increasingly well. I only even used the thing at first as a rosetta stone to help me translate CI scripts from shell to dos/bat, but on finding I could use one script for mac/win/lin/bsd I made the switch. And, aside from when I'm asking myself how I can abide a scripting language where '`' is the escape character, I haven't looked back.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
@deffcolony this is yours to consider
