### ISSUE TITLE
[FEATURE_REQUEST] Provide Official Docker Image / OCI

### ISSUE THREAD

**Issue by finalparanoia** [SillyTavern/SillyTavern#1366]
### Have you searched for similar requests?

None

### Describe the solution you'd like

use pipeline privide docker Image / OCI to simplified deployment and avoid dependence issue.
使用流水线提供Docker镜像或OCI镜像以简化部署及避免依赖问题

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
https://github.com/SillyTavern/SillyTavern/pkgs/container/sillytavern
