### ISSUE TITLE
[BUG] <Unable to access the tavern page, displaying link 0.0.0.0>

### ISSUE THREAD

**Issue by landones** [SillyTavern/SillyTavern#1368]
### Environment

Self-Hosted (Bare Metal)

### System

windows11

### Version

latest

### Desktop Information

node 20.9.0
windows11
rtx 4060 laptop

### Describe the problem

Unable to access the tavern page, displaying link 0.0.0.0
![1](https://github.com/SillyTavern/SillyTavern/assets/67811286/d422867c-b48c-42c6-9bf4-5d33432762b5)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by deffcolony** [comment]
@landones When you access a web page locally, you typically use an IP address like 127.0.0.1 or localhost to refer to the loopback interface, which is your own computer. so try 127.0.0.1:8000 to access sillytavern
