### ISSUE TITLE
Regarding the problem of Chinese characters displaying garbled characters

### ISSUE THREAD

**Issue by qw1642190428** [SillyTavern/SillyTavern#1369]
### Environment

Self-Hosted (Bare Metal)

### System

win10 22h2 Google 119.0.6045.160

### Version

1.10.9

### Desktop Information

node.js【v20.5.0】

### Describe the problem

The Chinese support of the software is not very good. Whether it is translated or modified by myself, the Chinese characters will be garbled. Just like the following, the only garbled characters are this one and nothing else.

������

### Additional info

![QQ截图20231117173000](https://github.com/SillyTavern/SillyTavern/assets/54324781/82c9a6e4-2833-405c-aab9-f6d41503863b)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
This comes from the Google Translations library and happens not only for your language. Switch the translation source if that concerns you.

**Comment by Cohee1207** [comment]
Should be fixed by https://github.com/SillyTavern/SillyTavern/commit/ded26f978399f66f3ca50424089d923e7dd8171d
