### ISSUE TITLE
[FEATURE_REQUEST] Can we support vits-simple-api as a new  local TTS API

### ISSUE THREAD

**Issue by cj0596** [SillyTavern/SillyTavern#1370]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

SillyTavern is a powerful LLM chat system.I love to use it to chat with some anime characters.On the other hand,there are lots of people make some vits tts model with some anime character voice.I think it's good to combine them together by a local vits-tts service vits-simple-api,which has a clear api document now.

vits-simple-api[:https://github.com/Artrajz/vits-simple-api
](https://github.com/Artrajz/vits-simple-api/blob/main/README.md)

### Describe the solution you'd like

Add the support for vits-simple-api as a choice of TTS

### Describe alternatives you've considered

It has a clear and detail api document,and has a good effect.

### Additional context

It will have a good effect when we chat with some anime character especially in Japanese.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

Maybe

**Comment by yujianke100** [comment]
I wrote a script myself to achieve it: https://greasyfork.org/zh-CN/scripts/482384-vits-simple-api-for-sillytavern

**Comment by DoshideDK** [comment]
> I wrote a script myself to achieve it: https://greasyfork.org/zh-CN/scripts/482384-vits-simple-api-for-sillytavern

Could you please add logic to only send recognized quotes within the conversation?

**Comment by DoshideDK** [comment]
> I wrote a script myself to achieve it: https://greasyfork.org/zh-CN/scripts/482384-vits-simple-api-for-sillytavern

Could you please support the integration of the Hiyori UI API?thanks
