### ISSUE TITLE
[FEATURE_REQUEST] Automatic detection for "temporary" characters

### ISSUE THREAD

**Issue by AlyxMS** [SillyTavern/SillyTavern#1375]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

During chat sessions with characters, sometimes a "temporary" character would be introduced, a co-worker in the office, the shop owner when visiting a shop with a character, a witness when investigating a crime scene... Sometimes they are "created" by me using `/sendas`, other times they are "created" by the AI character, like:

**Me:** Rachel, could you talk to that stranger overthere and see what he knows while I have a closer look.

**Rachel:** Of course. *Walks over to the stranger* Hi, can you tell us something about this? Were you here when it happened?
Stranger: Absolutely. I was jogging when

The stranger's dialogue would be within Rachel's dialogue. I can sidestep this by creating a "stranger" empty character and converting the chat to a group chat. But that seems like a lot of work when this "stranger" will be no logner mentioned after a few lines.
I wish there's some kind of automatic detection to format that line from the stranger as an individual character, like with a `/sendas`. It would make it the interface a lot clearer and prettier.

### Describe the solution you'd like

Upon detection of the pattern `(new line)` `Something` `:` `Some more thing` `(the end) or (pattern of another character's speech starting)`, it would be given an individual speech bubble with `Something` as the character's name and `Some more thing` as its content.

If more than one character is detected, create more bubbles.

With option to:
- Enable this feature.
- Check the character card list for automatic avatar assignment.
- Apply to user dialogues.
- Apply to AI dialogues.

I understand that SillyTavern store each piece of dialogue as an individual thing. I can see two approaches of doing this.

1. Automatically split this part off as an individual dialogue and treat it like one. As if added via `/sendas`.
2. Display it like an individual dialogue but it is still part of the original dialogue that generated it. It will be a visual formatting thing only and it can't be deleted, edited like a normal dialogue. Instead only its "parent" dialog can be edited or deleted. I can see this might be hard to maintain with future development.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
Sounds interesting, will consider it if it has some demand, but as an optional plugin.
