### ISSUE TITLE
Feature Request: Make openai baseurl configurable

### ISSUE THREAD

**Issue by jmtatsch** [SillyTavern/SillyTavern#1381]
Its hardcoded here:
https://github.com/SillyTavern/SillyTavern/blob/dd8deab4e39f73c71bbde43b267b0b2923b1b33a/server.js#L123
would be great if it were configurable via UI or in the config file.

This would allow to use any openapi compatible api. There are plenty that server local/personalized models.
Also people that use the azure hosted version of GPT would be happy.

**Comment by AlpinDale** [comment]
This can be configured from the proxy URL field in the generation settings tab after selecting OpenAI as the endpoint.

**Comment by Cohee1207** [comment]
Already been implemented, twice. Either via proxy or "custom endpoint" in the newest release.
https://docs.sillytavern.app/usage/api-connections/openai/#proxy
