### ISSUE TITLE
[BUG] Main, JB, & NSFW prompts cannot be injected to absolute positions

### ISSUE THREAD

**Issue by qwertea** [SillyTavern/SillyTavern#1382]
### Environment

Self-Hosted (Bare Metal)

### System

Firefox 119.0.1

### Version

1.10.9 'release' (dd8deab4)

### Desktop Information

- Node.js version: v21.1.0
- Generation API: OpenAI
- Branch: Release
- Model gpt-4-1106-preview

### Describe the problem

When I set those prompts to an absolute position of 1 in the prompt manager, above the last chat message, they still behave as if I'm using relative positioning. I've worked around this by using custom prompts for everything instead of the builtin fields, but it would be nice if this was fixed.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
They were not supposed to be injected to absolute. I removed the position selector from them in 1.10.10.
Use custom injections for this, also JB & NSFW have no deep meaning behind them or any difference from custom prompts with the same content, they are just predefined text parts for the lazy.
