### ISSUE TITLE
Add an "Adjust context size to worker capabilities" option for Mancer.

### ISSUE THREAD

**Issue by ghost** [SillyTavern/SillyTavern#1384]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Every time I change from KoboldAI Horde to TextGen WebUI, specifically Mancer, I have to change my context size to the maximum that the bot can handle, and I'm really clumsy, forgetting to do it every time just to receive an error and making me change my settings. Then when I go back to use KoboldAI Horde, I forget to change it again and the bots stay capped at the maximum Mancer was using, which leads to me having to change it manually again.

### Describe the solution you'd like

Adding a "Adjust context size to worker capabilities" checkbox to Mancer's tab, just like the one in KoboldAI Horde tab.

### Describe alternatives you've considered

Default capping at the maximum size Mancer can handle, but for some people that would like to send less context, this would be worse, since they wouldn't get as much control as my first suggestion.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
When you select a model in mancer, it automatically adjusts its context and reply size to the model-defined maximum. So if you pick your model again, it can adjust itself.

**Comment by ghost** [comment]
Yeah, but I gotta select it manually instead of having it happen 100% automatic, that and the context doesn't change back into normal when swapping back to KoboldAI

I'll try to rephrase what's happening.

Changing my API from KoboldAI Horde to Mancer doesn't automatically change my context size to the maximum supported by that Mancer model that is already selected, 
I'd have to re-select it so it happens.

That and changing back from Mancer to KoboldAI Horde doesn't change my context back to the one I was previously using on the Horde before using Mancer.

That's what my recommendation was supposed to fix.

Sorry if I didn't make myself clear before, English isn't my first language.
