### ISSUE TITLE
[FEATURE_REQUEST] Keyword based sound effects

### ISSUE THREAD

**Issue by GentlemanOfCulture** [SillyTavern/SillyTavern#1388]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

The dynamic audio extension is linked to expressions and backgrounds, but there seems to be no audio extension that triggers sounds based on keywords.

### Describe the solution you'd like

I suggest a keyword system for sound effects that is similar to the existing keyword system used for world entries.

For example:
"punch" AND "miss" = Whoosh Sound
"punch" NOT "miss" = Hit Sound

With those keyword triggers, I could have a simple boxing fight scene where a "whoosh" sound is played when a character misses and a "hit" sound is played when a character hits.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

None

**Comment by xxxbap** [comment]
I second this request. I think it would also be helpful to associate several sounds with one keyword group, for example, if the word "explosion" comes up it will randomly select any audio file that has been assigned to that group of words (e.g. explosion1.wav, big_explosion.wav) to prevent it from becoming overly repetitive. 

I imagine the input fields to look like this: 

[keyword group: explode, explosion, exploding, exploded] [audio: explosion1.wav, big_explosion.wav]

**Comment by SurrealiSam** [comment]
Bumping this in 2026. Surprised no one has made anything like this as an extension or that it got very little attention. This seems like a logical addition for an RP.
