### ISSUE TITLE
[FEATURE_REQUEST] BasicAuthentication only on external connection.

### ISSUE THREAD

**Issue by zip6como** [SillyTavern/SillyTavern#1391]

**Comment by Cohee1207** [comment]
I'm not sure there's an option to easily detect a local network connection. If implemented incorrectly, it opens a huge security hole, so I wouldn't rush with it.

**Comment by zip6como** [comment]
> I'm not sure there's an option to easily detect a local network connection.

SillyTavern could just detect 192.168.*.* & 127.0.0.1 as local connections.
Or maybe a whitelist for BasicAuthentication like the regular one.
