### ISSUE TITLE
[FEATURE_REQUEST] Add group "Write the next reply as..." to Utility Prompts in Presets

### ISSUE THREAD

**Issue by imesha10** [SillyTavern/SillyTavern#1393]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

I'm modifying a group jailbreak and the automatically injected "[Write the next reply only as {{char}}]" is getting in the way.

### Describe the solution you'd like

Add this to the utility prompts in the presets so I can change it to something else or leave it blank to disable it entirely. 

### Describe alternatives you've considered

None.

### Additional context

None.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

No

**Comment by Cohee1207** [comment]
This is done. With bonus configurable scenario and personality wrappers.

**Comment by imesha10** [comment]
Thank you!
