### ISSUE TITLE
Extra plugin for Exposing API or communicate through GET / POST 

### ISSUE THREAD

**Issue by MISTERNEGATIVE21** [SillyTavern/SillyTavern#1396]
Well it could be interesting if every elements on the web Ui could be controlled through rest Api or even sending command/messages Because silly tavern already handles the integration of various protocols and gives a nice LLM but is there any background Apis built in to extract text,audio, and img from the url

**Comment by Cohee1207** [comment]
This is not an intended use case and not in the project scope. You can use UI extensions to communicate with SillyTavern's UI. Look how to build your own based on this example: https://github.com/city-unit/st-extension-example
