### ISSUE TITLE
[FEATURE_REQUEST] LiteLLM Integration

### ISSUE THREAD

**Issue by gustrd** [SillyTavern/SillyTavern#1398]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

New models with APIs are realeased all the time, and it's hard to integrate then all one-by-one.

### Describe the solution you'd like

We could use LiteLLM's proxy to connect to every API already mapped by then (it's a lot, cotinuously updated - https://docs.litellm.ai/docs/providers ).

The documentation is good, it looks easy to integrate, and it's open-souce:
https://docs.litellm.ai/docs/simple_proxy

### Describe alternatives you've considered

- Include the APIs one-by-one, duplicating their work.

- Maybe we could add the litellm proxy server as an extension, simplifiying the setup to the user.

### Additional context

Thanks for the great work, this project is a great example of open source colaboration.

I can try to implement it if you like the idea and no one else is avaliable.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

Maybe

**Comment by Cohee1207** [comment]
Does it really need to be a separate API option since it provides just an API URL replacement? Which SillyTavern already has by setting the  "Reverse proxy" address URL in the settings.

**Comment by ghost** [comment]
Hey @gustrd i'm the maintainer of litellm - how can we help here?

**Comment by gustrd** [comment]
> Hey @gustrd i'm the maintainer of litellm - how can we help here?

Thanks a bunch! No tech queries here, just need a bit of space to dive into implementation. Quick request for the model selector: adding a slick 'LiteLLM' option. Pick a model, drop the API key. Easy peasy – just looking for some helping hands.

**Comment by gustrd** [comment]
I realized there's no need, because I can use the LiteLLM server with the API to oogabooga.
