### ISSUE TITLE
[FEATURE_REQUEST] Assign a chat completion preset to each character in a groupchat.

### ISSUE THREAD

**Issue by Anonymous8768** [SillyTavern/SillyTavern#1402]
### Have you searched for similar requests?

Yes

### Describe the solution you'd like

The option to assign a specific preset to each character in a groupchat so that different characters can be set to use a different set of prompts or model without having to manually swap every reply.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

No

**Comment by rosx27** [comment]
this is kinda like autogen. maybe including an option on connection settings to include additional API endpoints will do the job. for the character, maybe a setting "API Setting: API 1, API 2".

i think this feature is very useful e.g.: when asking an ai to create a python program, the instruct model will lay out all the necessary list of task for the coder model to create.

this is exactly what I have in mind when I request for autogen implementation.

**Comment by Cohee1207** [comment]
In the staging branch, I have added the ability to execute STscripts when a group member is getting activated before their turn. So it allows you to execute `/api` and `/preset` commands to switch presets based on the currently chosen character. The option is under the Quick Replies extension editor, check it out.

Related commit: https://github.com/SillyTavern/SillyTavern/commit/4f55824d7f0e0ff90886e6f53850a74b839d0206
