### ISSUE TITLE
[BUG] "Summary Settings" button shows partial information randomly

### ISSUE THREAD

**Issue by imesha10** [SillyTavern/SillyTavern#1408]
### Environment

Self-Hosted (Bare Metal)

### System

Windows 11

### Version

SillyTavern 1.10.10 'staging' (87707b56)

### Desktop Information

Node JS: v18.15.0
Generation: OpenAI reverse proxy
Branch: Staging
Model: any gpt version

### Describe the problem

I brought this up on #1355 and I thought it was fixed but it seems like it was not. I also think I didn't describe it enough.

When pressing the **"Summary Settings"** button it only shows part of the full settings. 
This happens randomly. It seems to go back to normal when I restart it again. I have tried to figure out what is causing it but I could not.
It's easier to show this with video so please refer to the videos below, there is also an image of how it's supposed to look in the end.

This is an example clip of this not working while it's attached:

https://github.com/SillyTavern/SillyTavern/assets/16441743/a1c91d4e-1f39-41ab-bd1d-d1aab042cb35

This is an example clip of this not working while not attached:

https://github.com/SillyTavern/SillyTavern/assets/16441743/ad7468c0-5eff-4d71-885a-739b7c367936

This is how it's supposed to look.
![image](https://github.com/SillyTavern/SillyTavern/assets/16441743/f1a9a5d3-189a-4c46-adae-09fd68dfc08e)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by underscorex86** [comment]
do you have the Extras Summary API connected when the "bugged" settings menu happens?
(not about what you have selected in the dropdown, just whether it is connected.

**Comment by imesha10** [comment]
> do you have the Extras Summary API connected when the "bugged" settings menu happens? (not about what you have selected in the dropdown, just whether it is connected.

@coffeebrown0 no I don't have the Extras Summary API connected when the bugged menu happened.

I just checked today and I don't seem to be able to recreate this issue, maybe it's because this happens after I use it for a while and then open the summaries menu.
In order to side step this issue I can also just restart the sillytavern server which fixes it.

I think I will close this issue for now and if it comes back I will try to debuging ST on my own and find the source of the problem and @ you.

**Comment by Cohee1207** [comment]
I was able to reproduce this a couple of times but don't know the exact steps. The workaround is clear however - you need to switch summary sources back and forth for settings to reappear. Maybe the source settings are not always properly applied on load every time. I'd have to check it later.

**Comment by imesha10** [comment]
Ok thanks, I'll keep an eye on this if this comes back but maybe it's already fixed by the commits. 🔥
