### ISSUE TITLE
[FEATURE_REQUEST] dalle 3 from proxybaseurl

### ISSUE THREAD

**Issue by ytpk** [SillyTavern/SillyTavern#1410]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

in the current implementation, the real openal api is used instead of what is specified in the proxy.

### Describe the solution you'd like

is it possible to ask the great tavern to create conditions for using dalle 3 inside the proxy?

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
No features for using proxies or unofficial API URLs are planned.
