### ISSUE TITLE
[FEATURE_REQUEST] Making the Web Search Extension work locally (without relying on api)

### ISSUE THREAD

**Issue by iChristGit** [SillyTavern/SillyTavern#1411]
### Have you searched for similar requests?

None

### Is your feature request related to a problem? If so, please describe.

There are plenty of projects that support the web search functionality without api usage, using the machine browser.

Examples:
https://github.com/huggingface/chat-ui/
https://github.com/simbake/web_search
https://github.com/ParisNeo/lollms-webui

Can the extension have an option to use local search for people who dont want to use api for search?

Thanks!

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
Updated Extras and WebSearch plugin with Selenium-based Google and DuckDuckGo searches.

**Comment by iChristGit** [comment]
> Updated Extras and WebSearch plugin with Selenium-based Google and DuckDuckGo searches.

You just made my whole week a lot better! Its working solidly,
Thank you once again!

**Comment by iChristGit** [comment]
> Updated Extras and WebSearch plugin with Selenium-based Google and DuckDuckGo searches.

There is an issue when trying both translate and web search it wont trigger the search function, i have tried even putting the foreign lanauage trigger word in the list, should i open a different issue?


Also, it seems to also add the "search' activation word in google instead of searching for the subject itself without the activation word.

![image](https://github.com/SillyTavern/SillyTavern/assets/20077386/d7998948-2f76-471c-8512-0d3655eb73ad)
![image](https://github.com/SillyTavern/SillyTavern/assets/20077386/a146e8fb-ebc0-4227-8869-b36fe7daa7bc)

**Comment by iChristGit** [comment]
Fixed
