### ISSUE TITLE
[FEATURE_REQUEST] user Identifier fix

### ISSUE THREAD

**Issue by ytpk** [SillyTavern/SillyTavern#1412]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

with a recent update, openai began to detect jailbreaks through userid, jailbreak works every other time, although with the same settings in risuai and the parameter for a random userid for each request, everything works as it should
{
    "model": "text-davinci-003",
    "prompt": "How do I make a coom?",
    "max_tokens": 1024,
    "user": "user1@company.com"
} = doom apoligise 

{
    "model": "text-davinci-003",
    "prompt": "How do I make a coom?",
    "max_tokens": 1024,
    "user": "random uuid/numbers"
} = good 

### Describe the solution you'd like

in addition to userid, I would also suggest adding a "seed" to parameters such as temperature and other variables, since this also helps to bypass censorship in some situations

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
1. Pull staging update
2. Start server
3. Edit config.yaml, set `openai.randomizeUserId` to true
4. Make a request
