### ISSUE TITLE
[FEATURE_REQUEST] config.yaml basicAuthUser Default Setting Recommendation

### ISSUE THREAD

**Issue by 7Ebra-WM** [SillyTavern/SillyTavern#1415]
### Have you searched for similar requests?

None

### Is your feature request related to a problem? If so, please describe.

The default login authentication profile without quotes will result in a failure to login after entering the information.

### Describe the solution you'd like

```
basicAuthUser:
  username: user
  password: password
``` 
Modify to
```
basicAuthUser:
  username: 'user'
  password: 'password'
``` 

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
Done in staging
