### ISSUE TITLE
[FEATURE_REQUEST]  Web Search Enhancements

### ISSUE THREAD

**Issue by iChristGit** [SillyTavern/SillyTavern#1416]
### Have you searched for similar requests?

None

### Is your feature request related to a problem? If so, please describe.

I wam super excited about the new web search option running it locally with great success.
I have a couple of enhancements to suggest:

### Describe the solution you'd like

1. The search activation word is being used in the google search query, I write "look up openai drama" and it searches it as is, instead of just "openai drama", 
Another approach is maybe let the LLM craft the query (user: who is micheal jackson? Assistant: Search "Micheal jackson biography", then user: how old is he? Assistant search "micheal jackson age")

2. Would be cool to have an option to display the sources in the end of the responses to quickly confirm the output (Source1 , Sourc2, Source3)
Or maybe like this: 
![image](https://github.com/SillyTavern/SillyTavern/assets/20077386/a3890eac-d9a7-445a-860e-2f3290f2b21b)

3.Having the option to choose how many sites visited for context, to limit misinformation or overwhelming the model when the AI visits multiple sites. could be cool to adjust from the UI.

5.When running it on Extras and using the cloudflare link, the websearch does not work as its cant conenct to Extras API while not on the local network, can it be integrated into the main repo?

Thanks for considering.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
Done
https://github.com/SillyTavern/Extension-WebSearch/commit/a28921a8664a09082745b589c2901c33285f5801

**Comment by Cohee1207** [comment]
>  can it be integrated into the main repo?

No, I don't want to run headless browsers under main repo

> 3.Having the option to choose how many sites visited for context, to limit misinformation or overwhelming the model when the AI visits multiple sites. could be cool to adjust from the UI.

It doesn't actually visit anything, only gets page snippets from the search results.

**Comment by iChristGit** [comment]
> > can it be integrated into the main repo?
> 
> No, I don't want to run headless browsers under main repo
> 
> > 3.Having the option to choose how many sites visited for context, to limit misinformation or overwhelming the model when the AI visits multiple sites. could be cool to adjust from the UI.
> 
> It doesn't actually visit anything, only gets page snippets from the search results.

So the LLM only gets the snippet or title? not the article inside the website?
It seems to give good results so maybe its just continuing from the title.. (?)
Thank you for the response

**Comment by iChristGit** [comment]
Also its posibble to make the llm craft the query? So we can ask follow up question and the bot can search for relevant information? It could be amazing
