### ISSUE TITLE
[BUG] Stable diffusion prompts always start with <bot> Said: 

### ISSUE THREAD

**Issue by iChristGit** [SillyTavern/SillyTavern#1418]
### Environment

Self-Hosted (Bare Metal)

### System

W11

### Version

1.10.10

### Desktop Information

![image](https://github.com/SillyTavern/SillyTavern/assets/20077386/beca6f51-c5de-44cb-ae09-7804cd6c4669)This is a small bug that might make some generations in stable diffusion worse by adding the words Bot said: at the start, can it please be removed for next update?

### Describe the problem

When Generating an image with stable diffusion the prompt should start without <Bot name> said: prefix

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Done in staging

**Comment by Cohee1207** [comment]
Released
