### ISSUE TITLE
[BUG] /send command not working as intended

### ISSUE THREAD

**Issue by creamsan** [SillyTavern/SillyTavern#1420]
### Environment

Android (Termux)

### System

iceraven-2.12.1 (Build #2015985067)

### Version

latest staging

### Describe the problem

The /send command adds the message as id 0.

### Additional info

![1](https://github.com/SillyTavern/SillyTavern/assets/141376415/70ab81ce-ef7f-4a1e-9f8e-8b1b61eab518)
![1](https://github.com/SillyTavern/SillyTavern/assets/141376415/c2522739-7226-4a36-aa39-b8456e5c063a)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Should be fixed by now, sorry for that, unintended side effect of another change.
