### ISSUE TITLE
[BUG] Claude 2.1 formatting issues

### ISSUE THREAD

**Issue by DonMoralez** [SillyTavern/SillyTavern#1422]
### Environment

Self-Hosted (Bare Metal)

### System

Firefox, Chrome/ windows

### Version

1.10.10

### Describe the problem

Cloud 2.1 with the system prompt still has formatting issues. Or I've misunderstood something.
If the main prompt's role is system:
It adds an empty (\n\n \n\nHuman: ) right after it(or after all prompts with the system role). Then the first Assistant's message starts.
In the console, it looks like this: 
```
Claude request: Syspromt-blah


Human: 

Assistant: First message
```
When we try to add some instructions to this empty Human:, by adding another prompt after it: this line is shifted down and left empty (if the prompt we added has system role). Or we get empty (\n\n \n\nHuman:) + (n\nHuman: blah-instructions) (in case of role user).
In the console, it looks like this: 
```
Claude request: Syspromt-blah


Human: 

Human: blah-instructions

Assistant: First message
```

In cases where the main prompt's role is user: 
It adds a blank (\n\n\ \n\nHuman: ) before it. So, again, we get empty (\n\n \n\nHuman:) + (n\nHuman: blah from main prompt).
By the way, this is also (2.0 - ) bug.
In the console, it looks like this: 
```
Claude request:

Human:

Human: Syspromt-blah

Assistant: First message
```

So, in most of these cases, Claude's formatting is kinda broken, or the human's messages(instruction) before the Assistant's first message is empty.

P.s. I'm not a programmer... But, currently, I modified (chat-completion.js) to make it not include (addHumanPrefix) when 2.1 is in use. Also, manually added the Human's prompt instruction, before the Assistant's first message.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
I tried disabling the `Human:` prefix after the system prompt, but it tends to fail the validation in most of the cases. `\n\nHuman` is still required. If you figure out a way to convert prompts that works in 100% of cases, send us a pull request.

**Comment by DonMoralez** [comment]
I've never used the git app, so, it would be problematic for me to send a pull request... =)  
But it seems I'm making some progress with reworking the code. Instead of generally adding the `Human:` prefix and then fiddling with formatting, it now adds the correct prefix directly to the first message. 
That should fix the 2.0 bugs(`/n/nHuman: /n/nHuman:` and `/n/nHuman: /n/nAssistant:` double prefixes), and some formatting problems of 2.1. At least during my tests, it worked as it should.
The only thing left to do is to add the editable prompt with `Human:` prefix in between sys and assistant(when 2.1 is in use). I could've tried to add a new utility prompt field or just simply added the `Human:` prefix to the new chat utility prompts(when 2.1 is in use) since we can edit them, and they inject directly before the first message... But, honestly, it is difficult for me to find the right JS file for editing. So, I'll try to figure it out tomorrow...
P.s. I think it will be even better to add sys.format checkbox and set it off(by default). Anthropic claims 2.1 can use 2.0 without any problems, so that solves most of the compatibility problems for regular users.
P.s.s. Just in case I attached my modified chat-completion.js here. [chat-completion.zip](https://github.com/SillyTavern/SillyTavern/files/13540750/chat-completion.zip)

**Comment by DonMoralez** [comment]
Well... As I thought, I'm having a hard time navigating all the tavern's js files. So I tried to modify chat-completion.js further.
Now it should set the correct prefixes for 2.0-. Set the correct prefix for 2.1 when the first message's(Main prompt's) role is `user`/has the `Human` prefix (that allows to use of the 2.0 format with the 2.1 model, since they are compatible). 
When the role of the first message is `system` or `assistant` it switches to syspromt format, and users should manually add a new `Human` prompt (or `Human:` prefix.) with instructions somewhere in between the first message and the first assistant's messages(if they want to have control over that prompt, of course). 
When there is no such prompt, role or prefix found - it adds `"/n/nHuman: Let's get started."` inside the first assistant's prefix to fix the `sys/human/assistant` formatting. I can still imagine a few potential bugs with such insertion, but it should work much better than other variants I have tried.
So I implemented it this way for now until I figure out how to change the other tavern files, or someone will do it in a better way. And of course, you'd better look inside the file and maybe edit something. 

P.s. Attach another modified version of chat-completion.js.
[chat-completionv2.zip](https://github.com/SillyTavern/SillyTavern/files/13574309/chat-completionv2.zip)

**Comment by kunkanader** [comment]
Haven't heard about this issue on [agnai](https://github.com/agnaistic/agnai). Maybe [sceuick](https://github.com/agnaistic/agnai/commits?author=sceuick) found a way to handle it better.

**Comment by Cohee1207** [comment]
@DonMoralez I'm not sure it's very convenient to drag zip files around. Have you considered making a pull request instead?

**Comment by DonMoralez** [comment]
> Haven't heard about this issue on [agnai](https://github.com/agnaistic/agnai). Maybe [sceuick](https://github.com/agnaistic/agnai/commits?author=sceuick) found a way to handle it better.
The last time I used Agnai, it had its own odds with Claude. But that was quite a while ago.

> @DonMoralez I'm not sure it's very convenient to drag zip files around. Have you considered making a pull request instead?
At the moment I'm trying to figure out how to properly make a pull request in the app. So, we'll see.

**Comment by DonMoralez** [comment]
After installing Visual Studio - working with code became much easier. I added a checkbox 'Use system prompt' and a text area 'Human message' under it(the last one displays only when the system prompt format is enabled). At the same time, I slightly changed `chat-completion.js`, and changed the annoying display of console logs (system messages, previously, blended in with the request prompt).
From what I am currently trying to finalize - the "Human message" area. It saves info and mostly works ok, except I keep getting `undefined` when trying to add this info to the request prompt.

**Comment by Cohee1207** [comment]
I think human message can be a config.yaml value to remove the need to have a UI for it. Under a claude specific section like we have for openai

**Comment by DonMoralez** [comment]
Ah, I just didn’t send the info from openai.js… Now everything works as expected.

So, the current logic is as follows:
```
If sysprompt is checked, human’s sysmessage is unfilled, and no other manual human message exists, then the sequence is:   sysprompt >…> (“\n\nHuman: Let’s start.\n\nAssistant:”) prefix.
If sysprompt is checked, human’s sysmessage is filled, and no other manual human message exists, then the sequence is:   sysprompt >…> (“\n\nHuman:”+human’s sysmessage.+\n\nAssistant:") prefix.
If sysprompt is checked, human’s sysmessage is filled or unfilled, and another manual human message exists, then the sequence is:   sysprompt >…> other manual human message >…> (“\n\nAssistant:”) prefix.
If sysprompt is unchecked, the sequence is:   (“\n\nHuman:”) >…> (“\n\nAssistant:”) (Claude 2.0 format mode for 2.1).
```
Also, I think it would be more convenient and intuitive to place the Prefill and Human message text areas under the “Exclude assistant” and “Use sysprompt” checkboxes and show/hide them accordingly (as shown in the attached screenshot). Or would it be better to place them inside the “Quick Prompts Edit” section?

![layout](https://github.com/SillyTavern/SillyTavern/assets/152644348/c76999f6-7726-4025-8a29-95dcd502c838)


Additionally, would there be any issues if I color the Claude console logs using ‘chalk’ in server.js? (my experiments are shown in the screenshot)
![console](https://github.com/SillyTavern/SillyTavern/assets/152644348/5911e7aa-f4a7-445f-ac7e-9b326919beb1)

P.S. The description in index.html needs some polishing. 
P.P.S. I also want to try implementing the Human’s message inside openai.js to see how it works. Maybe it would be better to insert it like this."

**Comment by DonMoralez** [comment]
Uh… After adding the prefix order checker, I discovered another bug in the 2.0. When the Context Size limit is reached, the tavern excludes the first assistant message. This isn’t a problem when using sysprompt, but it may cause a ‘\n\nHuman:’ - ‘\n\nHuman:’ - ‘\n\nAssistant:’ sequence when using 2.0.

**Comment by Cohee1207** [comment]
It's not a bug, it's the way prompt building works. Messages fall off from context one by one, it applies to every API.

**Comment by DonMoralez** [comment]
I know. What I mean is that it disrupts the correct prefix sequence when converting messages for Claude. Therefore, the prompt we send to the Claude server has the incorrect prefix order, which could confuse the AI.

**Comment by DonMoralez** [comment]
Ok... After losing my files due to git a few times, I hope I managed to make a proper pull request with the changes... And not lose some of them in the process... Also, I'm completely smashed because of the tons of time spent on the git app and the fact that I still don't fully understand how to work with it.
