### ISSUE TITLE
[BUG] KoboldCpp token streaming doesn't work with "Text Completion" API; gives blank/empty messages

### ISSUE THREAD

**Issue by valadaptive** [SillyTavern/SillyTavern#1424]
### Environment

Self-Hosted (Docker)

### System

Fedora 37; Docker 24.0.7

### Version

1.10.10

### Desktop Information

- Generation API: KoboldCpp
- Branch: release

### Describe the problem

(EDIT: It looks like this might actually be a problem with the streaming API that's being selected.)

With the "Text Completion" API option selected, and the "KoboldCPP" API selected, token streaming results in blank messages being generated. It seems that the responses are properly generated; they just aren't being handled properly.

To reproduce this, run KoboldCPP locally, connect to it with "Text Completion" and "KoboldCPP" selected in the API pane, then enable token streaming. Responses will be completely blank.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
What's the version of KoboldCpp? Only the version starting from this will work with Text Completions option: https://github.com/LostRuins/koboldcpp/releases/tag/v1.50.1

**Comment by valadaptive** [comment]
Ah, it's version 1.49. I'm using a third-party Docker image that updated to 1.49 just a couple days before 1.50.1 came out--I assumed it was completely up-to-date.
