### ISSUE TITLE
[BUG] SillyTavern server doesn't respond with an HTTP 400 if API requests are missing a body

### ISSUE THREAD

**Issue by valadaptive** [SillyTavern/SillyTavern#1427]
### Environment

Self-Hosted (Docker)

### System

Fedora 37; Docker 24.0.7

### Version

1.10.10

### Desktop Information

- Branch: staging

### Describe the problem

Pretty much every API route in `server.js` starts with a line of code something like this:
```js
if (!request.body) return response.sendStatus(400);
```

The intent is that if someone makes an API request that's missing a body, the server responds with a 400 Bad Request error.

However, all these routes also make use of Express's JSON middleware, which [will set the body to an empty object `{}` if it's missing](http://expressjs.com/en/api.html#express.json).

As a result, there's a lot of dead code involved with checking whether `response.body` exists, because it will always exist.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
I can't entirely agree with classifying it as a bug. Do you know if there are any affected areas? Can this be reproduced from the frontend? I'll set it as a low-priority improvement for now as it's not a performance concern either.

**Comment by valadaptive** [comment]
AFAIK there are no actual consequences since the frontend and backend are pretty tightly integrated. It's just a code style thing.
