### ISSUE TITLE
[BUG] Hovering the Mouse-Over Problem

### ISSUE THREAD

**Issue by LightSaveUs** [SillyTavern/SillyTavern#1434]
### Environment

Self-Hosted (Bare Metal)

### System

Windows 10 Pro 22H2; Google Chrome ver. 119.0.6045.200 (64 bit)

### Version

1.10.10

### Desktop Information

- Node.js 21.2.0
- KoboldCPP 1.51
- Branch [release]
- Model [OpenHermes-2.5-AshhLimaRP-Mistral-7B-Q4_KM.gguf]

### Describe the problem

After upgrading SillyTavern to version 1.10.10, I noticed that when hovering the mouse over the "message options menu" (indicated by an icon with three horizontal bars), the menu does not appear. Instead, you have to click on the icon, and then the menu appears.

Current behavior: To make the menu appear, you need to click on the icon with three horizontal bars on the left side of the text entry box.

Expected/Previous behavior: To make the menu appear, you need to hover your mouse over the icon with three horizontal bars on the left side of the text entry box. 

### Additional info

Attaching a screenshot to confirm the problem and make it easier to see.
(Please clarify whether this change is a bug or a feature, as I perceive it as a bug. The reason: hovering the mouse to make the menu appear is much more convenient while chatting with a character, as it is much less distracting)
![1](https://github.com/SillyTavern/SillyTavern/assets/108632621/3ebf65f9-5820-4570-a689-1cd8b624f0c1)

(P.S. Please disregard the lack of a magic wand icon. It was blocked using AdGuard in accordance with the personal preferences of the author of this ticket)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
That's intended. It prevents accidental clicks when dragging the cursor around the screen and makes the menu appear in line with the rest of the interface: extensions menu is on-click, top panels are on-click, a mobile layout is on-click (as they have no mouse obviously) and everything related to characters is on-click as well. On hover are only the tooltips.

**Comment by LightSaveUs** [comment]
> That's intended. It prevents accidental clicks when dragging the cursor around the screen and makes the menu appear in line with the rest of the interface: extensions menu is on-click, top panels are on-click, a mobile layout is on-click (as they have no mouse obviously) and everything related to characters is on-click as well. On hover are only the tooltips.

Thank you for the explanation.
In that case, I will close this issue.
