### ISSUE TITLE
[FEATURE_REQUEST] Is it possible to change Response (tokens) to 4096 or higher?

### ISSUE THREAD

**Issue by iChristGit** [SillyTavern/SillyTavern#1436]
### Have you searched for similar requests?

None

### Is your feature request related to a problem? If so, please describe.

When generating very large code it would be beneficial to have larger max tokens, is that possible to change in the files? user config of some sort?

### Describe the solution you'd like

A way to increase Response (tokens) to 4096

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
Added unlocked state for response length ("Unlocked" checkbox).
