### ISSUE TITLE
[Question] Summarize usage?

### ISSUE THREAD

**Issue by drallcom3** [SillyTavern/SillyTavern#1442]
### Have you searched for similar requests?

None

### Is your feature request related to a problem? If so, please describe.

-

### Describe the solution you'd like

-

### Describe alternatives you've considered

-

### Additional context

I have SillyTavern and Summarize set up properly. When pressing "Summarize now" it generates a summary which gets inserted in the request.

Question: Is Summarize being used automatically or do I have to use it manually?

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

None

**Comment by sangelone** [comment]
> Is Summarize being used automatically or do I have to use it manually?

Right under the "Summarize now" button you mention is another one. Smash that `⚙ Summary Settings` and configure it to run automatically every _n_ messages in the form that expands below it. As long as you set it to a non-zero number, it will start updating it for you automatically as you go. Just in case it's still not working automatically for you, be sure the "Pause" checkbox is unchecked; that's in there to disable it temporarily without losing all your settings.

![image](https://github.com/SillyTavern/SillyTavern/assets/271933/ed396bf4-8cea-4815-a240-c1b717557cfa)

**Comment by drallcom3** [comment]
Thanks. I just can't see any `n messages` setting there, or one that vaguely sounds like an interval.

![image](https://github.com/SillyTavern/SillyTavern/assets/25057147/99c38c5b-a6e2-4584-953b-157a0809febd)

**Comment by Cohee1207** [comment]
Interval is only for the Main API source. Extras summarize uses a buffer of messages to be summarized since its context size is limited to 1024 tokens.

**Comment by tomudo** [comment]
Does it still work in current recent release? I set "Summarize with:" to "Main API" and set interval to more than 0 but it does not automatic generate summary. I check terminal text print out but never show summary text in any prompts after pass several responses. It will show only by manual generate summary by pushed "Summarize now" button.
