### ISSUE TITLE
[FEATURE_REQUEST] STScript conditional logic in char. desc./persona/scenarios/etc.

### ISSUE THREAD

**Issue by Teashrock** [SillyTavern/SillyTavern#1483]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

No, there's no actual problem.

### Describe the solution you'd like

I was making my characters, and suddenly thought it would be good if I could affect what info is entered with just changing a variable. This would help a creator or user to alter the plot in easy ways, without editing scenarios directly. But for now, it's only possible to check variables only from the input line. In character description, you can get a variable with {{get[global]var::varname_here}}, but there is no "if" statement for it. I tried to use the one that Story String uses, e.g. {{#if}}{{/if}}, but it was just inserted into the prompt as a plain text. Is it possible to implement conditional logic into user personas, character sheets, personalities, scenarios, and world info? Thank you in advance.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

None

**Comment by Wolfsblvt** [comment]
Is planned for the macro rework. Follow this issue for that: #2052
