### ISSUE TITLE
[BUG] Different format of chat file name on file system when doing an chat import into "SillyTavern\public\chats\CHAR" + Missing version number after "Close Chat""

### ISSUE THREAD

**Issue by stho90** [SillyTavern/SillyTavern#1484]
### Environment

Self-Hosted (Bare Metal)

### System

FireFox 120.0.1 (64-Bit), Windows 11

### Version

 SillyTavern 1.10.10 'release' (74e5e0e4) 

### Desktop Information

Not important

### Describe the problem

**This is a low priority issue, maybe even not a real issue.**

As i had a look into my ST folder, i noticed that a newly created chat file and an imported chat file have a different chat name.
Nothing serious from my point of view, but it should be named.

Here is the example:
No. 1: New created chat file.
No. 2: I created an export of the chat file and imported it again.

![grafik](https://github.com/SillyTavern/SillyTavern/assets/143583451/01a38f7c-8047-4986-9e32-34139914cb7d)

Beside that, here is another small low priority issue i noticed while i created this issue here:
If you are in a chat and select "Close chat", you are returned to the start page. On this page, the version number is missing. This version number is displayed again if you press F5 and reload the page.
![grafik](https://github.com/SillyTavern/SillyTavern/assets/143583451/50364a74-cbf4-4fd9-9623-a66fd922de00)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Fixed in release
