### ISSUE TITLE
[FEATURE_REQUEST] Add support for Piper-TTS

### ISSUE THREAD

**Issue by dariox1337** [SillyTavern/SillyTavern#1489]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Many of the currently-supported TTS engines are slow on CPU. Piper is blazing fast and quite good at that. It even supports streaming out of the box for almost instant replies.

### Describe the solution you'd like

Add support for piper. 
https://github.com/rhasspy/piper

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

None

**Comment by FemBoxbrawl** [comment]
WE NEED PIPER PLEASE GUYS SOMEONE MAKE AN EXTENSION BECAUSE I DO NOT KNOW HOW :(

**Comment by Cohee1207** [comment]
Now available in a third-party extension by @maxime-fleury
https://github.com/maxime-fleury/SillyTavern-Piper-TTS
