### ISSUE TITLE
[FEATURE_REQUEST] StyleTTS2

### ISSUE THREAD

**Issue by dariox1337** [SillyTavern/SillyTavern#1490]
### Have you searched for similar requests?

Yes

### Describe the solution you'd like

It would be nice to have support for StyleTTS2, which seems to be the best local TTS engine (for GPUs) these days. It's also many times faster than XTTSv2.
https://github.com/yl4579/StyleTTS2

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
This is a Python project and ST is a JavaScript app. They are not compatible. You can ask to add it here: https://github.com/daswer123/xtts-api-server
Or create a separate API server that will provide access to the TTS model. Otherwise, it has no use for ST.

**Comment by dariox1337** [comment]
Okay. Thanks.
