### ISSUE TITLE
[BUG] mesExamples parameter does not work with "Never include examples"

### ISSUE THREAD

**Issue by MoodCharge** [SillyTavern/SillyTavern#1494]
### Environment

Self-Hosted (Bare Metal)

### System

Microsoft Edge 120.0.2210.61

### Version

1.10.10

### Desktop Information

- Node.js version v20.8.0
- Generation API KoboldCpp Version 1.51
- Branch Release
- Model [Tess-m-v1.1_34B_Q4_K_M.gguf](https://huggingface.co/TheBloke/Tess-M-v1.1-GGUF/tree/main)
- Operating System Windows 11 22H2

### Overall Description: 
The Example Messages Behavior does not work as expected, The "Never include examples" option wiped the "Examples of dialogue" completely in the final prompt sent via API, even if there is a "mesExamples" parameter in Story String settings.

### My intension and operations: 
I was trying to get "System Prompt" under "Examples of dialogue" in the final prompt sent to via API. So I added the "mesExamples" parameter and moved the "system" parameter below it in Story String Format. Then I set the Example Messages Behavior to "Never include examples" in settings.

### Expected Behavior: 
The final prompt should still contain the Examples of Dialogue, and they should be above the system prompt.

### Current Behavior: 
No Examples of dialogue were found in the final prompt sent via API, even if there is a "mesExamples" parameter in Story String settings. It's not what the [doc](https://docs.sillytavern.app/usage/core-concepts/advancedformatting/#context-template) says about avoiding duplication.

### Additional info

**My SillyTavern Settings when making these tests:**
![image](https://github.com/SillyTavern/SillyTavern/assets/63637655/f9e52fd8-6226-423c-90cf-ecbf7d99b1c9)

![image](https://github.com/SillyTavern/SillyTavern/assets/63637655/dc5904a3-fd9c-47c7-95bb-ce05d15ff75c)
**Story String Format:**
```
{{#if persona}}{{persona}}
{{/if}}{{#if wiBefore}}{{wiBefore}}
{{/if}}{{#if description}}{{description}}
{{/if}}{{#if personality}}{{char}}'s personality: {{personality}}
{{/if}}{{#if scenario}}Scenario: {{scenario}}
{{/if}}{{#if wiAfter}}{{wiAfter}}
{{/if}}{{#if mesExamples}}{{mesExamples}}
{{/if}}{{#if system}}{{system}}
{{/if}}
```
**Messages in the console:**
```
{
  prompt: 'This is the personality of TestJohn.\n' +
    'Below is an instruction that describes a task. Write a response that appropriately completes the request.\n' +
    "Write TestJohn's next reply in a fictional roleplay chat between User and TestJohn.\n" +
    '***\n' +
    '### Response:\n' +
    'This is the first_mes.\n' +
    '### Instruction:\n' +
    "User: This is User's input to the first_mes\n" +
    '### Response:\n',
  use_story: false,
  use_memory: false,
  use_authors_note: false,
  use_world_info: false,
  max_context_length: 4096,
  max_length: 250,
  rep_pen: 1.1,
  rep_pen_range: 512,
  rep_pen_slope: 0,
  temperature: 0.7,
  tfs: 1,
  top_a: 0,
  top_k: 0,
  top_p: 0.95,
  min_p: 0,
  typical: 1,
  sampler_order: [
    6, 0, 1, 3,
    4, 2, 5
  ],
  singleline: false,
  use_default_badwordsids: true,
  mirostat: 0,
  mirostat_eta: 0.1,
  mirostat_tau: 5,
  grammar: '',
  sampler_seed: undefined,
  stop_sequence: [
    '\nUser:',         '\n### Instruction:',
    '\n### Response:', '</s>',
    'USER ',           'USER',
    '<|im_end|>', 
    '### Input',       '### Response',
    'Instructions',    'Instruction',
    '***',             'End',
    'user:',           '\\n'
  ]
}
```

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Fixed in staging
https://github.com/SillyTavern/SillyTavern/commit/ddd4fac38c669829cbccc66029a83ae5b10675f0

**Comment by Cohee1207** [comment]
Fixed in release
