### ISSUE TITLE
[BUG] <cargado infinito>

### ISSUE THREAD

**Issue by Manuel121Z** [SillyTavern/SillyTavern#1497]
### Environment

Other (Specify below)

### System

Android 

### Version

1.10.10

### Describe the problem

Al ser transferido a google la platalla se queda cargando infinitamente, solo dejando en la pantalla el engranaje girando 

### Additional info

Perdóneme por la falta de información que nunca había hecho esto 

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [x] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Zeon1807** [comment]
Intenta usar el git stash, te puede ayudar a resetear todo, simplemente en vez de usar Node Server.js, al momento de iniciar a correr la ventana, tendrias que escribir Bash Start.sh.

**Comment by Cohee1207** [comment]
Do you mean hosting ST from a Google Drive? We don't recommend running from cloud sync storage as it may have an unintended effect on performance and cause other issues. If that's not the case, please provide more details.

**Comment by Zeon1807** [comment]
Me refiero si usas una aplicación llamada Termux, a veces debes aprenderte algunos comandos, puedes usar git help, donde te explicara las funciones que te ofrece, igualmente con npm help....Usas Termux en tu celular para correr SillyTavern, verdad?
