### ISSUE TITLE
[FEATURE_REQUEST] Big picture broke chat layout

### ISSUE THREAD

**Issue by Smoodust** [SillyTavern/SillyTavern#1506]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

When in message in markdown appear big image (for example 1200x2048) it broke layout.
1. ![image](https://github.com/SillyTavern/SillyTavern/assets/42073101/d7ef1da8-085b-429d-a825-b3055c3f6661)
Firstly, it overflows through chat tab.
2. ![image](https://github.com/SillyTavern/SillyTavern/assets/42073101/dcf1e094-4d9c-42fd-a06b-ad79bbf10ebd)
Second, control buttons are in the end of image (which you need to scroll idf you are on phone). Also buttons is quite hard to see.

This is markdown code that I used for for test message (image is SFW):
```markdown
Test greeting with big image.
![alt-text](https://files.catbox.moe/fa9nxm.jpeg)
```

### Describe the solution you'd like

I would like to somehow fix width or height for big pictures in the settings or right in chat tab.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

No

**Comment by LenAnderson** [comment]
Quick fix you can do yourself with custom CSS:

```css
.mes_text img {
    max-width: 100%;
    max-height: var(--doc-height);
}
```

Alternatively what you could do in your markdown:
```
![alt-text](https://files.catbox.moe/fa9nxm.jpeg =100%x*)
```

**Comment by Cohee1207** [comment]
Fixed in code (staging branch) using @LenAnderson 's proposal
