### ISSUE TITLE
setup error! 

### ISSUE THREAD

**Issue by f0ru4nty** [SillyTavern/SillyTavern#1509]
### Environment

Self-Hosted (Bare Metal)

### System

Windows 11

### Version

1.11.0

### Describe the problem

C:\silly_tavern\SillyTavern>call npm install --no-audit
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\silly_tavern\\SillyTavern\\node_modules',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\silly_tavern\SillyTavern\node_modules\pkg-fetch\node_modules'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\silly_tavern\\SillyTavern\\node_modules\\pkg-fetch\\node_modules'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\silly_tavern\\SillyTavern\\node_modules\\@eslint',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\silly_tavern\SillyTavern\node_modules\@eslint\eslintrc'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\silly_tavern\\SillyTavern\\node_modules\\@eslint\\eslintrc'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! network request to https://registry.npmjs.org/yocto-queue/-/yocto-queue-0.1.0.tgz failed, reason:
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in: C:\Users\wwwhu\AppData\Local\npm-cache\_logs\2023-12-10T19_03_40_843Z-debug-0.log
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module 'open'

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Remove the node_modules folder, clear cache and reinstall modules
```
rmdir /s /q node_modules
npm cache clean --force
npm install
```

**Comment by f0ru4nty** [comment]
> Remove the node_modules folder, clear cache and reinstall modules
> 
> ```
> rmdir /s /q node_modules
> npm cache clean --force
> npm install
> ```

I tried but still not working, still same

**Comment by f0ru4nty** [comment]
> Remove the node_modules folder, clear cache and reinstall modules
> 
> ```
> rmdir /s /q node_modules
> npm cache clean --force
> npm install
> ```
ok, solved!
Just a network problem.Thanks for your help!
