### ISSUE TITLE
[BUG] Chats no longer being saved

### ISSUE THREAD

**Issue by heffke** [SillyTavern/SillyTavern#1510]
### Environment

Self-Hosted (Bare Metal)

### System

Firefox 121

### Version

1.11.0

### Desktop Information

Node v18
TabbyAPI
staging + release

### Describe the problem

Chats are no longer being saved, so restarting or even just refreshing the page sets me back to an older version of the chat. The .jsonl files are not being changed. Works fine if I revert back to 1.10.10, but not in 1.11.0

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by heffke** [comment]
Seems it was because I had `enableCorsProxy: true` which I had to have enabled to get the TabbyAPI Loader extension to actually load models.

**Comment by Cohee1207** [comment]
Can't seem to reproduce. Since the server had some API routes changed, you might need to update Tabby loader extension and restart ST server.

**Comment by heffke** [comment]
Yeah, not sure what was going on. Loader extension didn't work without CORS proxy for a while (multiple days), but it did work in Chrome. And yet, now, without any further updates, it does suddenly work. No clue what was going on.
Loader extension aside, I'm not too familiar with CORS stuff, is it expected that it would stop chats from being saved?

**Comment by Cohee1207** [comment]
It shouldn't, maybe it's something else. CORS proxy is needed to make requests from the server, not from the browser since some may be rejected by the browser's policies.
