### ISSUE TITLE
ERR_CONNECTION_DENIED

### ISSUE THREAD

**Issue by Incognitwo2** [SillyTavern/SillyTavern#1513]
### Environment

Self-Hosted (Bare Metal)

### System

Chrome 119, Windows 11 22H2

### Version

1.11.0

### Desktop Information

Node v19.1.0
Kobolcpp_nocuda
release
Mythalion 13b

### Describe the problem

When i try to acces silly tavern on my phone over local network it just stops working sometimes, most of the time it stops for 1 or 2 days and then works again and i even had it stop working for an entire week. It's just giving me  the error "ERR_CONNECTION_DENIED"

### Additional info

Today i started off by using version 1.10.10 of sillytavern but updating it to 1.11.0 didn't help. I also tried using firefox instead of Chrome on my phone but that didn't solve it either. I also tried using my old phone and it's also not working on there.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Make sure your host machine still uses the same IP address. If it's not - create a reservation in your router so it will always use the same IP.

**Comment by Incognitwo2** [comment]
Oh, okay, thank you that solved the problem.
