### ISSUE TITLE
[BUG] On the mobile browser, the input field becomes two lines.

### ISSUE THREAD

**Issue by renewbo** [SillyTavern/SillyTavern#1514]
### Environment

Self-Hosted (Bare Metal)

### System

Opera Mobile 78
Chrome 119

### Version

1.10.10
1.11.0

### Desktop Information

Node.js: v18.18.0

### Describe the problem

Since the update to version 1.10.10, the input field on the mobile app has changed to two lines.
This occurs only in portrait mode; when in landscape mode, it reverts to a single line.
I'm not sure if this is a deliberate feature, but I find it a bit inconvenient.
If this is indeed a feature, I hope there is an option to set it back to a single line. Thank you.

1.10.10
12. Moved wand menu to the left, optimized mobile chat bar layout, and added square avatar style.

### Additional info

Portrait mode:
![Screenshot_20231211-165019](https://github.com/SillyTavern/SillyTavern/assets/151473348/ef398cbf-0e49-4be2-8f05-a7a295321906)
Landscape mode:
![Screenshot_20231211-165047~2](https://github.com/SillyTavern/SillyTavern/assets/151473348/7f1ce986-21f4-4e98-bd3b-08c0c85bbbab)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Not a bug, this is expected to give you more horizontal space for typing in your message since this bar becomes way too narrow with all four buttons being displayed at once.

**Comment by renewbo** [comment]
@Cohee1207 
Thank you for your response! Is there any plans to add a toggle switch? Or is there a particular part I can modify to achieve the original appearance?

**Comment by Cohee1207** [comment]
Custom CSS
```css
#leftSendForm, #rightSendForm {
    flex-wrap: nowrap;
    width: unset;
}
```

**Comment by renewbo** [comment]
Thank you so much for your prompt response! I appreciate your help.

**Comment by Cohee1207** [comment]
This is now a toggle
https://github.com/SillyTavern/SillyTavern/commit/9b9026b12e7464f05d0409bb20ee8882b78a4f61

**Comment by mushinbush** [comment]
It's great to hear that the option has been added as a toggle switch. Thanks again!
