### ISSUE TITLE
[FEATURE_REQUEST] ST config import/export

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [SillyTavern/SillyTavern#1522]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Sort of? 

There's not a convenient listing of which files/folders should be backed up prior to nuking a SillyTavern install, or cloning to another computer.

And, there's not a simple way of posting configs to discord (or here!) for help troubleshooting, except through screenshots.

### Describe the solution you'd like

I would like a way to export/import an entire SillyTavern config as an archive or as a single json/yaml/toml file; except secrets.

Actually, adding to the readme file the storage locations of chats, chars, galleries, etc. would be cool, too. Then I could symlink those dirs to other places on my storage device.

### Describe alternatives you've considered

Reading the .gitignore file(s?) to figure out which files are config and which are not. This will be mightily tedious.

The SillyTavern-Launcher is supposed to be able to backup and restore-from-backup. However, on my computer, it currently fails with an inability to locate the shell built-in command `cd`.

Also, locking this functionality in another project is, at best, inconvenient for everyone.

### Additional context

Sometimes, I want to nuke (`rm -rf`) the directory; for any number of reasons. I want to retain my configuration, though. Preferably, I want to re-import that config on re-install; or clone it to another computer; or restore to a known-good state.

... or, what if I had configs for wholly different profiles? A config consisting of all my custom settings for NovelAI (4? different locations in the UI) would be different from a config-set for Ooba or LocalAI or Ollama or OpenAI or Deepl or ... Switching these in and out, wholesale, would be tremendously useful.

I also want to be able to send human-readable config files to people who can help me solve a configuration dilemma. Screenshot are fine-and-dandy, but nothing beats reading the same files that the software is reading. Exporting it - at least revealing its location within the file tree - would expedite that process.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

No

**Comment by Cohee1207** [comment]
With new 1.12.0 you now have an independent data folder and multiple profiles support. With an ability to export/nuke at will.

Explore now: https://docs.sillytavern.app/installation/st-1.12.0-migration-guide/#users
