### ISSUE TITLE
[FEATURE] can't be packaged

### ISSUE THREAD

**Issue by ghost** [SillyTavern/SillyTavern#1523]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

I tried to package this on the mpr (like AUR but for debs) and i gave up. Everything is mixed together in one big mess. I think it even requires a first run to finish compiling stuff.

In the AUR they are some very obsessive people, there's even a package of XMMS that is close to 20 years old. But there's no package for sillytavern because it's just a mess.

### Describe the solution you'd like

The neet and sane solution, would be to publish this as an npm package.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

No

**Comment by Cohee1207** [comment]
https://www.npmjs.com/package/sillytavern

**Comment by ghost** [comment]
oh, lol... it seams it was published recently.
Then the bug is that it's not mentioned t in the readme.

**Comment by ghost** [comment]
oh... ok, i tried to package it now, it still dumps all it's stuff at random in his directory and requires a first run too.

In order to package it, the install directory must be immutable and user stuff should go in an other OS specific standard folder.

**Comment by ghost** [comment]
I'll be packaging it with unionfs-fuse. It's hacky though.

I moved the npm libs with NODE_PATH

It would be nice, to use variables to define the position of various assets. By default it can be set to the current directory. This way nothing breaks and the changes can happen gradually.

For the immutable stuff, we can survive with all in one folder, but it would be nice to organize them better then that.

For the user folder, we can survive with one, but linux can take 3 (cache, config, data). The internal stuff can easily be moved, however the user files are hard to move, so this should try to be perfect from the very beginning. They must be multy platform libraries that can do this properly.

**Comment by ghost** [comment]
here's the mpr package (like AUR but for debian)
It's as good as it gets given current limitations
https://mpr.makedeb.org/packages/sillytavern

**Comment by ghost** [comment]
Well, this issue isn't really done. I packaged it with a hacky way reserved for xenotransplants.

The issue is really about having a read only installation folder and a read/write user folder. And the location of the folders should be movable.

You could see the possibility of a read only installation folder as an enhancement in security. An unprivileged user shouldn't be able to edit the executables.
