### ISSUE TITLE
[BUG] VERY bad Ooba streaming performance after updating from 356c3a43 to latest

### ISSUE THREAD

**Issue by Daviljoe193** [SillyTavern/SillyTavern#1524]
### Environment

Self-Hosted (Bare Metal)

### System

Brave 1.60.110, Ubuntu 23.04

### Version

SillyTavern 1.11.0 'staging' (2ca9015a)

### Describe the problem

Simply, SillyTavern seems to peg a single CPU core at 100%, which even at 3.5 GHz on my i5-7300U struggles to stream at anything resembling "smooth".

### Additional info

Performance on 356c3a43

![good-performance](https://github.com/SillyTavern/SillyTavern/assets/67191631/72230fc9-68c8-4683-bfbd-e4f2daeadefb)

Versus performance on 2ca9015a (It's this bad even when not recording the screen)

![BAD-performance](https://github.com/SillyTavern/SillyTavern/assets/67191631/c70aaa3b-bf72-4d16-b924-680c73882f20)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
@valadaptive please take a look at this.

**Comment by valadaptive** [comment]
I can't replicate this locally with the latest Ooba running the llama.cpp backend. What version of Ooba are you running, and which backend?

**Comment by valadaptive** [comment]
Also, is it possible for you to record a performance trace using the Chrome/Brave devtools (under the Performance tab), and save and upload it here?

**Comment by Cohee1207** [comment]
I pushed a FPS limiter that should help on very fast streams to throttle some updates. Ooba Gradio UI has a 25 FPS limit, default here is 30.

**Comment by Daviljoe193** [comment]
@valadaptive 
> Also, is it possible for you to record a performance trace using the Chrome/Brave devtools (under the Performance tab), and save and upload it here?

I noticed that my specific stopping strings seemed to cause this weirdness, because no stopping strings resulted in normal performance (On both the old and new version of ST). Those stopping strings being 

```
["<|", "\nUser:", "\n\"{{user}}:", "\n*{{user}}:", "\n{{user}}:", "\n*{{user}}*:", "\n**{{user}}**:", "\nYou:", "\n\n***", "\n***", "\n***\n", "\n\n**Note: ", "\n\nNote: ", "\nSuggestion:", "\n#", "\n**Storyline:**", "\nStoryline:", "**Note:", "</s>", "\n___", "Me: ", "\n[(Human)", "<END>", "(END)", "[END]", "**Author note:", "**Author note**:", "\nAuthor", "**\nAuthor", "\n|", "\n{{char}}'s personality:", "\n{{user}}'s personality:", "\nOOC", "\n**OOC", "\n>", "\nInstruction: ", "\n1.", "\na.", "\nA.", "\nPersonality:", "\nEnd of ", "\n<", "\n <", "\n{{{user}}", "\n1st", "\nFirst", "\nParagraph", "\n*Paragraph", "\nEND", "\nEnd.", "\nEnd:"]
```

So it seems very related to the API itself, which always kinda was the case since the switchover happened from the old websocket streaming to the server sent events streaming, but it wasn't that bad, yet this is just that times a million. As for the performance trace, here. Had to switch to Edge, since it wouldn't save in Brave, and had to try a few times until one came in at a filesize that Github allows. The performance there was somehow WORSE. Sorry for the delay.

[Trace-20231212T155241.json](https://github.com/SillyTavern/SillyTavern/files/13653110/Trace-20231212T155241.json)

**Comment by Daviljoe193** [comment]
@Cohee1207 
> I pushed a FPS limiter that should help on very fast streams to throttle some updates. Ooba Gradio UI has a 25 FPS limit, default here is 30.

Tried that, and the performance is mildly better, but still very much bad. Like 4 frames per second streaming, and without that horrible multi-second stop at the end.

**Comment by Cohee1207** [comment]
> I noticed that my specific stopping strings seemed to cause this weirdness, because no stopping strings resulted in normal performance (On both the old and new version of ST). Those stopping strings being

That actually gives me something to work with, I have an idea now. Please pull and check again.

**Comment by Daviljoe193** [comment]
@Cohee1207
That did it! Now it's back at full performance!

**Comment by Cohee1207** [comment]
Great. Seems like an insane edge case, but good to have it sorted out.
