### ISSUE TITLE
[FEATURE_REQUEST] Mistral AI API support

### ISSUE THREAD

**Issue by aikitoria** [SillyTavern/SillyTavern#1526]
### Have you searched for similar requests?

Yes

### Describe the solution you'd like

Mistral AI API is now starting to become available:

https://docs.mistral.ai/
https://docs.mistral.ai/api/

It's very similar to OpenAI API, but much more useful as it isn't lobotomized and doesn't ban your account for submitting certain content.

I got it "working" by just swapping the API link and model name. The mistral-small and mistral-medium models are both very nice from what I can see. But there are some annoying restrictions:

- stop sequences are not supported (I posted a feature request for them to add it, if they don't it would need client side filtering to kill the streaming request)
- system messages can only be at the start and then never again (the continue feature and image generation are broken as implemented currently)
- it wants alternating user/assistant messages and the user must write the first message (workaround: manually place a user message above the first message of the character)

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

No

**Comment by Cohee1207** [comment]
Available in staging branch.

**Comment by aikitoria** [comment]
Awesome, thanks!
