### ISSUE TITLE
[FEATURE_REQUEST] <title> Add support for Google's Gemini Pro.

### ISSUE THREAD

**Issue by ScarySpy** [SillyTavern/SillyTavern#1541]
### Have you searched for similar requests?

None

### Describe the solution you'd like

Gemini Pro support will be very good for users on a budget, or users who don't want to pay anything as it is on par with GPT 3.5

The addition of this feature will be highly appreciated, and thank you for making such a amazing frontend SillyTavern devs!

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
Please switch to staging branch where it is already supported.

**Comment by ScarySpy** [comment]
Oh thanks! I'm so dumb 😭
