### ISSUE TITLE
[BUG] <Download chat as a text file includes /help commands in html format>

### ISSUE THREAD

**Issue by manwith33** [SillyTavern/SillyTavern#1542]
### Environment

Self-Hosted (Bare Metal)

### System

FIrefox 120

### Version

1.11.0

### Describe the problem

If you export the Sillytavern chat as a text file, the /help commands are included, which I don't think makes sense as a design decision. They aren't really part of the chat. They also export not as plain text but as HTML that looks like the below code, which kind of defeats the purpose of a plain text export. I'd recommend simply not exporting the /help commands.

SillyTavern System: Hello there! Please select the help topic you would like to learn more about:
<code>
&lt;ul&gt;
    &lt;li&gt;&lt;a data-displayhelp="1" href="#" target="_blank" rel="noopener"&gt;Slash Commands&lt;/a&gt; (or &lt;tt&gt;/help slash&lt;/tt&gt;)&lt;/li&gt;
&lt;/ul&gt;
</code>

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Ok, prompt-hidden messages will be hidden from TXT exports now

**Comment by Cohee1207** [comment]
Fixed.
