### ISSUE TITLE
[BUG] Annoying Context Token Lock.

### ISSUE THREAD

**Issue by Avroboros** [SillyTavern/SillyTavern#1546]
### Environment

Self-Hosted (Bare Metal)

### System

Windows 11

### Version

1.11

### Describe the problem

I want to set this fucker right here to 2.620 tokens, which is around the maximum i can use. However it keeps locking to 2.560 or 2.816, and the only way to properly set it to specific values is to create a separate .json file that already has the specific number in it and THEN import it. This is fucking annoying and there is no reason for this locking system to be there, people should be able to input any value they want.

![image](https://github.com/SillyTavern/SillyTavern/assets/146421595/9acb9d39-933d-4647-8a7d-b4ec687dcb10)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Lowered step precision should get you as close as 2616. Is that enough?

**Comment by Woisek** [comment]
I wonder more, how important 60 tokens can be with 2500+ tokens already ... 🤔

**Comment by Cohee1207** [comment]
On the contrary, the step of 64 will get you 2624 but still allows you to more easily set the power of two values such as 2048 and 4096 easily by the slider alone.

**Comment by Avroboros** [comment]
> Lowered step precision should get you as close as 2616. Is that enough?

Sure that works

> I wonder more, how important 60 tokens can be with 2500+ tokens already ... 🤔

60 tokens is already worth one message. Every single token counts.

**Comment by Woisek** [comment]
> 60 tokens is already worth one message. Every single token counts.

Ah, come on ... 60 more tokens when you already output 2500 ...  practically a whole story ... 🤪
I rp with a 250 token output and that already often gives too much of information where the story winds into directions I don't want.
