### ISSUE TITLE
[FEATURE_REQUEST] Together.ai API (openai style already)

### ISSUE THREAD

**Issue by Porln4ie** [SillyTavern/SillyTavern#1547]
### Have you searched for similar requests?

Yes

### Describe the solution you'd like

Hey, the together.ai API uses the same format as openai. Could it please be added as an option? 

https://docs.together.ai/docs/openai-api-compatibility

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

None

**Comment by anachronous** [comment]
i assume this would be similar to https://github.com/SillyTavern/SillyTavern/pull/1552?

**Comment by Cohee1207** [comment]
Merged to staging #1565
