### ISSUE TITLE
[FEATURE_REQUEST] Character card name separated with actually used character name

### ISSUE THREAD

**Issue by valden80** [SillyTavern/SillyTavern#1549]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

There is now ST features expanded so much, that it's more then capable to be used not only as chat client. I successfully using it for story writing, and more. But there is one thing that make it uncomfortable: Character card name always tied to {{char}} macro (and other internal naming). This is natural when you have only one character with this name. But there is actually two sort of problems:
1. When you have several characters with one name (versions of one character or separate) - there is a problem with many cards in list with one name.  For example I like to have them different - like "Anna", "Anna 2", "Anna Reed" - but if I want all of them to have {{char}}=Anna - I need to have all three cards to be named "Anna". This cause unneeded mess in card's list. (Tags making it lesser but still...)
2. On story writing, character card usually used as general scenario setup - for description of story background, not the single character at all. In this case natural name for such card is like "City living scenario", "Pirates of old asteroid", "Fishing with cat" etc. But as character card name always leaking into ST system - it's not possible to name card that way without heavy trick's in template system. (Not possible - such names will poison generation, for story writing character name need to set to something like "AI", "Coauthor", "Writing system" to have effective results.)

### Describe the solution you'd like

Separate field for the "real character name" in the character card - if it's not empty, then ST shall use it for {{char}} macro and other internal character name processing. If empty - character card name used as is.

### Describe alternatives you've considered

Nothing that I can think off.

### Additional context

None.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

Maybe

**Comment by drago87** [comment]
I second this
