### ISSUE TITLE
[BUG] <I just modified the conversation and saved it and it was automatically sent.>

### ISSUE THREAD

**Issue by qw1642190428** [SillyTavern/SillyTavern#1554]
### Environment

Self-Hosted (Bare Metal)

### System

win10 22h2 Google 112

### Version

1.11.0

### Describe the problem

I don't know if this is a bug or another setup issue. After modifying the dialogue, whether it is checked or saved with esc, there is a probability that it will be automatically sent without returning any content. This gives me a headache because I have a limited number of conversations. This is a waste of time.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
If you have automatic summary generation via Main API - disable it

**Comment by qw1642190428** [comment]
> 如果您通过 Main API 自动生成摘要 - 禁用它
