### ISSUE TITLE
[BUG] Settings restoration is broken

### ISSUE THREAD

**Issue by dariox1337** [SillyTavern/SillyTavern#1555]
### Environment

Self-Hosted (Bare Metal)

### System

Firefox 120

### Version

SillyTavern 1.11.0 'staging' (b569d745)

### Desktop Information

- Node 20.9.0
- OpenAI/Kobold
- Staging

### Describe the problem

The settings (e.g. TopP, RepPen, etc) are saved in *.settings files (when I press the "save" button), but SillyTavern on restart reads *.json files that were converted once in the past. Because of this, newer changes are never restored. If I delete the jsons, it forces SillyTavern to convert *.settings again and actually updates them.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
I didn't reproduce this behavior. Updated presets are saved to ".json" and correctly reloaded when switching between presets, reloading the UI, or restarting the server. ".settings" files are not saved anymore, the ones that still exist will not be updated.

**Comment by dariox1337** [comment]
I cloned the repository again, and it seems the bug went away. Maybe some very old settings conflicted with the latest version.
