### ISSUE TITLE
[FEATURE_REQUEST] LJASON Chat Export Options (Incl. prompts)

### ISSUE THREAD

**Issue by PGadoury** [SillyTavern/SillyTavern#1566]
### Have you searched for similar requests?

None

### Is your feature request related to a problem? If so, please describe.

I'd like to generate some training datasets for local fine tuning, so I'd need pairs of (prompt/input, expected output).

### Describe the solution you'd like

Building on the existing chat export options, I'd like an export dialog (or somewhere in the options menu) to be able to specify what gets exported.

I'd like to be able to include (either as a default or as an option to be ticked)

- The prompt being sent to the API is not included in the json,
- The resulting (possibly user-corrected) output.

The second item (user-corrected output) would allow me to fine tune using desired outputs, not just what the LLM might have spat out.

### Describe alternatives you've considered

I thought of scraping the terminal output (piping it to another program or text file), but this would only provide the prompt, not the resulting output, nor would it include any user corrections.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
I made an extension for this: https://github.com/Cohee1207/SillyTavern-Dataset-Export
