### ISSUE TITLE
[FEATURE_REQUEST] Enable API token in URL for Ooobagooga and Kobold AI Classic

### ISSUE THREAD

**Issue by priamai** [SillyTavern/SillyTavern#1571]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Currently I am unable to connect to a Ooobagooga deployment which is setup with an API key.
This is to prevent unauthorized access from strangers.

### Describe the solution you'd like

When API is selected, when Default is OObagooga.
There should be a field Server URL And a API token field.

When API is selected, when Default is Kobold AI classic.
There should be a field Server URL And a API token field.

### Describe alternatives you've considered

I don't know.

### Additional context

This should be similar to what you have for the others API like OpenRouter where there is a API key field.
In this case it will be optional.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

Maybe

**Comment by Cohee1207** [comment]
This sounds like a job for custom headers that you can configure in config.yaml

Please see here for example. 

https://github.com/SillyTavern/SillyTavern/blob/2e6ab8be46f492f3ca4081fedbea13574e8659c0/default/config.yaml#L34-L40

**Comment by Cohee1207** [comment]
Ooobagooga: done
Koboldcpp: done

Kobold Classic: on life support, wontfix
