### ISSUE TITLE
[FEATURE_REQUEST] Allow using other OpenAI API compatible backends

### ISSUE THREAD

**Issue by templehasfallen** [SillyTavern/SillyTavern#1572]
### Have you searched for similar requests?

Yes

### Describe the solution you'd like

Allow custom API backends for OpenAI compatible APIs, such as LocalAI. I managed to use a workaround, but since for OpenAI the models are set, the models list does not update, even though SillyTavern will perform a GET to the /models endpoint.

Ideally:

- Ability to specify custom URL for API
- Load models from custom endpoint and populate models dropdown list

This would be adding full LocalAI support.

### Describe alternatives you've considered

Currently this can be _temporarily_ achieved by doing the following: (its not persistent)

- Set your reverse proxy to your backend IP/Port (ex. http://127.0.0.1:8080/v1)
- Inspect element in your browser and change the value of a model in the dropdown list of models
- Select the model

Your model can be normally queried and it seems all functionality is there.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

Maybe

**Comment by Cohee1207** [comment]
You don't have to do this. Choose "Show external models" and they will appear in the list as intended. Tested with LM Studio and LiteLLM, both work just very fine under reverse proxy if you specify /v1 at the end. Some ofc may not listen an endpoint that contains /v1, then you should remove it.

**Comment by templehasfallen** [comment]
You're absolutely right. Thanks, closing feature request.

**Comment by ishaan-jaff** [comment]
Hi @Cohee1207 do you use LiteLLM Proxy ? 

Can we hop on a call to learn how we can make litellm better for you?
Link to my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat?month=2024-02
