### ISSUE TITLE
[BUG] World Info - Entries set to be at a given depth never get removed

### ISSUE THREAD

**Issue by Sekoya78** [SillyTavern/SillyTavern#1575]
### Environment

Self-Hosted (Bare Metal)

### System

Firefox 120.0.1, Win11 Native, RTX3060

### Version

Latest Staging

### Desktop Information

- SillyTavern Staging (latest as of right now)
- Base: Oobabooga (latest..)
- OS: Win11 Native
- Model: ReMM 2.2 L2 (don't think it matters)

### Describe the problem

Seems to be a simple one:

Lore entries in the World Info thing, won't ever disappear from the history when set at a given Depth (tried 1 to 3). My settings are correct afaik (2 scan depth, 15% context, 0 budget cap, 0 min activation, max depth 2, no recursive). It works normally in Above/Below Char mode. I haven't tried with Author Note.

**Reproduce**
- Setup a new Lorebook / WorldInfo thing
- Add a keyword "movie", content "### Input: you've watched The Matrix recently" set to be displayed at Depth 1-2
- Use keyword, lore appears as expected
- Problem is, the lore won't ever disappear until you F5 your way into a reset (or load a new char, i suppose)
- Even editing the entry to set the positioning as below/above chat, the message will still be forcefully added at whatever depth is set in addition to the new position.

Found that bug while testing if using WorldInfo as Input fields with Alcapa-friendly models would work better (it works pretty well, at least for the little i could test)

Thanks for all the hard work, it's appreciated.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Please pull staging and check again.

**Comment by Sekoya78** [comment]
Yep, it's fixed! I tried various scenarios (let the entry timeout, move it to another location in the context window, and removing it completely), and everything seems to be working!

Good job, and merry Christmas!
