### ISSUE TITLE
[BUG] Can't import JanitorAI characters

### ISSUE THREAD

**Issue by Simplegram** [SillyTavern/SillyTavern#1576]
### Environment

Self-Hosted (Bare Metal)

### System

Windows 11

### Version

SillyTavern 1.11.0 'release' (2e6ab8be)

### Describe the problem

Can't import JanitorAI characters, always throws ```unsupported file type {id}.png```

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Not reproduced for me. Your requests could be blocked by Cloudflare. Otherwise, try the user script (requires to have a Tamper Monkey or Violentmonkey browser extension): https://greasyfork.org/en/scripts/470052-janitor-ripper

**Comment by slayermaster** [comment]
Having the same problem, "Unsupported file type: (randomletters).png

**Comment by shaggy2626** [comment]
Same problem as well on windows 11
![image](https://github.com/SillyTavern/SillyTavern/assets/120447538/157c9acf-2c3b-4f93-9ade-9604925e6710)
![image](https://github.com/SillyTavern/SillyTavern/assets/120447538/1464ded5-fedf-48d6-8607-b330877b258c)

**Comment by LabAviator** [comment]
I am encountering the exact same problem, except it's not only from JanitorAI, but also from Chub. I made sure that it's not some dumb captcha issue by turning off my VPN, but the error persists.
