### ISSUE TITLE
[FEATURE_REQUEST] Support YAML character import, from Oobabooga

### ISSUE THREAD

**Issue by Slug-Cat** [SillyTavern/SillyTavern#1579]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

For some reason, Oobabooga converts imported characters into a YAML file and a separate non-embedded image for each character. These images can't be imported into Tavern as they no longer contain any character data, and the YAMLs can't be imported either as they are apparently unsupported. 

### Describe the solution you'd like

I would like for ST to be able to read files in YAML container to make porting characters from Ooba to ST easier, as well as just providing another avenue for importing new characters.

### Describe alternatives you've considered

I've engaged with an issue on the Ooba github about the change from JSON to YAML (why??) and there is apparently no intention to reverse the change, participants of the thread recommending I submit issues elsewhere (here) to request support for the changed format.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

No

**Comment by Cohee1207** [comment]
Consider providing an example file.

**Comment by Slug-Cat** [comment]
@Cohee1207 
Github doesn't allow yaml attachment for some reason but here's the link to an example yaml on the ooba repo:
https://github.com/oobabooga/text-generation-webui/blob/main/characters/Example.yaml

**Comment by Cohee1207** [comment]
Added. The only fields are description, first message, and name. Ooba doesn't have more.
