### ISSUE TITLE
[BUG] DeepL Free Api fails with Code 400 for certain language identifiers consisting of 2 parts e.g. `zh-cn` or `zh-tw`

### ISSUE THREAD

**Issue by glloyd0314** [SillyTavern/SillyTavern#1584]
### Environment

Self-Hosted (Bare Metal)

### System

Windows 11 Pro, 23H2, 22635.2915

### Version

SillyTavern 1.11.0 'release' (2e6ab8be)

### Desktop Information

- Node: v21.5.0
- Generation API: ooba

### Describe the problem

![20231223134534](https://github.com/SillyTavern/SillyTavern/assets/65362403/b2a3f826-3a4b-4f86-b479-e3f574a14946)
The situation is similar to [another issue for i18n-ally](https://github.com/lokalise/i18n-ally/issues/622). When the language identifiers are consisted by 2 parts e.g. `zh-cn` or `zh-tw`, the DeepL api won't work but only give an error of 400. For other languages like `jp`, it goes smoothly.
I believe the solution would also be simple also as [said in that issue](https://github.com/lokalise/i18n-ally/issues/622#issuecomment-897393125), strip the second code when passing to deepl.

Hope it could be fixed soon!

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Fixed in release. Try again.
