### ISSUE TITLE
[BUG] llamacpp connection doesn't have prompt caching enabled

### ISSUE THREAD

**Issue by HiroseKoichi** [SillyTavern/SillyTavern#1589]
### Environment

Self-Hosted (Bare Metal)

### System

Firefox 120.0.1

### Version

1.11.1

### Desktop Information

- Node.js version: v20.9.0
- Generation API: LLamacpp
- Branch: Release

### Describe the problem

When using the llamacpp connection, the cache is cleared on every generation, causing it to process the prompt from the beginning every single time.

Here is the console output:
```bash
print_timings: prompt eval time =    9327.12 ms /   144 tokens (   64.77 ms per token,    15.44 tokens per second)
print_timings:        eval time =    3956.15 ms /    13 runs   (  304.32 ms per token,     3.29 tokens per second)
print_timings:       total time =   13283.27 ms
slot 0 released (158 tokens in cache)
{"timestamp":1703379264,"level":"INFO","function":"log_server_request","line":2659,"message":"request","remote_addr":"127.0.0.1","remote_port":55968,"status":200,"method":"POST","path":"/completion","params":{}}
slot 0 released (158 tokens in cache)
slot 0 is processing [task id: 2]
slot 0 : kv cache rm - [0, end)
```
Taking a look at the llamacpp [server example](https://github.com/ggerganov/llama.cpp/blob/master/examples/server/README.md#api-endpoints), it says that api requests have cache_prompt disabled by defaut: `cache_prompt`: Save the prompt and generation for avoid reprocess entire prompt if a part of this isn't change (default: false)

There is a fix available for this which doesn't involve any changes to SillyTavern; you change the following values in `/examples/server/server.cpp` to true, then recompile llamacpp:
```cpp
line: 194    bool cache_prompt = false; // remember the prompt to avoid reprocessing all prompt
line: 715    slot->params.cache_prompt     = json_value(data, "cache_prompt",      false);
line: 2442   llama_params["cache_prompt"]      = json_value(body, "cache_prompt", false);
```
After doing so, the console output now displays the cache and there is no delay when regenerate the prompt:
```bash
print_timings: prompt eval time =     666.02 ms /     0 tokens (     inf ms per token,     0.00 tokens per second)
print_timings:        eval time =    9899.18 ms /    31 runs   (  319.33 ms per token,     3.13 tokens per second)
print_timings:       total time =   10565.20 ms
slot 0 released (176 tokens in cache)
{"timestamp":1703382999,"level":"INFO","function":"log_server_request","line":2659,"message":"request","remote_addr":"127.0.0.1","remote_port":60968,"status":200,"method":"POST","path":"/completion","params":{}}
slot 0 released (176 tokens in cache)
slot 0 is processing [task id: 4]
slot 0 : in cache: 144 tokens | to process: 0 tokens
slot 0 : kv cache rm - [144, end)
slot 0 : we have to evaluate at least 1 token to generate logits
```
I'm perfectly okay with doing this every time I update llamacpp, but it would be nice if cache_prompt was added as a generation parameter in SillyTavern.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Strange that in the documentation this parameter is listed with the output parameters, not the input, that's why I didn't even know it accepts this and has it disabled by default. I think it's fair to say that you'd always want to have prompt caching enabled unconditionally, since this behavior is the default in all other l.cpp backends.

**Comment by HiroseKoichi** [comment]
Thanks :+1:
