### ISSUE TITLE
[BUG] TTS does not work in groups chats for Silly Tavern default characters

### ISSUE THREAD

**Issue by JarodMica** [SillyTavern/SillyTavern#1590]
### Environment

Self-Hosted (Bare Metal)

### System

Windows 11, Chrome Version 120.0.6099.110

### Version

1.11.1

### Desktop Information

- Node js: v20.10.0
- Branch: Release
- TTS Generation API

### Describe the problem

TTS does not work for group chats with the default Silly Tavern characters.  Imported and created characters are fine.

The issue appears to be a mismatch for the dictionary key vs. what is actually being called.  In this case, "Seraphina" is requested but is stored as "default_Seraphina", resulting in an error (see image 1 and image 2).

If you remove "default" from the png file names inside of ```public/characters```, this gets the correct name in the voicemap and works properly (see image 3 for the current name of these png files)

This issue is not present when talking to the characters 1-on-1

### Image 1
![image](https://github.com/SillyTavern/SillyTavern/assets/76232114/66790cff-9fdd-443f-b490-998dfb834c78)

### Image 2
![image](https://github.com/SillyTavern/SillyTavern/assets/76232114/02b458c8-37c1-4ae9-9062-4615217ea4df)

### Image 3
![image](https://github.com/SillyTavern/SillyTavern/assets/76232114/868dc17d-0fa9-4da3-a510-7beaf1e3f3c0)

### Please tick the boxes

- [x] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
I think I fixed it in the last release. Please check.
