### ISSUE TITLE
[FEATURE_REQUEST] Add an option to [enable, modify, remove] the default prompts, in the prompt manager

### ISSUE THREAD

**Issue by ahmed-elj** [SillyTavern/SillyTavern#1591]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

the default prompts like `main prompt` and `char Description`, and `world info` etc...  
why can't we remove or make it injectable in chat history?
it's a restriction for advanced users.

### Describe the solution you'd like

Add a mode (dev/debug mode) or a switch that enable these option to the default prompts.
Name | Role
Position
[Remove] | [edit] | enable/disable
all of them needs to be enabled for every prompt, even the default ones, it add more customization.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
You don't need to use default prompts. Just create custom ones, they cover all your needs.
