### ISSUE TITLE
api url isn't checked for validity.

### ISSUE THREAD

**Issue by iplayfast** [SillyTavern/SillyTavern#1601]
### Environment

Self-Hosted (Bare Metal)

### System

linux mint

### Version

1.11.1? (pulled Dec 27)

### Desktop Information

node --version
v20.10.0

### Describe the problem

I mistyped the api url to 127.0.0.0.1:11343
It would be good to have a check on the url to make sure it is valid. 

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
URL validation exists and works
![image](https://github.com/SillyTavern/SillyTavern/assets/18619528/fd137a0c-5064-4048-9028-4e7236062746)
