### ISSUE TITLE
[BUG] Invalid-Json error when receiving request from Clewd

### ISSUE THREAD

**Issue by Kedwyn** [SillyTavern/SillyTavern#1602]
### Environment

Self-Hosted (Bare Metal)

### System

Win 10

### Version

1.11.0

### Desktop Information

Node.js 20.5.1
Clewd v4.8

### Describe the problem

After Claude.ai finishes generating its body of text, Clewd receives it and tries to pass it over to SillyTavern. When that happens, an API Error occurs.

Considering that ST updates much more frequently than Clewd, I'm inclined to believe that its something on SillyTaverns end. More so because when I reinstaled ST, it worked fine for a couple of generations, then the error returned.

Might be Clewd, ST, Node, or even Claude. I'll leave it to the experts.

### Additional info

![image](https://github.com/SillyTavern/SillyTavern/assets/139186139/99e3d752-8092-4979-aaf9-800d60cc9fef)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
No support for unofficial access methods is provided.

**Comment by Cohee1207** [comment]
"stream" is false, but your API source returns an SSE data chunk instead, use that for debugging purposes.

**Comment by Kedwyn** [comment]
Thank you, I've raised the issue with ahsk and he was able to push out a hotfix for Clewd. Problem was indeed with Streaming turned off. Cheers!
