### ISSUE TITLE
[FEATURE_REQUEST] 给i18n.json的中文部分来一次大修

### ISSUE THREAD

**Issue by Touch-Night** [SillyTavern/SillyTavern#1603]
### Have you searched for similar requests?

None

### Is your feature request related to a problem? If so, please describe.

目前的翻译有很多不正确不严谨的，而且缺失了很多键与值。我曾经尝试补齐，但是应用后会导致整个ui无法交互的bug。

### Describe the solution you'd like

重新整理i18n.json，并重新检查翻译。

### Describe alternatives you've considered

[i18n-wip.json](https://github.com/SillyTavern/SillyTavern/files/13783272/i18n-wip.json)
[i18n-wip-nocomment.json](https://github.com/SillyTavern/SillyTavern/files/13783273/i18n-wip-nocomment.json)
这里是我整理到 $\frac{2}{3}$ 的语言文件

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

Maybe

**Comment by Cohee1207** [comment]
I have no idea what is this about. I don't speak Chinese, all localization was submitted by the community.

**Comment by Touch-Night** [comment]
I'm aware of that, so I write the issue in Chinese so the Chinese in the community can understand.  
And where can I get a full list of <data-i18n> keys? I tried to retranslate and add new translation, but it doesn't work (see the attachment).

**Comment by Touch-Night** [comment]
And some keys share the same name, which makes one of them untranslatable in the i18n.json file

**Comment by XXpE3** [comment]
fork staging 修改完之后直接提交合并就行了，很多部分还在开发没定下来暂时不用翻译，只翻译 i18n.json 里有的就行。

**Comment by Touch-Night** [comment]
不过有些语言的键多，有些的少，希望能有一个当前可以拿来翻译的完整英文原文的键值对表
