### ISSUE TITLE
[FEATURE_REQUEST] Find untagged character cards

### ISSUE THREAD

**Issue by novakda** [SillyTavern/SillyTavern#1611]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

With a large number of character cards, it becomes very difficult to manage the tags on them.   While it's possible to select each tag pill twice to excluide all possible tags from the search, this is impractical for hundreds of tags.

### Describe the solution you'd like

A method to find characters that have no tags at all.   Possible implementations:

* Add "most tags", "least tags" as a sort option (by number of tags)
* Select All and/or Invert Selection controls in the tag list
* A button or search option that directly filters to only characters with no tags
* Search expressions and wild cards like Danbooru
* More advanced bulk tag management, possibly with an extension

### Describe alternatives you've considered

Extensions seem to be able to manage tags, but I'm not sure how complex a UI can be implemented in that framework.  There are existing extensions that manage tags such as [st-bulk-card-manager](https://github.com/city-unit/st-bulk-card-manager) and Auto Tagger, so it does seem possible to build something to do this, but I don't know what the level of effort would be.

### Additional context

I have some experience in front and backend development with frameworks like Vue and React, but I'm not familiar with the framework(s) used by SIllyTavern (I am familiar with express, JQuery and general HTML/CSS/JS development).

I'd be interested in writing an extension to implement this, but I can't estimate the level of effort for that just yet.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

Maybe

**Comment by Wolfsblvt** [comment]
If you are still looking for this, there is an extension now, called [sakhavhyand/SillyTavern-AnotherCharManager](https://github.com/sakhavhyand/SillyTavern-AnotherCharManager).
Should achieve what you were looking for.
