### ISSUE TITLE
[FEATURE_REQUEST] Multiple expressions packs for a character

### ISSUE THREAD

**Issue by korsar4eg** [SillyTavern/SillyTavern#1615]
### Have you searched for similar requests?

Yes

### Describe the solution you'd like

It would be very nice to have the ability to set up multiple expression packs for a single character (for instance same character in different outfits) and manually select the proper pack of expressions during the chat. 

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

None

**Comment by LenAnderson** [comment]
You did not look very hard, did you? :D
https://docs.sillytavern.app/extras/extensions/expression-images/#how-to-set-an-override
![image](https://github.com/SillyTavern/SillyTavern/assets/7149120/2a2ee6a7-3f44-41ec-9f3a-7260fb111d6f)
```
/spriteoverride (optional folder) – sets an override sprite folder for the current character. If the name starts with a slash or a backslash, selects a sub-folder in the character-named folder. Empty value to reset to default. (alias: /costume)
```
