### ISSUE TITLE
Enable Legacy API

### ISSUE THREAD

**Issue by skaba04** [SillyTavern/SillyTavern#1618]
So i connect my SillyTavern Linux version on my phone using Termux and on the start i get a pop-up that generation may fail if i do not enable "Legacy API" setting. Also when the generation takes longer than 30 seconds the app crashes.

**Comment by skaba04** [comment]
![Screenshot_20231231-135200_Chrome](https://github.com/SillyTavern/SillyTavern/assets/116293460/35fba6c6-ca25-4c23-89b6-34da7f895f03)
![Uploading Screenshot_20231231-135635_Chrome.jpg…]()

**Comment by skaba04** [comment]
![Uploading Screenshot_20231231-135635_Chrome.jpg…]()

**Comment by skaba04** [comment]
![SquarePic_20231231_14021211](https://github.com/SillyTavern/SillyTavern/assets/116293460/7444d369-7f54-4b7e-a69d-f31d4b93a7bf)

**Comment by Cohee1207** [comment]
Please use a proper template for reporting issues. This one lacks crucial details about your actual backend.
