### ISSUE TITLE
[BUG] Connection to SillyTavern-Extras fails if SillyTavern launched with --ssl option

### ISSUE THREAD

**Issue by FlareP1** [SillyTavern/SillyTavern#1620]
### Environment

Self-Hosted (Bare Metal)

### System

Firefox 121.0(64-bit) , Windows 10

### Version

SillyTavern 1.11.1 'release' (6508a2d9)

### Desktop Information

node --version
v18.16.0

### Describe the problem

After enabling ssl (required to allow microphone access on remote connections), then the connection to Silly Tavern Extras fails.
-If I launch ST with 'node server.js' then I have full functionality and can connect to Silly Tavern Extras via http from local or remote IP addresses, but remote IP addresses will not allow microphone access as the connection is unencrypted. 

-if I launch ST with 'node server.js -ssl' then I have full functionality and can access to Silly Tavern from local and remote servers via https, including microphone access.  However it is not possible to connect to Silly Tavern Extras on http.  There is no error shown just connection is rejected.  

After debugging I can see that the following line causes an exception that is silently caught.  Manually editing the code to print the error reports 'Network error when attempting to fetch resource' under firefox.  It is possible to manually connect to Silly Tavern by browings to the correct URL 127.0.0.1:5100 in a browser but not via ST.

The ssl mode is effecting the behaviour to connect to a none https address from extras connection, it is not an error of the extras code.  See https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default

https://github.com/SillyTavern/SillyTavern/blob/release/public/scripts/extensions.js line 172
```
async function doExtrasFetch(endpoint, args) { 
...
const response = await fetch(endpoint, args);    <--- throws an exception
    return response;
}
```
The expected behavior would be for the silly tavern extras connection to be uneffected by the --ssl mode and continue to connect normally.

### Additional info

Firefox web console log (ctrl-shift-k) after pressing connect on extras tab.

```
Blocked loading mixed active content "http://192.168.1.xxx:5100/api/modules"
[extensions.js:178:27](https://192.168.1.xxx:8000/scripts/extensions.js)
TypeError: NetworkError when attempting to fetch resource.
    doExtrasFetch https://192.168.1.xxx:8000/scripts/extensions.js:178
    connectToApi https://192.168.1.xxx:8000/scripts/extensions.js:390
    connectClickHandler https://192.168.1.xxx:8000/scripts/extensions.js:304
    jQuery 2
[extensions.js:409:17](https://192.168.1.xxx:8000/scripts/extensions.js)
```

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
This is self-explanatory - you need to run extras server under HTTPS. The only doable way is with --share flag or some nginx proxy server before it as extras doesn't support running with SSL natively.

**Comment by FlareP1** [comment]
Thanks for the quick reply, I do not want to expose the sever to the internet therefore --share is not an option.  I will investigate the ngnix option and see if this is possible on windows.

**Comment by FlareP1** [comment]
@Cohee1207 Thank very much for pointing me in the direction of the nginx reverse proxy, I have this setup and now I can connect to both Silly Tavern and Silly taven extras with ssl.   I can also transcribe from a remote PC via Firefox.  

For some reason it is not yet working from IOS/safari as the audio seems to get lost some how, i'm still working to debug that.

If anyone needs a setup for ngnix this is the working config that I have used, this takes the standard 5100 http connection and turns it into a https connection on 5101.  You can then enter a https address on port 5101 for your extras connection.

```
keepalive_timeout 65;
server {
listen 5101 ssl;
server_name 192.168.1.xxx; #replace localhost with you dns name
ssl_certificate fullchain.pem;
ssl_certificate_key privkey.pem;
ssl_session_cache shared:SSL:1m;
ssl_session_timeout 5m;
ssl_ciphers HIGH:!aNULL:!MD5;
ssl_prefer_server_ciphers on;
location / {
proxy_pass http://localhost:5100;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection ‘upgrade’;
proxy_set_header Host $host;
proxy_cache_bypass $http_upgrade;
}
}
}
```

**Comment by FlareP1** [comment]
I have finally got it working with IOS, ssl and ngix.  The probelm with IOS audio was due to a slightly older version of FFMPEG not correctly dealing with the latest IOS aac(lc) audio format in an mp4a wrapper, i needed to update to the latest FFMPEG then it works perfectly.  

Thanks for your help.
