### ISSUE TITLE
[BUG] Can't connect to Oobabooga: "Models endpoint is offline"

### ISSUE THREAD

**Issue by 3ternal** [SillyTavern/SillyTavern#1621]
### Environment

Self-Hosted (Bare Metal)

### System

Win 11

### Version

1.11.1

### Desktop Information

Node v21.5.0

### Describe the problem

I'm currently unable to connect SillyTavern to the [Oobabooga Text Generation Web UI](https://github.com/oobabooga/text-generation-webui).

I'm starting the application with the `--api` flag, as required, and I can access the UI at http://127.0.0.1:7860. I can also confirm in the settings that the flags for `api` and `public_api` are both true.

Meanwhile, in SillyTavern, I've set the API to Text Completion and the API Type to Oobabooga. When I try to connect, I get the following error in the SillyTavern console:

```
Trying to connect to API: {
  api_server: 'http://127.0.0.1:7860',
  api_type: 'ooba',
  legacy_api: false
}
Models endpoint is offline.
```

And I get the following error in the Oobabooga console:

```
INFO:     127.0.0.1:14931 - "GET /v1/models HTTP/1.1" 404 Not Found
```

I think it's the same problem that this person encountered: https://www.reddit.com/r/SillyTavernAI/comments/18vzmc8/models_endpoint_is_offline_when_connecting_public/

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
The API server is not hosted at port 7860, it's for Gradio UI only. API endpoint is at port 5000 by default, look closely at the console output of textgen webui

**Comment by 3ternal** [comment]
> The API server is not hosted at port 7860, it's for Gradio UI only. API endpoint is at port 5000 by default, look closely at the console output of textgen webui

Oh! I see, thank you. In that case, it's all working now.
