### ISSUE TITLE
Allow user install extension locally

### ISSUE THREAD

**Issue by feitianfu** [SillyTavern/SillyTavern#1624]
### Have you searched for similar requests?

None

### Describe the solution you'd like

允许用户自行离线下载extension包，并且安装

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
1. Download the extension repo as a ZIP file
2. Unpack to /public/scripts/extensions/third-party
3. You have the extension installed.
