### ISSUE TITLE
[FEATURE_REQUEST] Custom API endpoint type for Text Completion

### ISSUE THREAD

**Issue by deoxykev** [SillyTavern/SillyTavern#1627]
### Have you searched for similar requests?

None

### Is your feature request related to a problem? If so, please describe.

There is a similar feature implemented in #1580 for OAI-compatible Chat Completion endpoints, but not one for Text completion.

### Describe the solution you'd like

Similar to this PR: #1580, could we have a custom endpoint for OAI-compatible text completion as well? Please include the status check bypass option and specifying in a custom model id, even if /v1/models isn't implemented.

### Describe alternatives you've considered

I tried setting custom request headers in the config.yaml and used tabby, but that didn't seem to work well.

### Priority

High (The app does not function without it)

### Is this something you would be keen to implement?

Maybe

**Comment by kingbri1** [comment]
If you're trying to use TabbyAPI, it's implemented in SillyTavern under text completions

**Comment by deoxykev** [comment]
It's not tabby. I think the main issue is the status check, which queries for available models. If there is an option to turn that off and specify a custom model, that would work too.

**Comment by Cohee1207** [comment]
Added.

**Comment by deoxykev** [comment]
Thank you!
