### ISSUE TITLE
[BUG] Failed to read config.yaml

### ISSUE THREAD

**Issue by Aethrios** [SillyTavern/SillyTavern#1628]
### Environment

Self-Hosted (Bare Metal)

### System

W10, FF 121.0

### Version

1.11.1 (37d6f13b)

### Desktop Information

I prefer to use Koboldcpp as my generation engine, but 

### Describe the problem

Used UpdateAndStart to move from ~1.10 -> 1.11.1, and now can't log in or access anything through the front end. Log reads: 

```
D:\SillyTavern\SillyTavern>call npm audit fix --force
npm WARN using --force Recommended protections disabled.
npm WARN audit Updating google-translate-api-browser to 4.2.7, which is a SemVer major change.
npm WARN audit Updating fix to 0.0.3, which is a SemVer major change.

removed 2 packages, changed 3 packages, and audited 747 packages in 2s

101 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
'//' is not recognized as an internal or external command,
operable program or batch file.
Failed to read config.yaml
Failed to read config.yaml
Failed to read config.yaml
Running from source
Failed to read config.yaml
Failed to read config.yaml
Failed to read config.yaml
Failed to read config.yaml
Failed to read config.yaml
SillyTavern 1.11.1 'release' (37d6f13b)
Failed to read config.yaml
Failed to read config.yaml
Launching...
SillyTavern is listening on: http://127.0.0.1:8000/
```

I only bothered with ```npm audit fix --force``` because of another help thread, but I haven't been able to find anything here or on reddit pertaining to this particular issue. Every attempt at logging in seems to fail because the whitelist isn't getting detected, so all connections are terminated. 

My previous, working build had both config.conf and config.yaml files, but I deleted the former at ST's prompting in the log. Subsequent attempts at updating yield the same result.

### Additional info

Despite claiming to launch, no browser session is ever opened. All connections are refused. 

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Remove config.conf and config.yaml, run `npm install` to let it regenerate, restart ST server.
