### ISSUE TITLE
[BUG] /regex not working as intended

### ISSUE THREAD

**Issue by creamsan** [SillyTavern/SillyTavern#1629]
### Environment

Android (Termux)

### System

iceraven-2.14.0

### Version

Latest staging

### Desktop Information

Staging branch

### Describe the problem

Unintended behavior in latest commit. Explained with screenshots below.

### Additional info

Here is the regex script to be run.
![Screenshot_20240103-235615_1](https://github.com/SillyTavern/SillyTavern/assets/141376415/14f49327-ed04-41f4-b89d-c27f25a99e8f)

These are the values I'm going to pass.
![Screenshot_20240103-235709_1](https://github.com/SillyTavern/SillyTavern/assets/141376415/669fa5e7-ba43-45b1-9f2d-c914f8f5fe8e)

Prior to the latest commit, works as intended.
![Screenshot_20240103-235719_1](https://github.com/SillyTavern/SillyTavern/assets/141376415/bf36aebd-d680-4948-8f8f-0b90672e4b4b)

The /regex command returns this in the latest commit.
![Screenshot_20240104-000001_1](https://github.com/SillyTavern/SillyTavern/assets/141376415/542a7322-979a-4e38-a564-70a0ea503635)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
I think this should fix it. At least your case and the case that kickstarted this change work. 
I'm not a very active regex user, so please let me know if there are any cases that still don't work for you.
