### ISSUE TITLE
[FEATURE_REQUEST] Limit regex scripts to messages above certain depths

### ISSUE THREAD

**Issue by qwertea** [SillyTavern/SillyTavern#1630]
### Have you searched for similar requests?

No

### Is your feature request related to a problem? If so, please describe.

Some cards have long, hidden Chain-of-Thought messages or status trackers that eat context tokens. Often, you can't simply regex all of them out as they are tracking something/doing so would confuse the LLM, but you could safely do so for messages above depth 2, for example. This could save thousands of tokens in long chats.

### Describe the solution you'd like

An input box in the regex script editor that defines the minimum depth the regex script would run at.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

No

**Comment by Manimap** [comment]
I have been wondering if someone asked for that one, glad you were.
Setting a depth where the regex is applied would be awesome.

**Comment by AnonCardMaker** [comment]
I came here to make the same request, glad someone already did. Cards with stats are bordering into the unusable, and it's a shame as there is a lot of design space in there. I want to add that the optional depth should be per individual regex rule instead of regex as a whole (this is an issue with lorebooks.)

**Comment by kunkanader** [comment]
Such an obviously needed feature, but sadly Cohee is too busy
I mean, llm like examples VERY much so having such examples in your chat history would be very beneficial but not with the current cost (in tokens or manual work)

**Comment by kunkanader** [comment]
Possibly duplicate of this issue badly described here https://github.com/SillyTavern/SillyTavern/issues/1270

**Comment by Cohee1207** [comment]
This is ready to test.

**Comment by qwertea** [comment]
> This is ready to test.

Thanks for adding it! Tried using the min depth option at 4 with a simple regex that removes comments, but it seems to be affecting the latest output. Edit: Also tried one that removes codeblocks with a much simpler prompt preset, and disabled all other regex scripts, but it still seems to affect the latest output, sadly.

**Comment by qwertea** [comment]
My mistake, I see it's supposed to work with one of the 'Only format' options. I was just trying to delete the text entirely, but that's actually smarter since it doesn't take up context tokens and preserves the contents if you want to check them later. I'll do a few more tests and close the issue if everything works!

**Comment by qwertea** [comment]
Alright, tested a bit. Formatting prompts seems to work without issues. Formatting display works initially when I activate the regex, but it doesn't continue to hide old codeblocks above as I chat further (using Firefox, I did update to 1ae5a8b). Will leave the issue open if you want to fix it, but I'm fine with just the prompt formatting working since I just wanted to save context tokens. Thanks!

**Comment by Cohee1207** [comment]
Old messages are not re-rendered until the chat is reloaded to save resources. I don't know if that should be fixed.

**Comment by qwertea** [comment]
My own use case is for removing already \ from context so it doesn't affect me. Another use case is stat blocks, and I'd wager people won't want them removed from view anyway, only from context. If re-rendering old messages would slow down ST then you should leave it as is, IMO.

**Comment by kunkanader** [comment]
Well, technically it doesn't work properly so I guess it should not be left as it is. 
I think that loading chats in parts was a mistake, it should be optional at least. Just here we can see how it breaks adding even such simple functionality. Rewriting regex plugin to run each time a new part is being rendered is a worse solution obviously

**Comment by AnonCardMaker** [comment]
There is a HUGE bug with this feature.
The bug is that the regex rule is not applied AT ALL when you load SillyTavern.
Activating/Disactivating the rule does nothing. You need to open the regex rule itself and 'Save' it even if you didn't change anything. Now the rule is applied as intended, but for further posts it only works for the "Only format prompt" element and not the "Only format display" (but the visual bug was already noted above.)

The rule I'm using:
>Find Regex
```
(```)?\n?<thinking>[\s\S]*?<\/thinking>\n?(```)?\n?\n ? ?
```
-Affects
✅ AI Output
-Min Depth
1
-Max Depth
Unlimited
-Other Options
✅ Only Format Display
✅ Only Format Prompt

**Comment by Cohee1207** [comment]
@AnonCardMaker I found the issue you're describing, however, the other issue is harder to fix as I'm not sure that rendering the entire chat on every action to apply the display regex is a very performance-effective strategy.

**Comment by AnonCardMaker** [comment]
@Cohee1207 Thanks. I honestly don't really care much about the Format Display, but it might become an issue down the road if \<thinking>methods and \<stats> become ubiquitous (they probably won't).
