### ISSUE TITLE
[FEATURE_REQUEST] HTML video player not working

### ISSUE THREAD

**Issue by MaterialMiko** [SillyTavern/SillyTavern#1631]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Unless I made a mistake, it seems impossible as of now to use Markdown's html features to include a video player inside a ST message. One can use the following code in for example, Obsidian, to make a local video playable:
```<video src="file:///your/path.mp4" controls></video>```
And this method using either a relative paths to the SillyTavern/public/ folder, or an online .webm/.mp4 file, seems to fail.

- To explain the utility of this: 
When making cards, it is possible to design cards that will pull a local .png/.jpg/.gif file at random using a combination of features in the following way:
```![title](MyPictures/forest{{roll:d42}}.png)```
Which would pull one of the 42 files titled "forest1.png" to "forest42.png" inside the MyPictures folder, created manually inside /public/. Similar methods can be used to pull pictures hosted online. This enables prompts designed for the AI to include a template with the exact text ```![title](MyPictures/forest{{roll:d42}}.png)``` in each message, to show different parts of the forest being explored, for example. Or different pictures of the same character.
- The same idea could apply with webms and .mp4 files. But Markdown doesn't natively have this feature, but its support for html gives us a workaround for this using instead ```<video src="MyVideos/MagicSpell{{roll:d42}}.mp4" controls></video>```
Having this feature, would enable the creation of cards incorporating both pictures and videos, easily.
This method seems to work for the Markdown text editor Obsidian, and SillyTavern does support HTML code for Markdown already. So there must be a solution.

### Describe the solution you'd like

Finding a way for Markdown html text to make a videoplayer read local video files:
```<video src="file:///your/path.mp4" controls></video>```

Bonus point for making the video loop automatically, and for sound to work.

### Describe alternatives you've considered

I have no ideas right now, as I lack the knowledge to help. 
Except that until this feature gets added/this issue gets fixed, converting .webms files towards a .gif format is a valid workaround, using the following method:

```![title]([a folder created inside /public/]filename.gif)```

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

No

**Comment by Cohee1207** [comment]
Use single quotes instead of double quotes. Double quotes have a special treatment in the processing.

**Comment by MaterialMiko** [comment]
Thank you, indeed it works!
For the sake of clarity, adding that this precise syntax perfectly works for SillyTavern to show videos:
```<video src='MyVideos/MagicSpell{{roll:d42}}.mp4' controls></video>```
