### ISSUE TITLE
[BUG] typical_p not matching typical for TabbyAPI (name mismatch)

### ISSUE THREAD

**Issue by Hoborific** [SillyTavern/SillyTavern#1634]
### Environment

Self-Hosted (Bare Metal)

### System

WinNT

### Version

1.11.1

### Describe the problem

Pretty straight forward, I am using TabbyAPI for /v1/completions and ST is passing "typical_p" as "typical_p" however the completion request object for TabbyAPI only takes "typical".

### Additional info

https://hobo.zip/share/I0C4NUn9RS6ZxXZm.png

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Maybe @bdashore3 can just add an alias on Tabby's side?

**Comment by kingbri1** [comment]
Aliased in https://github.com/theroyallab/tabbyAPI/commit/2c57dafc599a3135a82029f224e2ec94b0132701
