### ISSUE TITLE
[FEATURE_REQUEST] Multiple Portraits in Group Chat

### ISSUE THREAD

**Issue by CatapultingWizard** [SillyTavern/SillyTavern#1637]
### Have you searched for similar requests?

Yes

### Describe the solution you'd like

The ability to display portraits for each character in a group chat at the same time while in visual novel mode. Alternatively, it automatically displays the character that last spoke in the group chat.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

None

**Comment by LenAnderson** [comment]
Enable expressions and populate them for all participating characters (you can use the same picture, even the avatar for all 28 expressions).

**Comment by Cohee1207** [comment]
Also consider the following (this is a third-party extension that presumably does what you need):
https://github.com/LenAnderson/SillyTavern-GroupExpressions
