### ISSUE TITLE
[BUG] UI element not showing list on tap

### ISSUE THREAD

**Issue by creamsan** [SillyTavern/SillyTavern#1640]
### Environment

Android (Termux)

### System

iceraven-2.14.0

### Version

Latest staging

### Desktop Information

Branch: staging

### Describe the problem

On mobile, the highlighted select UI elements below don't show the list on tap.

### Additional info

![Screenshot_20240106-120045_1_1](https://github.com/SillyTavern/SillyTavern/assets/141376415/e47679ed-8708-4329-b148-a4a7094a78e6)
![Screenshot_20240106-120118_1_1](https://github.com/SillyTavern/SillyTavern/assets/141376415/cb04ab95-0f82-479e-be56-abd32c417513)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
@LenAnderson please take a look at. 

Also, does "on mobile" means it works on desktop?

**Comment by LenAnderson** [comment]
Looks like sortable is breaking touch events in some children. jQuery cancer...  I'll see what can do later today.

**Comment by LenAnderson** [comment]
Same problems on desktop btw. Touch events are the problem, not the type of device.
