### ISSUE TITLE
[BUG] QR sets' UI elements added by slash commands do not work properly

### ISSUE THREAD

**Issue by creamsan** [SillyTavern/SillyTavern#1647]
### Environment

Android (Termux)

### System

iceraven-2.14.0

### Version

SillyTavern 1.11.2 'staging' (e3d1008a)

### Describe the problem

UI elements of QR sets added with slash commands don't work. However, this can be fixed temporarily by dragging them a bit as shown in the vid.

### Additional info

[MP4_20240107_092105.webm](https://github.com/SillyTavern/SillyTavern/assets/141376415/521ad7cf-5295-4bc2-89bf-c73a158349a8)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by LenAnderson** [comment]
Thanks for testing. Keep 'em coming :)
