### ISSUE TITLE
[FEATURE_REQUEST] Export All Characters

### ISSUE THREAD

**Issue by MilesQLi** [SillyTavern/SillyTavern#1653]
### Have you searched for similar requests?

None

### Is your feature request related to a problem? If so, please describe.

No

### Describe the solution you'd like

A button to allow the user to export all characters and groups.

### Additional context

Could anyone tell me where the character files are stored? Before the function is provided, I can do it manually if I'm told where they are stored.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
They are in /public/characters

**Comment by MilesQLi** [comment]
> They are in /public/characters

Yeah, just found that they are in the  metadata of the images..

**Comment by Slug-Cat** [comment]
Still, could be convenient. For example, a button that auto generates a zip file or something with all of the characters and their logs for importing into another installation.
