### ISSUE TITLE
[FEATURE_REQUEST] <PIPER_TTS - super fast TTS generation for Low end PC'S> PiperTTS extension

### ISSUE THREAD

**Issue by FemBoxbrawl** [SillyTavern/SillyTavern#1655]
### Have you searched for similar requests?

Yes

### Describe the solution you'd like

I think PiperTTS would be a great extension to have, espescially  for people with low end PC's. The generation is super fast. and if you decide to train a voice, you can make it sound really good, a slightly robotic version of what that specific person would sound like.

Voice Training Tutorials (by Natlamir):
Locally, using WSL in windows: https://youtu.be/kGl0a652XtE?si=cN74VJL0VNc2Ck5P
Google colab tutorial:  https://youtu.be/67QvWOp3dkU?si=YKaOYJ9x01eG4iQG

I would like the PiperTTS extension to be similar to the XTTSv2 menu.

### Additional context

![Screenshot 2024-01-07 215431](https://github.com/SillyTavern/SillyTavern/assets/129459206/91e421af-2bca-42f5-804c-7837526611fd)

Having an extension with the same options as XTTSv2. would be Nice, ^^

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
Duplicate #1489
