### ISSUE TITLE
[BUG] <XTTS not showing fine tuned models in the available speaker list>

### ISSUE THREAD

**Issue by GamingDaveUk** [SillyTavern/SillyTavern#1657]
### Environment

Self-Hosted (Bare Metal)

### System

windows 10

### Version

SillyTavern 1.11.1 'release' (7104daf7)

### Desktop Information

Windows 11
Xtts updated (cant find a version number but its 100% the version that supports finetuned models as before I updated it the launcher crashed with unknown command for selecting the model folder (which now its updated...it does not)

### Describe the problem

Launching the XTTS server with:
```
cd xtts
call venv\Scripts\activate
python -m xtts_api_server -mf C:\NewAI\SillyTavern\SillyTavern\xtts\models -sf C:\NewAI\SillyTavern\SillyTavern\xtts\speakers2 --streaming-mode-improve --deepspeed --stream-play-sync
```
and to test i have one wav file in the speakers2 folder and one fine tuned model in the models folder.
I can only see the wav file in speaker2 folder, not the fine tuned model.

Not sure if its a bug with silly tavern or if its simply that the ability to use fine tuned models is so new?

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by daswer123** [comment]
I'll duplicate my answer here

> Hi at the moment, you can't switch xtts model via SillyTaven. 
> Currently, to use a custom model you need to add the flag `-v {MODEL NAME}` where MODEL NAME is the folder name in the folder where the models are located.
> 
> I also prepared some endpoints in a recent update, maybe later they can be added to SillyTavern. 
> GET `http://127.0.0.1:8020/get_models_list` - gets a list of all available models
> POST `http://127.0.0.1:8020/switch_model` - switches to the model we pass in

**Comment by GamingDaveUk** [comment]
Hopefully Silly Tavern will add those endpoints, fine tuned models come out really well.
