### ISSUE TITLE
[Feature Request] Send messages as the System.

### ISSUE THREAD

**Issue by Chanka0** [SillyTavern/SillyTavern#166]
**Is your feature request related to a problem? Please describe.**
There's no way to send messages as the system role besides manipulating the Author's Note.

**Describe the solution you'd like**
Add a toggleable option to send messages as the system role. This would allow for easier manipulation and event interjection within the chat by disassociating it from the user role. The toggle would be located in the options tab left of the text box. These messages would persist within the chat, being displayed in the logs with the username 'System'.

**Describe alternatives you've considered**
As mentioned, the current workaround is to micromanage the Author's Note.

**Additional context**
The send button's quill icon should be changed to something else (a robot would be most befitting) to indicate that the feature has been toggled on.

**Comment by StefanDanielSchwarz** [comment]
I thought that's what "{{text}}" does. Help text says "set the behavioral bias for the AI character", but I though that means just sending a system message.

If I'm mistaken, a simple way to send text as system would be useful. Usually I just use square brackets in my messages to indicate "stage directions", which the AI usually accepts.

**Comment by Chanka0** [comment]
That does work but it's dirty. The only time that text/messages are accepted as system messages are ones with `role: system` in the logs (check the terminal after you send a message, you'll see what I mean). Right now the author's note and the initial prompt are the only `system` messages, everything else uses the `user` and `assistant` roles.

**Comment by RossAscends** [comment]
worth noting that system, user, assistant are API-specific tags. I believe for KoboldAI, not certain though. Other APIs could use different tags, or ignore them completely.

**Comment by Chanka0** [comment]
Not sure about Kobold but OpenAI uses this for their ChatCompletion
endpoint.

**Comment by cass02** [comment]
If a feature is included, I would super recommend leaving it up to the user. Each model requires something differently. Different tags or formatting do different things. Something as simple as:
/sys` [ Scene: A dragon appears! ]` is infinitely better than
`System: [ Scene: A dragon appears! ]` as this would be sub-par for many models and uses.

**Comment by kakhulu31** [comment]
>Just letting you know, you can try this out in dev branch already

You mean instruct mode? So it's not for openai models?

**Comment by Chanka0** [comment]
> > Just letting you know, you can try this out in dev branch already
> 
> You mean instruct mode? So it's not for openai models?

It's `/sys`. Currently it's still on the dev branch

**Comment by alicat22** [comment]
@Chanka0 Do you believe this should still be open or should this be closed now? The devs leave closing up to the individuals after requests are completed. Or do you believe it's missing something?

**Comment by Chanka0** [comment]
> @Chanka0 Do you believe this should still be open or should this be closed now? The devs leave closing up to the individuals after requests are completed. Or do you believe it's missing something?
It's good as is. Closing the request now.
