### ISSUE TITLE
[FEATURE_REQUEST] Add Support for Dynamic Temperature

### ISSUE THREAD

**Issue by sophosympatheia** [SillyTavern/SillyTavern#1661]
### Have you searched for similar requests?

Yes

### Describe the solution you'd like

Textgen Webui just added the Dynamic Temperature feature and a dynamic_temperature_low sampler setting associated with it to their HF loaders. This feature request is for adding support for these new sampler settings to SillyTavern.

### Additional context

See https://github.com/oobabooga/text-generation-webui/commit/48327cc5c4dbc76a8c8dc795acd3dcf72f6d2896
and
https://github.com/oobabooga/text-generation-webui/commit/0d07b3a6a1e35e1da18f14949c757ac47c84f39c

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

None

**Comment by jackie1218** [comment]
#1666

**Comment by Cohee1207** [comment]
Merged.
