### ISSUE TITLE
[BUG] "Disable Send" Setting not saving in Quick Reply preset through the UI

### ISSUE THREAD

**Issue by As4shi** [SillyTavern/SillyTavern#1662]
### Environment

Self-Hosted (Bare Metal)

### System

Chrome 120

### Version

 1.11.1 'release' (7104daf7)

### Desktop Information

Node v19.3.0

### Describe the problem

When using the "Update" button the setting "Disable Send / Insert In User Input" (quickActionEnabled) doesn't save. It works fine if using the slash command with the nosend arg (/qr-presetupdate nosend=true <preset_name>).

Additionally, if a preset doesn't have the quickActionEnabled parameter defined it will not disable immediately, but once you reload the page after changing the preset it will be turned off.

It should either keep the existing setting if the quickActionEnabled is not defined in the preset or always save it to the preset.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Thanks for reporting, but I won't be addressing this issue since the staging branch has a QR extension completely rewritten. If you have the ability to switch branches, please check it there and report back.
