### ISSUE TITLE
[BUG] when i input the api url and click connect nothing happens

### ISSUE THREAD

**Issue by Eddieddg** [SillyTavern/SillyTavern#1665]
### Environment

Self-Hosted (Bare Metal)

### System

Windows 10pro

### Version

1.5.2

### Desktop Information

Generation api oobabooga
Model Wizard-Vicuna-13B-Uncensored.Q4_K_M.gguf

### Describe the problem

In oobabooga i start api mode i copy the api url and paste it in sillytavern settings on right side and click connect and nothing happens in either webui nor either cmd/powershell no output nothing.
![image_2024-01-08_201533436](https://github.com/SillyTavern/SillyTavern/assets/110125354/72e1a495-3005-45f4-94c0-f678d636291a)
![image_2024-01-08_201613513](https://github.com/SillyTavern/SillyTavern/assets/110125354/cc678f1c-775c-4394-aa74-4347ed7a9c40)
![image](https://github.com/SillyTavern/SillyTavern/assets/110125354/126439d1-9ba7-45c4-98d9-919eb945e943)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Not our program.
https://github.com/TavernAI/TavernAI/issues

**Comment by Eddieddg** [comment]
shit did i accidentally download tavern-ai

**Comment by Eddieddg** [comment]
i downloaded sillytavern and it worked instatly thanks
