### ISSUE TITLE
[FEATURE_REQUEST] LLM determine the next character to speak

### ISSUE THREAD

**Issue by MilesQLi** [SillyTavern/SillyTavern#1670]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

No.

### Describe the solution you'd like

In a group conversation scenario, it is better to ask the LLM which character to speak rather than randomly based on the character’s feature. The latter may lead to some strange storyline.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

None

**Comment by Katehuuh** [comment]
Name first character you want to speak.

**Comment by MilesQLi** [comment]
@Katehuuh Sometimes, an AI character’s speech should be followed by a specific AI character. I am not in the position to name.
