### ISSUE TITLE
[FEATURE_REQUEST] Allow the disabling of samplers.

### ISSUE THREAD

**Issue by SabinStargem** [SillyTavern/SillyTavern#1674]
### Have you searched for similar requests?

None

### Is your feature request related to a problem? If so, please describe.

Kalomaze recommends only certain sampler settings to be used with their Dynatemp feature.  Most aspects of sampling have to be turned off.   Problem is, it isn't clear what is 'off' for every preset setting.  Some have to be set at their lowest level, others at the highest, and not all have tooltips.    This can result in confusion.

### Describe the solution you'd like

I think having a checkbox by each setting in the preset panel would be ideal.   When checked, the setting is enabled.  While unchecked, the setting is darkened and ST will make it disabled or closest to being neutral.

This should allow for users to tweak their presets or to experiment more effectively.  We do not know what requirements future sampler implementations should have, so universally turning off everything during DynaTemp mode might not be ideal.

### Describe alternatives you've considered

Adding an extra option to the DynaTemp section where it disables all features that Kalomaze wants to be disabled would be good.  That would be ideal for people who do not want to experiment.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

None

**Comment by kalomaze** [comment]
I have [a PR up](https://github.com/SillyTavern/SillyTavern/pull/1677) that has a single button to disable the extraneous samplers that most people don't use.

https://github.com/SillyTavern/SillyTavern/assets/66376113/dce62fe9-e5a8-4d26-a65c-a9f728e3a950

**Comment by frammiie** [comment]
@kalomaze 
Ahh this is nice, but it would be great if we could just collapse any samplers entirely.

**Comment by Cohee1207** [comment]
The disable samplers button was implemented several releases ago.
