### ISSUE TITLE
pkg has been deprecated and archived

### ISSUE THREAD

**Issue by valadaptive** [SillyTavern/SillyTavern#1681]
ST currently uses `pkg` to build single-executable packages. Unfortunately, `pkg` was suddenly [deprecated and archived without warning](https://github.com/vercel/pkg) last week.

Somewhat frustratingly, they direct people to "forked versions of pkg" without listing any in particular, or [Node's single-executable application support](https://nodejs.org/api/single-executable-applications.html) which is still experimental and subject to breaking changes.

I can only find a few real alternatives:
- [nexe](https://github.com/nexe/nexe), which appears to be only barely maintained
- [boxednode](https://github.com/mongodb-js/boxednode), which compiles Node.js from source
- [Node's aforementioned experimental single-executable application support](https://nodejs.org/api/single-executable-applications.html)

I find it extremely frustrating that `pkg` outcompeted all alternative solutions and then was abruptly discontinued with no clear path forward, but I'm not sure what to do about it right now. Maybe in the following weeks/months, a better solution will emerge?

**Comment by Cohee1207** [comment]
I'm not sure anyone is using the pkg-packaged version, this is not very convenient at all since it requires having all the frontend files, it only saves from installing node runtime. In my opinion, if there is no viable alternative, pkg packaging could be safely removed.

**Comment by Cohee1207** [comment]
Now when someone dropped a vulnerability advisory, it is no longer viable to have around.

https://github.com/advisories/GHSA-22r3-9w55-cj54
