### ISSUE TITLE
[BUG] Continue the last message function seems to work incorrectly

### ISSUE THREAD

**Issue by Hanter9901** [SillyTavern/SillyTavern#1682]
### Environment

Self-Hosted (Bare Metal)

### System

Windows 10

### Version

1.11.2 'staging' (911428f5)

### Desktop Information

- Node version: v18.16.1
- API: OpenAPI with Venus Chub
- Branch: staging
- Model: Venus Mars

### Describe the problem

When I try to get SillyTavern to continue last response it seems like it appends new generation to said response which causes it to impersonate user.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Try the "Continue prefill" option. OpenAI API simply doesn't have a built-in option to continue from the previous generation, all of the available methods are workarounds and assumptions. Some may work, and some may not. Especially for non-OAI models that get their prompts converted by the unknown backend.

**Comment by Hanter9901** [comment]
Thanks. seems to work a bit better.
