### ISSUE TITLE
[General Questions] lorebook keywords only support english?

### ISSUE THREAD

**Issue by darcula1993** [SillyTavern/SillyTavern#1685]
It looks like we can only use English as keywords of lorebook?

**Comment by Cohee1207** [comment]
You can use anything, it's just a string match

**Comment by darcula1993** [comment]
> You can use anything, it's just a string match

It should be.But I try several times,it only works for english words.No other language words or numbers can trigger world infos. Any idea?

**Comment by darcula1993** [comment]
OK numbers can be a key,but not chinese,japanese or any other languages. Does sillytavern use utf-8 encodings?

**Comment by Cohee1207** [comment]
WI files are written as utf-8 and matched using whatever is the default encoding of JavaScript strings (assume it's utf-16).

**Comment by darcula1993** [comment]
@Cohee1207 That is weird. Are you able to reproduce this problem?

**Comment by darcula1993** [comment]
OK I think I found the problem. @Cohee1207 
The function `matchKeys` construct regexp as:
```const regex = new RegExp(`\\b${escapeRegex(transformedString)}\\b`);```
But word boundary `\b` is not applicable to non-Latin alphabets.

**Comment by Cohee1207** [comment]
Disable "match whole words" WI activation setting, it won't be used

**Comment by darcula1993** [comment]
great! it works! Thx!
