### ISSUE TITLE
[BUG] Error rendering template

### ISSUE THREAD

**Issue by RandomUser1017** [SillyTavern/SillyTavern#1686]
### Environment

Self-Hosted (Bare Metal)

### System

Chrome 120

### Version

1.11.1

### Describe the problem

It keeps showing rendering template error bubbles.
![image](https://github.com/SillyTavern/SillyTavern/assets/138387006/ef856e92-1037-436d-be72-be23402abaaf)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Hi there, I'm actively trying to reproduce or find the reason why it is happening for some users, but no luck so far. Could you provide more information? For example, what extensions do you use, and what methods of access ST instance (local, network, etc)?

**Comment by artisticMink** [comment]
@RandomUser1017 

Please provide additional information, thanks:
* The way of which you access ST (desktop/mobile/device)
* Enabled browser extensions, if any.

**Comment by Zerugen** [comment]
I don't know if this helps, but my dev console says this multiple times over: script.js:577 Error rendering template scripts/extensions/expressions/list-item.html Object Error: Error loading scripts/extensions/expressions/list-item.html: 0 
    at getUrlSync (script.js:551:11)
    at renderTemplate (script.js:561:37)
    at renderExtensionTemplate (extensions.js:61:12)
    at getListItem (index.js:989:12)
    at index.js:974:37
    at Array.forEach (<anonymous>)
    at drawSpritesList (index.js:965:19)
    at validateImages (index.js:949:28)
    at async ModuleWorkerWrapper.moduleWorker [as callback] (index.js:534:9)
    at async ModuleWorkerWrapper.update (extensions.js:81:13)
I run ST locally on windows 10 using google chrome. Sorry if I messed up in any way.

**Comment by Cohee1207** [comment]
There are reports that this is due to antivirus browser extension. Please try disabling them. @Zerugen

**Comment by Zerugen** [comment]
Thank you, that seems to have fixed the issue.

**Comment by blueswolf** [comment]
the bug still there on iphone 15 .I 'm in china,MY ST(1.11.6) running on vps in USA, I access  it from my phone with safari and chrome，Error rendering template……BUT when i run ST server on my own PC,and  use an intranet penetration software(on PC) to help my mobile phone access the ST server, I can avoid this problem. Is it a problem caused by long distance communication?or someting about network?
