### ISSUE TITLE
error, spawn unknown

### ISSUE THREAD

**Issue by Elextrofaaxz** [SillyTavern/SillyTavern#1691]
![Captura de pantalla 2024-01-14 000017](https://github.com/SillyTavern/SillyTavern/assets/140289797/39ac3c34-21e3-4816-b190-e94adcbfdb72)
I don´t really know how to solve this problem right here but please, can you help me please?

**Comment by Cohee1207** [comment]
Open config.yaml, change from autorun: true to autorun: false. Save and restart. Then use the URL in console to open.

**Comment by Elextrofaaxz** [comment]
wow, thank you!
