### ISSUE TITLE
[FEATURE_REQUEST] Mixtral Instruct 8x7b (and upcoming top models) presets to be included and loaded by default when connected to it, (fast after new model release) in official ST (hotfix) releases.

### ISSUE THREAD

**Issue by Mintberry1** [SillyTavern/SillyTavern#1692]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Mixtral Instruct 8x7b is now used by many roleplayers because it offers 32k context instead of 4k.
Finetunes of Mixtral until now all have the router/gate problem not performing as good as Mixtral Instruct.
Many users on locallama have bad experiences because Mixtral Instruct is very specific about it's Instruct format structure in particular, and i think most of the disappointed users have bad or not the right presets.
The community is experimenting too with different presets and system prompts to better prevent Mixtral from repeating.
There are currently finetunes like noromaid mixtral where the model builders included three presets:
One for general Text generation (important because of penalty settings, min p and such...) , 1x for Context, 1x for Instruct.
For now there are also some sites from people on rentry and such with different Mixtral settings, creating a confusing chaos of options if the person using Mixtral finds them at all.

### Describe the solution you'd like

Mixtral Instruct 8x7b presets to be included and loaded by default when connected to a backend which uses it, in an official ST release.
Even if the Mixtral presets are not perfect, they could be changed in the next version.
Just call it preset set 1.00 and versionize it when changes are made.
Creating official standards (for specific LLM models which are widely used) in the settings will be crucial for better mass adoption of LLM roleplaying and will help newcomers have a better experience and help in the debugging as well.
Because by default certain presets would be used it will cause less frustrated users, and a bigger base of testers which then would contribute, test, benchmark, experiment and help/suggest to make small fixes like for example v.1.1 of the Mixtral Instructs presets shipping in the next ST release.
As long as there are no official default standards in settings  (specific to models) you have a wild west situation, which obliterates community efforts, everyone doing their own thing not knowing what the others do and what their settings are.

### Describe alternatives you've considered

The default model presets for ST could be included in gguf  and exl2.
Less likely by companies like Mistral though.

### Additional context

I set it here on Priority high, because currently without getting Mixtral presets for ST from somewhere, Mixtral will be very bad, you could say broken, which in my humble opinion is preventing the current roleplaying topmodel (for now Mixtral) to be adopted by the community. If you look at koboldcpp and llamacpp they almost immediately released new versions and fixes for Mixtral to be used. But unfortunately Silly Tavern is lagging and i don't even know if the developers are aware of this situation. If they were, i would suppose they would have introduced a "hot fix" release, as fast as possible after Mixtral came out, with included Mixtral presets and settings. And please don't misunderstand we have "Mistral" settings, but those are a different thing than Mixtral.

I hope that we get those Mixtral settings in the next release included and that in the future when models like the upcoming llama3 for example comes out, that ST will support them with official preloaded settings in a new hotfix release relatively soon after the new model releases.

### Priority

High (The app does not function without it)

### Is this something you would be keen to implement?

No

**Comment by Cohee1207** [comment]
What am I supposed to do here?

**Comment by Mintberry1** [comment]
![image](https://github.com/SillyTavern/SillyTavern/assets/16798881/90c647ff-fb43-4818-89c7-210ebb6c2e2c)
![image](https://github.com/SillyTavern/SillyTavern/assets/16798881/3d584101-79f6-4230-8177-8626bc72bae8)

My three files that i use for now for Mixtral, just to illustrate what i mean (they can be imported in ST and should show as):
"Mixtral Instruct 8x7b" in "Text Completion", "Instruct" and "Context" category.
[MixtralInstructAdvancedFormattingInstructModePreset.json](https://github.com/SillyTavern/SillyTavern/files/13931996/MixtralInstructAdvancedFormattingInstructModePreset.json)
[MixtralInstructAdvancedFormattingContextPreset.json](https://github.com/SillyTavern/SillyTavern/files/13931997/MixtralInstructAdvancedFormattingContextPreset.json)
[MixtralInstructTextCompletionPreset.json](https://github.com/SillyTavern/SillyTavern/files/13932015/MixtralInstructTextCompletionPreset.json)


I tested those three settings from many different places (they are partly from the Noromaid Mixtral Finetune though) and i don't claim they are the best or even right settings. I have problem often with 10k-16k context that Mixtral keeps repeating itself, although that seems to be a specific Mixtral problem.

I read that some people claimed, that they got better results with different settings about the repetition problem.

**Comment by Mintberry1** [comment]
New features like the "Dynamic Context" added in latest koboldcpp will find it's way to ST sooner than later too, implying that default Presets would have to be updated. (versionized).

The same goes for llama3, it will most probably have higher context for example 16k-32k to compete with Mixtral or even higher, so at least that would have to be changed of course if a default preset would be implemented.

My suggestion is that at least you provide as fast as possible those presets in a hotfix release when something like Mixtral (new top roleplaying contender model releases. The presets don't have to be optimal but they are at least a foundational standardized base to build and finetune/experiment on.)

Mixtral released on 11.12.2023 and as i mentioned koboldcpp and everyone else tried their best in short time to support it, but unfortunately ST until today (more than 1 month) has no release with default presets for it.

Many roleplayers use it because some char cards have already 2-3k context tokens leaving only 1k for context and Mixtral (and finetunes if the gate/router problem is solved) having 32k will soon be the defacto standard model for rp.

Official Name of the model should be used:
"Mixtral-8x7B-Instruct-v0.1-Preset-v1.0"

**Comment by Cohee1207** [comment]
Submit these files using a pull request feature

**Comment by Mintberry1** [comment]
i tried but it says i am no collaborator 
"Pull request creation failed. Validation failed: must be a collaborator."
I have not much Github experience.

Git Pull Title:
Mixtral-8x7B-Instruct-v0.1-Presets-v1.0

Git Pull Description:
According to Cohee1207 i am making my first commit.

[#1692](https://github.com/SillyTavern/SillyTavern/issues/1692)

Three presets to be included in Silly Tavern for Mixtral-8x7B-Instruct-v0.1:

[Mixtral-8x7B-Instruct-v0.1-Preset-v1.0-Instruct-Mode.json](https://github.com/SillyTavern/SillyTavern/files/13932281/Mixtral-8x7B-Instruct-v0.1-Preset-v1.0-Instruct-Mode.json)
[Mixtral-8x7B-Instruct-v0.1-Preset-v1.0-Context-Template.json](https://github.com/SillyTavern/SillyTavern/files/13932282/Mixtral-8x7B-Instruct-v0.1-Preset-v1.0-Context-Template.json)
[Mixtral-8x7B-Instruct-v0.1-Preset-v1.0-Text-Completion.json](https://github.com/SillyTavern/SillyTavern/files/13932283/Mixtral-8x7B-Instruct-v0.1-Preset-v1.0-Text-Completion.json)

**Comment by Mintberry1** [comment]
i tried "https://medium.com/nebula-graph/how-to-be-a-github-contributor-in-five-minutes-72175c036c17"
According to the guide i came to (trying pushing my commit to Staging):
git push -f origin Mixtral-8x7B-Instruct-v0.1-Presets-v1.0
and got
" remote: Permission to SillyTavern/SillyTavern.git denied to Mintberry1.
fatal: unable to access 'https://github.com/SillyTavern/SillyTavern.git/': The requested URL returned error: 403"

I am total Git and Github noob i must say. 

SillyTavern\public\TextGen Settings i saw there are .settings files with git clone and my file is an exported .json. Probably not okay but i don't know how to make a .settings file out of the .json.

Probably would be easiest if someone experienced could make a commit and push it.

**Comment by Cohee1207** [comment]
You don't need to do it. .settings are deprecated and eventually going to be deleted. New files go to /default/content/presets/textgen and added to /default/index.json

**Comment by Mintberry1** [comment]
i added the Mixtral-8x7B-Instruct-v0.1-Preset-v1.0-Text-Completion.json to

/default/content/presets/textgen and edited into /default/index.json

i suppose the other two go to public\instruct and public\context

when using "git add Mixtral-8x7B-Instruct-v0.1-Preset-v1.0-Context-Template.json" it says
"The following paths are ignored by one of your .gitignore files:
public/context
hint: Use -f if you really want to add them.
hint: Turn this message off by running
hint: "git config advice.addIgnoredFile false""

i suppose i should make it git add Mixtral-8x7B-Instruct-v0.1-Preset-v1.0-Context-Template.json -f

**Comment by Cohee1207** [comment]
Yes, `git add -f` 
Also make sure the name of the file and the name inside of JSON match.

**Comment by Mintberry1** [comment]
i git added the files, then entered:
git commit -m 'Mixtral-8x7B-Instruct-v0.1-Presets-v1.0'
Console Output:
[Mixtral-8x7B-Instruct-v0.1-Presets-v1.0 5a31221a] 'Mixtral-8x7B-Instruct-v0.1-Presets-v1.0'
 4 files changed, 84 insertions(+)
 create mode 100644 default/content/presets/textgen/Mixtral-8x7B-Instruct-v0.1-Preset-v1.0-Text-Completion.json
 create mode 100644 public/context/Mixtral-8x7B-Instruct-v0.1-Preset-v1.0-Context-Template.json
 create mode 100644 public/instruct/Mixtral-8x7B-Instruct-v0.1-Preset-v1.0-Instruct-Mode.json

then: (for your information, i cloned sillyTavern Staging at the beginning, i thought that was the right choice)
git push -f origin Mixtral-8x7B-Instruct-v0.1-Presets-v1.0
and then i get:
Console output:
info: please complete authentication in your browser...
remote: Permission to SillyTavern/SillyTavern.git denied to Mintberry1.
fatal: unable to access 'https://github.com/SillyTavern/SillyTavern.git/': The requested URL returned error: 403

Firefox popup "sign in with your browser"--> Authentication Succeeded - You may now close this tab and return to the application.

Anyhow i get 403 error "probably for forbidden afaik".

**Comment by Cohee1207** [comment]
You can't push directly to the repo, you need to make a fork first.

**Comment by Mintberry1** [comment]
Thank you Cohee1207 for your patience!
I added the git pull request, i hope everything is okay, since this being my first git pull request.
If everything is okay will it probably be merged and included in the next release? Any timeframe?
(Hopeful for 1.11.2 Hotfix (^_^) so the community can start to use the presets as fast as possible)

**Comment by XZVB12** [comment]
@Mintberry1 As far as I understand, the context length is incorrectly. At least koboldcpp thinks that 32768 should be specified instead of 31744. 
Correct me if I'm wrong.
