### ISSUE TITLE
[BUG] {{ Hidden Messages }} are now visible?

### ISSUE THREAD

**Issue by imesha10** [SillyTavern/SillyTavern#1697]
### Environment

Self-Hosted (Bare Metal)

### System

Windows 11, Chrome

### Version

SillyTavern 1.11.2 'staging' (e9a7be54)

### Desktop Information

Node JS: v18.15.0
Generation: OpenAI reverse proxy
Branch: Staging
Model: any gpt version

### Describe the problem

The latest `git pull` I've done seems to have changed the behaviour for the messages contained within {{ }}.

It used to be that anything that would be inside those two curly brackets would be hidden automatically and not sent to the ai, however the latest update seems to have changed that behaviour.
![image](https://github.com/SillyTavern/SillyTavern/assets/16441743/11ae7e63-468e-4f18-be01-d3c2f00b9b6c)

Possible Solution:
Add a option in the settings menu to allow this functionality to continue to exist.
Maybe here:
![image](https://github.com/SillyTavern/SillyTavern/assets/16441743/3df03d64-0474-445b-9a33-f54b297a835d)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
This is expected as there are legit use cases for double curlies that are not valid macros to appear in the output.
Use proper comment syntax to hide text from messages 
`{{// comment}}`

**Comment by imesha10** [comment]
Ok I'll figure out a way around this.
