### ISSUE TITLE
[BUG] basic auth re-prompted repeatedly on Chrome

### ISSUE THREAD

**Issue by xifer** [SillyTavern/SillyTavern#1712]
### Environment

Self-Hosted (Bare Metal)

### System

Chrome 120.0.6099.225 on Windows 10 64-bit

### Version

1.11.2

### Describe the problem

I re-use a subdomain in nginx via proxies for xtts and sillytavern-extras endpoints.
https://sillytavern.example.com (proxied to sillytavern)
https://sillytavern.example.com/tts/ (proxied to xtts_api_server)
https://sillytavern.example.com/extras/ (proxied to sillytavern-extras)

When loading the frontend in Chrome (and Edge, but not Firefox), function calls to [doExtrasFetch](https://github.com/SillyTavern/SillyTavern/blob/e3ccaf70a10b862113f9bad8ae039fc7ce6570df/public/scripts/extensions.js#L158) (in [/public/scripts/extension.js](https://github.com/SillyTavern/SillyTavern/blob/e3ccaf70a10b862113f9bad8ae039fc7ce6570df/public/scripts/extensions.js)) with the xtts or extras endpoints set an auth bearer header which seems to cause the browser to request basic auth again repeatedly (I assume one for each request from doExtrasFetch).  Somehow Chrome "forgets" it's previous authorization when it encounters the auth bearer header while Firefox seems to have no problems with it.

https://github.com/SillyTavern/SillyTavern/blob/e3ccaf70a10b862113f9bad8ae039fc7ce6570df/public/scripts/extensions.js#L171

Commenting that out or changing it to:
```
if(extension_settings.apiKey) {
    Object.assign(args.headers, {
        'Authorization': `Bearer ${extension_settings.apiKey}`,
    });
}
```
Solved the problem for me since I don't use an apiKey with sillytavern-extras... But for users who do, perhaps additionally xtts.js should not use doExtrasFetch especially since xtts is not a part of sillytavern-extras anyways?

This might be more about working around a Chrome bug, but I think the two fixes above sound reasonable?

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
> Solved the problem for me since I don't use an apiKey with sillytavern-extras... But for users who do, perhaps additionally xtts.js should not use doExtrasFetch especially since xtts is not a part of sillytavern-extras anyways?

However, it won't solve it for those who use an API key with Extras since it will still override an Authentication header. Since your hosting method is rather unusual, I don't think it poses problems for other users.

**Comment by xifer** [comment]
Thanks for making that change.  And yes, if I'm following you, xtts.js would need to use it's own fetch function instead of doExtrasFetch if an API key is set.  This doesn't seem like a bad thing to me because [xtts_api_server](https://github.com/daswer123/xtts-api-server) is not an Extras module and probably shouldn't be using the Extra's fetch function.

**Comment by libid0nes** [comment]
For me this is the same even in firefox, I'm using 11.6
