### ISSUE TITLE
[BUG] <title> not really a bug report, just something that I'm not sure is feature 

### ISSUE THREAD

**Issue by Naba51** [SillyTavern/SillyTavern#1715]
### Environment

Self-Hosted (Bare Metal)

### System

Android

### Version

Latest

### Describe the problem

When downloading chub bots, the custom imbedded lore book that comes with the bot don't show up in sillytavern, I want to know if its possible to somehow install those, because I don't really wanna have to manually copy paste them, some of them are huge

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Download v2 cards. v1 don't have lorebook embeds.
