### ISSUE TITLE
[BUG] Search in manage chat files fails to open chats

### ISSUE THREAD

**Issue by Technologicat** [SillyTavern/SillyTavern#1718]
### Environment

Self-Hosted (Bare Metal)

### System

Firefox 121.0

### Version

1.11.2 'staging' (e9a7be54)

### Desktop Information

Node.js: v20.10.0
API: oobabooga (self-hosted / bare metal), with the OAI compatible endpoints
Branch: `staging`
Model: [dolphin-2.6-mistral-7b-dpo-laser.Q5_K_M.gguf](https://huggingface.co/TheBloke/dolphin-2.6-mistral-7B-dpo-laser-GGUF)

### Describe the problem

**Steps to reproduce**:

- Click on the "≡" menu ⊳ Manage chat files ⊳ Search...
- Type in some search term
- Click on a chat in the search results to open it

**Expected result**:

The clicked chat opens.

**Actual result**:

Either no chat opens, or the wrong (usually the latest) chat opens.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Done.

**Comment by Technologicat** [comment]
Confirmed working. Fastest bug fixing ever!
