### ISSUE TITLE
[BUG] Render formulas shows both rendered and plaintext formula

### ISSUE THREAD

**Issue by Technologicat** [SillyTavern/SillyTavern#1719]
### Environment

Self-Hosted (Bare Metal)

### System

Firefox 121.0, Linux Mint 21.1

### Version

1.11.2 'staging' (e9a7be5)

### Desktop Information

Node.js: v20.10.0
API: oobabooga (self-hosted / bare metal), with the OAI compatible endpoints
Branch: staging
Model: [dolphin-2.6-mistral-7b-dpo-laser.Q5_K_M.gguf](https://huggingface.co/TheBloke/dolphin-2.6-mistral-7B-dpo-laser-GGUF)

### Describe the problem

**Steps to reproduce**

- Type e.g. this LaTeX into the chat: $$ \int \sin(x) \, \mathrm{d}x = -\cos(x) $$
- Send the message to the AI

**Expected result**

Only the rendered formula is shown, unless the message is in edit mode.

**Actual result**

Both the rendered formula and its plaintext are shown next to each other. The plaintext seems to appear twice.

### Additional info

Rendered:

![image](https://github.com/SillyTavern/SillyTavern/assets/16972251/c72570d3-5106-4f10-9515-813f1bcad41c)

Message edit mode works correctly. Here's what I actually typed:

![image](https://github.com/SillyTavern/SillyTavern/assets/16972251/e0fc4de6-6a1b-4985-8f41-b80c36b19253)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Done.

**Comment by Technologicat** [comment]
Tested (b2509f8d).

Although no longer three, it's still rendering **two** copies of the formula - the rendered LaTeX, and the LaTeX source code:

![image](https://github.com/SillyTavern/SillyTavern/assets/16972251/1e96cdd6-6cda-495a-80a6-a54fd8c1a179)

Also, in this revision, now trying to edit the message (by clicking the pencil icon) clears the whole input:

![image](https://github.com/SillyTavern/SillyTavern/assets/16972251/c00ef979-387e-4d60-b7a2-d7407e185cb3)

**Comment by Cohee1207** [comment]
Firefox is so goofy.

**Comment by Technologicat** [comment]
Well, as we all know:

*[In the browser], the theoretically simple becomes a legacy-driven quirk-hole.*
  --Jake Archibald

Confirmed working (same revision, https://github.com/SillyTavern/SillyTavern/commit/b2509f8de475eb8b907e57c5fea2248a5aa419e4) in Chromium, Version 120.0.6099.109 (Official Build) for Linux Mint (64-bit).

Render:

![image](https://github.com/SillyTavern/SillyTavern/assets/16972251/76c906db-a84d-46d1-a17c-7ccd6b2d7f5b)

Edit mode, after clicking on pencil:

![image](https://github.com/SillyTavern/SillyTavern/assets/16972251/f20018fa-305c-4417-a620-eca490aa258f)
