### ISSUE TITLE
[BUG] ElevenLabs TTS fails on custom voice

### ISSUE THREAD

**Issue by sinoth** [SillyTavern/SillyTavern#172]
**Describe the bug**
Using a custom cloned voice from ElevenLabs fails the voice map check with "Voice map is invalid, check console for errors"

**To Reproduce**
1. Write a valid custom voice into the voice map (appears in the Available Voices menu)
2. Click apply
3. "Voice map is invalid, check console for errors"

If I short circuit the logic at 
https://github.com/Cohee1207/SillyTavern/blob/dev/public/scripts/extensions/tts/index.js#L330
to just read `if (true)`, the voice loads and generates successfully. This is a bug in the `voicemapIsValid` function.

**Comment by IcoSpawn** [comment]
> **Describe the bug** Using a custom cloned voice from ElevenLabs fails the voice map check with "Voice map is invalid, check console for errors"
> 
> **To Reproduce**
> 
> 1. Write a valid custom voice into the voice map (appears in the Available Voices menu)
> 2. Click apply
> 3. "Voice map is invalid, check console for errors"
> 
> If I short circuit the logic at https://github.com/Cohee1207/SillyTavern/blob/dev/public/scripts/extensions/tts/index.js#L330 to just read `if (true)`, the voice loads and generates successfully. This is a bug in the `voicemapIsValid` function.

wait you are able to get elevenlabs to work with this???

**Comment by Chanka0** [comment]
> > **Describe the bug** Using a custom cloned voice from ElevenLabs fails the voice map check with "Voice map is invalid, check console for errors"
> > **To Reproduce**
> > 
> > 1. Write a valid custom voice into the voice map (appears in the Available Voices menu)
> > 2. Click apply
> > 3. "Voice map is invalid, check console for errors"
> > 
> > If I short circuit the logic at https://github.com/Cohee1207/SillyTavern/blob/dev/public/scripts/extensions/tts/index.js#L330 to just read `if (true)`, the voice loads and generates successfully. This is a bug in the `voicemapIsValid` function.
> 
> wait you are able to get elevenlabs to work with this???

It's part of the dev branch.
