### ISSUE TITLE
[FEATURE_REQUEST] Lorebooks: Move Activation Settings to individual Entries

### ISSUE THREAD

**Issue by AnonCardMaker** [SillyTavern/SillyTavern#1727]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Activation Settings being global hampers the versatility of Lorebooks, as well as creating problems when it comes to distribution (Having to tell users to mess around with their Lorebooks settings). Scan Depth being the big one.

### Describe the solution you'd like

Move Scan Depth, Case-Sensitive and Match Whole words, from the Activation Settings submenu to each individual Entry of each individual Lorebooks.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
Scan Depth is impossible to move to an entry level without completely rethinking the way of processing the text and recursion. Right now all chat messages up to a scan depth are joint into a single buffer that is used for all matching operations. How is it supposed to work when the recursed entries are added to the buffer? Just ignore it / treat it as zero?

**Comment by anonCantCode** [comment]
I would ask to still have global activation settings for compatibility with old lorebooks designed for it. (Can't check the PR code right now but 'override' implies that's what's being done, in which case great 👌)

**Comment by Cohee1207** [comment]
You're right, global settings will still be available if unset on a WI entry level.

**Comment by AnonCardMaker** [comment]
Thanks, it works great.
