### ISSUE TITLE
[BUG] /rand returns null instead of zero

### ISSUE THREAD

**Issue by creamsan** [SillyTavern/SillyTavern#1728]
### Environment

Android (Termux)

### System

iceraven-2.14.2

### Version

SillyTavern 1.11.3 'staging' (958cf6a3)

### Describe the problem

/rand returns null instead of zero

### Additional info

Here's a simple func
![Screenshot_20240123-065317_1](https://github.com/SillyTavern/SillyTavern/assets/141376415/19dde455-828d-4aeb-ae57-282093bc2d30)
I looped it 50 times
![Screenshot_20240123-060444_1](https://github.com/SillyTavern/SillyTavern/assets/141376415/0bc7569d-4d83-46ee-b2eb-b92259dbaa80)
Result shows missing values instead of zero
![Screenshot_20240123-065337_1](https://github.com/SillyTavern/SillyTavern/assets/141376415/827f5a34-25c3-43a2-ab6f-061ae796d976)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by creamsan** [comment]
Tried and the zeros still don't show up. I don't think it's a /rand problem anymore, it's the pipe macro.
![Screenshot_20240125-020445_1](https://github.com/SillyTavern/SillyTavern/assets/141376415/ee73f0f8-a5e6-49b1-b61c-dd050533a45f)
![Screenshot_20240125-020500_1](https://github.com/SillyTavern/SillyTavern/assets/141376415/9b6cef28-b1cc-4296-9056-84119b5b586e)

**Comment by Cohee1207** [comment]
I think you're right. Found it.

**Comment by creamsan** [comment]
Just checked. Still no zero.
