### ISSUE TITLE
[BUG] Additional Headers dont apply to /models GET request

### ISSUE THREAD

**Issue by TNT3530** [SillyTavern/SillyTavern#1729]
### Environment

Self-Hosted (Bare Metal)

### System

Ubuntu 22.04

### Version

1.11.2

### Desktop Information

VLLM running OpenAI endpoint
Node v18.17.1

### Describe the problem

The custom OpenAI endpoint requires a specific API key for all requests to authorize the user. This can either be in the header or the body of the request, but it seems the /models query for the connection drop-down refuses to use it (even if the /chat one does successfully)

Both the config.yaml input and the additional parameters drop-down do not work.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
I wasn't able to reproduce. The additional header I entered was passed to the backend okay. Are you sure you're using the correct syntax? Even if only one header, it should be prepended with a hyphen to ensure it is parsed as a YAML object, and not a string.
Example:
```
- Custom-Header: test
```

**Comment by TNT3530** [comment]
Fixing the YAML formatting in the Additional Parameters headers box does work. Im still not getting anything passed from the body or config variants, but since I only need one ill assume its more formatting issues. Thanks
