### ISSUE TITLE
[FEATURE_REQUEST] Clear/Delete Chat History

### ISSUE THREAD

**Issue by GentlemanOfCulture** [SillyTavern/SillyTavern#1730]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Over time, a large number of chatlogs may accumulate. There appears to be no way to clear all chat history with a single click, and manually deleting chatlogs one by one can be time-consuming.

### Describe the solution you'd like

I would like a single button that can be clicked to clear all chat history for a single character or group chat, as well as a single button that can clear all chat history for all characters and groups at the same time.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

No

**Comment by Cohee1207** [comment]
You can always delete the files from the file system using a system file explorer. Bulk deletion in chat management can be considered.

> single button that can clear all chat history for all characters and groups

I don't see any use case for that.

**Comment by GentlemanOfCulture** [comment]
I actually did try to remove all of my group chats from the group chat folder before I made my post here, but it caused a weird issue. After I manually deleted all of my group chat logs, I started a new group chat session. I later found that whenever I tried to open that new group chat session, Sillytavern created and started a new blank chat session instead. I had the sense to make a backup, and the issue went away when I copied my old group chat logs back to the folder. After that experiment, I stopped messing with the folder and reverted to manually deleting my group chat logs the slow way, one by one, through Sillytavern.

**Comment by ghost** [comment]
> I don't see any use case for that.

Upgrading this. There is a use case, too many chat logs slow down opening the chat files unbearably, like minutes, in slow systems like Raspberry Pis.

The way I solved this is through a bash script running on Cron that only deletes the chat logs if the character folder has more than 200 chat logs, if the chat file isn't manually named, and if it is older than 2 months. All needs to happen together for it to be deleted. It would be nice to have a built-in button that deletes unnamed branches older than a certain time if their number grows too big.
