### ISSUE TITLE
[BUG] Bias doesn't work correctly

### ISSUE THREAD

**Issue by Anxious99** [SillyTavern/SillyTavern#1735]
### Environment

Android (Termux)

### System

Mobile Google Chrome

### Version

1.11.2 staging

### Describe the problem

When using bias macros, it is not hidden in the following answers, but remains in the user input that affects the following answers.

### Additional info

This problem constant. "{{bias "some text"}} always staining in context in user input and doesn't replace automatically.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [x] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by keturn** [comment]
Reproduced in SillyTavern 1.11.3 'release' (08e3fc60).

Sometimes it works as intended. Maybe it's specific to messages containing the macro that have been re-edited?
