### ISSUE TITLE
Feature request: Add web browser push notification for iOS

### ISSUE THREAD

**Issue by FrostyMisa** [SillyTavern/SillyTavern#1736]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

I have only small “problem” when using Silly Tavern on iOS with Safari (iPhone) and it’s when you don’t wait for the answer with browser opened, the answer will get lost and even you refresh the website, message is lost. When I watch the log, it also abort the generation. 

### Describe the solution you'd like

I’m running Koboldcpp on mini pc locally in my LAN, it’s cool, but slow. Running only on cpu, so it takes 15-2 minutes for reply. I don’t have problem with it, I’m happy it running on low power PC. But is there any way how to continue generating the message even I close Safari and receive it when I open it later or refresh the website? You know, it will be more convenient to have chance do something else on the phone then watch the web interface so the answer won’t get lost. 

Like if it can save the message when the client is not connected and be refreshed after when client connect again? Or safari on iOS support push notifications, this will be the best, if I can use other apps and when the message is ready, receive push notification, open the chat and message will be there!
https://developer.apple.com/documentation/usernotifications/sending_web_push_notifications_in_web_apps_and_browsers
Until there will be some iOS app directly connected to Silly Tavern, this will be great feature for all iOS users. 
Thank you for this great project!

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

No

**Comment by Cohee1207** [comment]
I made it an extension
https://github.com/Cohee1207/SillyTavern-PushNotifications

**Comment by FrostyMisa** [comment]
> I made it an extension https://github.com/Cohee1207/SillyTavern-PushNotifications

If I understand, this only add certificate to the website. How it will help me receive push notification when the text will be generated? iOS have lot of limitations. But I test some web with push and it works. So I think it can be implemented somehow.

**Comment by FrostyMisa** [comment]
I tested the latest version of Koboldcpp and the notification for chrome on PC in windows works great. After first message, it will ask if I want receive notification.
But sadly, on iOS, I tested in Safari, chrome and Firefox and it doesn’t ask me for receive notification.  So there must be some other way for iOS devices.
