### ISSUE TITLE
[FEATURE_REQUEST] Separate connection info from chat presets/prompts into a "connection manager"

### ISSUE THREAD

**Issue by LurkerHub** [SillyTavern/SillyTavern#1738]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Users often have different presets to see what works best for different scenarios.
They may also have access to multiple services, tokens, and reverse proxies.

Conceptually, those settings are orthogonal, so if one uses (for example) 10 different prompt settings and 10 different source/proxy/key combinations, it will result in 10x10=100 presets.

Moreover, if a prompt is updated, it needs to be changed in all the presets (10 in this example), which is extremely inconvenient.

### Describe the solution you'd like

I would like the proxy settings to be moved into API connections and have their own dropdown/import/export consisting of everything that is needed to connect:
- Connection name
- API
- Source
- Key / password
- Proxy / custom URL
- Optionally initial model selection

It is a much more logical organization.

### Priority

Medium (Would be very useful)

**Comment by Archeb** [comment]
This is absolutely useful. It's very inconvenient to have connection information in your preset when you want to export and share it with others.

**Comment by Cohee1207** [comment]
I think it's already done with Connection Profiles?
