### ISSUE TITLE
[BUG] Deleting current chat opens random chat

### ISSUE THREAD

**Issue by Technologicat** [SillyTavern/SillyTavern#1740]
### Environment

Self-Hosted (Bare Metal)

### System

Chromium, Version 120.0.6099.109 (Official Build) for Linux Mint (64-bit)

### Version

SillyTavern 1.11.3 'staging' (e627e897)

### Desktop Information

Node.js: v20.10.0
API: oobabooga (self-hosted / bare metal), with the OAI compatible endpoints
Branch: staging
Model: [dolphin-2.6-mistral-7b-dpo-laser.Q5_K_M.gguf](https://huggingface.co/TheBloke/dolphin-2.6-mistral-7B-dpo-laser-GGUF)

### Describe the problem

**Steps to reproduce**

- "≡" menu ⊳ *Start new chat*
- Enter something in the chat, send to AI, wait for response to complete, to make this new chat auto-save in *Manage chat files*.
- "≡" menu ⊳ *Manage chat files*
- Delete the chat that is currently open

**Expected result**

The latest existing chat with the same character opens.

**Actual result**

A random existing chat with the same character opens, from some arbitrary time. If there is some logic to this, I haven't been able to figure out what it is.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Technologicat** [comment]
I wonder if this has something to do with file timestamps, similarly to https://github.com/SillyTavern/SillyTavern/issues/1069?

**Comment by Cohee1207** [comment]
> The latest existing chat with the same character opens.

Ok, done.

**Comment by Technologicat** [comment]
Thanks!
