### ISSUE TITLE
[FEATURE_REQUEST] Quick access to Manage chat files

### ISSUE THREAD

**Issue by Technologicat** [SillyTavern/SillyTavern#1742]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

I constantly use the *Manage chat files* feature, but opening it requires two clicks, which is frustrating.

**Background**

In fact-heavy use cases, it's better to keep irrelevant information out of the context window to discourage hallucinations and sidetracking (from the irrelevant information present in the context window), so I open new chats quite often.

However, sometimes I need to return to an existing chat, for example to ask a follow-up question. *Manage chat files* is convenient for this, especially via its search feature.

But as soon as I'm done with the follow-up,  I'll then quickly again switch to another chat, which requires another two clicks to open the switcher GUI.

### Describe the solution you'd like

I'd like to open *Manage chat files* with one click.

### Describe alternatives you've considered

- Dedicated GUI button?
- Default quick reply script, like *New chat* is?

### Additional context

I can make a PR, but I'd like to first discuss whether this is desirable, and if so, what the best UX approach is.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

Yes!

**Comment by Cohee1207** [comment]
`/chat-manager`, `/chat-history`, `/manage-chats` pick whatever you like, they all do the same.

**Comment by Technologicat** [comment]
Ooh, great! Thanks!
