### ISSUE TITLE
[BUG] Change persona image - Upload successfull but loaded from browser cache

### ISSUE THREAD

**Issue by stho90** [SillyTavern/SillyTavern#1745]
### Environment

Self-Hosted (Bare Metal)

### System

Tested on: Debian 11.8, Win11

### Version

v1.11.2 (release)

### Desktop Information

Firefox v122

### Describe the problem

I wanted to change my own char picture, found in "Persona Management".
There, i clicked on my own persona and selected "Change persona image".
Then i selected a .png (and tested it with .jpeg) and the "Set the crop" window appeared. I did not change the size and selected "Accept".

But the picture did not change in the frontend, even if i pressed F5.

Here is the example:

I wanted to change the picture:
![grafik](https://github.com/SillyTavern/SillyTavern/assets/143583451/2686d7a4-02eb-42b4-a6bb-7a3a3bc5d680)

Then i selected a picture and pressed Accept:
![grafik](https://github.com/SillyTavern/SillyTavern/assets/143583451/4be4bbc9-6238-423b-9e24-4380feb2f8f1)

After pressing F5, the old picture was still there. It seems that the picture was stored in the browser cache and is not marked as "Expired" from the webserver. (If i use F12 and select "Disable cache" and refresh the page, then the correct picture is shown)

![grafik](https://github.com/SillyTavern/SillyTavern/assets/143583451/761d0354-40a4-4dfe-a7f4-88af4985fd0a)

After some searching, i found the following: https://stackoverflow.com/a/22013028
Quote:
```
...
What you probably need to fix, is to add Expires headers to what you are serving. 
Then you will see the NS_BINDING_ABORTED message change to (cache), 
meaning the browser is simply getting content out of its cache, knowing it has not yet expired.
...
```

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Related: #1720

> Firefox has a very aggressive image cache which doesn't bust when using Fetch API with no-cache.

**Comment by alkaris2** [comment]
I came looking to see if there were any solutions to this exact issue I'm also having, but then I came across a page that tells you how to get Firefox to respect the `no-cache` by going to your `about:config` and look for `browser.cache.disk.enable` and toggle it to `False`. This appears to be a workable solution to this problem unless they decide to change it within Firefox again.

**Comment by Cohee1207** [comment]
No need. There's a workaround in code _specifically for Firefox_ that forces to redownload persona images every time they're displayed.
https://github.com/SillyTavern/SillyTavern/blob/release/public/script.js#L5962

**Comment by alkaris2** [comment]
If that's the case, then I shouldn't have been able to still have this bug as a result in the latest releases that I downloaded from, so I'm looking at two possibilities here, another Firefox update broke it again, or the code isn't doing what it should be doing, or is not consistent between different platforms when applying the workaround code.
