### ISSUE TITLE
[FEATURE_REQUEST] Separate simulation time that passes with each AI message

### ISSUE THREAD

**Issue by MLBott** [SillyTavern/SillyTavern#1752]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Many AI models get confused on time passage and don't know how to progress time in a natural way.

### Describe the solution you'd like

I think it could be useful to have an option to keep custom world time rate in the AM/PM format as a system variable, and increment it by a percentage whenever the AI replies. The user could also reset time to whatever number they want for changing scenes, or changing characters. Every couple in-RP hours, the system could inject the time into the chat as a system message so the AI can also see it and adjust to it.

### Describe alternatives you've considered

I tried something like this with quick replies and STscript with a 24 hour format. The result was OK, but the AI still got confused on whether 1200 meant AM or PM.
![Screenshot 2024-01-26 205922](https://github.com/SillyTavern/SillyTavern/assets/7270299/f1bc3e61-0e23-42a7-9f8e-d9ea9b53ac75)
![Screenshot 2024-01-26 210136](https://github.com/SillyTavern/SillyTavern/assets/7270299/e4fdf63b-a5ff-48ad-83d0-6f93d85d7a57)

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

None

**Comment by Sazu-bit** [comment]
When going with formats, sometimes it's helpful to specify... so 1200z or 1200 UTC or even T1200z (per ISO 8601) that might help with the AI being able to detect the time properly.
