### ISSUE TITLE
[FEATURE_REQUEST] Proxy support for API connection (not reverse proxy)

### ISSUE THREAD

**Issue by OKN1212** [SillyTavern/SillyTavern#1756]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Sometime I stumbled into random people using cloudflared or similar hosting local model for people to test and play with, however, by connecting to their server it potentially can log your IP address and therefore the prompt log can be traced back.
This is also a problem with Kobold horde, although their server already act as a proxy, one can never be too cautious.

### Describe the solution you'd like

Create a proxy solution inside user config such as SOCKS5 and HTTPS.
Bonus point if we can configure which API connection use which proxy.

### Describe alternatives you've considered

VPN: This is no-brainer, just use a VPN, but then I need to whitelist/blacklist each API connection, or using a dedicated browser altogether. I currently use this method but it's quite a hassle.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

None

**Comment by LurkerHub** [comment]
Please add a HTTP(S)/SOCKS proxy option for the outgoing connection (to server, reverse proxy, horde, etc.)
