### ISSUE TITLE
[FEATURE_REQUEST] Mute character in group chat but keep character card

### ISSUE THREAD

**Issue by AlyxMS** [SillyTavern/SillyTavern#1758]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

In group chats, sometimes character card might contain important context. This is largely fixed with the "Join Character Card" feature added a while ago. However, if a character is muted, their description would not be included in the prompt, even if "Group generation handling mode" is set to "Join Character Card".

### Describe the solution you'd like

If "Join Character Card" is selected, muting a character should preserve the character's description in the prompt. Perhaps an additional button "Disable" can be added that functions the same as the original mute button.

### Describe alternatives you've considered

Instead of adding a button, have an option in the settings menu that changes how mute behaves.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
Maybe this will work?
![image](https://github.com/SillyTavern/SillyTavern/assets/18619528/fa25a77d-b295-4b6b-a9cd-494371bf7369)

**Comment by AlyxMS** [comment]
> Maybe this will work? ![image](https://private-user-images.githubusercontent.com/18619528/300772125-fa25a77d-b295-4b6b-a9cd-494371bf7369.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MTU2OTcsIm5iZiI6MTcwNjYxNTM5NywicGF0aCI6Ii8xODYxOTUyOC8zMDA3NzIxMjUtZmEyNWE3N2QtYjI5NS00YjZiLWE5Y2QtNDk0MzcxYmY3MzY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDExNDk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwMjIwMTQ2M2QyM2E2MmIxNDVmOGY1Y2FjYzJhZjk1OThjYWFlYjcyZWM1MWVkOGYwZWY2NjUxMDliMzI4NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4jy00lza4uHKb_IiCcId6ErYuvlqoLHH7j8IcwKYQjA)

Oh, that's amazing, thanks!

I tested your code a little bit, worked flawlessly so far.
