### ISSUE TITLE
[FEATURE_REQUEST] Add support for advanced samplers (min_p, top_a, etc) to custom chat completion endpoint

### ISSUE THREAD

**Issue by jackie1218** [SillyTavern/SillyTavern#1759]
### Have you searched for similar requests?

Yes

### Describe the solution you'd like

Currently, when OpenRouter is selected as the chat completion API, you can select from several advanced samplers that aren't available if using the Custom (OAI-Compatible) option. These should be selectable, but like unlocking the context size, have a warning that some APIs might not support it.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

No

**Comment by Cohee1207** [comment]
Custom endpoint type is intended only for OpenAI-compatible endpoints, which OpenRouter parameters do not comply with and will cause validation errors if sent unconditionally. Another issue is that parameter names aren't uniform across ""compatible"" endpoints. For example "Repetition Penalty" translates to `repeat_renalty` in llama.cpp server and `repetition_penalty` in oobabooga. Use the "Additional parameters" window to add extra body params.
