### ISSUE TITLE
[BUG] Importing characters doesn't work on mobile

### ISSUE THREAD

**Issue by aikitoria** [SillyTavern/SillyTavern#1760]
### Environment

Other (Specify below)

### System

Server running on Windows 11, tried client with both Chrome Android and Firefox Android

### Version

1.11.3 'staging' (4d1a77aa)

### Describe the problem

Trying to use the character import buttons doesn't seem to work on mobile browsers. After uploading an image to it, nothing happens, and nothing appears in the server log either.

Trying to use the cloud import button and entering a chub.ai url makes it say it downloaded the character file in the log, but it does not proceed to the second step of importing it that happens in a desktop browser. The import window closes on the client side and nothing else happens.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Spacellary** [comment]
Just my feedback as well, but personally I can't reproduce it, importing seems to work be it cards or chub.ai links (server running on Windows 11 - connecting via local network from mobile)... :'(

**Comment by aikitoria** [comment]
Hmm, interesting. I wonder what's the issue then...

Trying to follow the code to see where it drops, but the flow is very strange - the client seems to send a request to the server, which then downloads the character from chub and returns it to the client, only for the client to then upload it back to the server to a different endpoint?

**Comment by Cohee1207** [comment]
Yes. The client itself doesn't do any communications with the remote server. Your requests are probably blocked by Cloudflare, which sometimes happens and doesn't really depend on ST.

**Comment by aikitoria** [comment]
I don't think that's the case though, if requests from my SillyTavern server were blocked by Cloudflare, why would it reliably work when using a desktop browser? If I manually download the character.png file from the website and then try to use the direct upload button with the media picker, nothing happens after that either. It's like my mobile browser is failing to upload the attachment correctly or something.

**Comment by aikitoria** [comment]
Nevermind, it was my fault, I had wrongly configured the maximum upload size on the proxy I use to expose SillyTavern to other devices like my phone.

Though it would probably be useful if the client showed some kind of error message if the upload fails
