### ISSUE TITLE
[FEATURE_REQUEST] Add pages to persona management tab

### ISSUE THREAD

**Issue by etgv2** [SillyTavern/SillyTavern#1761]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

When you have too many personas in the persona management tab, the screen kind of looks unorganized and messy.

### Describe the solution you'd like

Add pages for the personas in the persona management tab, also make it so we can change how many columns and rows the pages are.

### Additional context

I'm not entirely sure if this is already a feature, but I did look through the settings and couldn't find anything.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

Yes!

**Comment by etgv2** [comment]
The new persona management tab is pretty good, but there is still a few things I would personally change. Having 10 per page makes it so you have to scroll down to see one of your personas, and it would be easier to see all of your avatars at once so you can just switch pages without having to scroll.  It would also be convenient to have columns as well or a grid view, so you can see more avatars, and maybe the option to remove the descriptions below the names.  Edit; Someone else brought this up already but you cant make new personas either.

**Comment by Cohee1207** [comment]
> Having 10 per page makes it so you have to scroll down to see one of your personas

Added an option to view 5 personas per page (making it a default one).

>  Someone else brought this up already but you cant make new personas either.

You actually can, it just starts with assigning a name first and uploading an image second, basically enforcing one flow and making personas more of an entity on its own rather than just an extra lichen on top of a user avatar. I moved a button to a more natural place so it is visible.

> It would also be convenient to have columns as well or a grid view, so you can see more avatars, and maybe the option to remove the descriptions below the names

Basically, reverting to an old-style avatar-only view? We'll see.

**Comment by etgv2** [comment]
> Basically, reverting to an old-style avatar-only view? We'll see.

Yeah, but adding the names below the avatars might look better and be more convenient. Also in the characater management tab, its still only 10 per page, maybe you should add a 5 per page option too.

**Comment by Cohee1207** [comment]
Got it, I'll look into it shortly.
