### ISSUE TITLE
[BUG] Scrollbar style not being applied properly

### ISSUE THREAD

**Issue by ArnoldDCoy** [SillyTavern/SillyTavern#1762]
### Environment

Self-Hosted (Bare Metal)

### System

Chrome 121.0.6167.86

### Version

SillyTavern 1.11.2 'release' (e3ccaf70)

### Describe the problem

I just recently updated ST. The scrollbar is some default browser one instead of the one ST is meant to have.
![scroll](https://github.com/SillyTavern/SillyTavern/assets/143622787/89e4f437-3f9a-45e3-ab50-e39892f7b991)
It's distracting as hell.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Fixed in the pre-release branch: https://github.com/SillyTavern/SillyTavern/commit/625a07ac1f02c896191030feeb2ef6ee4edbae4d
