### ISSUE TITLE
[BUG] How to add new persona now? Can't find a way after presona management rework.

### ISSUE THREAD

**Issue by valden80** [SillyTavern/SillyTavern#1765]
### Environment

Self-Hosted (Bare Metal)

### System

Firefox 115.2.0esr, Manjaro current.

### Version

SillyTavern1.11.2 staging

### Desktop Information

- OS/Device: Manjaro Linux
 - Environment: local
 - Node.js: version 20.2.0
 - Browser: Firefox
 - Generation API: Oobaboga
 - Branch: staging
 - Model: any local
 
 Firefox 115.2.0esr, Manjaro current.

### Describe the problem

After current rework of persona management in staging (commit e1b28580aa3d81e8c4bf95dcb89091522b5ee37b), ability to add new persona seem's to be missing. Can't find how to add a new persona now.
If it's still possible somehow - it's become so counterintuitive that it's can be considered a bug still.

### Additional info

As you doing persona rework, maybe you can also add a feature - binding the lore book to persona (the same thing as binding to character)?

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by glencoe2004** [comment]
Do you see either of these options? Both of them will let you create a new persona
![silly](https://github.com/SillyTavern/SillyTavern/assets/19866447/9d96a1ec-0e73-4533-a17e-1f7d5b8485fc)

**Comment by Cohee1207** [comment]
"Create" button creates a blank persona.

**Comment by Cohee1207** [comment]
This should be it.

![image](https://github.com/SillyTavern/SillyTavern/assets/18619528/a4259e14-ceed-488b-9b63-f7ce96bc3ece)

**Comment by valden80** [comment]
This is how I seen it first time:
![pic1](https://github.com/SillyTavern/SillyTavern/assets/111227649/5f1b0fb8-6e2a-4679-9669-4a553a5da246)
Then after few reloads and restarting:
![pic2](https://github.com/SillyTavern/SillyTavern/assets/111227649/0ad397ab-8901-46f7-98e7-b199feeb6d86)
I assume it's scroll problem (not fully up on first image, but it's not scrolled by mouse scroll and no slider line to indicate it.) 
After these restarts/reloads it's seems to be fixed, but layout still looking strange in Firefox...
Maybe it will look better if right column will be moves one string lower - So "Name" will be in the one level with "Astor" - name of the first persona card.
