### ISSUE TITLE
[BUG] /len command not working

### ISSUE THREAD

**Issue by creamsan** [SillyTavern/SillyTavern#1781]
### Environment

Android (Termux)

### System

Mull 121.1.0

### Version

Staging 17a783f9

### Describe the problem

In chat or QR, /len does not work.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by creamsan** [comment]
Numbers as argument returns undefined
![Screenshot_20240203-074503_1](https://github.com/SillyTavern/SillyTavern/assets/141376415/87c756b0-aac3-40ce-8bdc-f8c06c4a2f42)
![Screenshot_20240203-074511_1](https://github.com/SillyTavern/SillyTavern/assets/141376415/160cd5cb-316f-4343-bda9-dc428d201885)

For vars, defined or otherwise, do not send to chat
![Screenshot_20240203-074538_1](https://github.com/SillyTavern/SillyTavern/assets/141376415/9c61da17-41f4-4d03-affe-6fd3b0ee3b71)
![Screenshot_20240203-074611_1](https://github.com/SillyTavern/SillyTavern/assets/141376415/7602b950-438a-43c8-895d-0ecf8d7546c6)
![Screenshot_20240203-074632_1](https://github.com/SillyTavern/SillyTavern/assets/141376415/ec154c38-e412-4641-8ae2-09ad6bff3dc9)

**Comment by Cohee1207** [comment]
There are actually two problems at once - one was that /len doesn't parse numeric values as strings, and that non-string return values are trying to get unescaped. I think I solved both, try it out, please.

**Comment by creamsan** [comment]
👌
