### ISSUE TITLE
[FEATURE_REQUEST] Send multiple requests or multi swipe for OpenAI completions

### ISSUE THREAD

**Issue by imesha10** [SillyTavern/SillyTavern#1782]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

To send multiple (streaming) requests at once.
The problem is sometimes a gpt-4-1106 message might take a minuite because it's long. In order to rp faster it would be better to send multiple requests at the same time.
I have checked the issues and the docs but I could not find anything regarding an existing feature.

A related issue that I found but for a different source is #1403.

### Describe the solution you'd like

The ability to send multiple swipes. 

I have no idea how this would be implemented but here are some loose ideas:
1. In the settings or somewhere have a setting where it asks for how many requests to send on a swipe.
2. When pressing the > or swiping allow the user to swipe to a new one while the old one is still generating. And be able to swipe back and forth while it's generating.

It would be prefereable if this solution includes the streaming outputs in each message, but it's also fine if you can't.

### Describe alternatives you've considered

Just waiting.

### Additional context

None

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

No

**Comment by Cohee1207** [comment]
1 will be fine. It's already implemented for Aphrodite backend, similar approach could be reused. 
2 is not possible, swipes are blocked during the generation to prevent data corruption.

**Comment by imesha10** [comment]
Alright, 1 is good.
Please implement it.

**Comment by imesha10** [comment]
@Cohee1207 
Please revert this commit or add a checkbox beside it to enable and disable it. 
I'm getting 
```
{
    "error": "An error occurred while validating your request."
}
```

I should add that the method used in aphrodite is not directly appropriate for openai. Open ai does not have a batch parameter that you pass in the docs.
When I mentioned this feature request I was thinking about everytime the user enter let's say 2 in the "multiple swipes per generation box" you would send simulataneously two seperate requests. 
However the current implementnation seems to only send one request with n=inputnumber as a paramter.

I just did some research and I found these links on OpenAI. It seems there is another way to do this. I have never tested this though.

Info about batching
https://platform.openai.com/docs/guides/production-best-practices/batching

Example and usage of batching
https://platform.openai.com/docs/guides/rate-limits/batching-requests

**Comment by Cohee1207** [comment]
`n` is from an official OpenAI API reference for Chat Completion API. It was tested with OpenAI turbo. What exactly gives you that response? An official OpenAI endpoint with real API key?

<img width="520" alt="image" src="https://github.com/SillyTavern/SillyTavern/assets/18619528/e211c873-841d-4555-9ed9-718d044ad544">

**Comment by imesha10** [comment]
> `n` is from an official OpenAI API reference for Chat Completion API. It was tested with OpenAI turbo. What exactly gives you that response? An official OpenAI endpoint with real API key?
> 
> <img alt="image" width="520" src="https://private-user-images.githubusercontent.com/18619528/302128017-e211c873-841d-4555-9ed9-718d044ad544.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNzQ2OTgsIm5iZiI6MTcwNzA3NDM5OCwicGF0aCI6Ii8xODYxOTUyOC8zMDIxMjgwMTctZTIxMWM4NzMtODQxZC00NTU1LTllZDktNzE4ZDA0NGFkNTQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDE5MTk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5YWM1NmMyZmRiODMxOTA5NDg0NmM0MjgyZjBjZDZjNmJhMDUyYzgyYzAzNDU1NDNmNTY3NTI2OGMyZjEwNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I5h0pUp775nHu6m9alR4wW3X6FvvCoMG5UzcV4XdTiA">

Ok I was wrong. How did I miss that. Yes you're right, I was using a proxy that gives me gpt-4-turbo. I guess they have not implemented this on the proxy side and it gave a validation error. My bad.

But is there a way to disable this if the current model does not support it? Like setting it to -1 or a checkbox?

**Comment by Cohee1207** [comment]
> using a proxy

Do not report problems with proxies.
