### ISSUE TITLE
[BUG] SillyTavern not using ContextShifting

### ISSUE THREAD

**Issue by Sazu-bit** [SillyTavern/SillyTavern#1784]
### Environment

Self-Hosted (Bare Metal)

### System

Manjaro, kernel 5.15.145. Firefox 121.0.1.

### Version

SillyTavern 1.11.2 'release' (e3ccaf70)

### Desktop Information

Node: 21.5.0
Generation API: koboldcpp
Branch: Release
Model MythoMax 13B

### Describe the problem

When I use KoboldCpp (Lite), ContextShifting works near flawlessly. When I use SillyTavern instead of ContextShifting despite nothing changing, it simply processes the entire prompt. 

I do not have
- Summarizing
- Vectorizing
- World Info / Lorebooks
- Randomization macros

I'm not going to say all my settings are default because I've been messing with them. I've set the Tokenizer to API and I've set the padding to 69 (giggity). My context is 4096, which is exactly the same as KoboldCpp.

I'm unsure what else I can do here to try and make it work. Please could someone provide some assistance. 

### Additional info

This happens constantly, it is very very rare that SillyTavern actually uses ContextShifting and I have no idea why. 

```
Processing Prompt [BLAS] (3695 / 3695 tokens)
Generating (17 / 400 tokens)
(EOS token triggered!)
ContextLimit: 3713/4096, Processing:436.85s (118.2ms/T), Generation:44.79s (2634.8ms/T), Total:481.64s (0.04T/s)
```

```
Processing Prompt [BLAS] (3695 / 3695 tokens)
Generating (16 / 400 tokens)
(EOS token triggered!)
ContextLimit: 3712/4096, Processing:429.85s (116.3ms/T), Generation:40.15s (2509.6ms/T), Total:470.00s (0.03T/s)
```

```
Processing Prompt [BLAS] (3695 / 3695 tokens)
Generating (60 / 400 tokens)
(EOS token triggered!)
ContextLimit: 3756/4096, Processing:390.50s (105.7ms/T), Generation:45.30s (755.0ms/T), Total:435.79s (0.14T/s)
```

i have no idea why the processing prompt appears to being limited to 3695.

KoboldCpp settings

```
{"model": null, "model_param": "/data/AI/llm/mythomax-l2-13b.Q5_K_M.gguf", "port": 5001, "port_param": 5001, "host": "", "launch": false, "lora": null, "config": null, "threads": 6, "blasthreads": null, "highpriority": false, "contextsize": 4096, "blasbatchsize": 512, "ropeconfig": [0, 10000.0], "smartcontext": false, "noshift": false, "bantokens": null, "forceversion": 0, "nommap": false, "usemlock": false, "noavx2": false, "debugmode": 0, "skiplauncher": false, "hordeconfig": null, "noblas": false, "useclblast": [0, 0], "usecublas": null, "gpulayers": 37, "tensor_split": null, "onready": "", "multiuser": 1, "remotetunnel": false, "foreground": false, "preloadstory": null, "quiet": false, "ssl": null}
```

To be clear, I have checked previous issues but I have not found a solution or the OP of the issue went awol. The SillyTavern documentation does not provide any guidance on this matter. 

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Take raw generated prompts and run them with string diff

**Comment by Sazu-bit** [comment]
Okay so I've just run this through an online diff checker because I have no clue how my command line version is supposed to work and I can't tell the difference. 

As far as I can tell, the only difference between Block A and Block B is that Block A had a chunk of text chopped (specifically it was an earlier chat message nothing to do with lore books or random generated content). Block B had the addition of the newer content. 

Both called for a full Processing Prompt. I also checked Block B against Block C and again, a full processing prompt. The only thing that changed was a block of the earlier text getting deleted. The personality/bot descriptor and char remained the same.

**Comment by Cohee1207** [comment]
When going through Kobold Lite, are you sure you're reaching a context cutoff point? Or you are comparing empty vs full context? 

Try increasing padding, maybe that would help.

**Comment by Sazu-bit** [comment]
I never reach the 'cut off point' with KoboldCpp because of the context shifting, it's always getting rid of some of the earlier stuff. I'll try setting the padding to 200. Documentation seems to indicated that this has no affect on chat, only on instruct but will give it a shot. 

Kobold Lite ContextShifting also works when I use memory as well, where as I'm aware SillyTavern's Lorebooks apparently have an issue with. Brb, gonna relaunch.

**Comment by Sazu-bit** [comment]
Padding had no effect.

**Comment by Sazu-bit** [comment]
Never mind, instructions were unclear and I dun goofed.

For anyone else having a problem with ContextShifting not working in SillyTavern you may have selected the wrong API. For koboldcpp you want Text Completion, not Chat Completion (despite what other documentation may say). 

Context Shifting appears to be working after correcting that little error.

**Comment by Spacellary** [comment]
I am currently experiencing some times where Context Shifting just doesn't happen without any dynamic information involved.

Discussion if you've found anything else since then:

https://github.com/LostRuins/koboldcpp/discussions/674#discussioncomment-8430464

**Comment by Woisek** [comment]
> For anyone else having a problem with ContextShifting not working in SillyTavern you may have selected the wrong API.

I'm probably blind, but where exactly is this set? 🤔

**Comment by Spacellary** [comment]
@Woisek This: https://postimg.cc/K1LZhLdM/7ca0acc1

But I already have it set correctly, as the screenshot shows.

**Comment by Woisek** [comment]
> @Woisek This: https://postimg.cc/K1LZhLdM/7ca0acc1
> 
> But I already have it set correctly, as the screenshot shows.

Oh, that's interesting now. I have set this always to KoboldAI Classic, because I believed that this would be right one when using koboldccp. So I was entirely wrong all the time ... ? 🤔
Thanks for pointing that out.

**Comment by Spacellary** [comment]
@Woisek Since there is a dedicated option for KoboldCpp in the Text Completion API I believe that is the correct option.

Is that correct, @LostRuins?

**Comment by LostRuins** [comment]
Both options should work. Cohee has chosen to prioritize the OpenAI (Text Completion) API over the classic Kobold API for KoboldCpp users, so some newer features/samplers may not be sent in the payload while using the Kobold API. But from the backend, both APIs should be fully supported with all permitted fields and functionality.
