### ISSUE TITLE
[BUG] Dynatemp missing from koboldcpp

### ISSUE THREAD

**Issue by ghost** [SillyTavern/SillyTavern#1788]
### Environment

Self-Hosted (Bare Metal)

### System

Windows 11

### Version

1.11.3

### Desktop Information

Node.js v20.11.0.
koboldcpp 1.56

### Describe the problem

After upgrading to 1.11.3, Dynamic Temperature setting is missing from KoboldCpp presets.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
This issue is not clear. Provide more details.

**Comment by ghost** [comment]
I am using Silly Tavern with Kobold.Cpp. I am using my custom Mixtral preset from Text Completion presets. It uses Dynamic Temperature.

I got the notification about 1.11.3 release. Closed Silly Tavern. Run UpdateAndStart.bat.

When Silly Tavern opened, I opened my presets. Dynamic Temperature was missing from the screen, like this: https://imgpile.com/images/x81wwr.png

It used to be there.

**Comment by Cohee1207** [comment]
It is still there for me. Show your API connection panel.

<img width="527" alt="image" src="https://github.com/SillyTavern/SillyTavern/assets/18619528/1b863d39-3694-4562-b2ad-e738ec72181c">

**Comment by ghost** [comment]
Here, I have no other backends installed: https://imgpile.com/images/x815sR.png

**Comment by ghost** [comment]
This is how it all looks: https://imgpile.com/images/x81R0g.png

**Comment by Cohee1207** [comment]
Consider the following, in order:
1. Switch source from KoboldCpp to other and then back.
2. Switch from Advanced to Simple UI mode and back (in User Settings).
3. Do a clean install in a separate folder and compare.
4. Restore to a default settings.json (delete from /public, and restart ST server).

**Comment by Cohee1207** [comment]
Did you have any git conflicts on pull or unresolved merges? Try resetting the git state
```
git merge --abort
git reset --hard
git pull --rebase --autostash
```

**Comment by ghost** [comment]
Resetting git fixed it. Thank you =)
