### ISSUE TITLE
[BUG] Repetition Penalty Slope setting is missing under Text Completition -> KoboldCpp

### ISSUE THREAD

**Issue by Robot1me** [SillyTavern/SillyTavern#1789]
### Environment

Self-Hosted (Bare Metal)

### System

Windows 10, Firefox 121, Chrome 121

### Version

SillyTavern 1.11.3

### Desktop Information

- Branch: release

### Describe the problem

Since Reddit is not the place to make bug reports, I thought to create this issue.
Under API Connections -> Text Completion -> KoboldCpp, the API Response Configuration window is still **missing** the **"Repetition Penalty Slope"** setting. I have seen that KoboldCpp is no longer meant to be used under the "KoboldAI Classic" AI, but it does still have the "Repetition Penalty Slope" setting.

### Additional info

Here are two screenshots that show you what I mean.

Repetition Penalty Slope still there under "KoboldAI Classic":
![2024-02-04_205818](https://github.com/SillyTavern/SillyTavern/assets/51457886/3910fa2d-c4af-406d-af3d-b57c7fd427ac)

Does not exist under "KoboldCpp":
![2024-02-04_205855](https://github.com/SillyTavern/SillyTavern/assets/51457886/596c46a3-3a74-47c6-8b1b-e6b3929c3dcc)

If you can add the setting back to KoboldCpp, it would be much appreciated. Thanks for all your efforts and this awesome project!

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
It would do nothing for KoboldCpp, it is not supported there.
