### ISSUE TITLE
[BUG] AllTalk TTS error - TTS Provider not ready. TypeError: Failed to fetch

### ISSUE THREAD

**Issue by Jefferderp** [SillyTavern/SillyTavern#1796]
### Environment

Other (Specify below)

### System

Debian 12 (virtualized)

### Version

1.11.3 release-branch

### Desktop Information

nodejs v20.11.0 (also tried v18)

### Describe the problem

Hello!

I'm running an AllTalk TTS server, and it's reachable at `http://192.168.1.64:7851/`. I have confirmed that the server is reachable by  SillyTavern, by running `curl http://192.168.1.64:7851/` within the ST environment.

When refreshing the ST GUI, in the _Plugins_ menu, under _TTS_, I get the error _`TTS Provider not ready. TypeError: Failed to fetch`_. When I click _Reload_ next to the _Select TTS provider_ dropdown, the error becomes `TypeError: Failed to fetch`

This issue occurs regardless of whether:
* The _Enabled_ checkbox is toggled
* The _Endpoint_ URL is correct or not.
* I install via your your official docker container image, or via a straight git clone.

I am running the latest version on the release branch, in a Debian 12 virtual machine.

Am I correct that `sillytavern-extras` is not required in this case? This wasn't clearly called out in the docs. I spun up and connected an instance, and some other `extras` modules were active, but this error was not resolved.

I'm unsure how to continue debugging this. Are there any logs I can reference, or more information to provide?

Thanks very much!

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Jefferderp** [comment]
Is there any more information I can provide to help troubleshoot this?

Could anybody with a working AllTalk TTS integration share how their setup might be different?

Thanks very much!

**Comment by Cohee1207** [comment]
I have no idea, @erew123 please take a look.

**Comment by erew123** [comment]
Hi @Jefferderp 

As I only have a few details on your setup, Im going to ask a few general questions:

1) In the AllTalk configuration page of the machine where you are running AllTalk http://127.0.0.1:7851/, have you changed the external IP Address from 127.0.0.1 to 192.168.1.64 (and then restarted AlllTalk)? Making it directly available on http://192.168.1.64:7851/

![image](https://github.com/SillyTavern/SillyTavern/assets/35898566/45d6b871-ab19-4d0a-a7ef-85e3a1f52d37)

2) Can you confirm that when you load SillyTavern and look at the TTS Page, the endpoint is set to the 192.168.1.64 IP address (without having to change it again).

![image](https://github.com/SillyTavern/SillyTavern/assets/35898566/f069c0ea-e5b7-4963-b339-c73d529ff0bb)

3) I see you have CURL available, so could you try the following both on the local and remote machine:

```curl -X POST "http://192.168.1.64:7851/api/tts-generate" -d "text_input=All of this is text spoken by the character. This is text not inside quotes, though that doesnt matter in the slightest" -d "text_filtering=standard" -d "character_voice_gen=female_01.wav" -d "narrator_enabled=false" -d "narrator_voice_gen=male_01.wav" -d "text_not_inside=character" -d "language=en" -d "output_file_name=myoutputfile" -d "output_file_timestamp=true" -d "autoplay=true" -d "autoplay_volume=0.8"```

Audio should play on the machine where AllTalk is running and you should get a response similar to the following....

![image](https://github.com/SillyTavern/SillyTavern/assets/35898566/f9252cb4-efef-418a-8f8e-25123eb4ec3a)

4) On the AllTalk configuration page, in the **Demo/Test TTS** section, does that work when connecting on the local machine (where AllTalk is running) and also when connecting to that page from the remote machine? 

Please let me know

Thanks

**Comment by Jefferderp** [comment]
Hey @erew123 , thanks very much for your assistance with this.

1. Yes my AllTalk TTS config is correct, and I'm accessing the interface from `http://192.168.1.64:7851`.

2. In SillyTavern, the API URL is pre-populated with the default localhost address:
![image](https://github.com/SillyTavern/SillyTavern/assets/13530594/53a32390-3b3b-4850-b20e-d9bfa2c04414)

When I change the _AllTalk Endpoint_ field to `http://192.168.1.64:7851`, and uncheck/recheck _Enabled_, I still see _Status: Offline_. When I refresh the page, the value resets itself to `http://localhost:7851`. When I change the value and press Enter, the page refreshes itself and again the _AllTalk Endpoint_ field resets itself to `http://localhost:7851`.

This may be at the root of the issue. Could there be an issue saving to a config file?

I'm running the official container image found in this repo, via `docker-compose`, and have had no issues saving/recalling other UI settings. As mentioned, I also experienced this issue with a vanilla install via `git`.

3. Yes, I see activity and hear TTS output, both when I run your `curl` command locally and from the machine running SillyTavern. On the SillyTavern machine, I'm running the command *inside* the docker environment, and still the communication works just fine.

4. Yes, the **Demo/Test TTS** section works great from the host machine. The machine running SillyTavern is a headless VM running Debian, so I don't have a browser to check with, however I can `curl` the AllTalk web interface and receive the expected response.

Thanks again for your help!

**Comment by erew123** [comment]
@Jefferderp Thanks for that! I think nail on the head with the settings issue. Ive seen this issue where it doesnt save the setting immediately when you change the IP address unless it communicates to the AllTalk server (it may be something I have to jig in the backend at some point). However there is a workaround you can try:

In your SillyTavern Public folder `/sillytavern/public/` there is a file called `settings.json`. In there, if you search for `AllTalk` you should find `"provider_endpoint"` and you can manually change `localhost` to `192.168.1.64` (as below)

![image](https://github.com/SillyTavern/SillyTavern/assets/35898566/144e4ac4-87dc-4a2b-8a73-39314abed1ca)

Save the file and refresh the SillyTavern page (no need to reload) and see if that now connects.

Thanks

**Comment by Jefferderp** [comment]
That did the trick! Works great now, thanks very much.

Very curiously, the section for AllTalk was not populated in my `settings.json`. Here's an excerpt:

```json
        "tts": {
            "voiceMap": "",
            "ttsEnabled": false,
            "currentProvider": "AllTalk",
            "auto_generation": true,
            "ElevenLabs": {},
            "System": {
                "voiceMap": {
                    "[Default Voice]": "disabled",
                    "User": "[Default Voice]",
                    "Seraphina": "[Default Voice]"
                }
            },
            "narrate_user": false,
            "XTTSv2": {
             ...truncated...
                },
                "streaming": true
            },
            "enabled": true,
            "skip_codeblocks": true,
            "pass_asterisks": true,
            "AllTalk": {},   <-----
            "Silero": {
                "provider_endpoint": "https://patch-patrol-universe-jd.trycloudflare.com/api/tts",
                "voiceMap": {
                    "[Default Voice]": "en_0",
                    "User": "[Default Voice]",
                    "Seraphina": "[Default Voice]"
                }
            },
            "Coqui": {
                "voiceMap": {},
                "customVoices": {},
                "voiceIds": [],
                "voiceMapDict": {}
            },
            "Novel": {
                "voiceMap": {
                    "[Default Voice]": "disabled",
                    "User": "[Default Voice]",
                    "Seraphina": "[Default Voice]"
                ...
```

I added the _provider_endpoint_ key manually, reloaded the GUI, and the rest of the keys populated themselves.

Thanks again.

**Comment by erew123** [comment]
@Jefferderp Great! Glad you have it working. 

Pretty sure ST wont populate that area until its actually had 1x successful connection, at which point it will save the settings in there. Good to know that pushing the endpoint setting in made it work though.

I cant close this ticket off so you may want to close it.

Thanks

**Comment by Jefferderp** [comment]
Gotcha! Yes you're right, I had to establish a connection using the correct endpoint URL before the config file would populate.

**Comment by Cohee1207** [comment]
I tried to fix it on staging. The problem was that the event handler of Endpoint input was set up after the status check (which could fail). It means that if the API runs on non-default URL, it fails.

**Comment by erew123** [comment]
@Cohee1207 Is this something I have out of sequence? (in the AllTalk code)

Thanks
