### ISSUE TITLE
[BUG] <Dubbing translated text in XTTS. Russian translate or any other that changes the quotes to «direct speech» or —direct speech—. >

### ISSUE THREAD

**Issue by KazPulse** [SillyTavern/SillyTavern#1807]
### Environment

Self-Hosted (Bare Metal)

### System

Google Chrome 121.0.6167.161. Windows 10 Pro. i7-13700K. 3080ti. 

### Version

1.11.2

### Desktop Information

node v21.5.0
Staging
KoboldAI
Noromaid-13b-v0.3-T4.q4_k_s

### Describe the problem

When using XTTS to voice direct speech in a language other than English(In my case, Russian), there is an incorrect definition of direct speech.
I use the translation of the text from English to Russian. When translating, the structure changes from "direct speech" to «direct speech» or —direct speech—. Regex helps to get the formatting back to "". 
When XTTS receives the translated text, it voices it in full (ignoring the quotes for direct speech).

Is it possible to make an option for the translated text to arrive in XTTS after processing it by Regex? So that XTTS understands direct speech correctly.

I tried to change it, but it didn't help.
I will be very glad if you tell me what to change in XTTS.py
processText(text) {
// Replace "..." with "«...»"
text = text.replace(/\.\.\./g, '«...»');
// Replace "..." with "—...—"
text = text.replace(/\.\.\./g, '—...—');

and 

text = text.replace(/"/g, '«').replace(/"/g, '»');

### Additional info

![1](https://github.com/SillyTavern/SillyTavern/assets/155398120/effd1e92-4c42-4fe4-bd52-2fb81b4ce0c4)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
I think you'd want to normalize quotes to `"` instead of `«` other regional variants. Basically, extend this line to include your flavor of quotes:
https://github.com/SillyTavern/SillyTavern/blob/release/public/scripts/extensions/tts/index.js#L539

Then if your option is to translate only quoted text, it will be extracted properly.

**Comment by KazPulse** [comment]
> I think you'd want to normalize quotes to `"` instead of `«` other regional variants. Basically, extend this line to include your flavor of quotes: https://github.com/SillyTavern/SillyTavern/blob/release/public/scripts/extensions/tts/index.js#L539
> 
> Then if your option is to translate only quoted text, it will be extracted properly.

Oh, it's working. Thanks for the super fast response.
