### ISSUE TITLE
[BUG] Failed to run SillyTavern on docker

### ISSUE THREAD

**Issue by Klounita** [SillyTavern/SillyTavern#1809]
### Environment

Self-Hosted (Docker)

### System

Manjaro linux, Docker 24.0.7

### Version

SillyTavern 1.11.3

### Desktop Information

Node.js v19.1.0

### Describe the problem

**Have you searched for similar [bugs](https://github.com/Cohee1207/SillyTavern/issues?q=)?**
Yes, [latest message here is similar](https://github.com/SillyTavern/SillyTavern/issues/434)

**Describe the bug**
Failed to run SillyTavern 1.11.3 on docker, latest version that work is SillyTavern 1.10.9.
I also tried run that image on k8s on debian 12.4 and got the same result.

**To Reproduce**
`sudo docker run ghcr.io/sillytavern/sillytavern:1.11.3
`

**Expected behavior**
sillytavern to start on port 8000

### Additional info

**logs:**
```
...
# -- SERVER PLUGIN CONFIGURATION --
enableServerPlugins: false
The listen parameter is set to false. If you can't connect to the server, edit the "docker/config/config.yaml" file and restart the container.
The whitelistMode parameter is set to true. If you can't connect to the server, edit the "docker/config/config.yaml" file and restart the container.
Running from source
SillyTavern 1.11.3
node:fs:1388
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, mkdir 'public/user/images/'
    at Object.mkdirSync (node:fs:1388:3)
    at ensurePublicDirectoriesExist (/home/node/app/server.js:705:16)
    at Server.setupTasks (/home/node/app/server.js:619:5) {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: 'public/user/images/'
}

Node.js v19.1.0

```

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Try 1.11.4, should be fixed.

**Comment by Klounita** [comment]
It's works now, thanks!
