### ISSUE TITLE
[BUG] Failed to run SillyTavern on podman

### ISSUE THREAD

**Issue by wy580477** [SillyTavern/SillyTavern#1812]
### Environment

Other (Specify below)

### System

Debian 12, podman 4.3.1

### Version

1.11.4

### Describe the problem

It seems that there is no "/home/node/app/public/user"  path in the container. 

Result in following error:

Error: crun: openat2 `home/node/app/public/user`: No such file or directory: OCI runtime attempted to invoke a command that was not found

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Steps to replicate?

**Comment by wy580477** [comment]
> Steps to replicate?


I tried to run container with following command, then it gave me the error above. Only "
/home/node/app/public/user" this path give me trouble. If I delete  "-v /home/debian/podman-volumes/sillytavern/user:/home/node/app/public/user", the container works fine.

podman run -d --name sillytavern -p 8666:8000 -v /home/debian/podman-volumes/sillytavern/user:/home/node/app/public/user -v /home/debian/podman-volumes/sillytavern/config:/home/node/app/config -v /home/debian/podman-volumes/sillytavern/extensions:/home/node/app/public/scripts/extensions/third-party ghcr.io/sillytavern/sillytavern:latest

**Comment by Cohee1207** [comment]
https://github.com/SillyTavern/SillyTavern/pkgs/container/sillytavern/177463919?tag=1.11.4-1
https://github.com/SillyTavern/SillyTavern/commit/f183f55c741d075ebfc13e3f4e2bbc7aac6c9132

**Comment by wy580477** [comment]
> https://github.com/SillyTavern/SillyTavern/pkgs/container/sillytavern/177463919?tag=1.11.4-1 [f183f55](https://github.com/SillyTavern/SillyTavern/commit/f183f55c741d075ebfc13e3f4e2bbc7aac6c9132)

Thx. Working fine now. 

Here is a suggestion:

"Listen for incoming connections" option shoud be set to true on default for container deployment. Because most docker users will use bridge network.
