### ISSUE TITLE
[BUG] Squash system messages not working

### ISSUE THREAD

**Issue by Quairon-Nailo** [SillyTavern/SillyTavern#1813]
### Environment

Self-Hosted (Bare Metal)

### System

Windows 11

### Version

1.11.3

### Describe the problem

When turning Squash System messages it still sends multiple System messages in a row, the request is the same as when the setting is off.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Can you show what is being sent? Messages that are marked "example_assistant" and "example_user" are not squashed

**Comment by Quairon-Nailo** [comment]
![image](https://github.com/SillyTavern/SillyTavern/assets/28443257/2f8eab26-9d31-4fed-b1ba-bbd68c3c89a1)

**Comment by Cohee1207** [comment]
Ok, found the problem, thanks.

**Comment by Wolfsblvt** [comment]
Fixed and shipped in the latest release.
