### ISSUE TITLE
[FEATURE_REQUEST] Allow proxy support to other completion sources

### ISSUE THREAD

**Issue by LurkerHub** [SillyTavern/SillyTavern#1818]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

I am trying to use a reverse proxy with AI21 (J2 ultra) but the UI does not allow it

### Describe the solution you'd like

The ability to use reverse proxies with sources other than OpenAI and Claude.

In particular, this request is about AI21, but support for other other sources (Mistral? Google?) will also be appreciated

Also, it appears to me that the "OpenAI compatible" option only supports a single endpoint.
I would like the ability to save more than one "OpenAI compatible" endpoint/key pair (whether by reusing the proxy dorpdown or by other means)
Putting it here because I use this to with proxies that provide access to other models while pretending to be OpenAI, but I can a separate issue for it if it's preferred.

### Priority

Medium (Would be very useful)

**Comment by alexolog** [comment]
Asking to reopen
