### ISSUE TITLE
[FEATURE_REQUEST] Add Impersonation Prompt control for Text Completion API

### ISSUE THREAD

**Issue by Spacellary** [SillyTavern/SillyTavern#1819]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

The Text Completion API is missing the ability to control the /impersonate prompt effectively, which is present in the Chat Completion API.

### Describe the solution you'd like

I'd like to see enhancements when using the Text Completion API to include a feature similar to the Chat Completion API, where you can customize the Impersonation Prompt in the UI.

### Describe alternatives you've considered

N/A

### Additional context

[Related Reddit thread.](https://www.reddit.com/r/SillyTavernAI/comments/1anzczx/options_to_change_the_behavior_of_impersonate/)

### Priority

Low

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
Text Completion mode does not require a prompt for impersonation, since it's a text completion. It formats the prompt as would a user message would be.

**Comment by Spacellary** [comment]
Taking into account what u/Worldly-Mistake-8147 said:
> From what I could get form the sources (and then confirmed by looking into the inference server log), in text completion mode it just sends user's sequence (ie <|im_start|>user) and/or {{user}}'s name, forcing the model to continue as the user.
> 
> The chat's history (including the character's description and your persona) is the prompt. Which I think was pointed by other comments too.


@Cohee1207 Would also sending an Impersonation Prompt, for Text Completions, help tune the reply generations as well?

**Comment by Cohee1207** [comment]
The prompt stays the same, only the formatting of the last line changes. You can test it yourself, swapping the prompts manually.

**Comment by Spacellary** [comment]
@Cohee1207, got it. That is kind of what I was expecting for this implementation, pretty much just a way to set a separate `### Response:` or equivalent for /impersonate.

In your honest opinion does that sound too convoluted or impractical?

**Comment by Spacellary** [comment]
Satisfied enough by Merge https://github.com/SillyTavern/SillyTavern/pull/1840. The additional control is what I was looking for.
