### ISSUE TITLE
[BUG] Multiple pipe macros not replacing.

### ISSUE THREAD

**Issue by creamsan** [SillyTavern/SillyTavern#1821]
### Environment

Android (Termux)

### System

Mull 122.0.0

### Version

SillyTavern 1.11.4 'staging' (04804881)

### Describe the problem

Only the first one gets replaced. I'm not sure if this is intended or not, but I kinda remember being able to replace multiple.

### Additional info

![Screenshot_20240212-042523_1](https://github.com/SillyTavern/SillyTavern/assets/141376415/b1fb20e9-7486-422e-bf52-434f2da7449a)

![Screenshot_20240212-042608_1](https://github.com/SillyTavern/SillyTavern/assets/141376415/b484fb04-a547-4122-b2eb-35a7de180cff)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Yes, intended. Only the first instance of pipe is replaced.

**Comment by creamsan** [comment]
Oh, ok. Got it.
