### ISSUE TITLE
[BUG] Disabling Top K by setting it to 0 seems equivalent to setting it to 1

### ISSUE THREAD

**Issue by jim-plus** [SillyTavern/SillyTavern#1823]
### Environment

Self-Hosted (Bare Metal)

### System

Windows 11

### Version

1.11.4

### Desktop Information

Python 3.11.5
Current stable node.js
Occurs with every GGUF model I try, even with bare llama-cpp-python.

### Describe the problem

When I manually set Top K to 0, the result is deterministic, as if I had step Top K to 1. According to the hover help, setting Top K to 0 should disable this. A workaround is to set Top K to the max of 200, but this lacks elegance.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Top K "disabled" value differs across the backend. It could be either 0 or -1 to use the entire vocabulary. What is the actual API you're using it with? Text Completion?

**Comment by jim-plus** [comment]
Yes, llama-cpp-python reports POST /v1/completions via llama_cpp.server.

The slider doesn't let me pick -1. Manual entry tells me valid numbers must be between 0 and 200, so I can't force -1 from SillyTavern.

**Comment by Cohee1207** [comment]
Changed the min value for the top K slider to -1. But not in Zen sliders mode because it makes it janky, so use regular sliders mode.
