### ISSUE TITLE
[FEATURE_REQUEST] Better resolution selection for SDXL

### ISSUE THREAD

**Issue by aikitoria** [SillyTavern/SillyTavern#1826]
### Have you searched for similar requests?

Yes

### Describe the solution you'd like

Currently, it seems like if we use the options "Generate Image" -> "Your Face" or "Generate Image" -> "Background" it will take the base resolution and scale up one axis. But for SDXL this is wrong and produces distorted images, the total pixel count needs to stay roughly the same as the aspect ratio changes.

Perhaps the easiest way to handle it would be to add separate options for which resolution to use for each picture type.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

No

**Comment by Cohee1207** [comment]
There was already a list of good SDXL resolutions, so the easiest was to allow using that instead.

**Comment by aikitoria** [comment]
Nice, can confirm that works as intended!
