### ISSUE TITLE
[BUG] The {{group}} macro doesn't return the entire group's name, and just returns one character's name

### ISSUE THREAD

**Issue by qwertea** [SillyTavern/SillyTavern#1827]
### Environment

Self-Hosted (Bare Metal)

### System

Arch Linux, Firefox

### Version

SillyTavern 1.11.4 'staging' (72256110)

### Desktop Information

- node --version: v21.5.0
- OpenAI
- staging
- gpt-4-0125-preview

### Describe the problem

The {{group}} macro, when used in custom prompts or the chat, returns the currently speaking character's name instead of all names in the group (exactly the same result as {{char}}). Inconsistently, when it's used in its default utility prompt ("New Group Chat"), it returns the full group separated by commas, which is the behaviour I expected. I don't know what the 'intended' behaviour here is since there seems to be no documentation for this macro; if this is intentional please re-tag this issue to be a feature request for a macro which consistently returns the names of all characters in the group chat, as that would be a basic & very useful feature for custom presets designed for group chats. Related question: what the heck does {{charIfNotGroup}} do?

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
{{group}} should now work everywhere. charIfNotGroup is an alias for it.

**Comment by qwertea** [comment]
Thank you, it seems to function fine. I also had a small feature request to better separate definitions when using joint character cards in group chats, but it should be a different issue so I'll make it.
