### ISSUE TITLE
[FEATURE_REQUEST] Char Description format template in Utility Prompts

### ISSUE THREAD

**Issue by qwertea** [SillyTavern/SillyTavern#1828]
### Have you searched for similar requests?

None

### Is your feature request related to a problem? If so, please describe.

When using the 'Join character cards' in group chats*, the descriptions for each character are joint with no separation/wrapping, which can confuse the LLM into conflating characters (depending on how the descriptions are formatted, of course, but I'd rather not alter definitions manually for each group chat).

\* I always use this since newer models have enough context and smarts to remember multiple characters but speak only as one. The 'Swap character cards' method can lead to inaccuracies or hallucinations about present but not speaking characters.

### Describe the solution you'd like

Adding an extra format template in the Utility Prompts for Character Descriptions, similar to existant ones for Scenarios and Personalities. The user could use separators, or wrap character definitions in XML tags, which Claude is specifically trained to understand, and GPT also understands just fine. Like this:
<{{char}}'s description>
{{description}}
</{{char}} description>

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

None

**Comment by qwertea** [comment]
Well I tried implementing this myself since I kinda need it. I just copied how it's done for personalities in openai.js, and it works perfectly fine single chats, but in group chats descriptions are still joint without separation except a newline (hardcoded in group-chats.js, related: #1829), and it happens before the format template is applied, so the end result is just:
```
<{{char1}}'s description>
(char1's description)
(char2's description)
(char3's description)
</{{char1}}'s description>
```
Sadly I don't really know how to fix that (not a real programmer lol)

**Comment by Wolfsblvt** [comment]
PR for this is open. Feel free to check it out and test if you want: #2036

**Comment by qwertea** [comment]
Closing pre-emptively so I don't forget to later.

**Comment by Wolfsblvt** [comment]
It would've auto-closed when the PR gets merged into `release` branch :D

**Comment by qwertea** [comment]
Whoops, didn't know.
