### ISSUE TITLE
[BUG] Personality merge in group chats when using Join Character Cards

### ISSUE THREAD

**Issue by AlyxMS** [SillyTavern/SillyTavern#1829]
### Environment

Self-Hosted (Bare Metal)

### System

Chrome 121.0.6167.161

### Version

SillyTavern 1.11.3 'release' (318235e1)

### Desktop Information

API: Ooba

### Describe the problem

While using the "Join Character Cards" option(either include or exclude muted characters), the personalities of character would be joined before added to the prompt. Always remaining the same no matter who is actually speaking.

To illustrate the issue, assume 3 character cards:
Person A, personality: calm, focused
Person B, personality: angry, chaotic
Person C, personality: (empty)

When person A is speaking, the prompt would look something like this:
```
Person A's personality: calm, focused\n
angry,chaotic\n
\n
```

When person B is speaking:
```
Person B's personality: calm, focused\n
angry,chaotic\n
\n
```

When person C is speaking:
```
Person C's personality: calm, focused\n
angry,chaotic\n
\n
```

I believe this issue also affects scienario, since I will always get
```
Scienario: \n
\n
\n
```
appended to my prompt despite all my characters having emtpy scienarios. And this is not seen when Group generation handling mode is set to "Swap Character Cards".

Idealy, personality and scienario should remain independent. While character descriptions are joined.

### Additional info

I am using the default Context Template.

I've managed to solve the empty scienario issue, I think. With: `.filter(e => e.length)` before the join to filter out empties and prevent a string full of `\n`s.
Also added it to description, personality and mesExamples. And by writing personalities in the character description instead of using SillyTavern's provided personality field, I think I've side stepped the issue for now. But still, it probably needs a proper fix.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Wolfsblvt** [comment]
Found the issue and attempted a bugfix.

Your original suggestion was on point. We'll just have to filter out all empty fields on character cards, so they don't get considered for the join.

**Comment by Wolfsblvt** [comment]
This one is fixed, @deffcolony
