### ISSUE TITLE
[BUG] <Error in the child process>

### ISSUE THREAD

**Issue by Brayan123KM** [SillyTavern/SillyTavern#1831]
### Environment

Self-Hosted (Bare Metal)

### System

Windows 10 - 64 bits - Chrome 121

### Version

1.11.4

### Desktop Information

Node.js version: 20.11.0

### Describe the problem

Well, I had tried to run SillyTavern on my PC, everything was fine until I always got this code that did not allow me to run the program. I have the recommended version of Node.js so I don't understand how to solve that. And I tried with the latest version of Node.js... But it doesn't worked too. Please help :(

### Additional info

![Captura de pantalla 2024-02-14 201738](https://github.com/SillyTavern/SillyTavern/assets/159750114/1d0d287c-6be0-4c02-99ef-1bf19210d268)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Something else is listening on port 8000, change port number in config.yaml

**Comment by Brayan123KM** [comment]
> Something else is listening on port 8000, change port number in config.yaml

Thanks man! But... How exactly can I do that? I'm not that expert on this topic haha

**Comment by Cohee1207** [comment]
Open this file with text editor, change the number, restart.
