### ISSUE TITLE
[BUG] <Uncaught exception>

### ISSUE THREAD

**Issue by Brayan123KM** [SillyTavern/SillyTavern#1835]
### Environment

Self-Hosted (Docker)

### System

Windows 10 - 64 bits - Chrome 121

### Version

1.11.4

### Desktop Information

Node.js 20.11.0

### Describe the problem

Well, I had tried to install SillyTavern on my PC, everything was fine until I always got this code that didn't allow me to run the program. I have the recommended version of Node.js so I don't understand how to solve that. And I tried with the latest version of Node.js... But it doesn't worked too.

### Additional info

![Captura de pantalla 2024-02-14 201738](https://github.com/SillyTavern/SillyTavern/assets/159750114/e306d4ae-53eb-4ada-a2e8-f1a479528059)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Wolfsblvt** [comment]
Have you tried running Silly Tavern on a different port? Maybe port 8000 is currently being blocked by something on your system already.  
You can do this by opening the `config.yaml` in your ST folder, and change `port: 8000` to something like `port: 8027` or whatever.
