### ISSUE TITLE
[FEATURE_REQUEST] more text styles (e.g. inner thoughts)

### ISSUE THREAD

**Issue by keturn** [SillyTavern/SillyTavern#1836]
### Have you searched for similar requests?

Yes

### Describe the solution you'd like

I see the current theme system allows customization of _Italics Text_ and _Quote Text,_ but some texts (such as the [Lima RP](https://huggingface.co/datasets/lemonilia/LimaRP) data set) give semantics to other syntactic elements. The most interesting of which, IMHO, is that inner dialog (a character's internal thoughts) uses underscores, which are kept distinct from other forms of emphasis.

As it is in ST today, both *asterisks* and _underscored_ phrases both get lumped in to the single category of Italics Text. It would be nice to be able to distinguish them. Perhaps even introduce an extensible mechanism that lets us introduce other new text styles.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

Maybe

**Comment by Wolfsblvt** [comment]
Is part of the latest release now. So consider this feature implemented.
