### ISSUE TITLE
[FEATURE_REQUEST] Increase size of text entry area

### ISSUE THREAD

**Issue by Sazu-bit** [SillyTavern/SillyTavern#1837]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

When I type a long paragraph into the submission box/increase the size of submission area it will basically hide part of the chat that I'm referring to when typing my reply. Very inconvenient. Sometimes I just copy and paste the previous reply into notepad to get around this. 

We're talking between 100 and 200 words.

### Describe the solution you'd like

I can't seem to find anything in the CSS to change it. (If someone could provide the CSS, I'll happily run it through Stylus/Stylish or something)

At the moment the text entry box is designed to have a single line. If you're writing a larger submission, it hides part of the previous chat and this can be somewhat hard to use. Yes you can increase the size of the submission area, but this increases the amount of the chat that is hidden. 

Changing the auto-scroll doesn't seem to affect this. 

I suspect it has something to do with the submitted content css trying to take 90% of the entire display, rather than the space it actually has. Is the chat submission area nested within the same container?

### Describe alternatives you've considered

Adjusting the CSS (this doesn't appear to affect it)
Increasing the size of the submission area through the GUI (exacerbates the problem)

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

No

### Workaround

Use a third party open source extension such as Stylus. https://github.com/SillyTavern/SillyTavern/issues/1837#issuecomment-1951996648

**Comment by Cohee1207** [comment]
What submission area? Can I have a screenshot of what are you talking about ? If you're talking about user input text area - it is auto expanded vertically as any input is performed.

**Comment by Sazu-bit** [comment]
Yes that's the area and yes it auto expands... but when it auto expands, the text already submitted gets hidden. 

So each extra line the submission box takes up, a line will be hidden from the text and then I have to scroll it down manually. The best way to test this is to have a full screen of content, then copy/paste a text dump into the chat area and watch as the text gets hidden.

What I expect to happen is that the latest text remains visible and the earliest text becomes hidden, at the moment it's the other way around. 

Auto-scroll is ticked, but it only auto-scrolls upon a reply (which, is expected behavior). Hence my request for the size of the text area to have a larger minimum size. In all fairness it has a 'width' setting, which (is useless to me *shrug*) but no height setting. My submissions are usually between 200-350 tokens a time so this problem is quite frequent for me.

**Comment by Sazu-bit** [comment]
Yes that's the area and yes it auto expands... but when it auto expands, the text already submitted gets hidden. 

So each extra line the submission box takes up, a line will be hidden from the text and then I have to scroll it down manually. The best way to test this is to have a full screen of content, then copy/paste a text dump into the chat area and watch as the text gets hidden.

What I expect to happen is that the latest text remains visible and the earliest text becomes hidden, at the moment it's the other way around. 

Auto-scroll is ticked, but it only auto-scrolls upon a reply (which, is expected behavior). Hence my request for the size of the text area to have a larger minimum size. In all fairness it has a 'width' setting, which (is useless to me *shrug*) but no height setting. My submissions are usually between 200-350 tokens a time so this problem is quite frequent for me.

**Comment by Cohee1207** [comment]
Switch from Firefox to a different browser

**Comment by Sazu-bit** [comment]
That's unfortunately not going to work. I cannot run chromium-based browsers on my system while running the AI at the same time, not without significantly compromising the AI. I would have to drop from a 13B model to a 7B model and/or halve the amount of context I use. Chromium/Chrome use significant resources on my machine and do not have the add-ons that I use for accessibility reasons. (High Performance Cost vs Low Usability Increase, doesn't seem great value for money)

Firefox is more standards compliant than Chrome and most other browsers. All I'm requesting should be a fairly easy fix I just don't know what the CSS is to use, and that's to increase the minimum height of the text entry area. Doesn't have to be by default.

**Comment by Sazu-bit** [comment]
Found the CSS. 

Input the following into Stylus.
```
div#nonQRFormItems textarea#send_textarea {
    min-height: 150px;
}
```

Note: Be careful you don't add a comma between the two tags.

Seems to work quite nicely. Also works with movable UI. Configure number as required, just a shame that it needs a third party extension to do. 

It appears to replace:

```
min-height: var(--bottomFormBlockSize);
height: var(--bottomFormBlockSize);
```

Or at least they get lined out. As noted I'm using a Firefox-based browser, on a Linux Desktop. Your mileage may vary but should work.

**Comment by Cohee1207** [comment]
Firefox input scroll adjustment is specifically disabled because it causes issues due to the input area being resized. Glad you found an alternate solution.
