### ISSUE TITLE
[FEATURE_REQUEST] Can the unlocked max context size for OpenAI completion be increased from 102k to 200k for example?

### ISSUE THREAD

**Issue by RendiHD** [SillyTavern/SillyTavern#1842]
### Have you searched for similar requests?

None

### Is your feature request related to a problem? If so, please describe.

![Screenshot_2024-02-18-22-49-08-75_2c2851f616de21a6da6fb44c83a25e93](https://github.com/SillyTavern/SillyTavern/assets/75966130/e2d6aa98-3230-4fe4-8ca3-51e82044b884)

As in the picture above, I want to try to increase the context size to 200k, but I can't. If curious why would I want to increase it to 200k? Because there are other models such as Claude which require using OpenAI completion. And normally Claude's context size is 200k, but in unlocked the context size is only limited to 102k.

### Describe the solution you'd like

If possible, I hope this can be increased from 102k to 200k max context size(its for unlocked max context). That would be very helpful

### Describe alternatives you've considered

But if possible too, you can put this feature only in the on custom (openAI compatible) completion. Or maybe this alterantives idea! That is unlimited mode, if I explain it, it would be like this, (`The feature is active when the max context size is slid to the left until it becomes 0, that's when it changes to unlimited, the feature is same as Chat Truncation,  0 = unlimited`) for example, if some models like Claude have unlimited mode activated, dynamically it will automatically change them to 200k for Claude-2, and if for model claude-1.3-100k, then it will automatically become 100k, if the model is 32k, it will automatically change to 32k. That's simple i guess.

Anddd that is what i hope for the feature, hope you guys dont mind :)

Thanks!

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

Yes!

**Comment by Cohee1207** [comment]
> The feature is active when the max context size is slid to the left until it becomes 0, that's when it changes to unlimited, the feature is same as Chat Truncation,  0 = unlimited

No, sending more tokens than allowed by the model 99% of the time causes a hard validation error or other unintended behavior.

**Comment by Cohee1207** [comment]
> Because there are other models such as Claude which require using OpenAI completion

Also I don't get it. Claude has native Chat Completion source which correctly sets the max size per model.
