### ISSUE TITLE
Documenting everything in the exported/imported lorebook JSON files

### ISSUE THREAD

**Issue by theredwillow** [SillyTavern/SillyTavern#1847]
I'd like to engineer a much easier way to make lorebooks at scale, through imported JSON files. I created [a gist](https://gist.github.com/theredwillow/fe047fabad8e5608c492842f5cfdd116) for documenting what all of the exported properties are. I found quite a few in the [docs](https://docs.sillytavern.app/usage/core-concepts/worldinfo) but some are still missing.

I'm envisioning something like a customGPT that has this documentation in its instructions. That way you could just have a casual conversation with AI to generate a whole lorebook.

Here's an example...

Let's say I want to create dynamic instructions for a Pokemon story-telling game. I need it to know what types of Pokemon are commonly associated with electric-type, what types are strong against electric, and what types are weak against it. But if I did that for each type all the time, that would eat up my token usage. _Lorebooks to the rescue!_ I could manually enter all this data, but I have found that ChatGPT can generate this information for me pretty quickly. I just need to format into an importable JSON file. Although this repo doesn't use TypeScript, it's a common way to handle this kind of documentation in a way that a computer can easily understand.

![image](https://github.com/SillyTavern/SillyTavern/assets/18607666/f481dd5a-397f-4d57-a7ae-7bd87a0d3ee6)

Could we update the docs to include everything a user could possibly need?

**Comment by Morgul** [comment]
I had a similar idea (dumping wiki pages to a llm and asking for a lorebook entry on the given topic). I also ran into the same issue of the format not being well documented.

+1 for this!
