### ISSUE TITLE
[FEATURE_REQUEST] google drive

### ISSUE THREAD

**Issue by RendiHD** [SillyTavern/SillyTavern#1849]
### Have you searched for similar requests?

None

### Is your feature request related to a problem? If so, please describe.

Is there any plan to link SillyTavern with Google Drive? So the chats and character cards are not lost anymore when the phone got reset or sillytavern accidentally got deleted

### Describe the solution you'd like

-

### Describe alternatives you've considered

-

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

Yes!

**Comment by Woisek** [comment]
Doing (regular) backups probably would be way easier ...

**Comment by botslop** [comment]
I don't think it would be a bad idea to have some built-in backup solution. Correct me if I'm wrong, but there is a ./backups folder in the root of ST. However, it seems to only capture chatlog history (and not the character definitions themselves). I didn't see any documentation on this but I figure that's what it is for.

Before considering a cloud backup option, it might be worth considering a scheduled local backup feature first that lets you choose a custom directory for character cards that have been modified? I doubt most ST users are backing up their cards/logs properly but I don't have anything to back that up. Even if a feature isn't directly added to ST, a write up on making proper backups could be a welcome addition.

**Comment by Cohee1207** [comment]
Everything you need to do to configure cloud backups is to drop your local installation folder to the cloud provider directory (OneDrive, Google, Dropbox). Anything else is a won't do.
