### ISSUE TITLE
[FEATURE_REQUEST] Fast switching of characters

### ISSUE THREAD

**Issue by XZVB12** [SillyTavern/SillyTavern#1850]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

If you have many characters and want to switch between them frequently you need to go back to the general list from the character card each time and search from the beginning.

### Describe the solution you'd like

Adding an item in the settings that allows you to select a character without opening its card and settings and without resetting the list of characters to the beginning.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

None

**Comment by underscorex86** [comment]
The slash command `/go Serphina` will open a chat with Seraphina. Just type the name of the character you want to go to in your chat.

You can create a quick reply button with the /go command and you can even add a sub-menu to the quick reply button with a list of your favourite characters if you wish.

**Comment by XZVB12** [comment]
> The slash command `/go Serphina` will open a chat with Seraphina. Just type the name of the character you want to go to in your chat.
> 
> You can create a quick reply button with the /go command and you can even add a sub-menu to the quick reply button with a list of your favourite characters if you wish.

Thanks, I knew about this possibility, but when you have 250+ characters it's not very convenient and not all names can be memorized, some consist of several words or symbols that aren't on the keyboard. So it doesn't solve the problem completely.

**Comment by Cohee1207** [comment]
So, what's an actual proposal here? I don't see the opening without seeing the card useful, as you can't favorite, delete, tag, etc.  without going into bulk mode. Also, the paginated characters don't reset if you click the list button once (it resets to the first page if clicked twice), only the scroll position resets. Maybe you'd want to use tags for list organization?

**Comment by XZVB12** [comment]
> as you can't favorite, delete, tag, etc. without going into bulk mode.

You can navigate to a persona card by double-clicking with the mouse, for example. One click opens the chat, double click goes to the character card (if it is really necessary).

If you think this is a silly idea, I don't mind closing this discussion. I probably don't understand something about the ergonomics of interacting with personages. In any case, I can just limit the list of personas to 10 per page, even though it requires extra clicks to switch.
