### ISSUE TITLE
[BUG] New Example Chat doesn't parse {{char}} (nor any other macro)

### ISSUE THREAD

**Issue by AnonCardMaker** [SillyTavern/SillyTavern#1851]
### Environment

Self-Hosted (Bare Metal)

### System

Firefox 122

### Version

1.11.3

### Describe the problem

The New Example Chat thing in Utility Prompts doesn't convert macros to what it should.
e.g.
[Following is an example of how {{char}} acts, reacts, and speaks:]

Will send the AI literally that, instead of changing {{char}} to Joe or whatever.  Same is true for {{user}}, {{random}}, {{roll}}.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Okay, confirmed missed that one. Will be fixed.

**Comment by Wolfsblvt** [comment]
Fixed and should be part of the latest release **1.11.7**

Can you confirm this?
