### ISSUE TITLE
[FEATURE_REQUEST] STscript in lore book entries

### ISSUE THREAD

**Issue by theredwillow** [SillyTavern/SillyTavern#1853]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

[Example use case]: I'm trying to use a lore book as a URL database.

The word "recommend" triggers a "You suggest IMDb links below..." lore entry. Then "recommend" + "dog" suggests a particular URL based on the summary ("imdb.com/all-dogs-go-to-heaven - A film about dogs as angels").

This works in the asking my character "Can you recommend any movies about dogs?", it responds with things like "I know a few... Balto, All Dogs Go to Heaven" (it seems to be getting the title from the 'comments' field, which I don't understand?).

### Describe the solution you'd like

I can't get the URL's in my use case to display in the chat at all. They get lost in the LLM every time. I'd like to bypass it (saving some tokens too!).

The most basic example in the docs (`/pass Hello, World! | /echo`) would actually serve this purpose perfectly.

The entry could display the text when it's called by executing the script directly in SillyTavern. It wouldn't even need to go to the LLM prompt!

This is just one example. Another one: I'm sure many people are doing `/sd` commands and would love a way to have lore books activate auto-generated images based on lore activation.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
This is similar to a request to make STscript shareable with character cards which I'm not doing as it is a risk for users, as we want them to only run trusted scripts that they informely imported and reviewed in prior. I can offer another auto-execution category for QR scripts "on WI activation" that executes when WI with a certain key (let's call it "Automation ID" gets activated). Will that be enough?

**Comment by theredwillow** [comment]
Thank you for your attention to security!

This sounds awesome!

Similarly, can quick replies also be *displayed* context-dependent _(like world info is with keywords or something)_?

I think it's possible now with STscript doing an `if` on `{{input}}` and `/qr-create`, but it feels like a more commonly used feature than something that needs to be engineered. Am I a newb overlooking something?

[Use case example]:
Surely there are users looking to create a "hello" template with options like "Hi!", "Hey there!", or "Sup".

**Comment by Wolfsblvt** [comment]
Was already done.
