### ISSUE TITLE
[FEATURE_REQUEST] Dynamic first message.

### ISSUE THREAD

**Issue by whocares0101** [SillyTavern/SillyTavern#1856]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

I'd like the first message to be dynamic to allow for more variety.

### Describe the solution you'd like

Execute the "First message" as a prompt instead of showing it as is.
This should be an optional per character setting.
Add a checkbox left of the "Alt. Greetings" button to enable/disable this feature, disabled by default.

Example first message:
[Narrate how a traveler matching the following description "{{persona}}" visits the following place.
An old and worn tavern in the worst part of town.]

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

No

**Comment by Wolfsblvt** [comment]
If you are on the Silly Tavern discord, there is one member who made an extension + script for dynamic opening messages.

https://discord.com/channels/1100685673633153084/1206374686930509915
