### ISSUE TITLE
[FEATURE_REQUEST] Allow setting 'Instruct' mode per card

### ISSUE THREAD

**Issue by Sazu-bit** [SillyTavern/SillyTavern#1857]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

When trying to test out the Instruct Mode, I noted that if I turned it on, that it applies to all chat instances. It's easy to forget that its enabled and I get odd results when I switch to a different character. 

### Describe the solution you'd like

I'd like to be able to set "Advanced Settings" (specifically Instruct mode) per character. The perfect solution would be to have "Disabled, Global, Local" choice so some settings would apply globally and some settings would only apply to the given card. This would allow for advanced settings to apply differently.

Another way might be to save "advanced settings" and then in the character area have an additional drop down to load preferred advanced settings. I do something similar with koboldcpp, where I have several different setting configs depending on which LLM I load. 

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

No

**Comment by Wolfsblvt** [comment]
You can name an instruct preset the same as your character, and it will be auto-loaded if you select the character.

Issue is, you can't easily bind presets to characters, because presets also depend on chosen API and model.
