### ISSUE TITLE
[FEATURE_REQUEST] Add support for Ollama `keep_alive` parameter

### ISSUE THREAD

**Issue by Morgul** [SillyTavern/SillyTavern#1859]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Ollama, by default, unloads the model after some time. This leads to some significant delays on generation for larger models that take a while to load.

### Describe the solution you'd like

Ollama has a `keep_alive` parameter (see [here](https://github.com/ollama/ollama/blob/main/docs/api.md#generate-a-completion)) that can specify the length of time before the model is unloaded. Specifying `-1` will disable this unloading behavior.

It would be nice to expose this property in the settings for Ollama, so the user can specify the kind of behavior they'd like.

### Describe alternatives you've considered

Unfortunately, there isn't much of one. There's no cli option or other parameter that can be sent to ollama to make it keep it around; I could send my own generation request with the `keep_alive` every time I want to change it, but that's pretty annoying.

### Additional context

I've figured out how to hack in sending `keep_alive` as `-1` in my local copy, but I haven't worked out how to expose this through the UI. I'm sure this is just a 5 minute change for someone who knows the codebase better.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

Maybe

**Comment by Cohee1207** [comment]
I'm not sure it warrants a UI toggle (same as llama.cpp prompt caching which is disabled by default). Anyway, I made the change.

**Comment by CultusMechanicus** [comment]
Ah, this change is forcing my GPU to stay on unless I kill ST and restart Ollama. I was using the Ollama environment var OLLAMA_KEEP_ALIVE to unload all models after 15 mins, but API calls override that and ST is sending a fixed -1 (keep forever) which leaves my GPU sucking down power 24/7 instead of idling at P8. Any chance this could be either configurable or removed?

**Comment by Wolfsblvt** [comment]
How about we make it a feature setting inside the server `config.yaml`, allowing an integer to be set?
Saves us from a weird one-API UI toggle, but still allows it to be configurable.

**Comment by Wolfsblvt** [comment]
Done on staging. You can test this, if you want.

**Comment by CultusMechanicus** [comment]
It works, but I suspect the docs are wrong. `5m` gives a keepalive of, like, 27 billion years, whereas `300` gives 5 minutes. So I'm guessing that it only accepts seconds, not formatted time. I wouldn't bother fixing it personally, just change the docs to say keepalive in secs.
