### ISSUE TITLE
OpenAI NSFW avoidance prompt should be visible to the user

### ISSUE THREAD

**Issue by sinoth** [SillyTavern/SillyTavern#186]
I noticed that disabling NSFW sends a prompt to OpenAI that I was not aware of. See here:
https://github.com/Cohee1207/SillyTavern/blob/f25ecbd95ceef54eafbc0b9be187264608803cfc/public/scripts/openai.js#L276

This should be visible to the user the same way the NSFW prompt is visible. In my situation I don't want *any* NSFW prompt sent to OpenAI, positive or negative.

**Comment by StefanDanielSchwarz** [comment]
@Cohee1207 Thanks. The workaround works.

With prompt building such a complex issue (and a great advantage SillyTavern has over other frontends), I'd love to see all of the prompt customization as its own top-level menu items, and not just for OpenAI.

There's even a [simple-proxy-for-tavern](https://github.com/anon998/simple-proxy-for-tavern) to make the OpenAI prompts usable with other backends, showing that prompt configuration is universally relevant.

**Comment by kakhulu31** [comment]
Since the nsfw toggle with the empty prompt field works fine, why not just add a note about it?

**Comment by RossAscends** [comment]
we now have prompt boxes for both encouragement and discouragement, and both can be left blank
