### ISSUE TITLE
[BUG] Instruct mode: Example dialogue formatted differently from message history when Include Names disabled

### ISSUE THREAD

**Issue by deciare** [SillyTavern/SillyTavern#1860]
### Environment

Self-Hosted (Bare Metal)

### System

Firefox 123, macOS 14.3.1

### Version

1.11.4 (staging, fc289126)

### Describe the problem

# The problem

This issue occurs with the following combination of settings in Advanced Formatting.

- Instruct Mode: enabled
- Include Names: disabled
- Force for Groups and Personas: enabled

Given the above settings, the persona's name is always appended to the input sequence when formatting chat history. However, the persona's name is _not_ appended to the input sequence when formatting example dialogue.

To illustrate, here are samples of messages formatted with an Alpaca-derived instruction template.

Formatted example dialogue:
```
### Response:
Hello Deci, what's on your mind?
### Input:
I'm just here for some sample output. Please keep your responses as short as possible.
### Response:
Sure thing!
### Input:
Thanks. Say one more thing.
### Response:
Certainly.
```

Formatted chat history:
```
### Response:
Hello Deci, what's on your mind?
### Input:
Deci: I'm just here for some sample output. Please keep your responses as short as possible.
### Response:
Sure thing!
### Input:
Deci: Thanks. Say one more thing.
### Response:
Certainly.
```

# Potential resolutions

- Append the currently-selected persona's name to the input sequence when formatting example dialogue, too.
- Rework the **Force for Groups and Personas** setting so that it only appends the persona's name to the input sequence if more than one persona is involved in the current chat.
- Explain the purpose of the **Force for Groups and Personas** setting in the documentation (I wasn't able to find any mention of it in the docs). Is it possible to have a chat without creating/selecting a persona?

# Workarounds

Simply disable the **Force for Groups and Personas** setting, so that names are either always included or never included.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Wolfsblvt** [comment]
Confirmed, and attempted a bugfix.

**Comment by Cohee1207** [comment]
Fix merged to the staging branch. Let us know if you find any problem with the solution.

**Comment by deciare** [comment]
Example dialogue now appears consistent with chat history in all cases. Thanks!
