### ISSUE TITLE
[FEATURE_REQUEST] Alt Greetings in Group chats

### ISSUE THREAD

**Issue by zer0thgear** [SillyTavern/SillyTavern#1867]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

As it stands, when you create a group chat (using the Create New Group Chat Button) you're only able to use the first/default greeting for each character. I would like to be able to use an alternate greeting for each character in the group chat, if one exists.

### Describe the solution you'd like

Each character in the group chat would have the ability to have their greetings cycled through like in a single chat. The last character in the list would retain the ability to start generating new messages when you attempt to swipe past their last greeting.

### Describe alternatives you've considered

My current workaround is to convert the first character to a group chat, which will allow me to use an alt greeting for them. For any additional characters I then manually trigger a response and replace their message with the desired greeting.
I've seen people alternatively create separate cards for single-use and group chats, but that seems clunky and unnecessary.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

Maybe

**Comment by Cohee1207** [comment]
The new group chat selects greetings [randomly](https://github.com/SillyTavern/SillyTavern/blob/release/public/scripts/group-chats.js#L380). What's the proposed solution exactly? Ability to select a greeting to be used only in group chats? Because as you've said, there are rarely any greetings in publicly available cards that are compatible with group scenarios.

**Comment by zer0thgear** [comment]
The idea is that in a groupchat consisting of N characters, all characters would have the swipe arrows exposed to cycle through greetings if any alternate greetings are present. For the sake of continuity, only the last/Nth character to speak would have the ability to generate new messages on swipe instead of looping around back to the first greeting. And similar to single chats, once a message has been sent by the user all previous swipe arrows would disappear. Hacked together a quick mockup with Paint just in case.
![ui example](https://github.com/SillyTavern/SillyTavern/assets/161616981/72be5893-dd92-4148-ae46-3b81cd54fd3c)
![image](https://github.com/SillyTavern/SillyTavern/assets/161616981/789c2d5c-3706-4b0a-b630-19853507f28c)

My main concern would be running into the same continuity and format issues as #1731, but the expectation here is to be able to choose a greeting at the beginning of the chat rather than having the swipes always be available or creating explicit flags/fields for this purpose.

**Comment by Cohee1207** [comment]
I made an extension for that: https://github.com/SillyTavern/Extension-GroupGreetings
