### ISSUE TITLE
[FEATURE_REQUEST] Enable Sending Jailbreak Prompt in Preset by the current {{char}}.

### ISSUE THREAD

**Issue by imesha10** [SillyTavern/SillyTavern#1873]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

I have a jailbreak that has a section (seperate prompt) for female and another for male. Only one can be activated at a time.
When I want to send one for a specific male/female {{char}} I have to toggle the corrosponding jailbreak prompt on and the other one off. Each time when I want to switch back to the other character I have to do this in reverse.

### Describe the solution you'd like

So my request and solution to this is for each user generated prompt in the chat completion presets to have another optional field that you can enter the character name or select in a check box list that this will only apply to.
In here:
![image](https://github.com/SillyTavern/SillyTavern/assets/16441743/25e20975-596c-417f-967f-7e379b167173)

The filed can be just manually type in the name of the character or populate it with a list of all the characters (not groups ig) like the world info:
![image](https://github.com/SillyTavern/SillyTavern/assets/16441743/e2c4c149-2ee7-4115-8477-5b6c83c5ea13)

If it's empty then it should just be ignored and work as normal.

### Describe alternatives you've considered

None.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

No

**Comment by Cohee1207** [comment]
You can create a custom prompt at absolute position 0 and role system. The "real" jailbreak has no magical properties, any prompt injection will work. To make it connected to a card - set a variable in the card and use a macro.

**Comment by imesha10** [comment]
> You can create a custom prompt at absolute position 0 and role system. The "real" jailbreak has no magical properties, any prompt injection will work. To make it connected to a card - set a variable in the card and use a macro.

Yes it seems that I might be able to use that. However I have a question. How do I use / commands like `/if left="/getvar ...` in the prompt or the character card. It seems that the only place to use the slash commands is the user input. 

I'm adding things like to the prompt and sending it to see what it shows up as on the terminal.
```
{{// if left="/getvar sex" right=male rule=eq else="/setvar key=temp1 asdf" "/setvar key=temp1 qwer"}}
{{getvar::temp1}}
```
It does not seem to output anything.

I've looked through this and I didn't see a section regarding this.
https://docs.sillytavern.app/usage/st-script/#variables

**Comment by imesha10** [comment]
Oh ok it seems that after reading the docs more the quick reply can do what I need this to do.
I can run a set of commands there somehow and mess with the jailbreak. I'll figure it out.

https://docs.sillytavern.app/usage/st-script/#quick-replies-script-library-and-auto-execution

Thanks!
