### ISSUE TITLE
[FEATURE_REQUEST] Flowgpt in API section

### ISSUE THREAD

**Issue by infinit-X** [SillyTavern/SillyTavern#1878]
### Have you searched for similar requests?

None

### Describe the solution you'd like

Can't we add Flowgpt since it gives free access to many models ?

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
They provide no usable API. You can prove me wrong by providing relevant documentation. 
Any reverse engineered access methods are a won't do.

**Comment by infinit-X** [comment]
I see. I added this feature request because I saw (https://github.com/LegendPoet/SillyTavern-fix) has implemented flowgpt under its API. So i thought it would be a cool feature in the official build too.

**Comment by Cohee1207** [comment]
It uses webdriver with headless browser, there's no proper API. This is something that won't be implemented here.
