### ISSUE TITLE
[FEATURE_REQUEST] Option to toggle disable instruct formatting for example dialogue insertion 

### ISSUE THREAD

**Issue by Deathcow** [SillyTavern/SillyTavern#1881]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Poorly formatted dialogue examples or those that include characters other than {{user}} or {{char}}, can easily lead to poor prompt formatting, for example (here Jackson != {{user}}):

```
- Example dialogue of Kelly Bundy: 
[/INST] Kelly Bundy: "He'll be here. When my daddy says he'll do something he... no, that's my friend Marsha's daddy. But when my daddy puts his mind to something, he... no, that's Carolyn's daddy. Well, my daddy dear, he knows he's still number one, oh girls just want to have fun. No, that's Cyndi Lauper's daddy. Hmm."
Jackson: "What about your daddy?" [/INST] Kelly Bundy: "Obviously, he's not here."
```

This is not valid prompt formatting for Mistral and fixing the dialogue examples for each character card requires heavy manual editing.

It will break for other prompt formats too if the examples aren't meticulously crafted.

### Describe the solution you'd like

I'd like to be able to toggle disable instruct tags formatting for examples and have them be included just as contextual information as plain text. The example separator in combination with gradual push-out will give some measure of control about context.

### Describe alternatives you've considered

When Instruct Mode is on, warn users when creating example dialogues that don't start with {{user}}:, which don't alternate between {{user}} and {{char}} or include other characters besides {{user}} and {{char}}

I assume most don't even realize how they mess up their prompt

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

No

**Comment by ghost** [comment]
I often encounter such errors as well, so I have also summarized the possible situations where errors may occur. This may be helpful in pinpointing the issue.

---
Possible premises that may lead to this error:
```
1. The existence of dialogue templates with stop symbols (such as ChatML, Gemma, OpenChat, etc.).
2. The authors of character cards did not write example dialogues in the standard format (missing <START>, {{user}}, {{char}} in the example dialogues).
```

---
Error reproduction:
```
1. In the case of writing <START>, {{user}}, {{char}} completely, there will be two "<|im_end|>" at the purple-marked position.
2. If one {{user}} is missing, the blue-marked position will have less "<|im_end|>", "<|im_start|>user", and "Test User:".
3. If only <START> is missing, the black-marked position will have one less "<|im_end|>".
```
![2](https://github.com/SillyTavern/SillyTavern/assets/80347183/3425c3b3-f567-42c7-a30e-6bd3fae050f0)

---
The format I use for testing (common mistakes made by character card authors):
![3](https://github.com/SillyTavern/SillyTavern/assets/80347183/f4789082-4fd3-4b26-9ada-e44d67687ba6)

---
The correct format for the dialogue template should be:
```
<|im_start|>system\nMessage.<|im_end|>\n<|im_start|>user\nMessage.<|im_end|>\n<|im_start|>assistant\nMessage.<|im_end|>\n
```

Looks like:
```
<|im_start|>system
Message.<|im_end|>
<|im_start|>user
Message.<|im_end|>
<|im_start|>assistant
Message.<|im_end|>
```

`Sorry, I don't understand the code at all, so I can only present it this way.`

**Comment by Deathcow** [comment]
As an aside, this behavior also breaks context shifting/preservation during group chats

https://www.reddit.com/r/LocalLLaMA/comments/1b54y9g/ok_i_admit_sillytavern_is_a_great_way_to_test/kt4b5az/

In group chats examples should always be printed verbatim or instruct wrapping should be implemented differently.

**Comment by Spacellary** [comment]
This would be very useful.

**Comment by Spacellary** [comment]
So for staging users, thanks Cohee, the "Skip Example Dialogues Formatting" toggle in the Advanced Formatting tab seems to be the fix for this.

**Comment by Deathcow** [comment]
@Cohee1207 , thanks for the implementation. I gave it a whirl today with the release of 1.11.6 and seems to do exactly what I wanted to have. Awesome! I'll close this issue now.
