### ISSUE TITLE
[FEATURE_REQUEST] Add a command to enable or disable chat preset elements by Name

### ISSUE THREAD

**Issue by imesha10** [SillyTavern/SillyTavern#1888]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

I'm making a script that will enable and disable different parts of chat presets and come across a road block. I'm unable to enable or disable chat preset individual elements by using commands.
I am refering to these:
![image](https://github.com/SillyTavern/SillyTavern/assets/16441743/f98559b9-c60d-446c-ab55-d1d61ba5ee6d)

I have searched https://docs.sillytavern.app/usage/st-script/ and have found no command for that.

There are quite few uses for this:
- There are Chat presets that come with toggles for things like "fantasy", "realism", etc that you only enable one of. I want to have a button on the quick reply section called let's say "Fantasy" that will run commands that will enable and disable parts of the presets quickly at once.
- I can press a button to quick disable the Jailbreak specific components (some jb have multiple jb sections)

### Describe the solution you'd like

Add a new commad maybe called /chatpreset_enable and /chatpreset_disable that will do:

/chatpreset_enable presetname_1:
  - enables the preset item presetname_1 in the current chat preset, if does not exist do nothing.

/chatpreset_disable presetname_1:
  - disables the prest item presetname_1 in the current chat preset, if does not exist do nothing.

Example usage:

/chatpreset_enable jailbreak
/chatpreset_disable fantasy
/chatpreset_enable novel writer

### Describe alternatives you've considered

None

### Additional context

None

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

No

**Comment by Wolfsblvt** [comment]
No one did this? I wanna do this. I like this.

**Comment by Wolfsblvt** [comment]
Ignore this, I just realized we already have this, for quite a while.
Called `/setpromptentry`. Supports toggle, on and off, and you can specify one or more prompts.
