### ISSUE TITLE
[FEATURE_REQUEST] Conversational/Multi-round First Message

### ISSUE THREAD

**Issue by doloreshaze337** [SillyTavern/SillyTavern#1889]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Not really, no.

### Describe the solution you'd like

Ideally conversational/multi-round first message would allow a first message to emit multiple messages into the chat for each participant. For instance, take the below example of a conversational/multi-round first message:
```
{{user}}: Hi, how are you?
{{char}}: I'm good! How are you?
{{user}}: I'm good, though I need some help.
{{char}}: Oh? What do you need help with?
```
This would then emit four separate messages into the chat for {{user}} and {{char}} respectively, like so:
```
{{user}}: Hi, how are you?
<MESSAGE BREAK>
{{char}}: I'm good! How are you?
<MESSAGE BREAK>
{{user}}: I'm good, though I need some help.
<MESSAGE BREAK>
{{char}}: Oh? What do you need help with?
```
This would allow for more complex first messages that can set up a more complex scenario without having to overload {{char}}'s first message in the chat, as is currently the case where often a more complex scenario requires a first message that's 2-3x longer than the desired response length and includes {{user}}'s actions and dialogue (unless clever writing is included to clue the LLM into the scenario). This could also be expanded to include emitting system messages for providing further context without overloading {{user}}'s or {{char}}'s emitted messages.

### Describe alternatives you've considered

One possible way to emulate this without making such invasive changes (I took a look at how SillyTavern handles the first message and my idea above would completely break alternate greetings as they're currently implemented) would be to somehow tie example messages with specific greetings, or provide a second example message box that is tied to specific greetings. Doing so would allow you to place the extra conversation rounds within example messages, while still respecting alternate greetings. One problem with this approach would be that the conversation rounds won't show in the chat history as example messages currently aren't shown, which sucks but isn't the end of the world if you can write a good first message that summarises the example messages.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

No

**Comment by drago87** [comment]
Seams to be a nice addition
