### ISSUE TITLE
[BUG] Endless "generation" of a response in Scale _jwt

### ISSUE THREAD

**Issue by gh215** [SillyTavern/SillyTavern#1891]
### Environment

Self-Hosted (Bare Metal)

### System

Windows 10, Chrome 122

### Version

1.11.5

### Desktop Information

- Node.js - v20.5.0
- Spellbook's Scale
- gpt-4

### Describe the problem

When generating text with Scale _jwt, the text is only generated on the command line, and ST continues to "generate" in the text input field without outputting text in chat.

![image](https://github.com/SillyTavern/SillyTavern/assets/52608180/83011635-b64c-4a51-a6e0-2825e1e828f3)

It was good before the update...

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Fixed, pull and check please.

**Comment by gh215** [comment]
> Fixed, pull and check please.

Can't do now... will git pull and check tomorrow

**Comment by gh215** [comment]
DONE
