### ISSUE TITLE
[FEATURE_REQUEST]  An option to switch from different scenes would be nice

### ISSUE THREAD

**Issue by infinit-X** [SillyTavern/SillyTavern#1892]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

No

### Describe the solution you'd like

While chatting with the character if we could switch the scenes (Basically the background image associated with the respective scene and characters expression with attire; i.e  Office , Apartment etc.

I have seen this is implemented on miku.gg (another opensource project) and would be cool if ST also had that.

### Additional context

![Screenshot 2024-03-05 020722](https://github.com/SillyTavern/SillyTavern/assets/36435884/aac8c2a5-bb1a-4c17-91f1-8395860d7ec0)

Ref:miku.gg

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
You can do that by assigning STscript commands to Quick Reply extension buttons

**Comment by infinit-X** [comment]
Can you give the link to documentation pls. I don't know how to assign script commands.

And yes I think although the implementation exists in this way, many users don't use it or simply they don't know. So isn't it better to add that as a side panel or in the chatbox as switch scenes ?

**Comment by parsedone** [comment]
@infinit-X  when you load ST, on the front page you have the link to the documentation

> Confused or lost?
>  - click these icons!
> - Enter /? in the chat bar
> - [SillyTavern Documentation Site](https://docs.sillytavern.app/)
> - [Extras Installation Guide](https://docs.sillytavern.app/extras/installation/)

There you have the page "[STscript Language Reference](https://docs.sillytavern.app/usage/st-script/)".
You might be interested by 

> /bg (name) — finds and sets a background using fuzzy names matching. Respect the chat background lock state.


You can also type `/?` in your ST prompt to see the list of all slash commands available.


Using Quick Replies (QR) you can add buttons just above your prompt and you can create actions to switch background.
Like 1 button (QR) per background, or you could have only 1 button (QR) that displays a `/popup` to select a room an change the background accordingly.

_(I am not sure this is what you were looking for, I wish it helps)_

**Comment by infinit-X** [comment]
@parsedone Thank you very much for the information. 

Certainly! It’s interesting how we can achieve a similar scene-changing experience by altering the background without a direct scene implementation. But the scene implementation I was talking actually changes character's look (costumes etc) in expressions too. So also I have to mention that switching scenes, needs your character to have different sprite packs accordingly.

**Comment by Cohee1207** [comment]
Read a little further and find out that you can combine commands into batches
```
/bg Pool | /costume Bikini
```

**Comment by infinit-X** [comment]
Sure. I will update once I tried the above mentioned methods.

**Comment by infinit-X** [comment]
So yeah....

I tried to do what you said and it works.

**What i was able to do :**

- Change the background along with the Sprite 
- Auto execute a given scene (background+sprite) when I open the chat

But there is a problem. Whenever we switch scenes although the Background change and sprite change happens, AI doesn't know we switched the scene. I have tried all the **edit quick replies options** with manual injection too still AI doesn't know upon changing the scene. But when I given the AI {switch to Beach scene} first before any commands like /bg beach , AI understands that we are switching scenes but none of the background change or sprite change work this time. I will post some pics below.


![Screenshot 2024-03-06 003301](https://github.com/SillyTavern/SillyTavern/assets/36435884/585084a0-4549-4508-8575-f7dc4614c381) **AI have no idea we switched scenes**
![Screenshot 2024-03-06 003348](https://github.com/SillyTavern/SillyTavern/assets/36435884/19328684-66af-488e-b850-f1ccb9771866) **I switched the scene again but AI doesn't get any idea we are changing scenes**
![Screenshot 2024-03-06 003223](https://github.com/SillyTavern/SillyTavern/assets/36435884/a3429a8a-ce45-4ea3-82b7-1134d5da32d6)
![Screenshot 2024-03-06 003145](https://github.com/SillyTavern/SillyTavern/assets/36435884/e83803e1-351e-4bcf-ae3c-6311257c2d70)

**Comment by Cohee1207** [comment]
Easy. Pair that with `/inject` command to add a custom prompt blurb to indicate the scene.

**Comment by infinit-X** [comment]
I wil try that and update :)

**Comment by infinit-X** [comment]
Where am i going wrong ?

![Screenshot 2024-03-06 010329](https://github.com/SillyTavern/SillyTavern/assets/36435884/891f9f64-358c-448f-9904-58f3ca96d6e2)

It still doesn't detect and i have no idea what is inject ID tho

**Comment by Cohee1207** [comment]
It would be like that. Id can be whatever
```
/inject id=scene position=chat depth=4 Switch to Beach scene
```

**Comment by infinit-X** [comment]
Great It worked. Thank you very much @Cohee1207 @parsedone 

So I would close the feature request since the primary objective of the feature request is satisfied and it was already implemented.

But still workaround to play with different scenes in ST is not quite...that easy and If we could make switching scenes easily like what we have in miku.gg would be so cool in ST as well. 
Also the buttons won't appear when you starting a new chat. We have to go to **Quick replies > Chat Quick reply sets > +**

So anyone who want scenes in ST can refer to this since I didn't find any yt video or such guide for using different scenes in ST.

THX.
