### ISSUE TITLE
[FEATURE_REQUEST] claude-3

### ISSUE THREAD

**Issue by RendiHD** [SillyTavern/SillyTavern#1894]
### Have you searched for similar requests?

None

### Is your feature request related to a problem? If so, please describe.

Add claude-3😁

Thank you!

### Describe the solution you'd like

-

### Describe alternatives you've considered

-

### Additional context

-

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

Yes!

**Comment by WizardShawn** [comment]
I assume they are working on it, but I'm particularly interested in knowing whether the release version or the staging version will receive this feature first.

**Comment by Cohee1207** [comment]
Resolved by #1890
