### ISSUE TITLE
[BUG] SillyTavern is timing out KoboldCPP connection if prompt context takes too long

### ISSUE THREAD

**Issue by cmdrscotty** [SillyTavern/SillyTavern#1898]
### Environment

Self-Hosted (Bare Metal)

### System

Ubuntu 22.04

### Version

1.11.5

### Desktop Information

node.js v20.11.1
KoboldCPP 1.60
Branch: Release
model: koboldcpp/toppy-m-7b.Q5_K_M

### Describe the problem

SillyTavern is prematurely sending an Abort command to KoboldCPP if the prompt/response takes too long.

KoboldCPP is still processing prompt context OR generating response but hasn't sent it to SillyTavern yet. If this takes too long, SillyTavern will behave as if it has reached a timeout and send the abort command to Kobold and stop receiving information from KoboldCPP.

I was able to confirm this by modifying text-completion.js at line 65 to
```
async function abortKoboldCppRequest(url) {
    try {
        console.log('Aborting Kobold generation...');
//        const abortResponse = await fetch(`${url}/api/extra/abort`, {
//            method: 'POST',
//        });

//        if (!abortResponse.ok) {
//            console.log('Error sending abort request to Kobold:', abortResponse.status, abortResponse.statusText);
//        }
    } catch (error) {
        console.log(error);
    }
}
```

by doing this, I was able to set SillyTavern to still log the abortion, but avoid sending the abort command to KoboldCPP. I was able to see the CLI in Silly report it, but KoboldCPP was still processing.

![image_2024-03-05_141901289](https://github.com/SillyTavern/SillyTavern/assets/36492195/8c0120bf-ae0b-4a61-9107-a698f5f64fe7)

Issue is somewhat better if set for streaming, however if the prompt context processing takes too long, the system will time it out at that time and cease waiting for anything from KoboldCPP

There should either be no timeout set for waiting a response from the API (allow an infinite amount of time for KoboldCPP to complete it's processing) or a system prompt advising generation taking a very long time and ask if it should be aborted.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
> There should either be no timeout set for waiting a response from the API (allow an infinite amount of time for KoboldCPP to complete it's processing) or a system prompt advising generation taking a very long time and ask if it should be aborted.

This is exactly what is going on. 

https://github.com/SillyTavern/SillyTavern/blob/1cce26d631460cbf638182f1deef26086cc025e4/src/endpoints/backends/text-completions.js#L261

You are likely hitting a system-wide limit of how long a TCP connection could be waiting before it times out.

Consider: https://www.baeldung.com/linux/tcp-timeout

**Comment by cmdrscotty** [comment]
That's certainly an aspect I didn't consider.

i put the edit i made in text-completions.js back to original so that it handling the abortion like intended (at line 65)

I checked the defaults and they were set as:

```
****:~$ cat /proc/sys/net/ipv4/tcp_keepalive_time
7200
****:~$ cat /proc/sys/net/ipv4/tcp_keepalive_probes
9
****:~$ cat /proc/sys/net/ipv4/tcp_keepalive_intvl
75
```

so i updated them to:

```
****:~$ cat /proc/sys/net/ipv4/tcp_keepalive_time
72000
****:~$ cat /proc/sys/net/ipv4/tcp_keepalive_probes
127
****:~$ cat /proc/sys/net/ipv4/tcp_keepalive_intvl
72000 
```

But i still run into the same situation where SillyTavern will abort the generation and send the command to KoboldCPP to end it's process.

just for giggles I tried playing with the timeout variable  in text-completions.js (setting it to max 32-bit value)
```
timeout: 2147483647, // was 0
```

but none the less, still getting an error message reporting 'the user aborted' even though I didn't click or initiate any abortion
Aborting Kobold generation...
```
Endpoint error: AbortError: The user aborted a request.
    at abort (/mnt/md0/SD/pytorch2.1.2/SillyTavern/node_modules/node-fetch/lib/index.js:1462:16)
    at EventTarget.abortAndFinalize (/mnt/md0/SD/pytorch2.1.2/SillyTavern/node_modules/node-fetch/lib/index.js:1477:4)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:826:20)
    at EventTarget.dispatchEvent (node:internal/event_target:761:26)
    at abortSignal (node:internal/abort_controller:371:10)
    at AbortController.abort (node:internal/abort_controller:393:5)
    at Socket.<anonymous> (/mnt/md0/SD/pytorch2.1.2/SillyTavern/src/endpoints/backends/text-completions.js:225:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'aborted'
}

```

**Comment by Cohee1207** [comment]
A user here could mean the HTTP client. Then see if your browser aborts the connection and has any sort of timeouts to configure.

**Comment by cmdrscotty** [comment]
darn you HaProxy 🤣

Found it, HaProxy was generating a 504 timeout code if it took longer than 60000ms for the server to respond.
I use HaProxy for a bunch of routing functions within my intranet since I can easily just set up a dns record to go to HaProxy, then have that route to the computer:port needed.

tested it by connecting via IP, worked just fine, and even found via devtools that the generation took 3mins to complete.
![image_2024-03-05_153711184](https://github.com/SillyTavern/SillyTavern/assets/36492195/532c62c4-4afa-4f3b-9b61-1bbf190e82d6)

updated the HaProxy settings and problem solved 🤣
