### ISSUE TITLE
[BUG] Proxy stream error

### ISSUE THREAD

**Issue by MisterTwelve** [SillyTavern/SillyTavern#1899]
### Environment

Android (Termux)

### System

Android 9 (old phone, I know) / all browsers

### Version

SillyTavern 1.11.5 'staging' (3b990801)

### Desktop Information

- node.js 21.6.2-1
- Claude
- staging
- Any

### Describe the problem

Two issues:
1. Whenever changing any setting (prompts, character, proxy, sending a message) the page will become unresponsive for up to a minute. Possibly because my phone is old, but I never had this issue with the old dev branch, which I (as of two hours ago spent trying to fix this myself) just switched from to staging. I updated Termux, did gitpull, npm install, made sure nodejs was up to date, everything in the guides.

2. [MAIN PROBLEM] Getting streaming errors on all proxies I try, no matter which Claude version I pick. No errors appear in Termux, only on the SillyTavern UI.

### Additional info

{
  "message": "Got mysterious error chunk: validationexception",
  "stack": "Error: Got mysterious error chunk: validationexception\n    at SSEStreamAdapter.processAwsMessage (/home/ec2-user/oai-reverse-proxy/src/proxy/middleware/response/streaming/sse-stream-adapter.ts:77:32)\n    at SSEStreamAdapter._transform (/home/ec2-user/oai-reverse-proxy/src/proxy/middleware/response/streaming/sse-stream-adapter.ts:121:30)\n    at SSEStreamAdapter.Transform._write (node:internal/streams/transform:171:8)\n    at writeOrBuffer (node:internal/streams/writable:564:12)\n    at _write (node:internal/streams/writable:493:10)\n    at SSEStreamAdapter.Writable.write (node:internal/streams/writable:502:10)\n    at AWSEventStreamDecoder.ondata (node:internal/streams/readable:1007:22)\n    at AWSEventStreamDecoder.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushObjectMode (node:internal/streams/readable:536:3)",
  "lastEvent": "{\n  \"headers\": {\n    \":exception-type\": {\n      \"type\": \"string\",\n      \"value\": \"validationException\"\n    },\n    \":content-type\": {\n      \"type\": \"string\",\n      \"value\": \"application/json\"\n    },\n    \":message-type\": {\n      \"type\": \"string\",\n      \"value\": \"exception\"\n    }\n  },\n  \"body\": {\n    \"0\": 123,\n    \"1\": 34,\n    \"2\": 109,\n    \"3\": 101,\n    \"4\": 115,\n    \"5\": 115,\n    \"6\": 97,\n    \"7\": 103,\n    \"8\": 101,\n    \"9\": 34,\n    \"10\": 58,\n    \"11\": 34,\n    \"12\": 109,\n    \"13\": 101,\n    \"14\": 115,\n    \"15\": 115,\n    \"16\": 97,\n    \"17\": 103,\n    \"18\": 101,\n    \"19\": 115,\n    \"20\": 58,\n    \"21\": 32,\n    \"22\": 102,\n    \"23\": 105,\n    \"24\": 110,\n    \"25\": 97,\n    \"26\": 108,\n    \"27\": 32,\n    \"28\": 97,\n    \"29\": 115,\n    \"30\": 115,\n    \"31\": 105,\n    \"32\": 115,\n    \"33\": 116,\n    \"34\": 97,\n    \"35\": 110,\n    \"36\": 116,\n    \"37\": 32,\n    \"38\": 99,\n    \"39\": 111,\n    \"40\": 110,\n    \"41\": 116,\n    \"42\": 101,\n    \"43\": 110,\n    \"44\": 116,\n    \"45\": 32,\n    \"46\": 99,\n    \"47\": 97,\n    \"48\": 110,\n    \"49\": 110,\n    \"50\": 111,\n    \"51\": 116,\n    \"52\": 32,\n    \"53\": 101,\n    \"54\": 110,\n    \"55\": 100,\n    \"56\": 32,\n    \"57\": 119,\n    \"58\": 105,\n    \"59\": 116,\n    \"60\": 104,\n    \"61\": 32,\n    \"62\": 116,\n    \"63\": 114,\n    \"64\": 97,\n    \"65\": 105,\n    \"66\": 108,\n    \"67\": 105,\n    \"68\": 110,\n    \"69\": 103,\n    \"70\": 32,\n    \"71\": 119,\n    \"72\": 104,\n    \"73\": 105,\n    \"74\": 116,\n    \"75\": 101,\n    \"76\": 115,\n    \"77\": 112,\n    \"78\": 97,\n    \"79\": 99,\n    \"80\": 101,\n    \"81\": 34,\n    \"82\": 125\n  }\n}"
}

Error: Got mysterious error chunk: validationexception
    at SSEStreamAdapter.processAwsMessage (/home/ec2-user/oai-reverse-proxy/src/proxy/middleware/response/streaming/sse-stream-adapter.ts:77:32)
    at SSEStreamAdapter._transform (/home/ec2-user/oai-reverse-proxy/src/proxy/middleware/response/streaming/sse-stream-adapter.ts:121:30)
    at SSEStreamAdapter.Transform._write (node:internal/streams/transform:171:8)
    at writeOrBuffer (node:internal/streams/writable:564:12)
    at _write (node:internal/streams/writable:493:10)
    at SSEStreamAdapter.Writable.write (node:internal/streams/writable:502:10)
    at AWSEventStreamDecoder.ondata (node:internal/streams/readable:1007:22)
    at AWSEventStreamDecoder.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushObjectMode (node:internal/streams/readable:536:3)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
We do not provide support for reverse proxy users.
