### ISSUE TITLE
[BUG] Swiping Generation Bug

### ISSUE THREAD

**Issue by Kingmiami** [SillyTavern/SillyTavern#1905]
### Environment

Self-Hosted (Bare Metal)

### System

Safari 16, Firefox 123

### Version

1.11.5

### Desktop Information

Node.js 18.17.1
OpenAI/Claude
Release/Staging, same result

### Describe the problem

When swiping to the left or right of an already completed message, SillyTavern will start generating anyway. Nothing pops up, but the send icon turns to this ![Screenshot 2024-03-06 231855](https://github.com/SillyTavern/SillyTavern/assets/49174731/a8f70294-9b6e-4b5a-ab3e-080356573aa5), "invalid json response" error appears in the terminal, and it contributes to rate limits and I would imagine cost too. Seems to only pop up past ten messages in a chat. Also tends to delete messages if you're in the middle of editing.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Disable automatic summaries.

**Comment by Kingmiami** [comment]
> Disable automatic summaries.

Thank you
