### ISSUE TITLE
[BUG] Character definitions in group chat's with indendations (spaces or tabs) at the beggining has the indentation removed.

### ISSUE THREAD

**Issue by imesha10** [SillyTavern/SillyTavern#1908]
### Environment

Self-Hosted (Bare Metal)

### System

Windows 11, Chrome

### Version

SillyTavern 1.11.5 'HEAD' (8cf1671d)

### Desktop Information

Node JS: v18.15.0
Generation: OpenAI reverse proxy
Branch: Staging
Model: any gpt version

### Describe the problem

Character definitions in group chat's with indendations (spaces or tabs) at the beggining has the indentation removed.
This only happens to the first line.
This does not affect the User Defenition.
I have only tested this on group chats.
Using a newline at the start also does not work as it's removed.

Character Profile Example:
```
    <John>
    Read the following YAML section and understand John's character. His information is only known to himself unless said or seen. His character changes as the story goes on.
    ``` yaml
    ...... (rest of the definiton ommited)
```

What's shown in the console and what is sent:
```
    '<John>\n' +
    "    Read the following YAML section and understand John's initial character. His information is only known to himself unless said or seen. His character changes as the story goes on.\n" +
    '    ``` yaml\n' +
    '    General:\n' +
```

### Additional info

No perticular error.

The way I get around this is just have it fetch a random variable in the first line which seems to work.
`{{getvar::testas23}}`

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Wolfsblvt** [comment]
Trimming contents like character descriptions, scenario and more is actually intended.  
At least it's explicitly written in code.

Your work-around is valid. I am not sure this *should* be fixed, as its not really a bug.
@Cohee1207 correct?

**Comment by imesha10** [comment]
Closing since it's no longer a problem for me and this is stale.
