### ISSUE TITLE
[FEATURE_REQUEST] Supports offline Windows TTS

### ISSUE THREAD

**Issue by DDXDB** [SillyTavern/SillyTavern#1911]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Everything I see in system TTS at SillyTavern right now is [online]
Windows11 seems to come with a WindowsTTS for offline use

### Describe the solution you'd like

Can I call Windows11's offline TTS?

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
System TTS is limited to whatever is visible to the JavaScript Speech Synthesis API. Try to see in the Edge browser if it exposes these engines to clients.
