### ISSUE TITLE
[BUG] Character Swapping Issue with Custom Chat Completion

### ISSUE THREAD

**Issue by KyuubiYoru** [SillyTavern/SillyTavern#1914]
### Environment

Self-Hosted (Bare Metal)

### System

Windows 10, Waterfox G6.0.9

### Version

1.11.5

### Describe the problem

When using the Chat Completion with Custom (OpenAI-compatible) backend, LM Studio v0.2.16 as back-end, there seems to be a character swapping bug. The responses generated for the AI character are appropriate as my responses and when using the "impersonate" function, the responses are appropriate for the AI character.

When i use oobabooga with the same model and Character everything works as intended.

### Additional info

![image](https://github.com/SillyTavern/SillyTavern/assets/33806787/27dcdcaf-cb3d-4510-82bc-a83c1cee512d)
![image](https://github.com/SillyTavern/SillyTavern/assets/33806787/4241e504-dae4-4001-a119-3f402ba52ce0)
![image](https://github.com/SillyTavern/SillyTavern/assets/33806787/ba532b71-5cc1-4aec-9d6a-4a0c1a0e09a9)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Use LM Studio with Text Completion API, leave Type at Default (oobabooga). Using it with Chat Completion will lead to subpar experience.
