### ISSUE TITLE
[FEATURE_REQUEST] Put pre-generated images into chat

### ISSUE THREAD

**Issue by Toroidal-meow** [SillyTavern/SillyTavern#1916]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

No

### Describe the solution you'd like

I would like to be able to insert pre-made images into chat window itself, in the same way RisuAI does with "Assets".

Note that this is different from Custom Character Expressions, since those images are transient. The requested feature would instead insert the images within the text so they would stay permanently.

Example:

`[Date: 2023-05-12 | Time: AM 07:00 | Location: Jisoo's Home | Jisoo's current outfit: <img="sleepwear/polka dot pajama sheer shorts">]`

Result:

![image](https://github.com/SillyTavern/SillyTavern/assets/126524509/e9815a6e-ed40-48aa-911a-241986877069)

### Describe alternatives you've considered

Perhaps a separate window for images could appear next to the chat window? These windows would stay permanent, and travel with the chat log as it scrolls up.

### Additional context

Currently, the only way to insert images into chat is to have the images generated by Stable Diffusion. However, this sacrifices the level of control for the bot's behavior. If the bot creator already has image assets created, it would be good to have the option to have them appear on chat window.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

**Comment by Cohee1207** [comment]
You can use Markdown images to insert images you uploaded into ST's public/user folder, like this `![alt-text](/user/Char/image.png)`. I'm not a big fan of the idea of embedding images into the card because it pushes the limits of the format in unintended ways and will cause issues, PNG is not suitable for storing hundreds of megabytes of base64 encoded metadata.

**Comment by Toroidal-meow** [comment]
![alt-text](/user/Char/image.png)
This works! Thank you.
