### ISSUE TITLE
[Feature Request] AI-powered Character Generation Using Description Input.

### ISSUE THREAD

**Issue by maxime-fleury** [SillyTavern/SillyTavern#192]
**Is your feature request related to a problem? Please describe.**

**Creating a** well-developed and interesting **character**  can be **a challenging** and **time-consuming task**. Often, most people struggle to come up with unique personality traits and prompts that make their characters stand out.

**Describe the solution you'd like**

I would like to suggest adding a feature to SillyTavern that would **allow users** to **create characters** quickly and easily. This feature could be a **textarea field** where users could **input** a detailed **description** of the **character** they want to create, including personality traits, backstory, and other relevant information.

Once the user has entered the description, SillyTavern could utilize the **AI to generate** a unique and **well-developed character** based on the input provided. The user could then have the option to **regenerate the character** or make further improvements before saving it.

This feature would be a valuable addition to SillyTavern, **making it easier for us to create** compelling **characters**.

**Comment by RossAscends** [comment]
You can do this already by typing in such a description into ChatGPT and asking it to create a character profile using whatever character format you prefer (boostyle, w++, etc)

**Comment by maxime-fleury** [comment]
It can't make nsfw characters

**Comment by ComproLoper** [comment]
> 

It very much can, ChatGPT "can't" do ERP, yet SillyTavern has absolutely no problem with it, it is all about using the correct prompt, take a look at the prompts Tavern uses, you can see them clicking on the API settings button (top left), I have only evern needed the "NSFW Toggle", nothing else.
Here are the prompts I use for an app I am developing as a personal project, it is incomplete, but it may give you the correct idea on how to approach this: [](https://pastecode.io/s/hq0g0040)
