### ISSUE TITLE
[FEATURE_REQUEST] Support for Claude 3 with Claude API

### ISSUE THREAD

**Issue by Cosmoline1986** [SillyTavern/SillyTavern#1928]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Been a bit since Claude 3 was released, but it's only accessible through OpenRouter. Having it natively through Claude would be nice.

### Describe the solution you'd like

Add claude-3-opus-20240229 and claude-3-sonnet-20240229.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

No

**Comment by Cohee1207** [comment]
Duplicate #1894 https://github.com/SillyTavern/SillyTavern/pull/1890
