### ISSUE TITLE
[FEATURE_REQUEST] Support for Gemini 1.5 Pro in MakerSuite

### ISSUE THREAD

**Issue by Memebread** [SillyTavern/SillyTavern#1933]
### Have you searched for similar requests?

Yes

### Describe the solution you'd like

It'd be nice to test out the model's efficiency when it comes to RP and general coherency.

### Additional context

I know that right now it's hard for most people to get access to Gemini 1.5 right now but I feel like it'd be good to atleast have the option there for those who do have access.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

None

**Comment by infinit-X** [comment]
+1

I think it is still only available for AI studio

**Comment by Cohee1207** [comment]
Links to API docs?
It's not here: https://ai.google.dev/models/gemini

**Comment by infinit-X** [comment]
Currently only a preview in AI studio.

https://ai.google.dev/docs

**Comment by ghost** [comment]
I can use it in Studio, but when I use curl https://generativelanguage.googleapis.com/v1beta/models/?key=API command, I don't see it. I guess you can't use it from API yet.

**Comment by QingyeSC** [comment]
Hope it does, I have access to 1.5 too, can't wait to try it out in SillyTavern!

**Comment by Memebread** [comment]
![Screenshot 2024-04-01 174433](https://github.com/SillyTavern/SillyTavern/assets/72225891/85768d41-7673-4069-a31d-c09014684fd1)
If this helps at all.

**Comment by Memebread** [comment]
Also it's called "gemini-1.5-pro-latest" in the code if that helps at all when it becomes usable in the API.

**Comment by Cohee1207** [comment]
Gemini 1.5 pro is there since
