### ISSUE TITLE
[FEATURE_REQUEST] Support KoboldCPP Authentication

### ISSUE THREAD

**Issue by jobobby04** [SillyTavern/SillyTavern#1934]
### Have you searched for similar requests?

Yes

### Describe the solution you'd like

Authentication like a OpenAI token has been added in the latest release: https://github.com/LostRuins/koboldcpp/releases/tag/v1.61.2

I tend to password protect my server and adding support for this would allow me to protect my text api endpoint.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

No

**Comment by Cohee1207** [comment]
This is already done but not yet released: https://github.com/SillyTavern/SillyTavern/commit/acf36b6107c65a056c95b6f66a7ec2be68ec4f85
