### ISSUE TITLE
[BUG] {{random:1,2,3}} and {{random::1::2::3}} conflict with each other

### ISSUE THREAD

**Issue by AnonCardMaker** [SillyTavern/SillyTavern#1940]
### Environment

Self-Hosted (Bare Metal)

### System

Firefox 122

### Version

1.11.6

### Describe the problem

The same message including an instance of both {{random:1,2,3}} and {{random::1::2::3}} will result in only the latter being resolved.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Pull the following commit and try again: https://github.com/SillyTavern/SillyTavern/commit/76cde592ade8cfa061f52a35165ea3b3c2d34100

**Comment by Wolfsblvt** [comment]
Should be fixed with the latest changes and the new **1.11.7** release.
