### ISSUE TITLE
[BUG] <title>Error rendering template

### ISSUE THREAD

**Issue by blueswolf** [SillyTavern/SillyTavern#1941]
### Environment

Cloud Service (Static)

### System

IPHONE15 SAFARI AND CHROME

### Version

1.11.6

### Describe the problem

Error rendering templateCheck the DevTools console formore information.
Error rendering template.the bug still there on iphone 15 .I 'm in china,MY ST(1.11.6) running on vps in USA, I access it from my phone with safari and chrome，Error rendering template……BUT when i run ST server on my own PC,and use an intranet penetration software(on PC) to help my mobile phone access the ST server, I can avoid this problem. Is it a problem caused by long distance communication?or someting about network?Android phones don't seem to have this problem, they are also CHROME
![4f4818c2549c388eaaa1ad6d958f023](https://github.com/SillyTavern/SillyTavern/assets/160055096/18b05918-fd23-4e12-ad32-b4b8bd9e2f2a)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by blueswolf** [comment]
I heard that returning to 1.11.5 can solve this problem. Do some modules or plug-ins in the new version use any earlier code?

**Comment by blueswolf** [comment]
There is currently a solution: after entering the ST access password, close the browser process, reopen it, and enter it again, and the problem will disappear. Is it a password verification time point that blocks the rendering process?

**Comment by Cohee1207** [comment]
The password should be asked before rendering the first HTML page and even attempting to load a script that would render templates. I haven't heard of anyone having the same problem.

**Comment by Cohee1207** [comment]
This is of course true if you use the built-in server basic auth, not some external solution.

**Comment by blueswolf** [comment]
I set the password in congfig.yaml. In a discord community, when I posted a question, I met two people who had the same problem as me. The above method was discovered by them.

**Comment by blueswolf** [comment]
![image](https://github.com/SillyTavern/SillyTavern/assets/160055096/b201e78c-0440-4150-9dd1-7b5f1eeb8745)
Did I write something wrong?

**Comment by Cohee1207** [comment]
I found the same issue with Safari when using both simple auth and CSRF protection after forcefully killing the process. The working solution turned out to be pretty dumb: forcefully reload the page when the settings fail to load, nothing else worked. Here's a pointer to commit in staging: https://github.com/SillyTavern/SillyTavern/commit/a15ab86fd06738e3bf74ad4f3967657ac84c6c31

**Comment by blueswolf** [comment]
Thanks for your help, I'll install STAGING and give it a try.
