### ISSUE TITLE
[FEATURE_REQUEST] Long Load times

### ISSUE THREAD

**Issue by Zeralun** [SillyTavern/SillyTavern#1944]
### Have you searched for similar requests?

None

### Is your feature request related to a problem? If so, please describe.

Everytime i make a new message in the chat the time to generate gets longer and longer its going from 4 sec to 59 sec and then further on it takes forever.
![Anmerkung 2024-03-19 121102](https://github.com/SillyTavern/SillyTavern/assets/98699004/dfdfbc80-fb20-4237-9667-971b563a1a26)

### Describe the solution you'd like

Chat without 5 min + Response time 

### Priority

High (The app does not function without it)

### Is this something you would be keen to implement?

None

**Comment by Zeralun** [comment]
i have a 40480 and a i5 13600k

**Comment by Cohee1207** [comment]
Specify the actual backend, model, and loader used, as well as the API connection method and settings.

**Comment by Zeralun** [comment]
i use oobabooga/text-generation-webui 
I used the text completion in silly tavern 
i used the video from the youtube channel Aitrepreneur


![Anmerkung 2024-03-19 133828](https://github.com/SillyTavern/SillyTavern/assets/98699004/709856bd-d194-4ff8-acd8-a592f1bb1f4a)

**Comment by Zeralun** [comment]
I just reinstalley everything ^^"
