### ISSUE TITLE
[BUG] Error rendering template

### ISSUE THREAD

**Issue by sndkcd** [SillyTavern/SillyTavern#1947]
### Environment

Other (Specify below)

### System

ios chrome

### Version

1.11.6

### Describe the problem

I get this error every time I run my sillytavern in a colab. I closed the browser and tried again, but the error still occurred. 
![IMG_2629](https://github.com/SillyTavern/SillyTavern/assets/146307817/15a6c9f0-a2e4-4499-ad3b-cd4d9bac2c86)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Try switching to staging. Related: https://github.com/SillyTavern/SillyTavern/issues/1941

**Comment by sndkcd** [comment]
How do I switch to staging? I don't know much about colab.

**Comment by Cohee1207** [comment]
The only official colab provided by SillyTavern developers is for Extras API: https://colab.research.google.com/github/SillyTavern/SillyTavern/blob/release/colab/GPU.ipynb

Anything else is unofficial, so I'm not able to provide help for it. Ask the creator of a particular colab for support.

**Comment by Cohee1207** [comment]
Should be fixed.
