### ISSUE TITLE
[FEATURE_REQUEST] Groq API

### ISSUE THREAD

**Issue by ghost** [SillyTavern/SillyTavern#1952]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Groq offers a free API for Mixtral, and rate limits are very generous right now (14,400 requests per day). While it could be used as a custom OpenAI-compatible API, it would be nice to have it.

### Describe the solution you'd like

Adding Groq API to the Chat Completion list.

### Describe alternatives you've considered

It works with the custom OpenAI compatible chat completion. But you need to disable requesting token probabilities.

### Additional context

[Groq API](https://console.groq.com/docs/quickstart)

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
https://github.com/SillyTavern/SillyTavern/commit/181b5aff97beb044547c98dcd2c2e516460a2481

**Comment by Cohee1207** [comment]
Released.
