### ISSUE TITLE
After installing on my personal VPS, I encountered this prompt. My website can be accessed, but it cannot be opened using my server's IP + port 8000. What could be the reason for this?

### ISSUE THREAD

**Issue by xkdopod** [SillyTavern/SillyTavern#1953]
After installing on my personal VPS, I encountered this prompt. My website can be accessed, but it cannot be opened using my server's IP + port 8000. What could be the reason for this?

**Comment by xkdopod** [comment]
After installing on my personal VPS, I encountered this prompt. My website can be accessed, but it cannot be opened using my server's IP + port 8000. What could be the reason for this?
![7780](https://github.com/SillyTavern/SillyTavern/assets/35407030/1c134b94-d998-4162-a6cd-c25a1c1be101)

**Comment by Teashrock** [comment]
@xkdopod 
That means you should open config.yaml and enable `listen: true`. After that, you'll either need to enable whitelist, or login/pass authentication.

**Comment by xkdopod** [comment]
Brother, I changed the configuration file. I set it to true, but it still doesn't work. I also replaced the whitelist "127.0.0.1" with my IP, but it still doesn't work. Can anyone help?
![47](https://github.com/SillyTavern/SillyTavern/assets/35407030/9aa2ccfc-a302-4d16-bd4f-76a4b760ad71)

**Comment by QingyeSC** [comment]
Maybe you can change "WhitelistMode" to "true" and "whitelist" to "0.0.0.0", and then set "BasicauthMode" to "true" as well, and you can set the username and password to ensure security.

**Comment by cmdrscotty** [comment]
these are the values i have set in mine that made it work:

```
# -- NETWORK CONFIGURATION --
# Listen for incoming connections
listen: true
# Server port
port: 8000
# Toggle whitelist mode
whitelistMode: true
# Whitelist of allowed IP addresses
whitelist:
  - 127.0.0.1
  - 192.168.0.0/22
  - 192.168.4.0/24
# Toggle basic authentication for endpoints
basicAuthMode: false
```
This allows me to connect to it from either my local net (192.186.0.0/22) or my vpn net (192.168.4.0/24), or localhost (127.0.0.1) since i run this on a linux server and then connect to it

**Comment by sirius422** [comment]
Please check your firewall setting. Even if your client IP is not in the whitelist, you should see a webpage like this:

<b>Forbidden</b>: Connection attempt from <b>YOUR IP ADDR</b>. If you are attempting to connect, please add your IP address in whitelist or disable whitelist mode in config.yaml in root of SillyTavern folder.

Or you can just make sillytavern listen to loaclhost with basicAuth and reverse proxy it using caddy/nginx with HTTPS. this should be a common pratice.
