### ISSUE TITLE
[FEATURE_REQUEST] Disable/toggle codeblock wrapping of attached files

### ISSUE THREAD

**Issue by Amanoki** [SillyTavern/SillyTavern#1954]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Currently, when sending a message with a text file using "Attach a file", the file content will be automatically wrapped in a ``` codeblock.
In some cases this could cause problems:
1. I often use "Attach a file" as a convenient way to insert long text, or I directly write prompts inside the files. I hope they can be inserted seamlessly into the context as plain text and not recognized as files/code. When they are wrapped in ```, it may cause the model to mistake them for coding material or other special purposes, or it may break the model's output formatting.
2. For cases where the file content already contains codeblocks, sometimes the model confuses the beginning and end of the codeblocks as shown below:
![111111](https://github.com/SillyTavern/SillyTavern/assets/46240634/07b70e93-f460-449a-8c47-e7326d84064f)
(BTW, why is the Tokens "-1" here?)

### Describe the solution you'd like

It would be nice to have a switch to disable/toggle/change the auto ``` wrapping when attaching files. Similar to the existing `Wrap in Quotes (Wrap entire user message in quotes before sending. Leave off if you use quotes manually for speech.)` option.

### Describe alternatives you've considered

I've tried using Regex to replace backticks with empty, but it didn't work for backticks that wrap the file content. And since this would eliminate any intentional codeblocks in the message, this is not an ideal solution.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

None

**Comment by Amanoki** [comment]
I see that the updated version has removed the default backticks wrapping, thank you!
Not sure if you plan to add a toggle switch for re-enabling backticks, I believe the wrappers would still be benificial for other cases where user does want the files to be recognize as files.

I have some further suggestion about customization for different use cases:
1. Have a setting to customize file content wrappers, so I can set it as none, or any customizable text such as backticks or tags like `<doc></doc>` (which would be useful for reference the file in later chats by mentioning the tag).
2. OR better, allow the file to be inserted in the middle of the user message instead of just the beginning. This would grant more flexible control for the presentation of the inserted content, so I can add whatever wrappers that fit the current case directly in the message, provide context before the inserted content to tell the model what this piece of text is and what to do with it, etc.

For now the removal of backticks works perfectly for the situations I initially described. So these are additional suggestions for your consideration. Thanks again!

**Comment by Cohee1207** [comment]
Check this: https://docs.sillytavern.app/usage/core-concepts/data-bank/#data-bank
It allows setting a template for inserted file chunks and seems more flexible than plain file attachments.
This refers to a pre-release version that is currently live in staging.

**Comment by Amanoki** [comment]
Thanks for the reply! I have tried the Data Bank on staging branch, it's awesome and absolutely fulfills some of my other needs.

Though I think my request is still more focused on file attachments. I usually frequently upload different files or upload files that are constantly updating (like constantly updating code files), it would be more convenient to upload them in the chat than to open the Data Bank. Unfortunately the Injection Template seems to only support Data Bank files and not Message attachments.

As a side note I usually need to insert the full file text, so vectorization isn't really necessary (the template would require enabling it). But this may not be a problem since I can set a large size threshold to avoid file splitting.

Macro is one solution I've considered. Though I was thinking about using it in the message, such as creating a unique {{macro}} each time a file is uploaded, and automatically inserting it into the message, and then it can be placed in any position in the message. But I am not very familiar with macros, from what I understand, micros would appear as actual text once the message is sent, which may get the interface to lag if it's big (one reason I prefer file uploads for big text). Other than that, macros seem quite close to what I'm looking for.

It would also be great for message attachments to have a template like the Data Bank has. A template might not be as flexible as micros directly in the message but it would still be helpful for setting custom file content wrappers.
