### ISSUE TITLE
[BUG] <cannot move the sprite expression of characters, even ig move ui was triggered

### ISSUE THREAD

**Issue by euphobie** [SillyTavern/SillyTavern#1956]
### Environment

Self-Hosted (Bare Metal)

### System

w11

### Version

SillyTavern 1.11.6 'staging' (76cde592)

### Desktop Information

-branch: stagging

### Describe the problem

i can't move a sprite of a character expression, despite the fact i can move the chatbox, and character card

https://github.com/SillyTavern/SillyTavern/assets/164052063/1b0dcf48-f1f2-409d-86e3-b73893aa7b56

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
I cannot reproduce this on my end. Do you use any extensions or custom CSS that changes the layering indices of UI elements? Most notably VRM and Live2d, try disabling them if you do.
