### ISSUE TITLE
[BUG] <Chinese name REGEX export named file is underlined>

### ISSUE THREAD

**Issue by blueswolf** [SillyTavern/SillyTavern#1960]
### Environment

Self-Hosted (Bare Metal)

### System

WINDOWS

### Version

1.11.6

### Describe the problem

Chinese name REGEX export named file is underlined
![image](https://github.com/SillyTavern/SillyTavern/assets/160055096/676ce94d-32d1-405b-b3b8-97e4481464b6)
![image](https://github.com/SillyTavern/SillyTavern/assets/160055096/210aa84e-9873-4d02-922a-3846917f2400)

Default export long file name error：：Export file has no extension name
![image](https://github.com/SillyTavern/SillyTavern/assets/160055096/f79797df-0814-4786-af30-9ac7ad161581)
![image](https://github.com/SillyTavern/SillyTavern/assets/160055096/089d59fe-7f33-4731-96c0-32113a5ee181)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Fixed in release.
