### ISSUE TITLE
a specific sillytavern character is not responding.[BUG] <title>

### ISSUE THREAD

**Issue by icarokizz** [SillyTavern/SillyTavern#1961]
### Environment

Self-Hosted (Bare Metal)

### System

chrome

### Version

SillyTavern 1.11.6 'release' (f121d1da)

### Describe the problem

I've been playing with a character for two days but out of nowhere he stopped responding. Is there any specific reason for this?

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Provide more information. API? Model? Settings?

**Comment by icarokizz** [comment]
![Screenshot_20240324-223330](https://github.com/SillyTavern/SillyTavern/assets/164784796/fbff26a3-445b-41a0-8920-deb0e7f0b303)


now it's not just one bot it's everyone, if you can help me I'll be grateful🙏🙏🙏

**Comment by Cohee1207** [comment]
Check that you got money on Claude account. It's not free.
