### ISSUE TITLE
[BUG] Potential issue (with a fix) when converting a char to user persona

### ISSUE THREAD

**Issue by sinlorekain** [SillyTavern/SillyTavern#1966]
### Environment

Self-Hosted (Bare Metal)

### System

Win 10 22H2, Chrome Latest

### Version

SillyTavern 1.11.6 'release' (d6168fda)

### Describe the problem

If you attempt to convert the character that has a ' single quote sign (example M'aiq the Liar) - it will break the public\script.js line 5557 resulting in a constant cogwheel screen.

### Additional info

Solution:
Replace the line:
 `    $(#user_avatar_block .avatar-container[imgfile='${user_avatar}']).addClass('selected');`
With:
`    $(#user_avatar_block .avatar-container[imgfile="${user_avatar}"]).addClass('selected');`
This will ensure that any charater that named like that can be renamed. 
This doesn't happen outside actual converts so, yeah.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by sinlorekain** [comment]
Related console output without a quickfix applied.

`Uncaught Error: Syntax error, unrecognized expression: #user_avatar_block .avatar-container[imgfile='M'aiq the Liar (Persona).png']
    at se.error (jquery-3.5.1.min.js:2:13606)
    at se.tokenize (jquery-3.5.1.min.js:2:21617)
    at se.select (jquery-3.5.1.min.js:2:22444)
    at Function.se [as find] (jquery-3.5.1.min.js:2:7089)
    at S.fn.init.find (jquery-3.5.1.min.js:2:25014)
    at S.fn.init (jquery-3.5.1.min.js:2:25503)
    at S (jquery-3.5.1.min.js:2:1024)
    at highlightSelectedAvatar (script.js:5557:5)
    at getSettings (script.js:5859:9)
    at async firstLoadInit (script.js:837:5)`

**Comment by Cohee1207** [comment]
I applied your solution, it makes sense.

**Comment by sinlorekain** [comment]
Thanks, happy to help.
