### ISSUE TITLE
[FEATURE_REQUEST] Change how summarize uses chat completion mode

### ISSUE THREAD

**Issue by allo-** [SillyTavern/SillyTavern#1980]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

When using the chat completion API, the summarize feature breaks on many models and just generates a bot post instead of a summary. I think this is related to the way chat completion works, and possibly due to inserting a system role post after a lot of user/assistant dialog.

### Describe the solution you'd like

Most models are pretty good at summarizing text if you instruct them correctly. I would suggest that the summarize addon should not inject a message into the chat, but create a summarize request like this:

```
[
{"role": "system", "content": "You are an AI that summarizes dialogs provided by the user."}
{"role": "user", "[CHATLOG]"}
]
```

with CHATLOG formatted as a dialog:
```
Bot: *The bot enters the stage and says* "Hi User!"
User: "Hello! What's up?"
Bot: ...
```

This way the summarization could probably be even better than in text completion mode.

### Describe alternatives you've considered

Sending the "[Pause your roleplay and summarize]" request with the "user" role instead of the "system" role may result in a response that is equivalent to text completion mode.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

No

**Comment by Cohee1207** [comment]
Try the updated prompt builder for summarization in 1.11.7

**Comment by allo-** [comment]
The raw modes work well for me. Thanks for the quick implementation.
