### ISSUE TITLE
[FEATURE_REQUEST] Gemini Repetition Fix

### ISSUE THREAD

**Issue by Memebread** [SillyTavern/SillyTavern#1984]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Gemini is well known for being highly repitive and repeating the same line of text from a previous message (might be a personal issue but I haven't looked too far into it)

### Describe the solution you'd like

I think it'd be a great idea to probably add something that removes a already present line of text that has appeared in previous messages.

### Describe alternatives you've considered

Can this be done with something like regex (don't know much about it) or is that something it probably shouldn't do?

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

No

**Comment by Cohee1207** [comment]
I doubt there are any heuristics that could be applied to that. Try regular expressions extension, it's built-in but is unlikely to solve your problem too. If nothing helps - switch the backend to any of the other dozen supported.
