### ISSUE TITLE
[BUG] Editing a swipe causes a continue when clicking to confirm, and the generation never appears in the chat. Sometimes a swipe will never populate even without editing it.

### ISSUE THREAD

**Issue by JPFlare** [SillyTavern/SillyTavern#1987]
### Environment

🪟 Windows

### System

Windows 10, chrome 123.0.6312.86, Oobabooga with Exllamav2, koboldcpp

### Version

1.11.6 Tried an earlier version as well.

### Desktop Information

Node.js version v18.16.1.

Tried Oobabooga with Exllamav2, as well as Koboldcpp. Happens with any model. Happens in both Firefox and Chrome.

Has happened on:

ROG Zephyrus G15, Ryzen 9 4900HS, 2060 Max-Q, Windows 10
Workstation, Intel I9 12900k, RTX 3090, Windows 10
Render Server, Intel I9 10900x, 4x RTX 3090, Windows 10

### Describe the problem

When generating a swipe, sometimes the API will receive the request and begin generating a response, but SillyTavern will never populate with the response.

When it does get a response, if you stop the generation and click to edit the response, then click the checkbox to confirm the edit, it will automatically send a Continue.

The responses generated when it automatically continues typically don't show up in SillyTavern, but the API does generate them, and SillyTavern acts as though it's waiting for a response. You can interrupt the generation by clicking to "Stop".

When stopping it, the swipe will bug out and show as an improper fraction, IE. 3/2, or 5/4, and editing the message will show you the previous swipe.

It seems to happen when a chat reaches a certain length, but it's difficult to tell exactly what causes it.

I've tried on three different devices, with the API being hosted on the same machine, or on a different machine on the network. It happens with all of them.

Happens when connected via localhost, over LAN using the machine's IP address, and remotely using VPN port forwarding, on all three machines, running either API.

### Additional info

There's nothing different about the request compared to a normal continue, SillyTavern just never puts the response into the chat, and the continue happens without the user asking for it. It seems to happen to me the most when there's a longer chat, but once it starts happening it is easily reproducible and happens every time.

I've tried clean installations, I've tried older versions, I've tried several devices, I've tried several different character cards. It happens somewhat often.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Disable automatic summarization.

**Comment by ShivaThomas** [comment]
> Disable automatic summarization.

Thank you @Cohee1207! That fixed the issue for me. I was going crazy with that bug. Auto sumarization was screwing everything up after 10 messages.

**Comment by ShivaThomas** [comment]
By the way, it's not a Windows specific bug. I had the same issue on **🍎MacOS** and I don't think I ever changed the summarization settings.
