### ISSUE TITLE
[Feature Request] Local TTS option instead of using Eleven Labs.

### ISSUE THREAD

**Issue by paracaxt** [SillyTavern/SillyTavern#199]
I'm not fond of Eleven Labs for their outrageous cost using the dev build's TTS function.
Making voices ate up a ton of characters for my free generation with almost nothing left! 😂 
Least forgetting how truly frightening expensive the service is, I propose a free option.
The TTS I propose being Bark, which seems superior at times to EL and very feature rich. While quite fast for the quality of spoken dialogue it generates on my old hardware. Another last resort that's local is silero implementation, but that one is well not that great and feature rich as Bark.

Here's my suggestion's links and examples if possible to implement eventually.
https://github.com/suno-ai/bark
https://huggingface.co/spaces/suno/bark

Ah! I see Oobabooga has this as an extension already!
Hopefully we can get this for SillyTavern too.
https://github.com/wsippel/bark_tts

**Comment by Dankmank** [comment]
Yes this would be awesome. I really hope enough people see the potential in something like Bark. Creating/cloning voices and sharing them with others, easy to use in a TTS extensions is just to good. Combine this with voice recognition and AI characters and you could basically talk freely to every character you like. And it seems like we are really close now in achieving this.
