### ISSUE TITLE
[FEATURE_REQUEST] API key support for llamacpp

### ISSUE THREAD

**Issue by SimplyCorbett** [SillyTavern/SillyTavern#1991]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Currently it is not possible to use the API key with the llamacpp text backend.

### Describe the solution you'd like

API key is supported like on kobold.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

No

**Comment by Cohee1207** [comment]
see: https://github.com/SillyTavern/SillyTavern/commit/a96bb4050595ab1e1c9d98cede6fedab09d522eb (staging)

**Comment by Cohee1207** [comment]
Done.
