### ISSUE TITLE
[BUG] “不调整头像大小”功能，在刷新后被自动裁切放大。

### ISSUE THREAD

**Issue by leetraman822** [SillyTavern/SillyTavern#1993]
### Environment

🪟 Windows

### System

Microsoft Edge 版本 123.0.2420.65 (正式版本) (64 位)

### Version

1.11.6 'release' (d6168fda)

### Describe the problem

我的角色图像比例为1:1方形，我尝试使用方形图片为头像。

当我勾选“不调整头像大小(Never resize avatars)”并导入方形图像后，在“角色卡”和“聊天栏”里是没有被裁切和缩放的，方形图片可以完整的展示。

【自动裁切缩放出现的几种情况】
- 页面刷新后
- 退出“角色卡”页面后
- 点击“角色卡”页面上方的角色名字后

我查看了路径：SillyTavern\public\characters 里导入的方形角色头像，头像和原始图片一模一样，没有被裁切或缩放。
裁切和缩放只在SillyTavern网页中出现。

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by steve02081504** [comment]
apng可以避免裁剪 望周知
