### ISSUE TITLE
[FEATURE_REQUEST] Add Cohere API support.

### ISSUE THREAD

**Issue by IvanMazh** [SillyTavern/SillyTavern#1994]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Add Cohere API support. https://docs.cohere.com/docs/models

### Describe the solution you'd like

Add Cohere API support. https://docs.cohere.com/docs/models

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

No

**Comment by Cohee1207** [comment]
Done.
