### ISSUE TITLE
[BUG] `NOT ANY` May didn't work the way it was supposed to.

### ISSUE THREAD

**Issue by steve02081504** [SillyTavern/SillyTavern#2009]
### Environment

🪟 Windows

### System

Windows11 64-bit; Firefox 125; NodeJS v21.5.0; Flash 32.0

### Version

commit 9d87b233e1cdc357d7b3d221e9d5c11332a3e9ee

### Desktop Information

as above

### Describe the problem

I'm working on a Lorebook for one of my Chinese characters, and since this character has two modes that use two completely different prompts and I couldn't find a good way to implement this mechanism, I wrote this entry to trigger the base setup of the general prompt in the general case:
```json
"9": {
	"uid": 9,
	"key": [
		"龙胆",
		"主人",
		"子",
		"么",
		"我",
		"你",
		"咱",
		"是",
		"的",
		"吧",
		"呀",
		"e",
		".",
		"。",
		"，",
		"～"
	],
	"keysecondary": [
		"进入调制模式",
		"some other rare word"
	],
	"comment": "一般模式base",
	"content": "some r18 prompt",
	"constant": false,
	"selective": true,
	"order": 2,
	"position": 1,
	"excludeRecursion": false,
	"preventRecursion": false,
	"disable": false,
	"addMemo": true,
	"displayIndex": 7,
	"probability": 100,
	"useProbability": true,
	"depth": 4,
	"selectiveLogic": 2,
	"group": "",
	"scanDepth": null,
	"caseSensitive": null,
	"matchWholeWords": false,
	"automationId": ""
}
```
It has a `key` section that matches almost any dialog, and a `keysecondary` section where I list two keywords that might match the content of a dialog in another mode.
I set the match pattern to `not any` and tried several rounds of dialog with that character, but I don't see the prompt content for that entry in the console window.
Is this perhaps a bug?

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Make sure you don't have Match whole words enabled as a global setting, it doesn't work nice with languages that don't separate words with spaces.

**Comment by steve02081504** [comment]
> Make sure you don't have Match whole words enabled as a global setting, it doesn't work nice with languages that don't separate words with spaces. 

```json
"matchWholeWords": false,
```
Yeah I'm pretty sure that, the doc says that global configs can be overridden by entry config.
https://docs.sillytavern.app/usage/core-concepts/worldinfo/#match-whole-words

**Comment by Wolfsblvt** [comment]
Would be very helpful if you post your full global settings as well, so I could test it.

Maybe also a message that should trigger it - but like you said, it *should* honestly be triggered by nearly everything.

**Comment by steve02081504** [comment]
> Would be very helpful if you post your full global settings as well, so I could test it.
> 
> Maybe also a message that should trigger it - but like you said, it _should_ honestly be triggered by nearly everything.

settings: [settings.json](https://github.com/SillyTavern/SillyTavern/files/14878733/settings.json)
message: e.g. `我不想上班。`
ty for your help!

**Comment by Wolfsblvt** [comment]
I don't know if its rude to ask, but are you 100% sure you have enabled that world info for either your character or the chat?  
Because it's not active in your global settings.

Please open the developer console in your browser, and when you send a message and it starts generating, check the console log for messages like this:
![image](https://github.com/SillyTavern/SillyTavern/assets/9962104/7fab77c6-33ef-4426-bc05-50161c88fca3)

You can see that this is telling me that I have 12 active WI entries that *can* be triggered.

**Comment by steve02081504** [comment]
> I don't know if its rude to ask, but are you 100% sure you have enabled that world info for either your character or the chat?  
> Because it's not active in your global settings.

I'm sure this world info is linked to the char card and I've successfully triggered the other entries
Do you need the character card to help with testing?

**Comment by Wolfsblvt** [comment]
I don't think this would help. It **does** trigger for me, I have tested your exact entry, and also copied over your main world info settings.

![image](https://github.com/SillyTavern/SillyTavern/assets/9962104/5356dc90-0c52-4b7f-b28c-ce4a329c8ace)

Can you do the following for me please?
1. Confirm the book is enabled for the character.
2. Check the console output, like I suggested, that it **actually** prints that the world info is being loaded with existing entries
3. Verify that `{{wiAfter}}` is actually part of your story string that you are using. Check that in Advanced Formatting -> Context Template -> Story String. Without that it might trigger, but still not be actually included into your context.
4. Lastly, check for the generated AI response via the "Prompt" button -> Prompt Itemization (first button of the header) that it actually is not inserted into your context.

I am pretty sure there is some issue with your setup, and not an actual bug.

**Comment by steve02081504** [comment]
Oh I found the reason: lack of WI budget!
Sorry for the hassle....
Is there any way to set it up to give a warning when WI budget out?

**Comment by steve02081504** [comment]
Figured out what the problem is, sorry for the trouble

**Comment by Wolfsblvt** [comment]
No worries, glad we figured that one out!

And sure there is. Check the global WI options (:

![image](https://github.com/SillyTavern/SillyTavern/assets/9962104/1b824118-f783-4952-bcea-4b79f21787cc)


Edit: You can close this issue if you consider this solved. I can't. Otherwise we have to wait for Cohee.
