### ISSUE TITLE
[BUG] Image Gen workflow seed replacement only replaces first instance.

### ISSUE THREAD

**Issue by cochese9000** [SillyTavern/SillyTavern#2012]
### Environment

🪟 Windows

### System

Vivaldi

### Version

Latest

### Describe the problem

When I'm using a complex workflow with more than one sampler (e.g.  'base' and 'refiner') the iamge fails to generate, due to the prompt having a string in that is not parseable to an int.

That's because there are multiple instances of the token "%seed%" and the extension only does a replace on the first one.  

I've found the fix, but I can't push, so just leaving this here for reference.  I've simply replaced 'replace' with 'replaceAll'

Line 2337:
```js
workflow = workflow.replaceAll('"%seed%"', JSON.stringify(Math.round(Math.random() * Number.MAX_SAFE_INTEGER)));
```

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by cochese9000** [comment]
Feel free to close this immediately or when you include the fix.

**Comment by Cohee1207** [comment]
Just to be clear, you want all instances of `%seed%` to be replaced with the same number, or every instance to have its own seed?

**Comment by LenAnderson** [comment]
How about having `"%seed%"` as a new random value on every replacement, and `"%seed-\d+%"` (or even named `"%seed-[a-z]+%"`?) for same-value seeds?

**Comment by Cohee1207** [comment]
@LenAnderson you stole my idea 👁️ 
I'm all in for it.

**Comment by cochese9000** [comment]
> Just to be clear, you want all instances of `%seed%` to be replaced with the same number, or every instance to have its own seed?

It needs to be the same number, or else the output has some incongruity for base-refiner relationship (you'd be refining a different version of the same image, otherwise), but as LenAnderson suggested above, you could support both approaches, in case you want to mix it up for some reason.
