### ISSUE TITLE
[BUG] Recent update really breaks Gemini smooth streaming

### ISSUE THREAD

**Issue by Daviljoe193** [SillyTavern/SillyTavern#2013]
### Environment

🐧 Linux

### System

Brave 1.63.174, Ubuntu 23.10

### Version

SillyTavern 1.11.6 'staging' (6cc73c2a)

### Desktop Information

v20.11.1

### Describe the problem

Smooth streaming was like a godsend for Google Gemini in SillyTavern, as it made the streaming something that wouldn't put my browser to a crawl. Problem is that pulling from staging cf6705ba to 6cc73c2a broke it completely, and I don't even know how to describe what's going on with this bug. Below is what it looks like on cf6705ba...

![strembef](https://github.com/SillyTavern/SillyTavern/assets/67191631/060beb8c-ee82-4c83-a7e9-e762720314d8)

And what happens on 6cc73c2a...

![stremaft](https://github.com/SillyTavern/SillyTavern/assets/67191631/408e60a6-cf48-4ad4-8a78-edbef41ce874)

### Additional info

Disabling smooth streaming seems to prevent the output from getting weird and jumbled, but Gemini streams so fast that it causes my browser to chug, so hopefully smooth streaming can be fixed, since the alternative is to just disable streaming altogether.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [x] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Interesting find, thanks. Should be fixed now.

**Comment by Daviljoe193** [comment]
Yep. Can confirm, 7221549 fixes the issue. Thanks for fixing this so quickly! 👍
