### ISSUE TITLE
[BUG] Novelai's image generation api route is outdated

### ISSUE THREAD

**Issue by MNarath1** [SillyTavern/SillyTavern#2016]
### Environment

🐋 Docker

### System

Docker version 26.0.0, build 2ae903e

### Version

SillyTavern 1.11.6 Staging

### Desktop Information

Generation API Novelai

### Describe the problem

Novelai's Image generation api has changed from api.novelai.net to image.novelai.net/ai/generate-image and is as of today completly deprecated so without changing this api specifically for nai image generation that feature won't work in sillytavern

### Additional info

NovelAI returned an error. Not Found {"statusCode":404,"message":"On 2024-02-21, we announced the deprecation of api.novelai.net for image generation. As of 2024-04-05, this url does not work for such. Please use image.novelai.net/ai/generate-image."}

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Hopefully fixed in staging. Releasing tomorrow.
