### ISSUE TITLE
[FEATURE_REQUEST] Allow separating user data directory from the source tree

### ISSUE THREAD

**Issue by vikanezrimaya** [SillyTavern/SillyTavern#2020]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

SillyTavern seems to store a lot of its data inside of the `public` directory, which clobbers the source tree. Allowing to separate user data from the `public` directory would enable easier packaging of SillyTavern in Linux distributions, making workarounds such as Docker unnecessary.

### Describe the solution you'd like

A command-line argument, or perhaps an environment variable, to allow SillyTavern to direct all of its writes and reads to a different directory, and only fall back on the `public` directory for things that do not change. Picking up `config.yaml` from the same location also seems like a good idea.

### Describe alternatives you've considered

Brave souls attempting to package SillyTavern seem to use workarounds with unionfs ([1](https://mpr.makedeb.org/pkgbase/sillytavern/git/tree/sillytavern-wrapper.sh), [2](https://github.com/NixOS/nixpkgs/pull/287908)), however, these seem to be rather fragile (the second one, in particular, ended up with nothing writable due to a mistake by the maintainer; my attempts to change it led to other hilarious things which I'd prefer not to describe here for the sake of brevity)

### Additional context

While containerization seems an acceptable choice to many, providing alternatives to it might be a good idea for people unwilling to install a container runtime on their system but desiring an installation through their system-wide package manager instead.

### Priority

High (The app does not function without it)

### Are you willing to test this on staging/unstable branch if this is implemented?

Maybe

**Comment by Cohee1207** [comment]
This is non trivial, but I'll get to it soon.

**Comment by Cohee1207** [comment]
Track the progress here: https://github.com/SillyTavern/SillyTavern/tree/neo-server

**Comment by Cohee1207** [comment]
Merged to staging, and released as 1.12.0-preview

**Comment by Cohee1207** [comment]
Released.
