### ISSUE TITLE
[FEATURE_REQUEST] eazy mode switching of char

### ISSUE THREAD

**Issue by steve02081504** [SillyTavern/SillyTavern#2021]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

You know, sometimes people like to shoehorn different "modes" into the same character, and the character has big sections of prompts that diff from mode to mode.
The most outrageous character card I've ever seen had five modes, and my favorite character card had two.
At the moment I'm mostly using the not-very-reliable keyword matching technique for this, see #2009
I'd like to have a simpler way to support mode switching for characters instead of setting up complicated keyword matching

### Describe the solution you'd like

1. Allows setting triggers to set variables x to y when someone says something
2. Allows world info entry on/off depending on the variable.

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Wolfsblvt** [comment]
Same as with the other request you had, this can also be solved with scripting. Have the different modes in a lore book. Have a quick reply defined that runs after each {{char}} message and that script will enable or disable the relevant world entries.

It's a bit of scripting setup for sure, but should be possible to set up.

**Comment by steve02081504** [comment]
> Same as with the other request you had, this can also be solved with scripting. Have the different modes in a lore book. Have a quick reply defined that runs after each {{char}} message and that script will enable or disable the relevant world entries.

If I understand correctly, there are the following problems with this with scripts and quick reply:
1. scripted content can't be saved to character cards (png), which is a pain for character sharing: maybe we should allow the extension to store character-related information in the character json?
2. quick reply seems to be able to match only specific dialog content, not retrieve keyword triggers within the dialog content.

**Comment by Wolfsblvt** [comment]
You aren't wrong with your remarks. Yes. This is currently a *missing feature* in ST. You cannot include something I'd call "light scripting" into cards, besides basic stuff like the `{{roll}}` or `{{pick}}` macro, and setting variables that can be utilized after, but not like.. directly.

There are workarounds, like actually having WI entries being triggered that use `{{setvar}}` and then having then using the same variable to print stuff out on every following execution, etc.  
It's all a bit workarounds though.

I am currently planning to do a rework on the macros that you can use in actual character descriptions and world lore. With that it will be possible to actually nest macros inside macros, build simple if blocks and other things, so you can add light changes and scripted stuff into character cards.   
That's a planned feature though, and might take some time.
