### ISSUE TITLE
[FEATURE_REQUEST] Allow hosting SillyTavern on a subpath

### ISSUE THREAD

**Issue by vikanezrimaya** [SillyTavern/SillyTavern#2025]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

This would allow hosting SillyTavern in a subpath, kinda like "http://localhost/sillytavern". Currently some paths are absolute, this would need to change.

### Describe the solution you'd like

Change absolute paths (in particular, to `/api/` calls) to relative paths, or allow configuring a prefix at runtime.

### Describe alternatives you've considered

Hosting as a subdomain is nice, but not always accomplished without DNS. Tailscale, for example, still has a feature request for Magic DNS subdomains open. Currently I just have it sitting on port 8000, which is... not bad, but the lack of HTTPS is unnerving me a little (Tailscale does TLS for me on port 443, but, as there are no subdomains, I can't host SillyTavern and Jellyfin together, as Jellyfin's support for path prefixing is terrible and can break some things, or so the documentation says). Therefore I would classify this as a low-priority issue.

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Wolfsblvt** [comment]
Well, doesn't Silly Tavern already support HTTPS with SLL certificates? [ST Doc -> Remote connections -> HTTPS](https://docs.sillytavern.app/usage/remoteconnections/#start-sillytavern-with-tlsssl)  
This might not be the exact answer to the question you were asking, but still quite relevant.

Besides that, I don't know which paths you are speaking of that are absolute? All API calls I could find just use relative urls like this: `/api/settings/save`

**Comment by vikanezrimaya** [comment]
Wolfsblvt ***@***.***> writes:

> Besides that, I don't know which paths you are speaking of that are
> absolute? All API calls I could find just use relative urls like this:
> `/api/settings/save`

That is an absolute path, in the sense that if I were to reverse-proxy
SillyTavern to a subpath (like `example.com/sillytavern/`), it would try
to knock to `example.com/api/settings/save`, not
`example.com/sillytavern/api/settings/save`.

Allowing to put a prefix in these paths, like
`/sillytavern/api/settings/save` would be a solution to my problem. (The
`index.html` and the JS imports seem to use relative paths to import
everything already, so the API calls are probably the only thing that
would need to be changed.)

--
Sincerely,
Vika

**Comment by Wolfsblvt** [comment]
It would be both API calls on the server-side and on the client-side though. I don't know if that's actually feasible. That would be something Cohee has to tackle if that even is an option.

**Comment by LenAnderson** [comment]
> It would be both API calls on the server-side and on the client-side though. I don't know if that's actually feasible. That would be something Cohee has to tackle if that even is an option.

The endpoints don't mind. This would only affect client side. Took me about five minutes with search-replace to get a working ST on `http://localhost/st` (behind an apache `<Location>` with proxypass).

However, there should probably an exported `baseUrl` or `rootUrl` variable available for extensions to use when talking to the server or using media...

And of course it breaks all extensions that use `/...` in their paths for anything...

**Comment by Wolfsblvt** [comment]
Which sounds like a lot of breaking changes for not much gain to me, hm.

**Comment by LenAnderson** [comment]
Yep, would be easier to just use a subdomain that gets resolved locally (nginx proxy manager or something like that).
(or maybe something to consider for cohee's neo-server)
