### ISSUE TITLE
[FEATURE_REQUEST] File-system like view for tags

### ISSUE THREAD

**Issue by psi00** [SillyTavern/SillyTavern#2027]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Not applicable.

### Describe the solution you'd like

Using the folder view for tags is great, but having more of a 'file system' sort of view would be great. Being able to sort through folders without having all of the characters unsorted right below them would be a nice feature to have.

### Describe alternatives you've considered

Using alternative sorting methods e.g. sorting by emojis, which I currently do now. Or, just sorting by alphabetical order like ST does by default.

### Additional context

(I'm very bad at explaining myself through words so here is the most generic photo I could think of to demonstrate what I meant. Obviously the folders would be the tags, and you could click into them and view all the subfolders [more specific tags? maybe?] or just have the characters there)

![What I meant](https://i.imgur.com/REAHkhl.png)

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
The newest release has ability to hide characters outside of folders.

**Comment by Wolfsblvt** [comment]
Yup, check all the features on the latest release.

There'll never be "real" folders in ST though, as folders and subfolders don't really work with how tags in ST are used.

**Comment by psi00** [comment]
> The newest release has ability to hide characters outside of folders.

Really?? I completely glossed over that lol
Will definitely be checking that out, thank you :)

> Yup, check all the features on the latest release.
> 
> There'll never be "real" folders in ST though, as folders and subfolders don't really work with how tags in ST are used.

Yeah I would have assumed so, giving the current system (which I don't completely understand to be completely honest but it works xd)

**Comment by Wolfsblvt** [comment]
Let us know if there is still some big feature lacking with the new tagging options. Feedback always welcome.

**Comment by psi00** [comment]
Bit late to this but I had a bit of a play around with it, works great, was exactly what I was looking for :) although it was a bit hidden away at first, which I guess makes sense since it does mess with the tags quite a bit
