### ISSUE TITLE
[BUG] I don't think it's supposed to look like this

### ISSUE THREAD

**Issue by ELind77** [SillyTavern/SillyTavern#2039]
### Environment

🐋 Docker

### System

sillytavern docker; Chrome and Firefox

### Version

:latest :release :staging

### Describe the problem

That huge blank space doesn't go away when chats should make it expand.

![image](https://github.com/SillyTavern/SillyTavern/assets/5109720/ddbf8009-1f27-4491-989e-98e28900ae88)

I am using Docker.  I tried the official docker repo with :latest, :release, and :staging.
I'm using the `docker-compose.yaml` file included in the `release` branch of the repo.  I built a local docker image on Friday evening and then I copied out `/home/node/app/config` to a `config/` in `docker/` and used `docker-compose up`.  

When I run the original image I built, without mounting any of the host directories as volumes, everything looks fine. 

I apologize in advance if this issue has been raised already.  I did my best to look around 

I'm guessing this is user error with me forgetting or missing some step in how I got the build to work but it makes the whole thing not usable. 

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Disable visual novel mode under user settings
