### ISSUE TITLE
[Feature Request] gif/apng card

### ISSUE THREAD

**Issue by steve02081504** [SillyTavern/SillyTavern#2040]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

I was just thinking it would be nice if our cards could become moving pictures.

### Describe the solution you'd like

support apng/gif cards.

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
APNG are supported. Animated GIFs are not.

**Comment by steve02081504** [comment]
> APNG are supported. Animated GIFs are not.

gotit, ty for replying!
