### ISSUE TITLE
[FEATURE_REQUEST] world info edit UI: `excludeRecursion`&`preventRecursion` setting in non-English languages

### ISSUE THREAD

**Issue by steve02081504** [SillyTavern/SillyTavern#2041]
### Have you searched for similar requests?

No

### Is your feature request related to a problem? If so, please describe.

I noticed that the world info entry has these two properties but I don't find the corresponding buttons in the UI.
Currently if I want to change these properties I need to export json file, edit it in an external text editor and import it back.

### Describe the solution you'd like

It would be a lot easier if there were corresponding checkboxes

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Wolfsblvt** [comment]
You mean those two ones?
![image](https://github.com/SillyTavern/SillyTavern/assets/9962104/12130da5-92c8-484c-b5e9-2130ba738807)

**Comment by steve02081504** [comment]
> You mean those two ones?

That's it!
It's strange that I don't see them on my page
Is it a problem with the language settings?🤔

**Comment by sirius422** [comment]
> > You mean those two ones?
> 
> That's it! It's strange that I don't see them on my page Is it a problem with the language settings?🤔

I can confirm that it won't show up unless you choose English as UI Language in 1.11.7 'staging' (42e1ade1)

**Comment by Cohee1207** [comment]
True that. I fixed it in: https://github.com/SillyTavern/SillyTavern/commit/75857ae18cf08ff2367f966878dcb4fd0f7817dd
