### ISSUE TITLE
[FEATURE_REQUEST] (Custom API) Claude-like settings

### ISSUE THREAD

**Issue by rivey404** [SillyTavern/SillyTavern#2043]
### Have you searched for similar requests?

No

### Is your feature request related to a problem? If so, please describe.

(Trying to use Claude models with cloud providers through an OpenAI compatible API.)

It doesn't work without the "User first message" option like in the Claude completion source, and also the furthest message from the chat history when trimmed to be from the user role. It would also be nice to have the squashing of prompts after Chat History to the latest user prompt and the assistant prefill option (from already existing Claude completion settings).

### Describe the solution you'd like

Hopefully just some extra toggles/settings in the presets panel when the custom chat completion source is selected.

### Describe alternatives you've considered

None

### Additional context

None

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by YunySun** [comment]
claude3 first message problem? me too

**Comment by Cohee1207** [comment]
Create a custom prompt injection with a user role at max depth (999). This will have the exact same effect, no need for a special box just for the occasion of something "OpenAI-compatible" being not OpenAI-compatible.
