### ISSUE TITLE
[BUG] Failed to create generation on group chat with potential Fix; "Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'replace')"

### ISSUE THREAD

**Issue by imesha10** [SillyTavern/SillyTavern#2046]
### Environment

🪟 Windows

### System

Windows 11, Chrome

### Version

d56722a * (I do have tiny modified code on my scratch forked vers. however I'm assuming this is universal based on the fix. If I'm wrong close this br)

### Desktop Information

Node JS: v18.15.0
Chat Completion Source: OpenAI - Proxy Presets
Branch: Staging
Model: any gpt version

### Describe the problem
Error in console after sending a generation request:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'replace')
    at customBaseChatReplace (group-chats.js:359:23)
    at replaceAndPrepareForJoin (group-chats.js:371:24)
    at getGroupCharacterCards (group-chats.js:401:27)
    at getCharacterCardFields (script.js:2653:28)
    at substituteParams (script.js:2333:24)
    at getBiasStrings (script.js:4417:19)
    at Generate (script.js:3228:57)
    at generateGroupWrapper (group-chats.js:814:32)
    at async S.fn.init.complete (script.js:8123:37)
```

Identified Surface Level Problem at:
https://github.com/SillyTavern/SillyTavern/blob/d56722a4b64520f675d6fc767cbc415fa37e3aed/public/scripts/group-chats.js#L357-L361

My ai generated Fix:
``` javascript
function customBaseChatReplace(value, fieldName, characterName) {
    if (value === undefined) {
        console.error('Value is undefined');
        return;
    }
    // We should do the custom field name replacement first, and then run it through the normal macro engine with provided names
    value = value.replace(/<FIELDNAME>/gi, fieldName);
    return baseChatReplace(value.trim(), name1, characterName);
}
```

Then it worked.

### Additional info
I'm running this on a quick private fork that I have for testing stuff. This is running the latest by doing `git pull origin staging`, there are minor small code changes that should not be affecting this. I normally wouldn't post this because this is an error of a fork however based on the 'fix'/patch I did, I assume the problem is here.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
I see. Should be fixed by now.
