### ISSUE TITLE
[BUG] TTS Auto Generation error with text streaming

### ISSUE THREAD

**Issue by Andybui1012** [SillyTavern/SillyTavern#2047]
### Environment

🪟 Windows

### System

Chrome Version 123.0.6312.106 (Official Build) (64-bit)

### Version

SillyTavern 1.11.7 'staging' (63117653)

### Desktop Information

node v20.9.0 
branch staging

### Describe the problem

When text streaming is on, user messages don't get sent to the tts queue, even if auto generation and narrate user messages are checked.
The same happens for group chat when text streaming is on, only the last message gets narrated if the characters reply to each other.
I tested with the System and AllTalk TTS providers, and both worked when I turned off text streaming and stopped working when I turned on text streaming.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Pull staging and try again
