### ISSUE TITLE
[FEATURE_REQUEST] How do I add sampling parameters to default ones?

### ISSUE THREAD

**Issue by Priestru** [SillyTavern/SillyTavern#2048]
### Have you searched for similar requests?

No

### Is your feature request related to a problem? If so, please describe.

I want to incorporate this thing,

https://github.com/oobabooga/text-generation-webui/pull/5677

But struggle to find where to add below to parameters SillyTavern sends to Ooba

```
    'dry_allowed_length': 2,
    'dry_multiplier': 0.8,
    'dry_base': 1.75,
    'dry_sequence_breakers': '["\\n", ":", "\\"", "*"]',
    'dry_range': 0,
```
    
 I think it's to early to implement into Silly Tavern yet, but I want to make it work on my local.

### Describe the solution you'd like

Just to find a line of code where I can stick these things.

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Priestru** [comment]
I think i found

**Comment by Priestru** [comment]
early_stopping: false,
  add_bos_token: false,
  dry_allowed_length: 2,
  dry_multiplier: 0.8,
  dry_base: 1.75,
  dry_sequence_breakers: '["\\n", ":", "\\"", "*"]',
  dry_range: 0,
  dynamic_temperature: false,
  
  Yeah i actually made it work. Incomprehensible to me how is it just possible to do just anything if you try hard enough. Magic.

**Comment by Priestru** [comment]
Works fucking wonders on generation. I bet everyone needs that.

**Comment by Cohee1207** [comment]
Make a pull request with proper GUI controls.

**Comment by kokansei** [comment]
I have made a pull request to add DRY samplers here:
https://github.com/SillyTavern/SillyTavern/pull/2211
