### ISSUE TITLE
How does the "Target length (tokens)" work?

### ISSUE THREAD

**Issue by GaelicThunder** [SillyTavern/SillyTavern#2049]
Hi everybody, im trying to understand how does it work between endpoints etc.. but i can't find anything about it in the wiki. Can someone help me?
![SillyTavernToken](https://github.com/SillyTavern/SillyTavern/assets/48930397/3deb4c6e-6e92-46d4-bf4b-97b99d1aa5f7)

**Comment by Cohee1207** [comment]
This is a target length for the auto-continue function only. It is disabled in your case.

**Comment by GaelicThunder** [comment]
I see, thanks for the clarification.
Still, how does it archieve it? Does it cut the output when it reaches the target?

**Comment by LenAnderson** [comment]
> I see, thanks for the clarification. Still, how does it archieve it? Does it cut the output when it reaches the target?

The feature is called auto-continue, not auto-cut. It practically presses the continue button for you until the message has at least target length.

**Comment by GaelicThunder** [comment]
Ok, so it just doesnt click _continue_ if the number of token is > of _Target length_
Thanks a lot!
