### ISSUE TITLE
[FEATURE_REQUEST] Support system instructions for Gemini API

### ISSUE THREAD

**Issue by Jasonnor** [SillyTavern/SillyTavern#2056]
### Have you searched for similar requests?

Yes

### Describe the solution you'd like

Google just announced [Gemini 1.5 Pro with System Instructions](https://developers.googleblog.com/2024/04/gemini-15-pro-in-public-preview-with-new-features.html).
It would be helpful to integrate system instruction into the Google MakerSuite API for chat completions. 👍
I've listed the relevant API references I found below.

### Additional context

- [API reference of system instructions](https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/send-chat-prompts-gemini#system-instructions)
- [System instructions  |  Google AI for Developers](https://ai.google.dev/docs/system_instructions)

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
Merged to staging branch, thanks @kingbased

**Comment by Jasonnor** [comment]
@Cohee1207 
I've tested it and it seems to be working fine, thanks to @kingbased!
