### ISSUE TITLE
[BUG] avatar missing after updating

### ISSUE THREAD

**Issue by Sasamitatami** [SillyTavern/SillyTavern#2058]
### Environment

🪟 Windows

### System

edge 123.0.2420.81

### Version

1.11.7

### Desktop Information

![image](https://github.com/SillyTavern/SillyTavern/assets/49764735/18e1289a-f765-4cd8-9170-54f6ed74370f)

### Describe the problem

after updating to the latest version, most of my character avatar went missing..then error pop out whenever i put a image again

### Additional info

![image](https://github.com/SillyTavern/SillyTavern/assets/49764735/71f4f2d1-ea6d-4e90-b72a-3b1abfa0e286)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Not enough information, but it sounds like you have a corrupted image processing library. Try deleting node_modules, running `npm cache clean --force` and then restarting again. If that doesn't help - disable thumbnails in config.yaml: `disableThumbnails: true`

**Comment by Sasamitatami** [comment]
hmm how can i disable the protection? also the image also missing after i putting it up again after i restart ( this is before i sending the issue report )
![Capture](https://github.com/SillyTavern/SillyTavern/assets/49764735/f7793759-26d7-47d5-9de2-590fdf312d37)

**Comment by Cohee1207** [comment]
Have you tried disabling thumbnails?

**Comment by Sasamitatami** [comment]
it give out this error 
![image](https://github.com/SillyTavern/SillyTavern/assets/49764735/6d06573b-4983-4815-a0e7-6bebe29861ba)

**Comment by Sasamitatami** [comment]
somehow i got it work for now..i just delete node_modules only without the npm cache clean and change back disablethumbnail back to way it was
