### ISSUE TITLE
Is there a way to remove this part of the UI in the chat window?

### ISSUE THREAD

**Issue by A-Dream-Of-Illusionary-Senses** [SillyTavern/SillyTavern#2059]
![2024-04-10 185558](https://github.com/SillyTavern/SillyTavern/assets/126984422/676e01de-58ae-470d-a571-baa594b76819)
I recently updated to 1.11.6 and this part of the UI is right above chatbox is an eyesore. 
Once I click this button
![2024-04-10 185748](https://github.com/SillyTavern/SillyTavern/assets/126984422/05ad2c17-510b-4b2a-8550-c79967bbfb25)
It moves the window to the side, but still no way to close it completely.
![2024-04-10 185834](https://github.com/SillyTavern/SillyTavern/assets/126984422/1a228402-e232-4680-8b28-4cf4ab194ae6)

**Comment by Cohee1207** [comment]
Extensions => Quick Replies => disable

**Comment by A-Dream-Of-Illusionary-Senses** [comment]
Thank you very much!
