### ISSUE TITLE
[FEATURE_REQUEST] Custom inputs for ComfyUI

### ISSUE THREAD

**Issue by drago87** [SillyTavern/SillyTavern#2060]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Would want more inputs that the user can use to change settings in the workflow for ComfyUI (%prompt%,%width% and the likes) and the input field for it in the SillyTavern Image generation GUI
The fields i would want is 
1 or more int inputs
1 or more string inputs
1 or more image input

### Describe the solution you'd like

for the int you could use %number% if you have more then 1 you coud use %number1%,%number2%...
for the string you could use %text% if you have more then 1 you coud use %text1%,%text2%...
for the image you can have a button that let the user select a image and it fills the input field with the path to that image %image% or %image1%,%image2%...

### Additional context

This lets you make more complex workflows where you for a example can send a image for a pose or a image for face swap.
The int cold work with switches or outher int based settings

A uppdate to the [stable-diffusion docs](https://docs.sillytavern.app/extras/extensions/stable-diffusion/) where it mentions that the ComfyUI workflow needs to be manually changed and what %% can be used

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by LenAnderson** [comment]
You can already add as many custom placeholders as you want, with full macro replacement (`{{char}}`, `{{getvar::...}}`, `{{random::...}}`, ...).

![image](https://github.com/SillyTavern/SillyTavern/assets/7149120/5a591a30-8550-4ea2-8f68-24f81fe02a8e)

**Comment by drago87** [comment]
Took me a while to find the "Open workflow editor" button
Now i only need to find out how to use them
