### ISSUE TITLE
[BUG] Gemini Pro 1.5 supports 1048576 tokens, but UI limit is 200K

### ISSUE THREAD

**Issue by wujipu0** [SillyTavern/SillyTavern#2062]
### Environment

🐧 Linux

### System

Ubuntu 22.04

### Version

1.11.7 commit 4f83782430adca851faafc774b3edf7ed44f157d

### Desktop Information

- Node v20.12.0

![Screenshot_2024-04-10_14-02-23](https://github.com/SillyTavern/SillyTavern/assets/165673044/bdd32d1c-36e7-4a40-9aa2-40d29f5c1700)

### Describe the problem

I am able to access the 1048576 token limit via Google's API for Gemini 1.5 Pro, but not in SillyTavern, as it seems to limit me to 200K. See https://ai.google.dev/models/gemini for details.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Disable unlocked context. The max will be set to 1 million.
