### ISSUE TITLE
[BUG] <title>The existing text classification models cannot correctly classify texts outside of English

### ISSUE THREAD

**Issue by blueswolf** [SillyTavern/SillyTavern#2065]
### Environment

🪟 Windows

### System

WINDOWS

### Version

1.11.7

### Describe the problem

The existing text classification models are unable to correctly classify text outside of English, which seriously affects the experience of non English users when using emoticons or LIVE2D. It is impossible to establish correct emoticon results, so it is recommended to replace the text classification model with a multilingual version

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Training classification models is out of scope of this project. All default models are open source and were found on Huggingface.

**Comment by Cohee1207** [comment]
Research transformers docs if you want to train them yourself. 

https://huggingface.co/docs/transformers/en/tasks/sequence_classification

**Comment by blueswolf** [comment]
Ok I will try to make an onnx model.
In addition, I wonder if it is possible to provide an option to call the translation module to preprocess the text before classifying it?

**Comment by Cohee1207** [comment]
> In addition, I wonder if it is possible to provide an option to call the translation module to preprocess the text before classifying it?

Not impossible. I'll look into it.

**Comment by Cohee1207** [comment]
Done. I am curious why anyone didn't think of it before, it's simple but effective.
