### ISSUE TITLE
[FEATURE_REQUEST] Console window title

### ISSUE THREAD

**Issue by steve02081504** [SillyTavern/SillyTavern#2071]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

When I run the web server, the console window that pops up is titled `Windows PowerShell`.
![图片](https://github.com/SillyTavern/SillyTavern/assets/31927825/31e8e7d4-0984-4d66-a051-546b4f678c04)
Can we swap it out for a more recognizable window title like `SillyTavern WebServer`?

### Describe the solution you'd like

Set Window tittle

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by LenAnderson** [comment]
You can edit your `Start.bat` (or make a copy `MyStart.bat`) and add the line `title SillyTavern WebServer` between `call npm ...` and `node ...`

**Comment by steve02081504** [comment]
> You can edit your `Start.bat` (or make a copy `MyStart.bat`) and add the line `title SillyTavern WebServer` between `call npm ...` and `node ...`

tried but not work....
sad.

**Comment by LenAnderson** [comment]
Oh, yeah. You have to set `autorun` to `false` in your config.yaml and add `start http://localhost:8000` (or whatever URL/port you use to open ST) as well.
Should look something like this in the end:
```bat
@echo off
pushd %~dp0
set NODE_ENV=production
call npm install --no-audit --no-fund --quiet --omit=dev
title Your Title Here
start http://localhost:8000
node server.js %*
pause
popd
```

**Comment by steve02081504** [comment]
> Oh, yeah. You have to set `autorun` to `false` in your config.yaml and add `start http://localhost:8000` (or whatever URL/port you use to open ST) as well. 

This method worked! Thankss!
Is there a way to make `autorun` not change the window title when it turns on? 🤔

**Comment by LenAnderson** [comment]
Not without changing code in the ST server. There might be by changing how the server launches the ST client. The title change is a stupid thing that node does when launching other processes. But I don't remember what I found when I last looked into it.
