### ISSUE TITLE
[FEATURE_REQUEST] Can you put all the original texts in en.json?

### ISSUE THREAD

**Issue by Touch-Night** [SillyTavern/SillyTavern#2074]
### Have you searched for similar requests?

No

### Describe the solution you'd like

A full en.json file for reference.   
So translators can better know if there're new entries to translate.

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

No

**Comment by Zhongyi-Lu** [comment]
https://github.com/SillyTavern/SillyTavern/pull/2098

I made one by using a Python script to set all values as the keys, following by a manual correction. I'm not sure if there are any typos.

**Comment by Touch-Night** [comment]
That would not be right and is not what I want. The keys are not the original text nor your manual correction. (e.g. line 38 `"LLaMA / Mistral / Yi models only"`).  
And setting all values as keys cannot resolve the issue that some text that are shown in the webpage which do have a `<data-i18n>` tag are not in the language files. Plus, some key:value are deprecated and should be removed.  
I want a true list that contains all key:value that should be translated.

**Comment by Zhongyi-Lu** [comment]
@Touch-Night Should I remove all unused lines in this pull request, or do it in the next one?

**Comment by Touch-Night** [comment]
I think it's better to set #2098 as draft and reopen it when it's ready.

**Comment by Touch-Night** [comment]
https://github.com/SillyTavern/SillyTavern/pull/2098#issuecomment-2166449713
