### ISSUE TITLE
[BUG] DrawThings API error

### ISSUE THREAD

**Issue by huh342** [SillyTavern/SillyTavern#2075]
### Environment

🍎 Mac

### System

Ventura 13.6.3, Chrome 123.0.6312.107

### Version

SillyTavern 1.11.7 'release' (4f837824)

### Desktop Information

- Node.js:  v20.11.1
- Generation API: ollama
- Model: nollama/mythomax-l2-13b:Q5_K_S

### Describe the problem

When asking sillytavern to generate an image with drawthings, I expect the request to be sent to drawthings, but I actually see an API error.

Error: SD DrawThings API returned an error.

    at /Users/user/SillyTavern/src/endpoints/stable-diffusion.js:702:19

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {

  [cause]: '{"body":"","errors":"","detail":"Unrecognized keys: [\\"auth\\"]","error":"HTTPException"}'

### Additional info

- drawthings is running
- drawthings server is running
- sillytavern has drawthings api selected under image generation
- sillytavern has correct port and ip for drawthings server
- sillytavern has optional authentication section as blank (nothing entered)
- note: drawthings does not have a section for authentication

![error](https://github.com/SillyTavern/SillyTavern/assets/166851004/04fb7a65-fac4-4749-bcca-5f4ef49a49e4)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Fixed. Try again please.

**Comment by huh342** [comment]
It works now. Thank you!
