### ISSUE TITLE
[FEATURE_REQUEST] Default character expression

### ISSUE THREAD

**Issue by maxime-fleury** [SillyTavern/SillyTavern#2077]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

When I add a new Card, or select one that doesn't have an expression pack loaded, it doesn't load my favorid expression pack, so I need for each card to go to settings and add the expression pack.

### Describe the solution you'd like

In settings the ability to select one expression pack for when there are none, so when you add a new card it will automatically be loaded.

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Wolfsblvt** [comment]
Wait. You are using the same expression images for several different characters?

This is not how ST is designed. Expressions are character-specific and placed in a folder with the character name.
How exactly are you selecting the expression packs? You need to provide a bit more details.

**Comment by maxime-fleury** [comment]
I'd rather have a default character I like, instead of the smiley/nothing, I know usually most people have one set per character, but I really like to have to have a character instead of nothing or the smiley, I use minervaOC character when I don't have images.
I have like 200 characters and most of them don't have an expression pack.

So for almost every new character I add in ST I go to settings expression pack and add the same ZIP file.

**Comment by Wolfsblvt** [comment]
Where do you have the smiley/nothing that you want replaced? I am still not really getting it.  
If a character does not have an expression pack, it will just show up with its default character image all the time, doesn't it?

But besides that, I think what you have is a very niche use-case. Most people use expressions for their character, and want to use it as that character - that is what this system is designed for.  
Your request might be doable as an extension, but for core ST it doesn't really make sense in my eyes.

**Comment by Cohee1207** [comment]
If you don't like the default smileys - just replace them in the `public/img/default-expressions` folder with whatever images you like. Just keep in mind that since these images are a part of the repo, they are subject to `git reset` if you ever need to use that command.

**Comment by Cohee1207** [comment]
Also, you might need to play around with custom CSS since default expressions have slightly altering styles compared to the default ones (they are v-aligned at the top).

**Comment by maxime-fleury** [comment]
> Where do you have the smiley/nothing that you want replaced? I am still not really getting it. If a character does not have an expression pack, it will just show up with its default character image all the time, doesn't it?
> 
> But besides that, I think what you have is a very niche use-case. Most people use expressions for their character, and want to use it as that character - that is what this system is designed for. Your request might be doable as an extension, but for core ST it doesn't really make sense in my eyes.

Ok I understand, so I'm just gonna replace the folder with default expressions and tweak the css, thanks
