### ISSUE TITLE
[BUG] Some translations are not applied

### ISSUE THREAD

**Issue by Touch-Night** [SillyTavern/SillyTavern#2083]
### Environment

🪟 Windows

### System

Windows 10; Microsoft Edge 123

### Version

1.11.7 'release' (4f837824)

### Describe the problem

Some translations in json file were not applied to the page. For example  
```
"Favorite characters to add them to HotSwaps": "收藏角色以将它们添加到快速热切换区",
```
Although  
```
<span data-i18n="Favorite characters to add them to HotSwaps">Favorite characters to add them to HotSwaps</span>
```
It's not applied.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Wolfsblvt** [comment]
That one is likely  a bug because that text gets "pulled" and then inserted into the DOM manually if favs are empty.

Not sure how to fix this, as translations are wacky anyway. Likely have to add a hidden placeholder element and show/hide that depending on the length.
