### ISSUE TITLE
[FEATURE_REQUEST] Optimize the logic for loading character cards

### ISSUE THREAD

**Issue by magicdmer** [SillyTavern/SillyTavern#2085]
### Have you searched for similar requests?

No

### Is your feature request related to a problem? If so, please describe.

I have set up the docker on the Ubuntu 22.04 server. When I ping the server from my machine, the latency is around 200ms. When I click to load character cards, many token query messages are sent, causing the UI to stuck for a while. The higher the latency, the longer the stuck. 

### Describe the solution you'd like
Can this be changed to an asynchronous method without affecting the UI loading?
When i click to load character card,  UI not stuck or give me a loading tip

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
It happens because of timeouts in token counters and token counting being sync. To fix this, token counting should be rewritten to use async server calls. As a temporary workaround, select a local tokenizer (llama? mistral?)

**Comment by Cohee1207** [comment]
Done for character editor. The rest is coming.

**Comment by magicdmer** [comment]
SillyTavern 1.11.8 test very good
