### ISSUE TITLE
 Request to Improve Documentation for Extras local install

### ISSUE THREAD

**Issue by haliliceylan** [SillyTavern/SillyTavern#2086]
I encountered a build error due to missing X11 development libraries when compiling the `praat` project. Here's the specific error message:

```
/tmp/pip-install-39fm099f/praat-parselmouth_3651e0a8134949038a3303aa76cd099e/praat/sys/sendpraat.c:49:18: fatal error: X11/Xlib.h: No such file or directory
    49 | #include <X11/Xlib.h>
```

I've found a solution that involves installing these libraries and would like to update the documentation to help others. The solution that worked for me is as follows:

- For Conda users:
  ```bash
  conda install -c conda-forge xorg-libx11
  ```

- For APT users (like Debian or Ubuntu):
  ```bash
  apt install libx11-dev
  ```
  
  Should we add this to documentation ?

How can I proceed with opening a PR for this documentation improvement?

**Comment by LenAnderson** [comment]
https://github.com/SillyTavern/SillyTavern-Docs/

**Comment by Wolfsblvt** [comment]
Also note that Extras are not really continued anymore.

> Extras project has been discontinued since April 2024 and won't receive any new updates or modules. The vast majority of modules are available natively in the main SillyTavern application. You may still use the Colab notebook but don't expect to get immediate support if you face any issues.

Source: https://docs.sillytavern.app/extras/running-extras-in-colab/

**Comment by haliliceylan** [comment]
@Wolfsblvt if this is the situation, No longer need to add additional comments for docs. thanks.
