### ISSUE TITLE
[FEATURE_REQUEST] proxy password too short

### ISSUE THREAD

**Issue by iqiu2023** [SillyTavern/SillyTavern#2091]
### Have you searched for similar requests?

No

### Is your feature request related to a problem? If so, please describe.

 When using third-party APIs  proxy password  max length too short

### Describe the solution you'd like

increase max length

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

None

**Comment by Cohee1207** [comment]
Increased tenfold: https://github.com/SillyTavern/SillyTavern/commit/8ce6872d6ffcaee4e449a240ccf0fc1a38110468

**Comment by Wolfsblvt** [comment]
Fixed and now released with the latest release.

Cohee, you didn't use the correct wording for issue auto-close :GuraStare:
