### ISSUE TITLE
[FEATURE_REQUEST] <title> add a Yes/No/Global setting option for Recursive Scan for each lorebook

### ISSUE THREAD

**Issue by DoshideDK** [SillyTavern/SillyTavern#2096]
### Have you searched for similar requests?

No

### Describe the solution you'd like

add a Yes/No/Global setting option for "Recursive Scan" for each lorebook, similar to the settings of other options.

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by sirius422** [comment]
I believe this feature has already been implemented in 1.11.8 or earlier.
![image](https://github.com/SillyTavern/SillyTavern/assets/38351200/ad913763-4d53-4ba5-8965-ed0ead63c590)

**Comment by DoshideDK** [comment]
> I believe this feature has already been implemented in 1.11.8 or earlier. ![image](https://private-user-images.githubusercontent.com/38351200/326048081-ad913763-4d53-4ba5-8965-ed0ead63c590.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NzAxNjUsIm5iZiI6MTcxNDU2OTg2NSwicGF0aCI6Ii8zODM1MTIwMC8zMjYwNDgwODEtYWQ5MTM3NjMtNGQ1My00YmE1LTg5NjUtZWQwZWFkNjNjNTkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAxVDEzMjQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhNTA0ZWIxNzU0OWNlNzU4OTQ1MjdlOWViYTFkODNhMzgxNjYzMzU3NDc0YjBkZjlkMjA2MWU5OWExMWUwZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pXYNBjlX_wzl4pO60TfxCgrcAJmaw83WpByT4fk990I)

Thank you for the reminder. However, I'm curious why the developers haven't closed the issue.
