### ISSUE TITLE
[BUG] <title>  source activate xtts  & source activate extras not working

### ISSUE THREAD

**Issue by chicagojoe** [SillyTavern/SillyTavern#2102]
### Environment

🐧 Linux

### System

Mint 21.3.0

### Version

latest

### Desktop Information

Nodejs - 12.22.9, oobabooga release version

### Describe the problem

I'm sorry, I don't code or use git. I've been trying to get the launcher to install and launch with Extras and xtts for 3 days. (AMD if that matters) All I keep getting is 'can not activate environment xtts or extras'. So I looked in the install.sh and saw source activate extras & conda activate extras further on in the file. I figured 'has to be a typo', changed both to source, nothing. Changed both to conda, nothing.

Did some digging on the net cause when I run both of those commands in a terminal on my own they work... Cam across a post on stackoverflow (will provide a link if you need it) and user 'Anthony Scopatz' mentioned a fix for conda 4.6+

````
log_message "INFO" "Activating Conda environment: ${cyan_fg_strong}extras${reset}"
    conda init bash
    eval "$(conda shell.bash hook)"
    conda activate extras
...
...
...
    eval "$(conda shell.bash hook)"
    conda activate xtts
````
    

It seems to work now. Just thought I'd let someone know incase it actually is a bug and not my dumb*** screwing something up.
    
Just in case someone else is having the same issue and finds this, I literally have Zero clues as to what any of that is. I just tried stuff till it worked so wait till someone round here who knows their stuff says 'yeah this works' or 'this guys an idiot' please.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Move launcher discussions to launcher issues: https://github.com/SillyTavern/SillyTavern-Launcher/issues
