### ISSUE TITLE
[BUG] Infinite SillyTavern load on browser

### ISSUE THREAD

**Issue by 13Angels** [SillyTavern/SillyTavern#2107]
### Environment

🪟 Windows

### System

Firefox 118

### Version

1.11.8

### Desktop Information

Node Version: 18.16.1
Branch: Staging

### Describe the problem

When I try to open up SillyTavern on any browser, it loads forever. No error log in the SillyTavern terminal but there is one in the browser.

### Additional info

Firefox console log:
```
Uncaught TypeError: reference is null
    sanitizeServiceSettings http://127.0.0.1:8000/scripts/PromptManager.js:844
    sanitizeServiceSettings http://127.0.0.1:8000/scripts/PromptManager.js:844
    init http://127.0.0.1:8000/scripts/PromptManager.js:318
    setupChatCompletionPromptManager http://127.0.0.1:8000/scripts/openai.js:588
    changeMainAPI http://127.0.0.1:8000/script.js:5880
    getSettings http://127.0.0.1:8000/script.js:6275
[PromptManager.js:844:77](http://127.0.0.1:8000/scripts/PromptManager.js)
    sanitizeServiceSettings http://127.0.0.1:8000/scripts/PromptManager.js:844
    findIndex self-hosted:368
    sanitizeServiceSettings http://127.0.0.1:8000/scripts/PromptManager.js:844
    init http://127.0.0.1:8000/scripts/PromptManager.js:318
    setupChatCompletionPromptManager http://127.0.0.1:8000/scripts/openai.js:588
    changeMainAPI http://127.0.0.1:8000/script.js:5880
    getSettings http://127.0.0.1:8000/script.js:6275
    InterpretGeneratorResume self-hosted:1469
    AsyncFunctionNext self-hosted:852
    
Error: Promised response from onMessage listener went out of scope
```

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
It seems your prompt manager settings are a bit corrupted. I added a failsafe check to the prompt manager init function to let it complete the app initialization. After that you'd need to go to prompt manager settings for chat completion and reset the prompt order (yellow round arrow button).

**Comment by 13Angels** [comment]
That worked! Thank you for the quick fix.
