### ISSUE TITLE
[FEATURE_REQUEST] new marco for char's version

### ISSUE THREAD

**Issue by steve02081504** [SillyTavern/SillyTavern#2111]
### Have you searched for similar requests?

No

### Is your feature request related to a problem? If so, please describe.

For some reason I thought it would be cool to let the character know their version number
But when I put it into the charinfo, I have to change the version number twice every time I release a new version
That's why I wish there was a macro.

### Describe the solution you'd like

`{{char_version}}`

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Wolfsblvt** [comment]
Relatively trivial, but I don't see many use-cases for the char version in a macro tbh, if you can just write it in text. We already have a lot of macros.

Can you tell me your use-case, so I might understand this better?

**Comment by steve02081504** [comment]
> Can you tell me your use-case, so I might understand this better?

I just want the character to know its version number, so that on some UIs that don't implement version number viewing (like some bots in IM) I can just ask it for the version number without having to guess if my update was successful

If possible, I hope to have more macros, such as conversation statistics, the start time of the first conversation, how many words the bot and I chatted in total, and even sth like CPU load.
These can be simple and effective ways to make characters more powerful.

**Comment by Wolfsblvt** [comment]
ooooooh, character stats as macros sounds very, very sexy to be honest.  
I am currently working on a major stats rework for character chat stats, so this would work really well.

Planned with the macro rework adding macros for stats and for the version number sounds like a good idea.  
Right now, I would hold off of that though, as with the current implementation more macros make the system more fragile.

This idea is noted down though, so I'll come back to it.
