### ISSUE TITLE
[FEATURE_REQUEST] Retain the extension settings for the char to the char data

### ISSUE THREAD

**Issue by steve02081504** [SillyTavern/SillyTavern#2114]
### Have you searched for similar requests?

No

### Is your feature request related to a problem? If so, please describe.

Let's say I've made a card, and I've installed the image generation extension and set up an image generation prompt for this card
When I export and re-import char, the data is lost because it's not stored in the role's json/png metadata.
I want the extension to be able to read and write in the role data.

### Describe the solution you'd like

`char.data.extension_data.{{extension uuid}}`

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
Extensions can read and write data to the extension cards - there's a helper function for that.
It's up to the extension author to use that or not.

**Comment by steve02081504** [comment]
okey got it
ty for explan!
