### ISSUE TITLE
[FEATURE_REQUEST] multiple images for character and persona

### ISSUE THREAD

**Issue by etgv2** [SillyTavern/SillyTavern#2115]
### Have you searched for similar requests?

No

### Describe the solution you'd like

multiple images for one character or persona, and you can quickly switch between the images when you expand them in the chat

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
Duplicate.

We have a built-in image gallery extension that covers your request. Open with `/show-gallery` command or "Show Gallery" in the "More" character actions menu.

https://github.com/SillyTavern/SillyTavern/issues/1099

**Comment by etgv2** [comment]
its fine if u cant but id like the same thing for persona's, and the ability to switch between images quicker. also how do i delete images from gallery quickly without going into files?
