### ISSUE TITLE
[FEATURE_REQUEST] .json compatibility with HTML in theme creation

### ISSUE THREAD

**Issue by Incognito15647** [SillyTavern/SillyTavern#2117]
### Have you searched for similar requests?

No

### Is your feature request related to a problem? If so, please describe.

Themes created in ST are limited to an extent. I feel as if it can do with an upgrade to express creativity with the assistance of HTML support.

### Describe the solution you'd like

.json themes can only provide so much, along with custom CSS scripts aswell. 
That is why I was searching online and found this theme:
```https://codepen.io/szrooel/pen/nNNrjy```
It displays a loading screen with HTML, CSS, and .json compatibility all at once.
I believe HTML would be able to have so much more styles than what we have currently. Along with being able to add our own .mp3/.ogg SFXs to add further customisation with ST. Adding a sense of uniqueness that it is ours to keep alone, *or share publicly* to create more engagement with A.I and the whole aesthetic overall.

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
The use of HTML and JavaScript for customization is a territory of extensions.
JSON with Custom CSS for theming should already allow much customization as seen by some well-known examples: https://github.com/nyxkrage/st-discord-inspired/

**Comment by Incognito15647** [comment]
> The use of HTML and JavaScript for customization is a territory of extensions. JSON with Custom CSS for theming should already allow much customization as seen by some well-known examples: https://github.com/nyxkrage/st-discord-inspired/

Well, even though we already have this, I just think it would add more style options and interactivity to ST already, you know? I do not know how to explain further honestly but it would be cool as like a developer type feel with the example I provided.

**Comment by Cohee1207** [comment]
Re: UI sounds. It was attempted here: https://github.com/SillyTavern/Extension-Audio/pull/2

**Comment by Cohee1207** [comment]
Also, STscript is a way to add interactivity with some light coding using a specially crafted esolang, and it's fully shareable using the Quick Replies extension: https://docs.sillytavern.app/usage/st-script/

**Comment by Incognito15647** [comment]
Would this be possible for all accessible devices like mobile and such with the same IP?

**Comment by Cohee1207** [comment]
The IP or device doesn't matter.

**Comment by Incognito15647** [comment]
Alright, just a check, what tutorial would you recommend for learning STScript so that I can customize my own UI in ST?

**Comment by Cohee1207** [comment]
I linked the official language guide above. You can find more resources and example scripts in the ST Discord server.

**Comment by Incognito15647** [comment]
Thank you. You have been so much help! Keep up the excellent work!! xx ❤️
