### ISSUE TITLE
[BUG] <Proxy Error (HTTP 400 Bad Request) >

### ISSUE THREAD

**Issue by Marridreg** [SillyTavern/SillyTavern#2120]
### Environment

🪟 Windows

### System

Firefox 125.0.1

### Version

1.11.8

### Desktop Information

Node v20.12.2, I have tested this with multiple api's, openai and claude, release version, and I've used different versions of claude and gpt.

### Describe the problem

Any time I enter a chat it instantly pops up with the attached error. 
![Screenshot 2024-04-23 at 00-12-27 SillyTavern](https://github.com/SillyTavern/SillyTavern/assets/42444570/f54f40e3-3afc-4915-8387-94656eb3a47c)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
No help or support with proxies.
