### ISSUE TITLE
[FEATURE_REQUEST] Specific Model Option for Image Generation Prompt Generator.

### ISSUE THREAD

**Issue by Abulhanan** [SillyTavern/SillyTavern#2124]
### Have you searched for similar requests?

No

### Is your feature request related to a problem? If so, please describe.

Like using Summarization Extras Api any way to add a separate model for Image Generation Prompt cuz the main api doesn't do what it is asked.

### Describe the solution you'd like

 i was thinking of it like we use seperate summarization models from ST-extras like that.

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
The problem is that the summarization model from Extras does not produce good SD prompts. I tried that more than a year ago before even the Extras project was started, and it did not produce good results. You shall try multimodal captions if you'd like to generate portraits.

**Comment by Abulhanan** [comment]
but how to use that i mainly use Stable diffusion from ST-Extras.

**Comment by Abulhanan** [comment]
or we can use GPT-2 large for that?

**Comment by Cohee1207** [comment]
Stable Diffusion in extras is bad, consider switching to any other of the 10 supported sources.
See the documentation https://docs.sillytavern.app/extras/extensions/stable-diffusion/#stable-diffusion

**Comment by Abulhanan** [comment]
others are simply banned from google colab or kaggle.

**Comment by Abulhanan** [comment]
i use MeinaMix V11 and it's the best for SD for ST-Extras.

**Comment by Abulhanan** [comment]
https://civitai.com/models/7240/meinamix

Or 

https://huggingface.co/Meina/MeinaMix_V11
