### ISSUE TITLE
[FEATURE_REQUEST] Author's Note

### ISSUE THREAD

**Issue by drago87** [SillyTavern/SillyTavern#2125]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

In ST 1.12.0 i see that on Author's Note you can chose to send it as user, system or Assistant (character?).
I would want to be able to send different Author's Note for the different chats (user, system and Assistant)

### Describe the solution you'd like

There could be tabbs on the top of the Author's Note window one for each (user, system and Assistant)
Where you can fill in the information specific for that

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Wolfsblvt** [comment]
We already have the character-specific Author's Notes.

But I figure it would be possible to add that dropdown there too to decide as which to send that one.
Biggest issue there is that Character Author's note either replaces the default AN, or squashes itself together with that one. So two different senders wouldn't really work well.

**Comment by Cohee1207** [comment]
This is not needed since character lorebooks exist. They provide the same prompt injection functionality but you can have as many of them as you like.

**Comment by drago87** [comment]
What i ment is that i want to have one Author's Note for the User and another for the character and maby a third for the system

**Comment by Cohee1207** [comment]
Yes, exactly. You can easily do that in a lorebook. It is much more powerful than the author's note in terms of control over prompt injections.

**Comment by Cohee1207** [comment]
If lorebooks do not satisfy your needs - feel free to propose improvements for them.
