### ISSUE TITLE
[FEATURE_REQUEST] PORTABLE

### ISSUE THREAD

**Issue by marco-trovato** [SillyTavern/SillyTavern#2126]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

The launcher installed conda and the requirements system wide, but i would like it to have a virtual environment, so it could be transportable to another machine on a USB drive.

### Describe the solution you'd like

Just add "python -m venv env" to the launcher :)

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Wolfsblvt** [comment]
The launcher is a different project. This is for Silly Tavern itself.
https://github.com/SillyTavern/SillyTavern-Launcher

You can open feature requests there.

**Comment by Cohee1207** [comment]
Not an ST issue.
