### ISSUE TITLE
[BUG] using llava as backend model can't see image

### ISSUE THREAD

**Issue by yht4work** [SillyTavern/SillyTavern#2139]
### Environment

🐧 Linux

### System

Ubuntu

### Version

22.04

### Desktop Information

node version: v20.12.2

### Describe the problem

first, I deployed a llava and it work normal.
![image](https://github.com/SillyTavern/SillyTavern/assets/92348729/46fb8805-1eb6-4040-90f4-7503ef148e22)

then I fill the address to SillyTavern endpoints
![image](https://github.com/SillyTavern/SillyTavern/assets/92348729/4402757a-00a6-452e-9527-96432a8803d4)

and talk to this system, attached a image and ask what's in it.
![image](https://github.com/SillyTavern/SillyTavern/assets/92348729/88892b0a-3b22-404e-9c4c-20ce37739392)

but it not work as expected.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by sirius422** [comment]
Have you chose the option **Send inline images** inside Chat Completion Presets panel? I noticed that your screenshot did not include this option, so I suspect that this might be what caused the issue.

**Comment by yht4work** [comment]
Thanks for your help. 

yeah, I haven't ticked that option, there is a problem after I turn it on.

![image](https://github.com/SillyTavern/SillyTavern/assets/92348729/31d2071c-111d-4ceb-a015-42e5470879e6)

it's seems the server problem https://github.com/Mozilla-Ocho/llamafile/issues/258 , https://github.com/vllm-project/vllm/issues/2058 the server endpoint should make some modify.
