### ISSUE TITLE
[Feature Request] Character Tags UX improvements

### ISSUE THREAD

**Issue by Ace-Lite** [SillyTavern/SillyTavern#214]
1. Color indexing for tags could be useful for the orientation in the sea of tags. Since there is already an "editor", I don't think UI-wise it should be an issue. (Preferably to keep the current UI glass style, instead of colouring, just light tinting)

2. Speaking of UI and tags, on smaller screen, large amounts of tags can become a problem. Perhaps connecting the character select panel to the tag panel in those cases or making the tags panel sizable could work. There is also the option of a pop-up list.

3. Speaking of the tags editor, there could be an access button from the character select menu.

**Comment by RossAscends** [comment]
Customizable tag coloring has been added into dev branch.
