### ISSUE TITLE
[BUG] IP Connection error

### ISSUE THREAD

**Issue by sndkcd** [SillyTavern/SillyTavern#2140]
### System

iphone chrome, colab

### Version

1.11.8

### Describe the problem

![IMG_2894](https://github.com/SillyTavern/SillyTavern/assets/146307817/fe5b2b50-1c3a-4353-b9fa-12b4adb057ad)

I'm using colab in Chorme on my iPhone. After the 1.11.8 update, I got an IP connection error and I searched for all the information to solve it. I've tried changing whitelist to false in the config file, or using a vpn with zerotiger, or adding my IP address to the whitelist and restarting. But no matter what I do, that error pops up. Did I do something wrong?

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
We don't support hosting on colab. Make sure that the config you are editing is not the default one. It should be next to server.js

**Comment by Cohee1207** [comment]
Also you must set whitelistMode to false. Not the whitelist. That's only as array of IPs
