### ISSUE TITLE
[FEATURE_REQUEST] Jailbreak support for Image prompt templates

### ISSUE THREAD

**Issue by xalyy** [SillyTavern/SillyTavern#2142]
### Have you searched for similar requests?

No

### Describe the solution you'd like

I would like to be able to insert jailbreaks in the image prompts templates. If you try to generate a description prompt for the generated images with Claude it doesnt work since Claude has to be jailbroken for it to work.
A tickable box would be nice where you can enable jailbreaks for it.

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Wolfsblvt** [comment]
I think the better feature would be to have macros work in image gen prompts. That way you could simply add your jailbreak there via its macro, or even put a specific one into a variable.

**Comment by Cohee1207** [comment]
Macros should be working in image prompts without any modifications since day 1 of the ImageGen extension.

**Comment by Wolfsblvt** [comment]
Yup, you are correct.

So you can either use `{{charJailbreak}}` at the beginning of your image prompts,  
or more specific, create your own jealbreak via
```
/setglobalvar key=imageGenJailbreak Write your Jailbreak here
```
and then just add it via `{{getglobalvar::imageGenJailbreak}}`.

**Comment by xalyy** [comment]
> Macros should be working in image prompts without any modifications since day 1 of the ImageGen extension.



> Yup, you are correct.
> 
> So you can either use `{{charJailbreak}}` at the beginning of your image prompts, or more specific, create your own jealbreak via
> 
> ```
> /setglobalvar key=imageGenJailbreak Write your Jailbreak here
> ```
> 
> and then just add it via `{{getglobalvar::imageGenJailbreak}}`.

I can try that, thanks for the suggestion guys. 
Another suggestion I can give is that if there would be an option to choose which language model or API do you want the templates to be handled by, like how it is with image captioning, you can choose multiple APIs.

**Comment by Cohee1207** [comment]
> Another suggestion I can give is that if there would be an option to choose which language model or API do you want the templates to be handled by, like how it is with image captioning, you can choose multiple APIs.

No, this is impossible due to how complex the handling of different models, their settings, and prompts is. You don't simply say "I want this model!", you need to configure specific instruct formatting, select parameters, configure the system prompt, etc.  The list goes on. And with the growing list of supported APIs, this is going to be more and more improbable. STscripts already give control over your currently selected model and its settings - use that instead.

**Comment by xalyy** [comment]
> Yup, you are correct.
> 
> So you can either use `{{charJailbreak}}` at the beginning of your image prompts, or more specific, create your own jealbreak via
> 
> ```
> /setglobalvar key=imageGenJailbreak Write your Jailbreak here
> ```
> 
> and then just add it via `{{getglobalvar::imageGenJailbreak}}`.

Just for clarification how will the prefill get added to this? Because as far as I understand Claude still needs the prefill too.

**Comment by Cohee1207** [comment]
Macros and extensions are not aware of prefills. You have to monitor the generated prompts to figure it out
