### ISSUE TITLE
[BUG] <Stream isn’t working>

### ISSUE THREAD

**Issue by Yone09** [SillyTavern/SillyTavern#2159]
### Environment

📱 Termux

### System

Safari/604.1

### Version

1.12.0-preview

### Desktop Information

Node version 19.6.1
Api from OpenAI 
Model gpt-4
Branch staging

### Describe the problem

I’m using staging branch and today I update it using git pull and now I’m in last release (1.12.1 preview) I used to use my mobile to start tavern by termux and stream it to my other devices (listen is true) Tavren is working on the mobile but in my other devices it just freeze at the loading in the beginning 
I try to go back to the version I was in before the git pull (1.11.8) but I get back all my characters and chats and everything have gone
Then I get back to 1.12.1 and check from mobile everything is back but I still can’t stream tavren to other devices.

### Additional info

![IMG_0078](https://github.com/SillyTavern/SillyTavern/assets/123294012/df037157-b7ac-4a43-9a31-7a15aa759fde)
I stuck here

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Check the browser devtools

**Comment by Yone09** [comment]
> Check the browser devtools
I don’t think it’s available on iPad 
Or I’m just dump

**Comment by Cohee1207** [comment]
Do you have a laptop or a desktop? Androids can also use Kiwi Browser to access devtools.

**Comment by Yone09** [comment]
> Do you have a laptop or a desktop? Androids can also use Kiwi Browser to access devtools.

i checked out, my desktop dont even have this problem just the ipad.

**Comment by Cohee1207** [comment]
I was able to find and fix a problem with the desktop Safari.

**Comment by Yone09** [comment]
> I was able to find and fix a problem with the desktop Safari.

it's fixed, thank you.
