### ISSUE TITLE
[BUG] <title> Character Card with Chinese Name Cannot Be Exported

### ISSUE THREAD

**Issue by yca321** [SillyTavern/SillyTavern#2161]
### Environment

🪟 Windows

### System

Windows

### Version

1.12.0-preview

### Desktop Information

Using Windows environment, download the latest version of sillytavern from git, using start.sh to startup sillytavern

### Describe the problem

While exporting characters with Chinese names using png format, sillytavern could not find the character. I can still locate the png file in SillyTavern-1.12.0-preview\data\default-user\characters folder, and interaction with characters, modifying, add characters are normal. json file output seems normal and will not trigger error msg

### Additional info

Character export failed TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Content-Disposition"]
    at ServerResponse.setHeader (node:_http_outgoing:662:3)
    at D:\SillyTavern\SillyTavern-1.12.0-preview\src\endpoints\characters.js:1100:26 {
  code: 'ERR_INVALID_CHAR'
}

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
https://github.com/SillyTavern/SillyTavern/issues/2127
This was fixed here: https://github.com/SillyTavern/SillyTavern/commit/530bf81940d0d0ad4d082b701736f9bb235ac4fa
