### ISSUE TITLE
In STscript,unable to get a sub value from an array or an object

### ISSUE THREAD

**Issue by ylongly7** [SillyTavern/SillyTavern#2162]
### Environment

📱 Termux

### System

android termux

### Version

newest version

### Describe the problem

/setvar key=arr ["a","b"]
/getvar arr index=0
return empty.
please provide a crorrect example!

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by LenAnderson** [comment]
Read the autocomplete / script help for `/getvar` again.

**Comment by ylongly7** [comment]
I find it.
