### ISSUE TITLE
[FEATURE_REQUEST] <improvment about Data Bank>

### ISSUE THREAD

**Issue by GOLDENLULUZ** [SillyTavern/SillyTavern#2164]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

I tried Data Bank for a while. I like it and also found some problems that need improvement.

### Describe the solution you'd like

1. Toggle box for data sources, allowing us to deactivate some specific data sources temporarily.
2. Up to now I don't know if it's the last message that trigger the search or the whole chat history. Maybe scan depth option would help?
3. Up to now I saw no error message about victorization. Even when I chose a wrong Vector Providers, it still said victorization succeeded, which made me confused. Error message could be a help.

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by GOLDENLULUZ** [comment]
I forgot the most important part. Thank you for working on Sillytavern.

**Comment by Cohee1207** [comment]
> Toggle box for data sources, allowing us to deactivate some specific data sources temporarily.

Done.

> Up to now I don't know if it's the last message that trigger the search or the whole chat history. Maybe scan depth option would help?

Configurable in Vector Storage. With the "Query messages" setting.

> Up to now I saw no error message about victorization. Even when I chose a wrong Vector Providers, it still said victorization succeeded, which made me confused. Error message could be a help.

Done.
