### ISSUE TITLE
[FEATURE_REQUEST] export to Alpaca format for fine-tuning

### ISSUE THREAD

**Issue by win10ogod** [SillyTavern/SillyTavern#2166]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Hello, could you please add the function of exporting conversations to a specific format?
For example, export to Alpaca format for fine-tuning

### Describe the solution you'd like

Added the ability to export conversations to a specific format

### Describe alternatives you've considered

Plugin for exporting conversations into a specific format

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by win10ogod** [comment]
@Cohee1207 Can you implement this feature?

**Comment by Wolfsblvt** [comment]
Chat files are already a pretty straightforward structured `.jsonl`-file.

This could be easily done as an extension, or just writing your own python script to convert it in the format you want.

**Comment by Cohee1207** [comment]
I made this an extension 5 months ago
https://github.com/Cohee1207/SillyTavern-Dataset-Export
