### ISSUE TITLE
[BUG] World Info: "Match Whole Words" only works for... words

### ISSUE THREAD

**Issue by EugeoSynthesisThirtyTwo** [SillyTavern/SillyTavern#2167]
### Environment

🪟 Windows

### System

Firefox

### Version

SillyTavern 1.12.0-preview 'staging' (d9d76ba1)

### Describe the problem

In a World Info entry, type "#hello" in the primary keywords and select "Match Whole Words: Yes"
I expect the entry to be added when the recent text contains "#hello" but due to the "#" character, it's not considered a whole word and thus it's not being added

It happens here:
https://github.com/SillyTavern/SillyTavern/blob/47b656260595967ad70b749845f7b5b33ed3631c/public/scripts/world-info.js#L190
![image](https://github.com/SillyTavern/SillyTavern/assets/24735555/c92e122d-ec45-42d8-ac9d-238d416c3ef7)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Wolfsblvt** [comment]
Acknowledged, reproduced and fixed.

You can text the branch here if you want, or wait for it to be merged.
#2169

**Comment by EugeoSynthesisThirtyTwo** [comment]
Thank you !
