### ISSUE TITLE
[FEATURE_REQUEST] Provides more detailed error information when importing the WI Book error

### ISSUE THREAD

**Issue by steve02081504** [SillyTavern/SillyTavern#2172]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

I'm trying to create a git repo for a card I wrote.
But for some reason, the WIbook data embedded in the PNG file created/updated via code in the repo cannot be read by SillyTavern, the code can be found [here](https://github.com/steve02081504/GentianAphrodite/blob/39eda822626d088949e85f6d4b840d74159b7ab2/src/cardinfo.mjs#L96).
To make matters worse, it doesn't have any error output in web page or console window.
This makes it difficult for me to debug.

### Describe the solution you'd like

I wish there was more error output.

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Wolfsblvt** [comment]
There *should* be debugging messages if parsing the WI info fails.  
Note that all this stuff is handled on the server side (node.js), and not in the actual client on the browser.

You can check here, that is the place where the world info is loaded from an imported `.png`.
https://github.com/SillyTavern/SillyTavern/blob/staging/src/endpoints/characters.js#L373

This is the same method being used to load the saved world info json files, so you can just check their exact format. Or try to debug the server-side at this exact place, and see how your data is being passed in in comparison to an official character card.

**Comment by steve02081504** [comment]
Not sure why it's working now...
thank you for the help!
