### ISSUE TITLE
[FEATURE_REQUEST] Support for single-space indentations with markdown

### ISSUE THREAD

**Issue by SSJGabraham** [SillyTavern/SillyTavern#2176]
### Have you searched for similar requests?

Yes

### Describe the solution you'd like

Add the ability for single-line indentations with bullets (and anything that can be indented in the same way) to be recognized by the UI and rendered properly.

### Example
This text:
```
- bullet 1
 - bullet 2
   - bullet 3
```
should result in:
- bullet 1
  - bullet 2
    - bullet 3
    
 At the moment, it displays like this:
 - bullet 1
 - bullet 2
 - bullet 3

### Describe alternatives you've considered

Naturally it's not so much of an issue if the user is utilizing markdown as they can just use the supported 4-space indentation, but the AI itself might decide to use single-line indentations all on its own with the intent of them rendering as desired above, likely from being fed data where this version of markdown is used, so the result is that the intended indentations are not shown and the data presented is not organized as the AI intended.

### Additional context

I spoke with @LenAnderson regarding this issue who recommended including these two lines in script.js:
![image](https://github.com/SillyTavern/SillyTavern/assets/97507861/98f72912-4fdb-43f5-a9cb-26011cb1b53e)

~~However, he recently pointed out that this screws up the greeting page:~~
It does not screw up the greeting page, I misunderstood.

If this change cannot be filtered in some way to only apply to certain text, this might have destructive ramifications in many parts of the UI, so it would likely need to be tested thoroughly.

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Wolfsblvt** [comment]
While I think markdown nested lists would be nice to have, I'll throw in a quick fix for the time being.
Dunno if the single-space nesting is that easy to use.

Use a custom regex replace on AI output (maybe even user input), and replace it with four times the spaces.  
The following works for nested levels 1-3, which should be enough.

Regex: `/^( {1,3})-/gm`
Replace: `$1$1$1$1-`

See it in action here: https://regex101.com/r/VrrhEg/1

**Comment by LenAnderson** [comment]
> However, he recently pointed out that this screws up the greeting page:

Huh?
Turning off 4-space nesting in showdown does not mess anything up in the greeting message. And I'm not sure what that screenshot has to do with it.

Outside of an actual chat you don't get proper, if any, markdown support. That has nothing to do with this switch.


@Wolfsblvt 
> While I think markdown nested lists would be nice to have, I'll throw in a quick fix for the time being.
Dunno if the single-space nesting is that easy to use.

We already have nested list, just with 4 instead of the commonly used 2 spaces. The showdown option simply enables using 2 spaces (not single spaces) like probably 99% of markdown converters. I don't see how that would make it difficult to use. 
2-space nesting is what most people somewhat familiar with markdown should be accustomed to. And it seems to be (anecdotally) how many LLMs apply markdown as well.

**Comment by SSJGabraham** [comment]
@LenAnderson 
> Huh? Turning off 4-space nesting in showdown does not mess anything up in the greeting message. And I'm not sure what that screenshot has to do with it.
>
> Outside of an actual chat you don't get proper, if any, markdown support. That has nothing to do with this switch.

We talked about it hours ago after I made this issue, I was confused because you said "markdown does not work correctly on the greeting page" and then posted that screenshot, so I thought you were trying to say that adding those two lines it was screwing formatting up on the greeting page and were showing an example of it. That is good to know that the formatting does not escape the chats, though, as it is less worry that changes there will lead to unexpected weird stuff in the UI.

> The showdown option simply enables using 2 spaces (not single spaces) like probably 99% of markdown converters

Are you talking about something other than the `disableForced4SpacesIndentedSublists: true` lines? Because I did try it briefly and was able to do 1 indent easily with a single space, although trying to do a 2 indent resulted in the third item remaining on 1 indent until I added in 4 extra spaces for a total of 5.

Worth noting, my particular model only tried to go 1 indent deep, and I don't often see them use complicated markdown for formatting, so I can only guess how often more complex formatting even turns up. I have a worry, though, that enabling compatibility for, say, 1-space, 2-space, *and* 4-space indenting would be difficult to manage when ST has to guess which one you are trying to use.

**Comment by SSJGabraham** [comment]
Tried some testing with this. The model I am using seems to be inconsistent with its usage of markdown. Sometimes it will use 2 spaces. It seems to be comfortable with using any number of between 1-4 spaces to create a sublist, and then if it tries going deeper to create a second sublist, it will either double the number of spaces for the second sublist or do something weird like 3, then 5 spaces like
```
- Bullet 1
   - Bullet 1.1
     - Bullet 1.1.1
```

At the very least, whatever it chooses for the first sublist gets recognized just fine. I have yet to see it do 4 spaces (or 1.1), then 8 spaces (or 1.1.1), and its only really if it decides to nest a sublist within a sublist that things get tricky.

**Comment by SSJGabraham** [comment]
![image](https://github.com/SillyTavern/SillyTavern/assets/97507861/2ba646db-a7f7-4591-941e-713f58f4e253)
The above picture demonstrates how tabs react when `disableForced4SpacesIndentedSublists: true` is set. Instead of spacing in increments of 1, or 2, bullets are rendered in ranges instead. This will be confusing to anyone who is expecting markdown to behave a certain way, and the alternative is to add behavior in to make it consistent and turn it into an optional setting so it can be toggled which is also not ideal given how many people might actually need or use it. Can maybe place this in an extension of some kind bundled with other formatting customizations including for any other markdown inconsistencies that the user might prefer.

**Comment by Cohee1207** [comment]
I'd prefer to go with it YOLO-style and enable it for all in staging, then wait for user feedback. I don't see any big areas of failure here anyway.

> The model I am using seems to be inconsistent with its usage of markdown

Model skill issues are luckily not something that ST can or should fix.

@SSJGabraham feel free to PR that change in, as it seems you've been running it for quite some time already and would have reported on further issues (if any).

**Comment by Cohee1207** [comment]
No complaints since, I think we're good.

**Comment by Erquint** [comment]
`SillyTavern 1.12.12 'release' (938c8a9a3)`

# Uniform increment nesting indentation widths in counts of spaces from the linebreak.

```md
- 0 spaces indented.
 - +1 = 1 space indented.
  - +1 = 2 spaces indented.
```

```md
- 0 spaces indented.
  - +2 = 2 spaces indented.
    - +2 = 4 spaces indented.
```

Doesn't nest properly.

![Image](https://github.com/user-attachments/assets/fa8cccc5-a8ab-47c3-81d7-e7690970752d)

```md
- 0 spaces indented.
   - +3 = 3 spaces indented.
      - +3 = 6 spaces indented.
```

```md
- 0 spaces indented.
    - +4 = 4 spaces indented.
        - +4 = 8 spaces indented.
```

```md
- 0 spaces indented.
     - +5 = 5 spaces indented.
          - +5 = 10 spaces indented.
```

Does work correctly. Don't mind CSS `tab-size: 8`.

![Image](https://github.com/user-attachments/assets/5c1113bd-2ee7-42d6-aaa2-849f51a6d3f9)

```md
- 0 spaces indented.
      - +6 = 6 spaces indented.
            - +6 = 12 spaces indented.
```

```md
- 0 spaces indented.
       - +7 = 7 spaces indented.
              - +7 = 14 spaces indented.
```

Breaks the list.

![Image](https://github.com/user-attachments/assets/226bae82-942c-4630-b413-c3598611193e)

```md
- 0 spaces indented.
        - +8 = 8 spaces indented.
                - +8 = 16 spaces indented.
```

Breaks the list even worse.

![Image](https://github.com/user-attachments/assets/a9fd3254-c022-4ee9-9961-8a8581d23ab2)

# Non-uniform increment nesting indentation widths in counts of spaces from the linebreak.

Following numbers correspond to uniform space-width of indentation in a list nested like this, topologically:

```md
- 0 spaces indented.
       - + 7 = 7 spaces indented.
```

Works.

![Image](https://github.com/user-attachments/assets/975d7d43-bee5-4335-9c8e-1c07c463334f)

```md
- 0 spaces indented.
        - + 8 = 8 spaces indented.
```

Doesn't work.

![Image](https://github.com/user-attachments/assets/73d5e71b-ba5c-43b0-97a8-2b29232a2e34)

```md
- 0 spaces indented.
       - + 7 = 7 spaces indented.
           - + 4 = 11 space indented.
```

Works.

![Image](https://github.com/user-attachments/assets/602023f1-96e5-428e-b5b3-d17a24b98287)

```md
- 0 spaces indented.
       - + 7 = 7 spaces indented.
            - + 5 = 12 spaces indented.
```

Doesn't work.

![Image](https://github.com/user-attachments/assets/371f1df4-0dc2-40ef-b4c7-b99bd69e6bf6)

```md
- 0 spaces indented.
       - + 7 = 7 spaces indented.
           - + 4 = 11 space indented.
               - + 4 = 15 spaces indented.
```

Works.

![Image](https://github.com/user-attachments/assets/ae1545ee-2ddf-4612-a9ff-faeb58e28b15)

```md
- 0 spaces indented.
       - + 7 = 7 spaces indented.
           - + 4 = 11 space indented.
                - + 5 = 16 spaces indented.
```

Doesn't work.

![Image](https://github.com/user-attachments/assets/42afc1ee-2f99-424b-a95f-4592efa447a1)

# I give up!

```md
- 0 spaces indented.
       - 7 spaces indented.
 - 1 space indented.
```

Losing my mind here…

![Image](https://github.com/user-attachments/assets/f934cd72-87f0-4e03-99e5-d769468cc435)

**Comment by SSJGabraham** [comment]
@Erquint This seems to be consistent with the behavior above [in this post](https://github.com/SillyTavern/SillyTavern/issues/2176#issuecomment-2094400102). I don't believe this change really did what I was hoping, it simply made the requirements for indentations slightly more flexible. Hard for me to say how much of an improvement it really is. In either case if you want the AI to format correctly, you will need to teach it how to do it or it may not look right.

If I'm not mistaken, this comes down to the library ST uses to process Markdown, so it may be a limitation that's difficult to get around. If that library doesn't have an inbuilt solution, then one would need to be found, and if it doesn't exist, it would need to be created. I doubt anyone here will be passionate enough to make custom code to do it. If it's important to you, I would suggest opening a new issue and referencing this one.

**Comment by Wolfsblvt** [comment]
We use [Showdown](https://github.com/showdownjs/showdown), yes.

**Comment by Erquint** [comment]
Installed <https://github.com/LenAnderson/SillyTavern-AlternativeMarkdownConverter> and switched to Marked. That does the job better.  
The extra options of it, though, are better left turned off as they can majorly — but not irrevocably — break functioning of ST.
