### ISSUE TITLE
[FEATURE_REQUEST] STscript slash command, generate without card info

### ISSUE THREAD

**Issue by SSJGabraham** [SillyTavern/SillyTavern#2179]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

No.

### Describe the solution you'd like

All of the commands that generate seem to either omit everything (`/genraw`) or include everything (`/gen`, `/sysgen`) from the character card in the selected chat. On occasion, however, it is helpful to be able to prompt the bot with the chat history alone if you want it to speak as a narrator or objective third party and not be brainwashed into thinking it is one of the characters within the story. Additionally, making it pipable means you can conveniently pipe the output into `/comment` and it will not pollute the chat history if prompting the bot normally after.

This could be added as an argument to a slash command or its own command.

### Describe alternatives you've considered

This can basically be accomplished by creating a blank card and using `/ask`, but `/ask` also overwrites the character you are speaking with after getting a response, so you have to use `/ask` again to set it back to the original. A slight inconvenience. 

There are also ways to force the chat history into the prompt itself but I don't think it plays well with other things like the lorebook scan depth and all of that, and utilizing `/message` does not seem to ignore hidden messages.

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Wolfsblvt** [comment]
What keeps you from using `/genraw` and building the context yourself however you want it, if you have special requirements that differ from the default use-case?

That's actually what that command is for. Giving you full free reign on what you build as a prompt. STscript should give you all the options.

**Comment by SSJGabraham** [comment]
@Wolfsblvt 
That was my first inclination but it is actually kind of a pain in the ass to do. If you utilize the hidden posts function, you can't automatically grab it with `/message` because `/message` also grabs hidden posts within the range and there doesn't seem to be a way weed those out other than to change your script each time. Even if it could, you have to feed it a range, and if all the messages in that range are hidden, that command would output nothing. I also don't think `/genraw` activates lore entries, but I could be wrong.

A specific use for this would be to ask the model about things happening in the story as an objective third party, such as "Create a detailed description of <place> which you could use to create a lorebook entry for it without writing it manually yourself. If that place existing within a larger town or city, then grabbing the message history the way you would through normal chat could provide valuable information, as well as other lorebook information that might exist, but if your character card provides a bunch of information such as what would be included in the personality, character's note, prompt override, etc. then it would fill the prompt with instructions that would pollute the output. I often set some of these things to be added to the prompt with a low depth so you can imagine how that might significantly impact the output.

**Comment by Cohee1207** [comment]
> If you utilize the hidden posts function, you can't automatically grab it with /message because /message also grabs hidden posts within the range and there doesn't seem to be a way weed those out other than to change your script each time

Why not just ask to introduce that as a command argument? That surely would be simpler than hacking the entire prompt builder.

**Comment by Wolfsblvt** [comment]
Not true. Current ST allows grabbing hidden/unhidden messages. It's not trivial, but possible.  
I made a script for that recently.

```
/setvar key=i {{lastMessageId}} |
/setvar key=curMessage > |
/while left=curMessage right=">" rule=eq "/messages names=off \{\{getvar::i\}\}  \| /setvar key=curMessage >\{\{pipe\}\} \| /addvar key=i -1 \| /if left=i right=-1 rule=lt "/abort"" |
/addvar key=i 1 |
/echo i {{getvar::i}} |
/flushvar i |
/flushvar curMessage
```

That grabs the first message id that is not hidden. I explained more on discord. Expand that a bit, and you only grab unhidden messages

[Source on the Discord server](https://discord.com/channels/1100685673633153084/1137348375856029716/1212069717108457514)

But I agree with Cohee, it makes sense to introduce an optional parameter on the `/messages` command, why not. With the new STscript parser its easier as ever.

**Comment by Wolfsblvt** [comment]
There it is: https://github.com/SillyTavern/SillyTavern/commit/14aa70eea88298e383f8eb07b119682f81199b3d

**Comment by Cohee1207** [comment]
```
/messages names=off hidden=on role=user 0-2 | /comment
```

**Comment by SSJGabraham** [comment]
@Cohee1207  
> Why not just ask to introduce that as a command argument? That surely would be simpler than hacking the entire prompt builder.

You say that like I am demanding it be solved this way. Your form asks for a solution so I proposed one. If it's not a good one, that's what discussion is for.

> There it is: [14aa70e](https://github.com/SillyTavern/SillyTavern/commit/14aa70eea88298e383f8eb07b119682f81199b3d)

Appreciated. I will try it out the next time I get an opportunity.

**Comment by Cohee1207** [comment]
An update to `/messages` was released. If you have any more suggestions - reopen or create a new issue.
