### ISSUE TITLE
[BUG] A MovingUI bug when using Visual Novel Mode with Expression images in Group Chats

### ISSUE THREAD

**Issue by introvertedcreature** [SillyTavern/SillyTavern#2181]
### Environment

🪟 Windows

### System

Windows 10

### Version

1.11.8

### Describe the problem

Seems there's a MovingUI bug, when using Visual Novel Mode with Expression images in group chats. The expression images are "stuck" to the bottom of the page, and can only be moved horizontally. Even when resizing, the image jumps back to the bottom. This only happens in group chats; in single character chats, the expression images can be moved anywhere.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Fix released
