### ISSUE TITLE
[BUG] /sysgen not triggering Lorebooks

### ISSUE THREAD

**Issue by drago87** [SillyTavern/SillyTavern#2182]
### Environment

🪟 Windows

### System

Firefox, Win 10, ollama 0.1.32

### Version

1.12.0

### Describe the problem

When trying to use `/sysgen <trigger word>` it seams to not trigger Lorebooks/World Info (Atleast not when bound as a Primary Lorebook or added as a 'Active World(s) for all chats'). If i generate a messege as the character or use the continue the last messege it works.

A side note
When binding a lorebook as a "Primary Lorebook" you loose the abillity to add "Additional Lorebooks". Want me to do a seperate "Feature Request" for that.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
> When binding a lorebook as a "Primary Lorebook" you loose the abillity to add "Additional Lorebooks". Want me to do a seperate "Feature Request" for that.

Not true. Click a world icon while holding "Shift" or select "Link to World Info" from the More... menu.

**Comment by drago87** [comment]
Good to know that clicking the world icon while holding "Shift" works. Should have something like "Hold "Shift" while clicking to change Lorebook" or something like that in the hover over info
