### ISSUE TITLE
[FEATURE_REQUEST] Group Chat Improvement

### ISSUE THREAD

**Issue by steve02081504** [SillyTavern/SillyTavern#2185]
### Have you searched for similar requests?

No

### Is your feature request related to a problem? If so, please describe.

I've noticed that in some communities more people are writing a multichar card than multiple solo cards.
After asking and testing, I think there are certain issues with the current group chat system:
1. The characters barely interact with each other, and they don't know the other characters role set
2. The existing character dialogue triggering mechanism cannot handle episodes where some characters are not present for a certain period of time

### Describe the solution you'd like

1. Let the character know the basic settings of other characters who have been active recently in dialogue
2. Add a character that is not visible to the user to determine the departure and appearance of the characters

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
Not a software issue. Most models are bad at group chats, and that's not something I can solve.

> Let the character know the basic settings of other characters who have been active recently in dialogue

"Join character cards" setting. https://docs.sillytavern.app/usage/core-concepts/groupchats/#join-character-cards

> Add a character that is not visible to the user to determine the departure and appearance of the characters

It's a description of Lorebooks/world info.

**Comment by steve02081504** [comment]
> "Join character cards" setting.

Can we add an additional data segment to the charcard and use that segment when it is available instead of else as the role summary in group chat?
