### ISSUE TITLE
[FEATURE_REQUEST] Allows charcards/WIjsons to embed regex data

### ISSUE THREAD

**Issue by steve02081504** [SillyTavern/SillyTavern#2186]
### Have you searched for similar requests?

No

### Is your feature request related to a problem? If so, please describe.

Some cards/WIbooks require regex to work properly, which makes it very troublesome for us to share, download, and import.

### Describe the solution you'd like

Let's allow regex data to be embedded in charpngs/WIjsons!

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
No. Regex in character cards could be a source of abuse and DoS as well as weird non-debuggable issues due to poor regex.
