### ISSUE TITLE
SillyTavern-1.12.0-preview.   "Forgot password?"  "Rcovert code?" 

### ISSUE THREAD

**Issue by pubgqreen** [SillyTavern/SillyTavern#2190]
I am testing and have a question about SillyTavern-1.12.0-preview.

When I want to reset my password, I click on "Forgot password?" and it shows: "Recovery code has been posted to the server console."

It asks me to enter a "Rcovert code" and a new password in order to change my password.

However, I do not know where to find this code. Could you please tell me where to look for it?

![XXXXX](https://github.com/SillyTavern/SillyTavern/assets/164447524/65e6ac0e-4ebe-4d66-a789-b023a5fb734a)

**Comment by Cohee1207** [comment]
The server console is the command line window that appears when you start ST server.

**Comment by pubgqreen** [comment]
> 伺服器控制台是啟動 ST 伺服器時出現的命令列視窗。

Got it ... found it ... thanks

> The server console is the command line window that appears when you start ST server.
