### ISSUE TITLE
[FEATURE_REQUEST] Change main image through image gallery

### ISSUE THREAD

**Issue by etgv2** [SillyTavern/SillyTavern#2196]
### Have you searched for similar requests?

No

### Describe the solution you'd like

Can you make it possible to change the main avatar of your character through the image gallery? But for the previous messages, keep the same old avatar, just update the new messages with the new avatar. Its good for a character that has transformed or has 2 versions of themselves for example. 

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Wolfsblvt** [comment]
That is very easily achievable through the persona management. Just create multiple persona, with either the same name or slightly varying.

Name and Avatar is saved per message.

**Comment by etgv2** [comment]
I want to do that with characters, but if I do that with characters I have to open a group chat which can be slightly inefficient. You cant use swipe for your persona's, only characters.  I would like it if I could easily change the image without changing previous images via the image gallery.

**Comment by Wolfsblvt** [comment]
That sounds like extension material. Integrating stuff like the expressions and costumes into the inline avatar of the chat.
Not possible in ST core.
