### ISSUE TITLE
[BUG] Gibberish output after few messages when using dolphin-llama3:70b on ollama.

### ISSUE THREAD

**Issue by Mikhael-Danilov** [SillyTavern/SillyTavern#2206]
### Environment

🐧 Linux

### System

ubuntu 22.04

### Version

SillyTavern 1.11.8 'release' (204a9345)

### Desktop Information

node --version
v12.22.9

ollama --version
ollama version is 0.1.34

Model: dolphin-llama3:70b      39cf3e48a70

### Describe the problem

After few messages, chat start output gibberish like:
\\\\\\},""#im)\//­ &#..\\\'\x,8\\,\ for\ \""

Few first message are fine,

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Settings and prompt presets used?

**Comment by Mikhael-Danilov** [comment]
Llama 3 Instruct, tried the other with no visible changes in results.
Also tried different context length, with no visible effect.
