### ISSUE TITLE
[BUG] Recursion not work will with Not ANY

### ISSUE THREAD

**Issue by steve02081504** [SillyTavern/SillyTavern#2213]
### Environment

🪟 Windows

### System

some computer

### Version

10ee002091beacea0710ad4aa4695923115a8805

### Describe the problem

Here is the test json:
![图片](https://github.com/SillyTavern/SillyTavern/assets/31927825/fdf2253f-5aea-4462-91cf-f43c631840fe)
When you type `1 2`, you can see the output on the console: here's a `b` that shouldn't exist.
![图片](https://github.com/SillyTavern/SillyTavern/assets/31927825/115ab916-cf03-4343-89d3-bf4e40f9e232)
![图片](https://github.com/SillyTavern/SillyTavern/assets/31927825/2f5f0986-b36d-4f96-a352-e4691e29ec3b)

### Additional info

```json
{
	"entries": {
		"0": {
			"uid": 0,
			"key": [
				"1"
			],
			"keysecondary": [],
			"comment": "a",
			"content": "a",
			"constant": false,
			"vectorized": false,
			"selective": true,
			"selectiveLogic": 0,
			"addMemo": true,
			"order": 100,
			"position": 0,
			"disable": false,
			"excludeRecursion": true,
			"probability": 100,
			"useProbability": true,
			"depth": 4,
			"group": "",
			"groupOverride": false,
			"groupWeight": 100,
			"scanDepth": null,
			"caseSensitive": null,
			"matchWholeWords": null,
			"useGroupScoring": null,
			"automationId": "",
			"role": null,
			"displayIndex": 0,
			"preventRecursion": false
		},
		"1": {
			"uid": 1,
			"key": [
				"2"
			],
			"keysecondary": [
				"a"
			],
			"comment": "b",
			"content": "b",
			"constant": false,
			"vectorized": false,
			"selective": true,
			"selectiveLogic": 2,
			"addMemo": true,
			"order": 100,
			"position": 0,
			"disable": false,
			"excludeRecursion": false,
			"probability": 100,
			"useProbability": true,
			"depth": 4,
			"group": "",
			"groupOverride": false,
			"groupWeight": 100,
			"scanDepth": null,
			"caseSensitive": null,
			"matchWholeWords": null,
			"useGroupScoring": null,
			"automationId": "",
			"role": null,
			"displayIndex": 1,
			"preventRecursion": true
		}
	}
}
```

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Wolfsblvt** [comment]
This is not a bug, this is intended. A WI entry is not added to the context until all its trigger conditions are checked, its evaluated on trigger%, inclusion group etc. Only then when it will finally be activated, its content will be parsed and looked at, and added to the context.

Other WI entries cannot depend or look at that content until it is fully activated. And they shouldn't.

I also explained it in the PR like this:

> No. Recursion will not remove already triggered entries, and it shouldn't. Ever. I explained this in long detail on discord and the reasons why. You'd run into circular references, endless loops and all that stuff so so fast.
> 
> WI entries on the same sweep (first sweep over context, first recursive run, second, etc) should not really have impact on each other either.
> They get checked against the current context, and optionally against already fully triggered WIs on a sweep before. They will not check against each other.
> 
> The bug is not a bug either, it's just a behavior that we should explain in the docs. And I am planning to, once I am done with the other WI features.
> 
> Besides that, there are obvious other issues with this code, as it'll check items against each other that aren't really activated yet anyway. They might not be added because of trigger% rolls, because of inclusion groups, or any of the other options that are checked later.

**Comment by Cohee1207** [comment]
Functions as intended.
