### ISSUE TITLE
[BUG] TypeError: Only HTTP(S) protocols are supported when connecting to a llama cpp server on 127.0.0.1:8080

### ISSUE THREAD

**Issue by nekohacker591** [SillyTavern/SillyTavern#2220]
### Environment

🪟 Windows

### System

windows 10

### Version

latest as of making this

### Desktop Information

gpu RTX A4000 AMD EPYC 75420 32 dimm ram 

everything else is up to date

### Describe the problem

apon clicking server.exe the model loads up

after putting the url in text completion with llama.cpp connected

it refuses the connection to server with the error

TypeError: Only HTTP(S) protocols are supported refusing my local server

### Additional info

![image](https://github.com/SillyTavern/SillyTavern/assets/73713314/29d27897-1148-4378-8a3f-9f7ab3d2a406)
![image](https://github.com/SillyTavern/SillyTavern/assets/73713314/8e298f3b-eff4-4666-b1cb-58eaed5e951a)
![image](https://github.com/SillyTavern/SillyTavern/assets/73713314/cb4c218b-bd62-4ab6-9995-7518cd0b9288)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
You're missing a protocol in the URL. Add `http://`, look at the example above the text box.
