### ISSUE TITLE
[BUG] Missing API connection with oobabooga and koboldcpp

### ISSUE THREAD

**Issue by grasemydog** [SillyTavern/SillyTavern#2222]
### Environment

🪟 Windows

### System

(Windows NT 11.0; Win64; x64) Chrome 113

### Version

SillyTavern 1.11.8 'release' (204a9345)

### Describe the problem

When I try to connect to the koboldcpp API over the local network, nothing happens (no connection). Similarly, when trying to connect to the oobabooga API, the situation is the same. The API server settings have not been changed. The error occurred after updating SillyTavern.

### Additional info

The server settings have not been changed. But I do not have access to the server to check. The error occurred after updating SillyTavern. Shell not have any errors.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Not reproduced for me or anyone else. Verify that the local network server IP has not changed and it is pingable from your ST host machine - check that firewall and other network settings.

**Comment by grasemydog** [comment]
> network server IP has not changed and it is pingable from your ST host machine

Ping OK
And I can connect directly to the koboldcpp and oobabooga server.
Server run on Windows (http://192.168.1.78:5001)

**Comment by grasemydog** [comment]
The question is closed. The problem was on the server. node.exe was running through a proxy.
