### ISSUE TITLE
[FEATURE_REQUEST] Default settings/characters for new accounts in 1.12.0

### ISSUE THREAD

**Issue by drago87** [SillyTavern/SillyTavern#2227]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

When using enableUserAccounts = true. (If it is not already possible) When you make a new account load settings and characters from a folder so that all users get something the server owner knows work

### Describe the solution you'd like

A button when logged into an Admin account that makes a (multiple) file('s) that contains the current
AI Respons Configuration
API Connections
AI Respons Formating
World Info (Maybe present a list to choose what to export)
Extensions (Only the activated extensions and their settings)
Caracters (Either present a list of all the characters to chose from or link to a folder where you can put characters that will automaticly be inported)
Autor's Notes

That will be automaticly imported when making a new account.

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
https://github.com/SillyTavern/SillyTavern/tree/staging/default/scaffold
