### ISSUE TITLE
[BUG] Some checkboxes in TTS options aren't working

### ISSUE THREAD

**Issue by bobcate** [SillyTavern/SillyTavern#2234]
### Environment

🪟 Windows

### System

Thorium v123.0.6312.133

### Version

SillyTavern 1.11.8 'release' (204a9345)

### Describe the problem

Some checkbox settings in "SillyTavern > Extensions > TTS" aren't working.
Using AllTalk-tts.

Steps to reproduce:
1. Set up SillyTavern and AllTalk to work together
2. Go to "SillyTavern > Extensions > TTS", enable AllTalk
3. Check `Ignore *text, even "quotes", inside asterisks*` and `Skip codeblocks`
4. Open browser console
5. Edit the first message as ``` `test 1` *"test2"* ```
6. Click the Narrate button
7. Observe the browser console, the texts are still passed to the tts server and vocalized

Unless I'm not getting the meanings of those checkboxes, if they were working, nothing would be sent to the tts server.

### Additional info

I [reported this issue to AllTalk](https://github.com/erew123/alltalk_tts/issues/225) first and the dev said those options were managed by SillyTavern. If this is something that requires work on AllTalk, please continue from that ticket.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Can't see a bug here.
1. \`this\` is not a code block, it's an inline code element. And it's not controlled by the setting.
2. "Pass Asterisks to TTS Engine" verify that this setting is disabled. As I wasn't able to reproduce with this off, but when it's on - the text insight of the asterisks is narrated as it should.

**Comment by bobcate** [comment]
Thank you for the clarification. I didn't know 1 was called a different name; and in 2, `Pass Asterisks to TTS Engine` have precedence over `Ignore *text, even "quotes", inside asterisks*`.

Issue resolved, but if you're interested, please keep reading to see why I was trying to use those checkboxes, maybe you'll consider adding a feature.

I'm experimenting with different visual promt formats, trying to see what looks good.
The stucture I decided on was ```Response: *action* "dialogue *"inner voice"* ```
Then I discovered AllTalk, which uses 2 different voices, one for narrator, one for character.
The `*"inner voice"*` in the response doesn't belong to the narrator, and also the character shouldn't vocalize it since it's not spoken. (wish there was a third voice)
So, I wanted the `Ignore *text, even "quotes", inside asterisks*` box to prevent it's passage to the tts server.
The inline code element was part of my experiment, trying to find an alternative way to display the inner voice while not vocalizing it.
