### ISSUE TITLE
[FEATURE_REQUEST] Slash command for rename chat

### ISSUE THREAD

**Issue by Amanoki** [SillyTavern/SillyTavern#2235]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

I usually name each chat manually for better organization, and prefer to rename the chat right after creating it. But compare to the fact that you can easily create a new chat, renaming the chat seems quite cumbersome: open chat manager - click pencil - enter name - click save - close manager.

### Describe the solution you'd like

It would be nice to have a command like `/renamechat (name)` for quick renaming, and also it can be used in QR so I can rename the chat whenever a new one is created.

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Wolfsblvt** [comment]
PR up.

**Comment by Amanoki** [comment]
Thanks so much for the implementation this will be a great help!
