### ISSUE TITLE
[FEATURE_REQUEST] Similar replacement tags to {{// (note)}}, not visible in the chat, but visible for the AI.

### ISSUE THREAD

**Issue by renewbo** [SillyTavern/SillyTavern#2236]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

When creating a character card, different greetings may depict varying relationships between {{char}} and {{user}}, as well as differing thoughts or goals for {{char}}. Including all of this information in the description could unnecessarily lengthen the context as the number of greetings increases.

### Describe the solution you'd like

I have come up with a quick solution that should be able to address this problem. That is to add a replacement tag, the content of which will not be displayed in the chat, but will still be inputted into the model. Think it's quite similar to {{// {note}}}, but visible for the model?

### Describe alternatives you've considered

There should be better solutions to it, but they would likely require more significant changes, so I think this is good enough.

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
HTML comment does what you need.

**Comment by renewbo** [comment]
Thanks, it did!
