### ISSUE TITLE
[BUG] QR message/command edit box is hidden when editing

### ISSUE THREAD

**Issue by creamsan** [SillyTavern/SillyTavern#2237]
### Environment

📱 Termux

### System

Mull 125.3.0

### Version

SillyTavern 1.12.0-preview 'staging' (caf85ad0)

### Describe the problem

Can't see edit box when editing (on mobile).

### Additional info

![Screenshot_20240515-061504_1](https://github.com/SillyTavern/SillyTavern/assets/141376415/6d579718-a58d-47ef-94a9-eb3e2bc77fab)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Fixed in #2242
