### ISSUE TITLE
[FEATURE_REQUEST]  can you add the new maker suite model

### ISSUE THREAD

**Issue by vrihatgan** [SillyTavern/SillyTavern#2240]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

I am always frustrated when cohee not giving me latest model, that Google just launched 

### Describe the solution you'd like

Please Add the model called Gemini 1.5 flash in maker suite

### Describe alternatives you've considered

Add the new model if you haven't done so Gemini 1.5 flash

### Additional context

Gemini 1.5 flash is available 

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
> I am always frustrated when cohee not giving me latest model

💢
