### ISSUE TITLE
[BUG] Group chat card image not changing 

### ISSUE THREAD

**Issue by Dylan1100** [SillyTavern/SillyTavern#2245]
### Environment

🪟 Windows

### System

Firefox

### Version

1.12.0-preview

### Desktop Information

Staging Branch

### Describe the problem

When clicking on the avatar image in a group chat to update it to a single image rather than the default collage image
![Screenshot 2024-05-15 183146](https://github.com/SillyTavern/SillyTavern/assets/57307744/67be3466-53d2-45a0-a1ab-daec6bb9fd1e)

the prompt to crop the new avatar appears 
![Screenshot 2024-05-15 183237](https://github.com/SillyTavern/SillyTavern/assets/57307744/06930626-36bd-4c2b-8e8f-ea98824d87cb)

But afterwards doesn't update the image. It will instead keep the collage image as if nothing had changed. It gives the option to revert back to the collage avatar as if it had been updated.
![Screenshot 2024-05-15 183411](https://github.com/SillyTavern/SillyTavern/assets/57307744/5ff7c930-4d83-41b3-80a1-f747bce6e613)

Refreshing the browser or restarting sillytavern doesn't fix it. Tried on both firefox and chrome. Nothing appears in the console. Ran without any extensions and same issue. 

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Should be fixed now.
