### ISSUE TITLE
[FEATURE_REQUEST] <title> Is it possible to access with ipv6 address

### ISSUE THREAD

**Issue by a542557923** [SillyTavern/SillyTavern#2250]
### Have you searched for similar requests?

Yes

### Describe the solution you'd like

Due to the shortage of ipv4 addresses, I had to use ipv6 in order for me to access my computer remotely

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
Yes. As long as the port is open and everything is configured correctly - there's no difference between IPv4 and IPv6 for the app server.
