### ISSUE TITLE
[BUG] Unexpected behavior with subcommand in quotes

### ISSUE THREAD

**Issue by creamsan** [SillyTavern/SillyTavern#2254]
### Environment

📱 Termux

### System

Mull 125.3.0

### Version

SillyTavern 1.12.0-preview 'staging' (517da9f9)

### Describe the problem

The exection goes through despite using /abort with quotes. {: ... :} works fine though.

### Additional info

![Screenshot_20240516-235408_1](https://github.com/SillyTavern/SillyTavern/assets/141376415/4c935d88-3cc0-4a14-868d-6898685d6f5e)

![Screenshot_20240516-235239_1](https://github.com/SillyTavern/SillyTavern/assets/141376415/92a41cac-b29f-4c72-82fe-a1071a524f3b)

![Screenshot_20240516-235307_1](https://github.com/SillyTavern/SillyTavern/assets/141376415/6e8eab4a-6b81-45e1-8751-182834d9ce1d)

![Screenshot_20240516-235315_1](https://github.com/SillyTavern/SillyTavern/assets/141376415/0b1808f3-60f2-4cc0-9fbe-6cc782ad5fb0)

![Screenshot_20240516-235907_1](https://github.com/SillyTavern/SillyTavern/assets/141376415/cf7de155-c7e1-49be-b92d-de8268d4cb06)

![Screenshot_20240516-235722_1](https://github.com/SillyTavern/SillyTavern/assets/141376415/54e608ae-1a03-44f3-bdfb-6b1362a3ae97)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
@LenAnderson does the abort not immediately stop the execution in the new parser when encountered in a subcommand?

**Comment by LenAnderson** [comment]
My guess would be that subcommands are called with handleExecutionErrors set to true. Should be false so that the exception gets rethrown and reaches the proper scope.
I can take a look tonight.


________________________________

**Comment by Cohee1207** [comment]
> Should be false so that the exception gets rethrown and reaches the proper scope.

I believe that's all to it.
