### ISSUE TITLE
[BUG]In the lorebooks management panel, when in the Custom sorting mode, entries may be incorrectly placed above the table header.

### ISSUE THREAD

**Issue by Kas1o** [SillyTavern/SillyTavern#2262]
### Environment

🪟 Windows

### System

Windows 10

### Version

SillyTavern 1.12.0-preview 'staging' (c52bdb9a) (also happens in release)

### Describe the problem

![image](https://github.com/SillyTavern/SillyTavern/assets/88198563/730603b1-ae33-4fb9-9e0c-4ace1a351fc7)

When I try to drag an entry upwards, it produces the effect shown in the image.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Fixed in https://github.com/SillyTavern/SillyTavern/commit/a398566b33d43bb19950d01eebdf680e01075f32
