### ISSUE TITLE
[BUG] /while not looping

### ISSUE THREAD

**Issue by creamsan** [SillyTavern/SillyTavern#2268]
### Environment

📱 Termux

### System

Mull 125.3.0

### Version

SillyTavern 1.12.0-preview 'staging' (d9b55df8)

### Describe the problem

Title

### Additional info

![Screenshot_20240519-125650_1](https://github.com/SillyTavern/SillyTavern/assets/141376415/82025759-668c-4e54-abdc-2e03d619219b)
![Screenshot_20240519-125736_1](https://github.com/SillyTavern/SillyTavern/assets/141376415/9074f42c-8f6e-426d-bde7-46593841c48b)

Expected to work like times
![Screenshot_20240519-125746_1](https://github.com/SillyTavern/SillyTavern/assets/141376415/c9153616-cc0d-4974-a326-fb45c762a0ad)
![Screenshot_20240519-125757_1](https://github.com/SillyTavern/SillyTavern/assets/141376415/2c323092-c8d5-483b-bab2-71cd17eb8390)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by creamsan** [comment]
Fixed when using {: ... :}. But there's a new error when using quotes.
![Screenshot_20240519-220119_1](https://github.com/SillyTavern/SillyTavern/assets/141376415/2baba2d8-4507-4310-a51e-9f972ae4634e)
![Screenshot_20240519-220137_1](https://github.com/SillyTavern/SillyTavern/assets/141376415/ea0e8730-dccc-4a69-805c-3cc8172d9e89)

**Comment by Cohee1207** [comment]
@LenAnderson did we even have multiline subcommands though?

**Comment by LenAnderson** [comment]
Yes and they still work. I suspect there's a space after the closing quote in the example above. Parser does not seem to like that and that was the only way I found to reproduce the issue.

So, either end with the final quote, or put a pipe behind it.
Then again, quoting the unnamed argument is a bit pointless if you don't use strict escaping and escape the pipes anyways. 

I'll look into that later today. The way quoted subcommands are done is a bit iffy at the moment.
