### ISSUE TITLE
[BUG] Questions about basicAuthUser authentication in version 1.12.0

### ISSUE THREAD

**Issue by magicdmer** [SillyTavern/SillyTavern#2278]
### Environment

🐧 Linux

### System

ubuntu 22.04

### Version

1.12.0

### Describe the problem

I need to turn off the whitelist to open to the public, but to turn off the whitelist, I must turn on the basicAuthMode field. Now that the new version has a multi-user management function, it should be changed to either basicAuthMode or enableUserAccounts to turn off the whitelist, otherwise you need to authenticate twice.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Works as expected. Passwords are not required for user accounts and do not provide an adequate level of security. 
If you're confident about your setup, set securityOverride to true, but this is not recommended, as well as hosting public instances.
You are taking FULL RESPONSIBILITY for potential security risks. AGPLv3 license does not provide any warranty or liability for any damages.

**Comment by magicdmer** [comment]
> Works as expected. Passwords are not required for user accounts and do not provide an adequate level of security. If you're confident about your setup, set securityOverride to true, but this is not recommended, as well as hosting public instances. You are taking FULL RESPONSIBILITY for potential security risks. AGPLv3 license does not provide any warranty or liability for any damages.

Thanks for your explanation, I didn't notice that account management can be set without a password now, which is indeed unsafe, but fortunately there is a securityOverride field
