### ISSUE TITLE
[BUG] speech recognition button does not reset

### ISSUE THREAD

**Issue by VoicelessCoffee** [SillyTavern/SillyTavern#2279]
### Environment

🪟 Windows

### System

Windows 10

### Version

1.12.0 'staging' (863e0c36)

### Describe the problem

the botton to start the speech recognition does not reset after the message was recorded and send. Have to push the button twice to start a new recordning.
Encountered this with whisper and browser speech recognition provider (others I have not tested).

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Move it here
https://github.com/SillyTavern/Extension-Speech-Recognition/
