### ISSUE TITLE
Deprecation warning: `punycode` module

### ISSUE THREAD

**Issue by Solomon1732** [SillyTavern/SillyTavern#2280]
### Environment

🪟 Windows

### System

Brave v1.66.110

### Version

1.12

### Desktop Information

- Node.js v21.7.3
- Kobolde Horde
- Branch release

### Describe the problem

Whenever I start SillyTavern, the console throws this warning:
> (node:15164) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

### Additional info

![image](https://github.com/SillyTavern/SillyTavern/assets/16454223/a894d63f-f26d-400b-876d-fa9507dc6c00)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Unsolvable until the https://github.com/node-fetch/node-fetch/issues/1797 is resolved.

To be fair, it doesn't prevent you from using any functionation, nor affect the performance, or anything.

**Comment by Cohee1207** [comment]
Resolved in staging
