### ISSUE TITLE
[BUG] Unable to verify key while using Groq api

### ISSUE THREAD

**Issue by Elevenlong1101** [SillyTavern/SillyTavern#2283]
### Environment

🪟 Windows

### System

edge 125.0.2535.51

### Version

SillyTavern 1.12.0 'release' (ab75680e)

### Desktop Information

node version v20.10.0

### Describe the problem

I just installed sillytavern and didn't change any settings
I used the Chat Completion API and Groq in Chat Completion Source, after input the right API key, I clicked the connect button, and it replied this "Unable to verify key; press "Test Message" to validate." , so i click the "Test Message", and error pops out.
![image](https://github.com/SillyTavern/SillyTavern/assets/96627843/36afbc01-7e80-4286-9428-3ce8615c4f0e)

### Additional info

![image](https://github.com/SillyTavern/SillyTavern/assets/96627843/e4ee933c-9a1a-4dbb-85bd-3997209a53de)
this is the log in the command line
i have read the docs of Groq , and find out this maybe the reason of it 
![image](https://github.com/SillyTavern/SillyTavern/assets/96627843/4a2e8cc7-b68a-46b8-8179-eed664ddb619)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Elevenlong1101** [comment]
I don't know how to code and hopes someone can fix it : )

**Comment by Cohee1207** [comment]
Forbidden means that the API actively refused you access. Not related to SillyTavern. Contact Groq support and ask why.

**Comment by Elevenlong1101** [comment]
I tried several different keys and it just constantly tells me that I was forbidden QAQ

**Comment by Elevenlong1101** [comment]
sorry, problem solved, I was using VPN, so trun on the tun mod will solve it
