### ISSUE TITLE
[FEATURE_REQUEST] personas @D

### ISSUE THREAD

**Issue by steve02081504** [SillyTavern/SillyTavern#2284]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

I have a friend who has found that his personas don't always work, and he'd like to have personas that can be put on AT DEPTH (`@ D`) as well as WIbook.

### Describe the solution you'd like

Support for at depth for personas.

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
Done in https://github.com/SillyTavern/SillyTavern/commit/3dc4c8ca392b1682847d199552dbbc352a0e73aa

**Comment by steve02081504** [comment]
ty for ya help!
