### ISSUE TITLE
[BUG] Full screen STscript editor is unusable (Quick Reply)

### ISSUE THREAD

**Issue by valden80** [SillyTavern/SillyTavern#2285]
### Environment

🐧 Linux

### System

Various browsers, Manjaro current.

### Version

SillyTavern1.12.0 staging

### Desktop Information

 - OS/Device: Manjaro Linux
 - Environment: local
 - Node.js: version 20.2.0
 - Browser: Various
 - Generation API: Oobaboga
 - Branch: staging
 - Model: any local

### Describe the problem

When I try to edit scripts, I got these problems in the full screen script editor (after button with vertical ... ).

In Firefox: I can't edit scripts body at all - text area field with them is disabled to RO state. Don't allow to put cursor in it.

In Vivaldi, Chromium: Cursor don't represent actual place where next typed letter will be put. It always like several letters back from cursor - if cursor and actual font has different widths for the every letter and maybe spaces changed for tabulations for cursor. Mouse become useless completely (can't be guessed where will be next letter for the cursor position), with keyboard arrows still possible to make blind entering position change by counting letters on pressing arrows.

I guessing it's strongly related to the interactive syntax help pop-ups, as they also make cursor jump around the string when they appears.

### Additional info

No error logs, on screenshot it's not exactly visible. Maybe I can make some videos later (don't has any video screencap software right now.)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Wolfsblvt** [comment]
@LenAnderson might be something for you to look at?

**Comment by LenAnderson** [comment]
> @LenAnderson might be something for you to look at?

Waiting for the screenshots. All I can see is some issues with autocomplete in FF. Rest looks fine.

**Comment by valden80** [comment]
@LenAnderson @Wolfsblvt This is how it behave in the all chrome based browsers. Vivaldi, Chromium, etc. Without extensions, on clean profile.
https://github.com/SillyTavern/SillyTavern/assets/111227649/a8ee9e12-9994-42fe-9fcf-61b0c70ce0a4

**Comment by valden80** [comment]
And this is how it looks in FireFox:

https://github.com/SillyTavern/SillyTavern/assets/111227649/ea32dbc6-15d7-4167-a087-337c73ad86e5

**Comment by LenAnderson** [comment]
**Please list the versions for each of the tested browsers.**

In the Chromium based example, Something's fucked up with your fonts. Check if you have any custom CSS (in ST or in your browsers), any extensions (in ST or in your browser) that might touch input fields in *any* way, even if you don't think it is related.
The glyphs in the textarea font seem to be wider for some reason than the font used for syntax highlighting. Clearly visible when you selected text and the textarea-content showed through. Although it seems to be a monospace font as far as I could tell.
Any OS settings for font scaling or high-DPI displays?

Might also be an idea to right-click > inspect element the textarea to see what kind of font, size, padding, etc. is actually applied to that element. And to the neighboring syntax highlight element (pre > code).

In Firefox it looks like half of the styles are not even applied. Stuff is all over the place. And the reason you cannot click into the textbox is most likely that the actual text box is the container *below* the text that you see.

**Comment by valden80** [comment]
@LenAnderson When I make these videos, I don't have any custom CSS, any browser extensions (I created a clean profile for testing), and I even make new install for ST. After it, I even create the new user in my system - to exclude any user-based personal settings. Still the same results.
I don't have any non-standard fonts in system either. Actually it maybe related to issue - In my current system no proprietary M$ Windows fonts installed, only open source fonts - those that come with Manjaro itself. So if ST want use strictly M$ fonts in CSS - it may be substitution problem for render in browsers... 

But I don't has similar problems ANYWHERE else. Not on any other web-pages, and nowhere otherwise in ST.
And this is for both - chromium based and firefox based issue. 
Now I can't use this editor in ANY browser. If you can't catch the real problem, can you at least make it switchable to simple textarea (as in previous ST version where is no problems with it)? 

Vivaldi: 6.4.3160.42 (Stable channel) stable
Chromium: 119.0.6045.159
Firefox: 119.0.1
I have standard FullHD 1920x1080 screen, no HighDPI settings turned on. ( 96 DPI )

P.S. There is no issues with recent similar changes in the WI keys field. I still prefer plain text for keys, but switching to fancy GUI worked normally for them - no formatting or cursor issues.

**Comment by LenAnderson** [comment]
All your browsers are severely outdated. Please update your browsers and try again to see if the issues persist.

Vivaldi is from November 2023.
Chromium and Firefox are from October 2023.



________________________________

**Comment by valden80** [comment]
@LenAnderson Ok, this it what inspection says in Vivaldi (sorry if it's not what you want - I have some experience with HTML/CSS but LONG time ago, and almost no experience for current standards). 
This is what applied to editor's textarea.

Font used for element:
``` Noto Sans Mono—Local file(131 glyphs)```

Other:
```appearance auto
background-attachment scroll
background-clip border-box
background-color rgba(0, 0, 0, 0)
background-image none
background-origin padding-box
background-position-x 0%
background-position-y 0%
background-repeat-x repeat
background-repeat-y repeat
background-size auto
border-bottom-color rgb(69, 69, 69)
border-bottom-left-radius 5px
border-bottom-right-radius 5px
border-bottom-style solid
border-bottom-width 1px
border-image-outset 0
border-image-repeat stretch
border-image-slice 100%
border-image-source none
border-image-width 1
border-left-color rgb(69, 69, 69)
border-left-style solid
border-left-width 1px
border-right-color rgb(69, 69, 69)
border-right-style solid
border-right-width 1px
border-top-color rgb(69, 69, 69)
border-top-left-radius 5px
border-top-right-radius 5px
border-top-style solid
border-top-width 1px
box-sizing border-box
caret-color rgb(255, 255, 255)
color rgba(0, 0, 0, 0)
color-scheme light only
column-count auto
cursor text
display block
font-family monospace
font-feature-settings normal
font-kerning auto
font-optical-sizing auto
font-size 15px
font-stretch 100%
font-style normal
font-variant-alternates normal
font-variant-caps normal
font-variant-east-asian normal
font-variant-ligatures normal
font-variant-numeric normal
font-variant-position normal
font-variation-settings normal
font-weight 400
grid-column-end auto
grid-column-start 1
grid-row-end auto
grid-row-start 1
height 612.297px
letter-spacing normal
line-height 18px
margin-bottom 0px
margin-left 0px
margin-right 0px
margin-top 0px
max-height 834.3px
mix-blend-mode difference
outline-color rgba(0, 0, 0, 0)
outline-style none
outline-width 0px
overflow-wrap break-word
padding-bottom 11.25px
padding-left 11.25px
padding-right 11.25px
padding-top 11.25px
resize none
tab-size 4
text-align start
text-indent 0px
text-rendering auto
text-shadow none
text-transform none
text-wrap nowrap
white-space-collapse preserve
width 1319.16px
word-spacing 0px
writing-mode horizontal-tb
-webkit-font-smoothing antialiased
-webkit-rtl-ordering logical
```

**Comment by valden80** [comment]
@LenAnderson Browsers updating with the system update. There is a war in my country, and so - very unstable power supply now. Too risque to update system right now - with loss of power in the process it will be a mess. :(

Also - a half year is "outdated beyond usability"? Really?

**Comment by LenAnderson** [comment]
Yes, that should be helpful, can you do the same for the `<pre>` (and the `<code>` inside the pre) next to the `<textarea>`?


________________________________

**Comment by valden80** [comment]
@LenAnderson This is for the "pre":

Font:
``Consolas—Local file(131 glyphs)``

Other:
```
backdrop-filter none
border-bottom-color rgb(255, 255, 255)
border-bottom-style none
border-bottom-width 0px
border-image-outset 0
border-image-repeat stretch
border-image-slice 100%
border-image-source none
border-image-width 1
border-left-color rgb(255, 255, 255)
border-left-style none
border-left-width 0px
border-right-color rgb(255, 255, 255)
border-right-style none
border-right-width 0px
border-top-color rgb(255, 255, 255)
border-top-style none
border-top-width 0px
box-sizing border-box
color rgb(255, 255, 255)
color-scheme light only
display block
font-family monospace
font-size 15px
grid-column-end auto
grid-column-start 1
grid-row-end auto
grid-row-start 1
height 679.797px
margin-bottom 0px
margin-left 0px
margin-right 0px
margin-top 0px
min-width 100%
overflow-x hidden
overflow-y hidden
padding-bottom 0px
padding-left 0px
padding-right 0px
padding-top 0px
text-align left
text-shadow rgba(0, 0, 0, 0.72) 0px 0px 2px
width 1350.66px
-webkit-font-smoothing antialiased
```

**Comment by Cohee1207** [comment]
I believe this comes from using different fonts for two elements?

**Comment by LenAnderson** [comment]
You should be able to update your browsers without updating your OS.
And yes, half a year is a *very long time* in terms of browser updates. Not just in terms of features (web moves fast and ST tends to use some fairly recent stuff once all major browsers support it), but even more so for security patches.


________________________________

**Comment by Cohee1207** [comment]
Might be worth prebaking some cool monospace font into frontend files (same as we do now with Noto Sans) and setting it as a font-face with default system monospace as a fallback.

**Comment by LenAnderson** [comment]
Yes, different fonts was my now confirmed suspicion. Consolas vs noto mono.
Now need to check why...

**Comment by valden80** [comment]
@LenAnderson Browser updates integrated in the system packet manager. Manjaro is a rolling distro, it's don't really support partial updates. I can try to update only browser, but even is has 50/50 chance to start after (as glibc is updated from previous time - most programs shall be updated after this).

Upd: Ok, I will make sacrifice with chromium - if it will not work after update I can live with it.

**Comment by LenAnderson** [comment]
Should be possible to install software without package manager. 
From manjaro wiki: 
> Generally it is better to use the version of Firefox that is available in the repos but installing Firefox directly has one advantage: Firefox will update itself automatically as soon as an update is available. This is great for users, who want to get the latest update as soon as possible without waiting for the next Manjaro update.

**Comment by valden80** [comment]
@LenAnderson: Direct installs broke the same way in case when I can't make regular full update.
And chromium is broken now:
```/usr/lib/chromium/chromium: error while loading shared libraries: libicui18n.so.74: cannot open shared object file: No such file or directory```

**Comment by LenAnderson** [comment]
Well, that sucks. Weird that updates of third-party software would be coupled so tightly to OS updates.

**Comment by LenAnderson** [comment]
In Vivaldi, could you use inspect to make both the textarea and the pre/code use the same font and check if that fixes the misalignment? Just want to know if that is the only issue there of if there's more.

**Comment by valden80** [comment]
@LenAnderson I rolled back older chromium version, so I have it back.

But I can't find where and how to edit code in inspect for using one font. Not in Chromium, not in Vivialdi (inspect almost the same in boths).

P.S. Power been out and returned just now - that why I go silent for half hour..

**Comment by Wolfsblvt** [comment]
Open the dev tools, then select an HTML element. Likely one of the parents, and go here:
![image](https://github.com/SillyTavern/SillyTavern/assets/9962104/3639d4ef-6168-4045-934e-4dce068cc3ff)

Write something like this. Add the `!important` if there might be other rules overriding the fonts, so we can be sure.
![image](https://github.com/SillyTavern/SillyTavern/assets/9962104/590f9671-f8ae-4fda-ba71-e128987d52fa)

```css
font-family: "Consolas" !important;
```

**Comment by LenAnderson** [comment]
https://github.com/SillyTavern/SillyTavern/assets/7149120/17f045f7-653e-4575-9723-ed316c807158

**Comment by valden80** [comment]
@LenAnderson Yes, it seem's to be it.
When I adding ``font-family: "Consolas" !important;`` to the textarea (editor itself) - cursor starting to work normally. Code, pre, div, up from the textarea - no changes, issue present.

**Comment by LenAnderson** [comment]
Ok, so that's an easy fix for the chromium based browsers.
For the old FF's and other ancient browsers I'll just add a plaintext toggle.

**Comment by valden80** [comment]
@LenAnderson Sorry to disturb, but do this fix been pushed to staging or not? 
Right now after today's pull I still having this issue...
I been out for a while, and can't find/track it myself. I don't want to hurry you - I just asking to be sure that fix is effective if it's already done.

**Comment by Cohee1207** [comment]
The latest update I've heard is that Firefox is still being a nuisance.
