### ISSUE TITLE
[BUG] Chat Translation not translating after Edit & Confirm

### ISSUE THREAD

**Issue by renewbo** [SillyTavern/SillyTavern#2289]
### Environment

🪟 Windows

### System

Edge 124.0.2478.97

### Version

SillyTavern 1.12.0 'release' (db2c9a99), or after SillyTavern 1.12.0-preview 'release' (d51b155e)

### Desktop Information

- Node.js: v18.18.0
- Branch: release

### Describe the problem

Using the `Chat Translation` Extensions, with settings below:
Auto-mode: Translate both
Provider: Google
Target Language: Any other translatable language

Click `Edit` in the dialogue box, then click `Confirm`
![1](https://github.com/SillyTavern/SillyTavern/assets/151473348/aa7f4605-2eef-44ac-8336-91ef9b02acf3)

Before (d51b155e), the translated content would immediately appear.
![2](https://github.com/SillyTavern/SillyTavern/assets/151473348/ed98e291-3b02-4429-a76b-e8bba5a8d66e)

However, after (d51b155e), the dialogue box shows no change.
![3](https://github.com/SillyTavern/SillyTavern/assets/151473348/ad05ff41-7ca6-4be4-96f8-5fc190345c29)
It did translate in the console output, but didn't show up in the dialogue.

I'm not sure if it's an intentional feature, but I feel the original one was more convenient?

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Fixed in: https://github.com/SillyTavern/SillyTavern/commit/c21deb3a8c6e9b71b544eef42c0fca2894935e12

This was related to the split of message edit events.

**Comment by renewbo** [comment]
It's working fine now, thanks.
