### ISSUE TITLE
[BUG] <AI image tag send format error>

### ISSUE THREAD

**Issue by DysAnia1013** [SillyTavern/SillyTavern#2290]
### Environment

📱 Termux

### System

5.4.0-174-generic

### Version

1.12.0

### Describe the problem

I would like to give feedback on a bug and a suggestion.
The bug is that sillytavern removes the {} symbol from the tag when generating the AItag and sending it to novelai causing the weights to not be added. Only the prompt located in the Common prompt prefix will be sent correctly.
before sending:
 ```
Claude response: {
  id: 'msg_01MdAsqfbJzhwkTCq7puMN7r',
  type: 'message',
  role: 'assistant',
  model: 'claude-3-opus-20240229',
  stop_sequence: null,
  usage: { input_tokens: 8771, output_tokens: 140 },
  content: [
    {
      type: 'text',
      text: '1girl, {{sparkle_(honkai:_star_rail)}}, pinky eyes, butterfly-shaped pupils, black tear-shaped mole under eyes, very long black hair, twintails, red white black kimono, red rope, black collar, golden bell, red white fox mask, red nail polish, barefeet, lying, sleeping, pretending to sleep, eyes closed, mouth open, tongue out, saliva trail, small breasts, slim, pale thighs, red string anklet, spreading legs, {deepthroat}, {penis in mouth}, {fellatio}, {close-up}, {pov}'
    }
  ],
  stop_reason: 'end_turn',
```
after sending:
```
NAI Diffusion request: {
  prompt: '{artist:misaka_12003-gou}, [artist:omone_hokoma_agm], [artist:gongha], [artist:houkisei], [[artist:ask_(askzy)]], {best quality}, masterpiece, highres, {absurdres}, extremely detailed CG unity 8k wallpaper, detailed face, detailed hair, nsfw, 1girl, sparkle (honkai: star rail), pinky eyes, butterfly-shaped pupils, black tear-shaped mole under eyes, very long black hair, twintails, red white black kimono, red rope, black collar, golden bell, red white fox mask, red nail polish, barefeet, lying, sleeping, pretending to sleep, eyes closed, mouth open, tongue out, saliva trail, small breasts, slim, pale thighs, red string anklet, spreading legs, deepthroat, penis in mouth, fellatio, close-up, pov',
  model: 'nai-diffusion-3',
  sampler: 'k_dpmpp_2m',
  steps: 28,
  scale: 7,
  width: 832,
  height: 1216,
  negative_prompt: 'lowres, {bad}, error, fewer, extra, missing, worst quality, jpeg artifacts, bad quality, watermark, unfinished, displeasing, chromatic aberration, signature, extra digits, artistic error, username, scan, [abstract], lowres, {bad}, error, fewer, extra, missing, worst quality, jpeg artifacts, bad quality, watermark, unfinished, displeasing, chromatic aberration, signature, extra digits, artistic error, username, scan, [abstract], lowres, {bad}, error, fewer, extra, missing, worst quality, jpeg artifacts, bad quality, watermark, unfinished, displeasing, chromatic aberration, signature, extra digits, artistic error, username, scan, [abstract], lowres, {bad}, error, fewer, extra, missing, worst quality, jpeg artifacts, bad quality, watermark, unfinished, displeasing, chromatic aberration, signature, extra digits, artistic error, username, scan, [abstract], lowres, bad anatomy, bad hands, text, error, {weibo username}, [weibo logo], bisexual',
  upscale_ratio: 1,
  sm: true,
  sm_dyn: false
```
I think this is a bug and that the () symbol is sent correctly if stable diffusion is used, only the {} for novelai is removed.

Also I would like to make a suggestion, can the order of prompts in style be freely adjustable by the user? Right now the common prompt will be at the top and the character prompt is fixed after it, but the character tag is very important to the generated result of the AI painting and usually needs to be placed in the first tag, otherwise it will be overwritten by the later prompts leading to invalidation.
If I want to put the character tag in the front, I have to put it in the common prompt, but that would be a pain in the ass when switching between character cards, so I'd like to be able to give the user the freedom to adjust the order of the prompts for the various modules, just like the chat presets.
<img width="432" alt="61439e364418825b37f1f585bb138ac9" src="https://github.com/SillyTavern/SillyTavern/assets/92561928/811e6ebb-a8a4-48fb-9128-34f498857260">

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
The first part was trivial to fix - curly braces are now allowed in the LLM output (staging branch).
The second part would be more tricky. By the way, did you know that you can use the `{prompt}` pseudo-macro in style's common prompt prefix to specify how it will be combined with the generated prompt? Example: `SD_prefix, {prompt}, SD_postfix`

**Comment by DysAnia1013** [comment]
Thank you very much for your dedication, the first problem has been solved perfectly.
As for the second suggestion, I've learned a bit about the scenario you mentioned, but in my opinion this one still doesn't solve my problem.
I usually add the artist and high quality tags to the common prompt to define the painting style, leave the character and other tags to the AI to generate, and my character tags are fixed to appear first in the AI generated tag.
If I use the scenario you described, my character tag appears in the first place, but there are many unimportant tags after it, followed by my common prompt, which again will cause problems with the NOVEL coming out.
The result I want is the AI generated character tag in the first place, the common prompt in the second place, and the other tags generated by the AI in the third place, so it doesn't work with your solution.
I was wondering if it could be made into an array-like format that would allow me to freely control the AI-generated tags. e.g. my AI tag array is A, and I could set it to something like: A[0], [common prompt], A[1:].
Of course I realize that I'm probably in the minority with this usage, so if you come up with a better solution or have something else important to do, it's fine to ignore this comment.
Thank you very much for your great work.

**Comment by DysAnia1013** [comment]
Well, I found another awkward problem, now () and {} are sent correctly, but [] is not, so it seems that these brackets are deeply emotionally entangled with each other.

**Comment by Cohee1207** [comment]
Well, it wasn't too hard to leave them in. Also low dashes, seems they seem important too

**Comment by DysAnia1013** [comment]
Thank you very much, hard work
