### ISSUE TITLE
[FEATURE_REQUEST] SSO Support

### ISSUE THREAD

**Issue by LeaderbotX400** [SillyTavern/SillyTavern#2294]
### Have you searched for similar requests?

Yes

### Describe the solution you'd like

Since user accounts are now a thing, I don't think it would be too much of an additional stretch to implement SSO, ideally OAuth/OIDC support.

### Additional context

I already use Authentik and am fine with using the reverse proxy provider, but that means I lose the segregation of concerns when working with multiple users

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

None

**Comment by Cohee1207** [comment]
>  I don't think it would be too much of a stretch to implement SSO

It is, and it's not in the scope of this project. Accounts are not a serious security feature, given they're not enabled by default, don't have a password requirement, or otherwise provide strong protection that makes them suitable for any kind of public deployment. This is more akin to a little lock on a kid's diary that hides it from wandering eyes. 

If you need SSO, look into appropriate projects that provide this, e.g. https://github.com/authelia/authelia

**Comment by exu-g** [comment]
Having an OIDC client integrated into SillyTavern would be a valuable addition and would make using Authelia, Authentik or whatever other SSO provider much easier.  
Currently I have to fight SillyTavern to disable authentication so I can proxy it through Authentik instead.

**Comment by Cohee1207** [comment]
See the response above. Also, authentication is disabled by default, why do you have to fight it?

**Comment by exu-g** [comment]
> See the response above  

Ok, I interpreted this incorrectly. Apologies

> Also, authentication is disabled by default, why do you have to fight it?  

I have my instance publicly accessible and, based on the docs, this requires one of the following three options.
- Whitelisting enabled
- Whitelisting disabled + user and password
- HTTP Basic auth

However, as I'm using Authentik and nginx already to handle authentication none of the three are necessary.  
I managed to solve this by having whitelisting enabled with 0.0.0.0/0 allowed as a workaround.

**Comment by Cohee1207** [comment]
Yes, whitelisting of wildcards is expected in this case.

**Comment by LeaderbotX400** [comment]
https://github.com/auth0/express-openid-connect could be helpful here.

**Comment by mininator1** [comment]
I would also love this feature. This could make everything easier. I have a group of friends and would like to host the instance. Maybe they could create the user themselves then instead of giving out user and passwords.
