### ISSUE TITLE
[BUG] World/Lorebook will be overwritten if user creates a new lorebook with identical name

### ISSUE THREAD

**Issue by Archeb** [SillyTavern/SillyTavern#2297]
### Environment

🪟 Windows

### System

N/A

### Version

1.12.0 'staging' (863e0c36)

### Describe the problem

Lorebook will be overwritten if user creates a new lorebook with identical name.

Steps to reproduce:

1. Copy the name of lorebook to be overwritten, In this case, "Kisna-WI"
![image](https://github.com/SillyTavern/SillyTavern/assets/11910831/9bbf4072-5236-40bb-b66b-330f8fd0933e)

2. Create a new World Info with that name.
![image](https://github.com/SillyTavern/SillyTavern/assets/11910831/b85dad49-b152-4972-8e28-9357f48f3a86)

3. All entries were overwritten with blank.
![image](https://github.com/SillyTavern/SillyTavern/assets/11910831/6afc74b3-18e0-4134-8443-cbcbe22f8c09)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Archeb** [comment]
This should be considered as a bug. Since we already have the DELETE button, this kind of overwriting behaviour should not be allowed.

**Comment by Wolfsblvt** [comment]
Fixed/implemented in staging now.
