### ISSUE TITLE
[FEATURE_REQUEST] Change instruction template without changing system prompt

### ISSUE THREAD

**Issue by allo-** [SillyTavern/SillyTavern#2303]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

When testing different models, it is often necessary to change the instruction template, which then also changes the system prompt. The system prompts themselves seem to be similar without too many differences, although they are probably slightly adapted for different models.

If one has an adapted system prompt, one might want to keep it for the new model with another instruction template. Currently, SillyTavern links the system prompt template to the instruction template, so you have to copy & paste the system prompt each time you change the template to keep using the old system prompt. I wonder if it wouldn't be better to uncouple these templates.

### Describe the solution you'd like

Be able to keep the customized system prompt while switching instruction templates.

There could either be an own set of presets for the system prompt (one might want to have, e.g., one for storytelling, one for assisstants and one for programming), or maybe just a checkbox "keep my systemprompt" that keeps the prompt fixed when changing instruction templates.

### Describe alternatives you've considered

Create own presets for each instruction template and copy&paste the system prompt to them.

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
This was implemented in 1.12.6

**Comment by allo-** [comment]
That's why I closed it. But I see, there was a bit more to this issue, but storing multiple system prompts got less important since user profiles were introduced.

If you still want to implement that as well, feel free to reopen the issue.
