### ISSUE TITLE
[BUG] Passing --dataRoot to Start.bat uses incorrect config.yaml

### ISSUE THREAD

**Issue by OgalFinklestein** [SillyTavern/SillyTavern#2306]
### Environment

🪟 Windows

### System

Win10

### Version

53496d70f1cfca7891d75058e8be39999ea67657

### Desktop Information

- Node 20.13

### Describe the problem

- Started off creating a shortcut to Start.bat.
- Edit the target to be `D:\A\SillyTavern-1.12.0\Start.bat --dataRoot A:\stories\SillyTavern.new`.
- Fire up shortcut.  It acknowledges the `dataRoot`, creating `default-user`, copying files, etc.
- Does ***not*** adhere to `A:\stories\SillyTavern.new\config.yaml`, but rather `D:\A\SillyTavern-1.12.0\config.yaml`

I have a different port defined in `A:\stories\SillyTavern.new\config.yaml` (copied over from 1.11.8), and yet it binds to default 8000 as defined in `D:\A\SillyTavern-1.12.0\config.yaml`.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Functions as intended. `config.yaml` is not a part of the data root. If you want to control the port you start with - use a command line argument (`node server.js --port=1337`)

**Comment by OgalFinklestein** [comment]
Noted.  Passing `--port` through the shortcut works nicely.

Seems I understood https://docs.sillytavern.app/installation/st-1.12.0-migration-guide/ differently:
> You can provide either an absolute or a relative (to the ST repository directory) path to the data root either by config.yaml or by starting the server with the --dataRoot console argument.

Where "or by starting the server with the `--dataRoot` console argument" was understood that `config.yaml` followed that path too.
