### ISSUE TITLE
[BUG] The "Prompt" button vanishes after clicking "Create branch" and often requires a page reload to return

### ISSUE THREAD

**Issue by Robot1me** [SillyTavern/SillyTavern#2308]
### Environment

🪟 Windows

### System

Chrome 124, Firefox 126, Windows 10 22H2

### Version

SillyTavern 1.12.0 'release' (db2c9a99)

### Desktop Information

Node.js version: v18.18.2
koboldcpp: 1.64
SillyTavern version: 1.12.0
Issues occurs for all models

### Describe the problem

When forking a chat by clicking "Create branch", the "Prompt" button (for viewing the full context information) disappears. A page reload is required to get the "Prompt" button back. In some cases (where the triggers are unknown to me), it is even necessary to generate a new response via a swipe, until a page reload brings the "Prompt" button back.

In case if it's not clear what I mean with "Prompt button", I'm providing some screenshots:

![2024-05-23_224230](https://github.com/SillyTavern/SillyTavern/assets/51457886/b65ca3fa-5dcf-493f-a1a1-9fbda4fe8a39)

After clicking "Create Branch"...

![2024-05-23_224326](https://github.com/SillyTavern/SillyTavern/assets/51457886/6dd979f7-e84b-4b52-a360-e218602d812c)

... the "Prompt" button is gone:

![2024-05-23_224332](https://github.com/SillyTavern/SillyTavern/assets/51457886/88038d5b-fa0c-49d0-a61b-7c64ce8a4f49)

I recall this wasn't an issue before some changes were made that cause SillyTavern to show the cog loading animation when switching between chat files.

### Additional info

Backend used:

![2024-05-23_223947](https://github.com/SillyTavern/SillyTavern/assets/51457886/1fad389b-cfe2-475a-a26d-2a9c97aec014)

I also made a recording to demonstrate the issue, as that is the quickest way to understand the issue. I hope it helps you verify this on your end:

https://github.com/SillyTavern/SillyTavern/assets/51457886/d2c642b7-1823-40d1-9c14-bad213e7e64e

Thank you for investigating!

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
That's because prompts are saved based on chat file Id, so prompts get lost if you change it (by branching or renaming the chat)
