### ISSUE TITLE
[FEATURE_REQUEST] Allow Character Avatars to displayed by default

### ISSUE THREAD

**Issue by DecodeTalker1** [SillyTavern/SillyTavern#2309]
### Have you searched for similar requests?

Yes

### Describe the solution you'd like

I enjoy having the avatar being displayed on the side. I would like a User Setting that allows the character avatar to be displayed on the side automatically when loading characters. Having to click the character's icon in the chat every time I switch characters is a pain.

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
This can be done with a simple user script (https://violentmonkey.github.io/ - install with this)

```js
window.addEventListener('load', () => {
SillyTavern.getContext().eventSource.on(SillyTavern.getContext().event_types.CHAT_CHANGED, () => {
   document.querySelector('#chat .mes[is_user="false"][is_system="false"] .avatar')?.click();
});
});
```

**Comment by DecodeTalker1** [comment]
> This can be done with a simple user script (https://violentmonkey.github.io/ - install with this)
> 
> ```js
> window.addEventListener('load', () => {
> SillyTavern.getContext().eventSource.on(SillyTavern.getContext().event_types.CHAT_CHANGED, () => {
>    document.querySelector('#chat .mes[is_user="false"][is_system="false"] .avatar')?.click();
> });
> });
> ```

gave it a try, but it doesn't work on my end for some reason. I make a new script on the SillyTavern tab and add it in on line 10 right?
