### ISSUE TITLE
[BUG] Documentation Error: Missing Requirements for Windows install via Silly Launcher

### ISSUE THREAD

**Issue by cgwers** [SillyTavern/SillyTavern#2310]
### Environment

🪟 Windows

### System

N/A

### Version

N/A - Most current

### Desktop Information

node v18.17.1

### Describe the problem

The Silly Launcher requires MINOCONDA and MICROSOFT STORE.

Neither is mentioned in the install. The install.bat eventually claims to have installed it, but then re-running the install.bat does the same thing as it did on the first run with the exact same output and instruction to re-run it.

If the user does not have or does not have rights to the MS Store the silly launcher chokes and dies. Also, regarding Python, it's wrong to assume that a windows user does not have python installed or is not willing to install it. Perhaps mentioning the version you'd prefer them to use and then dealing with that fork in the install script would resolve this?

The plain old git install works fine, though.

How about letting us decide to install Python for you or not? Not all windows users are down with getting any software via the MS STORE because MS's goal is to lock down the windows ecosystem and crowd out the smaller developers. It may not seem that way now, but once you drink their koolaid you're locked in.. They can change their TOS and whatever other requirements they choose regarding your app's interfaces to windows and the internet, its look and feel, etc. They've screwed over MSDN devs in the past so you're certainly not immune. If you think I'm full of BS, you go hunt up some old Mac shareware people and they'll give you the run down on what happened when Apple had everyone pretty much locked in. 

With all respect for your efforts and those of the helpers, none of you are technical writers. You ought to see if you can attract one or two to fix your docs. 

### Additional info

find: '/i': No such file or directory

[DEBUG] "current_path is: D:\Python\Python311\Scripts\;D:\Python\Python311\;C:\Python\Python310\Scripts\;C:\Python\Python310\;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;C:\Users\test\AppData\Roaming\npm;C:\Users\test\AppData\Local\GitHubDesktop\bin;D:\Program Files\ImageMagick-7.1.1-Q16-HDRI;D:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Scripts;;C:\Users\test\AppData\Local\Microsoft\WindowsApps;C:\Users\test\miniconda3;C:\Users\test\miniconda3\Library\mingw-w64\bin;C:\Users\test\miniconda3\Library\usr\bin;C:\Users\test\miniconda3\Library\bin;C:\Users\test\miniconda3\Scripts;C:\Users\test\AppData\Local\Microsoft\WindowsApps;C:\Users\test\miniconda3;C:\Users\test\miniconda3\Library\mingw-w64\bin;C:\Users\test\miniconda3\Library\usr\bin;C:\Users\test\miniconda3\Library\bin;C:\Users\test\miniconda3\Scripts"

[DEBUG] "winget_path is: C:\Users\test\AppData\Local\Microsoft\WindowsApps"

[DEBUG] "new_path is: D:\Python\Python311\Scripts\;D:\Python\Python311\;C:\Python\Python310\Scripts\;C:\Python\Python310\;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;C:\Users\test\AppData\Roaming\npm;C:\Users\test\AppData\Local\GitHubDesktop\bin;D:\Program Files\ImageMagick-7.1.1-Q16-HDRI;D:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Scripts;;C:\Users\test\AppData\Local\Microsoft\WindowsApps;C:\Users\test\miniconda3;C:\Users\test\miniconda3\Library\mingw-w64\bin;C:\Users\test\miniconda3\Library\usr\bin;C:\Users\test\miniconda3\Library\bin;C:\Users\test\miniconda3\Scripts;C:\Users\test\AppData\Local\Microsoft\WindowsApps;C:\Users\test\miniconda3;C:\Users\test\miniconda3\Library\mingw-w64\bin;C:\Users\test\miniconda3\Library\usr\bin;C:\Users\test\miniconda3\Library\bin;C:\Users\test\miniconda3\Scripts;C:\Users\test\AppData\Local\Microsoft\WindowsApps"
The operation completed successfully.
←[44m[21:39:11.86]←[0m ←[94m[INFO]←[0m ←[92mwinget added to PATH.←[0m
[INFO] Winget is already installed.
[INFO] Git is already installed.
find: '/i': No such file or directory
find: 'C:\\Users\\test\\miniconda3': No such file or directory

[DEBUG] "current_path is: D:\Python\Python311\Scripts\;D:\Python\Python311\;C:\Python\Python310\Scripts\;C:\Python\Python310\;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;C:\Users\test\AppData\Roaming\npm;C:\Users\test\AppData\Local\GitHubDesktop\bin;D:\Program Files\ImageMagick-7.1.1-Q16-HDRI;D:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Scripts;;C:\Users\test\AppData\Local\Microsoft\WindowsApps;C:\Users\test\miniconda3;C:\Users\test\miniconda3\Library\mingw-w64\bin;C:\Users\test\miniconda3\Library\usr\bin;C:\Users\test\miniconda3\Library\bin;C:\Users\test\miniconda3\Scripts;C:\Users\test\AppData\Local\Microsoft\WindowsApps;C:\Users\test\miniconda3;C:\Users\test\miniconda3\Library\mingw-w64\bin;C:\Users\test\miniconda3\Library\usr\bin;C:\Users\test\miniconda3\Library\bin;C:\Users\test\miniconda3\Scripts;C:\Users\test\AppData\Local\Microsoft\WindowsApps"

[DEBUG] "miniconda_path is: C:\Users\test\miniconda3"

[DEBUG] "new_path is: D:\Python\Python311\Scripts\;D:\Python\Python311\;C:\Python\Python310\Scripts\;C:\Python\Python310\;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;C:\Users\test\AppData\Roaming\npm;C:\Users\test\AppData\Local\GitHubDesktop\bin;D:\Program Files\ImageMagick-7.1.1-Q16-HDRI;D:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Scripts;;C:\Users\test\AppData\Local\Microsoft\WindowsApps;C:\Users\test\miniconda3;C:\Users\test\miniconda3\Library\mingw-w64\bin;C:\Users\test\miniconda3\Library\usr\bin;C:\Users\test\miniconda3\Library\bin;C:\Users\test\miniconda3\Scripts;C:\Users\test\AppData\Local\Microsoft\WindowsApps;C:\Users\test\miniconda3;C:\Users\test\miniconda3\Library\mingw-w64\bin;C:\Users\test\miniconda3\Library\usr\bin;C:\Users\test\miniconda3\Library\bin;C:\Users\test\miniconda3\Scripts;C:\Users\test\AppData\Local\Microsoft\WindowsApps;C:\Users\test\miniconda3;C:\Users\test\miniconda3\Library\mingw-w64\bin;C:\Users\test\miniconda3\Library\usr\bin;C:\Users\test\miniconda3\Library\bin;C:\Users\test\miniconda3\Scripts"
The operation completed successfully.

WARNING: The data being saved is truncated to 1024 characters.
←[44m[21:39:12.33]←[0m ←[94m[INFO]←[0m ←[92mminiconda3 added to PATH.←[0m
[21:39:12.47] [WARN] Miniconda3 is not installed on this system.
[21:39:12.47] [INFO] Installing Miniconda3 using Winget...
Failed when searching source: msstore
An unexpected error occurred while executing the command:
0x8a15005e : The server certificate did not match any of the expected values.

The following packages were found among the working sources.
Please specify one of them using the --source option to proceed.
Name       Id                  Source
-------------------------------------
Miniconda3 Anaconda.Miniconda3 winget
←[44m[21:39:12.48]←[0m ←[94m[INFO]←[0m ←[92mMiniconda3 installed successfully. Please restart the Installer.←[0m

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
https://github.com/SillyTavern/SillyTavern-Launcher/issues
