### ISSUE TITLE
[FEATURE_REQUEST] <Is it possible to distinguish between AI for dialog and drawing?>

### ISSUE THREAD

**Issue by DysAnia1013** [SillyTavern/SillyTavern#2311]
### Have you searched for similar requests?

Yes

### Describe the solution you'd like

I have two APIs, one is Claude opus and the other is GPT 4o, and I usually use opus for conversation.
Recently I started using AI to draw and leave it to AI to generate tags, but soon I found a problem. opus is very creative, which means it is very disobedient and often outputs irrelevant tags. gpt4o is very obedient, it outputs tags perfectly, but it is rather rigid to use for dialog.
So I'm asking if it's possible to add a feature to separate the dialog model from the model that generates the drawing tags. opus is expensive, and I don't want to use it to generate drawing tags, but it's a pain in the ass to switch back and forth between the two APIs.
If it's possible, I think it would be a good idea to add a function to select the model for generating the tag in the novelai item in the api column, just to keep it the same as the original dialog model function.
Thank you very much for your hard work.

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
Switch models with [STscript](https://docs.sillytavern.app/usage/st-script/). Adding a model select for each and every extension is a wontfix.

**Comment by DysAnia1013** [comment]
I'm sorry to say that I know nothing about code and am basically one of those users who will just follow the tutorials. So I've looked over this page and still don't understand how to accomplish what I need.
Are you trying to get me to switch back and forth between generating tags via code instructions? That still feels like a pain in the ass. I know I'm probably being a bit unreasonable, but I wanted to ask if it's possible to just add a function to specify the model used to generate the tag?
Sorry if this is a pain in the ass and I'm being unreasonable, but I think this feature would be really useful.
I've used risuai before, and it distinguishes between a primary model and a secondary model, with the primary model being responsible for conversations and the secondary model being responsible for analyzing emotional images, generating drawing tags, auto-suggestions, and other less important functions, is it possible to mimic this model of risuai?

**Comment by Cohee1207** [comment]
>  but I wanted to ask if it's possible to just add a function to specify the model used to generate the tag?

It's not.

**Comment by DysAnia1013** [comment]
Well, thank you very much for your response.

**Comment by Cohee1207** [comment]
Basically since ChatComp presets save the selected model, you can just use the preset command to switch back and forth (given your presets are named GPT4 and Claude respectively).
```stscript
/preset GPT4 |
// Generate an sd image (portrait) |
/sd face |
// Restore previous parameters |
/preset Claude |
/echo DONE!!
```

**Comment by DysAnia1013** [comment]
Thank you so much for your reply, I will try to learn to try it.

**Comment by DysAnia1013** [comment]
I succeeded, thank you very much for your help! It's not difficult. I was unreasonable when I asked you to add features before, and I'm very sorry.
