### ISSUE TITLE
[FEATURE_REQUEST] improved getvar getting arrays or objects in stscripts

### ISSUE THREAD

**Issue by GOLDENLULUZ** [SillyTavern/SillyTavern#2313]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

No

### Describe the solution you'd like

Please add new ways of using getvar, it would be extremely (actually critically) helpful.
example:
/setvar key=fruits index=1 apple |
/setvar key=fruits index=2 orange |
/popup {{getvar::fruits::index=1}}

/setvar key=fruits index=likes apple |
/setvar key=fruits index=dislikes orange |
/popup {{getvar::fruits::index=likes}}

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

None

**Comment by Wolfsblvt** [comment]
Have you checked the docs?
This is already there. https://docs.sillytavern.app/usage/st-script/#arrays-and-objects

Note that macros do not currently support array indices. *yet*. They will, with the coming macro rework.  
So right now, you can only do this directly with STscript.
