### ISSUE TITLE
[FEATURE_REQUEST] Automatically tag new uploaded characters

### ISSUE THREAD

**Issue by Sqrlly** [SillyTavern/SillyTavern#2314]
### Have you searched for similar requests?

Yes

### Describe the solution you'd like

When uploading a new character into ST, have the option to automatically add some tags.
Primarily, if I'm in a Folder (Tags as Folders), I would like it to add the tag for that folder.  That's a fairly logical and expected case.

### Describe alternatives you've considered

Alternately/additionally it could apply all selected tags/folders in the filter list.

### Additional context

I can imagine this either being a User Setting, and/or a pop-up upon loading a character asking to apply the tags or not.

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

None

**Comment by Wolfsblvt** [comment]
> I can imagine this either being a User Setting, and/or a pop-up upon loading a character asking to apply the tags or not.

There is already a user setting like this, with a popup, to import the cards' tags on import:
![image](https://github.com/SillyTavern/SillyTavern/assets/9962104/8483134c-708d-4f1f-ac9f-45d2158967cd)

That dialog is a bit lacking though. I am currently working on a revamped version. I can give you a sneak peek. I was also planning to add another box there where you can manually add tags on the import step.  
Having the current drilled-down tag folders - if you are inside any - also considered, is a very interesting idea. I'm gonna add this too.

![image](https://github.com/SillyTavern/SillyTavern/assets/9962104/60134b62-bf37-4f5c-81b8-8518eb8dc711)

**Comment by Sqrlly** [comment]
That would be great.  Yes I had seen that option when looking, but it's for tags embedded in the added character, not my own.  So I leave that off for more control.

An example use case, I download a bunch of cards from CHub into a disk folder.  Then I look through those and select the more interesting ones and drag-and-drop them into ST.  For this case I'd like them all to have my 'New' tag to separate them from my regular chats.  Which involves going into bulk edit, finding all the new ones (which aren't always all at the bottom even in Recent sorting), then adding the tag.  If I could just drop them all into the New folder that would simplify that work.

So not a critical thing, but would be a convenience.  So looks like yours could do the trick.  Maybe an option to unselect all embedded tags.  And maybe how would yours handle dropping a bunch of cards into ST at once?  Would I have to go through every card one at a time when I just want to apply one tag (or more) to all of them?

**Comment by Wolfsblvt** [comment]
> Maybe an option to unselect all embedded tags.
It separates the embedded ones into the ones you actually have yourself and new ones. You can choose to only import the ones you already have, or none at all.  

> And maybe how would yours handle dropping a bunch of cards into ST at once? Would I have to go through every card one at a time when I just want to apply one tag (or more) to all of them?
The dialog would pop up for every card, yes. Unless you choose the "Remember my choice" option, which change it so the dialog will never show up anymore, and your chosen option (existing, all, none) will be remembered.
With the new thingy of inside folders, that should also be remembered.

I'll see that I make this as convenient as possible. Then you can try it out.

**Comment by Sqrlly** [comment]
Sounds good!  Maybe an "Apply to remaining" option that applies just to that batch, just as an idea.  Whatever works out to be the least trouble to make. :-)  And thanks!

**Comment by Wolfsblvt** [comment]
Whoops, forgot to update this issue.
This was integrated in #2330 and finalized with the "Remember Choice" option in #2405 and is now part of the current release.

The "currently selected folders" option was also implemented.

Can you test the latest import dialog and see if it fulfills what you wanted?
