### ISSUE TITLE
[FEATURE_REQUEST] rand for objects in stscripts

### ISSUE THREAD

**Issue by GOLDENLULUZ** [SillyTavern/SillyTavern#2315]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

I am trying to pick a random number from 1 to 6 in  stscript, but find it hard.
I am now using the following as a method, but it is obviously not elegant.
/rand round=floor from 1 to 6.9999

### Describe the solution you'd like

/rand [1,2,3,4,5,6]
/rand ["apple","orange","banana"]

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

None

**Comment by Wolfsblvt** [comment]
You can just use the `{{random}}` macro, which already supports supplying a lost of options. Easier than tryin to work with a random generated number.

https://docs.sillytavern.app/usage/core-concepts/characterdesign/#replacement-tags-macros
See 33

**Comment by GOLDENLULUZ** [comment]
> You can just use the `{{random}}` macro, which already supports supplying a lost of options. Easier than tryin to work with a random generated number.
> 
> https://docs.sillytavern.app/usage/core-concepts/characterdesign/#replacement-tags-macros See 33

That's cool, I was reading the STscript page and totally forget to read the page you mentioned.

**Comment by Wolfsblvt** [comment]
That's because there is no real own doc for macros yet. A bit sad, but something that will change soon too.
I can see how you missed it.
