### ISSUE TITLE
[BUG] QR auto executes on landing page

### ISSUE THREAD

**Issue by bobcate** [SillyTavern/SillyTavern#2316]
### Environment

🪟 Windows

### System

Thorium v123.0.6312.133

### Version

SillyTavern 1.12.0 'staging' (439ef0dc)

### Describe the problem

A quick reply that is set to execute on opening a chat, executes when going back to the landing page.
In other words, the landing page is considered a valid chat window for QR.

Steps to reproduce:
1- Open a random chat with a character.
1- Go to `Extensions` > `Quick Reply`
2- Add a new QR
3- Open `Additional options`
4- Tick `Execute on opening chat`
5- Add `/echo test` as message
6- Choose `Close chat` from the hamburger menu next to the input area
7- Observe the new QR execute.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by LenAnderson** [comment]
The landing page is really just another chat, only without characters and nothing is saved. Triggering QRs when returning to the landing page is expected and in line with ST's events.
If you don't want to run your QR on the landing page, you can for example check `{{group}}` to see if you're in a chat with any characters and /abort if you're not.

**Comment by bobcate** [comment]
When I first launch ST, and call `/echo {{group}}` it returns `SillyTavern System`, nice.
But, if I enter a char chat, close it an go back to landing, it doesn't return anything, no popup message, console says `no arg provided for /echo`.
I nested ifs to get around that:
```
/if left={{group}} rule=neq right="SillyTavern System"
    else={: /echo NOTchat1 | /abort :}
    {: /if left={{group}} right="" rule=neq else="/echo NOTchat2 \| /abort" "/echo chat" :}
```
Also, the same thing is true for `{{char}}`.
So, `{{group}}` and `{{char}}` becomes empty after entering a chat and going back to the landing page.
