### ISSUE TITLE
[BUG] Vector Storage messes up the AI conversation

### ISSUE THREAD

**Issue by KometFox** [SillyTavern/SillyTavern#2318]
### Environment

🐧 Linux

### System

Librewolf 123, Xubuntu 22.04

### Version

1.12.0

### Desktop Information

NodeJS Version: v20.13.1
Generation API: KoboldCPP 
Branch: Release
Model: L3-8B-Stheno-v3.1.Q4_K_M

### Describe the problem

When I have Vector Storage enabled it currently messes up with the AI response. The AI doesn't take any previous last few message into consideration for writing it's reply to me and instead acts like it's a new chat or writes a completely different response. I tried changing around with the Vector Storage settings and none of the changes fixes this bug or makes the AI behave in a different behavior which relates to the current conversation. When I disable the Vector Storage feature the AI behaves back to normal and the conversation can be resumed as is. 

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Let's align on the expectations first. What do you expect Vector Storage to do?

**Comment by KometFox** [comment]
> Let's align on the expectations first. What do you expect Vector Storage to do?

I excepted that it's used for the AI to recall parts of previous chatting history, so some sort of having a permanent memory feature I think? But right now on my end that's not the case, with Vector Storage enabled the AI just completely says something different which is not related to the last prompt. So when I try to say something about a topic then the AI won't continue this discussion but does things like it reintroduces itself or writes completely different text.

**Comment by Cohee1207** [comment]
Vector storage _for chats_ never guaranteed a permanent memory or even improvement of any sort. It was an experimental feature that has proven not to work as expected. Valid use cases for RAG are files/data bank, and maybe WI activation. There's nothing I can do to fix it since the approach of rearranging past chats for better memory is fundamentally flawed.

**Comment by KometFox** [comment]
Hmmm. Looks like I was wrong then. Shouldn't there been a warning on the SillyTavern WebUI that Vector Storage is a experimental feature?
