### ISSUE TITLE
[FEATURE_REQUEST] Group Chat "Reply Only When Mentioned" Setting

### ISSUE THREAD

**Issue by dontcallmemrsu** [SillyTavern/SillyTavern#2321]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

I've always thought group chats had a lot of potential for interesting scenarios not possible with single character cards, but also require a lot of "help" from the user in order to function properly. Be it adding or removing characters manually, or manually disabling a character's responses when they leave a scene or you don't want them butting in on a certain topic or conversation. I think there's a lot of room for improvements with the system and I believe I came up with a decently useful feature.

### Describe the solution you'd like

Adding a new reply setting to characters group chats called "reply only when mentioned" that restricts a character from replying unless they are directly mentioned by name in the previous message. Perhaps there could be further settings for how many messages back it will scan for their name, as well as how likely they are to respond if it finds it (similar to the "Talkativeness" setting that already exists).

My primary inspiration for this setting (to illustrate an example of the use case for this feature) is a scenario in which the group chat is primarily between two characters, but with a third card to represent an on-board AI for a space ship. With the "reply only when mentioned" feature, the AI character would not respond or but in on any conversation unless either the human or other card directly asks it a question or to do something.

Anther potential use is for a card representing an RPG System for adventure scenarios, whereby the user can 'call' the card by typing "STATS" or "INVENTORY" in their message. These could be separate cards, or the same card that is being called by a preset 'Alias' which could also be set in the group chat menu.

Another setting I would add (if I wasn't an illiterate ape when it came to coding) is whether a card can be called by participant in the group chat, or only by the human.

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
Setting 0 talkativeness on a character definition level is essentially equivalent to "only speak when mentioned".
