### ISSUE TITLE
[BUG] Default_Comfy_Workflow.json missing the loader for the VAE.

### ISSUE THREAD

**Issue by aiimagestudio** [SillyTavern/SillyTavern#2322]
### Environment

🪟 Windows

### System

windows 10, Microsoft Edge

### Version

1.12.0

### Describe the problem

The Default_Comfy_Workflow.json is missing the loader for the VAE.
Here's my modified version.

`{
  **"2": {
    "class_type": "VAELoader",
    "inputs": {
      "vae_name": "%vae%"
    }
  },**
  "3": {
    "class_type": "KSampler",
    "inputs": {
      "cfg": "%scale%",
      "denoise": 1,
      "latent_image": [
        "5",
        0
      ],
      "model": [
        "4",
        0
      ],
      "negative": [
        "7",
        0
      ],
      "positive": [
        "6",
        0
      ],
      "sampler_name": "%sampler%",
      "scheduler": "%scheduler%",
      "seed": "%seed%",
      "steps": "%steps%"
    }
  },
  "4": {
    "class_type": "CheckpointLoaderSimple",
    "inputs": {
      "ckpt_name": "%model%"
    }
  },
  "5": {
    "class_type": "EmptyLatentImage",
    "inputs": {
      "batch_size": 1,
      "height": "%height%",
      "width": "%width%"
    }
  },
  "6": {
    "class_type": "CLIPTextEncode",
    "inputs": {
      "clip": [
        "4",
        1
      ],
      "text": "%prompt%"
    }
  },
  "7": {
    "class_type": "CLIPTextEncode",
    "inputs": {
      "clip": [
        "4",
        1
      ],
      "text": "%negative_prompt%"
    }
  },
  "8": {
    "class_type": "VAEDecode",
    "inputs": {
      "samples": [
        "3",
        0
      ],
      "vae": [
        "2",
        0
      ]
    }
  },
  "9": {
    "class_type": "SaveImage",
    "inputs": {
      "filename_prefix": "SillyTavern",
      "images": [
        "8",
        0
      ]
    }
  }
}`

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Please send a pull request if you think the workflow is wrong
https://github.com/SillyTavern/SillyTavern/pulls
