### ISSUE TITLE
[FEATURE_REQUEST] Multi swipe for tabbyapi

### ISSUE THREAD

**Issue by aikitoria** [SillyTavern/SillyTavern#2323]
### Have you searched for similar requests?

Yes

### Describe the solution you'd like

exl2 and tabbyapi now support batching multiple prompts and paged kv cache. Would be great if we could have the multi swipe generation feature that exists on the aphrodite backend for tabby too!

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
@bdashore3 is still working on this. Will be added as soon as it's ready.

Related tabby issue: https://github.com/theroyallab/tabbyAPI/issues/110

**Comment by kingbri1** [comment]
See #2325

**Comment by Cohee1207** [comment]
Merged

**Comment by aikitoria** [comment]
It's been working for me. The performance of batching on exl2 seems worse than expected, but that's not related to ST.
