### ISSUE TITLE
[FEATURE_REQUEST] Deleting a chat should delete created images from disk

### ISSUE THREAD

**Issue by aikitoria** [SillyTavern/SillyTavern#2331]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

After deleting a chat, images generated during the chat still exist on disk, and must be manually removed.

### Describe the solution you'd like

It would be great if deleting a chat automatically cleaned up any images that were generated from the user folder.

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
> any images that were generated

There's a problem. Only a link to the latest image is preserved. The links to regenerated images or images from removed messages are lost. This would require keeping a list in the chat metadata of all images that were ever uploaded or generated in a chat, which I'm not a huge fan of.

**Comment by aikitoria** [comment]
Wouldn't it make sense if images were put in a folder for the current chat?
