### ISSUE TITLE
[BUG] Sending image to ComfyUI results in "Incorrect padding" error

### ISSUE THREAD

**Issue by 2haloes** [SillyTavern/SillyTavern#2334]
### Environment

🪟 Windows

### System

Windows 11 (latest update) running through Sillytavern launcher

### Version

SillyTavern 1.12.0 'release' (1d32749ed)

### Desktop Information

- Node.js version
  - 18.16.1
- Text generation API
  - oobabooga/text-generation-webui
- Stable diffusion API
  - ComfyUI  (Version: [bf3e33](2024-05-30))
- ComfyUI custom nodes tested
  - Acly/comfyui-tooling-nodes
  - A8R8_ComfyUI_nodes
  - glowcone/comfyui-base64-to-image
- Branch
  - Release

Everything is running from a single machine with the text generation running in WSL and everything else running in the Windows environment

### Describe the problem

When using ComfyUI to generate images that include the %char_avatar% macro in the prompt JSON and attempt to generate an image, what I expect to happen is that the image is sent to ComfyUI in base64 and is then decoded within ComfyUI to be used within the connected node(s).

What is actually happening is that the base64 that is being output is not considered valid within the Python base64 library, resulting in the following exception message:
`binascii.Error: Incorrect padding`

I attempted this with different default bots and the result is the same. 

I have tried manually injecting an extra padding character which does allow the base64 to be decoded however it does not decode as an image and results in a different exception.

I have checked the base64 that has been output sent to ComfyUI with web converter tools and varifiers and they all return that it is valid and free of errors.

I have been able to run this through the Python (3.12.0) interactive shell and am able to replicate this with the standard base64 library that came with my python installation

### Additional info

I've been able to replicate this in the python shell with the following:
```
import base64
content_string = '''[BASE64 STRING HERE]'''
base64.b64decode(content_string )
```

For the details below, the base64 node used for ComfyUI is [Acly/comfyui-tooling-nodes](https://github.com/Acly/comfyui-tooling-nodes), all of the nodes I have tested have had the same result, likely because they all use the same base64 library.

The JSON used in SillyTavern can be found here: 
[Default_Comfy_Workflow_with_lora_and_ip.json](https://github.com/user-attachments/files/15518279/Default_Comfy_Workflow_with_lora_and_ip.json)

The base64 for the Flux the Cat avatar sent by SillyTavern can be found here: 
[base64_image_sillytavern.txt](https://github.com/user-attachments/files/15518301/base64_image_sillytavern.txt)

Full log of processing from ComfyUI:
```
FETCH DATA from: C:\dev\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
#read_workflow_json_files_all C:\dev\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\app\
data_path:  C:\dev\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\data
got prompt
[rgthree] Using rgthree's optimized recursive execution.
!!! Exception during processing!!! Incorrect padding
Traceback (most recent call last):
  File "C:\dev\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-tooling-nodes\nodes.py", line 19, in load_image
    imgdata = base64.b64decode(image)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "base64.py", line 88, in b64decode
binascii.Error: Incorrect padding
```

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by LenAnderson** [comment]
That's because SillyTavern provides a dataURI and your node expects plain base64 data.
Switch to a node that loads an image from a dataURI and it should work.

**Comment by 2haloes** [comment]
That makes sense, I was looking into that when I raised this

I was able to find Ryuukeisyou/comfyui_io_helpers which supports the full dataURI and everything is now working, thank you for the pointer!
