### ISSUE TITLE
[FEATURE_REQUEST] Enhanced Logic Handling in World Triggers to Prevent Overlapping Entries

### ISSUE THREAD

**Issue by XYZOTZ** [SillyTavern/SillyTavern#2338]
### Have you searched for similar requests?

Yes
### Is your feature request related to a problem? If so, please describe.

Yes, the issue is related to the current logic handling of World triggers. Specifically, there are conflicts when triggers with similar primary keywords but different optional filters are activated simultaneously. For example, when two entries are set up as follows:
- **Entry 1:** Primary Keywords: Sheep, Optional Filter: Prairie, Content: Start the scenario where sheep are grazing on the prairie.
- **Entry 2:** Primary Keywords: Sheep, Logic: AND ALL, Optional Filters: Prairie, Wolf, Content: Scenario where a wolf chases sheep on the prairie.

The problem arises when Entry 2 is triggered, inadvertently causing Entry 1 to also trigger due to the overlapping keyword 'Sheep' and 'Prairie,' despite the presence of 'Wolf' in Entry 2's filters. This leads to potential misjudgments by the LLM model, activating inappropriate or unintended scenarios.

### Describe the solution you'd like

I propose an enhancement to the Logic options within Worlds. The solution involves allowing multiple selections within the Logic settings to refine trigger conditions. For instance:
- **Logic Adjustment:** Primary Keywords: Sheep
  - **New Logic Option:** AND ANY combined with NOT ANY
  - **Configuration:** AND ANY Optional Filter: Prairie AND NOT ANY Optional Filter: Wolf

This adjustment ensures that while Entry 2 is triggered due to the inclusion of 'Wolf,' Entry 1 remains untriggered because it explicitly excludes scenarios where 'Wolf' is a factor, despite sharing other keywords and filters.

### Describe alternatives you've considered

An alternative considered was to manually adjust the specificity of keywords and filters for each entry, ensuring minimal overlap. However, this method is less efficient and can lead to increased complexity in setting up World triggers, potentially limiting the flexibility and dynamic nature of scenario creation.

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
If you don't want overlap between certain entries - use inclusion groups with a priority checkbox that will exclude one entry if one is triggered.

**Comment by Wolfsblvt** [comment]
Or, if you actually want to have the one trigger where **most** keywords match, use the Group Scoring option, combined with inclusion groups.

**Comment by XYZOTZ** [comment]
> If you don't want overlap between certain entries - use inclusion groups with a priority checkbox that will exclude one entry if one is triggered.

Thanks, looks like I overlooked some cool features before
