### ISSUE TITLE
[FEATURE_REQUEST]  Add Image generater Fooocus

### ISSUE THREAD

**Issue by JimmyLoar** [SillyTavern/SillyTavern#2340]
### Have you searched for similar requests?

Yes

### Describe the solution you'd like

Add the ability to use local Fooocus AI (https://github.com/lllyasviel/Fooocus) to generate images

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Maybe

**Comment by Cohee1207** [comment]
Nothing I can do here.

Fooocus doesn't have a proper HTTP API. The Gradio client doesn't count, it's awful to use and I wouldn't recommend anyone to ever deal with that. The request is closed as wontfix https://github.com/lllyasviel/Fooocus/issues/442

There's an [unofficial fork](https://github.com/mrhan1993/Fooocus-API) that provides a proper API, but I doubt that anyone would want to install that just to use it with ST. At this point it's easier to bite the AUTO1111 pill, it's not even that bad.

**Comment by Hexag0nSun** [comment]
> There's an [unofficial fork](https://github.com/mrhan1993/Fooocus-API) that provides a proper API, but I doubt that anyone would want to install that just to use it with ST.

Actually, I just did that to see if it could work with ST, so now I have found this thread. Would it be possible to add support for Fooocus-API in ST? It's so much faster than AUTO1111, and it makes little sense for ST-Launcher to include Fooocus in its menu if there is no support. That is how I've heard of Fooocus to begin with, so it's very confusing it's not supported.

Thank you.

**Comment by LevinGamer8** [comment]
I also would like Fooocus image generation really much, because the AUTO1111 is not even half as good as Fooocus from what i have seen. Probably I am just to dumb to set it up correctly but thats also a plus point for foocus. And if you do not want to add Fooocus could you then add an just other API? So you can put an url and all the api entrys to make requests to your own hostet image generator.
