### ISSUE TITLE
[FEATURE_REQUEST] Suggestions for QR

### ISSUE THREAD

**Issue by lannashelton** [SillyTavern/SillyTavern#2345]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

I've noted down some points I noticed while using QR feature of ST.

### Describe the solution you'd like

1. **Slash command for renaming active character**
I had several cases I looked up for this slash command. It'd be handy to have this. This command should rename the active character without switching the active chat.

2. **Add "Every X turn" feature to QR automatic triggers**
For example if I enabled 'Execute on AI message', I should also be able to choose if I want it to execute after every 1 message of AI or every 3 message and so on.

3. **Automation ID on Regex?**
Is it possible to make a Regex entry be able to trigger a QR via Automation ID? When regex script triggers, it would also activate QR

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

None

**Comment by Wolfsblvt** [comment]
1. Interesting suggestion, should be possible.
2. Already easily achievable with the current system. Just make change the QR a bit that it checks the current message id in the script or something, and either uses modulo to decide to execute, or remembers the last time it executed via a saved variable, etc.
3. Also possible, just not with the Regex extension. WI entries support regex keys. So you can simply make a WI entry that has the regex you want as a key, and then set an automation ID there.

**Comment by Wolfsblvt** [comment]
PR for your suggestion 1: #2351
