### ISSUE TITLE
[BUG] Stacking Member Disable in Group Chats

### ISSUE THREAD

**Issue by lannashelton** [SillyTavern/SillyTavern#2347]
### Environment

🐧 Linux

### System

Firefox 126, Linux Mint 21.3 Cinnamon 6.0.4

### Version

1.12.0

### Describe the problem

In group chats when /member-disable command is used multiple times in succession, it stacks and makes /member-enable commands (or manually enabling) that comes afterwards not work.

How to Reproduce the Issue:
1. Open Group Chat
2. Add a few characters
3. Use slash command "/member-disable 1" 3-4 times
4. Manually enable that character's chat bubble
5. Move that character down or close the group chat and re-enter
6. That character reverts back to disabled status and needs to be moved and enabled as many times as the disable command used for it to return back to working status.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Wolfsblvt** [comment]
Confirmed and PR for fix open.

**Comment by Wolfsblvt** [comment]
Fixed.

/close

**Comment by Wolfsblvt** [comment]
_Hellooo... thank you... have a nice day! Byeeee_
