### ISSUE TITLE
[BUG] Speech Recognition, Message Mode, Auto Send, sends an empty response either before or after actual speech text randomly, disrupting model responses.

### ISSUE THREAD

**Issue by xxzbill** [SillyTavern/SillyTavern#2348]
### Environment

🪟 Windows

### System

Google Chrome

### Version

 SillyTavern 1.12.0-preview Running 'HEAD' 

### Desktop Information

> sillytavern@1.12.0-preview postinstall
> node post-install.js
up to date in 762ms
Node version: v20.10.0. Running in production environment.
SillyTavern 1.12.0-preview
Running 'HEAD' (80ff8383) - 2024-04-21 22:36:28 +0300

Using: openrouter, either chatGPT4o, or claude Opus, same issue.

### Describe the problem

Using Speech Recognition, Message Mode, Auto Send, after voice input and transcription, it sends an empty user response either before or after the actual speech text user response. It ends up disrupting AI model responses. AI usually cannot recognize the actual text response because of the presence of the empty response.

To reproduce:
1. turn on speech recognition, set message mode to auto send,
2. hit microphone button, say something, hit microphone button again, wait for user responses to show
3. it would give 2 user responses, 1 is empty.

### Additional info

![image](https://github.com/SillyTavern/SillyTavern/assets/25886652/88b69b06-ed5b-419c-91de-b6be3eacdcee)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Update the extension and try again.

**Comment by xxzbill** [comment]
> Update the extension and try again.

Thank you for reply! I tried both UpdateAndStart.bat, and UpdateForkAndStart under root folder, but the issue persist after update. Do you mean another way to update the extensions?![image](https://github.com/SillyTavern/SillyTavern/assets/25886652/ba181270-e58d-4164-9e39-97e1a8081538)

**Comment by Cohee1207** [comment]
Extensions are updated via the extensions management menu. Bat files won't do it.

**Comment by xxzbill** [comment]
Thanks! 
![image](https://github.com/SillyTavern/SillyTavern/assets/25886652/7db1416e-1c9c-499e-b541-db4c6bdf0f73)
I clicked it and it says "already up to date", and the empty message issue persists.
