### ISSUE TITLE
[FEATURE_REQUEST] model add hyperlink aplication shortcut 

### ISSUE THREAD

**Issue by harrisonvanderbyl** [SillyTavern/SillyTavern#2349]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Problem is the complexity of adding custom models

### Describe the solution you'd like

similar to how zoom allows for custom links that open on the application:
something like: sillytavern://0.0.0.0:8000/modeltype=openai&apikey=rc_xxxx
so that a "try model" button can implemented on a website or local runner.

### Describe alternatives you've considered

Long detailed explaination on how to integrate a model, creating videos or tutorials

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Wolfsblvt** [comment]
Kinda like the idea. Thing is. What kind of parameters are supported? There might be dozens and dozens people want to have. What makes sense here?
