### ISSUE TITLE
[BUG] MovingUI panel positions reset when view port size changes temporarily

### ISSUE THREAD

**Issue by Kenqr** [SillyTavern/SillyTavern#2353]
### Environment

🪟 Windows

### System

Firefox 126

### Version

1.11.8

### Describe the problem

With MovingUI on, all panel positions reset when view port size changes temporarily, with the message `Panel positions reset due to zoom/resize`.
This happens in various situations:
- Pressing Alt or Ctrl+F in Firefox. (happens a lot to me)
- Toggling developer tools in many browsers.
- Toggling bookmarks bar in many browsers.
- Toggling bookmarks sidebar or history sidebar in Firefox.
- Toggling collections or Copilot sidebar in Edge.

I expect everything to stay in their place when the view port size changes temporarily.
Actually I don't see why I would ever want to reset every panel to their default positions. Maybe you can add an option to turn off this feature?

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Wolfsblvt** [comment]
That feature is actually on for a reason. If your window resizes, tons of moved and placed element could be outside of the viewport and not recoverable anymore. This would be very bad UI design.

Generally, Moving UI is intended to be used with the same resolution, so the stuff you moves actually stays consistent and makes sense.

**Comment by Kenqr** [comment]
The panel positions are always recoverable, because there's a `Reset MovingUI` button in User Settings.

The current behavior is no desirable, because if the resize is temporary, or if the change is small, you most likely wouldn't want to reset the positions. Even if the change is significant, that doesn't mean you want to start from scratch.

My suggestion:
- Add an option to disable the auto reset behavior.
- Or just remove this behavior. You can always use the `Reset MovingUI` button.
- Or ask the user before resetting.

**Comment by Wolfsblvt** [comment]
I just noticed, your ST version is severely outdated. We are now on version **1.12.1** on the release branch.

The behavior you describe was changed/fixed three weeks ago and should be part of the latest release.
See https://github.com/SillyTavern/SillyTavern/commit/9b1a254553ee4557b919121ed76a48a09292c839

Please update your ST installation to the latest version first, before reporting any issues. ST changes a lot with every new release (:

**Comment by Kenqr** [comment]
I updated to 1.12.1 and it works now, thanks.

That commit was merged into release 2 days after I post this issue, and I did search in the release notes to make sure it's not fixed in newer versions, so updating wouldn't have helped anyway.

If updating to the newest release is required before posting an issue, you can add it to the `Please tick the boxes` section of the new issue template.
