### ISSUE TITLE
[FEATURE_REQUEST] Option to Turn off QR Editor Slash Command Helper

### ISSUE THREAD

**Issue by lannashelton** [SillyTavern/SillyTavern#2360]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

In QR Editor window when a line is clicked on, a huge command helper window pops up as usage guide. But this window blocks my view and really makes it difficult for me to use QR editor. I've come to the point that I can no longer use QR editor because of this.

### Describe the solution you'd like

Please add an option to turn this feature off.

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

None

**Comment by LenAnderson** [comment]
Press Escape.

**Comment by Cohee1207** [comment]
If you really-really loathe autocomplete, hide it with CSS
```css
.autoComplete-wrap,
.autoComplete-detailsWrap {
  display: none !important;
}
```

**Comment by lannashelton** [comment]
> Press Escape.

Doesn't work. The moment I start typing, it comes back.



> If you really-really loathe autocomplete, hide it with CSS
> 
> ```css
> .autoComplete-wrap,
> .autoComplete-detailsWrap {
>   display: none !important;
> }
> ```

Where do I add it to?

**Comment by Wolfsblvt** [comment]
The "Custom CSS" in your User Settings inside Silly Tavern.
![image](https://github.com/SillyTavern/SillyTavern/assets/9962104/11242b4d-ac1e-427b-bb8a-f2647aceffcd)
