### ISSUE TITLE
[BUG] DRY Samplers not available.

### ISSUE THREAD

**Issue by iiiiiiiiA** [SillyTavern/SillyTavern#2368]
### Environment

🪟 Windows

### System

Firefox 118.0.1. Windows 1909 18363.1500

### Version

1.12.1

### Desktop Information

ST Release Branch
KoboldCPP-1.67

### Describe the problem

When attempting to enable dry samplers via Sampler Select in AI Response Configuration menu, no menu items appear and upon closing and reopening Sample Select window, selected samplers were deselected again.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Not a bug, DRY sampling is not yet available neither in koboldcpp, nor in mainline llama.cpp server.

https://github.com/LostRuins/koboldcpp/blob/concedo/koboldcpp.py#L67
https://github.com/ggerganov/llama.cpp/pull/6839

**Comment by Cohee1207** [comment]
But the problem that DRY sampling is not in the samplers select list exists - @RossAscends you might wanna look into that meanwhile.
