### ISSUE TITLE
[BUG] System Messages Interfere With Expressions

### ISSUE THREAD

**Issue by lannashelton** [SillyTavern/SillyTavern#2369]
### Environment

🐧 Linux

### System

Firefox 126, Linux Mint 21.3 Cinnamon 6.0.4

### Version

1.12.1

### Describe the problem

With Expressions Extension enabled, if you use /sys command to send a system message and then do /emote command to change Sprite at same turn (while System Message is the last message) Expressions Extension shows "System" as current character and stops working.

How to Reproduce the Issue:
1- During a chat, send a system message with "/sys" command
2- Use "/emote" command to manually trigger a Sprite
3- Expressions Extension switches to " Sprite set: System " instead of "Sprite set: {{char}}" when it should ignore System message.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Wolfsblvt** [comment]
Potentially fixed with the recent commits. Can you test this?
