### ISSUE TITLE
[FEATURE_REQUEST] User-facing settings in QR sets, and temporary/private variables in QRs

### ISSUE THREAD

**Issue by doloreshaze337** [SillyTavern/SillyTavern#2370]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Quick replies and STScript as a whole have been a huge boon in extending SillyTavern's functionality without needing to break out full UI extensions, but I feel like they could still be improved. Three additions I've been wanting for a little while is the ability to define user-facing settings for specific QR sets (such as message prompts for scripted generation), temporary variables that are cleaned up when a QR finishes executing, and private variables that can only be accessed by the set their QR belongs to.

### Describe the solution you'd like

For QR set settings, ideally a dedicated menu would be added that lets you create a list of settings of different types such as numbers, booleans and strings. This would be accessible via a button within the "Edit Quick Replies" section of the QR extension menu, and possibly even a button to the side of the QR set's tray above the chat if QR authors anticipate users to frequently change settings. These settings can be accessed by any quick replies within the set via a new slash command or a new macro, similar to variables.

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by LenAnderson** [comment]
- settings: feels like extension territory to me, just use global/chat vars with default values, you can still include context menus or QRs to modify those
- temp vars: scoped variables only exist while their scope exists
- QR set specific variables: not sure if we really need a fourth kind of variables

**Comment by Cohee1207** [comment]
As for the dedicated menu, there's an extension that lets you view variables 

https://github.com/LenAnderson/SillyTavern-Variable-Viewer

**Comment by Wolfsblvt** [comment]
Or as a workaround, just have a separate QR that "sets up" your variables, however you want it, and execute that as the first statement in each QR where you need it.

Nearly all of your requests are already possible, with very slight workarounds.
