### ISSUE TITLE
[BUG] World Info: Commas inside character classes breaks regex

### ISSUE THREAD

**Issue by jcsanady** [SillyTavern/SillyTavern#2375]
### Environment

🪟 Windows

### System

Firefox 126.0.1

### Version

1.12.1

### Desktop Information

KoboldCPP, Staging Version

### Describe the problem

When entering regex for world info, fancy mode will recognize and ignore commas that are part of the string normally, but breaks when they're inside a character class.

This works: /Test,
This doesn't: /Test[,

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Wolfsblvt** [comment]
Confirmed. Know the issue. Don't know a fix yet. But I'll figure it out.

Thanks for reporting this.

**Comment by Wolfsblvt** [comment]
Willing to stresstest the fix? (:

**Comment by jcsanady** [comment]
Sure, happy to take a swing at it

**Comment by Cohee1207** [comment]
Give it a try on staging.
