### ISSUE TITLE
[FEATURE_REQUEST] Fix the way continue works with "Continue prefill" (chat completion)

### ISSUE THREAD

**Issue by cloak1505** [SillyTavern/SillyTavern#2379]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Miraculously I found out enabling "Continue prefill" works just like you're continuing from local text completion (edit: for some models)... except when you're in group chat or have post history instructions.

Group chat causes the Group Nudge prompt to appear after the message to be continued.

Jailbreak Prompt (post history instructions) comes after Chat History, and the message-to-be-continued is treated as part of chat history.

### Describe the solution you'd like

Since the purpose of continue is to continue the most recent response, the most recent response should be sent last so that it can be continued directly from as expected.

### Additional context

[redacted] (image in third comment is enough)

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by cloak1505** [comment]
[redacted]

Regardless of the provider/model's continue capability, I'd like to ascertain hitting continue sends the last message last and that the terminal reflects this.

**Comment by cloak1505** [comment]
The terminal in Staging looks good now. 👍
Just bump the Continue nudge ("Continue prefill" off) down to match the change.
I notice the new order fixes "Continue prefill" response for Llama 3 8B and 70B. Previously, 8B couldn't continue group chat under either method (70B can do nudge).

![continue prompt](https://github.com/SillyTavern/SillyTavern/assets/170299980/7e6848de-f9de-4c32-a99d-73db09fb1f48)

Edit: Last message should also be moved down, above continue nudge. See my second post in issue 1531.

I toyed with the [Prompt Inspector](https://github.com/SillyTavern/Extension-PromptInspector) extension to test above 2-1-3 order.

| | Continue nudge, v1.12.1 | Continue nudge at bottom |
| - | - | - |
| Some older Claude models | might simply sneeze | work |
| PaLM 2 Chat | repeat then continue | work (first word capitalized) |
| Mistral 7B Instruct | sneeze first, capitalize continuation, or new response | mostly work, might capitalize or ALL CAPS |

Most work more cleanly with Continue prefill.

**Comment by Cohee1207** [comment]
Considering this solved.
