### ISSUE TITLE
[Solved, I had a problem with my own settings, sorry]Why does the new version fail to connect to the api when it moves? Other programs api reply quickly, only this one does not work, every api is prone to problems, after switching suddenly can not connect![BUG] <title>

### ISSUE THREAD

**Issue by kiradzS** [SillyTavern/SillyTavern#2380]
### Environment

🪟 Windows

### System

win11，edge、chrome、firefox

### Version

12.1

### Describe the problem

Could not get a reply from API.
Check your connection settings /
API key and try again.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
What API?

**Comment by Cohee1207** [comment]
Provide more details and open a proper report.
