### ISSUE TITLE
[BUG] <title>I can't use my novelAi api  

### ISSUE THREAD

**Issue by hopexros** [SillyTavern/SillyTavern#2386]
### Environment

🪟 Windows

### System

Microsoft Windows 10 Professional 10.0.19045，chrome 125.0.6422.142

### Version

SillyTavern 1.12.1 'release' (f05d90ba)

### Desktop Information

node v22.3.0, novelai scroll subscription,

### Describe the problem

When I try to connect to the novelai source site's api to run sillytavern, the page keeps showing a no connection state.My English is not very good and in using the translation program, I cannot describe my problem well. The error message is as follows. 

### Additional info

![88cbab11-67d1-48c9-a06b-3877110b78e1](https://github.com/SillyTavern/SillyTavern/assets/61700937/5a27efe6-2a9f-4f34-9297-ae99220990d2)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Use a VPN or something like that. Your PC can't connect to the server and it's not a software issue.

**Comment by hopexros** [comment]
> Use a VPN or something like that. Your PC can't connect to the server and it's not a software issue.

I‘m already using one and I can connect to other providers like claude and openAi. I can also use novelAi's service in their website.But I've never been able to connect to novelai through tavern.

**Comment by Cohee1207** [comment]
Still, this is clearly a network connectivity problem. You need to use a system-wide VPN, the HTTP proxy that you set in a browser will not work. Nothing I can do from my end, no one else is reporting this issue and it is not reproducible for me.

**Comment by hopexros** [comment]
> Still, this is clearly a network connectivity problem. You need to use a system-wide VPN, the HTTP proxy that you set in a browser will not work. Nothing I can do from my end, no one else is reporting this issue and it is not reproducible for me.

thank you,I'll try it.
