### ISSUE TITLE
Connect to selfHosted LLM?

### ISSUE THREAD

**Issue by theyonatan** [SillyTavern/SillyTavern#2390]
I am running a server LMStudio and LLama 3.
I would like to use it with Silly Tavern but I can't seem to find a way.

My goal is to have my computer connected to the remove server, simply changing the token streaming api to it instead of openai/google/anthropic.

How can I do that? Thanks

**Comment by Wolfsblvt** [comment]
Set up API endpoint to Text Completion -> OpenAI compatible

![image](https://github.com/SillyTavern/SillyTavern/assets/9962104/01c30aa9-bc2d-4e47-aa01-d8d03bcf366b)

See also the official docs: https://docs.sillytavern.app/usage/local-llm-guide/how-to-use-a-self-hosted-model/
