### ISSUE TITLE
[BUG] Insistent error messages when context size reaches past 32k that prevent further chat progression on Gemini 1.5 Pro

### ISSUE THREAD

**Issue by AiD-69420** [SillyTavern/SillyTavern#2393]
### Environment

📱 Termux

### System

Firefox 126.0.1

### Version

1.12.1

### Desktop Information

V21.6.2
Gemini
Release
1.5 Pro

### Describe the problem

When chat history token count nears and goes over 32k and above, error message: "Too many requests" starts appearing. During earlier stages, waiting for a couple of seconds usually solves the issue, but as the chat progresses, the error message: "MakerSuite Candidate text empty" appears. Doing the aforementioned solution still works, but slowly loses efficacy as chat progresses further until I only get the aforementioned error messages with each attempt at sending a reply or regenerating a response, making me unable to progress the chat any further.

For context—I've set the token count to 1M (Gemini 1.5P), kept temp at 0.9, 1 for top P, and 0 or 1 for top K. Max response length is at 250.

Thank you for your time and consideration!

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
> Too many requests

You're getting rate-limited by Google. 

> MakerSuite Candidate text empty

You're getting filtered by Google.

In both cases, there's nothing really I can help you with.

**Comment by AiD-69420** [comment]
> > Too many requests
> 
> You're getting rate-limited by Google.
> 
> > MakerSuite Candidate text empty
> 
> You're getting filtered by Google.
> 
> In both cases, there's nothing really I can help you with.

Thank for the info! 
Just managed to find another solution (kind of). Enabling streaminng seems to do the job.

**Comment by Wolfsblvt** [comment]
I think this is solved then. If anyone disagrees, feel free to reopen.
