### ISSUE TITLE
[FEATURE_REQUEST] Concept feature: "Split box" (not final name)

### ISSUE THREAD

**Issue by AiD-69420** [SillyTavern/SillyTavern#2394]
### Have you searched for similar requests?

No

### Is your feature request related to a problem? If so, please describe.

Problem: Author's note is limited as it's unable to "record" or generate "notes" that can be used to increase the response coherence and improve LLM memory.

### Describe the solution you'd like

Works essentially like this:
- Users can make whatever prompt they want.
- Acts and works like AN, but is able to send prompts to the AI, and receive and store its responses in the "Split Box Container." And like AN, users can set insertion frequency AND set it either to "overwrite" or "append."
- AI responses carry Split Box responses at the end which are signified by specified markers. ST then cuts SB (split box) responses to store in the SBC (Split Box Container). 

Enabling this will:
- Tell user to increase context size and response length to accomodate for the SB responses.
- SB response will be specified with a marker that ST will use to find and cut it from the rest and store it in the SBC.

Use cases:
You want to keep a very concise, info dense, chronological summary of your chat history. You enable SB and prompt the AI to: "Make very consice and information dense summary of chat history." You set it to "overwrite" and insertion frequency to "Always." Now, everytime you send a message, you also prompt the AI to make a summary of the CH (chat history). the SB response then gets stored in the SBC and is overwritten with each response. And every time you respond, the contents of the SBC is sent to the AI, giving it context to build on.

### Describe alternatives you've considered

Not much, really. Vector storage is nice, but I don't have the hardware for that, and recording or editing every error is a pain in the bum.

### Additional context

Context for this idea?
I thought AN was useful, but was missing a crucial element—which was SB. I've often wondered why no one ever thought of making the AI respond directly to the AN, especially when you think about how useful it can be and with how context sizes for modern LLMs have been on the rise.

And, since you guys are the expert, correct or make this idea better if you consider making it. I'm just suggesting what I thought everyone would probably find very useful... maybe even game changing? 

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
You can already do that with the summary extension - just replace the prompt with whatever you need to generate instead of summary.

**Comment by Wolfsblvt** [comment]
I think we can close this one then?  
If anyone disagrees, reopen.
