### ISSUE TITLE
[BUG][Staging] Alltalk TTS Provider failed to return voice ids 

### ISSUE THREAD

**Issue by Crazya94** [SillyTavern/SillyTavern#2397]
### Environment

🪟 Windows

### System

Windows 11

### Version

SillyTavern 1.12.1 'staging' (0ffad7f4)

### Desktop Information

Node.js version: 20.13.1
Generation API Kobold AI
Branch: Staging 0ffad7f4
Extension issue: TTS

### Describe the problem

Alltalk works perfectly fine with the release branch version but has stopped working on the staging branch. This issue occurs even with a fresh installation of SillyTavern on the staging branch through a git clone.

I can also connect to Alltalk through web-browser with the IP I am using.

Sadly, nothing shows up on the cmd. 

![Screenshot_19-6-2024_18711_127 0 0 1](https://github.com/SillyTavern/SillyTavern/assets/61875944/cf7bfe4f-8293-4e43-91eb-08d6fdcc4bb2)

![Screenshot 2024-06-19 180754](https://github.com/SillyTavern/SillyTavern/assets/61875944/c94fe7e3-db5d-4f48-ab2b-8560a7a5b7f8)

Steps to Reproduce:

Perform a fresh installation of SillyTavern staging branch using git clone.
Navigate to Extensions --> TTS --> Alltalk.
Fill out the endpoint and reload.
Observe that while it says the TTS provider is loaded, an error still appears. (Alltalk TTS Provider failed to return voice ids )
Attempt to change the endpoint to a new value (e.g., localhost:7851) and reload.
Notice that the endpoint reverts back to the previous value (e.g., IP:7851) instead of saving the new value. 

Please let me know if there is any additional information or logs I can provide to help resolve this issue.

### Additional info

This issue does not occur with the release branch, where Alltalk works fine and connects to the same IP.
The problem persists despite a fresh installation of the staging branch.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Not reproduced. 

Tried with a new account on staging to simulate a fresh installation.

1. Connected to a valid AllTalk endpoint first - ready status
2. Connected to an invalid endpoint - status changed to offline.

Nothing reverts back, no errors appear. Staging has changes to AllTalk provider, see yourself https://github.com/SillyTavern/SillyTavern/compare/release...staging

**Comment by Crazya94** [comment]
> Not reproduced.
> 
> Tried with a new account on staging to simulate a fresh installation.
> 
> 1. Connected to a valid AllTalk endpoint first - ready status
> 2. Connected to an invalid endpoint - status changed to offline.
> 
> Nothing reverts back, no errors appear. Staging has changes to AllTalk provider, see yourself [release...staging](https://github.com/SillyTavern/SillyTavern/compare/release...staging)

Oddly enough, I have given up on this. I reinstalled it, and it worked, even though I have three test folders that arent working. Yet, Downloading Release--> switching to staging branch--- relaunching.. works fine? 

I will chalk this up to weird/bad luck. Thank you very much for testing it.
