### ISSUE TITLE
[Feature request]: Add option to switch between group chat or single character in the sidebar

### ISSUE THREAD

**Issue by lorffine** [SillyTavern/SillyTavern#240]
Problem: After creating a lot of group chats, the character sidebar became a mess.
Possible Solution: Add an option to either show group chat or single character in the side bar.

**Comment by lorffine** [comment]
Yes i am aware of the tags feature, but the Character Management sidebar could be more clear and more organized, maybe add an expand button (like in bias preset)

**Comment by lorffine** [comment]
Thanks for the hard work, but i was suggesting making characters more "visible" maybe a **special** character `icon/tag` and an option to only show characters?, but thanks anyway :)

**Comment by lorffine** [comment]
Thank you for listening to my request (d1369004bbdd6de58d636133246b6cc77c395059), I would suggest the new button to switch between showing characters only or groups only

**Comment by RossAscends** [comment]
there is a button to only show groups now.
