### ISSUE TITLE
[BUG] <title> UTF-8 string not exported properly when exporting chat completion preset

### ISSUE THREAD

**Issue by yca321** [SillyTavern/SillyTavern#2400]
### Environment

🐧 Linux

### System

Ubuntu

### Version

1.12.1

### Describe the problem

When exporting files from chat completion preset, UTF-8 string will not exporting correctly.

the attached file is partially json file of my exported json

![IMG_8190](https://github.com/SillyTavern/SillyTavern/assets/44513440/2bc6e46e-82a8-46fd-9f8b-838f481dae8d)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Wolfsblvt** [comment]
Cannot reproduce.

Which export button are you using exactly to export this? And you can give me the example UTF-8 characters that aren't exported correctly for you?

**Comment by yca321** [comment]
Hi, I got this error while exporting chat completion preset. Currently I rolled my version back to 1.11.8, I cannot reproduce this issue as well at the moment. I will attach more info if this occurs again.

**Comment by Cohee1207** [comment]
This seems to be an issue with your file viewer, not with ST. Open in something that respects file encodings.
