### ISSUE TITLE
[FEATURE_REQUEST] Grayed out/hidden folders when they don't refine the search any more.

### ISSUE THREAD

**Issue by whiskeyfur** [SillyTavern/SillyTavern#2404]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

When Tags as Folders is checked, folders that do not change what characters get listed should probably either be grayed out or hidden, depending on settings.

Extra folders that don't do anything to drill down, as in they don't refine the search any more, don't really add anything to the UI. 

### Describe the solution you'd like

I would like to see where folders that don't add anything to the search be grayed out, or if the option is set in the user preferences, just hidden altogether.

Example:
![image](https://github.com/SillyTavern/SillyTavern/assets/3805521/58708988-7dd0-4af4-9744-ab204264ebb3)

### Describe alternatives you've considered

Less tags, but that isn't always feasible.

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Wolfsblvt** [comment]
Let me think about this. There are reasons why those folders should still be displayed, so hiding them outright doesn't make sense. Greying out makes sense. I think I can add this.

I don't think adding a user setting to hide them is warranted though. That's a very niche request, and we already got a lot of settings.  
I'll grey them out via a specific CSS class though, so it should be easy to hide them with a Custom CSS. They will still count against the number displayed per page, but that's something I can't change there.  
Would that be okay for you?

**Comment by whiskeyfur** [comment]
That sounds like it might work, and if not it's an easy first step. for my html example what I did was add a style="opacity:0.25" so I didn't have to mess with colors, and it works well enough on black or white backgrounds.

**Comment by Cohee1207** [comment]
Request merged into staging.

**Comment by whiskeyfur** [comment]
It works! Thank you very much.

![image](https://github.com/SillyTavern/SillyTavern/assets/3805521/5913d130-3135-4a4d-9c1d-6295af09a3d6)
