### ISSUE TITLE
[FEATURE_REQUEST] Context Indicator Usability Improvement

### ISSUE THREAD

**Issue by skatardude10** [SillyTavern/SillyTavern#2407]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Usability enhancement. The dashed context indicator line is linked to the "quote text" color. 

This makes it difficult to identify when scrolling up through hundreds of messages on long context.

### Describe the solution you'd like

Any one of these would be nice:  
- Allow editing to another color in the UI, make it bold, or extend past the chat window a bit to make it easier to identify when scrolling up in long chats.
- Option to allow the view to snap to the context indicator line.
- A button, shortcut, something to quick scroll up to the context line. 
- A link in the prompt itemization screen next to, below, or the chat history text itself be a hyperlink to take you to the first message that is in context.

### Describe alternatives you've considered

Tried changing the color of the line to make it easier to find, and found out that it seems to be linked to the "quote text" color.

### Additional context

This feature would be very useful for me when using the summaries extension, allowing quick assessment of the chat context., Would save time by eliminating the need to manually search for the context line, or at least make it way easier.

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Wolfsblvt** [comment]
You can easily style it however you want with Custom CSS - like most things in ST.
This one should do the job. Use colors or size however you like. You can even highlight the whole message, if you want to. That CSS class is applied to the last message that is inside context.

```css
.lastInContext {
  border-top: 10px dotted red !important;
}
```

![image](https://github.com/SillyTavern/SillyTavern/assets/9962104/cef7580b-e288-46a2-b53d-aadad25d96a2)

**Comment by Cohee1207** [comment]
Hotkey is already a thing. ctrl+shift+up to scroll to the line

**Comment by skatardude10** [comment]
Thank you both! Closing!
