### ISSUE TITLE
Import screen doesn't fit on mobile devices

### ISSUE THREAD

**Issue by UrBoiTom** [SillyTavern/SillyTavern#2414]
### Environment

🪟 Windows

### System

Windows 11, chrome android (any version)

### Version

1.12.1

### Desktop Information

Probably not necessary

### Describe the problem

When importing a card the UI is the wrong size and doesn't fit on the screen on mobile.

### Additional info

Uncropped image: ![Screenshot_2024-06-23-23-46-37-957_com android chrome](https://github.com/SillyTavern/SillyTavern/assets/89468301/810b9d9e-ed64-4e61-a945-793d6da1cb9e)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Wolfsblvt** [comment]
Fixed on staging.
