### ISSUE TITLE
[BUG] QR editor caret is invisible on mobile

### ISSUE THREAD

**Issue by creamsan** [SillyTavern/SillyTavern#2416]
### Environment

📱 Termux

### System

Mull 127.0.0

### Version

SillyTavern 1.12.1 'staging' (0c69b698)

### Describe the problem

Title. Hard to tell what line I am in.

### Additional info

https://github.com/SillyTavern/SillyTavern/assets/141376415/1f5e8673-2e4b-40a2-b0f4-eac65ada64eb

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Wolfsblvt** [comment]
@LenAnderson I am not the only one with no caret visible in QR editor.  
Likely something that got broken with the new popups. But I can't seem to track down thee reason for it.

Happens to me in latest Chrome. I also don't have no syntax highlighting via the pre-block. So that might be related?

![image](https://github.com/SillyTavern/SillyTavern/assets/9962104/73c8ef43-6261-474c-899a-97bc61b73e25)

**Comment by LenAnderson** [comment]
> @LenAnderson I am not the only one with no caret visible in QR editor. Likely something that got broken with the new popups. But I can't seem to track down thee reason for it.
> 
> Happens to me in latest Chrome. I also don't have no syntax highlighting via the pre-block. So that might be related?
> 

Staging still has some `.dialogue_popup` selectors in the QR CSS. Looks like you never compiled the LESS file.
I use the VSC extension `mrcrowl.easy-less` to compile LESS files on save so I never have to think about it.

**Comment by Wolfsblvt** [comment]
I didn't even know we had to do that. Good to know.

**Comment by Cohee1207** [comment]
Should be fixed now
<img width="416" alt="image" src="https://github.com/SillyTavern/SillyTavern/assets/18619528/28e6034f-afd9-4f77-aa74-e24d16ad5a05">
