### ISSUE TITLE
[BUG] Expression Maps doent't work. Missing Local classification check in settings.

### ISSUE THREAD

**Issue by Martyprod** [SillyTavern/SillyTavern#2420]
### Environment

🪟 Windows

### System

Windows 11 x64

### Version

23H2

### Desktop Information

SillyTavern 1.12.1 'release
Edge (las version)

### Describe the problem

Hello, when trying to activate the expression characters, in the extension panel, the feature to have it working in offline mode, loca classiffication is missing and replace by something else. how can i fix that ? Thanks !

![No Local](https://github.com/SillyTavern/SillyTavern/assets/46346021/a5b8994a-1704-4421-83cc-495133921cea)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Choose English in a language selector or pull from a release branch.

**Comment by Martyprod** [comment]
> Choose English in a language selector or pull from a release branch.

hi, i put english / default back in the user settings, but the issue remains. any other option ?
pull from a release brunch ? you mean doing an update ? Git Pull ? 
it seems i'm areadly on the last release, so what must i do ? (sorry i have very few access on internet so can't try or search lot of info to do this or that.)
thanks !

**Comment by Cohee1207** [comment]
Try again after pulling the latest release.

**Comment by Martyprod** [comment]
> Try again after pulling the latest release.

I reinstalled totally the app and it's now working. weird. Thx !
