### ISSUE TITLE
[BUG] Error on saving group chat happens silently

### ISSUE THREAD

**Issue by Kentaree** [SillyTavern/SillyTavern#2429]
### Environment

🐧 Linux

### System

Chrome 126.0.6478.127

### Version

1.12.0

### Describe the problem

If an error happens on /api/chats/group/save, the user isn't notified that there's a problem and can continue the conversation, however messages will be lost.
The way I encountered this is that I'm running sillytavern behind an nginx reverse proxy, and my group chat got large enough that it was giving a 413 error. This was invisible to me until I re-opened the chat and a number of messages hadn't saved.

### Additional info

![image](https://github.com/SillyTavern/SillyTavern/assets/1275745/ebe12326-9981-4865-a355-e7e45dcb473b)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Wolfsblvt** [comment]
Most if not all API errors ST are only logged to the console, and not exposed as toasts or anything else.

Don't know if that design is there for a reason - but if we change this there are a lot of other places that need to be touched too.

**Comment by Cohee1207** [comment]
Adding error notification toasts is at the discretion of the fetch initiator. Some critical server saves could have it (like settings), while others don't. But seems like the chat one should be pretty easy to add.

**Comment by Wolfsblvt** [comment]
Implemented on Staging now.

Looks like this:
![image](https://github.com/SillyTavern/SillyTavern/assets/9962104/bac667cb-c86f-4125-bc5e-487376b6856f)
