### ISSUE TITLE
[BUG]  large number of tokenizers are tallying requests

### ISSUE THREAD

**Issue by bincooo** [SillyTavern/SillyTavern#2432]
### Environment

🐋 Docker

### System

linux

### Version

1.12.1

### Describe the problem

A large number of tokenizers are tallying requests, causing the page to freeze for a long time.
Is the IO taking up time, or is the tokenizers taking up time?

<img width="712" alt="Screenshot 2024-06-28 at 16 07 30" src="https://github.com/SillyTavern/SillyTavern/assets/36452456/f7b00e19-8c40-40c4-99c9-68b0af57a7fa">

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
The problem is that for chat completion the token counting is sync (i.e. blocking the page). It was changed to async for most of the other cases but still exists in the prompt builder for chat completion.

**Comment by bincooo** [comment]
Will consolidating these requests into one request and adding caching speed up the response?

Every time I send a message, it takes a long time, which really affects the experience.

**Comment by Cohee1207** [comment]
Resolution: The token counting in Chat Completion was changed to async.
