### ISSUE TITLE
Would it be possible to support the option to automatically translate to English after the input content is sent out, I know the plugin can set the response or input to translate to English, but I need to translate the English response to my language and my language to English.[FEATURE_REQUEST] <title>

### ISSUE THREAD

**Issue by kiradzS** [SillyTavern/SillyTavern#2454]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

no

### Describe the solution you'd like

Would it be possible to support the option to automatically translate to English after typing, I know the plugin can set the answer or input to translate to English, but I need to translate the English answer to my language and my language to English.

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
Auto mode "Both" under the Chat Translation extension does exactly that. You'll see your language in chat, but internally it would all stay English.

**Comment by kiradzS** [comment]
> 聊天翻译扩展下的自动模式“两者”正是这样做的。您会在聊天中看到您的语言，但在内部，一切都会保持英语。

谢谢！原来如此，我以为翻译两者的意思是都翻译成自己的语言

**Comment by Cohee1207** [comment]
I can't read that.

**Comment by kiradzS** [comment]
> 谢谢！原来如此，我以为翻译两者的意思是都翻译成自己的语言

Thank you!

**Comment by Wolfsblvt** [comment]
Nice! Request solved with existing features then. This can be closed.
