### ISSUE TITLE
[BUG] iPad下点击聊天记录的删除按钮，不会显示删除选项

### ISSUE THREAD

**Issue by Godoword** [SillyTavern/SillyTavern#2456]
### Environment

🍎 Mac

### System

iPadOS 15.8.2/Safari

### Version

1.12.2

### Describe the problem

我的酒馆架设在VPS上。

在升级到最新的1.12.2之后，在iPad上用Safari打开，点击任意一条聊天记录的删除按钮，不会正常显示弹出选项，然后整个界面完全卡死，只能强制刷新。

iPhone则无此问题。

iPad上的Safari，默认是请求桌面网站。所以我现在的临时解决办法是关闭“请求桌面网站”，问题可以得到解决。

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
English, please
