### ISSUE TITLE
[BUG] Clicking on the delete button on chat logs under iPad doesn't show the delete option

### ISSUE THREAD

**Issue by Godoword** [SillyTavern/SillyTavern#2457]
### Environment

🐋 Docker

### System

iPadOS 15.8.2/Safari

### Version

1.12.2

### Describe the problem

I have Sillytavern set up on my VPS.

After upgrading to the latest 1.12.2, opening it in Safari on an iPad and clicking on the delete button for any of the chats will not display the popup option properly, then the whole interface is completely stuck and I have to force a refresh.

The iPhone does not have this problem.

Safari on the iPad, by default, requests desktop websites. So my temporary solution is to disable the "request desktop site", and the problem will be solved.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Pull staging and try again.

**Comment by Cohee1207** [comment]
Additionally addressed  here: https://github.com/SillyTavern/SillyTavern/commit/a3031d798686db92f7668b1bb5920db0fb52cc23

**Comment by Cohee1207** [comment]
Fix pushed to the release branch.
