### ISSUE TITLE
[FEATURE_REQUEST] Response config: "Ban tokens containing English words" Option

### ISSUE THREAD

**Issue by hopto-dot** [SillyTavern/SillyTavern#2458]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Many multilingual LLMs unintentionally mix languages when you ask it something in a language other than English.

For example, `昨日、店に行って牛乳をbought。` (Yesterday, I went to the shop and bought milk)

### Describe the solution you'd like

Either:
1. On every selection of the next token, disregard any token that contains more than one lower case English letter with the exception of tokens with contain one of: `<`, `>`, `[`, `]`, `(`, `)`, `{`, `}`, `/`, `\` etc. etc.

For example ban `test` and `hello`, but don't ban `DIY` or `<eos>`.

2. Somehow detect the architecture of model used and loop through all tokens in the models vocabulary and ban tokens that meet the requirements above

Not practical but see below.

### Describe alternatives you've considered

The already existing `Banned Tokens` option doesn't work very well for this specific use case. For example, if I generate a list of tokens using method 2 above (with an external script), the resulting list would differ per model and would therefore have to be recalculated and swapped out each time I change model.

### Additional context

llama-cpp and LLM studio's API servers both allow you to provide a list of tokens to ban (or encourage) using an argument called `logit_bias`.

To test if banning tokens containing English words using method 2 above helped I wrote a python script that did just that and lo and behold the LLM generated text in only the language I wanted.

Of course, this option wouldn't work for coding because code contains English/roman characters, however it's perfect for other instruction-following, writing and roleplay.

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
This is not in the scope of the frontend. We don't sample tokens and don't care about model architectures. Bring this to your backend to consider.

Also, my personal opinion is that banning tokens is not a good thing as it affects the model not in a good way.
