### ISSUE TITLE
[BUG] ComfyUI workflow placeholders do not all get replaced

### ISSUE THREAD

**Issue by Weker01** [SillyTavern/SillyTavern#2460]
### Environment

🐧 Linux

### System

Archlinux

### Version

SillyTavern 1.12.1 'release' (00b44071)

### Describe the problem

I have workflows in Comfyui where I need the same value multiple time. In particular I need the %width% and %height% multiple times for different parts of the workflow. Right now only the first instance of a placeholder is replaced but I would've expected all occurences to be replaced.

I've looked into the source and it seems this function handles the replacement:

https://github.com/SillyTavern/SillyTavern/blob/303520be083388d5a2fbdebf5d1017dee33ef1d0/public/scripts/extensions/stable-diffusion/index.js#L2897-L2951

And there we see String replace() is used where the first parameter is a string. I think that is where the bug occurs. I think a quick fix would be to instead turn the first parameter into a regex with the g flag like so:

`workflow.replace(/"%negative_prompt%"/g, JSON.stringify(negativePrompt));`

but I am no js dev and don't know if that is the best way to resolve this.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
The fix is already in the release branch.
