### ISSUE TITLE
[BUG] <title>Character Expressions, in the Chinese interface, the Classifier API list is empty

### ISSUE THREAD

**Issue by blueswolf** [SillyTavern/SillyTavern#2464]
### Environment

🪟 Windows

### System

10

### Version

1.12.1

### Describe the problem

Character Expressions, in the Chinese interface, the Classifier API list is empty
![BUG](https://github.com/SillyTavern/SillyTavern/assets/160055096/6ae2e73a-d744-4360-8493-67323ab8f083)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
This was already fixed. Update to 1.12.2 or 1.12.3
