### ISSUE TITLE
[BUG] Lorebook Min. Activations setting not functional

### ISSUE THREAD

**Issue by Reithan** [SillyTavern/SillyTavern#2467]
### Environment

🪟 Windows

### System

Chrome 126

### Version

1.12.2

### Describe the problem

Using Min Activations, Max Depth, and Context % for world info without Scan Depth set (set to 0), results in no WI activations.
This setup worked fine in 1.12.1

Doesn't work, but did in 1.12.1
![image](https://github.com/SillyTavern/SillyTavern/assets/7475701/a9fe8da6-ed83-406d-9707-cc6608a2300f)

This activates WI, but is limited by scan depth, rather than Min Activations
![image](https://github.com/SillyTavern/SillyTavern/assets/7475701/99510424-9876-4040-9a1b-876f8ccdaf0c)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Not reproduced. I ran it step by step through the debugger and the depth skew worked correctly, advancing the scan depth from 0.

**Comment by Reithan** [comment]
1.12.2 or 1.12.3? I'll test to see if it's fixed in 1.12.3

**Comment by Reithan** [comment]
Wrong root cause. This issue is being addressed in #2468
