### ISSUE TITLE
[BUG] Importing a card with scoped regex and lorebook will only prompt to import regex

### ISSUE THREAD

**Issue by ghost** [SillyTavern/SillyTavern#2482]
### Environment

🪟 Windows

### System

Win11 23H2, Firefox 127

### Version

1.12.3 'staging' (6e86ab07)

### Describe the problem

See title. When importing a card that has both embedded regex and an embedded lorebook, ST will only prompt the user to import the regex when swapping to the card. You can still import the lorebook manually, but this is unintuitive unless the card creator realizes this behavior and instructs the user.

Card which demonstrates this issue: https://files.catbox.moe/efcaen.png

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Bugfix released in 1.12.4.
