### ISSUE TITLE
How to use the koboldcpp's multimodal captioning with SillyTavern?

### ISSUE THREAD

**Issue by goodmaney** [SillyTavern/SillyTavern#2483]
I can upload the image on koboldcpp's own webui,the multimodal llm worked. But cant upload on SillyTavern. I've try all source in the image captioning

![Snipaste_2024-07-07_00-33-34](https://github.com/SillyTavern/SillyTavern/assets/25651447/4fc0d467-174d-454e-91a6-0f7ab1be5e92)
![Snipaste_2024-07-07_00-34-06](https://github.com/SillyTavern/SillyTavern/assets/25651447/69198063-ad34-401f-8a77-91353507fba1)

when i chose mutimodal it reports
![Snipaste_2024-07-07_00-35-58](https://github.com/SillyTavern/SillyTavern/assets/25651447/d84bd6c9-4371-472b-bab7-ac2d6abac63c)
when i chose local it reports
![Snipaste_2024-07-07_00-36-32](https://github.com/SillyTavern/SillyTavern/assets/25651447/40433da9-1452-4b93-8c38-17e15fe27546)
![image](https://github.com/SillyTavern/SillyTavern/assets/25651447/91bcaa11-3a05-4d68-9899-196f07dd4baa)

SillyTavern v1.12.3
koboldcpp_cu12 v1.69.1

**Comment by Cohee1207** [comment]
Switch from Kobold Classic to Text Completion.

**Comment by goodmaney** [comment]
> Switch from Kobold Classic to Text Completion.

Thanks so much
