### ISSUE TITLE
[FEATURE_REQUEST] Custom model name for Google MakerSuite API

### ISSUE THREAD

**Issue by NijikaMyWaifu** [SillyTavern/SillyTavern#2487]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

gemini-1.5-pro-latest performs worse than gemini-1.5-pro-001, which has more guardrails and generates less words.

### Describe the solution you'd like

Add a custom model name textbox for Google MakerSuite API.

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Ph0rk0z** [comment]
On staging, the subversions of models are available. Thanks for the tip to use the 001 version.

**Comment by Wolfsblvt** [comment]
Yup, that's long existing. We can close this.
