### ISSUE TITLE
[BUG] UI shifting in mobile browser

### ISSUE THREAD

**Issue by Targren** [SillyTavern/SillyTavern#2488]
### Environment

🪟 Windows

### System

Android 12/Vivaldi 

### Version

1.12.3 

### Desktop Information

Windows 10 Pro 
Node v18.16.0
KoboldCPP
Release Branch
Any Model

### Describe the problem

On Mobile - when editing entries that extend beyond the view screen size (with keyboard open), using the "Word delete" function (hold backspace) causes the UI to "jump" up, usually moving the position of the cursor out of the view area.  This issue didn't occur in 1.12.2

Maybe related to #2466? 

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Which entries? Chat messages? 

Look into this: https://github.com/SillyTavern/SillyTavern/pull/2450

**Comment by Cohee1207** [comment]
Edits are debounced to prevent immediate autofit, so holding backspace causes a delayed height adjustment.

**Comment by Targren** [comment]
> Which entries? Chat messages?
> 
> Look into this: #2450

Yeah, chat messages. Sorry for the ambiguity.

**Comment by Cohee1207** [comment]
Try again on staging.

**Comment by Targren** [comment]
> Try again on staging.

Still getting the same issue with Chrome, Vivaldi, and Kiwi browsers.

**Comment by Cohee1207** [comment]
Possibly fixed in 1.12.4, and I haven't seen any other related reports.

Please reopen if persists.
