### ISSUE TITLE
[FEATURE_REQUEST] Queue TTS narration

### ISSUE THREAD

**Issue by Kaiten10** [SillyTavern/SillyTavern#2491]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

When the "Narrate" button is pressed on a message, it interrupts any currently playing TTS audio to generate the new TTS audio.

### Describe the solution you'd like

When the "Narrate" button is pressed and there is a TTS audio currently playing, it should not interrupt the current audio, instead it should queue this TTS audio to play after the current audio. 

When the "Narrate" button is pressed on multiple messages, it should queue in the order the buttons were pressed and play consecutively.

### Describe alternatives you've considered

It could be a toggleable option in the TTS menu.

### Additional context

I am using AllTalk extension in oobabooga webui.

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Wolfsblvt** [comment]
I can see people already requesting the exact opposite if this would be changed. This sounds a lot like personal taste.
*Could* be maybe a TTS setting that you can choose.

**Comment by Kaiten10** [comment]
> I can see people already requesting the exact opposite if this would be changed. This sounds a lot like personal taste. _Could_ be maybe a TTS setting that you can choose.

Yes, it could work as a setting. The idea is so that you can replay long conversations like an audiobook, where you press "Narrate" on each message and leave the TTS audio to queue in the background and play the narrations in sequence.

You can choose which messages to play in the "audiobook" session by selectively clicking on the desired message's Narrate button. I'm happy with a different implementation if it can achieve that.

**Comment by Cohee1207** [comment]
That's why it is important to first state your motivation rather than focusing on a specific solution. The option to play everything already exists, but it is not present in the UI, just available in the DevTools console - `playFullConversation()`

**Comment by Kaiten10** [comment]
Thanks, that's what I was looking for. I should have started with that. Appreciate the reply!
