### ISSUE TITLE
[BUG] World Info Page Not Working

### ISSUE THREAD

**Issue by jdwjen** [SillyTavern/SillyTavern#2493]
### Environment

🪟 Windows

### System

Google Chrome126.0.6478.127, Microsoft Edge 126.0.2592.87

### Version

1.12.3

### Desktop Information

Node Js - 20.9.0
API - Novelai
Model - Kayra

### Describe the problem

World Info Page Does Not Show any of my created worlds. When I select a world from the drop down menu nothing shows up. Just says NO ENTRIES FOUND. The worlds are in the sillytavern folder. But it will show the number of entires. I have tried this on both google chrome and microsoft edge with same results. Sometimes I can get some of the entries of a list to show up if I select 10 per page. But it will only show the first 10. If I try to go to the second page it says no entries found. I have tried importing them back in but then a blue box pops up says that World Info is not set. 
And if I try to select another world info list the box that shows the number of entries just stacks over the previous world info list selected. 

![IMG_1948](https://github.com/SillyTavern/SillyTavern/assets/147673727/1e524b7b-1151-4d23-b50b-2bdf02e422b0)

![IMG_1947](https://github.com/SillyTavern/SillyTavern/assets/147673727/0817cefa-7b28-4539-9f40-c8c867d4a2dd)

![IMG_1946](https://github.com/SillyTavern/SillyTavern/assets/147673727/8e0624f2-0765-42e5-ba85-2445024e0e02)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Remove your install from OneDrive. This is not recommended and is going to cause you problems.
