### ISSUE TITLE
[BUG] Restoring preset to default does not change value of min-P slider

### ISSUE THREAD

**Issue by LostRuins** [SillyTavern/SillyTavern#2501]
### Environment

🪟 Windows

### System

Windows

### Version

1.12.3

### Describe the problem

Just a random small bug I came across. Clicking the button for restoring preset to default does not change value of min-P slider, other sliders change but this remains at whatever correct/incorrect value it was previously.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Wolfsblvt** [comment]
I am quite sure this is not a bug.

Chat Completion or Text Completion?
Can you tell me which preset you are using? Against which API/model?

The preset you have selected **must** have that value set so it can be "reset" to it. If it's not in that preset, but pulling the default from the UI pre-definition, it's not gonna reset to it.
If you are using a default preset from ST, you might want to click "Save" and save it under a different name. Then it'll save all the settings with it, even the default ones who are not in the original preset.

**Comment by Cohee1207** [comment]
This likely comes from default presets not having a min p value set. To fix this, need to load and resave them one by one to set the value.

**Comment by Cohee1207** [comment]
Explanation for those wondering: presets do not have default values for missing fields. If a loaded preset is missing a value, it is carried over from the previous preset. This is true for most of the instances that roughly qualify as "presets" in ST (text completion, chat completion, themes, etc.).

**Comment by LostRuins** [comment]
Ah alright. I was just testing with a completely new sillytavern install (no prior settings or history). 

I tried maxing out all sampler settings, then triggered a rest to the "default" preset and noticed the Min-P did not change, hence this issue. Feel free to close if its working as intended.

**Comment by Cohee1207** [comment]
How to fix (presumably):

1. Neutralize samplers, then load a default preset.
2. Save the preset with a version that adds missing fields.
3. Replace a default preset with an updated version.
4. Repeat for all built-in presets.

Sounds boring but doable.

**Comment by Wolfsblvt** [comment]
Would make sense to just update our presets, yeah.
Then the "reset preset" function stays as intended and just loads the file.
