### ISSUE TITLE
[BUG] fuzzy did not work

### ISSUE THREAD

**Issue by GOLDENLULUZ** [SillyTavern/SillyTavern#2511]
### Environment

🪟 Windows

### System

docker

### Version

1.12.3

### Describe the problem

Last Message (You can ignore the most Chinese characters and focus on the first line):
```json
可可对LULUZ更喜欢了一点……
```
可可的棕色猫耳猛地竖起，眼睛瞬间亮了起来。她兴奋地在LULUZ身边蹦跳，棕色的短发随着动作轻轻晃动，毛茸茸的尾巴欢快地摇摆着。"和牛牛排喵？真的吗喵？可可最喜欢吃肉了喵！"她用柔软的手掌轻轻拍打着LULUZ的手臂，撒娇般地说道。

STscript:
/messages {{lastMessageId}} |
/fuzzy list=["陌生了一点","喜欢了一点"] {{pipe}} |
/setvar key=result {{pipe}} |

Expectation:
result="喜欢了一点"

What Happened:
result="陌生了一点"

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Wolfsblvt** [comment]
Please use English only for issues.
