### ISSUE TITLE
[BUG] fuzzy not working

### ISSUE THREAD

**Issue by GOLDENLULUZ** [SillyTavern/SillyTavern#2513]
### Environment

🐧 Linux

### System

docker

### Version

1.12.3

### Describe the problem

**The bug is strongly related to the text, so I post it in the original language I tested. You do not need to know any Chinese to understand the issue I am reporting. Please read through the report, then decide whether to close it.**

Last message (the really important content is at the first line):
可可对LULUZ更喜欢了一点……
可可的棕色猫耳猛地竖起，眼睛瞬间亮了起来。她兴奋地在LULUZ身边蹦跳，棕色的短发随着动作轻轻晃动，毛茸茸的尾巴欢快地摇摆着。"和牛牛排喵？真的吗喵？可可最喜欢吃肉了喵！"她用柔软的手掌轻轻拍打着LULUZ的手臂，撒娇般地说道。

STscript:
/messages {{lastMessageId}} |
/fuzzy list=["陌生了一点","喜欢了一点"] {{pipe}} |
/setvar key=result {{pipe}} |

Expectation:
The fuzzy worked and find the text "喜欢了一点" in the first line.
result="喜欢了一点"

What Happened:
The fuzzy didn't work as I expected.
result="陌生了一点"

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Wolfsblvt** [comment]
Okay, now I understand.
I am still hesitant to consider this a bug. It's not worded 100% like this, but what this command does is checking each value provided in the list, whether it passes the threshold for the fuzzy match. If one matches, it is returned.
This means they will be processed in order of appearance in that list.

I can see a reasoning for why it might be useful to check the threshold score values of the matches too. But that should likely be an optional parameter to enable this, as it kinda breaks the existing implementation. And depending on the values you send it, might lead to weird results. Fuzzy matching scores are something of their own.

**Comment by GOLDENLULUZ** [comment]
> Okay, now I understand. I am still hesitant to consider this a bug. It's not worded 100% like this, but what this command does is checking each value provided in the list, whether it passes the threshold for the fuzzy match. If one matches, it is returned. This means they will be processed in order of appearance in that list.
> 
> I can see a reasoning for why it might be useful to check the threshold score values of the matches too. But that should likely be an optional parameter to enable this, as it kinda breaks the existing implementation. And depending on the values you send it, might lead to weird results. Fuzzy matching scores are something of their own.

Hello, thank you for replying.
I have tried making the threshold at 1, and change the order of the two option, but the fuzzy function always returns the first one. I think it suggests that fuzzy didn't find any of the option, although actually there should be one to be found. I hope this additional information may help.

**Comment by Cohee1207** [comment]
Let's add a `mode` argument to /fuzzy:

1. `first` - will return a first match (like now)
2. `best` - will return the match with the lowest score (like it used to be before #1883)

**Comment by Cohee1207** [comment]
This should now work for you. Note the added argument and a threshold.

```
/fuzzy list=["陌生了一点","喜欢了一点"] mode=best threshold=0.85 可可对LULUZ更喜欢了一点……
可可的棕色猫耳猛地竖起，眼睛瞬间亮了起来。她兴奋地在LULUZ身边蹦跳，棕色的短发随着动作轻轻晃动，毛茸茸的尾巴欢快地摇摆着。"和牛牛排喵？真的吗喵？可可最喜欢吃肉了喵！"她用柔软的手掌轻轻拍打着LULUZ的手臂，撒娇般地说道。 | /echo
```

**Comment by Wolfsblvt** [comment]
Can you test this and checks if this works for you?

**Comment by GOLDENLULUZ** [comment]
> Can you test this and checks if this works for you?

Hello, I have tried the new version of fuzzy. It worked fine just like what I expected. Thank you all for working.

**Comment by Wolfsblvt** [comment]
Happy to hear that ☺️
This will be part of the next release then, so we can consider this done. Thanks for replying!
