### ISSUE TITLE
[Help needed] ST hanging at the gearbox splash when try to load

### ISSUE THREAD

**Issue by valden80** [SillyTavern/SillyTavern#2523]
### Environment

🐧 Linux

### System

Various browsers, Manjaro current.

### Version

Various

### Describe the problem

Sorry to break up report template, but this is not the ST bug - I just need help.

I has power loss at very unfortunate time when I just loading ST and now I has this problem. 
When I try to load ST I see selection of the users (multi users is on), but after I selecting one, ST hangs with gear spinning animation. 
On any user. It's in the Vivaldi browser.
It can be normally loaded in the Firefox, so I guessing it's not exactly ST problem.
But I still can't have it loaded up in Vivaldi. What can be done? I already cleared cookies - no difference.  

Can anyone give me some idea - where else to look, and what to try?

Upd: I can see ST interface though the gear splash (partial transparency) - it's seem's to loaded, but gear still not go.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Open DevTools console and look for errors.

**Comment by valden80** [comment]
Upd2 - I have this messages in browser dev console:
```The Cross-Origin-Opener-Policy header has been ignored, because the URL's origin was untrustworthy. It was defined either in the final response or a redirect. Please deliver the response using the HTTPS protocol. You can also use the 'localhost' origin instead. See https://www.w3.org/TR/powerful-features/#potentially-trustworthy-origin and https://html.spec.whatwg.org/#the-cross-origin-opener-policy-header.```

```The page requested an origin-keyed agent cluster using the Origin-Agent-Cluster header, but could not be origin-keyed since the origin 'http://orra:8000' had previously been placed in a site-keyed agent cluster. Update your headers to uniformly request origin-keying for all pages on the origin.```

(orra:8000 is legal LAN name for machine with ST host - worked before, also it's closed from internet, no security issues here.)

**Comment by valden80** [comment]
Also I can't connect to it as localhost or 127.0.0.1 even if it's the same machine. The same gear.

**Comment by valden80** [comment]
Another from console:
```
i18n.js:103 Unsupported language: en
findLang @ i18n.js:103

```

**Comment by Cohee1207** [comment]
Not an issue.

**Comment by valden80** [comment]
Somehow I managed to enter it (not exactly understand how exactly - I also deleted configs in one ST account and try to enter with it), and after issue don't come up again after.
