### ISSUE TITLE
Using the replace/update feature with a JSON file should not delete the character's profile picture

### ISSUE THREAD

**Issue by UrBoiTom** [SillyTavern/SillyTavern#2525]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

When importing a JSON file with the replace/update feature, at the moment it deletes the image. This should not happen if a new image is not provided, such as with a JSON file.

### Describe the solution you'd like

When a JSON is imported the image should be kept.

### Additional context

I'm mainly suggesting it because I use a text editor that doesn't support PNG meta editing to change the formatting on cards, and it would save me a lot of time. The change would be much appreciated.

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Wolfsblvt** [comment]
That is expected, and actually intended. The **Replace / Update** takes your new data, and saves that on the server side, using your current character id.
It functions the same as if you'd import a PNG, or a JSON, as a new character. It will override everything.

Making the image an exception would be a bit weird, when all other fields/data are overwritten.
