### ISSUE TITLE
[BUG] /qr-delete don't delete all records in set if called without "label" as help says it should.

### ISSUE THREAD

**Issue by valden80** [SillyTavern/SillyTavern#2527]
### Environment

🐧 Linux

### System

Firefox 115.2.0esr, Manjaro current.

### Version

SillyTavern1.12.3 staging

### Desktop Information

 - OS/Device: Manjaro Linux
 - Environment: local
 - Node.js: version 20.2.0
 - Browser: Firefox
 - Generation API: Oobaboga
 - Branch: staging
 - Model: any local

### Describe the problem

Trying to make stscript that will clean all records/buttons from specific set. My script:
`` /qr-delete set=AutoReply | ... ``
This part shall remove all buttons/records in AutoReply set. But nothing happens when script called.

When I do 
`` /qr-delete set=AutoReply label="Option 1" `` button with label "Option 1" become removed, no problems.

### Additional info

Currently help system says that "label" is optional, and if it's not set - all records shall be removed. It's the behavior I need for my script. If there is error in help system, then I asking how to do what I need?

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by LenAnderson** [comment]
/qr-delete never did that. The help text is wrong and will be fixed.

Loop through /qr-list to delete all QRs in a set.

**Comment by valden80** [comment]
@LenAnderson Maybe you can add something like qr-clean-set to remove all records at once?
In my case I don't know - nor the count of records, nor the labels itself. (These will be variants of replies for user, added by AI through another script.) To really clean all set with these conditions it's seems to needed pretty complex loop script...

**Comment by LenAnderson** [comment]
> @LenAnderson Maybe you can add something like qr-clean-set to remove all records at once? In my case I don't know - nor the count of records, nor the labels itself. (These will be variants of replies for user, added by AI through another script.) To really clean all set with these conditions it's seems to needed pretty complex loop script...


See my previous reply. /qr-list gives you the labels.

**Comment by Wolfsblvt** [comment]
You can also easily just delete the set and re-create it with the same name.

**Comment by valden80** [comment]
@Wolfsblvt Than you for the idea. It's will be easier then creating loop - stscript syntax not so easy when it come time for complex structures...

UPD: Yes, it's works exactly how I need it:
```
/qr-set-delete AutoReply |
/qr-set-create AutoReply |
/qr-chat-set-on AutoReply |
```
