### ISSUE TITLE
[FEATURE_REQUEST] <Batch edit Lorebooks and automatically fill in orders>

### ISSUE THREAD

**Issue by player99963** [SillyTavern/SillyTavern#2533]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Sometimes we need to change some of the entries' settings, but there are too many entries to change, making these changes very time-consuming and inconvenient, and limiting the potential of lorebooks.

### Describe the solution you'd like

So it would be great to be able to batch edit entries, which would also improve the functionality of lorebooks, as the player would be able to quickly adjust the settings of many entries to suit different needs.

In my imagination, there would be a batch edit button in lorebooks, which could be clicked to enter selection mode.
There is a select all/unselect all button, or you can manually click entries or drag ranges to select them. At the same time, there will be a "Selection Complete" button, after clicking it, a popup window will appear, the interface is similar to the current entry editing interface.
Users can edit the settings in this pop-up window, and then click "Finish Editing" to apply the editing result to all the selected entries.

I will list out the settings that I think need to be batch edited the most.

Status: I think it's very useful to batch select open/close, it's very necessary.
Position: Position is very important, sometimes lorebooks don't work well and you need to try them in a different position.
Depth: same as position
Order: When there are too many entries, managing and arranging their order becomes a troublesome task. When batch editing, you can specify a number for order, then it will start filling from the first selected entry, and every other selected entry will be automatically +1 (or other number) filled into the order.

### Describe alternatives you've considered

For batch editing of orders.
I found that when the order is the same, the output order of lorebooks seems to be according to ID? Anyway, it can't output according to my customised order. If lorebooks can output in user-defined order, I think it will be less urgent to auto-populate the orders.
![擷取](https://github.com/user-attachments/assets/353f1a8d-9849-4a5d-9a84-108e4da950ea)

### Additional context

There are many other settings in entry that I'm sure would be helpful to many people to be able to batch edit them, but these are the ones that I think are the most urgent and would help the most people.
I think it would be a good idea to release this section as soon as it is complete. If the developer intends to complete the bulk editing of the other settings, they can leave it for a future update.

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Wolfsblvt** [comment]
That's a very huge request. But yes, adding *some* kind of bulk editing utility to WI would make sense. Not as easy as one might think though. Especially with how many entries can exist and spread over multiple pages.

Maybe one day the UI gets a rework and this functionality can be added easier.

Until then, have you tried using STscript and slash commands for WI?
It should be pretty doable to loop over all WI entries of a book, check against specific criteria, and then update whatever fields you need.
You could build yourself QR buttons that open an input popup, ask you for some input, you'll define the state or whatever, and then the script in the background handles that.

**Comment by player99963** [comment]
> That's a very huge request. But yes, adding _some_ kind of bulk editing utility to WI would make sense. Not as easy as one might think though. Especially with how many entries can exist and spread over multiple pages.
> 
> Maybe one day the UI gets a rework and this functionality can be added easier.
> 
> Until then, have you tried using STscript and slash commands for WI? It should be pretty doable to loop over all WI entries of a book, check against specific criteria, and then update whatever fields you need. You could build yourself QR buttons that open an input popup, ask you for some input, you'll define the state or whatever, and then the script in the background handles that.

Programming languages are not my speciality, so what you are saying might be a bit difficult for me.
But if you're willing, I'd like to know more details, enough to make me look for tutorials to try.

**Comment by player99963** [comment]
> That's a very huge request. But yes, adding _some_ kind of bulk editing utility to WI would make sense. Not as easy as one might think though. Especially with how many entries can exist and spread over multiple pages.
> 
> Maybe one day the UI gets a rework and this functionality can be added easier.
> 
> Until then, have you tried using STscript and slash commands for WI? It should be pretty doable to loop over all WI entries of a book, check against specific criteria, and then update whatever fields you need. You could build yourself QR buttons that open an input popup, ask you for some input, you'll define the state or whatever, and then the script in the background handles that.

Since the batch edit function takes a long time to complete, is it possible to first allow entries with the same order to be output in a customised order?
I mean, we have a custom option in the sort setting, right? Then we can use the order under this sorting option to determine the output order when the entries have the same order number.

English is not my native language, so please let me know if there's anything strange in what I say.

**Comment by Wolfsblvt** [comment]
We could build a button, similar like the one that prefills the title, that'll update the order value based on your custom sorting. I'll look into whether that's feasible.

**Comment by player99963** [comment]
> We could build a button, similar like the one that prefills the title, that'll update the order value based on your custom sorting. I'll look into whether that's feasible.

Sounds great, I'll wait for the good news.

**Comment by Wolfsblvt** [comment]
PR open. Feel free to test and give feedback.

**Comment by Cohee1207** [comment]
Mass order filling released in 1.12.4

**Comment by player99963** [comment]
Just a small problem, the current auto-fill order seems to only be filled in from large to small.
But I and some players are more accustomed to placing the entries near the output position at the top, and the entries closer to the bottom at the bottom, so it would be better if the automatic filling could choose to fill in from small to large.

**Comment by Wolfsblvt** [comment]
Highest Order is the one which is inserted first. With this, the entries are presented in the same order as they are inserted into the context, which makes logical sense.

It's not really a good idea to switch the Order filling around. As nearly any sort - even the custom one -, has secondary sorting by Order ID **descending**. You'd have "jumping" entries with each time you click this button.

**Comment by player99963** [comment]
> Highest Order is the one which is inserted first. With this, the entries are presented in the same order as they are inserted into the context, which makes logical sense.
> 
> It's not really a good idea to switch the Order filling around. As nearly any sort - even the custom one -, has secondary sorting by Order ID **descending**. You'd have "jumping" entries with each time you click this button.

No problem. This is not a problem that has to be solved.
