### ISSUE TITLE
"npm is not installed" spammed over and over again 

### ISSUE THREAD

**Issue by Iommed** [SillyTavern/SillyTavern#2535]
### Environment

🪟 Windows

### System

Windows

### Version

Current

### Describe the problem

"npm is not installed. Do you want to install nodejs and npm? (y/n)"

This is the message on hitting the Start shell script. 

On Start Windows Batch file: 'npm' is not recognized as an internal or external command,
operable program or batch file.
'node' is not recognized as an internal or external command,
operable program or batch file.
Press any key to continue . . .

Update and start: Already up to date.
'npm' is not recognized as an internal or external command,
operable program or batch file.
'node' is not recognized as an internal or external command,
operable program or batch file.
Press any key to continue . .

UpdateForkAndStart: 

Checking Git installation
Current branch: release
Staying on the current branch
Updating and rebasing against 'origin'
From https://github.com/SillyTavern/SillyTavern
 * branch              release    -> FETCH_HEAD
Already up to date.
Installing npm packages and starting server
'npm' is not recognized as an internal or external command,
operable program or batch file.
'node' is not recognized as an internal or external command,
operable program or batch file.
Press any key to continue . . .

Npm IS in fact installed and therefore this is a bug.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Node and npm should be available in cmd, i.e PATH environmental variable. Reinstall and check that you enabled that option

**Comment by Iommed** [comment]
Fixed after installing Node.js manually. I guess I'm too used to TextGen Webui automatically installing everything needed -- also, huge shoutout to them for doing that
