### ISSUE TITLE
World Book Optimization

### ISSUE THREAD

**Issue by qw1642190428** [SillyTavern/SillyTavern#2539]
### Environment

🪟 Windows

### System

win10 22h2 Google 126.0.6478.182

### Version

1.12.3

### Desktop Information

node.js 22.1.0

### Describe the problem

When using Thesaurus, it's fine if there are few entries. But when there are many, both loading and expanding become extremely slow. I hope this can be optimized. I'm certain it's not a hardware issue, as it's equally slow both on the cloud and locally. 

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
World Info evaluation has been optimized in #2479, but this has not been released yet.

Please switch to staging and check if it's any better with this change.

**Comment by Cohee1207** [comment]
Optimization released in 1.12.4. Reopen if persists.
