### ISSUE TITLE
Response History/Selector

### ISSUE THREAD

**Issue by gobshyte** [SillyTavern/SillyTavern#256]
**Is your feature request related to a problem? Please describe.**
Perhaps removes the problem of not being able to see previous responses after hitting regenerate?

**Describe the solution you'd like**
Sorry if this is already possible and I'm an idiot, but it would be so useful (and seems trivial) to store the previous responses from the AI when hitting regenerate message, and allow you to cycle back and forth between them. They can be dropped once you've decided/edited your favoured message, but it would be nice when regenerating multiple times to go back and forth between them. 

Even better if this could be integrated into the message editor, so you can copy paste the best bits from multiple responses....

**Comment by gobshyte** [comment]
Damn it I thought that was something to do with touch screen support haha!
That's awesome.
It would be great if it didn't drop out of editor mode though? So I can start editing an existing message, swipe to another message and copy a section, then go back and paste it without it dropping out of the editor.
Anyway, thankful again! Cheers!

**Comment by gobshyte** [comment]
Not sure whether to close this or leave it open as a feature request to be able to do this in edit mode?

**Comment by RossAscends** [comment]
we disable editing messages during generation calls to prevent chat corruption in the case of a poorly timed edit save.
