### ISSUE TITLE
[BUG] Unable to connect to tabbyAPI endpoints when "disable_auth: True"

### ISSUE THREAD

**Issue by jmoney7823956789378** [SillyTavern/SillyTavern#2561]
### Environment

🐋 Docker

### System

Debian 12, Docker (issue is system agnostic)

### Version

SillyTavern 1.12.3

### Desktop Information

tabbyAPI commit: a1c3f6cc1cc13d1f52c28bd6a11adb5b05fc8a19

### Describe the problem

tabbyAPI endpoints without authentication are unable to be connected to, since sillytavern/tabbyAPI cannot "verify" the api key.

### Additional info

Chat-endpoints function fine, since they have a status check bypass.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by meigami0** [comment]
also same error occurs in SillyTavern 1.11.4 
```
ERROR:      File "K:\tabbyAPI\endpoints\core\router.py", line 62, in list_models
ERROR:        if get_key_permission(request) == "admin":
ERROR:      File "K:\tabbyAPI\common\auth.py", line 95, in get_key_permission
ERROR:        raise ValueError("The provided authentication key is missing.")
ERROR:    ValueError: The provided authentication key is missing.
```
auth.py
```
def get_key_permission(request: Request):
    
    # Gets the key permission from a request.

    # Internal only! Use the depends functions for incoming requests.
    
    # Hyphens are okay here
    test_key = coalesce(
        request.headers.get("x-admin-key"),
        request.headers.get("x-api-key"),
        request.headers.get("authorization"),
    )

    if test_key is None:
        raise ValueError("The provided authentication key is missing.")
```

**Comment by Cohee1207** [comment]
Not a problem in SillyTavern. This was reported to Tabby developers and fixed by them:
https://github.com/theroyallab/tabbyAPI/commit/4e808cbed78e61665223ed994da2dcf6b645fb1e
