### ISSUE TITLE
[BUG] Plugin Expression doesn't provide custom expression to LLM as options

### ISSUE THREAD

**Issue by vitorfdl** [SillyTavern/SillyTavern#2566]
### Environment

🪟 Windows

### System

Windows 11

### Version

1.12.3

### Desktop Information

- Release

### Describe the problem

I've noticed that when creating custom expression with the Expression Plugin, those custom expressions are not send to the LLM (when LLM is set as option).

Looking at the code, it doesn't seem the expected behavior.  It seems the plugin is actually ignoring the part of the code that concatenates the default with the custom expressions, because it creates a "cache" variable containing the default expression only.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Potential fix released in 1.12.4. Reopen if persists after updating.
