### ISSUE TITLE
[FEATURE_REQUEST] Add Qwen 2 Tokenizer

### ISSUE THREAD

**Issue by rrosmarinuss** [SillyTavern/SillyTavern#2574]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

N/A

### Describe the solution you'd like

Title is self explanatory. 

### Describe alternatives you've considered

GPT2 tokenizer is the closest one can get for models like Qwen and Magnum, but due to different pretokenization rules, it's not ideal.

### Additional context

N/A

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
What backend for running models do you use? Doesn't it support the tokenization endpoint?

**Comment by Cohee1207** [comment]
I'm not against adding a new tokenizer, but every tokenizer file adds a footprint on the app installation size, and tokenizers for recent models are pretty chunky (9MiB for Llama 3.1).

**Comment by rrosmarinuss** [comment]
> I'm not against adding a new tokenizer, but every tokenizer file adds a footprint on the app installation size, and tokenizers for recent models are pretty chunky (9MiB for Llama 3.1).

Oh, I understand now. The API I use (Infermatic) doesn't support tokenization endpoint when it should, so it's solely a 'them' issue. If adding a new tokenizer means increasing installation size, then I have no argument against keeping Qwen2 unimplemented.

**Comment by Cohee1207** [comment]
The tokenizer for Qwen2 is 7 megabytes. If there would be more demand, I'll add it.

https://huggingface.co/Qwen/Qwen2-72B-Instruct/blob/main/tokenizer.json

**Comment by Cohee1207** [comment]
Added to staging as an optional download.
