### ISSUE TITLE
[FEATURE_REQUEST] Quick Reply Slash-command for Tokenizer

### ISSUE THREAD

**Issue by rrosmarinuss** [SillyTavern/SillyTavern#2575]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

N/A

### Describe the solution you'd like

Implement a slash command for the Quick Replies extension to allow one to swap to a different tokenizer upon send. [Ex. `/tokenizer Llama3`]

### Describe alternatives you've considered

'Best match' is the ideal solution for when swapping models/presets using Quick Replies, however, certain APIs do not support that setting and therefore require the user to change their tokenizer manually each time.

### Additional context

Wolfsblvt on Discord recommended I make a feature request here about it.

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Wolfsblvt** [comment]
Agreed, makes sense.
Someone can pick this up, adding the current tokenizers to a slash command, while still allowing to switch to and back to the "Best match" model.

Should supplement the usage of `/api`, `/model` and such.

**Comment by Wolfsblvt** [comment]
Is done and already included in the latest release.
