### ISSUE TITLE
[BUG] Show more messages

### ISSUE THREAD

**Issue by Hakirus** [SillyTavern/SillyTavern#2586]
### Environment

🪟 Windows

### System

brave

### Version

0c2df51e

### Desktop Information

Windows  / Android

### Describe the problem

In a chat window with a character, if user delete message up to show more messages, when clicking on Show more messages nothing happen.  No Error in the console.  Msg. to load set to 5.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Wolfsblvt** [comment]
Made a PR to fix this issue. Are you willing to test this?
