### ISSUE TITLE
[BUG] Group nudge breaks impersonation for chat completion group chat

### ISSUE THREAD

**Issue by cloak1505** [SillyTavern/SillyTavern#2588]
### Environment

🪟 Windows

### System

Firefox

### Version

1.12.4 'release' (eac2e3d8), 1.12.4 'staging' (87a563e7)

### Describe the problem

Chat Completion: During group chat, the group nudge remains and conflicts with the impersonation prompt. Basically, you get this:

```
System: [Write the next reply only as Char.]
System: [Write your next reply from the point of view of User, using the chat history so far as a guideline for the writing style of User. Don't write as Char or system. Don't describe actions of Char.]
```

Sometimes it works, but sometimes it doesn't. Ideally the impersonate prompt should disable the group nudge. The workaround is to clear the group nudge from Utility Prompts then make custom prompts for group nudge and impersonation, and use one at a time.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Wolfsblvt** [comment]
Fixed on staging, you can test this if you want.

**Comment by cloak1505** [comment]
Yes, it works, thanks.
