### ISSUE TITLE
[Resolved] How can I make SillyTavern complete the connection through the proxy?

### ISSUE THREAD

**Issue by RIFTaReLINK** [SillyTavern/SillyTavern#259]
Sorry, I know what the problem is. It's a problem with my own environment.

I used Clash to connect to the proxy, but Clash does not support IPv6 connections well. 

I found out that maybe because my router has IPv6 support turned on, SillyTavern is trying to connect to an IPv6 address, which prevents data from being transferred through the proxy. 

The problem was solved after I turned off the IPv6 feature on my router.

------------------------------

I can't successfully connect to the OpenAI server by simply filling in the API and clicking connect. 
I guess it's because my area is outside of OpenAI's service area and I usually use a proxy to access the ChatGPT website.

I noticed that even though I turned on the proxy, I still couldn't complete the connection, probably because SillyTavern doesn't use the system's proxy route. 

How can I make SillyTavern complete the connection through the proxy?

**Comment by RossAscends** [comment]
user changed the title to 'resolved' a month ago.
