### ISSUE TITLE
"Unknown error occurred"

### ISSUE THREAD

**Issue by JoyWeeler-099** [SillyTavern/SillyTavern#2603]
### Environment

📱 Termux

### System

Termux

### Version

1.12.4

### Describe the problem

It's valid... But when testing it, it gives me "Unknown error occurred" (look at the screenshot)

### Additional info

![IMG_20240802_225218](https://github.com/user-attachments/assets/1903e807-588e-40a8-8da8-ec0d841a0cb0)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by JoyWeeler-099** [comment]
> I can't provide support with third-party endpoints.

Is it your problem...or them?

**Comment by Wolfsblvt** [comment]
Very likely them.
But as written everywhere, ST doesn't provide support for any third-party endpoint/proxy.
