### ISSUE TITLE
[FEATURE_REQUEST] <Please support FLUX Image generation as part of integration with SillyTavern in some way>

### ISSUE THREAD

**Issue by cleverestx** [SillyTavern/SillyTavern#2606]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

flux follows prompts WAY better out of the box than SD does, even with LORA and 3rd party models. It's fantastic. Please support it; one way would be via Comfy, since you can run FLUX locally in Comfy now. I tried using through Extensions > Image Generation, but it's not working/unsupported since it's not Stable Diffusion.

### Describe the solution you'd like

Please add Flux support. SD support exists already. Not sure what else to say here, but I'll be happy to test and provide logs if someone wants to work on this. I have a single RTX 4090 and 96GB of RAM, I meet the requirements easily.

### Describe alternatives you've considered

I use SD, but Flux is proving much better for us users with a high-end system. I realize this is not as many, but it would be a nice feature to have in ST.

### Additional context

![image](https://github.com/user-attachments/assets/b7c56513-706f-499d-9b58-29e3cba96278)

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
Comfy is supported. And the extension is called Image Generation.

**Comment by cleverestx** [comment]
> Comfy is supported. And the extension is called Image Generation.

Comfy is supported, but not Flux. All parameters in Comfy when loaded into ST is for SD.  I posted the error I get trying to use Flux with image generation using Comfy in IT. I can use SD models in comfy just fine. (in ST)

**Comment by Cohee1207** [comment]
You can skip any parameters and use values directly from the workflow JSON, leave just the `%prompt%`, `%seed%`, `%width%` and `%height%`.

Workflow attached, and tested working, assuming you got all the models downloaded.

```json
{
  "6": {
    "inputs": {
      "text": "%prompt%",
      "clip": [
        "11",
        0
      ]
    },
    "class_type": "CLIPTextEncode",
    "_meta": {
      "title": "CLIP Text Encode (Positive Prompt)"
    }
  },
  "8": {
    "inputs": {
      "samples": [
        "13",
        0
      ],
      "vae": [
        "10",
        0
      ]
    },
    "class_type": "VAEDecode",
    "_meta": {
      "title": "VAE Decode"
    }
  },
  "9": {
    "inputs": {
      "filename_prefix": "ComfyUI",
      "images": [
        "8",
        0
      ]
    },
    "class_type": "SaveImage",
    "_meta": {
      "title": "Save Image"
    }
  },
  "10": {
    "inputs": {
      "vae_name": "ae.sft"
    },
    "class_type": "VAELoader",
    "_meta": {
      "title": "Load VAE"
    }
  },
  "11": {
    "inputs": {
      "clip_name1": "t5xxl_fp16.safetensors",
      "clip_name2": "clip_l.safetensors",
      "type": "flux"
    },
    "class_type": "DualCLIPLoader",
    "_meta": {
      "title": "DualCLIPLoader"
    }
  },
  "12": {
    "inputs": {
      "unet_name": "flux1-dev.sft",
      "weight_dtype": "fp8_e4m3fn"
    },
    "class_type": "UNETLoader",
    "_meta": {
      "title": "Load Diffusion Model"
    }
  },
  "13": {
    "inputs": {
      "noise": [
        "25",
        0
      ],
      "guider": [
        "22",
        0
      ],
      "sampler": [
        "16",
        0
      ],
      "sigmas": [
        "17",
        0
      ],
      "latent_image": [
        "27",
        0
      ]
    },
    "class_type": "SamplerCustomAdvanced",
    "_meta": {
      "title": "SamplerCustomAdvanced"
    }
  },
  "16": {
    "inputs": {
      "sampler_name": "euler"
    },
    "class_type": "KSamplerSelect",
    "_meta": {
      "title": "KSamplerSelect"
    }
  },
  "17": {
    "inputs": {
      "scheduler": "simple",
      "steps": 20,
      "denoise": 1,
      "model": [
        "12",
        0
      ]
    },
    "class_type": "BasicScheduler",
    "_meta": {
      "title": "BasicScheduler"
    }
  },
  "22": {
    "inputs": {
      "model": [
        "12",
        0
      ],
      "conditioning": [
        "26",
        0
      ]
    },
    "class_type": "BasicGuider",
    "_meta": {
      "title": "BasicGuider"
    }
  },
  "25": {
    "inputs": {
      "noise_seed": "%seed%"
    },
    "class_type": "RandomNoise",
    "_meta": {
      "title": "RandomNoise"
    }
  },
  "26": {
    "inputs": {
      "guidance": 3.5,
      "conditioning": [
        "6",
        0
      ]
    },
    "class_type": "FluxGuidance",
    "_meta": {
      "title": "FluxGuidance"
    }
  },
  "27": {
    "inputs": {
      "width": "%width%",
      "height": "%height%",
      "batch_size": 1
    },
    "class_type": "EmptySD3LatentImage",
    "_meta": {
      "title": "EmptySD3LatentImage"
    }
  }
}
```

**Comment by cleverestx** [comment]
Thank you, I have this set up now, but not sure what to do with the model drop-down...it looks at the location of my SD models, not Comfy and doesn't show the SCHNELL or DEV models in the comfy folder...do I need to select something here or copy the comfy models into this folder so I can choose it in the ST interface here?

![image](https://github.com/user-attachments/assets/0cc262d6-4204-4b92-a23b-4ec6d5cf0b4c)

**Comment by Cohee1207** [comment]
> not sure what to do with the model drop-down

Nothing. It shows checkpoints, not unets. Specify all models directly in the workflow.

**Comment by cleverestx** [comment]
Got it. I also didn't want the models drop-down to conflict with the workflow if I left something in it (I couldn't blank it out), but thanks, I'll ignore it.
