### ISSUE TITLE
Add gemini-1.5-pro-exp-0801 to google makesuite api

### ISSUE THREAD

**Issue by zzc0208** [SillyTavern/SillyTavern#2610]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

No

### Describe the solution you'd like

Add gemini-1.5-pro-exp-0801 to google makesuite api
google's new model,model name:`gemini-1.5-pro-exp-0801`
![Screenshot_2024-08-03-18-18-00-848_com microsoft emmx](https://github.com/user-attachments/assets/dd47e1a5-b090-49dc-bd9d-f8ce323a77cb)

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

None

**Comment by Cohee1207** [comment]
#2600
