### ISSUE TITLE
[FEATURE_REQUEST] HuggingFace Inference API for Image generation

### ISSUE THREAD

**Issue by shivdbz2010** [SillyTavern/SillyTavern#2613]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

add HuggingFace Inference API for Image generation

### Describe the solution you'd like

HuggingFace Inference API for Image generation

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by ayancey** [comment]
Check out staging and test it out!

**Comment by Wolfsblvt** [comment]
Was merged and released with the latest release.
