### ISSUE TITLE
[BUG] World info entry names isn't imported

### ISSUE THREAD

**Issue by mirh** [SillyTavern/SillyTavern#2616]
### Environment

🪟 Windows

### System

Firefox 129, Windows 10

### Version

1.12.4 'release' (eac2e3d8)

### Desktop Information

Node-v20.16.0

### Describe the problem

I imported some big assed lorebook json from chub.ai. 
Pretty much everything was like you'd expect, except all the "titles" of the imported entries were empty ("Entry Title/Memo" is left to fill inside the tavern). 

After some skimming, I figured you must be dropping the `name` field from the values array. 

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Not a bug. We use the **comment** entry field to display an entry title. Chub uses **name** instead, which was never a part of the WI format SillyTavern uses. Report this to Chub.

**Comment by mirh** [comment]
[I see](https://docs.sillytavern.app/usage/st-script/#valid-entry-fields) (maybe @lloorree @CharHubAI can give it a check?)

But now that I think to it, the question comes kinda natural: despite your intents certainly being higher in authority, why did you decide on that *monicker* to begin with?
Like.. if I really go out of my way to see it, I can imagine how the LLM doesn't really need labels to organize and know the entities that are being defined by the lorebook. So whatever other property you add, it is just a casual reminder for the convenience of the user (and in this sense, it's no different from "comments" in the software programming sense). 

But if they are being used, and are supposed, to be the **titles** of every added element (i.e. not some "free text" field, to rant about how much time you spent banging your head on a concept or whatever)... than I see why chub may have stepped outside its due boundaries.

**Comment by Cohee1207** [comment]
`comment` is indeed not used in the LLM prompting and is used only to provide a quick note on what the entry is about without the need to expand it. The **only** field that is inserted into the prompt is `content`.

LLM is not aware of how the context is built exactly, and it doesn't need to. WI/lorebook is an inherently bad name because it shadows the fact that these are just glorified prompt injections.

**Comment by mirh** [comment]
Yes, I had guessed correctly then. 
And if this was exclusively for use and consumption of the inference engine (like a model?) it would be hard to disagree. 

But for as much as perhaps not its original purpose, it is functionally used as an interchange format too. 
And from the needs of browsing and presenting the plain data, of course humans may require some extra context. 
It's not so much that chub *replaced* "comment" with "name" (it's still [there](
https://www.characterhub.org/lorebooks/novinaare/ghostbusters-beb339a0) if you check), they ***added*** it. Because a title isn't a memo and vice versa.

**Comment by Cohee1207** [comment]
Yes, they added it. But I refuse to add it since there's already a field that fulfills this exact purpose.

**Comment by mirh** [comment]
I firmly believe that "humanly speaking" a title/name/label is pretty conceptually different from a comment/remark/annotation.. but your monkeys eventually to judge I guess.
