### ISSUE TITLE
[FEATURE_REQUEST] Max Depth for Lorebook Recursion

### ISSUE THREAD

**Issue by ghost** [SillyTavern/SillyTavern#2622]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

ST's current methods for capping lorebook recursion (token caps, max depth) are awkward and hard to reason about deterministically.

### Describe the solution you'd like

A configuration option that lets the user cap how far ST can recurse lorebook activations. So, for example, at max_recursion_depth=1, ST will load the lorebook entries that were activated by the chat history/are always active, see what lorebook entries those activate, enable those and stop recursing. 2 would add the lb entries _those_ activate as well, and so on so forth.

### Describe alternatives you've considered

As I've mentioned earlier, token caps and min activations are just hard to reason about in most contexts.

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Wolfsblvt** [comment]
What would a use-case for this be, that you cannot build in a similar way with the existing settings?
Why would you limit recursive scanning?
You can simply set the entries to "only on recursion" and "prevent recursion", if you want to limit what recursion does.

**Comment by ghost** [comment]
> What would a use-case for this be, that you cannot build in a similar way with the existing settings? Why would you limit recursive scanning? You can simply set the entries to "only on recursion" and "prevent recursion", if you want to limit what recursion does.

Sure, consider the following example lorebook (presented in key value format):

```
Robert: Robert is blond and friends with Alice and Roger.
Alice: Alice is a brunette, friends with Robert.
Roger: Roger is ginger, friends with Robert and Beatrix.
Beatrix: Beatrix is blonde, Roger's friend.
```

Assuming "Robert" is currently in the story, we can disable recursion and load exclusively the Robert entry. Alternatively, we can enable recursion, and then the entire lorebook is loaded into context.

Usually, you don't want either. What you _actually_ want in this situation is, _usually_, to load Robert and _the people he might most naturally bring up in conversation_, namely Alice and Roger, his friends. And, for things like series lorebooks (Touhou, Granblue, etc), this is almost always the behavior you want out of the lorebook.

Limiting the recursion steps solves that specifically. You load the people immediately relevant to the context, and the people immediately relevant to those people, and then you stop. Or you continue for another step (how many levels of recursion are optimal depends a lot on the LLM and Lorebook, but I'd personally mostly just recurse once).

Limiting the amount of the context the lorebook can take up is the current ST technique for dealing with lorebooks that look like that, and IMO it's much less reliable and very hard to reason around. Yeah, I know that things will keep getting loaded until _this many_ entries have been activated, but _what on Earth does that really tell me_. This is clean and very obviously deterministic.

**Comment by Wolfsblvt** [comment]
I would just mark all of the entries as "Prevent Recursion", so they are not used for further WI scanning.
Then have Jon's actual "character card" or description as its own, separate entry, and mention all their possible first-hand friends there. 
Makes a lot more sense even, because if Robert is present, you likely want much more information about him in that entry than another WI entry that mentions Robert, for example if Alice is present.

If you make a global setting about recursion depth, you'll stop a lot of *cool tricks* with WI being used as dynamic context and prompt builder from actually working.
That's why we have most relevant settings on the entries individually. The global settings are mostly about managing how much stuff you actually want to be present.

**Comment by ghost** [comment]
I think you misunderstand the intention of this feature request. Limiting recursion depth would be an alternative to the current context budgeting methods. Currently, recursion is nearly useless if you have a lorebook with many entries which have many different degrees of relation in how they activate each others' keys. They will simply chain activate and fill the budget immediately.

This feature would be invaluable for lorebooks with many different characters and locations (which refer to each other), as you could pull entries which only have one or two degrees of separation from directly activated keys in the scan depth.

**Comment by ghost** [comment]
> I would just mark all of the entries as "Prevent Recursion", so they are not used for further WI scanning.
> Then have Jon's actual "character card" or description as its own, separate entry, and mention all their possible first-hand friends there.

I think you misunderstood the issue. Robert is not supposed to be {{char}}, Robert is just a character in the lorebook. He's not supposed to be in the description, he's just relevant when he's in the context.

I can't just disable recursion on everyone else because, when Roger is on the scene, I also want the Beatrix entry to load, because if Roger is there then Beatrix is now relevant to the context.

>If you make a global setting about recursion depth, you'll stop a lot of cool tricks with WI being used as dynamic context and prompt builder from actually working.

I'll be honest I have no idea what you're talking about.

EDIT: The Lorebook I gave is an *example* for what a series lorebook looks like. You're supposed to imagine it's _immense_ and filled with, like, Naruto characters or something, and that I'm using a Naruto World RP bot.

**Comment by Wolfsblvt** [comment]
I am not averse to providing more fine control over how WI works.
Just.. I'm trying to tell you there it is very likely the feature like you are describing will not lead to the result that you'd like to have, for several reasons.

Doesn't hurt to have it though, so I can add it.

Edit: Note this will also limit/disable "Min Activations" in a way, as there is no way to keep track of if an entry was triggered recursively or not.
What we can do is limiting the number of times the loop to check for WI entries is being run. Which will implicitly limit recursion count.

**Comment by ghost** [comment]
> Just.. I'm trying to tell you there it is very likely the feature like you are describing will not lead to the result that you'd like to have, for several reasons.

Which would be? At the very should be much easier to reason around than context budgets for series lorebooks imo.

>Edit: Note this will also limit/disable "Min Activations" in a way, as there is no way to keep track of if an entry was triggered recursively or not.

I don't think I've ever used min activations or came across a natural use case tbqh.

**Comment by Cohee1207** [comment]
Very basic description added to docs.
https://docs.sillytavern.app/usage/core-concepts/worldinfo/#max-recursion-steps
