### ISSUE TITLE
[FEATURE_REQUEST] STScript addswipe switch to added swipe

### ISSUE THREAD

**Issue by Quairon-Nailo** [SillyTavern/SillyTavern#2626]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

addswipe allows us to create a new swipe for a message. However, the message will stay in the current one rather than automatically switching to the one we just added.

### Describe the solution you'd like

Having it switch to the new one, or at least having a parameter like switch=true to do that would be great.

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Wolfsblvt** [comment]
PR is open.

Check out https://github.com/LenAnderson/SillyTavern-LALib though. This user extension already had those commands. And many many more that are great for people using STscript.

**Comment by Wolfsblvt** [comment]
You can test this on staging now.

**Comment by Quairon-Nailo** [comment]
Oh, yeah, I have been using it, works perfectly, thanks!
