### ISSUE TITLE
[BUG] <title> When accessing silly tavern via ios safari, there are chance that browser may use voice Samantha says “hi” 

### ISSUE THREAD

**Issue by yca321** [SillyTavern/SillyTavern#2631]
### Environment

🐧 Linux

### System

Ubuntu/ios

### Version

1.11.8

### Desktop Information

Using an ubuntu server to run silly tavern, and access silly tavern via IOS safari

### Describe the problem

While accessing silly tavern in iOS safari, there are chances that browser will use the Samantha voice from tts, and speaks “hi”.
(quite spooky sometimes)
Asked few people who are running silly tavern in the same way, they also occasionally get this issue.

Haven’t seen any Android user who are also access remote silly tavern that running on a Linux server getting this issue though.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by yca321** [comment]
Also I am facing this issue even if my device is set to silence, and I didn't enable any tts function or any voice tool/api for silly tavern. tts1.0.0 which seems come with my default setting is available under my extension session of toolbar, but no check box was checked under the tts section.(I don't use the voice function myself, so I have little knowledge to that)

No button was clicked when “hi” is triggered, it happens even if I left my phone on the desk with screen on, no touch, and no text was in the progress of generation (all text generated)

**Comment by Cohee1207** [comment]
This is supposed to be silent and exists cause iOS only allows speech synthesis (for system TTS engines) in response to user interaction, so silent audio is played the first time you click anything. I replaced the placeholder text with something that doesn't produce any sound even with full volume, but I'm unsure if that doesn't break system TTS on iOS.

**Comment by yca321** [comment]
> This is supposed to be silent and exists cause iOS only allows speech synthesis (for system TTS engines) in response to user interaction, so silent audio is played the first time you click anything. I replaced the placeholder text with something that doesn't produce any sound even with full volume, but I'm unsure if that doesn't break system TTS on iOS.

Thanks Cohee, I will let you know if this happens again with new fix!
