### ISSUE TITLE
[FEATURE_REQUEST/BUG] Add MistralAI Prefill/Prefixes <title>

### ISSUE THREAD

**Issue by CandyIsaChad** [SillyTavern/SillyTavern#2632]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Yes, just a few weeks back, **MistralAI** had support for the ability to add Prefills manually by creating a custom prompt and placing it at the bottom. 

But recently, **I don't know when**, they had changed something that would require the user to have an extra parameter to make prefills/prefixes officially work, which looks like this;

```python
    messages = [
        {
            "role": "user",
            "content": "Placeholder",
        },
        {
            "role": "assistant",
            "content": "Placeholder, reciting the alphabet now; A, B, C, D, E, F,",
            "prefix": True # The new required parameter for Assistant Prefills to work
        }
    ]
```

### Describe the solution you'd like

I'm not an expert at figuring out how this works, but I'd figured that if `convertMistralMessages` were changed up a bit to support the new `prefix` parameter, it would fix/improve my issue, or even implementing/cloning the "Assistant Prefill" area from the Claude Completion Source to Mistral;

![image](https://github.com/user-attachments/assets/ed93c146-ffeb-43ed-9128-b1a99d838f4b)

### Describe alternatives you've considered

__I'm not exactly sure this is what's causing the issue, all I know is that Prefills used to work with Mistral, and by Manually testing and checking console requests, I'm 80% sure this is what's causing it judging by the chat history format, and the way it wouldn't give me an error if I were to disable the prompt.__
![image](https://github.com/user-attachments/assets/fa9c74d2-9e58-4bce-b229-731e97383af6)

### Error I'm getting when using custom Prefill Prompt
![image](https://github.com/user-attachments/assets/8501eed0-e401-459f-9a72-7c4385161909)

### Error I'm getting when manually testing
![image](https://github.com/user-attachments/assets/3138a7c4-c4cb-46bd-ba42-2dc6102c12d2)

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by CandyIsaChad** [comment]
#2557 states that I should enable this;

> To bring the prefix back after pulling, change this in your config.yaml and restart.
> 
> ```yaml
> mistral:
>   enablePrefix: true
> ```

But it ends up just breaking the response for me as it doesn't trim out the Prefill itself.

**Comment by qwertea** [comment]
as a temporary workaround you can just regex your prefix out of responses

**Comment by Cohee1207** [comment]
> But it ends up just breaking the response for me as it doesn't trim out the Prefill itself

This is exactly why it is disabled by default. I'm not sure when or if Mistral API developers would change this behavior, but they're aware of prefix echoing being not expected from the user side. Until then - use a workaround as suggested above.
