### ISSUE TITLE
[BUG] Timezone not respected with TZ environment variable

### ISSUE THREAD

**Issue by deadmeu** [SillyTavern/SillyTavern#2637]
### Environment

🐋 Docker

### System

Firefox 128

### Version

1.12.4

### Describe the problem

Messages and system logs do not seem to respect the `TZ` environment variable.
E.g.:
- `access.log` is reporting using UTC when I have set the timezone to `Asia/Tokyo`.
- Chat messages are displayed using the browser's configured timezone rather than the set timezone.

The timezone is being set as per the documentation `-e TZ="Asia/Tokyo"` when running the container.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Wolfsblvt** [comment]
Yep. We are using many different time display formats in ST, and not all work correctly with timezones.
Not sure this is something easy to fix or change.

**Comment by Cohee1207** [comment]
It's better just to remove TZ from the Docker setup line. I'm not sure why it is there in the first place.

**Comment by Cohee1207** [comment]
TZ removed from readme. It did never actually do anything, likely was there by mistake.
