### ISSUE TITLE
[FEATURE_REQUEST] TTS: OpenAI-compatible custom server support (e.g. openedai-speech)

### ISSUE THREAD

**Issue by t-m-w** [SillyTavern/SillyTavern#2639]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

The OpenAI option for the TTS extension only supports the official OpenAI server. Custom OpenAI-compatible servers can't be specified.

### Describe the solution you'd like

It would be great to be able to enter a custom URL for the OpenAI TTS support so that alternatives like [openedai-speech](https://github.com/matatonic/openedai-speech) can be used. This is supported by Open WebUI, so it would allow this one solution to work with both projects.

### Describe alternatives you've considered

Using whatever the (custom) Chat Generation endpoint is set as would *almost* work, but openedai-speech doesn't implement chat completion (not its goal), so a middle-server would be needed to redirect requests appropriately, which isn't great.

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by ayancey** [comment]
Great idea #2654

**Comment by ayancey** [comment]
Tested with openedai-speech, and it seems to work.

**Comment by ayancey** [comment]
Please checkout staging and let me know if you find any bugs 😄

**Comment by t-m-w** [comment]
Wow, that was fast, thanks! Seems to work great so far.

I don't know if this is even a bug, or if it is related to this change, but I noticed if you switch to an existing conversation, the very next message sent is not voiced, whether it be one that the user sends or one that a character sends, but the following messages are voiced as expected. New conversations are not affected.

**Comment by ayancey** [comment]
> Wow, that was fast, thanks! Seems to work great so far.
> 
> I don't know if this is even a bug, or if it is related to this change, but I noticed if you switch to an existing conversation, the very next message sent is not voiced, whether it be one that the user sends or one that a character sends, but the following messages are voiced as expected. New conversations are not affected.

@Cohee1207
