### ISSUE TITLE
[BUG] Impersonate problem on Chat Groups

### ISSUE THREAD

**Issue by vitorfdl** [SillyTavern/SillyTavern#2645]
### Environment

🪟 Windows

### System

Windows 11, Microsoft Edge

### Version

1.12.4 and staging

### Describe the problem

When using the command `/impersonate (waited=true)` with Force Names enabled in instruction mode, Sillytavern incorrectly adds `System:` as the assistant prefix instead of the expected {{user}} in group chats.

**Steps to reproduce:**
1. Enable Force Names in instruction mode
2. Create a Group Chat.
3. Use the command `/impersonate (waited=true)`

**Expected behavior:**
The assistant prefix should be {{user}} (`Taro:`) 

**Actual behavior:**
The assistant prefix is `System:`

```
<|eot_id|><|start_header_id|>system<|end_header_id|>

[Event Direction for the next story beat on Taro perspective: `As they sit down to enjoy their meal, Taro's eyes wander to a small, leather-bound book on Senshi's table, the cover adorned with intricate runes and symbols that seem to hum with an otherworldly energy.`]
[Based on the expected events, write the user response]<|eot_id|><|start_header_id|>user<|end_header_id|>

System:
```` 

- The issue seems to occur around line 3952 in the Generate function in scripts.js
The `quietToLoud` variable is undefined when reaching this part of the code
````
        if (isInstruct && !isContinue) {
            const name = (quiet_prompt && !quietToLoud) ? (quietName ?? 'System') : (isImpersonate ? name1 : name2);
            const isQuiet = quiet_prompt && type == 'quiet';
            lastMesString += formatInstructModePrompt(name, isImpersonate, promptBias, name1, name2, isQuiet, quietToLoud);
        }
````

**Additional notes:**
- The `doImpersonate` function appears to be sending the `quietToLoud` parameter as `true`
- Further investigation may be needed to understand why `quietToLoud` is undefined at this point in the code execution
- I stopped my debugging there, as I made a local modifification to the condition:
  From: `const name = (quiet_prompt && !quietToLoud)`
  To: `const name = (quiet_prompt && !quietToLoud && !isImpersonate)`

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
I just applied your patch, it seems logical.
