### ISSUE TITLE
[FEATURE_REQUEST] <title>Support GPT-SoVits

### ISSUE THREAD

**Issue by bushnerd** [SillyTavern/SillyTavern#2649]
### Have you searched for similar requests?

Yes

### Describe the solution you'd like

Support GPT-SoVits

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

None

**Comment by Cohee1207** [comment]
It's already there #1930

**Comment by bushnerd** [comment]
Thanks for your reply
