### ISSUE TITLE
[BUG] Mistral Large's prefix feature doesn't send last message as Assistant's.

### ISSUE THREAD

**Issue by GuyfromGit** [SillyTavern/SillyTavern#2653]
### Environment

🪟 Windows

### System

Brave v 1.68.137

### Version

1.12.4

### Describe the problem

When trying to use Mistral's prefix feature, in the console it doesn't appear as Assistant's message, either as system's if last message sent is a system's one, or a User's otherwise. Because of this, I believe it might be sending the prefix wrong.

### Additional info

![MistralPrefixWeird](https://github.com/user-attachments/assets/b629c885-e33e-4e7e-a98d-2fcd99b1f4f5)
Example of how it looks, as mentioned prior.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
https://docs.mistral.ai/api/#tag/chat/operation/chat_completion_v1_chat_completions_post

![image](https://github.com/user-attachments/assets/f44b8fa1-0274-4f58-9833-f1ffab56cdd8)

**Comment by GuyfromGit** [comment]
I'm sorry but that's rather unclear to me.
In any case, in config.yaml, enablePrefix is set to True and Silly was restarted, but prefix still doesn't work. In the prompt manager, role is set to Assistant but that doesn't work as well and I get an error. Screenshots of what I am talking about.
![PrefixIStrue](https://github.com/user-attachments/assets/eea76d78-5bfd-4d68-9342-99878cdcef69)
![PromptManagerMistralAssistant](https://github.com/user-attachments/assets/41365131-0856-4c36-a651-8d4ce3087599)
![TruePrefix](https://github.com/user-attachments/assets/5ba21db2-2ea6-476f-82d4-a5fe5637b9fe)

Hope this clarifies my problem and that I have done what I can to try fixing this without messing with code, which I have no idea of what to do.

**Comment by Cohee1207** [comment]
Where is that message? Where it's from? Do you use some kind of reverse proxy?

If yes, then NO SUPPORT will be provided.

**Comment by GuyfromGit** [comment]
I understand and yes, it is from a proxy. I don't think I can change your mind regarding helping out, so I will let sleeping dogs lie. Thanks for the answers, regardless. Closing this issue.

**Comment by ghost** [comment]
The issue in this case isn't proxies. AWS mangled the Mistral API for some genuinely incomprehensible reason, so prefills and phis don't work. You can confirm this by directly consuming AWS Mistral.

But it's also not an ST issue, so just leave it closed.
