### ISSUE TITLE
[BUG] Lorbook 'Apply current sorting as Order'

### ISSUE THREAD

**Issue by drago87** [SillyTavern/SillyTavern#2657]
### Environment

🪟 Windows

### System

Win 10, Opera

### Version

1.12.4 'release' (eac2e3d81)

### Describe the problem

When pressing the 'Apply current sorting as Order' button it tells me that 'Apply your current sorting to the "Order" field.'.
Pressing the button changes the "Depth" field. Either this is a bug or the tooltip needs to be made clearer.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
If you use third-party extensions that modify the WI entry header, it makes field labels misaligned.

**Comment by drago87** [comment]
Noticed that. That's why i closed it.
