### ISSUE TITLE
 [Help] how to turn off toast notifications.

### ISSUE THREAD

**Issue by Abdulhanan535** [SillyTavern/SillyTavern#2661]
I use stscripts due to that there are alot of toast notifications, is there any way to disable them??

**Comment by LenAnderson** [comment]
Stop writing /echo everywhere.

**Comment by Cohee1207** [comment]
What scripts? I can't help with code that I can't see.

**Comment by Abdulhanan535** [comment]
i mean when ever i do /summarize or or /api the popup appears...

**Comment by Abdulhanan535** [comment]
this is the code

```
// save current values 
/api | /setvar key=saveApi || /preset | /setvar key=savePreset || /context | /setvar key=saveContext ||
// set your preset, model, api here |
/api cohere ||
// get SD freemode prompt and generate |
/summarize ||
/sd you ||
// restore previous values |
/api {{getvar::saveApi}} ||
/flushvar saveApi || /flushvar savePreset ||
```

**Comment by Wolfsblvt** [comment]
We could possibly add `quiet` arg to quite a few of the slash commands.
But generally I think having toasts is not bad. You should be notified if your API changes, for example.

**Comment by Abdulhanan535** [comment]
its annoying, cuz i use the script for summary and image generation.
