### ISSUE TITLE
[BUG] Cannot connect to ComfyUI

### ISSUE THREAD

**Issue by hartmark** [SillyTavern/SillyTavern#2664]
### Environment

🐧 Linux

### System

Arch Linux

### Version

1.12.4

### Desktop Information

Docker compose image from repo

### Describe the problem

I have added this to the docker-compose.yml so I map against localhost:
```
    extra_hosts:
      - "host.docker.internal:host-gateway"
```

Then I have connected to the container:
```
CONTAINER ID   IMAGE                                    COMMAND                  CREATED              STATUS                 PORTS                                                                          NAMES
4cfa2c7345aa   ghcr.io/sillytavern/sillytavern:latest   "tini -- ./docker-en…"   About a minute ago   Up About a minute      0.0.0.0:8000->8000/tcp, :::8000->8000/tcp                                      sillytavern
```
```
markus@bernard ~/code/docker/ollama % sudo docker exec -ti 4cfa2c7345aa /bin/sh
/home/node/app # ping host.docker.internal
PING host.docker.internal (172.17.0.1): 56 data bytes
64 bytes from 172.17.0.1: seq=0 ttl=64 time=0.090 ms
64 bytes from 172.17.0.1: seq=1 ttl=64 time=0.077 ms
```

But when changing settings to ComfyUI and using http://host.docker.internal it fails to connect.
![image](https://github.com/user-attachments/assets/3c038fcf-2634-49eb-b1f0-706654b2b077)

Surfing to http://localhost/system_stats gets me this response:
![image](https://github.com/user-attachments/assets/e03c5295-981a-402a-bfb1-ae09f0e1ad93)

Connecting to my Ollama endpoint works perfectly
![image](https://github.com/user-attachments/assets/8545ed78-d985-4860-9da5-e7659c5c6568)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by LenAnderson** [comment]
I very much doubt that this is a bug. Sounds a lot more likely that it's an issue with how you set up your network and services.

What address is your comfy service listening on? I believe it defaults to 127.0.0.1 which means it is not reachable for external connections. And I would suspect that a connection coming from a docker container would be treated as such.
You can easily check whether or not comfy is reachable from another device (second computer, phone, ...).

**Comment by hartmark** [comment]
It was listening on all interfaces, just that ufw stopped it. I thought local docker access was allowed with ufw.

Just running this command on docker host fixed my issue:
`sudo ufw allow 80/tcp comment sd-web`
