### ISSUE TITLE
[FEATURE_REQUEST] Databank without vectorization

### ISSUE THREAD

**Issue by antonovmaxim** [SillyTavern/SillyTavern#2671]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Hello! The databank feature provides a very convenient format for sharing files with a chatbot. However, this requires file vectorization. I was happy to work with this system through a provider together.ai however, I am having problems with vectorization on openrouter. But in this case, I don't need vectorization, I would be happy to just share the text.

### Describe the solution you'd like

I think it's worth adding a "no vectorization" feature to just share files from DATABANK with the character. For example, if a certain provider does not provide an api for vectorization.

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
How would you imagine it working then? Data Bank depends on being able to tell which chunks are relevant. Adding all of the chunks for all files at once seems wasteful to me.

An alternative exists, however. Just attach files to directly messages via the message actions. When vectorization is disabled, you'll be able to fully insert them into the prompt.

**Comment by antonovmaxim** [comment]
You misunderstood me. I think the DATABANK interface is convenient in itself: you can edit files at the right time, perform a web search, parse web pages, etc. This is a powerful tool for determining what exactly gets into the input of the model. File vectorization is a useful feature, but I'm in favor of trying to separate these two features from each other. Just add a checkbox "databank without vectorization", or something like that. As for attaching a file to messages, of course, I use it, but it's not so convenient. Anyway, thanks for the quick response!

**Comment by Cohee1207** [comment]
I still don't understand your proposal. While it's true that the Data Bank itself does not solely depend on Vector Storage, as it's technically a shared functionality, and Vector Storage is just a reference implementation, I'm puzzled about how exactly to determine which files get into the prompt, and where (position) they get into the prompt.

Maybe you'd want to look into using Data Bank STscript commands with /inject to manually perform injections? Create a couple of Quick Replies with exactly the logic you imagine. Like this:
```
/databank-get source=character file.txt | /inject id=fileInject position=chat 
```

**Comment by antonovmaxim** [comment]
Let me give you a concrete example:

Model: gpt-4o (used via openrouter), bot: basic bot assistant.
```
User: Hi, can you help me with this? I need to look into this article.
Bot: Yeah, sure. Provide the text.
User: Ok, the text is in your DATABANK. Do you see it?
<user adds a pdf, parses a web page, etc.>
Bot: Yes, I can see it. It's an article about ... 
User: How would you comment on the third paragraph?
(After ~80 messages).
User: Thanks for your help! <deletes file from databank> And now... (changes the topic of the dialog)
```
Current behavior (attached to messages):
1. User has to attach a file to a specific user message, and it may just disappear from visibility.
2. Having to rewind to the message where the file was attached to delete it.

Expected behavior:
1. the bot receives something like this as input:
```
User: ...
Bot: ...
<DATABANK CONTENT BEGIN>
(Some article text, full text)
(it is assumed that the article fits completely into the context window of the model)
<DATABANK CONTENT END>
User: ...
Bot: ...
User: ...
```
2. The user can delete and add files at any time and be sure the system sees them. 

Is it clearer now? Or do you think it is useless?

**Comment by Cohee1207** [comment]
Use QR with script commands to post data bank files to chat. Here's a working script.
```
/databank-list field=name |
/buttons labels={{pipe}} Pick a file |
/databank-get |
/send <DATA BANK FILE>
{{pipe}}
</DATA BANK FILE>
```

**Comment by antonovmaxim** [comment]
Thank you. I admit: maybe then I did not quite understand correctly what databank is for. Thank you for your help!
