### ISSUE TITLE
[BUG] <title>No matter what I do still can't connect to TextgenwebUI API

### ISSUE THREAD

**Issue by SubaruDesu** [SillyTavern/SillyTavern#2680]
### Environment

🪟 Windows

### System

Win 11

### Version

1.12.4

### Desktop Information

Node v21.5.0

### Describe the problem

When I try to connect TextgenwebUI's API to ST, it always fails, I don't know what's the reason, I'm little... I've spent three days attempting to figure out why and have tried many methods, I've done my best, please help me (
<img width="308" alt="微信图片_20240818195508" src="https://github.com/user-attachments/assets/a1f8297a-34d7-4ddf-a38b-2d09535887db">
<img width="1280" alt="微信图片_20240818195512" src="https://github.com/user-attachments/assets/bfbc157d-df54-47f9-a370-911698608f40">
<img width="439" alt="微信图片_20240818195516" src="https://github.com/user-attachments/assets/3cc619ed-1ee1-454e-a3ac-b4fd6605eceb">
<img width="1280" alt="微信图片_20240818195520" src="https://github.com/user-attachments/assets/1fff6cac-e5ed-4ce1-80c6-1bfcbade15ad">
<img width="876" alt="微信图片_20240818195524" src="https://github.com/user-attachments/assets/7254857e-5676-422f-bc6b-997021c304c7">

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Uncheck "legacy API" toggle.

**Comment by SubaruDesu** [comment]
> ncheck "legacy API" toggle.

I'm so....I didn't even...thank you man!you're the best!

**Comment by SubaruDesu** [comment]
dude really helping me out!
