### ISSUE TITLE
[FEATURE_REQUEST] Automatically add asterisk (*) or quotation mark (") at the end of the Message when Trim Incomplete Sentences is enabled.

### ISSUE THREAD

**Issue by StellarBeing25** [SillyTavern/SillyTavern#2689]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Sometimes, when a part of the message does not get closure due to the context limit, it gets removed by Trim Incomplete Sentences, due to which the asterisk (*) or quotation mark (") present at the start of the message is not added at the end, breaking the chat formatting.

### Describe the solution you'd like

To improve this behavior, I propose automatically adding an asterisk (*) or quotation mark (") at the end of the message based on the punctuation present at the beginning of the message when Trim Incomplete Sentences is enabled to preserve chat formatting.

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

None

**Comment by Wolfsblvt** [comment]
Have you tried the "Auto-fix Markdown" toggle in the User Settings?
that should do exactly what you want.

![image](https://github.com/user-attachments/assets/40047150-80f6-4b95-8036-4d0e464a0b89)

**Comment by StellarBeing25** [comment]
Auto-Fix Markdown solved the problem, Thanks.
