### ISSUE TITLE
[Request] Chat cloning functionality 

### ISSUE THREAD

**Issue by Barbariskaa** [SillyTavern/SillyTavern#27]
**Is your feature request related to a problem? Please describe.**
Sometimes there are interesting moments in the chats that I would like to play out in different ways, i.e bot responds interestingly in the message history or I get a good swipe and I want to save it for the reuse. For this I copy the chat file and then use a copy. But this is tedious, because you have to go into the tavern folder, click publc, chats, {{char}} folder, search for the latest file, then copy it and rename the copy.

**Describe the solution you'd like**
Chat cloning functionality in the options menu.

**Describe alternatives you've considered**
Manually copying chat files.

**Comment by RossAscends** [comment]
You have described the bookmark feature. it is in the options menu on lower left side of the screen, next to the chat input box. It's copies the current chat at its current state.
