### ISSUE TITLE
[BUG] Custom UI Theme Not Initially Loading Chat Width, Font Scale, Avatar Type, etc. Upon Startup

### ISSUE THREAD

**Issue by HvskyAI** [SillyTavern/SillyTavern#2703]
### Environment

🪟 Windows

### System

Firefox/Librewolf 129.0.1

### Version

1.12.4

### Desktop Information

- Node Version v18.16.0
- Release Branch
- Text Generation Web UI Backend

### Describe the problem

A relatively minor issue, but I thought I would simply chime in about it. 

When initially starting up SillyTavern, the Custom UI theme is loaded, but does not apply Chat Width, Font Scale, or Avatar Type as located in `SillyTavern\data\default-user\themes\theme.JSON`

Selecting and loading a different UI theme and then reverting to the initially loaded theme applies the settings as specified in the `theme.JSON` file. 

Many thanks to the hardworking devs. 

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Should be fixed by #2706
