### ISSUE TITLE
[BUG] SillyTavern Cannot listen on port 80

### ISSUE THREAD

**Issue by GhostNaix** [SillyTavern/SillyTavern#2709]
### Environment

🐧 Linux

### System

Gentoo 2.15 x86_64

### Version

1.12.5

### Desktop Information

Node.js Version: v22.4.1

### Describe the problem

In config.yaml for some strange reason I cannot change the port option to 80 listen on port 80 for this update, previous updates I could listen on port 80 completely fine. I'm completely sure that there is nothing running on port 80.

### Additional info

The issue renders the following error
```
non-fatal error: failed to start server on IPv4
RangeError [ERR_SOCKET_BAD_PORT]: options.port should be >= 0 and < 65536. Received type string ('').
    at Server.listen (node:net:2055:5)
    at /opt/SillyTavernAI/server.js:835:16
    at new Promise (<anonymous>)
    at createHttpServer (/opt/SillyTavernAI/server.js:831:12)
    at startHTTPorHTTPS (/opt/SillyTavernAI/server.js:858:19)
    at startServer (/opt/SillyTavernAI/server.js:871:40)
    at <anonymous> {
  code: 'ERR_SOCKET_BAD_PORT'
}
fatal error: Failed to start server on IPv4 and IPv6 disabled
```
config attached below (I know cookie secret is in there, this is just a test config)
[config.yaml.txt](https://github.com/user-attachments/files/16741673/config.yaml.txt) 

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Fixed in both branches.
