### ISSUE TITLE
[FEATURE_REQUEST] Separate selection for system prompt

### ISSUE THREAD

**Issue by GodEmperor785** [SillyTavern/SillyTavern#2713]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Different character cards sometimes require different types of system prompt: typical RP characters need prompt to act as the character in a roleplay and describe actions, feelings and dialogue, some cards need additional uncensoring to work properly, assistant type cards often need another system prompt to not mention narrating character actions or feelings.

It would be good to separate selection for system prompt so any system prompt can be paired with any instruct preset (without duplicating the prompts for each format), instead of having system prompt inside instruct preset.

### Describe the solution you'd like

Right now there is instruct mode menu where both format and system prompt are present in one preset. I think it would be better to add another menu for selecting the system prompt, perhaps just a selection drop-down list, save/update/delete buttons (like in context and instruct mode) and a text field for the prompt.
The main idea is to separate system prompt from instruct preset.

### Describe alternatives you've considered

- Right now I maintain a version of each major instruct format (ChatML, Mistral, Alpaca, Vicuna, Llama 3, Command R, Gemma 2, etc) with the system prompts I use (I have at least 2 prompts for each - RP and assistant-type). This is problematic because in case of updates I need to update all of them and if I want to have more prompts the list of presets would grow fast.
- Or one would have to include system prompt in every character card, but that is even more problematic when many cards need same/similar RP prompt and there is over a hundred of them. (I know there is a feature of prompt override in advanced definition, but this is for each character separately and is tedious to do when you have over 100 character cards)
- Other alternative is to have a text file with system prompts and copy and paste them to the UI every time, but I think it will be much better to have everything in the UI.

### Additional context

There is a similar feature request from 05.2024 but there is no response in it: #2303 
So I thought I will just ask in a new issue if that is ok.

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Wolfsblvt** [comment]
I can provide you with some more alternatives:

- Use a World Info book for your system prompt. Bind them to specific characters or tags via the "Character Filter". If you want to have a default system prompt if none other applies, you can use the Inclusion groups and just mark all WI entries that apply to specific characters is Priority, so they will get taken first.
  You can then either use the system prompt as the "wiBefore", for example.
  The advantage is you can combine this to tags. What seems to go along with what you have written, that you have a specific prompt you want to use for all assistant-type characters.
- Use local variables and scripting to define your system prompt. You can build a Quick Reply that auto-runs on chat creation, and just sets the variable for that chat to whatever prompt you need, read from wherever you want it.
  Inside your system prompt in the preset just use `{{getvar::mySystemPrompt}}` to read that variable, or something like that.

What do you think about those?

**Comment by GodEmperor785** [comment]
Option 1 you provided makes sense, I tried experimenting with it:
I made a World Info book with entries containing prompts with following settings:
- Strategy = constant, so it always triggers
- Inclusion Group with common name, so I can have a default entry if not others match
- tags which should trigger the entry in "Filter to Characters or Tags"
- Order set to low number, so it always triggers first like a system prompt

I also needed to add this World Info to "Active World(s) for all chats" or else I would have to add it to all of my cards.
I have a question about this approach:
For this to work best I would need to add some tags specifying what type of prompt a card needs (I already had a tag for assistant-type cards so that already works). Is there a way to add tags to many characters at once without clicking through every character card?

Option 2 seems a bit complicated and I would have to learn more about scripting system in ST, approach with world info seems easier.

Thanks for the suggestions!

**Comment by Wolfsblvt** [comment]
> Is there a way to add tags to many characters at once without clicking through every character card?

Yes. There is a small "Bulk Edit" button in the character list. If you hover over it, it also explains how you can quickly select more than one character. Then right click, and edit the tags.

The rest that you explained about it sounds good, as far as I see.

> Option 2 seems a bit complicated and I would have to learn more about scripting system in ST, approach with world info seems easier.

Yep, WI is generally easier. STscript might seem daunting at first, but the basics aren't *that* hard to figure out.
Though world info sounds a lot cleaner for this option too, so I'd say go by that.

**Comment by GodEmperor785** [comment]
I see the "Bulk edit" button now, it does exactly what I needed, thanks.
Since the approach with World Info seems to work well and avoids the duplication of prompts which was my main problem - I will close this issue.

**Comment by Wolfsblvt** [comment]
Nice. Glad I could help.

That's the best part of ST. There are so many tools. For a lot of requests there already exists an alternative or workaround that isn't obvious right from the start.

**Comment by Cohee1207** [comment]
We're actually doing it now. #2868

**Comment by GodEmperor785** [comment]
In the World Info approach I really like that prompts can switch automatically based on character card tags.
Would it be possible to add something similar in this new system prompt system?
What I mean is to add a way to automatically switch system prompt based on a specified tag on character tag (equivalent of "Filter to Characters or Tags" in World Info)

**Comment by Cohee1207** [comment]
No, this is not covered there. For anything complex you're still advised to use WI, otherwise this would lead to duplication of the same feature in multiple places. The proposed sysprompt decoupling is a simple QoL change to prevent duplication of templates.
I guess if would want to make it possible in the system prompt box, this should wait until the macro rework. @Wolfsblvt 
Something like this (the syntax is entirely fictional).
```
{{if {{char}} eq "Name"}}
Foo
{{else}}
Bar
{{end}}
```

**Comment by GodEmperor785** [comment]
Ok, I get it. Thanks for quick response

**Comment by Wolfsblvt** [comment]
Yup, macros 2.0 will make this easier. But even then, I think adding character or scene-specific stuff to your main system prompt might be tackling it from the wrong way.

WI is added right after your system prompt, if you want. Why can't you add those specific instructions to WI entries, constant, as "WI After", and then bind them to specific characters or tags? Much easier to manage, and fits better structurally.

If you really need more control about the specific placement, consider using WI entries that simply do a `{{setvar::myPrompt::Whatever your text etc}}` and placing a `{{getvar::myPrompt}}` into the exact place of your system prompt.
Same thing again, WI gives you a lot of control when to trigger, why, how often.
Use inclusion groups and prio to only trigger one of your relevant prompts.

Edit: Wait. I have written the exact same thing above already 🤦
But that's still the valid response for your new remark.

**Comment by GodEmperor785** [comment]
Yes, I will most likely continue using the World Info approach for the prompts when I will need automatic switching based on character tag. Currently it works very well.
But just separating system prompt from instruct as mentioned will be a good change.
