### ISSUE TITLE
[BUG] cannot see avatar images

### ISSUE THREAD

**Issue by etgv2** [SillyTavern/SillyTavern#2716]
### Environment

🪟 Windows

### System

windows 10

### Version

1.12.5 'staging' (00ff2875)

### Describe the problem

I can't see the avatar pictures next to the messages.

### Additional info

It might only be me because no one else is reporting it. I've tried restarting silly tavern and updating it, but it didn't work. 
![3d333a950f70bbbbf68e8fe4904d1d7f](https://github.com/user-attachments/assets/907c76d4-27c7-4424-87b2-965911cfdd00)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by etgv2** [comment]
[Edit] Switched to release branch and now i can see them again, might be an extension or something?

**Comment by Cohee1207** [comment]
Enable avatars via User Settings => Hide Chat Avatars
