### ISSUE TITLE
[BUG] when context length fills up replies become a mess

### ISSUE THREAD

**Issue by SimplyCorbett** [SillyTavern/SillyTavern#2717]
### Environment

🐧 Linux

### System

Linux/NVIDIA & macos

### Version

1.12.5

### Desktop Information

Koboldcpp & llamacpp

### Describe the problem

When the context length comes close to full on long contexts the model stops replying coherently. It starts to make replies to things that happened several replies ago. It breaks down and just keeps repeating things.

this only happens when the context is near full. I have tried using —noshift on the backends. Same issue.

have tested on the latest koboldcpp and llamacpp.

can replicate on both Linux and macOS. I can replicate it on different models, different context lengths.

In both cases I am using flash attention. On the Linux/NVIDIA server I use k,v quant of 4.

I don’t know how to debug this. It happens on different presets.

I primarily use chat completion.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Not a frontend issue.

I've heard that quantizing KV cache leads to significant decrease in quality. If you have enough VRAM - do not quantize the cache, and don't overextend the context size beyond model limits.

**Comment by SimplyCorbett** [comment]
Yeah but I can replicate this on my Mac which does not use quantified k,v cache.

I’ve tried with lower context limits as well, same issue.

okay, will follow up with the backend devs, thanks!
