### ISSUE TITLE
[FEATURE_REQUEST] Silent output window

### ISSUE THREAD

**Issue by Vibecoder9000** [SillyTavern/SillyTavern#2720]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

No problem, maybe being messy.

### Describe the solution you'd like

It'd be perfect if the cmd window that shows debug info, chat messages, etc is just blank. 

### Describe alternatives you've considered

No window would be even better, just a right-side taskbar icon to show it running. 

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Wolfsblvt** [comment]
I think this might be a request that isn't really related to ST itself, but how you use and run it.
ST is nothing but a node server that you start via script.
You can open and check what the actual `Start.bat` does, and it's just installing/updating NPM references, and then running `server.js` via node.

You can check if node supports suppressing output from the script, or just call the bat file or node command in a different way.

I'm gonna be lazy and just copy a response from GPT.

> Hey! Yeah, it’s possible to run a `.bat` file in a minimized way without showing up in the taskbar, but it requires a bit of a workaround since Windows doesn’t natively support minimizing to the system tray for `.bat` files.
> 
> Here’s a quick rundown of how you can do it:
> 
> 1. **Use a third-party tool**: You can use a tool like [RBTray](https://rbtray.github.io/) or [TrayIt!](http://www.teamcti.com/trayit/trayit.htm). These tools allow you to minimize any window to the system tray, including command prompt windows running `.bat` files.
> 
> 2. **Convert the `.bat` file to a `.vbs` script**: You can write a simple Visual Basic Script that launches your `.bat` file minimized and doesn’t show up in the taskbar. Here’s how you can do that:
> 
>    ```vbs
>    Set WshShell = CreateObject("WScript.Shell")
>    WshShell.Run "cmd.exe /c your-batch-file.bat", 0, False
>    ```
> 
>    - Save this as a `.vbs` file and run it. The `0` in the `Run` command ensures the window is hidden, and it won’t appear in the taskbar.
> 
> 3. **Create a shortcut to run minimized**: You can create a shortcut for your `.bat` file and set the shortcut properties to "Run: Minimized." However, this will still show in the taskbar, so you’ll likely want to combine this with one of the other methods if you need to keep it out of the taskbar entirely.
> 
> 4. **Task Scheduler**: Another option is to run the `.bat` file using Windows Task Scheduler, which allows you to run tasks in the background without any visible window, including the taskbar.
> 
> So, yeah, it’s doable, but how easy it is depends on how comfortable you are with these tools and scripts. What do you think?

**Comment by Vibecoder9000** [comment]
Fantastic, thanks!

**Comment by Vibecoder9000** [comment]
How to run Sillytavern without console open:

1. Use notepad, paste in:

> Set WshShell = CreateObject("WScript.Shell")
> WshShell.Run "UpdateAndStart.bat", 0, False

2. Save as – RunUpdateAndStart.vbs

3. Add "RunUpdateAndStart.vbs" to .gitignore on new line

4. Create a shortcut from your new .vbs file, and put it wherever you open ST from. In my case, Desktop.

If you want to close it, open task manager and end node.js. Linux - You already know.
