### ISSUE TITLE
[BUG] No way to remove the "[Start a new Chat]" system message

### ISSUE THREAD

**Issue by ammar1y** [SillyTavern/SillyTavern#2724]
### Environment

🍎 Mac

### System

macOS, Chrome

### Version

1.12.5

### Describe the problem

I'm inspecting the messages sent to the model (OpenAI model in this case.)

I enabled "Squash system messages" in the settings but there is still a system message that comes from Chat History.

The message looks like this:

```
{
    "role": "system",
    "content": "[Start a new Chat]"
}
```

And here it is in Chat History:

![Screenshot 2024-08-28 at 12 56 41 AM](https://github.com/user-attachments/assets/77ad5792-e3bf-4239-bc25-6f7b9df6c6b5)

I couldn't find a way to remove it from the context. Please help.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by imesha10** [comment]
I think there is an option to change or remove it in the chat completion preset settings

![image](https://github.com/user-attachments/assets/83e45ab6-a0aa-4752-8e96-49f9feb636d5)


![image](https://github.com/user-attachments/assets/92169db4-f6a7-430d-877e-a53c306403fa)


^change this to:

![image](https://github.com/user-attachments/assets/6ec3ea12-c6d5-4778-907a-52bb8392316e)

**Comment by ammar1y** [comment]
That worked! Thank you!

**Comment by Cohee1207** [comment]
It's under Utility Prompts in the leftmost menu. If you don't see it, enable Advanced UI mode.
