### ISSUE TITLE
[BUG] Remove Claude System Prompt Character Limit in UI

### ISSUE THREAD

**Issue by imesha10** [SillyTavern/SillyTavern#2725]
### Environment

🪟 Windows

### System

Windows 11

### Version

Latest Staging: da96bf3

### Describe the problem

The UI element for the **System Prompt** for **Claude** does not exceed roughly 10000 characters. (It's not exact from my testing but always falls short just right before that point).

I also looked at the Anthropic docs and I didn't see anything regarding a character limit for the system message.

Here is an example where I generated a really long lorem ipsum and pasted it in as an example.

![image](https://github.com/user-attachments/assets/07c18773-ff3e-4b58-8b7d-4e2c3affdb9f)

![image](https://github.com/user-attachments/assets/fc74c402-9ace-40fb-a924-d9ecef34efd7)

The reason this came up as a problem was that I was experimenting by pasting the one of my normal prompts into the system prompt.

After a little bit more digging I found that there is character limit on the textbox from dev tools on chrome:
![image](https://github.com/user-attachments/assets/96081506-b38b-45b5-9167-6666c859d2e0)
max length

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
As discussed in the PR, that field does not have any direct relation to Claude system prompts. It was a misunderstanding on the reporter's side.
