### ISSUE TITLE
mlc-llm Support

### ISSUE THREAD

**Issue by theFisher86** [SillyTavern/SillyTavern#273]
[MLC-LLM](https://github.com/mlc-ai/mlc-llm) is an extremely impressive development allowing users to run LLMs on almost any hardware. It's working on cell phones, raspberry pi's and includes Vulkan support. They have even gone as far as to develop a way you can actually run a GPU enabled LLM model from your browser using their WebLLM. 

Given the wide hardware support it is likely MLC-LLM is going to become very popular as it grows and word spreads. Thus it would be really really cool if SillyTavern could connect to it.

I don't have the skills to build the connector but I know enough to know that this could be very helpful:
[https://github.com/mlc-ai/mlc-llm/blob/main/tests/chat.py](https://github.com/mlc-ai/mlc-llm/blob/main/tests/chat.py)

**Comment by ghost** [comment]
Hi! I just wanted to add that I would support adding MLC-LLM to SillyTavern

**Comment by Cohee1207** [comment]
From the repo readme:

> The Python API of mlc_llm.MLCEngine fully aligns with OpenAI API

You can use it as a Custom Chat Completion endpoint then. No need for a dedicated API type.
