### ISSUE TITLE
[BUG] RegEx Extension only replaces the first occurence.

### ISSUE THREAD

**Issue by Nrgte** [SillyTavern/SillyTavern#2732]
### Environment

🪟 Windows

### System

Firefox

### Version

1.12.5

### Describe the problem

RegEx extension only replaces the first instance of a match. It would be better if this was configurable, but otherwise it should replace all matches.

The error is on line 115 of:

public\scripts\extensions\regex\engine.js

Thanks!

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
That is not the extension at fault, that's the default regex behavior. Use flags to set the regex to be global. 
`/foo/g`

**Comment by Nrgte** [comment]
Ahh I see, I wasn't aware that it accepts / / as well. Thanks.
