### ISSUE TITLE
[FEATURE_REQUEST] Shared files in databank or assign a tag to databank

### ISSUE THREAD

**Issue by endertargaryen** [SillyTavern/SillyTavern#2734]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

I have 8 characters who constantly need the databank updated, but instead of pointing to a file, it creates a copy of the file, requiring someone to update all 8 entries each time it is updated.

### Describe the solution you'd like

Assigning a tag to databank entries would be great, or using a pointer with a file instead of copying it.

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Maybe

**Comment by Wolfsblvt** [comment]
What is the actual use-case you have with this? Can you describe it a bit more?
You are using files for those, and you want to drag&drop replace the existing databank files?

**Comment by endertargaryen** [comment]
> What is the actual use-case you have with this? Can you describe it a bit more? You are using files for those, and you want to drag&drop replace the existing databank files?

So not drag and drop. Currently I am updating the storyline as it is created and I want all the characters that are involved in said storyline to be aware of the updated story.  Right now, for RAG, I have to go into each one and delete the current file and re-upload the updated txt file for each of the 8 characters since it creates a copy of any file you upload instead of using the actual file that is uploaded. I guess this makes sense if not running a local LLM.

My suggestion to make this less cumbersome would be to have a DataBank that can be applied similar to the lore book in that the vectorized files are available to selected person or tag. Then it just has to be updated in one place.

I understand the DataBank system is implemented differently, so no worries if you don't see a lot of value in it. I appreciate you looking.

**Comment by Wolfsblvt** [comment]
Is there a reason why you don't store the story data in "World Info"? The entries there do support vector storage querying, and you can sort them a lot more cleanly into logical blocks, and assign them to characters. Either by having separate world info books, or by assigning entries to characters/tags.

You might just be using a tool that makes this more difficult than it could be.

**Comment by endertargaryen** [comment]
If world info supports vector storage then yeah, that would solve my issue. I don't see SillyTavern telling me "ingesting ..." when I change world info though.  Is there a setting somewhere that says to vectorize it?

**Comment by Wolfsblvt** [comment]
It's inside the "status" dropdown. Where you can set entries to Normal or Constant, you can also set them to Vectorized.
![image](https://github.com/user-attachments/assets/301d28f8-ab7c-4d9a-b393-184f5a11b3a0)

End then, I am pretty sure you have to enable it for vector storage.
![image](https://github.com/user-attachments/assets/90f057b7-4ccf-49cb-b48e-b8fb74bff068)

**Comment by endertargaryen** [comment]
Awesome!  Thank you.
