### ISSUE TITLE
[BUG] When sorting by tag, page doesn't autoscroll to the top.

### ISSUE THREAD

**Issue by Vibecoder9000** [SillyTavern/SillyTavern#2743]
### Environment

🪟 Windows

### System

N/a

### Version

1.12.5

### Desktop Information

Tabbyapi backend

### Describe the problem

In character management, if you click Show Tag List, the tags pop up. Upon selecting a tag that results in less that the width of the character page (4 in my case), and also the list is scrolled past the first row, then the tag, even through valid, will hide the characters under the top of the page. The fix: Scroll to the top when sorting by tag.

![image](https://github.com/user-attachments/assets/99141f3a-7060-4936-ac37-d33be0ed2fc5)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Wolfsblvt** [comment]
Confirmed, and fix pending review.

Issue was specifically with grid view, not the normal char list.

**Comment by Wolfsblvt** [comment]
Done on staging.
