### ISSUE TITLE
[BUG] Summarize (built-in) frequency options are ignored: summarization is never triggered

### ISSUE THREAD

**Issue by issues-opener** [SillyTavern/SillyTavern#2746]
### Environment

🪟 Windows

### System

Firefox latest

### Version

1.12.5

### Desktop Information

Using KoboldCpp

### Describe the problem

Bug in "Summarization" (built-in): the "frequency" options "Update every X messages" and "Update every X words" have no effect at all. The user is forced to manually use the button "Summarize Now".

### Additional info

Issue also mentioned here:
https://github.com/SillyTavern/SillyTavern/issues/1442#issuecomment-2107851384

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Try the attempted fix here: #2748

**Comment by issues-opener** [comment]
> Try the attempted fix here: #2748

Perfect, thank you.

**Comment by Cohee1207** [comment]
Merged to staging. Reopen if the fix did not help.
