### ISSUE TITLE
[BUG] Deleting "swipe" 1/2 goes to 2/1 and generates a new reply

### ISSUE THREAD

**Issue by cloak1505** [SillyTavern/SillyTavern#2749]
### Environment

🪟 Windows

### System

Firefox 129

### Version

SillyTavern 1.12.5 'staging' (293676fe)

### Describe the problem

When you delete a "swipe" at 1/2, it effectively "presses the right arrow" right after deletion. I expect it to stay at 1/1 and not generate a new message.

This is disruptive behavior when deleting exactly 1/2. Less disruptive when deleting 1/3+ but the way it goes to 2/n is inconsistent with how deleting any other swipe behaves.

```
SWIPE DELETION BEHAVIOR

CURRENT         BUG FIX
1/2 -> 2/1      1/2 -> 1/1
1/9 -> 2/8      1/9 -> 1/8
6/9 -> 5/8      6/9 -> 5/8
9/9 -> 8/8      9/9 -> 8/8
```

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Wolfsblvt** [comment]
Are you talking about deleting the swipe via the delete button, or the `/delswipe` slash command?

**Comment by cloak1505** [comment]
I'm talking about pressing the edit button then the trash can button. Learned about `/delswipe` just now, it doesn't happen with this command.

**Comment by Cohee1207** [comment]
`/delswipe` actually reloads the chat when trash can doesn't. Could be potentially fixed by reloading.

**Comment by Wolfsblvt** [comment]
The original delete function is kinda bad. The slash command does this far better. Clicking the UI elements for swipes just to change the current swipe is not that good. Especially if you've deleted a swipe right that moment.

I'll refactor this, and make both use the exact same core functionality.

**Comment by Wolfsblvt** [comment]
Fixed on staging.

**Comment by cloak1505** [comment]
Works great. Not complaining, but at 200 messages it starts growing past 1 second to reload. Might be noticeable to ultra long chat users.
