### ISSUE TITLE
[FEATURE_REQUEST] Option for alternative behavior upon swipe deletion

### ISSUE THREAD

**Issue by cloak1505** [SillyTavern/SillyTavern#2750]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

This is an optional followup to Issue #2749.

Current behavior is to view the previous swipe when deleting a swipe except the first. This is slightly disruptive to users reviewing swipes from left to right instead of right to left, who would have to press the right arrow after every deletion to view the next swipe.

I am requesting an option for behavior that views the next swipe when deleting a swipe except the last. Visually, this entails staying on the same number x after deleting x/y.

### Describe the solution you'd like

```
SWIPE DELETION BEHAVIOR

ISSUE #2749     WHEN FIXED      ALT BEHAVIOR
1/2 -> 2/1      1/2 -> 1/1      1/2 -> 1/1
1/9 -> 2/8      1/9 -> 1/8      1/9 -> 1/8
6/9 -> 5/8      6/9 -> 5/8      6/9 -> 6/8
9/9 -> 8/8      9/9 -> 8/8      9/9 -> 8/8
```

May be a checkbox option under User Settings > Chat/Message Handling as:
`[] Previous after swipe deletion`
Default on. I tried to keep it shorter than the longest existing option.

May be a dropdown:
```
After deleting swipe 3/5:
[View 2/4 (previous)] (default)
[View 3/4 (next)    ]
```
This is clearer but would probably look too clunky.

Alternatively, single line dropdown:
```
Delete swipe 3/5 → [2/4] (default)
                   [3/4]
```

### Additional context

Hypothetically, depending on preferences, a user going right to left might not mind pressing the left arrow to manually view previous message, as a conscious "I will view the previous message". So really it can go either way.

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
I'm afraid this option will be utilized by about 2 and a half users.

**Comment by Wolfsblvt** [comment]
Agree with @Cohee1207 here.
We gonna fix the mentioned bug, and just decide whether we want to go to the same swipe id (meaning going to the swipe on the right), or go a swipe to the left.

Both make somewhat sense. Not sure how to decide. Worst case, for consistence, we keep it as is, and just move to the right. Unless it's the last swipe, then we go left.

**Comment by cloak1505** [comment]
> Agree with @Cohee1207 here. We gonna fix the mentioned bug, and just decide whether we want to go to the same swipe id (meaning going to the swipe on the right), or go a swipe to the left.
> 
> Both make somewhat sense. Not sure how to decide. Worst case, for consistence, we keep it as is, and just move to the right. Unless it's the last swipe, then we go left.

Just so you know, "as is" is go left after deleting 2+. The 1 -> 2 is the bug ("go right twice") while everything else goes -1. Not a big deal in either direction, so I'm fine with whatever.

Edit: I see the requested behavior is made default now. 👌
And it seems I misinterpreted the "it" from "keep it as is", where "it" probably refers to swipe id and I took it to mean "current behavior".
