### ISSUE TITLE
[BUG] Mobile Swipe Broken with Token Probibilities Modal Open

### ISSUE THREAD

**Issue by Vibecoder9000** [SillyTavern/SillyTavern#2753]
### Environment

🪟 Windows

### System

Andorid/firefox

### Version

1.12.5

### Desktop Information

Hosting via pc, st on local network. 

### Describe the problem

When Token Probabilities page is enabled and the box is on screen, swiping on mobile doesn't do anything. On PC, arrows and clicking both work, but on mobile only clicking the arrow works.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Not entirely broken, just the swipe gesture is disabled when any of the modals are open, even if they don't entirely cover the sheld viewport. @Wolfsblvt see if you can offer any resolution for that.

**Comment by Vibecoder9000** [comment]
Whoops, wrote the title wrong. Think I was thinking about how to phrase it, thought of breaking swipe, changed my mind midsentence to start with "token".

**Comment by Wolfsblvt** [comment]
Fix in the in the works. PR is open. Feel free to check it out, or wait for it to be merged into staging.

**Comment by Vibecoder9000** [comment]
> Fix in the in the works. PR is open. Feel free to check it out, or wait for it to be merged into staging.

Great, thank you.
