### ISSUE TITLE
[FEATURE_REQUEST] Add Cohere tokenizers

### ISSUE THREAD

**Issue by equal-l2** [SillyTavern/SillyTavern#2754]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

The current token count is always too much for Cohere models.

### Describe the solution you'd like

Use tokenizers from Cohere for their models.

### Additional context

Docs about their tokenizers: https://docs.cohere.com/v1/docs/tokens-and-tokenizers

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
It's not impossible to add a local tokenizer, but Cohere tokenizer file is more than 12 Megabytes in size which adds a footprint to installation size. Are you sure that the benefits outweigh the inconvenience?

Example of a tokenizer file: https://storage.googleapis.com/cohere-public/tokenizers/command-r-plus.json

Upd: replaced link to Cohere's official file
Upd 2: tokenizer.json minified is 8.5 Mb. Slightly better, but still would be the largest of all available tokenizers.

**Comment by equal-l2** [comment]
Thank you for the information!
This issue was a naive thought and I was not aware of the size.
I checked the currently bundled ones and the biggest is `llama3.json`, which is 5.8 MB in size.

Surely it is not very good to add another few megabytes to the bundle.

Is it possible to add a capability to override the tokenizer with their own tokenizer, even with chat completion?
Once it is possible, I'm fine with that and will close this issue.

**Comment by Wolfsblvt** [comment]
Wouldn't it be possible to distribute less used tokenizers via an optional extensions?

**Comment by Cohee1207** [comment]
Thought about it, but tokenizers plug into too much of the core code to support every API. Other option is to just stop caring about repo size.

**Comment by Wolfsblvt** [comment]
repo size, install size. Who cares, people are using 3GB installs (without models) for AI and don't mind, or something.

If you wanna make it clever, add the tokenizers into an external asset repo. Integrate them in the UI and all though. And when the user selects it for the first time, let it download the tokenizer from the asset.
Allows both adding in core, and also not blowing up the repo size by default.

**Comment by Cohee1207** [comment]
Added to staging as an optional download.

**Comment by Cohee1207** [comment]
https://github.com/SillyTavern/SillyTavern/releases/tag/1.12.6
