### ISSUE TITLE
[BUG] SillyTavern 1.12.5 mobile ui broken

### ISSUE THREAD

**Issue by gamerboi9999** [SillyTavern/SillyTavern#2756]
### Environment

🐧 Linux

### System

firefox nightly on android 12

### Version

1.12.5

### Desktop Information

nodeJs 20.17.0
NovelAI scroll
release branch

### Describe the problem

When i connect to ST from desktop and go to the typing area it works fine but when i connect through mobile and do the same this happens
![WhatsApp Image 2024-09-02 at 10 10 48](https://github.com/user-attachments/assets/20ee4d4f-2561-4c7b-8886-3612fcaeaf7f)

when i pull down the keyboard the screen goes gray

![WhatsApp Image 2024-09-02 at 10 13 20](https://github.com/user-attachments/assets/c83a159b-dd58-45ca-bdda-1f2b2122fecb)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Wolfsblvt** [comment]
This might already be fixed on staging. Can you test that?

**Comment by gamerboi9999** [comment]
i just tested it and yes its indeed fixed.

**Comment by Wolfsblvt** [comment]
Okay. The issue was fixed in #2735, just for reference.
I can keep this open until next release, if anyone runs into the same issue and searches for it.

**Comment by hhllcc** [comment]
I'm having this same issue too.  However, I'm pretty much a beginner in this, so I'm not sure what 'staging' means.  Is it in the settings?

**Comment by Wolfsblvt** [comment]
It's a branch, for the development. All changes go there, until we release the next big release. [Docs](https://docs.sillytavern.app/#branches)

If you installed via Git or the Launcher, you can just use the command `git switch staging`. Do note that staging will come with some consequences, as documented.
Or you wait for the next release, which should be soon.

**Comment by Cohee1207** [comment]
Try in newest release.
https://github.com/SillyTavern/SillyTavern/releases/tag/1.12.6
