### ISSUE TITLE
[BUG] When an input field is activated on a mobile device, the interface becomes misaligned.

### ISSUE THREAD

**Issue by xyzdev-cell** [SillyTavern/SillyTavern#2760]
### Environment

🐧 Linux

### System

Edge mobile 127.0.2651.111

### Version

1.12.5

### Desktop Information

Android 13 , flyme 10

### Describe the problem

As shown in the video, when clicking on an input field, an extra blank widget appears between the input field and the keyboard.
The issue started appearing from version 1.12.2 (or higher) .
https://github.com/user-attachments/assets/88ddb59a-ec87-4808-8ceb-f94ac87961f4

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Likely a duplicate #2756

Switch to staging and try it there.

**Comment by xyzdev-cell** [comment]
it's fixed ，but If the chat area content can scroll along with the upward movement of the input box, that would be better.

**Comment by xyzdev-cell** [comment]
I'm still using the staging version. It was working fine in the beginning, but now the interface has the following issue:
The input field does not move up correctly when the input method is activated.
before
![0](https://github.com/user-attachments/assets/e0ead322-e563-4b4f-85c5-1d90d93e6a49)
after
![1](https://github.com/user-attachments/assets/94f856fc-43d6-4aad-b07e-7ee927b98173)

**Comment by xyzdev-cell** [comment]
1.12.6 release: still there

**Comment by Cohee1207** [comment]
This appears to be a bug in Edge on Android. It doesn't respect the "interactive-widget" tag that makes the viewport resize on opening keyboard. 

Solution: use a different browser. It should work fine in Chrome and Firefox.

Useful link: https://learn.microsoft.com/en-sg/answers/questions/2069280/does-edge-pay-attention-to-the-interactive-widget
