### ISSUE TITLE
[FEATURE_REQUEST] Hide the quick reply buttons?

### ISSUE THREAD

**Issue by Vladonai** [SillyTavern/SillyTavern#2761]
### Have you searched for similar requests?

Yes

### Describe the solution you'd like

Currently, if you enable the quick reply buttons on your PC, they show up at the top of the message entry window. Always. And the only way to hide them is to disable “quick replies”. I'd like to be able to hide or minimize these buttons - maybe if “quick replies” is enabled, add a small button on the side that will hide/show the quick reply buttons? Or a hotkey with such a function? Or a slider?

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
> Always

Untrue. You can disable buttons either on the whole set level, or individual QR level.

![image](https://github.com/user-attachments/assets/6bfa3c4d-165b-43e2-9c9e-91ea1af3babd)

![image](https://github.com/user-attachments/assets/ecbaf03b-40a1-4899-8827-5747c3801ea1)
