### ISSUE TITLE
[BUG] Sticky lorebook entries in groups not sticking if their content contains macros.

### ISSUE THREAD

**Issue by Susanoo1337** [SillyTavern/SillyTavern#2762]
### Environment

🪟 Windows

### System

Windows 10, Firefox 115

### Version

1.12.5

### Desktop Information

Branch: Staging

### Describe the problem

As I was writing the bug report I did further testing, trying to find a workaround for the issue, but instead found the likely root cause of the bug:

I'll explain methodically:

1. A lorebook contains multiple entries with sticky set to >0. (e.g. see below)
2. ONE of the entries is activated, the rest are not (i.e. if they're part of a group) (e.g. Entry A)
3. Entry A remains active until it's sticky value reaches 0.
4. The group is freed up.
5. Activation can trigger e.g. Entry B.
6. Entry B starts with a sticky value = 0.
7. The group is freed up.
8. etc.

- It doesn't matter if the entries are in an inclusion group or not.
- The second entry can be triggered on the turn the first entries sticky value became 0, or after, every following entry will have it's sticky value set to 0.
- If an Entry B with sticky = 10 is triggered WHILE the active Entry A has a remaining sticky value >0, Entry B will retain it's sticky value and remain sticky for 10 turns.
- As long as the last active sticky entry doesn't reach a sticky value of 0, new sticky entries will have their defined sticky values upon activation.

I confirmed this by detaching stickiness from a inclusion group by adding a grouped trigger layer.
Constant activation entry(with cooldown) -> Trigger layer (grouped and with weights) -> Sticky entries (ungrouped)

(Original observations:

Given four entries in the lorebook:
1. Activation - Strategy: Constant; Position: BeforeChar; Content: A unique activation string. (i.e. 1338)
2. Entry A - Primary keyword:1338;  Strategy: Normal; Position: BeforeChar; Inclusion group: X; Group weight: 40; Sticky: 10
3. Entry B - Primary keyword:1338;  Strategy: Normal; Position: BeforeChar; Inclusion group: X; Group weight: 35; Sticky: 10
4. Entry C - Primary keyword:1338;  Strategy: Normal; Position: BeforeChar; Inclusion group: X; Group weight: 25; Sticky: 10

Expected behavior: Activation is constant, so it always triggers Group X. One entry will be chosen according to weight and remain sticky for 10 turns. After 10 turns another entry will be chosen randomly according to weights and remain sticky for another 10 turns.

Observed behavior: A random entry is chosen for the first turn, it remains sticky for 10 turns. After which a random entry is chosen for every turn thereafter, not regaining it's stickiness upon a second activation.

Second, possibly related scenario:
1. Entry A -  Strategy: Constant; Position: BeforeChar; Inclusion group: X; Group weight: 40; Sticky: 10
2. Entry B -  Strategy: Constant; Position: BeforeChar; Inclusion group: X; Group weight: 35; Sticky: 10
3. Entry C -  Strategy: Constant; Position: BeforeChar; Inclusion group: X; Group weight: 25; Sticky: 10

Stickiness is completely ignored, a random entry is drawn every turn. )

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Wolfsblvt** [comment]
@Cohee1207 I think we might have an actual issue here. I checked the code, and stickiness is not taken in account when checking for inclusion groups.
Inclusion groups are decided and rolled before the probability rolling, and with it the stickiness and constant is applied.
So if you had an entry win in a group, which made it sticky, the next message could possibly reroll the group, let another entry win and then have an issue with timed effects.

I am not sure if this is 100% the bug described here, but it for sure is a bug.

**Comment by Cohee1207** [comment]
You can try the proposed fix here: #2765

**Comment by Susanoo1337** [comment]
From my (limited) testing #2765 seems to fix the issue. Thanks!

**Comment by Susanoo1337** [comment]
I spoke too soon, after a lot more testing I still seem to run into edge cases where sticky value is completely ignored.
I.e. if three entries in one group are set to constant and sticky, one is chosen according to weights at the beginning of a chat but doesn't stick for the set amount of responses. (e.g. Sticky = 20 but a new entry becomes active after 4 responses.)
Can you help me out how to set the ST console to be verbose? I tried the `/wi-get-timed-effect` command but can't get an output. (unless it doesn't print to console, then I don't know where) It would help me provide you with more accurate data perhaps?

**Comment by Wolfsblvt** [comment]
> Can you help me out how to set the ST console to be verbose?

Dev Tools Console to Verbose (in Chrome):
![image](https://github.com/user-attachments/assets/cb19eacc-a013-457d-9017-31dfac9efd8c)

WI has a very thorough logging since a few months, which *should* give you most clues what happened internally and even why.

> I tried the `/wi-get-timed-effect` command but can't get an output. (unless it doesn't print to console, then I don't know where)

You are correct with your latter assumption. Most STscript commands don't really print out a value or toast it. They retrieve it, so you can do whatever you want with it in script. You can just make an echo, if you wanna see the value.
Would be like this:
```
/wi-get-timed-effect file="Test World" effect=sticky 1 | /echo
```

**Comment by Wolfsblvt** [comment]
Please let us know if you can come up with any further repro steps or more information based on the debugging.

Right now, I don't have a clue where to start with this - besides the fixes we already did.

**Comment by Susanoo1337** [comment]
Right, still bugging out. (Pulled staging branch after you merged the commits from timed effects.)
Lore with 3 groups, 3 entries each group. All isolated from one another so I don't think that matters, Group A is the important one and the only one that uses sticky. Group B and C just help the LLM and are conditional upon Group A context. (might try it with only one group if I can't make this clear)

I'll include some debug output, so I'll explain a little bit for clarity: The Character lore is for a character with a dissociative personality, each of the entries contains around 1000 tokens of character description and some STScript to change the character name in the rest of the card.

The first two stickies worked, Entry 2 triggered, stuck around for 14, (confirmed using /wi-get-time-effect), then Entry 1 triggered, stuck around for 15, as expected, then Entry 2 triggered again, then on the next turn Entry 1 triggered as well, overriding Entry 2. now /wi-get-timed-effect for entry 1 and 2 gives me an output of 14 and 11 respectively, meaning two entries from group "personality" are sticky at the same time.


```
[WI] --- START WI SCAN (on 34 messages) ---
[WI] Context size: 15884; WI budget: 7942 (max% = 50%, cap = 0)
[WI] Character Yuusha's lore has 9 world info entries 
Array [ "Yuusha Test 3" ]
[WI] Found 9 world lore entries. Sorted by strategy 
Array [ "character_first", 1 ]
[WI] Processing sticky entry Yuusha Test 3.2 
Object { hash: 3537355703040921, start: 32, end: 46, protected: false }
[WI] --- SEARCHING ENTRIES (on 9 entries) ---

(SNIP)

[WI] --- INCLUSION GROUP CHECKS ---
[WI] Skipping group scoring for group 'personality'
[WI] Checking inclusion group 'personality' with 3 entries 
Array(3) [ {…}, {…}, {…} ]
[WI] Entry 1 activated as roll winner from inclusion group 'personality' 
[WI] Entry 2 removed as loser from inclusion group 'personality' 
[WI] Entry 3 removed as loser from inclusion group 'personality' 
[WI] --- PROBABILITY CHECKS ---
WI entry 1 does not use probability

(SNIP)

[WI] --- BUILDING PROMPT ---
[WI] Adding sticky entry Yuusha Test 3.1: start=34, end=49, protected=false
```

The expected log should be, since we had "Processing sticky entry Yuusha Test 3.2", "[WI] Entry 1 removed as a non-sticky loser from inclusion group 'personality' " but that didn't happen for one reason or another, leading to two sticky effects being active at the same time (although not visible in logs as far as I can tell, but /wi-get-timed-effect outputs numbers for both entries.)

Just in case this has anything at all to do with it, the previous message was a swipe and resulted in: `[WI] Removing sticky entry Yuusha Test 3.1 from timedWorldInfo: chat not advanced 
Object { hash: 2222259102225862, start: 32, end: 47, protected: false }`
but I swiped to roll entry 3.2 instead which then was processed as sticky. (as seen above)

Hope this is clear enough.

**Comment by Wolfsblvt** [comment]
This should not happen. The inclusion group snipped is on the exact same message as the snip above, right?

You should have already received loggings like this:
```
[WI] Entry ${entry.uid}`, `removed as a non-sticky loser from inclusion group '${key}'
```

And then most important
```
[WI] Skipping inclusion group check, group '${key}' has sticky entries
```

I think what would really help here is if you can reproduce it on a specific message/swipe, export your chat an world info so we can reproduce it. I can go through it step by step with the debugger.
Right now, it's very hard to try to understand what is happening on your end.

Even posting the full log for the current message and the message before might help.

**Comment by Susanoo1337** [comment]
Apologies, I started writing that up and ran out of time so I had to cut it short, I snipped stuff in a hurry since the log displays the full lore entries which are 1000+ token each, and very NSFW. 
Here's a full log of this incident happening. With just the 'content:' fields snipped out.
[console-export-2024-9-9_7-0-41.txt](https://github.com/user-attachments/files/16925636/console-export-2024-9-9_7-0-41.txt)
I can send you the card+character lore, but probably not here. (due to nsfw) and it's not public on venus or anything, so you can just add me on discord: invictusart

**Comment by Susanoo1337** [comment]
Changed the title since it no longer accurately represented what was going on. I had trouble recreating the issue synthetically with an empty card and simple lorebook entries. I thought it might be some conflict with all the STScript I had in the WI and Character card, but removing all of it didn't solve the issue.
![image](https://github.com/user-attachments/assets/66da7c44-76c2-4fd8-b759-6c4ecf1f1c9c)

When one of the "double entries" expires it shows 'undefined'
![image](https://github.com/user-attachments/assets/ec95f043-7fce-4ff0-94c3-f2f48d77ff48)
As opposed to when the actually active entry expires:
![image](https://github.com/user-attachments/assets/29ed0bea-9c7e-49da-a586-aca5df9f2450)

But definitely confirmed the ability of two sticky entries from the same group being able to stick, with only one being added to the context(at least that much).
e.g.
Entry 1 is rolled, becomes sticky.
Entry 1 expires, Entry 2 rolls "it's set as sticky according to log."
Sticky is processed, but ignored, another entry is rolled.
If it's Entry 2 again, on the next message, another entry is rolled again. This will keep happening until an entry that's not Entry 2 is rolled. E.g. Entry 3.
Entry 3 is sticky.
Entry 2 and Entry 3 are processed as sticky with their individual duration, only 3 is added to context.

More observations: the first sticky entry picked can also be ignored, dunno if that's because ST was already running and bugging out and I just started a new chat, but I don't have the time right now to keep restarting the server for every new chat.

**Comment by Wolfsblvt** [comment]
Is this inside a group chat?
The log that the entry could not be found happens when you either delete a currently sticky entry, or when the book itself where it was inside is **not** active for the current generation.
If the book is not there, there is nothing that could be added, and the sticky is removed.

I am still not sure I can follow about the issue, and I can't really reproduce it.
If you have an empty scenario/book and a way to consistently reproduce it, that'd be great if you could chare that.

**Comment by Susanoo1337** [comment]
No of course it wasn't a group chat :> I'm stupid but not that stupid haha. I do try to limit rogue variables when hunting bugs.

**I could not for the life of me replicate it with an empty card until I figured it out:**
Having a variable in the content field of the WI entry breaks the sticky system.
[Lore Tester.json](https://github.com/user-attachments/files/16989611/Lore.Tester.json)

This would run perfectly for ever until I added `{{char}}` to the lore entries, it stopped respecting sticky immediately after I added that.

(I figured it out by slowly removing any syntax from the large WI entries of my Yuusha card. First all STScript like `{{getvar}}` , then brackets `[ ] < >` etc.. And finally `{{char}}` - it was the last suspect since I figured it couldn't possibly be a built-in system variable... but alas. Any variable will do the trick apparently, curly brackets on their own don't seem to break it - whether left open or closed.)

**Comment by Cohee1207** [comment]
Yeah, that may make sense - entries are hashed by the content, but after replacing the macros. I think we can pre-calculate the hash on the entry level before replacing macros to make it work with dynamic content.

**Comment by Cohee1207** [comment]
PR for the fix here: #2840

**Comment by Susanoo1337** [comment]
Updated title for future reference. The fix in your PR seems to work. I'll test a bit more and close once conclusive. Thanks. (Or you can close once you're satisfied and the PR has been approved.)

**Comment by Wolfsblvt** [comment]
Dear god. I haven't even given this any thought. Good catch. Happy we finally resolved it.

@Susanoo1337 thanks for the very thorough and repeated analysis with tracking this down.
