### ISSUE TITLE
[BUG] An error occured while counting tokens when using images on Google Gemini API.

### ISSUE THREAD

**Issue by Ph0rk0z** [SillyTavern/SillyTavern#2763]
### Environment

🐧 Linux

### System

Firefox or Chrome

### Version

Git Staging as of today.

### Desktop Information

Linux.

### Describe the problem

I've been using google aistudio recently. Whenever I send an image to the chat, it either fails to caption or captions correctly and then says "an error occurred when counting tokens" in every subsequent message. The only way to fix it is to delete the message with the image.

Is inline image insertion supported by 1.5 flash and pro in ST? It defaults to using the captioning extension anyways. I thought these models can even ingest documents over the API.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Ph0rk0z** [comment]
The error goes away when I turn off inline images.. but gemini supports inline images?

**Comment by Cohee1207** [comment]
I was not able to replicate on gemini-1.5-pro-exp-0827, with image inlining enabled. Can you provide more details about this issue? Is this only one specific image giving you an error or any image? Are you able to check the DevTools console for possible errors found there?

**Comment by Ph0rk0z** [comment]
It won't let me use exp-0827, says too many requests. Am using 1.5 001. Simply adding any image with inline enabled causes the problem.

Should I be disabling the captioning extension too? I think mine is enabled to do auto caption.

pics of it: https://imgur.com/a/error-suOisjl

**Comment by Cohee1207** [comment]
Sorry, still nothing on my end. Please, could you gather DevTools console logs associated with this error? I'm sure there should be at least something that indicates the error.

<img width="520" alt="image" src="https://github.com/user-attachments/assets/95192e5d-a172-4c01-9bc1-abd72ed53c2d">
<img width="520" alt="image" src="https://github.com/user-attachments/assets/4e5afe94-3fb6-41f9-bcea-a7e499b3cd3d">

**Comment by Ph0rk0z** [comment]
So funny thing... It's some kind of network error in both chromium and firefox.
![request1](https://github.com/user-attachments/assets/f0a8dd61-aae1-4481-80fe-90edac8ef71e)
[console-export-2024-9-7_17-10-4.txt](https://github.com/user-attachments/files/16920062/console-export-2024-9-7_17-10-4.txt)

**Comment by Cohee1207** [comment]
Aha, that's getting closer. Do you use some sort of middleman/proxy between your ST server and client?

**Comment by Ph0rk0z** [comment]
Nope, runs right on my laptop. Unless openvpn is doing something between the system and google.

**Comment by Cohee1207** [comment]
This is the only thing I can offer now, as I could not see anything obviously wrong in the log or screenshot: https://github.com/SillyTavern/SillyTavern/commit/6f9846a29041bf6f9c14b412982a277ea3cc0681

**Comment by Ph0rk0z** [comment]
It killed the error but the AI doesn't see the picture. Have to see what's causing the whole "request header too large" error. I figured it would be the browser but two of them are doing it.

**Comment by Cohee1207** [comment]
It loads the image from a server to calculate its dimensions. This should be a simple HTTP GET request like in many other places.

You can see in Firefox request log how many bytes do the request headers use, and possibly locate any out-of-the-ordinary ones. The Node limit is 16kb for headers.

**Comment by Ph0rk0z** [comment]
Yes.. the node limit that got put in. I edited it.

![server-code](https://github.com/user-attachments/assets/a441b186-7838-4f35-86c1-a7f724bb0e6f)

So after changing it, I get different results.


![header2](https://github.com/user-attachments/assets/4e6501e3-22cb-4a38-80bc-f42dc83407f6)

![header3](https://github.com/user-attachments/assets/7ed19722-3ca7-490d-839b-d53901a69b09)


I found that I can upload very small images (under 30kb) and it seems to not error.


![header4](https://github.com/user-attachments/assets/c2105c3c-aec0-4afe-a27f-39fc74c272ae)
![header5](https://github.com/user-attachments/assets/011face2-d0e3-4ed6-b636-6c4b4354e4a0)

But I also found another bug. If you attach a file without putting any text, it will reply as the character inside your message.
![header-bug](https://github.com/user-attachments/assets/63390ada-a9d6-4e5c-b2d8-5ee6f0f07bf7)

Seems to be hit or miss whether the AI sees the pics that error. On rerolls it did. Error happens between count model and generate.

**Comment by Cohee1207** [comment]
Try the fix here: #2805

**Comment by Ph0rk0z** [comment]
Images don't do any errors. If I don't write text when attaching a picture, it still writes into my message as the character though.
Also, worth it to remove the "dead" models? There were a couple that said they were deprecated like the one you mentioned.

**Comment by Cohee1207** [comment]
> Also, worth it to remove the "dead" models? There were a couple that said they were deprecated like the one you mentioned.

I was about to do that, but noticed that OpenRouter still somehow provides access to gemini-pro-vision. Either it re-routes to a fallback model (on Vertex?) or there is still a spark of life somewhere in pro-vision.

**Comment by Ph0rk0z** [comment]
Palm2 and ultra don't generate for me either. Are some of the names doubled too? I notice there's some variations of 001.

**Comment by Cohee1207** [comment]
The names in the list are unique, but Google model naming scheme only recently started to make sense.
Before that there were Gemini 1.0 Pro and Gemini Pro 1.0

**Comment by Cohee1207** [comment]
> But I also found another bug. If you attach a file without putting any text, it will reply as the character inside your message.

I noticed that only happens when you attach an image but not press the "Send" button / Enter (usual flow), but instead:

- 'continue' = happens exactly what you describe.
- 'regenerate' = the image is sent but the stream is started as a character message. I think that is 100% fine.
- 'swipe' = same as above. Debatable.
- 'impersonate' = but the response streams into the input. Could be fixed, but not critical.

Do you expect the image not to be attached in the first case?

**Comment by Cohee1207** [comment]
I just disallowed sending attachments for all these types. The weirdness should be gone now.

**Comment by Ph0rk0z** [comment]
All I did was use "attach file" and then press enter without typing a message. My assumption is that it would send the file without any other input on my part. It sounds like it marks it as a continue, incorrectly.

**Comment by Cohee1207** [comment]
I guess you have "Send" to Continue enabled then that triggered continue instead of sending the file as a user. Well, two bugs for one.

**Comment by Ph0rk0z** [comment]
Yup.. a couple of them. Thanks tho. It seems to all be working now so I think I can close this.
