### ISSUE TITLE
[FEATURE_REQUEST] API added

### ISSUE THREAD

**Issue by qw1642190428** [SillyTavern/SillyTavern#2764]
### Have you searched for similar requests?

No

### Is your feature request related to a problem? If so, please describe.

https://chat.notdiamond.ai/
Will this latest AI website be considered for inclusion in ST? It can be used for free with GPT Claude and other APIs.

### Describe the solution you'd like

Hope to add

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
I don't see any API docs, and not sure it fits for a backend provider role.
I only assume it's a bring your own API keys service that routes your requests based on their contents.

**Comment by qw1642190428** [comment]
> 我没有看到任何 API 文档，也不确定它是否适合后端提供商角色。 我只假设它是一种自带 API 密钥服务，可根据其内容路由您的请求。

https://notdiamond.readme.io/docs/what-is-not-diamond
This is the documentation

**Comment by qw1642190428** [comment]
> I don't see any API docs, and not sure it fits for a backend provider role. I only assume it's a bring your own API keys service that routes your requests based on their contents.

https://notdiamond.readme.io/docs/what-is-not-diamond
This is the documentation

**Comment by Cohee1207** [comment]
Okay. It has an API to choose a model based on input. How is that useful? 

https://notdiamond.readme.io/reference/api-modelselect

**Comment by qw1642190428** [comment]
> Okay. It has an API to choose a model based on input. How is that useful?
> 
> https://notdiamond.readme.io/reference/api-modelselect

One more choice
