### ISSUE TITLE
[BUG] Drawthings API only supports -1 to 4294967295 seed 

### ISSUE THREAD

**Issue by george7551858** [SillyTavern/SillyTavern#2770]
### Environment

🍎 Mac

### System

macOS 14.6.1

### Version

1.12.5

### Desktop Information

- Draw Things version: 1.20240826

### Describe the problem

Generate Image has no problem, but it does occur during Swipe Image:

```
Error: SD DrawThings API returned an error.
    at /Users/ui/workspace/SillyTavern-Launcher/SillyTavern/src/endpoints/stable-diffusion.js:801:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [cause]: '{"body":"","detail":"Value for seed must be between -1 and 4294967295, inclusive (was 3088633670041979)","error":"HTTPException","errors":""}'
}
```
Seems like DrawThings only supports 32-bit integer seed (<4294967295).

It could be because of this line:
https://github.com/SillyTavern/SillyTavern/blob/5b8681ea9793f98c8f7bbb7a802d2193306cbec1/public/scripts/extensions/stable-diffusion/index.js#L3755

Number.MAX_SAFE_INTEGER is 9007199254740991.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Fixed in staging. Please let me know if you could pull and try it out.

**Comment by george7551858** [comment]
It works perfectly. Thank you!
