### ISSUE TITLE
[FEATURE_REQUEST] Set default bot

### ISSUE THREAD

**Issue by steve02081504** [SillyTavern/SillyTavern#2781]
### Have you searched for similar requests?

No

### Is your feature request related to a problem? If so, please describe.

For me, I would often just chat with one character and not explore the others.
Therefore, it would be very convenient if there was a function that could set a default character so that I could talk to it directly after starting the program without selecting a character.

### Describe the solution you'd like

Add a button that allows users to make a bot the default.

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Wolfsblvt** [comment]
You can make an auto-execution QR tied to on startup that calls `/go My Default Character`.

**Comment by LenAnderson** [comment]
There's also the user settings to open the last used chat. If you're only chatting with one char anyways, that's the same as a default char.

**Comment by steve02081504** [comment]
ok got it, ty for help!
