### ISSUE TITLE
[FEATURE_REQUEST] Add New Cohere Models

### ISSUE THREAD

**Issue by isr431** [SillyTavern/SillyTavern#2789]
### Have you searched for similar requests?

Yes

### Describe the solution you'd like

Add support for the new versions of Command R and Command R+.

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

None

**Comment by Cohee1207** [comment]
New models already added in staging branch.

**Comment by Cohee1207** [comment]
https://github.com/SillyTavern/SillyTavern/releases/tag/1.12.6
