### ISSUE TITLE
[FEATURE_REQUEST] Add Ban EOS checkbox to Text Completion

### ISSUE THREAD

**Issue by norasyeezys** [SillyTavern/SillyTavern#2791]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Yes, Ban EOS doesn't work with just kobold or oobabooga. Responses were too short before I found this out.

### Describe the solution you'd like

Add the Ban EOS checkbox to Text Completion as well

### Additional context

Checking BanEOS before switching to text completion resolved the issue of too short messages in sillytavern with kobold (Even when BanEOS was enabled in Kobold, it wouldn't work in sillytavern unless it was also checked in sillytavern!).

The checkbox disappears in text completion. I didn't like my messages too short, especially for RP. This would be helpful.

### Priority

Low (Nice to have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
It already exists, see the image. If you don't see it and you're on the release branch - disable "Simple" UI mode in user settings.

![image](https://github.com/user-attachments/assets/770ce7e0-8b79-4b17-90f4-b33f21c975fe)

**Comment by norasyeezys** [comment]
![Screenshot from 2024-09-06 22-40-37](https://github.com/user-attachments/assets/c7724c9e-26a7-419f-af59-f8543fafaf0e)
Not on Kobold mode it shows

**Comment by cloak1505** [comment]
> It already exists, see the image. If you don't see it and you're on the release branch - disable "Simple" UI mode in user settings.

By default KoboldAI Horde only shows "Ban EOS Token", and KoboldCpp only shows "Skip Special Tokens". Your screenshot refers to `Default [OpenAI /completions compatible: oobabooga, LM Studio, etc.]`.

@norasyeezys Meanwhile you can click on Sampler Select and enable it yourself.

![sampler select menu](https://github.com/user-attachments/assets/e57d4d86-a066-4878-955d-2fe85b842cc2)

> Checking BanEOS before switching to text completion resolved the issue of too short messages in sillytavern with kobold (Even when BanEOS was enabled in Kobold, it wouldn't work in sillytavern unless it was also checked in sillytavern!).

Wait, what? If you mean Kobold Lite UI, that's separate from SillyTavern. koboldcpp.exe backend itself isn't something you "turn off or on". If you mean setting API to KoboldAI Horde, that option should be separate from Text Completion. When I have it enabled in Sampler Select, checking or unchecking Ban EOS Token doesn't check/uncheck the other.

**Comment by Cohee1207** [comment]
@cloak1505 thanks for the clarification, it's now a bit more clear what the reporter meant. The checkbox was always there, just hidden for koboldcpp. Should not be hidden now.
