### ISSUE TITLE
[FEATURE_REQUEST] Reflection compatability

### ISSUE THREAD

**Issue by Vibecoder9000** [SillyTavern/SillyTavern#2793]
### Have you searched for similar requests?

Yes

### Describe the solution you'd like

The finetune Reflection, based on LLama 3.1 70b, is trained with special tokens thinking and output. They are part of the llm output, so creating new options to handle them would be good. Some options that would inprove handling:

Seperare text colors for thinking, output, reflection.

Better formatting, for instance large text for the tags. 

Hiding thinking and reflection sections toggles.

In chat boxes, separating the thinking/results. Artistic liberty to the implementer for this. 

### Additional context

![GWuM7xAWoAEIn61](https://github.com/user-attachments/assets/08cce6a9-b713-43cc-93fa-0bddffce6e19)

https://huggingface.co/mattshumer/Reflection-Llama-3.1-70B

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
Just use regex. There is absolutely no need to implement specific features for just one model.

**Comment by Vibecoder9000** [comment]
> Just use regex. There is absolutely no need to implement specific features for just one model.

If I knew how to use regex 😆

I'll probably just use chatgpt, but really, I think this formatting would be useful if loaded by default when these tokens are used. Maybe I'll try and make an extension.

**Comment by Wolfsblvt** [comment]
Extension is a reasonable way to go and more flexible than STscript + Regex.

But yeah, core features for just one model doesn't sound good.

**Comment by Vibecoder9000** [comment]
Well this ended up as a joke. Apparently it's actually Claude api that managed those results that were worse than Claude, better than chatgpt.

**Comment by Vibecoder9000** [comment]
Bump. This is now actually relevant. New thinking models use tags such as <think> to use CoT. The main feature that would be the most beneficial is a border or box for the thinking with a toggle to hide it entirely.

**Comment by Wolfsblvt** [comment]
Yeah, same here. PR is already in the works. #3345
