### ISSUE TITLE
[FEATURE_REQUEST] STscript to load current name of preset, proxy and model

### ISSUE THREAD

**Issue by GOLDENLULUZ** [SillyTavern/SillyTavern#2802]
### Have you searched for similar requests?

No

### Is your feature request related to a problem? If so, please describe.

I am doing a little fun work here, letting my players using a button to change to a preset with specific mission, like generating a random town to start the adventure, in order to make every LLM game fresh. The problem is, I need to use the QR to get my players back to their original preset. Up to now, I asked them to edit the QR by themselves. You can imagine how many people have difficulty doing that.

### Describe the solution you'd like

A set of STscript orders to load the current name of preset, proxy and model, allowing me to first store them and taking my player back.

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Wolfsblvt** [comment]
Boy do we have something for you.
Check what just got implemented and merged into staging: #2797

**Comment by Cohee1207** [comment]
Try our brand new connection profiles feature.
Docs: https://docs.sillytavern.app/usage/core-concepts/connection-profiles/

**Comment by Cohee1207** [comment]
Connection Profiles have been released.
