### ISSUE TITLE
[BUG] Renaming character in Group Chat does not select the right character and renames the wrong character.

### ISSUE THREAD

**Issue by imesha10** [SillyTavern/SillyTavern#2811]
### Environment

🪟 Windows

### System

Windows 11, Chrome

### Version

75e2790

### Desktop Information

Node JS: v18.15.0
Branch: Staging

### Describe the problem

When going to a group chat for the first time and then clicking on Character A and then going back and clicking Character B then pressing rename on Character B shows the name from Character A.

I thought this error was just maybe just a glitch but when I ran it (rename), it ended up renaming character A and screwing up most of my saves for that character. Fortunately I had a few day old back of the saves.

I have tried to reproduce the effect and I was successful, the way I got it to happen again is going to a group chat, then selecting character A in the group, going back to the group main view, the pressing character A, doing this again for 2/3 times. Then I go to character B and press rename and the name of character A is character B's rename. 

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by imesha10** [comment]
I have looked in the code and I found that:
``` js
export async function renameCharacter(name = null, { silent = false, renameChats = null } = {}) {
    if (!name && silent) {
        toastr.warning('No character name provided.', 'Rename Character');
        return false;
    }
    if (this_chid === undefined) {
        toastr.warning('No character selected.', 'Rename Character');
        return false;
    }

    const oldAvatar = characters[this_chid].avatar;
    const newValue = name || await callGenericPopup('<h3>New name:</h3>', POPUP_TYPE.INPUT, characters[this_chid].name);
    ....... (rest of code)
```

this_chid is assigned the wrong index for the character (using chrome debug)



Then I looked where this is called:
``` js
    $('#char-management-dropdown').on('change', async (e) => {
        let target = $(e.target.selectedOptions).attr('id');
        switch (target) {
            case 'set_character_world':
                openCharacterWorldPopup();
                break;
            case 'set_chat_scenario':
                await setScenarioOverride();
                break;
            case 'renameCharButton':
                renameCharacter();
                break;
```

However I'm unable to find where this_child value is set.

**Comment by imesha10** [comment]
I found this function, however it does not seem to be triggered by the debugger when I switch between character in the group chat at all so I'm guessing it's not called or related:
``` js
export async function selectCharacterById(id) {
    if (characters[id] === undefined) {
        return;
    }

    if (isChatSaving) {
        toastr.info('Please wait until the chat is saved before switching characters.', 'Your chat is still saving...');
        return;
    }

    if (selected_group && is_group_generating) {
        return;
    }

    if (selected_group || this_chid !== id) {
        //if clicked on a different character from what was currently selected
        if (!is_send_press) {
            await clearChat();
            cancelTtsPlay();
            resetSelectedGroup();
            this_edit_mes_id = undefined;
            selected_button = 'character_edit';
            this_chid = id;
            chat.length = 0;
            chat_metadata = {};
            await getChat();
        }
    } else {
        //if clicked on character that was already selected
        selected_button = 'character_edit';
        select_selected_character(this_chid);
    }
}
```

The only other thing that seems to set it is:
``` js
export function setCharacterId(value) {
    this_chid = value;
}
```

Actually I set a debug point at SetCharacterID and it hit, so that's where it is set.

**Comment by imesha10** [comment]
Ok, I found a clue to the issue.

In the group chat, when selecting a character sometimes it seems that there is two calls to `setCharacterID` being made.

It seems that if I stay long enough on the main group chat menu with all the characters, the first call get's done, then if I go to the specific character then the right `this_chid` is set.

The bug seems to happen when before the first call to the setCharacterID is made, you go to the specific character, it sets the `this_chid` to the right number however then the second call happens and sets it to the wrong `this_chid`.

Now I need to figure out where this first setCharacterID in the group chat menu comes from.

**Comment by imesha10** [comment]
The code that seems to call this 'first' setCharacterID that get's called everytime except the first time you go the character menu seems to from the `export async function Generate` specifically:

https://github.com/SillyTavern/SillyTavern/blob/5b8681ea9793f98c8f7bbb7a802d2193306cbec1/public/script.js#L3379-L3386

(figured this out using chrome debugger)

At this point I don't have any idea why this function ('generating') is being called when it's not generating.

**Comment by imesha10** [comment]
I found that this is called by:

https://github.com/SillyTavern/SillyTavern/blob/5b8681ea9793f98c8f7bbb7a802d2193306cbec1/public/scripts/openai.js#L650-L656

Which is then called from:
https://github.com/SillyTavern/SillyTavern/blob/5b8681ea9793f98c8f7bbb7a802d2193306cbec1/public/scripts/PromptManager.js#L712-L745

The lines that seem interesting is this line:
```js
waitUntilCondition(() => !is_send_press && !is_group_generating, 1024 * 1024, 100).then(async ()
```

If I had guess what is happening this delay here is causing the initial call to the SetCharacterID to be delayed. However in the mean time when I press another character in a group SetCharacterID is immediately called and then after the delay is done the SetCharacterID is then called again but with `setCharacterId(memberIds[0]); `

**Comment by imesha10** [comment]
At this point I think there are two possible solutions.

A) to reduce the timeout from 100ms to something smaller
B) instead of setting `setCharacterId(memberIds[0])` check if the individual character menu is open from the group chat menu and use that ID instead.

I think B makes the most sense because it might not just be the timeout, but just delay from running the functions. I also don't know what other efffect changing that timeout will do.
So B is a better solution I think.

However I don't know how to check if the character menu in the group chat is open and get the character_id from that.

**Comment by imesha10** [comment]
Okay I think I managed to fix it:

https://github.com/imesha10/SillyTavern/blob/448af33b4d195ee531fe983dd56cdc3db2775184/public/script.js#L3414-L3422

``` js
        if (memberIds.length > 0) {
            if (menu_type != 'character_edit') setCharacterId(memberIds[0]);
            setCharacterName('');
        } else {
            console.log('No enabled members found');
            unblockGeneration(type);
            return Promise.resolve();
        }
 ```
I'm making a PR

**Comment by Cohee1207** [comment]
Thanks for conducting a thorough investigation. I'll review the PR shortly.

> At this point I don't have any idea why this function ('generating') is being called when it's not generating.

It's not actually generating, but performing a dry run to calculate the prompt the token counts of the prompt parts.

**Comment by imesha10** [comment]
Thank you for reviewing and merging the PR. 🔥
