### ISSUE TITLE
[FEATURE_REQUEST] Invoke generations by other characters in a group chat if the current character tries to spek on their behalf

### ISSUE THREAD

**Issue by PinkSerenity** [SillyTavern/SillyTavern#2816]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Currently, generations of a certain character can be triggered if the AI mentions them in the last response. However, since AIs work by simply repeating learned patterns, often (at least when I tested it) if the character is not mentioned, instead the AI tries to speak on their behalf.
The message trim in group chats usually removes that; it can be turned off by enabling (kinda weird that you enable something to disable a feature) the option "Relax message trim in Groups". That message trim does only trim though, it does not trigger the generation of the other character.

### Describe the solution you'd like

Basically, instead of having the binary trimming option, I suggest a drop-down, where trimming can be turned off, turned on or invoke the generation of another character's response.

While I'm far from an expert, I don't assume it's a lot of work; the trimming feature already checks whether another character exists, and so it would only need to trigger a function that generates their response. Though I could be completely be wrong about that.

### Describe alternatives you've considered

The alternative would be turning off the trimming option so the user can see which character the AI tries to invoke, then editing the message to remove the lines and manually triggering the generation. That is very tedious.

### Additional context

This would help a lot with narrators in group chats. Basically, the narrator knows a bit of all characters and is tasked with comming up with scenarios and such, and as soon as it wants a character to speak, it will trigger the generation of that character by writing `{{other_char}}:`, and that character (otherwise set to shy so it will only talk when the narrator wants it to talk) will then respond accordingly.
This is a great way of saving tokens while still having the benefit of the narrator knowing every character (more or less) and writing the scenario like that.

I additionally suggest (tell me if I'm supposed to make that a new feature request) to make narrated group chats their own feature. In a narrated group chat the Talkativeness of every member but the narrator gets overwritten and set to 0. The narrator character will always be invoked after any character or the user have stopped speaking.

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by PinkSerenity** [comment]
Looking back, I don't think I have described it well. This is what I suggest:
### "Relax message trim in Groups" enabled:
**Foo:**
> *Lorem ipsum dolor sit amet.* At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
>
>Bar: *Lorem ipsum dolor sit amet, consetetur sadipscing elitr.* Sed diam.

### "Relax message trim in Groups" disabled (default):
**Foo:**
> *Lorem ipsum dolor sit amet.* At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
>
>~~Bar: *Lorem ipsum dolor sit amet, consetetur sadipscing elitr.* Sed diam.~~

### What I'd like to have:
**Foo:**
> *Lorem ipsum dolor sit amet.* At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
>
>~~Bar: *Lorem ipsum dolor sit amet, consetetur sadipscing elitr.* Sed diam.~~

**Bar** generation is automatically invoked.

**Bar**:
>*Lorem ipsum dolor sit amet, consetetur sadipscing elitr.* Sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.

**Comment by Wolfsblvt** [comment]
Other chars are added as stopping strings on the actual API side for the generation. I don't think there is a way to find out that the stopping string/stop was triggered for a specific other group member.

**Comment by PinkSerenity** [comment]
> Other chars are added as stopping strings on the actual API side for the generation. I don't think there is a way to find out that the stopping string/stop was triggered for a specific other group member.

That would be indeed a problem. The word "trim" instead of "stop at" made it sound like it happens client side. As it is, it might be something that should be an extension instead that will trim the other characters client-side and will handle the invoking. I will look into it a bit, but I doubt that I will actually do anything. I know that from past projects and ideas.

**Comment by Cohee1207** [comment]
> Other chars are added as stopping strings on the actual API side for the generation

Technically you can disable this by unchecking "names as stop strings" in the context formatting. This with relaxed trimming could do what @PinkSerenity wants, but I doubt this is portable to all backends and APIs equally. Ideally, all backends should support stop strings and react to them, so group names trimming only exists as a safety measure for those who don't.

I'm not sure what the implications would be of allowing this even if there were no other considerations. Could this lead to endless looping of the same characters replying to each other? Quite possibly. Just note how leaving the group chat on auto mode for too long leads to inevitable quality degradation on any model, since it goes into a feedback loop.

**Comment by PinkSerenity** [comment]
> I'm not sure what the implications would be of allowing this even if there were no other considerations. Could this lead to endless looping of the same characters replying to each other? Quite possibly. Just note how leaving the group chat on auto mode for too long leads to inevitable quality degradation on any model, since it goes into a feedback loop.

That is true. I still think it's easier to stop a generation than to invoke one, since for the latter you'd have to keep the member list open at all times. One could also have the rule that only one character would be allowed to invoke other generations, which would fit my idea for a special role for narrator characters. Also, one of the characters might still respond with "You:", which might stop (depending on the setting, I don't know what the default setting is) the generation as well.

I think it's worth trying, at least, and I think I'll try to write an extension for that.
