### ISSUE TITLE
[BUG] error creating image

### ISSUE THREAD

**Issue by clbl07** [SillyTavern/SillyTavern#2818]
### Environment

🪟 Windows

### System

windows10

### Version

???

### Desktop Information

sillytavern

### Describe the problem

I'm getting the image error when I try to create images of the characters I talk to in SillyTavern, I'm using stable horde with the "Use multimodal captioning for portraits" option
without it I can make images, but they don't look like my characters, any way to fix this?

sorry my english, not my main language

### Additional info

![chrome_40caaHBYi6](https://github.com/user-attachments/assets/f9c286dd-5e98-4d70-a5ca-2d2c3cd52f25)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Did you configure multimodal captions in the image captioning extension settings to use a valid source (that you have access to)?

**Comment by clbl07** [comment]
> Did you configure multimodal captions in the image captioning extension settings to use a valid source (that you have access to)?
I didn't know it was necessary, maybe I'll try later, thanks

**Comment by Cohee1207** [comment]
Reopen if persists with providing more details. I don't see anything broken with multimodal correctly configured.
