### ISSUE TITLE
[FEATURE_REQUEST] Adjust CC's Default names behavior and make TC's options consistent with CC

### ISSUE THREAD

**Issue by cloak1505** [SillyTavern/SillyTavern#2819]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Currently, Chat Completion's "Default" is more sane and adds prefixes for groups and past personas. The problem is Text Completion's "Force for Groups and Personas" forces current persona even in solo chat ("Include Names" unchecked). In fact, this feels like a bug.

### Describe the solution you'd like

~~Change TC's "Force for Groups and Personas" to "Force for Groups and Past Personas". That's it, this will make TC's two checkboxes match CC's None (TC both unchecked), Default (TC 2nd checked), and Message Content (TC 1st checked, or 2nd checked in group chat).~~

Edit: Request changed slightly. Make the "past persona" part of CC's Default solo chat apply to group chat too.

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Wolfsblvt** [comment]
I am not sure about this. Using names for all persona messages is that people likely need a lot in group chats.

You have to keep in mind that opposite to Chat Completion, which actually has **structured** messages with roles attached to the messages, and so on, Text Completion does not have any of that.
Roles are made up. Your context is a plaintext. How would you know what kind of message this is in a group chat without any prefix?
Sure, some TC models use some kind of instruct structure where this is visible. Others don't.
The option is there because people need it.

**Comment by cloak1505** [comment]
Do people actually want a situation where only persona names are used, excluding character names? Because that's what TC is doing in solo chat. And there's no option to do this in CC.

All instruct formats have a way to distinguish between user and model turns.

```
You are Bob the Builder. Alex is a close friend of Bob.

### Instruction:
"Hey Bob," Alex greets. Bob recognizes him and says his name.

### Response:
 "Hi, Alex!"
```
```
You are Bob the Builder.
<user_info>
Alex is a close friend of Bob.
</user_info>

### Instruction:
"Hey Bob," I greet. Bob recognizes me and says my name.

### Response:
 "Oh, hey Alex!" Bob replies with a warm smile. "What can I help you with today?"
 ```
 
Sure, there's no system tag for the context, but why would I need one? Such a model may be served over CC too. (Edit: Er, hypothetically... I don't think any modern CC model uses Alpaca but it's not like TC implodes when I prefix the sys prompt with `### Instruction:`. If you mean disabling Instruct Mode, names are always on.)

CC in general can get "confused" just like TC if you speak in first person without introducing yourself or indicating who you are in the context.

> I am not sure about this. Using names for all persona messages is that people likely need a lot in group chats.

Hold on, I notice you said this... I should clarify that I am not asking to change persona name behavior for group chats. All persona names are applied during group chat for both CC and TC. I am asking for current persona name to not apply in TC solo chat if "Include Names" is not checked.

As someone who almost never switches persona mid-chat, to mimic most of CC "Default" behavior to TC I would have to ignore "Force for Groups and Personas" and toggle "Include Names" every time I switch between solo and group chats. However, if I were to switch persona in solo chat, I would have to Force Personas which would show both past and current persona names.

(I'm actually in the process of drafting a separate feature request for an option to disable persona names for CC/TC group chats for user freedom as to which names are included for which type of chat. I haven't posted yet because I have to come up with reasonable UI designs without being too cluttered.)

**Comment by Wolfsblvt** [comment]
I don't have persona names in front of my messages in solo chats. I am not sure which settings you use or which kind of instruct template, but the toggles do work for solo chats as you'd expect.

![image](https://github.com/user-attachments/assets/af2f4b21-4093-4a1f-a40d-58c9fa7c7db3)

**Comment by cloak1505** [comment]
![solo chat tc force groups and personas](https://github.com/user-attachments/assets/818f8bcc-9671-440a-9138-b8509d4c3492)

To exclude persona, I would have to uncheck "Force for Groups and Personas", but then check either checkbox to get character names back in group chat.

**Comment by Wolfsblvt** [comment]
Ah, you have that checkbox checked. Yeah, then sure the name gets added.
I cannot tell you why the two options are combined into one toggle, and not separate ones - and I can't find a reason just thinking about it either.

**Comment by Cohee1207** [comment]
@cloak1505 
So you imagine the behavior of the toggle to be like a radio button instead? Please confirm.

* None - no names added
* Default - no names except for groups and personas
* Forced - all names, including current persona and non-groups

**Comment by Wolfsblvt** [comment]
Why do groups and personas have to be combined?
I would just make it two toggles.

- [ ] Include Names
  - [ ] Force for Persona
  - [ ] Force for Group

I think it makes sense to say groups need names all the time (then its also forced for persona inside a group chat), but in a solo chat I don't need enforced names for my persona. Either I turn on all (Include Names),  or I don't want name prefixes at all.

**Comment by cloak1505** [comment]
Took me awhile to think about...

The way CC's Default currently works is that "Groups" forces current persona too. However, if we made "Default" not apply current persona, then we can really just have 3 radio buttons.

```
Include Names
○ Never
○ For Groups and Past Personas
○ Always, All Names
```

Wrote the entries concisely to fit AF columns. This omits the option to strictly include only group chars and exclude persona name, but I don't think this has any demand. I personally don't care about past persona names showing hence no need for "Group chars only"; the only reason I care about current persona is because models often attribute OOC messages to {{user}}, sometimes continuing the RP, instead of as a direct user message.

![current UI 800px chat on 2560px window](https://github.com/user-attachments/assets/0f9548d8-83ed-4b52-af4c-88729d1ee3c1)

@ Wolf, very close but that suggestion doesn't make a distinction between past and current personas.

Anything more complex than the adjustment to the three radio buttons would require more checkboxes and clutter the UI, and radio buttons are simpler than checkboxes (one is active at a time), so this is the best solution.

**Comment by Cohee1207** [comment]
PR here, needs testing: #2837
