### ISSUE TITLE
[BUG] `/sendas name=` command forces name prefix even if name matches active solo chat card

### ISSUE THREAD

**Issue by cloak1505** [SillyTavern/SillyTavern#2820]
### Environment

🪟 Windows

### System

Firefox

### Version

1.12.5 'staging' (1582974b)

### Describe the problem

`/sendas name=Char message` forces the "Char:" prefix even when you are solo chatting with Char. This occurs with both CC's "Default" or TC's "Force for Groups and Personas" ("Include Names" off). Effectively, a slash commanded message is treated like a doppelganger group chat member taking the same avatar.

Expected: Don't force name prefix for `/sendas` messages when name matches the solo chat card and CC set to Default or TC set to Force for Groups ("Include Names" off).

### Additional info

(User `/send` messages behave correctly.)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Wolfsblvt** [comment]
PR for a fix is open. You can test it if you want.

It'll only work for new messages though, everything until when the fix is active had it saved to the chat context already.

**Comment by cloak1505** [comment]
looks good
