### ISSUE TITLE
[FEATURE_REQUEST] Add support for outgoing request proxying

### ISSUE THREAD

**Issue by LurkerHub** [SillyTavern/SillyTavern#2824]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

For security/privacy/anonymity reasons, it can be desirable for ST traffic to go through a different channel than the rest of the user's internet traffic.  The user may be on a network that blocks access, trying to access a geo-fenced server, etc.

Many Internet-facing applications allow for specifying a "forward proxy" to route traffic through.

For example, the FireFox browser:
<details>
  <summary>Screenshot</summary>
  <img src="https://files.catbox.moe/32i7k8.png">
</details>

### Describe the solution you'd like

Allow configuring an HTTP/HTTPS/SOCKS4/SOCK5 forward proxy in ST.
It can have a UI or use a config file.

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Wolfsblvt** [comment]
Are you talking about ST browser window to ST server communication, or ST server to the API/backend?

Both should already be doable though. For re-routing your calls to your own server you can use whatever proxy you want, and and Chat Completion APIs support specifying a reverse proxy. Just set up your own reverse proxy then.

**Comment by Cohee1207** [comment]
PR's up. Go try it if you want: #2828

**Comment by alexolog** [comment]
> Are you talking about ST browser window to ST server communication, or ST server to the API/backend?
> 
> Both should already be doable though. For re-routing your calls to your own server you can use whatever proxy you want, and and Chat Completion APIs support specifying a reverse proxy. Just set up your own reverse proxy then.

I am talking about a forward proxy between the server and the Internet, basically a tunnel on TCP/IP, independent of the API.

**Comment by LurkerHub** [comment]
> PR's up. Go try it if you want: #2828

Thanks! I'll take a look.

**Comment by LurkerHub** [comment]
I got a deprecation warning when I used an IP address for the proxy:
```
(node:8212) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
(Use `node --trace-deprecation ...` to show where the warning was created)
```
Not a big deal.

For some reason it did not work when I used HTTPS for the proxy:
```
Error communicating with Claude: FetchError: request to https://blank-blank-blank-blank.trycloudflare.com/proxy/aws/claude/messages failed, reason: write EPROTO 40220000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:355:
```
Which is weird, since it works if I use it as an HTTPS proxy in Firefox.

Changing the proxy protocol to HTTP worked without a hitch.

I will check SOCKS proxies when I find them :) But since you're using an external library it should work just the same.

Thank you!

**Comment by LurkerHub** [comment]
Can you make the config values overridable on the command-line?

Thank you!

**Comment by LurkerHub** [comment]
Thanks for the changes!

**Comment by LurkerHub** [comment]
As a followup, I have noticed that when using a slow forward proxy, I am getting many connection timeouts (`ETIMEDOUT`) and read timeouts (`ECONNRESET`) errors.

Are the timeout values configurable?
If not, can they be made configurable?

Examples:
```
Error communicating with Claude: FetchError: request to https://<address-here> failed, reason: socket hang up
```

**Comment by LurkerHub** [comment]
As a followup, I have noticed that when using a slow forward proxy, I am getting many connection timeouts (`ETIMEDOUT`) and read timeouts (`ECONNRESET`) errors.

Are the timeout values configurable?
If not, can they be made configurable?

Examples:
```
Error communicating with Claude: FetchError: request to https://.../proxy/aws/claude/message failed, reason: socket hang up

Error communicating with Claude: FetchError: request to https://.../proxy/aws/claude/messages failed, reason: Client network socket disconnected before secure TLS connection was established

Error communicating with Claude: FetchError: request to https://.../proxy/aws/claude/messages failed, reason: connect ETIMEDOUT aaa.bbb.ccc.ddd:3128
-
```

**Comment by Cohee1207** [comment]
Timeouts on Claude API requests are [explicitly](https://github.com/SillyTavern/SillyTavern/blob/staging/src/endpoints/backends/chat-completions.js#L151)  disabled.

**Comment by LurkerHub** [comment]
> Timeouts on Claude API requests are [explicitly](https://github.com/SillyTavern/SillyTavern/blob/staging/src/endpoints/backends/chat-completions.js?rgh-link-date=2024-09-18T16%3A54%3A36Z#L151) disabled.

Well, something causes these errors intermittently, and googling suggested socket timeouts.
I don't know what can be the cause.

**Edit:**
Updated the comment above with an error that explicitly mentioned `ETIMEDOUT` on the forward proxy.
