### ISSUE TITLE
[BUG] cards being messed in chat after using /ask macro

### ISSUE THREAD

**Issue by hlyyzz** [SillyTavern/SillyTavern#2825]
### Environment

🪟 Windows

### System

debian 12, windows 11

### Version

Latest staging release 

### Describe the problem

I'm using /ask macro in Quick reply, there's a bug which allow card A could incorrectly jump into card B's chat. Like this:
![1000068567](https://github.com/user-attachments/assets/12ca436a-95f2-4549-852a-a28e17d203c8)
The steps to repeat this bug: 
1. use /ask macro through Quick reply in card A's chat
2. Go to card B and send a normal message 
3. Use /ask macro through Quick reply in card B's chat

### Additional info

The Quick reply I'm using:
/preset B|
/ask name={{char}}{{input}}

<Request: Pause the plot. Contents in {{char}}'s first-person-POV, writing in a codeblock of {{random: 5, 6, 7, 8}} different creatively tips for {{user}}'s next move>|
/preset A|

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by hlyyzz** [comment]
This bug could destroy the whole chat log, and also may cause a "character not found(not quite remember the text)" error.
my solution for now: reload the page

**Comment by Cohee1207** [comment]
Try the proposed fix here: #2826

cc: @cloak1505

**Comment by Cohee1207** [comment]
Fix merged to staging.

**Comment by cloak1505** [comment]
Aiieee, a new bug that's just as bad! Issue #2832
Edit: Fixed.
