### ISSUE TITLE
[BUG] Quick Reply option does not show up on desktop versions of browsers

### ISSUE THREAD

**Issue by Godoword** [SillyTavern/SillyTavern#2827]
### Environment

🐋 Docker

### System

Desktop version Chrome/EDGE/Safari

### Version

1.12.5

### Desktop Information

Windows/iPad

### Describe the problem

I'm running SillyTavern on my own VPS.

Quick Reply option does not show up on desktop versions of browsers, including Chrome/EDGE/Safari

Since the iPad requests desktop by default, it's also affected.

On the iPhone it shows up fine.

The two screenshots are from the desktop version of Chrome and Safari under the iPad, respectively

![Chrome](https://github.com/user-attachments/assets/c6677023-ddac-4053-a2cd-6719ad5a5e89)
![iPad](https://github.com/user-attachments/assets/1dc9244e-89a3-472a-8a30-5bc797da16f3)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Press F12 and see if any error logs are to be found in the console. Also make sure that you're using the latest version of every browser.

**Comment by Godoword** [comment]
> Press F12 and see if any error logs are to be found in the console. Also make sure that you're using the latest version of every browser.

Uncaught TypeError: QuickReplySet.list.toSorted is not a function
    at SettingsUi.prepareQrEditor (SettingsUi.js:149:28)
    at SettingsUi.prepareDom (SettingsUi.js:227:14)
    at SettingsUi.render (SettingsUi.js:65:22)
    at async init (index.js:174:52)
    at async index.js:224:1

I can't view it on the iPad.

It shows up fine on iPhone because the browser is requesting a mobile device

**Comment by Cohee1207** [comment]
I added a polyfill for toSorted to staging, but please update your browser. You're using a version that is outdated by at least 1.5 years.

Source: https://caniuse.com/?search=tosorted
