### ISSUE TITLE
[BUG] /ask command overwrites the target card's last save with the current chat

### ISSUE THREAD

**Issue by cloak1505** [SillyTavern/SillyTavern#2832]
### Environment

🪟 Windows

### System

Firefox

### Version

 1.12.5 'staging' (a88b4232)

### Describe the problem

**`/ask` command is destructive.**

Whenever you use `/ask name=Char something`, Char's last opened chat will be overwritten as a copy of the chat you used /ask in.

### Additional info

Reproduce: Open a card to note the last opened save (rename to something like "asdf" if you want to), go to a different card to `/ask` aforementioned card, go back and notice the save is overwritten.

The current workaround is to pick a sacrificial save (or new chat) under the target card before using /ask. Irrelevant if the card is something you never chat with.

![might not be a bad idea to scrap the command lmao](https://github.com/user-attachments/assets/ebd7cb1f-baa7-47ae-a5e4-d45f1ab84528)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by hlyyzz** [comment]
Oh no that screenshot, please don't remove it, I need it to temporarily use another preset to make current character do some special tasks.

**Comment by cloak1505** [comment]
Terminal displays the following error when I import a card named foobar, never open it, and then `/ask` under another card:
```
Error: ENOENT: no such file or directory, open 'D:\LLM\SillyTavern\data\default-user\chats\foobar\2024-9-12 @00h 21m 08s 252ms.jsonl.228269195'
    at Object.openSync (node:fs:582:18)
    at writeFileSync (D:\LLM\SillyTavern\node_modules\write-file-atomic\lib\index.js:216:13)
    at D:\LLM\SillyTavern\src\endpoints\chats.js:149:9
    at Layer.handle [as handle_request] (D:\LLM\SillyTavern\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\LLM\SillyTavern\node_modules\express\lib\router\route.js:149:13)
    at D:\LLM\SillyTavern\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:206:9)
    at invokeCallback (D:\LLM\SillyTavern\node_modules\raw-body\index.js:238:16)
    at done (D:\LLM\SillyTavern\node_modules\raw-body\index.js:227:7)
    at IncomingMessage.onEnd (D:\LLM\SillyTavern\node_modules\raw-body\index.js:287:7) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'D:\\LLM\\SillyTavern\\data\\default-user\\chats\\foobar\\2024-9-12 @00h 21m 08s 252ms.jsonl.228269195'
}
Error: ENOENT: no such file or directory, open 'D:\LLM\SillyTavern\data\default-user\chats\foobar\2024-9-12 @00h 21m 08s 252ms.jsonl.3460571277'
    at Object.openSync (node:fs:582:18)
    at writeFileSync (D:\LLM\SillyTavern\node_modules\write-file-atomic\lib\index.js:216:13)
    at D:\LLM\SillyTavern\src\endpoints\chats.js:149:9
    at Layer.handle [as handle_request] (D:\LLM\SillyTavern\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\LLM\SillyTavern\node_modules\express\lib\router\route.js:149:13)
    at D:\LLM\SillyTavern\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:206:9)
    at invokeCallback (D:\LLM\SillyTavern\node_modules\raw-body\index.js:238:16)
    at done (D:\LLM\SillyTavern\node_modules\raw-body\index.js:227:7)
    at IncomingMessage.onEnd (D:\LLM\SillyTavern\node_modules\raw-body\index.js:287:7) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'D:\\LLM\\SillyTavern\\data\\default-user\\chats\\foobar\\2024-9-12 @00h 21m 08s 252ms.jsonl.3460571277'
}
```
When I open foobar, the save filename is dated the same as above, but contains the original greeting only rather than being a copy of the chat that used `/ask`.

**Comment by Cohee1207** [comment]
The fact that the chat with ask result was not saved after the reload should've ring the bell...

Try again.

**Comment by cloak1505** [comment]
> 2379fd5

Same behavior. For clarification, the command visibly works/worked but inadvertently saves to two locations, the active chat and last opened chat of the summoned card.

Same error in terminal for a never-opened card except the error shows once instead of twice.

**Comment by Wolfsblvt** [comment]
@Cohee1207 The issue likely is that the ask "prompt" that gets send as a user message before already triggers a chat save anyway.
That thing is very fucky by not even using a callback or function or anything, but triggering the message send button in chat.

But yeah, message send saves chat too, so you'll already save during the "switched char" chat.

**Comment by Cohee1207** [comment]
Why I do feel that removing or completely rethinking `/ask` would be a better solution.

**Comment by Wolfsblvt** [comment]
Because it likely is.

I don't see an easy way though, as you still need to inject and replace everything character-specific (character defs, possible WI triggers). Who knows about QRs that target the char by name that you are talking to, and much more.

Edit: I mean, switching the current textbox trigger thingy to using the prompt on something like the `/send` callback to make the user message *should* fix that current bug.
Not sure if more issues pop up though.

**Comment by Cohee1207** [comment]
Alright, if that wasn't it, /ask goes bye-bye for a while.

**Comment by cloak1505** [comment]
Works on my end. 👍
No external saving, no terminal error.

Don't mean to cause hair loss, but while we're on this topic, how easy would it be to make the string parameter optional? This will allow the user to `/del 1` then repeat the name part only of `/ask` ("swipe"), or preemptively `/send`. Basically a stringless ask will act like a solo chat version of `/trigger` that calls an external card.

**Comment by Cohee1207** [comment]
Possibly a few lines of code.
