### ISSUE TITLE
[BUG] /genraw error when model is not loaded

### ISSUE THREAD

**Issue by drago87** [SillyTavern/SillyTavern#2836]
### Environment

🪟 Windows

### System

Win 10, Opera

### Version

SillyTavern 1.12.5 'staging' (5e0a61ba)

### Desktop Information

TabbyAPI

### Describe the problem

If you don't load a model before running the `/genraw` command you get a non descript error
`SlashCommandExecutionError True` and nothing to indicate that it's the model that is not loaded.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Wolfsblvt** [comment]
Out on staging. Feel free to test this.
