### ISSUE TITLE
[FEATURE_REQUEST]Can a chat style option be added that looks like what we see in messaging apps, with avatars on either the left or right side?

### ISSUE THREAD

**Issue by leetraman822** [SillyTavern/SillyTavern#2839]
### Have you searched for similar requests?

Yes

### Describe the solution you'd like

Can a chat style option be added that resembles the bubble style used in messaging apps? I'm currently using the 'bubbles' style, but both the user's and character's avatars are stationary on the left side. Could it be possible to have the user's avatar on the right and the character's avatar on the left, or vice versa? I believe this could enhance the sense of immersion in our conversation.

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Wolfsblvt** [comment]
This is all customizable via simple Custom CSS.
SillyTavern is very extensible for a reason.

People have shared several approaches for stuff like this on the Discord in the past.

One example was done by @LenAnderson:

> Set *Avatars* to *Circle*, *Chat Style* to *Flat* and paste this into *Custom CSS*
> ```CSS
> #chat .mes * {
>     text-shadow: none;
> }
> #chat {
>     .mes {
>         align-items: stretch;
>         .mesAvatarWrapper {
>             display: flex;
>             flex-direction: column-reverse;
>             align-content: flex-end;
>             padding-bottom: 0;
>             > .avatar {
>                 flex: 0 0 auto;
>             }
>         }
>         .mes_block {
>             width: 80%;
>             border-radius: 10px;
>             margin-bottom: 2em;
>             position: relative;
>             overflow: visible;
>             &:after {
>                 content: "";
>                 position: absolute;
>                 bottom: -10px;
>                 height: 20px;
>                 width: 20px;
>             }
>             > .ch_name {
>                 color: rgb(234, 234, 234);
>                 position: absolute;
>                 bottom: -1em;
>                 max-width: 80%;
>                 .name_text {
>                     font-size: calc(var(--mainFontSize) * 0.7);
>                 }
>             }
>         }
>     }
>     .mes[is_user="true"] {
>         flex-direction: row-reverse;
>         .mes_block {
>             background: #4974ed;
>             margin-right: 1em;
>             &:after {
>                 right: -10px;
>                 background: #4974ed;
>                 clip-path: polygon(0% 50%, 50% 0%, 100% 100%);
>             }
>             > .ch_name {
>                 right: 1em;
>             }
>         }
>     }
>     .mes[is_user="false"] {
>         .mes_block {
>             background: rgb(200, 200, 200);
>             color: black;
>             margin-left: 1em;
>             &:after {
>                 background: rgb(200, 200, 200);
>                 left: -10px;
>                 clip-path: polygon(50% 0%, 100% 50%, 0% 100%);
>             }
>             > .ch_name {
>                 left: 1em;
>             }
>         }
>     }
> }
> ```
> You probably have to adjust the colors a bit, but this should get you started.
>
> ![image](https://github.com/user-attachments/assets/4d421db5-55a8-4043-95b3-812147a54157)

**Comment by leetraman822** [comment]
> This is all customizable via simple Custom CSS. SillyTavern is very extensible for a reason.

WOW, Thank you!
