### ISSUE TITLE
[BUG] LM Studio API integration wrong.

### ISSUE THREAD

**Issue by maniac-0s** [SillyTavern/SillyTavern#2849]
### Environment

🪟 Windows

### System

Firefox

### Version

1.12.´5

### Describe the problem

In the Text completion I have the option to select Default [oogabooga, LM Studio, etc] but that causes LM Studio to throw an error.

```
[2024-09-14 23:57:58.246] [INFO] Received GET request to /v1/models with body: {}
[2024-09-14 23:57:58.247] [INFO] Returning {
  "data": [
    {
      "id": "RichardErkhov/UCLA-AGI_-_Gemma-2-9B-It-SPPO-Iter3-gguf/Gemma-2-9B-It-SPPO-Iter3.Q8_0.gguf",
      "object": "model",
      "owned_by": "organization-owner",
      "permission": [
        {}
      ]
    }
  ],
  "object": "list"
}
[2024-09-14 23:58:13.786] [INFO] Received GET request to /v1/models with body: {}
[2024-09-14 23:58:13.786] [INFO] Returning {
  "data": [
    {
      "id": "RichardErkhov/UCLA-AGI_-_Gemma-2-9B-It-SPPO-Iter3-gguf/Gemma-2-9B-It-SPPO-Iter3.Q8_0.gguf",
      "object": "model",
      "owned_by": "organization-owner",
      "permission": [
        {}
      ]
    }
  ],
  "object": "list"
}
[2024-09-14 23:58:13.792] [ERROR] Unexpected endpoint or method. (GET /v1/internal/model/info). Returning 200 anyway
```

When I chose Aphrodite, I don't get an error in LM Studio but later on there are issues for instance that it won't notice that the server finished sending. I then always have to click stop to get to a new slide or regenerate. Also when generating the first response I always get that error

```
[2024-09-15 00:04:49.027] [ERROR] Unexpected endpoint or method. (POST /v1/internal/encode). Returning 200 anyway
[2024-09-15 00:04:49.768] [INFO] [LM STUDIO SERVER] Processing queued request...
```
In Silly I get the yellow notification about the same encode issue. I am not sure if that's related to selecting Aphrodite but I guess it is.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by maniac-0s** [comment]
Does the commit solve the issue? Because my Silly claims it's on the latest commit but the issue with getting errors when selecting "Default" persists.

**Comment by Cohee1207** [comment]
Staging branch only.
