### ISSUE TITLE
[BUG] Talkinghead plugin not working properly(not loading without workaround)

### ISSUE THREAD

**Issue by MNarath1** [SillyTavern/SillyTavern#2850]
### Environment

🐋 Docker

### System

Fedora 40 ,Docker version 27.2.1, build 9e34c9b

### Version

SillyTavern 1.12.5

### Describe the problem

The talkinhead animation doesn't load on startup to get it to work you have to first change the classifier api under expressions away from extras and then change it back again after that renable talkinghead and it works again.
So its probably an issue with the frontend and not with the extra api backend.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Try this: https://github.com/SillyTavern/SillyTavern/commit/dcaa8d5e9c9845c5c2d090fb9cff523f581c646c

I have no ability to test this, didn't have working talkinghead setup for ages.

**Comment by MNarath1** [comment]
> Try this: [dcaa8d5](https://github.com/SillyTavern/SillyTavern/commit/dcaa8d5e9c9845c5c2d090fb9cff523f581c646c)
> 
> I have no ability to test this, didn't have working talkinghead setup for ages.

doesn't work sadly i am gonna try to debug this more in js in my browser and get back to you if i find something.
