### ISSUE TITLE
[FEATURE_REQUEST] Revert default persona avatar's color to grey

### ISSUE THREAD

**Issue by cloak1505** [SillyTavern/SillyTavern#2862]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

At some points in time the default persona avatar was at least two different versions of grey, but it is now matching the purple default character, and the grey only applies to the account in User Settings > Account. This purpleization makes the user base's default persona avatar further inconsistent.

### Describe the solution you'd like

Make default persona avatar grey, but leave default character avatar purple.

### Describe alternatives you've considered

It is trivial to manually set it, but automating it doesn't seem to be a one line fix (tfw codelet).

What I tried: Copy `./default/content/user-default.png` to `'./public/img/`, then edit line 510 in `./public/script.js` from `export const default_avatar = 'img/ai4.png';` to `'img/user-default.png'`.

This will set default persona avatar to grey and leave new characters purple. The problem is `/sendas` turns grey, and the character creation preview is grey.

The `ai4.png` constants defined in `./src/endpoints/characters.js` are irrelevant to persona avatar.

### Additional context

Persona's grey and separation from character is superior UI design than otherwise.

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
Done: #2863
