### ISSUE TITLE
[BUG] Issues with the Mistral Tokenizer

### ISSUE THREAD

**Issue by ghost** [SillyTavern/SillyTavern#2870]
### Environment

🐧 Linux

### System

N/A

### Version

SillyTavern 1.12.5 'staging' (38d24f4b)

### Describe the problem

Mistral's tokenizer is weird and we probably need a "Use system message" checkbox like we have with Claude.

The official Mistral tokenizer is here: https://github.com/mistralai/mistral-common

And we can use it to check how messages are formatted for chat completion, with code like this:

```python3
from mistral_common.protocol.instruct.messages import (
    UserMessage,
    SystemMessage,
    AssistantMessage
)
from mistral_common.protocol.instruct.request import ChatCompletionRequest
from mistral_common.tokens.tokenizers.mistral import MistralTokenizer

tokenizer = MistralTokenizer.v3(is_tekken=True)

tokenized = tokenizer.encode_chat_completion(
        ChatCompletionRequest(
            messages=[
                    SystemMessage(content="[System message]"),
                    UserMessage(content="[First user message]"),
                    AssistantMessage(content="[Assistant response]"),
                    UserMessage(content="[Second user message]"),
                ],
            model="nemostral",
        )
)

print(tokenized.text)
```

(just `pip install mistral-common`)

which will print out:

```
<s>[INST][First user message][/INST][Assistant response]</s>[INST][System message]

[Second user message][/INST]
```

As you can see, the system message is lowered all the way down to immediately before the most recent user message, despite being the first thing on the chat completion.

This is pretty bad for RP, in particular because, unless I'm mistaken, some ST fields are necessarily sent as System ({{char}} description, persona, etc).

So yeah, "Use system message" checkbox like we have with Claude/Gemini. That would probably help a lot. Just disable sysmessages entirely and move any relevant PHI in place by hand.

As a side note, the default text completion instruct format seems to be off from tokenizer outputs for me (although this may be a versioning issue). This is what it should be like:

[Mistral Context.json](https://github.com/user-attachments/files/17043279/Mistral.Context.json)
[Mistral Instruct.json](https://github.com/user-attachments/files/17043280/Mistral.Instruct.json)

Sorry if I'm wrong about something or creating any confusion.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
1. Text completion prompt builder does not necessarily translate well to prompts built by converting the chat completion prompt. Converting prompts using official jinja templates would likely lead to some features becoming unavailable: impersonation and continuation are not directly possible in the chat completion schema, also they often limit system messages to one per prompt or require user message being first, or strict alteration between the roles. This is not acceptable here as it hurts utility. To solve your problem, there's an instruct sequence for the **last user prefix** that could help if you move certain fields from the story string into it: either just a system prompt, or the entire story string content.
2. Mistral templates are ever so different from between the models. So you'd need to specify exactly the type of model this is being designed for. Yours would be "Mistral Nemo" if I understand correctly. The original could be renamed to "Mistral Legacy" or "Mistral Classic".

**Comment by ghost** [comment]
>Converting prompts using official jinja templates would likely lead to some features becoming unavailable: impersonation and continuation are not directly possible in the chat completion schema, also they often limit system messages to one per prompt or require user message being first, or strict alteration between the roles. This is not acceptable here as it hurts utility. To solve your problem, there's an instruct sequence for the last user prefix that could help if you move certain fields from the story string into it: either just a system prompt, or the entire story string content.

Oh no, I think I've explained it badly. I'm mostly just concerned with how chat completion for mistral currently sends a lot of stuff as system and this basically results in the entire card being dropped in as a PHI. I don't want you to somehow figure out how to do Mistral-style lowered system prompts in text completion mode.

>Mistral templates are ever so different from between the models. So you'd need to specify exactly the type of model this is being designed for. Yours would be "Mistral Nemo" if I understand correctly. The original could be renamed to "Mistral Legacy" or "Mistral Classic".

I've actually just checked and the mistral-common tokenizers v1 through v3-tekken use the `<s>` in the start of the text and the `</s>` at the end of assistant messages, so I'm not sure which model_ is the current Mistral Context for.

**Comment by Cohee1207** [comment]
So, this is an issue related to specifically chat completions and MistralAI integration?

**Comment by ghost** [comment]
It's kind of both issues at once tbqh. The chat completion has the lowering issue and the context/instruct defaults look broken to me.

**Comment by Cohee1207** [comment]
> so I'm not sure which model_ is the current Mistral Context for.

From your first message it's 100% Nemo `model="nemostral"`

**Comment by ghost** [comment]
>From your first message it's 100% Nemo model="nemostral"

No, no, I meant the ST default without the `<s>` at the start.

**Comment by Cohee1207** [comment]
The ST default was for Mistral 7B afaik.

**Comment by ghost** [comment]
```
from mistral_common.protocol.instruct.messages import (
    UserMessage,
    SystemMessage,
    AssistantMessage
)
from mistral_common.protocol.instruct.request import ChatCompletionRequest
from mistral_common.tokens.tokenizers.mistral import MistralTokenizer

tokenizer = MistralTokenizer.from_model("open-mistral-7b")

tokenized = tokenizer.encode_chat_completion(
        ChatCompletionRequest(
            messages=[
                    SystemMessage(content="[System message]"),
                    UserMessage(content="[First user message]"),
                    AssistantMessage(content="[Assistant response]"),
                    UserMessage(content="[Second user message]"),
                ],
            model="open-mistral-7b",
        )
)

print(tokenized.text)
```

prints out

```
<s>▁[INST]▁[System▁message]<0x0A><0x0A>[First▁user▁message]▁[/INST]▁[Assistant▁response]</s>▁[INST]▁[Second▁user▁message]▁[/INST]
```

with the `<s>` and the `</s>`. See: https://github.com/mistralai/mistral-common/blob/main/src/mistral_common/tokens/tokenizers/mistral.py#L103 to check that the model name is correct.

**Comment by ghost** [comment]
Honestly text completion instruct for mistral may be unsalvageable, I mostly just want the chat completion checkbox to turn all sysprompts into user a la Claude/Gemini.

**Comment by ghost** [comment]
I'm going to actually email a mistral employee and ask him about the `<s>`.

Meanwhile:
[Mistral Large Context.json](https://github.com/user-attachments/files/17045059/Mistral.Large.Context.json)
[Mistral Large Instruct.json](https://github.com/user-attachments/files/17045061/Mistral.Large.Instruct.json)
[Mistral Nemo Context.json](https://github.com/user-attachments/files/17045062/Mistral.Nemo.Context.json)
[Mistral Nemo Instruct.json](https://github.com/user-attachments/files/17045063/Mistral.Nemo.Instruct.json)

The Mistral Large assistant message prefix is intentionally a single space.

**Comment by ghost** [comment]
![Capture](https://github.com/user-attachments/assets/2ae234b8-1d64-42e3-9e2a-cc1b6cad2824)

The Mistral context on ST was always broken.

**Comment by NeoTU** [comment]
> Mistral's tokenizer is weird

This was posted 2 hours ago from a team member named Pandora of Mistral Huggingface group [here](https://huggingface.co/bartowski/Mistral-Small-Instruct-2409-GGUF/discussions/1#66ead61cc5b2c25450bdf8bc).

**Demystifying Mistral's Instruct Tokenization & Chat Templates**
https://github.com/mistralai/cookbook/blob/main/concept-deep-dive/tokenization/chat_templates.md

SillyTavern current Mistral tokenizer and Mistral Context/Instruct template won't serve both Nemo and Mistral Small/Large.

![Screenshot](https://github.com/user-attachments/assets/3a8c5ab9-9927-4567-8a99-9f24a8037336)

**Comment by ghost** [comment]
To summarize:

- ST chat completion mode needs the Claude/Gemini "use system prompt" checkbox because the sysprompt has a fixed position in the chat history (prepended to the last user message since Mistral's v2 Tokenizer) and this is awful for RP
- the current Mistral instruct/context presets aren't really formatted correctly for any Mistral model at all (see the cookbook NeoTu linked and/or play around with mistral-common)
- the presets I provided should work correctly and provide sane behavior for Large/Nemo but it'd be cool if someone else looked them over

**Comment by Cohee1207** [comment]
I'd also like to clarify the issue title and the linked post. For the frontend, there is no direct corellation between the tokenizer chosen and the prompt format, the only exception is when using logit bias that requires exact token ids. Sure, the choise tokenizer can influence the choice of the prompt format, but only when training the model, not when prompting it. I think this misunderstanding comes from the Python package providing prompt formatting capabilities in the tokenizer object, which is semantically confusing. This is really just a jinja template [(here it is)](https://huggingface.co/mistralai/Mistral-Nemo-Instruct-2407/blob/main/tokenizer_config.json#L8008).

So, those are two distinct issues:

1. What is currently being shown as a "Mistral" tokenizer in ST's selection - is a _sentencepiece_ tokenizer taken directly from Mistral 7B's files. Adding a separate Nemo (tekken or equivalent) tokenizer is possible too, but only for two points: correct logit bias calculation, and more accurate token counting when building the prompt. This is only relevant for the backends that do not offer an endpoint for tokenizing directly with the model's own tokenizer.

2. We're not using the chat templates suggested by the model for formatting the prompt in the text completion mode. Instruct mode with proper settings can give a good enough approximation without sacrificing any of the frontend features. This is most critical and what really should be taken as an action item.

The problem with chat completion using the system role for the character card bits is a general SillyTavern's prompt builder limitation, not only for Mistral. This shouldn't be a big deal to allow changing roles on individual prompt bits. Keep in mind, that chat completion does not use instruct settings at all. This is the part when we let the backend do the prompt formatting, and is the actual biggest difference between the two modes, beside the UI for prompt builder configurations.

**Comment by ghost** [comment]
>The problem with chat completion using the system role for the character card bits is a general SillyTavern's prompt builder limitation, not only for Mistral. This shouldn't be a big deal to allow changing roles on individual prompt bits.

IMO that would help but it wouldn't really be an ideal solution because it'd interact funny with card author notes and lorebooks etc etc. Just the checkbox that gives us the Claude/Gemini system-to-user conversion would be perfect.

Honestly from now on whenever I use Mistral I'm pretty much just going to pretend it doesn't have system messages at all, and I don't really see a reason to do anything else.

**Comment by Cohee1207** [comment]
A model-exclusive solution is not a good solution as it benefits a very small group while offering nothing to the others. In ST we have to deal with 15+ backends and treat every single one equally. That's why I avoided adding a separate prefill box for Mistral. Not that it's impossible, but it creates an artifical separation between the backends while a working alternative (creating a Relative prompt injection in the Assistant role) exist.

**Comment by ghost** [comment]
![image_2024-09-18_135826119](https://github.com/user-attachments/assets/a5917fdd-c935-4b52-aef2-a32ee55df11c)

I mean you could add this to every single chat completion model as a preprocessing option. It's already sort of there for custom openai, no? It's a very mistral-specific issue tbqh, I don't think any other model has this completely insane behavior for system messages.

**Comment by Cohee1207** [comment]
> It's already sort of there for custom openai, no? 

Honestly, I don't even remember why is it there, but it definitely has some problems, like it butchers the image inlining when used, so I was thinking of removing it in favor of other alternatives if this very processing is strictly required.

**Comment by ghost** [comment]
>so I was thinking of removing it in favor of other alternatives if this very processing is strictly required.

Grim.

It's pretty much strictly required in this case IMO. Up to 2k tokens of accidental PHI unless you manually mangle a monolithic user prompt. Honestly if you didn't add the checkbox and instead just always turned all sysmessages into user messages I don't think anyone could really complain, since you CAN produce the exact same text completions with a bit of fiddling.

Case in point:
```python3
from mistral_common.protocol.instruct.messages import (
    UserMessage,
    SystemMessage,
    AssistantMessage
)
from mistral_common.protocol.instruct.request import ChatCompletionRequest
from mistral_common.tokens.tokenizers.mistral import MistralTokenizer

tokenizer = MistralTokenizer.v3(is_tekken=True)

tokenized_1 = tokenizer.encode_chat_completion(
        ChatCompletionRequest(
            messages=[
                    SystemMessage(content="This is a system message"),
                    UserMessage(content="This is a user message"),
                ],
            model="nemostral",
        )
)

tokenized_2 = tokenizer.encode_chat_completion(
        ChatCompletionRequest(
            messages=[
                    UserMessage(content="This is a system message\n\nThis is a user message"),
                ],
            model="nemostral",
        )
)

print(tokenized_1.text)
print("***")
print(tokenized_2.text)
```

Outputs:
```
<s>[INST]This is a system message

This is a user message[/INST]
***
<s>[INST]This is a system message

This is a user message[/INST]
```

so this would be pretty much going from an insane default to a much saner default.

**Comment by Cohee1207** [comment]
All done.

**Comment by ghost** [comment]
Wait, one second.

![image_2024-09-20_200936364](https://github.com/user-attachments/assets/2ae0d2f5-10e2-456f-97bd-b38f653118e9)

Why the Understood at the end?

Edit: should I move this to the already closed PR?

Edit 2: what you probably want to do is close off the story string with a text like "Please start the story for us based on the info above.[/INST]" (like a Story Start entry) and then let the greeting get plugged in immediately afterwards.

**Comment by Cohee1207** [comment]
> Why the Understood at the end?

Because it has a user filler in the instruct.

**Comment by ghost** [comment]
>Because it has a user filler in the instruct.

Ah. I just removed that part from my own instruct to be entirely honest. Less awkward.

**Comment by Cohee1207** [comment]
Just take a look at the fully formed prompt to undestand it better.
```txt
 [INST] Write Assistant's next reply in this fictional roleplay with Momiji. [/INST] Understood.</s> [INST] Momiji: Let's get started. Please respond based on the information and instructions provided above. [/INST] Assistant: Hello</s> [INST] Momiji: Hi [/INST] Assistant:
```

**Comment by ghost** [comment]
I get it and I don't see why you'd want to start the RP with an OOC message instead of using a "please start the story" instruction at the end of the sysprompt/story string.

**Comment by Cohee1207** [comment]
If you want to propose improvements - please open a new issue. I consider this one done.
