### ISSUE TITLE
[BUG] Deprecated npm packages warning

### ISSUE THREAD

**Issue by Solomon1732** [SillyTavern/SillyTavern#2876]
### Environment

🪟 Windows

### System

Brave 1.69.168

### Version

1.12.5

### Desktop Information

- Node.js: v22.9.0
- Generation API: AIHorde
- Branch: release

### Describe the problem

When I launch SillyTavern, I get the following two warnings:
> npm warn deprecated @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead

I expect to see no such warnings.

### Additional info

I attached the console log just in case.
[127.0.0.1-1726755055687.log](https://github.com/user-attachments/files/17060873/127.0.0.1-1726755055687.log)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
`@eslint` is a development package and should not be installed in normal circumstances (unless you want to contribute). The recommended startup script specifically omits dev packages, see here:
https://github.com/SillyTavern/SillyTavern/blob/15363a8d69cf83d84d8cb2e5f1c70216353f7782/Start.bat#L4

**Comment by Solomon1732** [comment]
~~I thought I installed the release branch through the launcher scripts. If this may be false, how do I reinstall ST as the release branch?~~

~~Edit: Also, how do I backup the chat files (and persona and characters and so forth)?~~

Edit 2: Never mind, I got help elsewhere.

**Comment by Cohee1207** [comment]
> I thought I installed the release branch through the launcher scripts. If this may be false, how do I reinstall ST as the release branch?

I pushed similar changes to the launcher script, hopefully to get merged soon.
