### ISSUE TITLE
[BUG] Cannot connect to custom API provider

### ISSUE THREAD

**Issue by KingXMAX** [SillyTavern/SillyTavern#2877]
### Environment

🪟 Windows

### System

Windows 10

### Version

1.12.5

### Describe the problem

I have a valid API key from NotDiamond AI platform and its compatible with OpenAI, but whenever i open Silly Tavern's Custom Connection menu in Chat Completion section and input the base URL and my API key and hit "Connect", i always get a "Not Found" Error, even though the same link works in the browser and gives "Welcome to Not Diamond API" message. Here is the Endpoint URL (Base URL): https://api.notdiamond.ai/
And here is the URL they mention in their documentation:
https://api.notdiamond.ai/v1/chat/completions
So, how can i successfully connect to that API? How to solve the "Not Found" issue?
Thanks in advance

### Additional info

This is not the first time i get a "Not Found" Error when using custom connections in Silly Tavern. I noticed that many custom API providers cannot be recognized by ST while they work normally with other front-end software.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Add `/v1` at the end.

**Comment by KingXMAX** [comment]
Added, the URL: https://api.notdiamond.ai/v1/ still returns "Not Found" both in browser and in ST.

**Comment by Cohee1207** [comment]
Can I ask a link to the doc where you saw it being compatible? None of the compatible endpoints are listed in the API reference. Also see this: #2764, this API has no use for any of the frontends, it provides no generation capabilities.

https://notdiamond.readme.io/reference/api-introduction

**Comment by KingXMAX** [comment]
Then how it works on other platforms like RisuAi and JanitorAi? And does it mean that there is no way to use it in Silly Tavern?

**Comment by Cohee1207** [comment]
Any evidence or relevant documentation?

Here what I got by entering this endpoint to RisuAI, getting a familiar message.

<img width="226" alt="image" src="https://github.com/user-attachments/assets/c34606d0-9d5d-4f29-a1bd-3b36751c8591">

**Comment by KingXMAX** [comment]
You should've added the ability to connect to those custom API providers regardless, go fix that trash ST app. BYE!

**Comment by Cohee1207** [comment]
The ability to connect custom endpoints exists and works consistently as confirmed by many other users.

You can check that by supplying a REAL OpenAI endpoint URL and a working legitimate API key. What you have linked is not a compatible endpoint and there is no supporting evidence that it is compatible with anything.
