### ISSUE TITLE
[BUG] Mobile ST screen issues

### ISSUE THREAD

**Issue by BRAIN-IS-BACK** [SillyTavern/SillyTavern#2879]
### Environment

📱 Termux

### System

Google Chrome latest version

### Version

SillyTavern 1.12.5 'staging' (1819604f)

### Desktop Information

latest Node.js version, and SillyTavern 1.12.5 'staging' (1819604f)

### Describe the problem

Since I don't know when, just typing a chat on ST mobile causes the screen on ST to move up like this. The more chats I type, the more it pushes up, and once it does, it stays there unless I refresh the page.

To be more precise, if I don't tilt my phone, there's no problem, but the moment I tilt my phone vertically to write a chat for convenient typing, the ST screen immediately slides up.

I was using the G-Board keyboard for English translation even before this happened, and I used another keyboard for cross-validation and confirmed that the same geometry still occurs. So it's not a keyboard issue, at least not for writing letters.

![1726804001918_2024 09 20_screencatch](https://github.com/user-attachments/assets/a386a4f9-7b71-40c6-a2d2-7a6c8d38c688)
![1726803986362_2024 09 20_screencatch](https://github.com/user-attachments/assets/20ba34e9-6196-4a7e-88f6-c3c1646a6bcb)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Consider the following: #2881
