### ISSUE TITLE
[BUG] <an error when generating images through QR>

### ISSUE THREAD

**Issue by DysAnia1013** [SillyTavern/SillyTavern#2885]
### Environment

📱 Termux

### System

5.4.0-174-generic

### Version

1.12.5 'staging' (125498cf)

### Describe the problem

My QR is as follows:

> /flushinjects |
Above are Chinese information contents, translate those in English and use it.|
/profile lowtemp-GPT |
/sd last |
/echo 生成中…… |
/profile maozi6.0 |
/echo 生成完成 |

——————————————————————————————————————
Before today's update, my quick reply had been working normally, but after today's update, using it again would result in an error:

>SD prompt text generation failed. Reason: Error: Prompt generation failed:
 Line: 3 Column: 1
1:   Above are Chinese information contents, translate those in English and use it.|
2:  /profile lowtemp-GPT |
3:  /sd last 
^^^^^

——————————————————————————————————————
Later on, I tried many times and found that only by placing 'sd last' on the first line would there be no error. Since this error has never occurred before, I believe it is a bug. If I have done anything wrong, please let me know. Thank you very much for your hard work.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Your backend has failed to produce any usable text for the SD prompt.

**Comment by DysAnia1013** [comment]
But when I manually switch the profile and enter "/sd last", the image can be generated normally. Does this mean that the proxy I am using can generate tag prompts normally?
I tried many times today, Claude sometimes reported errors and sometimes generated normally, GPT 100% reported errors and could only be manually generated without using quick reply.
If this is my proxy problem, sorry to bother you, I will close this issue.

**Comment by Cohee1207** [comment]
We do not provide any kind of support for proxy users.
