### ISSUE TITLE
[BUG] My comfyui resolutions are getting altered randomly.

### ISSUE THREAD

**Issue by Ph0rk0z** [SillyTavern/SillyTavern#2888]
### Environment

🐧 Linux

### System

chrome/firefox

### Version

git-staging

### Desktop Information

Any backend, ComfyUI sillytavern

### Describe the problem

I recently made a new comfy workflow for SD/SDXL. Coming off of flux, I played with the resolutions. Usually I gen 576x768. This time the gens were taking longer. 

Have the metadata plugin installed and looked at the images. They become 576x960 or when doing 768x768, it changes to 768x1xxx. Made sure the snap resolutions was unchecked, tried it checked. Same behavior. Was not 100% consistent either.

Thinking that it's the workflow, I hard set the width and height. Now images were the resolution I set.

Also the comfy page has highres fix and restore faces checkboxes which comfy workflows do not support. Perhaps something got bugged in a recent commit?

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
"Face" and "background" generation model alter the width/height set to force portrait/background resolutions respectively. This is not recent and worked like this since the very beginning.

**Comment by Ph0rk0z** [comment]
I was using flux and it never strayed when I did face. Those were all 576x768 for speed. Maybe it got fixed and suddenly started working. Would be cool to turn this on or off. Especially in place of the non functioning checkboxes.

**Comment by Cohee1207** [comment]
That is an option, yes. Will take into consdieration.

By the way, all of the checkboxes there work. Maybe "Auto-extend prompts" doesn't work as good as to be expected, but they all are functional. If you have questions about any of them - ask.

**Comment by Ph0rk0z** [comment]
What will highres fix and restore faces do in a comfy workflow? I don't have any nodes related to that.

**Comment by Cohee1207** [comment]
Great point. They're hidden now 👍

**Comment by Ph0rk0z** [comment]
Thanks. I guess I will have to mind the face thing or re-purpose another unused preset as non-res altering face. On SD w/lightinging it's not bad. But for flux to suddenly jump resolutions it will slow things down.
