### ISSUE TITLE
Expressions don't show up in single chat

### ISSUE THREAD

**Issue by Mark91-91** [SillyTavern/SillyTavern#2893]
### Environment

🪟 Windows

### System

Windows 10

### Version

1.9.7 but I tried also 1.12.5

### Describe the problem

In VNmode expressions don't show up in single chats unless I set them manually. In group chats they automatically appear. 

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
What API source do you use for expressions?

**Comment by Mark91-91** [comment]
![2](https://github.com/user-attachments/assets/3ce3987f-7b29-4ded-9423-7a9816f16079)
![3](https://github.com/user-attachments/assets/5b523183-104b-4610-9897-75433562d80f)
![Cattura](https://github.com/user-attachments/assets/f0516a84-c15b-47e9-8604-0a1e2d1e6986)

I'm not sure what you refer since I'm just getting started with silly, sorry :') however these are my screenshots. Characters img folders seem correctly detected and all characters appear in "Group Chats" (they appear also if I turn a single chat in a group one), but if I just start a single chat no character shows up... I can't understand. If you need more just tell me and I'll try to provide every info

**Comment by Cohee1207** [comment]
1.9.7 doesn't have a support for local classification and is a dead version (released more than a year ago).

And I genuinely suggest to reconsider a choice of the model, Pygmalion 7B is ancient too (and not very good). Please seek more modern alternatives based on Llama 3 or Mistral.

Read the docs on how to enable local classification in **supported** versions: https://docs.sillytavern.app/extensions/expression-images/#setup-instructions-local-classification

P.S. You would have to switch to KoboldCpp under Text Completion in the new version to get support of token streaming and modern samplers.

**Comment by Mark91-91** [comment]
Thank you! I followed the guide and I'm using ST 1.12.5 and expressions works now! I'll search a different model too
