### ISSUE TITLE
[BUG] Migration ate my system prompts.

### ISSUE THREAD

**Issue by Ph0rk0z** [SillyTavern/SillyTavern#2900]
### Environment

🐧 Linux

### System

chrome/firefox

### Version

git-staging

### Desktop Information

node on arch

### Describe the problem

I pulled and assumed the migration would be flawless like everything else. ST loaded up and updated my extensions after I refreshed it. At first it seemed like most of my system prompts got moved. Then I looked more carefully.

About 31/67 moved with the title of [migrated]. It was luckily all of my chatML templates, so my most recent ones. When it hit command-R it got stuck. Possibly because it was using the ## separators as CR+ says to use. It only got the first one and proceeded no further. Unfortunately it continued through all my other instruct templates and deleted the system prompts.

I looked through backups to no avail. It's permanent. Now I got a bunch of duplicated instructs that mainly differed by system prompt. I started using gemini before I noticed and the log scrolled away.

If you're on staging, beware and copy the folder.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Have you tried checking for non-migrated instructs in `/data/default-user/instruct`? They should have a `system_prompt` field in it.

**Comment by Cohee1207** [comment]
If you notice it being present in some files and you want to attempt the start migration again - delete the `.migrated` file in `/data/default-user/sysprompt`, then restart the server.

Also, the prompts are not migrated if they duplicate any of the default prompts to prevent lots of duplicated files.

**Comment by Cohee1207** [comment]
One more thing - the migration deduplicates sysprompts, so if you had 70 instructs where 30 of them had duplicate sysprompts, only 40 would be left. I think that's why you experienced the following: "It only got the first one and proceeded no further"

**Comment by Ph0rk0z** [comment]
The defaults were definitely not duplicated. The system prompts that were named command-r guides were unique because they had the safety preamble and ## fields like the CR+ prompting guide. It stopped at the first one. Some prompts were duplicates of themselves and it actually moved those so I have to go through them all.

I looked inside the templates that were not moved and they are all missing the system prompt field. All files in that folder were touched on the day I pulled. It simply got to a certain point and gave up on copying the sysprompt or there was an error I never got to see.

**Comment by Cohee1207** [comment]
Somehow I missed the point about auto-backups this time, sorry.
If you have saved prompt itemizations in your past chats, you can restore system prompts from there.

**Comment by Ph0rk0z** [comment]
Thanks. Will at least help other people avoiding the same fate. I tried to look back through chatlogs at a very surface level and they only seem to store the messages.

**Comment by Cohee1207** [comment]
"Prompt Itemization" is a message context action that appears on the AI response when you send a prompt, containing a tokenizer breakdown and the full prompt snapshot.

**Comment by Ph0rk0z** [comment]
Well.. the only place I'm finding prompts is in settings backups. In the chats themselves there is nothing but chats. So I will scour those.
