### ISSUE TITLE
[BUG] <title> Node_modules? something else?

### ISSUE THREAD

**Issue by The-HOLLOW-Idiot** [SillyTavern/SillyTavern#2909]
### Environment

🪟 Windows

### System

Windows 11

### Version

1.12.6

### Describe the problem

Got an error after updating an older vers of sillytavern, decided to uninstall then reinstall it, after the fresh reinstall I've been trying to launch silly tavern through the launcher and keep getting an error regarding Node_modules? It changes whenever I try launching it, I've removed the Node_modules folder through the launcher a few times and still get this error often, I have no idea why this is happening or if someone else has had this issue as I dont know exactly where to look here or in the Doc. If you guys need more information Ill happily share it, however youll probably have to guide me though to getting that info as Im not that bright.

### Additional info

Image of the console outputting the error
![image](https://github.com/user-attachments/assets/882ea21a-2f7a-434d-aba9-625238f49c39)

Log of error:
[2024-09-27T15_50_42_391Z-debug-0.log](https://github.com/user-attachments/files/17167113/2024-09-27T15_50_42_391Z-debug-0.log)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Please move launcher questions to https://github.com/SillyTavern/SillyTavern-Launcher/

This repo is only for issues with the program itself.
