### ISSUE TITLE
[Question] how to add character specific prompts to /sd?

### ISSUE THREAD

**Issue by Ph0rk0z** [SillyTavern/SillyTavern#2946]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

I have a QR that automatically makes images when the AI uses "sends a picture that contains". It pipes the prompt into /sd and I get nice AI initiated pictures. Unfortunately I've found that it doesn't add the character prefix or loras to the output.

Is there a macro for those so I can add it to the prompt automatically? If you use /sd face, it has it. 

Let's say the character is ganyu; /sd face makes ganyu with loras and all, /sd "prompt" just uses the raw prompt + the main sd string from the dropdown. Something like "ganyu smiling" would give you whatever the image model thinks it is.

### Describe the solution you'd like

figure out how to do it. or if it's impossible.

### Describe alternatives you've considered

finding a macro?

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
Try this:
1. Pull https://github.com/SillyTavern/SillyTavern/commit/10f51f5d9078ff19cc6480430321aa23c742f686
2. Replace `{{prompt}}` with `{{prefixedPrompt}}` in the Image Prompt Templates => Chat Message Template

**Comment by Ph0rk0z** [comment]
I probably explained this badly, that will only show it in the messages coming back but with /sd it still won't use it, unless I'm not reading this right either.

Here is how the tool does it's thing for the AI.

![script](https://github.com/user-attachments/assets/681a808f-b9a6-4544-afc8-a2085c7d930e)

**Comment by Cohee1207** [comment]
That should be it, however. Chat Message Template is for messages that get posted into the chat on `/sd`.

**Comment by Ph0rk0z** [comment]
I tried it and no character lora appeared in what was sent to comfyui. It pulls the prompt from the message and adds the main SD template which has the lightning lora but not everything in the character box.

**Comment by Cohee1207** [comment]
I think I get it now (sorta). Try the `{{charPrefix}}` macro. It is replaced with the specific prefix on /sd free mode generations.

**Comment by Ph0rk0z** [comment]
ok, will try to add it to my script and see what I get.

**Comment by Ph0rk0z** [comment]
Thanks, using that has worked. Char specific stuff gets added to the prompt of the image gen tool.
