### ISSUE TITLE
[FEATURE_REQUEST] Trusted Header Auth

### ISSUE THREAD

**Issue by QuantumEntangledAndy** [SillyTavern/SillyTavern#2948]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

I use a reverse proxy to handle authentication and SSL termination. The authentication can securely provide authentication details into the header request, (while also handling all sorts of auth details like password resets and 2fa). I would like to implement this method into sillytavern multi user, so that this SSO can be used for the auth without requiring a second SillyTavern login

### Describe the solution you'd like

Details of the headers are [here](https://www.authelia.com/integration/trusted-header-sso/introduction/) would mostly just need to make this a configurable login option, that can select the header that has the username

### Additional context

I can write up the code and test it myself, I just wanted to see it there was any wider interest here to release it publicly back into SillyTavern

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by chanamx** [comment]
Support it

**Comment by QuantumEntangledAndy** [comment]
PR in #2953

**Comment by QuantumEntangledAndy** [comment]
Added in #2953
