### ISSUE TITLE
[BUG] Selected world info makes the story context glitchy

### ISSUE THREAD

**Issue by Teashrock** [SillyTavern/SillyTavern#296]
**Describe the bug**
I have updated SillyTavern from 1.4.9 to 1.5.1. I have exported all my settings, chats, characters, and world info as they are, with no changes. Then, I've tried to create a new group chat with some two characters I've been using before. But I was disappointed, as the characters' behaviour was very different from how they behaved on their 1.4.9 chat. Instead of roleplaying their predefined personalities, they started to behave as if this were a chat application. They also seem to completely ignore what is said in their first messages and in previous messages at all. The above info is also seems to be correct for chatting with one character.

**To Reproduce**
1. Go to Character list
2. Create a group chat with some characters or a classic 1-to-1 chat.
3. Try to chat a bit.
4. See pretty dumb behaviour.

**Expected behavior**
A normal roleplay as it has been on 1.4.9.

**Screenshots**
![Screenshot_20230513_155746_Chrome](https://github.com/Cohee1207/SillyTavern/assets/12483854/abc7c91d-be8f-4d83-a085-ede1729caab6)
![Screenshot_20230513_155820_Chrome](https://github.com/Cohee1207/SillyTavern/assets/12483854/95a85e58-95ab-4f18-8d60-74098cc2bd70)

It can be seen on the above screenshots that the character has ignored everything written in the first message including even the style.

**Logs**

I've tried to continue an old chat with another character, and got this in the logs:

![Screenshot_20230513_162819_Termux](https://github.com/Cohee1207/SillyTavern/assets/12483854/6c74fd4a-6b6c-45d7-988d-d615f6ba9135)

Why in the world is "[Start a new chat]" here? The chat is not a new, it is already developed for a ton of messages. Will it always be like this now?

Thank you in advance.

**Comment by Teashrock** [comment]
@Cohee1207 
Yes, I'm using my usual OpenAI token. Also, I'm running on Termux.

**Comment by Teashrock** [comment]
It's not just the AI ignoring the context and the memory, but the message quality is also like I'm using KoboldAI (though OpenAI is selected in the Connection tab.

**Comment by Teashrock** [comment]
@Cohee1207 
Okay, I'll try to assemble these.

**Comment by Teashrock** [comment]
@Cohee1207 
Here it is. Please tell me if I'm missing something.

[Bug.zip](https://github.com/Cohee1207/SillyTavern/files/11470053/Bug.zip)

**Comment by Teashrock** [comment]
@Cohee1207 
Here it is. Please tell me if I missed something.

[Bug.zip](https://github.com/Cohee1207/SillyTavern/files/11470061/Bug.zip)

**Comment by Andrey36652** [comment]
May be related https://github.com/Cohee1207/SillyTavern/issues/317

**Comment by Teashrock** [comment]
Closing due to not being able to reproduce the bug in the latest version. I may reopen it in future in case if the bug reappears.

**Comment by Teashrock** [comment]
@Cohee1207 
The bug is still there, but I have new information about it. It seems that SillyTavern forgets to insert the first user message into the context. It happens whenever any world info other than None is selected. When the world info is None, it forgets nothing.

**Comment by Teashrock** [comment]
The bug is now absent, so I'm closing this. May reopen in some distant future if the bug returns.
