### ISSUE TITLE
[BUG] Gemini 1.5 Flash, 1.5 Pro and Pro 002: Cut off responses and repetitions on SillyTavern (Windows)

### ISSUE THREAD

**Issue by KingXMAX** [SillyTavern/SillyTavern#2961]
### Environment

🪟 Windows

### System

Windows 10

### Version

1.12.6

### Describe the problem

I use the models specified in the title, and in the last couple of days, i notice that Gemini gives cut-off responses most of the time, and even when the response is complete, it repeats the last two or three lines of the response. I adjusted my prompt not to repeat responses and i optimized the parameters but the problem persists. I tried it on another app (RisuAI) with the same prompt and the same parameters, and i notice that Risu gives no cut-offs, and no repetitions, which means there IS something wrong with Silly Tavern itself.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Let's keep communications in one place: #2960, as I think it's the same issue.

UPD: Fixed the link
