### ISSUE TITLE
[FEATURE_REQUEST] Don't crop the image

### ISSUE THREAD

**Issue by EugeoSynthesisThirtyTwo** [SillyTavern/SillyTavern#2966]
### Have you searched for similar requests?

Yes

### Describe the solution you'd like

When I create a character and import a profile picture for the character, it always requests me to crop the image to a predefined ratio that I don't like. Can't I have square image ? Or an option not to crop the image ?
Thank you.

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

None

**Comment by Cohee1207** [comment]
This feature is already available. You can skip the crop by enabling "Never resize avatars" under User Settings.

**Comment by EugeoSynthesisThirtyTwo** [comment]
Thank you!
