### ISSUE TITLE
[Feature Request] <Performance Mode>

### ISSUE THREAD

**Issue by qw1642190428** [SillyTavern/SillyTavern#2986]
### Have you searched for similar requests?

No

### Is your feature request related to a problem? If so, please describe.

Is it time to add a performance mode? Now the tavern has more and more functions, but it is also getting more and more laggy.

### Describe the solution you'd like

Added performance mode, allowing the Tavern to use more system resources to process content

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

None

**Comment by qw1642190428** [comment]
I am not the only one. Many people will experience lags when deploying the tavern locally or on a server.

**Comment by Cohee1207** [comment]
Follow the steps from a readme: https://github.com/SillyTavern/SillyTavern?tab=readme-ov-file#performance-issues
