### ISSUE TITLE
[BUG] <title>Visual Novel Mode

### ISSUE THREAD

**Issue by 1015g** [SillyTavern/SillyTavern#3010]
### Environment

🪟 Windows

### System

Windows 10 22H2 19045.5011 &Microsoft Edge130.0.2849.52

### Version

SillyTavern 1.12.6 'release' (ba6f7b7a9)

### Desktop Information

After the user settings ticked the visual novel mode, no images appeared, but the chat box was properly zoomed in

### Describe the problem

![000001](https://github.com/user-attachments/assets/7398d416-b1b6-4206-8fdf-4aa78c2d9431)
![000002](https://github.com/user-attachments/assets/34effb46-ec70-4b30-8513-5f48b580184a)
![000003](https://github.com/user-attachments/assets/72a94c55-8c3d-4af8-80c9-629ef32efcf1)
![000004](https://github.com/user-attachments/assets/4ebe769e-a5df-4388-8984-3a2832d29003)
![000005](https://github.com/user-attachments/assets/931145c1-9599-4e8e-95d0-1d76d1f58e8e)
![000006](https://github.com/user-attachments/assets/2ba01eb0-0e9b-42df-a829-af0c8c71204b)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by 1015g** [comment]
thanks

**Comment by Cohee1207** [comment]
Classifier API - Switch to Local. Related documentation: https://docs.sillytavern.app/extensions/expression-images/

**Comment by 1015g** [comment]
> 分类器 API - 切换到 Local。相关文档： https://docs.sillytavern.app/extensions/expression-images/

This will start a one-time download of the classification model from HuggingFace Hub (about ~100 Mb).Unfortunately, I did this, and the problem doesn't seem to be solved, please can you give me a specific address, I want to try to download it again to see if it works.If you can, it's a good idea to tell where to put it.

**Comment by Cohee1207** [comment]
https://huggingface.co/Cohee/distilbert-base-uncased-go-emotions-onnx

Put the files in `data/_cache/Cohee/distilbert-base-uncased-go-emotions-onnx`

**Comment by 1015g** [comment]
> https://huggingface.co/Cohee/distilbert-base-uncased-go-emotions-onnx
> 
> Put the files in `data/_cache/Cohee/distilbert-base-uncased-go-emotions-onnx`

Still won't work，
![000007](https://github.com/user-attachments/assets/2e9f4dc2-d494-49e8-bf8e-fb42132ebe56)
However, when I copied the file, I found that I didn't even have a Cohee directory, so I created it myself

**Comment by 1015g** [comment]
Oh,No!Who's going to help me!
