### ISSUE TITLE
[FEATURE_REQUEST] AntiSlop Sampler (Phrase Banning)

### ISSUE THREAD

**Issue by Abdulhanan535** [SillyTavern/SillyTavern#3014]
### Have you searched for similar requests?

No

### Is your feature request related to a problem? If so, please describe.

AI model are getting sloppy day by day, especially gemma and Mistral models.

https://github.com/sam-paech/antislop-sampler

### Describe the solution you'd like

Implementation of AntiSlop (Phrase Banning) sampler.

https://github.com/sam-paech/antislop-sampler

### Describe alternatives you've considered

None.

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
Out of scope. This has to be implemented on the backend side.
