### ISSUE TITLE
[BUG] llama.cpp does not generate

### ISSUE THREAD

**Issue by wooooyeahhhh** [SillyTavern/SillyTavern#3026]
### Environment

🪟 Windows

### System

Firefox 131.0.3

### Version

SillyTavern 1.12.7 'staging' (2030c2c71)

### Desktop Information

Branch - Staging
llama.cpp b3985

### Describe the problem

The llama.cpp logs will spam the following but no generation will occur:

request: POST /tokenize 127.0.0.1 200
request: POST /tokenize 127.0.0.1 200
request: POST /tokenize 127.0.0.1 200
request: POST /tokenize 127.0.0.1 200
request: POST /tokenize 127.0.0.1 200
request: POST /tokenize 127.0.0.1 200

I believe this is because the current implementation of the Dry sampler is not functional

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Pull this and try again

https://github.com/SillyTavern/SillyTavern/commit/542f77aeb819fced598c54e2c581460dee3906b1

**Comment by DoubleBarreledShotgun** [comment]
https://github.com/SillyTavern/SillyTavern/commit/542f77aeb819fced598c54e2c581460dee3906b1 worked for me thanks (error was dry_sequence_breakers must be a non-empty array of strings)

**Comment by wooooyeahhhh** [comment]
Seems to work now, thanks.

**Comment by SimplyCorbett** [comment]
Doesn't work for me :(
