### ISSUE TITLE
[BUG] RAG: Cannot set llamacpp server backend

### ISSUE THREAD

**Issue by SimplyCorbett** [SillyTavern/SillyTavern#3034]
### Environment

🐧 Linux

### System

Debian 12

### Version

1.12.7

### Desktop Information

Node: 22.4.1
Backend: LLamacpp & LM Studio

### Describe the problem

I am trying to set the llamacpp server backend URL for RAG (just for RAG) and use LM Studio as the primary backend for chat.

I cannot find the location to set llamacpp for RAG while maintaining the connection to LM Studio. There only appears to be an option for one API backend.

Use case: Llamacpp is run locally on a nvidia GPU while LM Studio is run on a different LAN server. Unfortunately, the single-threaded nature of local transformers for RAG is problematic in silly tavern.

I have checked the docs and cannot find this information. But perhaps I'm just an idiot.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
1. Text Completion => llama.cpp API type => set llama.cpp server URL
2. Text Completion => Default API type => set LM Studio server URL
3. Don't switch the Text Completion API type
4. Vector Storage => llama.cpp source

Alternatively, use Ollama as a fast and cheap local option for embeddings.

**Comment by SimplyCorbett** [comment]
That works. However, I'm running into issues where it's rejecting files because the context and batch size is too low on llamacpp. And when I crank those settings up the computer hard freezes.

It's.. interesting. User error, probably.

I did notice that when using (local) transformers as the option, if I attach a file directly to the chat it can extract the data on the main instance backend without an embedding model. And by that I mean it works on the remote server with the Nvidia GPU.

Is there a reason we need a separate backend/model for vectorization?

I will check into Ollama as well.

**Comment by Cohee1207** [comment]
> Is there a reason we need a separate backend/model for vectorization?

Because almost no backends can do both. And vice versa, some vectorization backends don't do text generation.
