### ISSUE TITLE
[BUG] `/max {{pipe}}` command doesn't work

### ISSUE THREAD

**Issue by soboruB** [SillyTavern/SillyTavern#3043]
### Environment

🪟 Windows

### System

Fire fox, Chrome

### Version

1.12.7 release

### Describe the problem

This works properly (Result: 1) :
```
/let x 1 |
/max {{pipe}} |
/echo |
```

This works fine. (Result: 2) :
```
/max 1 2 |
/echo
```

This doesn't work. (Result: 0) :
```
/let x 1 2 |
/max {{pipe}} |
/echo |
```

This doesn't work. (Result: 0) :
```
/let x 1 2 |
/max {{var::x}} |
/echo |
```

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
All your test cases should now pass since https://github.com/SillyTavern/SillyTavern/commit/c8a28137e0ffab3d62be45205bde011ffe40f91b
