### ISSUE TITLE
[BUG] DRY: Cannot use text completion (but can use chat competition)

### ISSUE THREAD

**Issue by SimplyCorbett** [SillyTavern/SillyTavern#3048]
### Environment

🐧 Linux

### System

Gentoo x86_64 with Nvidia

### Version

1.12.7

### Desktop Information

v22.4.1 nodes
1.12.7 SillyTavern
b4033 Llamacpp

### Describe the problem

When running 1.12.7 Sillytavern with Llama.cpp b4033, with Qwen 2.5 14b q4_0 gguf and --cache-type-k q8_0 and --cache-type-v q5_0, SillyTavern refuses to work with text completion, but will work with chat competition.

Example error:

{"error":{"code":400,"message":"Error: dry_sequence_breakers must be a non-empty array of strings","type":"invalid_request_error"}}

This is with a default installation and DRY multiplier set to 0.

### Additional info

.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Try switching to staging branch.

**Comment by SimplyCorbett** [comment]
I imported the changes on https://github.com/SillyTavern/SillyTavern/commit/a3ca407b2714df5af5a9f83aa925fd64fb778e24 which did not fix the issue.

I haven't tried staging though, would there be a different outcome?

**Comment by SimplyCorbett** [comment]
This is not fixed in the staging branch.

**Comment by Cohee1207** [comment]
I'm not able to reproduce. I'm on the latest pull of llama.cpp main and SillyTavern staging.

**Comment by SimplyCorbett** [comment]
I am using the OpenAI custom option, and I am not using /v1 at the end of the url. I am also using an api key.

when I’m home tomorrow I’ll toss my build info your way, but I’m just compiling llamacpp with cuda, openblas and all k,v quant cache types.

**Comment by SimplyCorbett** [comment]
Right, so I am building llamacpp like so:

`cmake -B build -DBLAS_INCLUDE_DIRS=/usr/include/openblas -DLLAMA_BLAS=ON -DLLAMA_BLAS_VENDOR=OpenBLAS -DGGML_CUDA=ON -DGGML_CUDA_FA_ALL_QUANTS=true`

and

`cmake --build build --config Release`

I use the source code provided under the releases page (I do not use git clone).

I run llamacpp on Fedora 41, and I use sillytavern on debian 12.

I am not sure why dry isn't working..

**Comment by frenzybiscuit** [comment]
Still broken in the latest sillytavern on Qwen 2.5.

**Comment by Cohee1207** [comment]
Running SillyTavern from release: https://github.com/SillyTavern/SillyTavern/commit/8ef49b40b230a50b70a92d1eee245f76978efbb9

Compiled llama.cpp from this commit: https://github.com/ggerganov/llama.cpp/commit/cc98896db858df7aa40d0e16a505883ef196a482

Running this quant: https://huggingface.co/Qwen/Qwen2.5-Coder-7B-Instruct-GGUF/blob/main/qwen2.5-coder-7b-instruct-q4_k_m.gguf

With the following payload related to DRY:
```
  dry_allowed_length: 2,
  dry_multiplier: 0,
  dry_base: 1.75,
  dry_sequence_breakers: [ '\n', ':', '"', '*' ],
  dry_penalty_last_n: 0,
```

Couldn't encounter this issue. Same when multiplier is set to 0.7.

**Comment by Cohee1207** [comment]
But I think I understood where the problem is. It probably doesn't like the DRY array being empty if you remove every default string from it. Try pulling this: https://github.com/SillyTavern/SillyTavern/commit/e6be28acea70ea6899f415d51aa8d78848909206

**Comment by frenzybiscuit** [comment]
No, same bug.

Also the dry array isnt empty and the default string is there.

`["\n", ":", "\"", "*"]`

**Comment by frenzybiscuit** [comment]
```
API Error
{"error":{"code":400,"message":"Error: dry_sequence_breakers must be a non-empty array of strings","type":"invalid_request_error"}}
```

**Comment by frenzybiscuit** [comment]
Interestingly, llama.cpp backend does work with the changed file you linked. Its just the OpenAI backend that does not.

This is a problem for me because I use vector storage with llamacpp as the backend. I dont think I can use two different llamacpp backends at the same time?

**Comment by Cohee1207** [comment]
Can you clarify what are llama.cpp backend and OpenAI backend? You mean text completion and chat completion endpoints?
Or those are distinct llama executables? You just start `llama-server`?

**Comment by frenzybiscuit** [comment]
No, I mean on sillytavern you can pick llama.cpp as the backend along with OpenAI compatible.

The OpenAI compatible doesn't let you use chat competition if the backend is llama.cpp.

However, the llamacpp backend option works fine.

This wouldn't be a problem, accept I can't use llamacpp as the chat backend because I'm using it as the vectorization backend.

**Comment by frenzybiscuit** [comment]
<img width="955" alt="Screenshot 2024-12-04 at 2 17 34 AM" src="https://github.com/user-attachments/assets/2f8a5d58-af87-4fcf-8ae5-396220377363">
<img width="911" alt="Screenshot 2024-12-04 at 2 18 15 AM" src="https://github.com/user-attachments/assets/023fb345-395b-4dc6-aece-d9e88bb525d1">
<img width="587" alt="Screenshot 2024-12-04 at 2 17 56 AM" src="https://github.com/user-attachments/assets/e5369bdf-bd76-4e92-88a2-1199573f4c5f">

**Comment by Cohee1207** [comment]
Unfortunately you can only have one link to llama.cpp. OpenAI-compatible is not really fully compatible with all backends that claim the compatibility since additional sampling parameters added by backends that are not a part of the standard are a gray zone. I guess there could be a compatibility mode that filters out all the parameters that are not in the [OpenAI docs](https://platform.openai.com/docs/api-reference/completions).

**Comment by frenzybiscuit** [comment]
What’s the best way to run embedding locally then if llamacpp is in use?

is there a way to increase the thread count on local transformers so it uses more then one core?

**Comment by Cohee1207** [comment]
> What’s the best way to run embedding locally then if llamacpp is in use?

Can't say anything about "the best", but ollama is an option that works.

> is there a way to increase the thread count on local transformers so it uses more then one core?

Not really.

**Comment by frenzybiscuit** [comment]
Hi,

Same issue with Open WebUI using llamacpp as the backend.

Can you add in an option to disable dry entirely?

**Comment by Cohee1207** [comment]
I have something better for you to try out @frenzybiscuit : a fully 100% OpenAI-compatible mode, no DRY, no XTC, just raw temp/top p
https://github.com/SillyTavern/SillyTavern/pull/3181

**Comment by frenzybiscuit** [comment]
> I have something better for you to try out @frenzybiscuit : a fully 100% OpenAI-compatible mode, no DRY, no XTC, just raw temp/top p #3181

Thanks so much! Is that ready for testing? Looks like there were some errors in the build.

**Comment by Cohee1207** [comment]
Yep, try it out. GitHub action went awry for some reasion, but it fully works.

**Comment by frenzybiscuit** [comment]
I get a black page.

It’s possible I messed up somewhere since I manually replaced the files. But, yeah.

**Comment by Cohee1207** [comment]
`git fetch origin`
`git switch tc-split-generic`

**Comment by frenzybiscuit** [comment]
Thanks!

I actually just cloned the staging branch and it appears to be working, so something you changed/did fixed it if the pull wasn't merged.
