### ISSUE TITLE
[Feature Request] Multiple World Infos

### ISSUE THREAD

**Issue by cc240b** [SillyTavern/SillyTavern#305]
It would be cool to be able to have multiple World Infos active at once instead of having to manually recreate entries on the one you want to use, maybe in an interface like NovelAI's Lorebook where you can quickly toggle entries on/off and edit them.
![nai lb](https://github.com/Cohee1207/SillyTavern/assets/110363819/31f85bfb-2a31-430b-9469-dc5fc2997109)

**Comment by RossAscends** [comment]
you can disable individual world info entries in ST.
