### ISSUE TITLE
[FEATURE_REQUEST] character avatar forward to comfyui as image to image generation 

### ISSUE THREAD

**Issue by Abdulhanan535** [SillyTavern/SillyTavern#3056]
### Have you searched for similar requests?

No

### Is your feature request related to a problem? If so, please describe.

Is it possible to forward character avatar image to comfyui for image to image as appending it "%char_image%" in workflow file?
I've tried the char_avatar one but it gives error.
Is it possible to upload the image to comfyui server aswell?.

### Describe the solution you'd like

.

### Describe alternatives you've considered

None

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
%char_avatar% returns a base64-encoded data URI string so you must use an appropriate loader node.

Example: https://comfy.icu/extension/glowcone__comfyui-base64-to-image

**Comment by Abdulhanan535** [comment]
oh thanks.
