### ISSUE TITLE
[FEATURE_REQUEST] Support Hyperbolic

### ISSUE THREAD

**Issue by Charuru** [SillyTavern/SillyTavern#3089]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

The Hyperbolic provider doesn't seem like it's an option on openrouter, please support that option. They have the only large context qwen deployment. https://openrouter.ai/qwen/qwen-2.5-coder-32b-instruct

### Describe the solution you'd like

Include it in one of the provider options in openrouter.

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
Done. https://github.com/SillyTavern/SillyTavern/commit/4c0da00f5b26e36aa7afcc0cfc6ece9bb9b282b2
