### ISSUE TITLE
[BUG] Substitute regex bug 

### ISSUE THREAD

**Issue by soboruB** [SillyTavern/SillyTavern#3104]
### Environment

🪟 Windows

### System

Firefox

### Version

1.12.7 staging

### Describe the problem

When using substitute within regex, it matches the literal characters.

Example QR:
```
/setvar key=regex .* |
/setvar key=regexflags ims |
/setvar key=toreplace TEST |
```

Regex: 
![1](https://github.com/user-attachments/assets/98d0569d-82c4-49b5-9127-23a806b8eeb2)
![2](https://github.com/user-attachments/assets/edd5897b-6d98-4120-a3d7-7163e70da680)

### Additional info

I noticed a pull requests from 3 weeks ago titled 'Fix substitute regex'. This seems to be the cause of the issue. Please revert this change. It's an unwanted feature… 

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
@honey-tree fight

**Comment by Cohee1207** [comment]
Alternatively, "substitute regex" could be made a three-state select: no substitutions, substitute (raw), substitute (escaped).

**Comment by ghost** [comment]
I maintain that my implementation is objectively correct because it bare minimum ensures the regexes outputted are valid for arbitrary {{char}} and generic macro outputs etc.

I am surprised that this actually breaks things for someone. Radio with 3 options sounds good yeah.

**Comment by ghost** [comment]
Actually DOES IT break things for someone? Can you give us the broad strokes on the actual usecase that led you to notice the change in behavior?

EDIT: on my end, the issue was primarily that variables with newlines produce incoherent regexes, and secondarily "/{{char}}/ should reliably match {{char}}", hence the PR.

**Comment by Cohee1207** [comment]
Check this one #3105

**Comment by ghost** [comment]
Away from my computer and can't test it but seems reasonable to me.

**Comment by Cohee1207** [comment]
I'll wait for someone to test it then.

**Comment by soboruB** [comment]
I'll show you a part of the QR I use. Please understand that some people use it this way. 
While I can add escaping when needed, I haven't found a way to modify already pre-processed escaped content.  (Please let me know if there is one)

1. When using simple regex (sentence replacement) Result: that filled something -> {{random:echoed,dispersed,diffused}}
```
  /setvar key=regex (that )?fill.{1,15} [a-z\s]{1,20} |
  /setvar key=regexflags gi |
  /setvar key=toreplace {{random:echoed,dispersed,diffused}}
```
Although direct changes can be made in regex, I use QR because I have many things to change and need to turn them on/off depending on the situation which makes direct regex inefficient.
For reference, I create a list of words or sentences to change within QR and change them all using the `/while`. (Sometimes I only change up to the middle of the list. It varies each time)

2. When using complex regex (deleting end sentences)
```
/flushvar key=toreplace |
/setvar key=regex (?<=[.?!\)`>]\|(?<!\s)")\s*([^.!?\)`>]\|(?<![^\s])")*?[".!?\)]*?(?=\s*$\|\s*```[\S\s]+?```\s*$\|\s*<([\S\s]+?)>[\S\s]+?<\/\2>\s*$\|\s*\[[^\n]*?\]\(#'[\S\s]+?'\)\s*$) |
/regex name=regexreplace {{lastMessage} |
/setvar key=regexflags i |
```
This regex can delete the last sentence. The pipelines are escaped here. (1.12.7 release)
However if everything is presented in an escaped state it cannot be used in these situations. Consider that it can be used in various ways.

**Comment by soboruB** [comment]
I tested substitute(raw) and everything worked well as before. Thanks!

**Comment by Cohee1207** [comment]
@honey-tree lemme know if escaped substitution broke. Closing for now.
