### ISSUE TITLE
[FEATURE_REQUEST] Enter to stop

### ISSUE THREAD

**Issue by Vibecoder9000** [SillyTavern/SillyTavern#3128]
### Have you searched for similar requests?

No

### Is your feature request related to a problem? If so, please describe.

When text is generating, I sometimes get annoyed when it's generating something wrong. I want to stop the generation. However, on mobile, the button is hard to press, and on PC (laptop) it's annoying to keep on using a trackpad to mouse over to it and click.

### Describe the solution you'd like

If the user presses Enter while generating text, the text stops generating. Additionally, pressing the right arrow key would stop the generating and immediately swipe (and save the output).

### Describe alternatives you've considered

macro, which I use. Can be unreliable through. 

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
You can use Escape to stop.

**Comment by Vibecoder9000** [comment]
Oh. Huh. Thanks for telling me. Is there a list of shortcuts somewhere?

**Comment by Cohee1207** [comment]
Type `/? hotkeys` in any SillyTavern chat.

**Comment by Vibecoder9000** [comment]
Great, thank you
