### ISSUE TITLE
[BUG] "Generate only one line per request" + Banned Strings

### ISSUE THREAD

**Issue by alicat22** [SillyTavern/SillyTavern#3143]
### Environment

🪟 Windows

### System

Chrome 131

### Version

SillyTavern 1.12.8 'staging' (980ebb2fb)

### Desktop Information

- Node.js version: v20.10.0
- API: KoboldAI
- Branch: Staging
- Model: Magnum-Picaro-0.7-v2

### Describe the problem

When banned strings is used with `Generate only one line per request`, it doesn't stop at the end of a paragraph, it stops after 4 to 5 words.

**Prompt:**
```
Here is the first paragraph.
Here is the second paragraph.
```
**Banned strings:**
```
"down your spine"
"through your spine"
"shiver through you"
"*"
```
**Actual:**
![image](https://github.com/user-attachments/assets/bd003e21-2985-4e6d-af0f-e7ec51a12bde)
**Expected:**
![image](https://github.com/user-attachments/assets/107a9aff-17a3-48c0-a445-82fe0060bd41)

### Additional info

```
Input: {"prompt": "Here is the first paragraph.\nHere is the second paragraph.\n", "max_new_tokens": 300, "max_tokens": 300, "temperature": 1.5, "top_p": 1, "typical_p": 1, "typical": 1, "sampler_seed": -1, "min_p": 0.02, "repetition_penalty": 1, "frequency_penalty": 0, "presence_penalty": 0, "top_k": 0, "skew": 0, "min_tokens": 0, "add_bos_token": true, "smoothing_factor": 0, "smoothing_curve": 1, "dry_allowed_length": 3, "dry_multiplier": 0.8, "dry_base": 1.75, "dry_sequence_breakers": "[\"\\n\",\":\",\"\\\"\",\"*\"]", "dry_penalty_last_n": 1400, "max_tokens_second": 0, "stopping_strings": ["\n", "\nAli:"], "stop": ["\n", "\nAli:"], "truncation_length": 16384, "ban_eos_token": false, "skip_special_tokens": true, "top_a": 0, "tfs": 1, "mirostat_mode": 0, "mirostat_tau": 5, "mirostat_eta": 0.1, "custom_token_bans": "", "banned_strings": ["down your spine", "through your spine", "shiver through you", "*"], "api_type": "koboldcpp", "api_server": "http://127.0.0.1:5000", "sampler_order": [5, 6, 0, 1, 2, 3, 4], "xtc_threshold": 0, "xtc_probability": 0, "nsigma": 0, "grammar": "", "rep_pen": 1, "rep_pen_range": 0, "repetition_penalty_range": 0, "seed": -1, "guidance_scale": 1, "negative_prompt": "", "grammar_string": "", "repeat_penalty": 1, "tfs_z": 1, "repeat_last_n": 0, "n_predict": 300, "num_predict": 300, "num_ctx": 16384, "mirostat": 0, "ignore_eos": false, "rep_pen_slope": 1, "stream": true}

Processing Prompt (12 / 12 tokens)
Generating (14 / 300 tokens)
(Stop sequence triggered: \n)
[20:03:44] CtxLimit:27/16384, Amt:14/300, Init:0.04s, Process:0.00s (0.3ms/T = 3000.00T/s), Generate:0.26s (18.6ms/T = 53.64T/s), Total:0.27s (52.83T/s)
Output: And here is the third paragraph

> “The primary way in which
```

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Not sure it's a frontend issue. Judging from the output, it looks like KoboldCpp just keeps generating after the stop token if there are banned strings in the request.

@LostRuins can you take a look please?

**Comment by LostRuins** [comment]
@Cohee1207 I assume you are not setting `trim_stop` to true? Maybe next time I will default it to true, since people seem to prefer that behavior and are unaware of that flag.

When `trim_stop` is false, the response includes the stop sequence.

When banned strings (anti-slop) is used, then the output string buffer is delayed by the maximum length of all banned string sequences, in order for it to be able to rewind when it gets triggered.

Combined, the net effect is that you'll notice `len(longest_banned_string)` extra tokens output after the stop sequence triggers.

If you're ok with the behavior of `trim_stop` then I can make that the default.

**Comment by LostRuins** [comment]
https://github.com/LostRuins/koboldcpp/commit/52cc908f7fd2201fbfc39a49e94c8bc8f9f3aa43 

You can try with this commit

**Comment by Cohee1207** [comment]
Fixed here https://github.com/SillyTavern/SillyTavern/commit/7ce2841588912bbd0d2f39527b634fe18857ab0c

@alicat22 please verify

**Comment by alicat22** [comment]
Yep, it works exactly as expected! This is no longer an issue.

Thank you!!
