### ISSUE TITLE
[BUG] Error when trying to import some personages from janitorai and PLACEHOLDER - TO BE UPDATED sometimes

### ISSUE THREAD

**Issue by XZVB12** [SillyTavern/SillyTavern#3174]
### Environment

🐧 Linux

### System

Firefox 133.0.3  , Manjaro Linux unstable

### Version

Stable 1.12.9 and curent staging  (e773678f2)

### Desktop Information

NodeJs v23.3.0

### Describe the problem

Hi. Sometimes i get the following error message when trying to import some characters from https://janitorai.com:

**Custom content import failed
Internal Server Error**
 
I suggested that the problem is that the name uses non-standard symbols, but this is not always the case, for example: https://janitorai.com/characters/326a180a-2967-4ff2-817b-7ba32fc77f9c_character-chara-dreemurr-%E2%9D%A4%EF%B8%8E and https://janitorai.com/characters/299b667e-6ea8-4f93-be4b-f25aa0af9982_character-%F0%9F%97%A1-%E2%94%8A-anne-bonny Imported without problems, but 
https://janitorai.com/characters/e75ad6af-9416-4545-82bd-8d92506da361_character-%E2%9E%B4-%E2%9D%A4%EF%B8%8E-trafalgar-law causes an error.

Also sometimes when importing all fields are filled with "**PLACEHOLDER - TO BE UPDATED**" message
At first I thought the problem was that Character Definition is hidden in some cards, but it’s not so, import can work when data is hidden and may not work even when they are open 
for example imported from here without any problems: https://janitorai.com/characters/1b8e1fd2-8a1f-4f43-b78c-60c5b14c39ba_character-ruby, but not this person : https://janitorai.com/characters/a3157688-dc9f-4216-a718-aa72d800ffb3_character-malepov-seirra-workaholic-wife

 All the cards are random examples that I found just by scrolling through characters to find the source of the problem. I did not check the description, but tried to choose safe examples.

### Additional info

Importing custom content failed TypeError: body used already for: https://api.jannyai.com/api/v1/download
at consumeBody (file:/SillyTavern-staging/node_modules/node-fetch/src/body.js:196:9)
at Response.text (file:/SillyTavern-staging/node_modules/node-fetch/src/body.js:158:24)
at downloadJannyCharacter (file:/SillyTavern-staging/src/endpoints/content-manager.js:488:73)
at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
at async file:SillyTavern-staging/src/endpoints/content-manager.js:663:22

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
External API issues, nothing to be done in ST itself.

**Comment by XZVB12** [comment]
> External API issues, nothing to be done in ST itself.

In the case of "PLACEHOLDER - TO BE UPDATED" too ?
It’s strange to me that errors or placeholders only happen in some cases

**Comment by Cohee1207** [comment]
The content is recorded unaltered as provided by the remote server.
