### ISSUE TITLE
[BUG] could not upload Janitor.ai to tavern

### ISSUE THREAD

**Issue by denish07-a** [SillyTavern/SillyTavern#3200]
### Environment

🪟 Windows

### System

window 11

### Version

1.12.9

### Describe the problem

I have tried to import jan profile via link and it kept saying this
![image](https://github.com/user-attachments/assets/7383a3c4-516a-4749-9705-429bdb898c08)
how to fic this issue?

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
This relates to an external service for which we don't have any control.
