### ISSUE TITLE
[BUG] `undefined` variable pollutes generation

### ISSUE THREAD

**Issue by drago87** [SillyTavern/SillyTavern#3204]
### Environment

🪟 Windows

### System

Windows 10, Opera

### Version

SillyTavern 1.12.9 'staging' (e49301308)

### Describe the problem

If you accidently use `/setvar t something` instead of `/setvar key=t something` it will save a `undefined` variable that will pollute future `/genraw` commands (Have not tried normal generation or /gen)

### Additional info

What i had done was.
```
/genraw {{getvar::fname}} is a Human. Describe in detail {{getvar::genpron}} skin tone.
Is {{getvar::fname}} sunburned?
If yes describe what part/parts {{getvar::genpron2}} is sunburned on.
Is {{getvar::fname}} tanned?
If yes describe what part/parts {{getvar::genpron2}} is tanned on.|
        /setvar t {{pipe}}|
```
Where i accidently forgot the `key=` on `/setvar t {{pipe}}|`
after i changed that to
```
/genraw {{getvar::fname}} is a Human. Describe in detail {{getvar::genpron}} skin tone.
Is {{getvar::fname}} sunburned?
If yes describe what part/parts {{getvar::genpron2}} is sunburned on.
Is {{getvar::fname}} tanned?
If yes describe what part/parts {{getvar::genpron2}} is tanned on.|
        /setvar key=t {{pipe}}|
```
I got the first attempts generation at the beginning of the new generation

[sent.txt](https://github.com/user-attachments/files/18184567/sent.txt)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Try the fix here: https://github.com/SillyTavern/SillyTavern/pull/3205

**Comment by drago87** [comment]
I have updated to SillyTavern 1.12.9 'staging' (https://github.com/SillyTavern/SillyTavern/commit/00363cc206fb7ba75970f08c1ae742b805afdf5f). So if it is on staging it still seams to not work. Aka still same outcome

**Comment by Cohee1207** [comment]
It's not on staging, it's in a PR branch. Fetch and switch to it from command line.

**Comment by drago87** [comment]
I have tried it now and seams to work as intended
