### ISSUE TITLE
[BUG] Connecting to ComfyUI Backend Extension in SwarmUI.

### ISSUE THREAD

**Issue by maccan-tech** [SillyTavern/SillyTavern#3208]
### Environment

🐧 Linux

### System

Fedora 40

### Version

1.12.9

### Desktop Information

Running SillyTavern official docker.
Running SwarmUI official docker with ComfyUI Backend Extension.
ComfyUI v0.3.8-6-gcac68ca
ComfyUI_frontend v1.3.44

### Describe the problem

Error connection to ComfyUI Backend Extension in SwarmUI.
'Could not validate ComfyUI API: ComfyUI returned an error.'

I the SwarmUI API docs
https://github.com/mcmonkeyprojects/SwarmUI/blob/master/docs/API.md
You can find the following.
`/ComfyBackendDirect/*.* - direct pass-through to a comfy instance, if the ComfyUI Backend Extension is in use.`

Using this exaple below in SillyTavern image generation setting givs an error.
`http://192.168.0.100:7801/ComfyBackendDirect`
Link works in other software as api path to comfyui.

http://192.168.0.100:7821 dos not work when running Swarm as docker.

Thank you for the great work !

### Additional info

Error in docker log:
Error: ComfyUI returned an error.
    at file:///home/node/app/src/endpoints/stable-diffusion.js:372:19
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

http://192.168.0.100:7801/ComfyBackendDirect/system_stats
returns
`
{"system": {"os": "posix", "ram_total": 67106959360, "ram_free": 62084505600, "comfyui_version": "v0.3.8-6-gcac68ca", "python_version": "3.11.2 (main, Sep 14 2024, 03:00:30) [GCC 12.2.0]", "pytorch_version": "2.5.1+cu124", "embedded_python": false, "argv": ["main.py", "--port", "7821", "--extra-model-paths-config", "/Data/comfy-auto-model.yaml", "--preview-method", "latent2rgb", "--front-end-version", "Comfy-Org/ComfyUI_frontend@v1.3.44"]}, "devices": [{"name": "cuda:0 NVIDIA RTX 4000 Ada Generation : cudaMallocAsync", "type": "cuda", "index": 0, "vram_total": 21015429120, "vram_free": 9388425216, "torch_vram_total": 0, "torch_vram_free": 0}]}
`

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Reproduced, fixed in the staging branch. Please confirm that this is fixed on your side.

**Comment by maccan-tech** [comment]
It will now connect using the api path to comfyui in swarmui. 
Thanks!
