### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by shwepsoff** [SillyTavern/SillyTavern#3214]
### Environment

📱 Termux

### System

Firefox 133.0.3, Chrome 131.0.6778.200, Kiwi Browser 124.0.6327.4

### Version

1.12.9, 1.11.4

### Desktop Information

• node.js version: v23.4.0
• branch: release

### Describe the problem

I've been using ST through Termux for a very long time, and at a completely random moment, it stopped working altogether. Termux does not issue absolutely any errors, however, devtools in one of browsers is simply teeming with them. 

The funny thing is that at a completely random moment, ST starts working as before, but 10-15 minutes pass and I see gray screen in front of me again.

What I tried to do to solve this problem: 
- check and restart Internet connection
- disable vpn
- check all possible antiviruses and firewalls on phone 
- roll back to old version (1.11.4)

None of the above solutions helped. I have no idea what else to do, so I'm asking for help here. Thanks in advance for answer!

### Additional info

![IMG_20241221_235802_231](https://github.com/user-attachments/assets/0fc60403-cc76-4439-97a1-8606691ec58b)
![IMG_20241221_235759_911](https://github.com/user-attachments/assets/db37ddb9-6831-438d-bd2d-f998c4bd6ed0)
![IMG_20241221_235758_119](https://github.com/user-attachments/assets/8a362ec8-6df1-42ea-b5a1-ea6be5ebc471)
![IMG_20241221_235756_106](https://github.com/user-attachments/assets/a4bd3c30-9ec6-4cf7-83a8-acc92d2341f4)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
I'm not sure why the "network changed" would trigger on a localhost, it's almost like your loopback interface is tripping and restarts itself every now and then. I can definitely say that this is not a software issue we could fix here. Try updating phone firmware, reinstall termux (not from a play store) or try hosting from another device.

**Comment by shwepsoff** [comment]
updating phone firmware really helped. thanks for help!
