### ISSUE TITLE
[Feature Request] See token budget

### ISSUE THREAD

**Issue by Manimap** [SillyTavern/SillyTavern#322]
Hello,

Sorry if it's already available, I didn't see it either in the cli nor the webui, but is there a way to know how many tokens are used in a story so far?
For example, something like 
Send sentence -> 1500 tokens are shown somewhere in the interface
Get back answer -> new count is shown as 1700
etc

**Comment by sanskar-mk2** [comment]
Per message token breakdown is in the dev branch already.
@RossAscends  could just sum it up to show the total somewhere?
