### ISSUE TITLE
[FEATURE_REQUEST] Add support for DeepSeek chat completion

### ISSUE THREAD

**Issue by cloak1505** [SillyTavern/SillyTavern#3233]
### Have you searched for similar requests?

Yes

### Describe the solution you'd like

https://api-docs.deepseek.com/api/create-chat-completion
https://api-docs.deepseek.com/guides/chat_prefix_completion

The regular URL is `https://api.deepseek.com/chat/completions` (does not require /v1) but the demand among users is to get support for prefill, which requires `https://api.deepseek.com/beta` and `"prefix": True` in assistant message as last message.

The currently available models are `deepseek-chat` (DeepSeek-V3) and `deepseek-coder` (?).

Top-P range is 0 exclusive and 1 inclusive, while the other ranges are inclusive on both ends.

The system role is supported, and it sees multiple system messages. However, in my testing where I ask it to state all the markers it sees in order, system messages get moved to the top. To circumvent this, any system messages after the first user/assistant message should be converted to user.

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by cloak1505** [comment]
**2025-01-23:** OpenRouter now has DeepSeek prefix built in for V3/R1, and direct DS has reverse proxy implemented. Do not edit your file. For slightly more information, see pull 3326.

Below is outdated.

***

Enabling DeepSeek prefill in Custom (OpenAI-compatible):

> In ./public/index.html:
>
> Find this line:
> `<option value="strict">Strict (user first, alternating roles)</option>`
> And add this below it:
> `<option value="deepseek">DeepSeek</option>`
> 
> In ./public/scripts/openai.js:
> 
> Find this line: `CLAUDE: 'claude',`
> Add add this below it: `DEEPSEEK: 'deepseek',`
> 
> In ./src/endpoints/backends/chat-completions.js:
> 
> Below `case 'strict':` block, add:
>
> ```
> case 'deepseek':
>     return (x => x[x.length - 1].role !== 'assistant' || (x[x.length - 1].prefix = true) ? x : x)([...messages])
> ```
> 
> After these edits, restart ST, use OpenAI-compatible, enter Base URL `https://api.deepseek.com/beta` and Model ID `deepseek-chat`, and select DeepSeek in Prompt Post-Processing.

Edit: This works on `https://openrouter.ai/api/v1` too!
Edit: Better return statement from honey-tree.

**Comment by ghost** [comment]
```
return (x => x[x.length - 1].role !== 'assistant' || (x[x.length - 1].prefix = true) ? x : x)([...messages])
```

EDIT: Or you can put normal person code in the codebase, this is if it actually needs to be a oneliner.

**Comment by cloak1505** [comment]
Logo 
![deepseek_128x128](https://github.com/user-attachments/assets/fc900ade-28ff-4af9-b64a-1b40f27277fd)

**Comment by Manimap** [comment]
> Enabling DeepSeek prefill in Custom (OpenAI-compatible):
> 
> > In ./public/index.html:
> > Find this line:
> > `<option value="strict">Strict (user first, alternating roles)</option>`
> > And add this below it:
> > `<option value="deepseek">DeepSeek</option>`
> > In ./public/scripts/openai.js:
> > Find this line: `CLAUDE: 'claude',`
> > Add add this below it: `DEEPSEEK: 'deepseek',`
> > In ./src/endpoints/backends/chat-completions.js:
> > Below `case 'strict':` block, add:
> > ```
> > case 'deepseek':
> >     return (x => x[x.length - 1].role !== 'assistant' || (x[x.length - 1].prefix = true) ? x : x)([...messages])
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After these edits, restart ST, use OpenAI-compatible, enter Base URL `https://api.deepseek.com/beta` and Model ID `deepseek-chat`, and select DeepSeek in Prompt Post-Processing.
> 
> Edit: This works on `https://openrouter.ai/api/v1` too! Edit: Better return statement from honey-tree.

Do you still need to do that in latest staging to include prefill with OpenRouter?

**Comment by ChooChoo38** [comment]
> Do you still need to do that in latest staging to include prefill with OpenRouter?

Probably not, provided you edit one file. I believe the official fix is specific for DeepSeek's API and that it doesn't apply if you access it via OpenRouter. From what I can tell at a glance, it adds an option where you select Chat Completion, then the new DeepSeek option, and applies the prefill fix to that. Sadly, there's no option in the UI to change the location of the API, it defaults to api.deepseek.com/beta.

However, if you edit src/endpoints/backends/chat-completions.js, you should be able to replace :

const API_DEEPSEEK = 'https://api.deepseek.com/beta';
with
const API_DEEPSEEK = 'https://openrouter.ai/api/v1';

Don't see why that wouldn't work, but I don't use OR, so you'll have to test it out. If it works, you should see "prefix: true" in the console provided the last prompt in your stack has its role set to AI Assistant.

**Comment by Manimap** [comment]
> > Do you still need to do that in latest staging to include prefill with OpenRouter?
> 
> Probably not, provided you edit one file. I believe the official fix is specific for DeepSeek's API and that it doesn't apply if you access it via OpenRouter. From what I can tell at a glance, it adds an option where you select Chat Completion, then the new DeepSeek option, and applies the prefill fix to that. Sadly, there's no option in the UI to change the location of the API, it defaults to api.deepseek.com/beta.
> 
> However, if you edit src/endpoints/backends/chat-completions.js, you should be able to replace :
> 
> const API_DEEPSEEK = 'https://api.deepseek.com/beta'; with const API_DEEPSEEK = 'https://openrouter.ai/api/v1';
> 
> Don't see why that wouldn't work, but I don't use OR, so you'll have to test it out. If it works, you should see "prefix: true" in the console provided the last prompt in your stack has its role set to AI Assistant.



Thanks for your anwser, I modified it from deepseek url to openrouter one, restarted the web service, and yet I don't see prefix = true in the parameters sent through openrouter in the console, all I see is : 

 prompt: undefined,
  model: 'deepseek/deepseek-chat',
  temperature: 0.9,
  max_tokens: 4096,
  max_completion_tokens: undefined,
  stream: true,
  presence_penalty: 0,
  frequency_penalty: 0,
  top_p: 1,
  top_k: 0,
  stop: undefined,
  logit_bias: undefined,
  seed: undefined,
  n: undefined,
  transforms: [],
  min_p: 0,
  top_a: 1,
  repetition_penalty: 1

**Comment by Manimap** [comment]
Oh wait I think I got it, I'm using openrouter as a chat completion source instead of the deepseek (that was manually modified to redirect to Openrouter).
It's a bit confusing but it works now!

**Comment by cloak1505** [comment]
OpenRouter "fixed" DeepSeek 15 minutes ago to send `prompt` as is to /beta/completions. This means TC is usable without editing or Custom.
[DeepSeek v2.5 template.json](https://github.com/user-attachments/files/18283979/DeepSeek.v2.5.template.json)
