### ISSUE TITLE
[FEATURE_REQUEST] Allow users to use http proxy

### ISSUE THREAD

**Issue by axel10** [SillyTavern/SillyTavern#3234]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Not every place in the world can freely access the APIs of AI providers such as OpenAI and Gemini. They often need HTTP proxy to access these APIs. Sillytarven does not initiate network requests through the system proxy by default. This means that if users want sillytarven to initiate requests through HTTP proxy, they must use some other network tools that can add virtual network adapters.

### Describe the solution you'd like

Use the [global-agent](https://github.com/gajus/global-agent) library to allow users to configure HTTP proxy by themselves through environment variables

Only need to add a line of code after adding the dependency to solve it
![image](https://github.com/user-attachments/assets/5675cb72-77e8-4372-aff8-691c7059ad4c)

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
Read the docs: https://docs.sillytavern.app/administration/config-yaml/#request-proxy-configuration
