### ISSUE TITLE
[Feature Request] Multi swap

### ISSUE THREAD

**Issue by Manimap** [SillyTavern/SillyTavern#327]
Hello, 

I really like the swap option, making me able to select an alternate answer. 
But is there any way to make multiple swaps in serie, (not in parallel)

Me: click on toggle on "multi swap"
Me : sentence
Bot : 5/6/10/20/x swaps with 5/6/10/20/x possible answers

It's pretty useful for local models or even cloud ones since I can ask them to queue multiple answers on a row when doing something else.

**Comment by RossAscends** [comment]
This is not how the APIs work. There is a reason why we disable swiping during streamed responses. You cannot make the API send multiple replies to your endpoint in a safe or reliable manner.

**Comment by alicat22** [comment]
So essentially, for the Auto-swipe option, but the ability to set how many swipes to do automatically with every generation?

For example, you'd set auto-swipe to 4. Then when you generate, it would automatically generate 4 swipe responses? Then the user could switch between them?

Or is this request a little different?

**Comment by Mu2u** [comment]
Just wanted to agree with this as well, for me I would like it to keep getting chat results until I send my actual response.  basically getting as many responses as possible until moving to the next one and then doing the same thing.  there shouldn't be idle time on the api.

**Comment by Priestru** [comment]
Agree that this would be valuable, had same thought today.
