### ISSUE TITLE
[Feature Request] Stop the page from jumping during text streaming generation. 📃

### ISSUE THREAD

**Issue by imesha10** [SillyTavern/SillyTavern#335]
**Is your feature request related to a problem? Please describe.**
When some text is generated I want to grab some text from above or read something that is above. When I go scroll up while the generation is being streamed it jumps back down to the bottom.

https://github.com/Cohee1207/SillyTavern/assets/16441743/275d32ba-8b86-4a1c-aea9-68107e7fb207

**Describe the solution you'd like**
I should be able to scoll freely while the text is being generated.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by sanskar-mk2** [comment]
https://github.com/Cohee1207/SillyTavern/issues/270

**Comment by sanskar-mk2** [comment]
Thoughts about changing the default behavior to not auto-scroll.
It isn't a pleasant experience.

**Comment by imesha10** [comment]
Ya it's not pleasant when you didn't know that option existed 😅.
I didn't see that there was an option in the settings so that does work for me.
However there might be more people who uses sillytavern and have the same issue later on so it might be better to disable that by default. Idk.
Thoughts? 💭

**Comment by imesha10** [comment]
Ok so there are some problems with the no autoscroll option. It does not seem to magnetically latch on to the bottom sometimes when it should (when a new text is initially generated) and other times it does. I may review this problem tommorow and post a new issue with more detail.

**Comment by RossAscends** [comment]
Will check if we can make the auto scroll only happen when a streamed message is completed.

**Comment by imesha10** [comment]
Hi @RossAscends,

I'd like to propose a new feature: "Magnetic Scrolling Lock".

In this mode, the view will automatically 'stick' to the latest incoming text (like a magnet) when the user is at the bottom of the page. However, if the user decides to scroll up, this magnetic lock would disengage, and they would enter a free-scrolling mode, enabling them to explore earlier parts of the text freely.

Initially, this could be introduced as an optional mode, allowing users to test its utility and provide feedback before it becomes a standard feature.

Looking forward to your thoughts on this.
