### ISSUE TITLE
[Feature Request] Use Proxy to connect Poe or OpenAI

### ISSUE THREAD

**Issue by jiayev** [SillyTavern/SillyTavern#364]
Use Proxy to connect Poe or OpenAI

**Comment by liukaixiang817** [comment]
Also need this

**Comment by gitmylo** [comment]
The openai proxy in the settings when you have openai selected works great! i haven't tested the claude proxy though.

**Comment by hengjiUSTC** [comment]
Hey, any simple solution instead of Docker?>
