### ISSUE TITLE
[Feature Request] handle "Unable to reach Poe." error from poe.com

### ISSUE THREAD

**Issue by azumukupoe** [SillyTavern/SillyTavern#398]
**Have you searched for similar [requests](https://github.com/Cohee1207/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
when poe.com returns the error, I have to reload the ST tab to continue as the hourglass indicator won't disappear and ST won't respond to any user input

**Describe the solution you'd like**
return error in ST when poe.com does

**Describe alternatives you've considered**
~~A clear and concise description of any alternative solutions or features you've considered.~~

**Additional context**
![image](https://github.com/SillyTavern/SillyTavern/assets/31339007/2c55fbe6-b519-4daf-8a75-ca1fd060e95e)

**Comment by mafusimp** [comment]
I have the same issue, tried to reload ST multiple times but still didn't work, it still says connected to the API but the space where to choose the bots is blank and they don't get any reply, what to do?

**Comment by Xanox141** [comment]
Same here...

**Comment by Custardboy** [comment]
for me I can connect my API but it doesnt show me the bots, and when I try to chat, it just shows blank text

**Comment by MasterHacker013** [comment]
Yeah it's letting me connect to Poe but the API field is showing up completely blank and the bots aren't generating any messages.

**Comment by whyamiherestillbruh** [comment]
I'm having the same issues of no bots appearing, here is a screenshot if this helps @Cohee1207 of poe and no bots.
![Screenshot 2023-05-31 205115](https://github.com/SillyTavern/SillyTavern/assets/133461973/531a6bde-0e56-4648-864c-72264d5ed122)

**Comment by whyamiherestillbruh** [comment]
it worked thank you brother
