### ISSUE TITLE
[Feature Request] Custom dice: words

### ISSUE THREAD

**Issue by OgalFinklestein** [SillyTavern/SillyTavern#400]
**Have you searched for similar [requests](https://github.com/Cohee1207/SillyTavern/issues?q=)?**
Always.

**Is your feature request related to a problem? Please describe.**
Well, not a _reported_ problem. I tell ST (using Kobold) that there are two (d6) dice.
1st die reads: 'Left Leg', 'Right Leg', 'Left Arm', 'Right Arm', 'Head', 'Butt'
2nd die read: 'Blue', 'Red', 'Yellow', 'Orange', 'Green', 'Purple'
(Think of the game Twister but with dice).
Problem is sometimes a bot will throw the same die twice, or add it's own variation (Elbow or Brown) into the mix. 

**Describe the solution you'd like**
Maybe import a file (or folder of JSON files) containing a comma-delimited list/array of customized dice that either I or the AI can make use of (maybe via {{dice:color}} ).

**Comment by Cohee1207** [comment]
Possible with new {{random}} macro
