### ISSUE TITLE
[Feature Request] Multiple Stopsequences

### ISSUE THREAD

**Issue by IkariDevGIT** [SillyTavern/SillyTavern#402]
**Have you searched for similar [requests](https://github.com/Cohee1207/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when it generates something that should not be there

**Describe the solution you'd like**
it could look like this: {{char}}:,{{user}}:,</s>

**Describe alternatives you've considered**
cant think of any alternatives

**Comment by IkariDevGIT** [comment]
> Which API? Not every API supports stop sequences

@Cohee1207 
Oobabooga webui

**Comment by IkariDevGIT** [comment]
@Cohee1207 you there?

**Comment by IkariDevGIT** [comment]
thanks for the reply @Cohee1207, auto swipe will not be an option, as I just want to let it stop if it does something like "### Response" or "user:" and things like that after the message from the character(I mean the stop sequence in the instruct mode btw)

**Comment by IkariDevGIT** [comment]
@Cohee1207 did you read my last reply?

**Comment by Cohee1207** [comment]
Implemented in main
