### ISSUE TITLE
Poe bots not showing up

### ISSUE THREAD

**Issue by VindictiveReflux** [SillyTavern/SillyTavern#409]
It just started happening a little bit ago for me. Whenever I launch SillyTavern(yes, I've updated to 1.6.0 to see if that would work; it did not.), all of the bot options disappeared. The dropdown is completely blank. Restarting doesn't work, and I've even tried signing in with a different account, to see if I could pull a different p-b token. Nothing has worked. This just started happening about an hour ago. I've restarted my computer, connected to a different wi-fi network on my router, deleted the cloned folder and cloned again, but... nothing has worked.

How to Reproduce:
1. Launch SillyTavern.
2. Connect using Poe API.

Expected Behavior
For the bots to show up.

I have screenshots provided; both the command prompt, and the GUI. The dropdown where the bots would be is totally blank, only dropping down a line. It's blank. There's nothing.

I use the main branch, version 1.6.0, running on Windows 11. I'm using Opera GX. Node.js version is the latest.

![Screenshot 2023-05-30 142053](https://github.com/SillyTavern/SillyTavern/assets/96753064/3241a28a-4182-4dc1-8e9e-ac3a7b708e65)
![Screenshot 2023-05-30 142241](https://github.com/SillyTavern/SillyTavern/assets/96753064/85aac65a-1731-4f0a-8fe3-727bd46f2c8e)

**Comment by LegionInstaller** [comment]
Let's not hope that Poe has shut us out

**Comment by VindictiveReflux** [comment]
Good to know I'm not the only one.

**Comment by NotCrosby** [comment]
Having the exact same issue here as well.

Both PC and Android.

**Comment by LegionInstaller** [comment]
Great, Let's hope they really didn't shut us out

**Comment by VindictiveReflux** [comment]
Maybe their servers are down... I hadn't thought of that, but this is unlike anything I've seen compared to any other instance.

**Comment by LegionInstaller** [comment]
> Maybe their servers are down... I hadn't thought of that, but this is unlike anything I've seen compared to any other instance.

But shouldn't we be able to connect in the first place, I don't know that much about that tbh

**Comment by LegionInstaller** [comment]
R.I.P my Issue XD

**Comment by VindictiveReflux** [comment]
Well until it fixes itself, I'm gonna assume that they finally cracked down on this... Sad.

**Comment by LegionInstaller** [comment]
> Well until this is fixed, I'm gonna assume that they finally cracked down on this... Sad.

Would suck

**Comment by NotCrosby** [comment]
Let's keep positive and say that this is a very Goofy bug and this is a very Goofy day.

**Comment by LegionInstaller** [comment]
> Let's keep positive and say that this is a very Goofy bug and this is a very Goofy day.

Yeah, but I think their servers are having trouble again since my bots won't respond and when they do very late

**Comment by VindictiveReflux** [comment]
I can only hope that that is the case.
I'd rather deal with "websocket error" and "timed out" on every other message if it meant that I could use Poe again...

**Comment by LegionInstaller** [comment]
"Yup" *cries in corner*

**Comment by Texint** [comment]
I can access and talk to sage on poe.com, so I'm assuming the worst.

**Comment by m-pokrovskii** [comment]
Savior has arrived: https://github.com/SillyTavern/SillyTavern/issues/411#issuecomment-1569187970

**Comment by VindictiveReflux** [comment]
I'll include it here, too.

Open poe-client.js. Find const "botList = viewer.availableBots;" and replace it with "const botList = viewer.viewerBotList;".
