### ISSUE TITLE
[BUG] AxiosError: connect ETIMEDOUT

### ISSUE THREAD

**Issue by BottleDemon** [SillyTavern/SillyTavern#432]
> **Warning**. Complete **all** the fields below. Otherwise your bug report will be **ignored**!

**Have you searched for similar [bugs](https://github.com/Cohee1207/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
When connect to ST using Poe, console pops out this and cannot download anything, using VPN.

**To Reproduce**
1. Follows the guide on discord to last step and click connect.
2. Console pops out Error and can't download anything.

**Expected behavior**
Something will be download and work perfectly.

**Screenshots**
![image](https://github.com/SillyTavern/SillyTavern/assets/135333473/e5cd89f7-9427-44c8-8042-aa6e912759c6)

**Logs**
AxiosError: connect ETIMEDOUT 128.242.245.93:443
at AxiosError.from (D:\AI\SillyTavern-1.6.5\node_modules\axios\dist\node\axios.cjs:836:14)
at RedirectableRequest.handleRequestError (D:\AI\SillyTavern-1.6.5\node_modules\axios\dist\node\axios.cjs:3010:25)
at RedirectableRequest.emit (node:events:525:35)
at eventHandlers. (D:\AI\SillyTavern-1.6.5\node_modules\follow-redirects\index.js:14:24)
at ClientRequest.emit (node:events:513:28)
at TLSSocket.socketErrorListener (node:_http_client:502:9)
at TLSSocket.emit (node:events:513:28)
at emitErrorNT (node:internal/streams/destroy:151:8)
at emitErrorCloseNT (node:internal/streams/destroy:116:3)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
port: 443,
address: '128.242.245.93',
syscall: 'connect',
code: 'ETIMEDOUT',
errno: -4039,
config: {
transitional: {
silentJSONParsing: true,
forcedJSONParsing: true,
clarifyTimeoutError: false
},
adapter: [ 'xhr', 'http' ],
transformRequest: [ [Function: transformRequest] ],
transformResponse: [ [Function: transformResponse] ],
timeout: 60000,
xsrfCookieName: 'XSRF-TOKEN',
xsrfHeaderName: 'X-XSRF-TOKEN',
maxContentLength: -1,
maxBodyLength: -1,
env: { FormData: [Function], Blob: [class Blob] },
validateStatus: [Function: validateStatus],
headers: AxiosHeaders {
'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36',
Referrer: 'https://poe.com/',
Origin: 'https://poe.com/',
Cookie: 'p-b=XU-w3tJqB7HGBcvn1YxGDA%3D%3D; Domain=poe.com',
'Accept-Encoding': 'gzip, compress, deflate, br'
},
httpAgent: Agent {
_events: [Object: null prototype],
_eventsCount: 2,
_maxListeners: undefined,
defaultPort: 80,
protocol: 'http:',
options: [Object: null prototype],
requests: [Object: null prototype] {},
sockets: [Object: null prototype] {},
freeSockets: [Object: null prototype] {},
keepAliveMsecs: 1000,
keepAlive: true,
maxSockets: Infinity,
maxFreeSockets: 256,
scheduling: 'lifo',
maxTotalSockets: Infinity,
totalSocketCount: 0,
[Symbol(kCapture)]: false
},
httpsAgent: Agent {
_events: [Object: null prototype],
_eventsCount: 2,
_maxListeners: undefined,
defaultPort: 443,
protocol: 'https:',
options: [Object: null prototype],
requests: [Object: null prototype] {},
sockets: [Object: null prototype],
freeSockets: [Object: null prototype] {},
keepAliveMsecs: 1000,
keepAlive: true,
maxSockets: Infinity,
maxFreeSockets: 256,
scheduling: 'lifo',
maxTotalSockets: Infinity,
totalSocketCount: 1,
maxCachedSessions: 100,
_sessionCache: [Object],
[Symbol(kCapture)]: false
},
signal: AbortSignal { aborted: false },
method: 'get',
url: 'https://poe.com/',
data: undefined
},
request: <ref *1> Writable {
_writableState: WritableState {
objectMode: false,
highWaterMark: 16384,
finalCalled: false,
needDrain: false,
ending: false,
ended: false,
finished: false,
destroyed: false,
decodeStrings: true,
defaultEncoding: 'utf8',
length: 0,
writing: false,
corked: 0,
sync: true,
bufferProcessing: false,
onwrite: [Function: bound onwrite],
writecb: null,
writelen: 0,
afterWriteTickInfo: null,
buffered: [],
bufferedIndex: 0,
allBuffers: true,
allNoop: true,
pendingcb: 0,
constructed: true,
prefinished: false,
errorEmitted: false,
emitClose: true,
autoDestroy: true,
errored: null,
closed: false,
closeEmitted: false,
[Symbol(kOnFinished)]: []
},
_events: [Object: null prototype] {
response: [Function: handleResponse],
error: [Function: handleRequestError],
socket: [Array]
},
_eventsCount: 3,
_maxListeners: undefined,
_options: {
maxRedirects: 21,
maxBodyLength: Infinity,
protocol: 'https:',
path: '/',
method: 'GET',
headers: [Object: null prototype],
agents: [Object],
auth: undefined,
family: undefined,
lookup: undefined,
beforeRedirect: [Function: dispatchBeforeRedirect],
beforeRedirects: [Object],
hostname: 'poe.com',
port: '',
agent: [Agent],
nativeProtocols: [Object],
pathname: '/'
},
_ended: true,
_ending: true,
_redirectCount: 0,
_redirects: [],
_requestBodyLength: 0,
_requestBodyBuffers: [],
_onNativeResponse: [Function (anonymous)],
_currentRequest: ClientRequest {
_events: [Object: null prototype],
_eventsCount: 7,
_maxListeners: undefined,
outputData: [],
outputSize: 0,
writable: true,
destroyed: false,
_last: true,
chunkedEncoding: false,
shouldKeepAlive: true,
maxRequestsOnConnectionReached: false,
_defaultKeepAlive: true,
useChunkedEncodingByDefault: false,
sendDate: false,
_removedConnection: false,
_removedContLen: false,
_removedTE: false,
strictContentLength: false,
_contentLength: 0,
_hasBody: true,
_trailer: '',
finished: true,
_headerSent: true,
_closed: false,
socket: [TLSSocket],
_header: 'GET / HTTP/1.1\r\n' +
'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36\r\n' +
'Referrer: [https://poe.com/\r\n](https://poe.com/%5Cr%5Cn)' +
'Origin: [https://poe.com\r\n](https://poe.com%5Cr%5Cn/)' +
'Cookie: p-b=XU-w3tJqB7HGBcvn1YxGDA%3D%3D; Domain=poe.com\r\n' +
'Accept-Encoding: gzip, compress, deflate, br\r\n' +
'Host: poe.com\r\n' +
'Connection: keep-alive\r\n' +
'\r\n',
_keepAliveTimeout: 0,
_onPendingData: [Function: nop],
agent: [Agent],
socketPath: undefined,
method: 'GET',
maxHeaderSize: undefined,
insecureHTTPParser: undefined,
joinDuplicateHeaders: undefined,
path: '/',
_ended: false,
res: null,
aborted: false,
timeoutCb: null,
upgradeOrConnect: false,
parser: null,
maxHeadersCount: null,
reusedSocket: false,
host: 'poe.com',
protocol: 'https:',
_redirectable: [Circular *1],
[Symbol(kCapture)]: false,
[Symbol(kBytesWritten)]: 0,
[Symbol(kNeedDrain)]: false,
[Symbol(corked)]: 0,
[Symbol(kOutHeaders)]: [Object: null prototype],
[Symbol(errored)]: null,
[Symbol(kUniqueHeaders)]: null
},
_currentUrl: 'https://poe.com/',
_timeout: null,
[Symbol(kCapture)]: false
},
cause: Error: connect ETIMEDOUT 128.242.245.93:443
at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
errno: -4039,
code: 'ETIMEDOUT',
syscall: 'connect',
address: '128.242.245.93',
port: 443
}
}

**Desktop (please complete the following information):**
 - OS/Device: Windows 11
 - Environment: cloud
 - Node.js version (if applicable): 18.16.0 x64
 - Browser: chrome
 - Generation API: Poe
 - Branch: main
 - Model: Claude

**Additional context**
Asked in discord, post here again for not missing any important info.
The IP in log is from VPN, changing ip don't work.

**Comment by bash99** [comment]
I got a similar error after download channal data.
```
Downloading next_data...
Downloading channel data...
Downloading https://poe.com/_next/data/nA40NpBklgK4lrWf3VY2B/Sage.json
Downloading https://poe.com/_next/data/nA40NpBklgK4lrWf3VY2B/GPT-4.json
Downloading https://poe.com/_next/data/nA40NpBklgK4lrWf3VY2B/Claude+.json
Downloading https://poe.com/_next/data/nA40NpBklgK4lrWf3VY2B/Claude-instant-100k.json
Downloading https://poe.com/_next/data/nA40NpBklgK4lrWf3VY2B/Claude-instant.json
Downloading https://poe.com/_next/data/nA40NpBklgK4lrWf3VY2B/ChatGPT.json
Subscribing to mutations
Websocket returned error: Error: connect ETIMEDOUT 103.252.114.61:443
```

But I don't where is those addtional log.

**Desktop (please complete the following information):**

- OS/Device: Debian 11 in WSL2
- Environment: WSL2
- Node.js version (if applicable): 18.16.0 x64
- Browser: chrome
- Generation API: Poe
- Branch: Dev

**Comment by bash99** [comment]
I think it's a problem what axios (or other underly libary) don't use proxy (or don't know how to use proxy) when doing websocket.

I use POE through a proxy I setup on a VPS, which always got timeout after successed to download those data.

So I just try setup SillyTavern on that VPS, and it works flawlessly.

**Comment by Amanoki** [comment]
I am also using a VPN and got exactly the same error. Have you solved it now?

**Comment by bash99** [comment]
> I am also using a VPN and got exactly the same error. Have you solved it now?

Use Tun to do it globally, config clash/v2ray use tun device.

**Comment by Amanoki** [comment]
> > I am also using a VPN and got exactly the same error. Have you solved it now?
> 
> Use Tun to do it globally, config clash/v2ray use tun device.

Thank you so much, it seems working. Though every time I send a message it says
```
Websocket ping timed out.
WebSocket died. Reconnecting...
```
and then initialize the client again every time before sending a reply. Is it normal?
Also, I am using Clash Windows, if I use Vmess proxy with tun mode, then it can connect to Poe API successfully. But if I use Shadowsocks proxy (which I normally use), it still shows error and fails to connect to API.
```
(cause: Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: poe.com. is not in the cert's altnames: DNS:*.atlassolutions.com, DNS:*.atdmt.com, DNS:*.atdmt2.com, DNS:*.atlassbx.com, DNS:*.xx.atlassbx.com, DNS:atdmt.com, DNS:atdmt2.com, DNS:atlassbx.com, DNS:atlassolutions.com, DNS:xx.atlassbx.com)
```
and so on. Do you have any idea what is causing this? Thank you for your help.

**Comment by bash99** [comment]
> > > I am also using a VPN and got exactly the same error. Have you solved it now?
> > 
> > 
> > Use Tun to do it globally, config clash/v2ray use tun device.
> 
> Thank you so much, it seems working. Though every time I send a message it says
> 
> ```
> Websocket ping timed out.
> WebSocket died. Reconnecting...
> ```
I don't got this error. I'm use nekobox when I need to tun all trafffic through vpn.

> ```
> (cause: Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: poe.com. is not in the cert's altnames: DNS:*.atlassolutions.com, DNS:*.atdmt.com, DNS:*.atdmt2.com, DNS:*.atlassbx.com, DNS:*.xx.atlassbx.com, DNS:atdmt.com, DNS:atdmt2.com, DNS:atlassbx.com, DNS:atlassolutions.com, DNS:xx.atlassbx.com)
> ```
> 
> and so on. Do you have any idea what is causing this? Thank you for your help.
This one looks like Clash messed up with dns record, I've got this before, after restart clash it will be ok for a few day.

**Comment by Amanoki** [comment]
I tried nekobox and ST still reconnects before returning every message. Nekobox seems to connect faster though. And shadowsocks with Clash now throw another different error. I seem to have no luck to get ST to work properly. Still thank you though.
