### ISSUE TITLE
[Feature Request] Read Subfolders for Character Cards

### ISSUE THREAD

**Issue by digiwombat** [SillyTavern/SillyTavern#436]
Listen, I gotta be honest. I have too many character cards. I'm seeing a guy about it.

So this isn't asking for #137, I don't want the UI to change at all since I think the tagging system achieves the filtering goal well. I really just want the character folder to allow subfolders so that the cards can be more organized on disk. This will also allow same-name characters or character alts without having to rename the files themselves. Since there's already a check in place as to whether a given file is a valid character card, it shouldn't interfere with the expressions folders.

Code should be pretty simple if you move the current code out into a function. Just pull the list of paths, check if fs.lstatSync(dirPath).isDirectory() and if it use, call the function recusively. EZPZ, bingo bango, no problem. Though when I tried putting something together I got a little error where the images wouldn't load and I didn't have time to dig any deeper into it.

**Comment by digiwombat** [comment]
The approach depends on how attached people are the setup as it exists now and ho.

My preference would be that characters+expressions are contained in a zip file (Alice.png or character.png inside Alice.zip file with expression files). Or a zip-file full of expressions which matches the character.png filename (Alice.png/Alice.zip in the same folder). The second format would make having people move over the easiest, while the first option would be the best for cutting down on file system clutter in the long run. The second format also makes grabbing files from services like chub.ai very easy since they provide zips with a workable structure. I imagine Lore could be coerced into including the character file in the zips as well if that was the direction it went. Files can also be easy added into zip files. But let's ignore those intrusive thoughts about changing the structure.

Without changing the setup at all, since expressions have a firm requirement (folder name matches a character.png name, Alice folder in the same folder as Alice.png) and none of the expressions will have valid character JSON in the PNG header, it should be pretty easy to match against named pngs that are in the same folder. So:

`Wholesome/Alice.png`  
will understand that looking in  
`Wholesome/Alice/`  
Should yield expression files that pertain to Alice.png in that folder.

The changes would should just require storing the subfolder the png exists in and appending the subfolder in the function that looks for expressions.

**Comment by stho90** [comment]
I would like that feature too 👍 
Currently, i am having over 200 character cards in my ST and more than 500 to check out for later.
Because of loosing overview, the other 500 cards are not added to ST yet.

**Comment by Cohee1207** [comment]
There are no plans for any kind of "folders" to be implemented.
