### ISSUE TITLE
[Feature Request] Character folders in list

### ISSUE THREAD

**Issue by bdashore3** [SillyTavern/SillyTavern#448]
**Have you searched for similar [requests](https://github.com/Cohee1207/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
Characters can become difficult to find after a certain amount are imported.

**Describe the solution you'd like**
Categorization of characters through user-configurable folders

**Additional context**
As discussed in Discord. This is a tracking issue to add character folders/groups so users can group characters depending on their characteristics, sfw/nsfw, etc.

**Comment by Neverdusk** [comment]
Absolutely. There are a group of characters I've made just for story writing purposes, and having them mixed in with everyone else is a mess. Being able to put them (and everyone else) into folders would be incredibly convenient. 

Otherwise, the ability to assign characters custom tags and then filter by those tags would also be really helpful.

**Comment by sialivi** [comment]
> Otherwise, the ability to assign characters custom tags and then filter by those tags would also be really helpful.

It already has that feature.

**Comment by Neverdusk** [comment]
> > Otherwise, the ability to assign characters custom tags and then filter by those tags would also be really helpful.
> 
> It already has that feature.

You're completely right. I realized that my SillyTavern was a bit behind, so I've updated it. 

It think it might still be nice to be able to visually organize characters into folders on the main character selection window. But my comments about tagging were definitely outdated - sorry for that.

**Comment by Woisek** [comment]
I also would like to see the option for optional folder sorting. Tags are nice, but folder feel more comfortably and direct. At least for me.

**Comment by Woisek** [comment]
A pity, but thanks for the info.
