### ISSUE TITLE
[Feature Request] A one-line description of a character under the character name in the character list

### ISSUE THREAD

**Issue by deskplace** [SillyTavern/SillyTavern#455]
**Have you searched for similar [requests](https://github.com/Cohee1207/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
When you get tons of characters, it's hard to remember who they all are

**Describe the solution you'd like**
A one-line description of a character under the character name in the character list. Cosmetic and for the UI only, not sent in any messages or anything.

**Describe alternatives you've considered**
For now I add a short description in parenthesis in the character name like Taylor (Police Officer), but this costs tokens ;(

**Comment by alicat22** [comment]
Tags?

**Comment by deskplace** [comment]
Sorry, never used the tags before! This accomplishes this feature
