### ISSUE TITLE
[Feature Request] Improvements for Chromadb usage

### ISSUE THREAD

**Issue by 7erminalVelociraptor** [SillyTavern/SillyTavern#463]
The current default strategy for chromadb works like this: The user sets x number of max chat history and y number of 'memories'. (lets ignore lenght of memories.

What happends when I type a message and hit enter?  The algorithm starts counting backwards and discards the chat history  after x messages, then if there is enought tokens left it  adds y memories if they get triggered, the  the entire prompt gets sent to whatever api hosts the model. 

Now, there are a number of usability problems with how this works. It puts a lot on the user to guestimate how much messages he needs to cut out and how much space that leaves. Even more so, 15 short sentences and replies can take as much space as 2 messages written with full paragraphs. Now the user also needs to babysit the slider because the lenght of messages vary.

Also it often happends that the chat history gets aggresivly cut off and not enough memories get triggered, and you are left with a prompt that's hundreds of tokens less than the max. I've seen prompts 600 tokens lower than the max, and that wasn't rare.

I suggest the following improvements.

First, give the user a toggle to count in tokens instead of number of messages. The limiting factor of the prompt is the token budget, and the maximum token amount is a lot less variable then how big the messages are.

Second, let's add a new strategy I'll call 'reserve and fill' that work with minimum instead of maximum. 

Example: have user set minimum amount of chat history (x), when generating prompt add history until either context max or (x) is reached. If there was any tokens left fetch any memories from chromadb that get triggered. If there is still space left then keep adding chat history until we hit the limit.

**Comment by Priestru** [comment]
You can use Token Padding with negative numbers to force ChromaDB to fill more data into prompt.

**Comment by 7erminalVelociraptor** [comment]
> You can use Token Padding with negative numbers to force ChromaDB to fill more data into prompt without tweaking sliders.

The issue isn't 'how can I trigger more memories', the issue is 'how do I make sure I'm not leaving context unused.'

**Comment by RossAscends** [comment]
in a recent update the 'max injection' and 'kept messages' sliders have been bumped up to allow 500 items each. 

this is enough to double fill a claude 100k prompt.

**Comment by 7erminalVelociraptor** [comment]
> in a recent update the 'max injection' and 'kept messages' sliders have been bumped up to allow 500 items each.
> 
> this is enough to double fill a claude 100k prompt.

I disagree that a larger maximum accomplishes my request. 

Having even higher maximums won't solve the issue of trying to find a good balance between chat history and chromadb memories, and making sure that the context budget doesnt get under utilized. If a user wants to just reserve a certain amount of context for chromadb (let's say 400 tokens) and wants to also make sure that any of the tokens chromadb doesn't use up get passe back up to the chat history, the only way to accomplish this now is to continually count chat messages and guesstimate and have your fingers crossed. And when the messages start varying in length he needs to do it again so it becomes a continual hassle. 

I believe the ability to choose minimum message amounts versus the current maximum only, and being able to count in tokens versus messages would be a huge QOL improvement. For this user he is already not using the sliders to the maximum, so an even higher maximum changes nothing.
