### ISSUE TITLE
[Feature Request] Format/cleaninig option to clean output received from backends with local models.

### ISSUE THREAD

**Issue by valden80** [SillyTavern/SillyTavern#478]
**Have you searched for similar [requests](https://github.com/Cohee1207/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
As I found, surprisingly many local models (most good ones otherwise) have specific behavior: they often adding double formatting symbols to the end of sentences. The cases with `**`, `""`, `''` - most annoying of them.

**Describe the solution you'd like**
Option with checkbox, to turn on globally filtering and replacing double symbols received output from backend's in their outputs: `** -> *`, `"" -> "`, `'' -> '`

**Describe alternatives you've considered**
Regexp extension, so user can setup what replace what he like by himself.

**Additional context**
None.

**Comment by valden80** [comment]
Yes, but earlier I don't seen, that the more primitive solution then full regexp extension possible - with replacing only three specific cases.

**Comment by RossAscends** [comment]
while i dislike the concept of micromanaging/formatting strings produced by specific models,  this could be handled in a similar way to the Instruct dinkus extension? @Cohee1207

**Comment by valden80** [comment]
Regexp extension is implemented, it's covering this issue, thanks.
