### ISSUE TITLE
[BUG] npm and sever issue

### ISSUE THREAD

**Issue by KL8436** [SillyTavern/SillyTavern#484]
> **Warning**. Complete **all** the fields below. Otherwise your bug report will be **ignored**!

**Have you searched for similar [bugs](https://github.com/Cohee1207/SillyTavern/issues?q=)?**
Yes/No
Yes
**Describe the bug**
Silly Tavern ran well for the first run atfter the installation. After restart the "start" batch file i receive this respond 

**Desktop (please complete the following information):**
 - OS/Device: Windows 10
 - Environment: [cloud, local]
 - Node.js version 18.16.0
 - Browser google chrome
 - Generation API Poe API
 - Branch [main, dev]
 - Model Poe Sage(i guess)
![InkedScreenshot (202)](https://github.com/SillyTavern/SillyTavern/assets/121068121/c5bbef6c-5ca8-4a7d-9739-2690146ede75)

**Comment by 500won** [comment]
I have the same issue. It's my first time downloading this I can't seem to start the program or anything.

**Comment by 500won** [comment]
You might have forgotten to run and install node.js

**Comment by TTGChamoy** [comment]
i solve this issue with the node installer, there is a section that says "repair". You only have to click there :D
