### ISSUE TITLE
[Feature Request] ChatGPT Demod Compatibility

### ISSUE THREAD

**Issue by TheCouncil1** [SillyTavern/SillyTavern#491]
**Have you searched for similar [requests](https://github.com/Cohee1207/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
Prompts can only be so effective at bypassing the ChatGPT filter. It can be a tedious and lengthy process to develop a successful prompt.

**Describe the solution you'd like**
SillyTavern is compatible with the [ChatGPT Demod](https://github.com/4as/ChatGPT-DeMod) userscript, which aids in bypassing the ChatGPT filter.

**Describe alternatives you've considered**
I have developed my own prompts and tweaked others and found great success; however, I have found ChatGPT Demod userscript to be a useful tool to reduce the amount of content violation notifications.

**Additional context**
It is worth mentioning that, in terms of OpenAI's response to the use of the userscript, the full ramifications of using ChatGPT Demod has not been documented. It is possible that using ChatGPT Demod could lead to OpenAI banning one's account.

Some information from their GitHub:

> This userscript for Tampermonkey and Greasemonkey allows you to disable moderation checks during conversations with ChatGPT, i.e. it will prevent "This content might violate our content policy" warnings from being triggered.
> 
> In particular this means that DeMod will:
> 1. Prevent your individual messages from being checked. Without DeMod each message will be sent to a moderation check.
> 2. Stops share function from working. Without DeMod opening the share dialog triggers a moderation check on the whole conversation.
> 3. Redirects any attempts at accessing a conversation directly through the URL (including refreshing the page) back to the "new chat" page. Without DeMod opening a conversation through a link triggers a moderation check on the whole conversation.

**Comment by TheCouncil1** [comment]
> Are you sure this is needed? We don't communicate with the ChatGPT's interface, but with the OpenAI APIs directly. It has much less strict filter and bypasses the moderation endpoint by default.

If that's the case, then please disregard. I'm still very new to this and am figuring things out. Thanks for the swift reply!

**Comment by coffeebrown0** [comment]
Demod does not help bypass the filter at all. It only suppreses the warning message provided by chatgpt flagging certain messages, which makes it more likely for a filter to be applied later.
