### ISSUE TITLE
Tree of Thoughts [Feature Request] 

### ISSUE THREAD

**Issue by nothingsuspiciousright** [SillyTavern/SillyTavern#510]
Good day!
I was thinking if it is possible to add this extension to the silly tavern?
https://github.com/kyegomez/tree-of-thoughts
It is said that models become much more 'logical/smarter' with it.

thank ya for reading,
nothingsuspicious

**Comment by 7erminalVelociraptor** [comment]
From what I can gather, that plugin works with the enginge actually hosting the model (ie. ooba Textgen, kobold.cpp or llama.cpp etc) As Sillytavern is just the frontend and doesn't actually host any models, this might be something to suggest at the git's of those programs.

**Comment by nothingsuspiciousright** [comment]
It has an option for openai to use with api key, so is it really?..

**Comment by Crataco** [comment]
@nothingsuspiciousright, after doing a little digging this is apparently the official repo for the Tree of Thoughts paper:
https://github.com/princeton-nlp/tree-of-thought-llm

It has this note at the very start of its README:
> *https://github.com/kyegomez/tree-of-thoughts is **NOT the correct implementation** to replicate paper results. In fact, people have reported that his code [cannot](https://github.com/kyegomez/tree-of-thoughts/issues/52) [properly](https://github.com/kyegomez/tree-of-thoughts/issues/41) [run](https://github.com/kyegomez/tree-of-thoughts/issues/60), and is [probably automatically generated by ChatGPT](https://github.com/princeton-nlp/tree-of-thought-llm/blob/master/fake.png), and [kyegomez has done so for other popular ML methods](https://twitter.com/qbitium/status/1663954096741814272), while **intentionally refusing to link to official implementations** for his own interests (see https://github.com/kyegomez/tree-of-thoughts/issues/54, https://github.com/kyegomez/tree-of-thoughts/issues/55, https://github.com/kyegomez/tree-of-thoughts/issues/56).*
