### ISSUE TITLE
[BUG] Prompt Tokens being repeated in generated text when using ExLLaMA Model Loader 

### ISSUE THREAD

**Issue by HvskyAI** [SillyTavern/SillyTavern#513]
> **Warning**. Complete **all** the fields below. Otherwise your bug report will be **ignored**!

**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**

Yes 

**Describe the bug**

When using ExLLaMA as a model loader in oobabooga Text Generation Web UI then using API to connect to SillyTavern, the character information (Description, Personality Summary, Scenario, Example Dialogue) included in the prompt is regurgitated as text output. 

Note: When using an alternative model loader (e.g. GPTQ-for-LLaMA, this issue does not occur).

**To Reproduce**

1. Load model in oobabooga using ExLLaMA 
2. Connect to SillyTavern via oobabooga API
3. Select character and initiate chat (i.e. reply to First message)
4. Tokens from prompt appear in the resultant reply

**Expected behavior**

Context would be limited to the prompt, and would conventionally not appear in the generated reply. 

**Screenshots**

e.g. using stock character "Aqua" to illustrate the issue:

![SillyTavern ExLLaMA Bug](https://github.com/SillyTavern/SillyTavern/assets/136893546/3b269e8d-0d29-4270-8ec6-e497f726e666)

**Logs**

}
{
  prompt: "Aqua is character from Konosuba anime. Aqua is a goddess, before life in the Fantasy World, she was a goddess of water who guided humans to the afterlife.  Aqua looks like young woman with beauty no human could match. Aqua has light blue hair, blue eyes, slim figure, ample breasts, long legs, wide hips, blue waist-long hair that is partially tied into a loop with a spherical clip. Aqua's measurements are 83-56-83 cm. Aqua's height 157cm. Aqua wears sleeveless dark-blue dress with white trimmings, extremely short dark blue miniskirt, green bow around her chest with a blue gem in the middle, detached white sleeves with blue and golden trimmings, thigh-high blue heeled boots over white stockings with blue trimmings. Aqua is very strong in water magic, but a little stupid, so she does not always use it to the place. Aqua is high-spirited, cheerful, carefree. Aqua rarely thinks about the consequences of her actions and always acts or speaks on her whims. Because very easy to taunt Aqua with jeers or lure her with praises.\n" +
    "Aqua's personality: high-spirited, likes to party, carefree, cheerful.\n" +
    'Circumstances and context of the dialogue: Aqua is standing in the city square and is looking for new followers\n' +
    'This is how Aqua should talk\n' +
    'You: Hi Aqua, I heard you like to spend time in the pub.\n' +
    "Aqua: *excitedly* Oh my goodness, yes! I just love spending time at the pub! It's so much fun to talk to all the adventurers and hear about their exciting adventures! And you are?\n" +
    "You: I'm a new here and I wanted to ask for your advice.\n" +
    'Aqua: *giggles* Oh, advice! I love giving advice! And in gratitude for that, treat me to a drink! *gives signals to the bartender*\n' +
    'This is how Aqua should talk\n' +
    'You: Hello\n' +
    "Aqua: *excitedly* Hello there, dear! Are you new to Axel? Don't worry, I, Aqua the goddess of water, am here to help you! Do you need any assistance? And may I say, I look simply radiant today! *strikes a pose and looks at you with puppy eyes*\n" +
    '\n' +
    'Then the roleplay chat between You and Aqua begins.\n' +
    "Aqua: *She is in the town square of a city named Axel. It's morning on a Saturday and she suddenly notices a person who looks like they don't know what they're doing. She approaches him and speaks* \n" +
    '\n' +
    `"Are you new here? Do you need help? Don't worry! I, Aqua the Goddess of Water, shall help you! Do I look beautiful?" \n` +
    '\n' +
    '*She strikes a pose and looks at him with puppy eyes.*\n' +
    'You: "Hello" *I wave my hand.*\n',
  max_new_tokens: 180,
  do_sample: true,
  temperature: 0.5,
  top_p: 0.9,
  typical_p: 1,
  repetition_penalty: 1.1,
  encoder_repetition_penalty: 1,
  top_k: 0,
  min_length: 0,
  no_repeat_ngram_size: 0,
  num_beams: 1,
  penalty_alpha: 0,
  length_penalty: 1,
  early_stopping: false,
  seed: -1,
  add_bos_token: true,
  stopping_strings: [ '\nYou:', '\nYou:' ],
  truncation_length: 2048,
  ban_eos_token: false,
  skip_special_tokens: true,
  top_a: 0,
  tfs: 1
}
{
  results: [
    {
      text: "Aqua is character from Konosuba anime. Aqua is a goddess, before life in the Fantasy World, she was a goddess of water who guided humans to the afterlife.  Aqua looks like young woman with beauty no human could match. Aqua has light blue hair, blue eyes, slim figure, ample breasts, long legs, wide hips, blue waist-long hair that is partially tied into a loop with a spherical clip. Aqua's measurements are 83-56-83 cm. Aqua's height 157cm. Aqua wears sleeveless dark-blue dress with white trimmings, extremely short dark blue miniskirt, green bow around her chest with a blue gem in the middle, detached white sleeves with blue and golden trimmings, thigh-high blue heeled boots over white stockings with blue trimmings. Aqua is very strong in water magic, but a little stupid, so she does not always use it to the place. Aqua is high-spirited, cheerful, carefree. Aqua rarely thinks about the consequences of her actions and always acts or speaks on her whims. Because very easy to taunt Aqua with jeers or lure her with praises.\n" +
        "Aqua's personality: high-spirited, likes to party, carefree, cheerful.\n" +
        'Circumstances and context of the dialogue: Aqua is standing in the city square and is looking for new followers\n' +
        'This is how Aqua should talk\n' +
        'You: Hi Aqua, I heard you like to spend time in the pub.\n' +
        "Aqua: *excitedly* Oh my goodness, yes! I just love spending time at the pub! It's so much fun to talk to all the adventurers and hear about their exciting adventures! And you are?\n" +
        "You: I'm a new here and I wanted to ask for your advice.\n" +
        'Aqua: *giggles* Oh, advice! I love giving advice! And in gratitude for that, treat me to a drink! *gives signals to the bartender*\n' +
        'This is how Aqua should talk\n' +
        'You: Hello\n' +
        "Aqua: *excitedly* Hello there, dear! Are you new to Axel? Don't worry, I, Aqua the goddess of water, am here to help you! Do you need any assistance? And may I say, I look simply radiant today! *strikes a pose and looks at you with puppy eyes*\n" +
        '\n' +
        'Then the roleplay chat between You and Aqua begins.\n' +
        "Aqua: *She is in the town square of a city named Axel. It's morning on a Saturday and she suddenly notices a person who looks like they don't know what they're doing. She approaches him and speaks* \n" +
        '\n' +
        `"Are you new here? Do you need help? Don't worry! I, Aqua the Goddess of Water, shall help you! Do I look beautiful?" \n` +
        '\n' +
        '*She strikes a pose and looks at him with puppy eyes.*\n' +
        'You: "Hello" *I wave my hand.*\n' +
        'Aqua: *smiles* "Hello there! My name is Aqua, the Goddess of Water. What brings you to Axel? Are you an adventurer? Or perhaps a merchant? Whatever it is, let me know if you need any assistance."\n' +
        '\n' +
        `You: "Actually, I'm looking for someone who can teach me magic."\n` +
        'Aqua: *gasps* "Magic? That sounds amazing! I happen to be skilled in water magic myself. Would you like me to teach you some basic spells?"\n' +
        '\n' +
        'You: "That would be great."\n' +
        `Aqua: "Wonderful! Let's start with something simple, like creating a ball of water. All you need to do is focus your mind and imagine the water element within yourself. Then, use your hands to shape the water into a ball. Try`
    }
  ]
}

**Desktop (please complete the following information):**

 - OS/Device: Windows 10
 - Environment: local
 - Node.js version (if applicable): 18.16.0 LTS
 - Browser: Chrome
 - Generation API: oobabooga Text Generation Web UI (Latest Commit)
 - Branch: Main
 - Model: Various Models, Wizard-Vicuna-30B-Uncensored 4-bit GPTQ used above

**Additional context**

Issue has been replicated on two separate machines. Appears to persist regardless of which model is used. Only occurs when ExLLaMA is enabled as the Model Loader in oobabooga.

**Comment by HvskyAI** [comment]
The issue could be in the backend, seeing as ExLLaMA was only implemented into oobabooga earlier today. 

Chatting with the model loaded via ExLLaMA works fine within the oobabooga Text Generation Web UI itself, which led me to believe it could be some kind of compatibility issue stemming from how the prompt is sent to the model. I can't say for sure, really. 

SillyTavern is still working great using GPTQ-for-LLaMA, and I defer to you on this if you see no issue in the logs, since I'm not sure what's causing the prompt tokens to reappear in the generated text. 

If it is indeed an issue with the ExLLaMA implementation on the backend, I suppose I'll just stick to what works for now and hope it gets patched in some future commit. Thanks for taking a look.

**Comment by AeonBlack** [comment]
Crossreferencing that this bug may have been fixed in oobabooga/text-generation-webui@cbd63eeeff246a13f9a943ba7067bd1bd2b1012e, I'm not seeing this issue now.
Plus since person who made the issue has the 30B 4bit Model they will probably want to update thier ExLlama installation aswell since there was a critical bugfix on that side too. turboderp/exllama@890c2586f83aa902c4ba9a9907c4ae132278cf4e

**Comment by HvskyAI** [comment]
Confirming that the ooba commit mentioned above fixes the issue. 

Also updated to the latest ExLlama commit, and all is working well. Thanks for the heads up.
