### ISSUE TITLE
[Feature Request] Option to allow Multigen to exceed Response Length (tokens) until EOS

### ISSUE THREAD

**Issue by AeonBlack** [SillyTavern/SillyTavern#524]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
- Multigen will stop at the Response Length (tokens) even if there is more text to generate.
- This can leave short responses or truncated lines if set too short.
- This can reduce context size if set too high and Context Size (tokens) hasn't been changed causing the context to get truncated earlier.

**Describe the solution you'd like**
- An option to ignore Response Length (tokens) for the limit, since there may be points where you want to limit how much text is generated,
- Also if Multigen is set to true, maybe have a slider with better descript for "Maximum Content Generated".
- The internal equivalent to Response Length (tokens) should be set to First chunk (tokens) or Next chunks (tokens) while the new option is true.

**Describe alternatives you've considered**
- Currently working around the issue by setting Response Length (tokens) to [ 1024 ].
- And Context Size (tokens) to [ Model's Max Context Size ]  + [ Response Length (tokens) ] - [ First chunk (tokens) ]
- In my case 2048 + 1024 - 200 = 2872

**Additional context**
- This is possibly also a bug as the behavior looks like it could be unintended.

**Comment by iChristGit** [comment]
Did you find a Fix?

**Comment by AeonBlack** [comment]
No longer applicable as Multigen was removed.

**Comment by iChristGit** [comment]
> No longer applicable as Multigen was removed.

Its not only on multigen, all of the api's are locked to 1024 reponse length..
