### ISSUE TITLE
[Feature Request] : Showing the numbers of total messages/chats in the Character sidebar

### ISSUE THREAD

**Issue by ahmed-elj** [SillyTavern/SillyTavern#548]
**_Goal:_** It will be nice to really see how `Most Chats` sort function actually works under the hood.

I suggest having two Permanent labels on top of the character image on the character sidebar showing numbers of how many messages and how many chats have been created.

**Comment by lorffine** [comment]
![247898956-0c84e4f0-9aa7-490b-9033-cb17ef3175e6](https://github.com/SillyTavern/SillyTavern/assets/31710770/97bb3694-1a62-4842-97be-7f4cf910c687)
Here is a Concept, the right one is how many messages, and the left one how many chats
