### ISSUE TITLE
[QUESTION]: Can't connect to oobabooga

### ISSUE THREAD

**Issue by Woisek** [SillyTavern/SillyTavern#562]
**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the question**
I have oobabooga up and running, everything works. --api is enabled
I start SillyTavern, click on API, select the Text Gen WebUI ooba and click connect, but it doesn't connect. The URL given is the one ooba runs on, plus the /api appended. Loading this address gives:
{"detail":"Not Found"}

**To Reproduce**
I start SillyTavern, click on API, select the Text Gen WebUI ooba and click connect, but it doesn't connect. 

**Expected behavior**
SillyTavern should connect

**Screenshots**

**Logs**
Already up to date.

changed 1 package, and audited 345 packages in 5s

40 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Running from source
SillyTavern 1.7.1 'main' (c873a6b0)
Launching...
SillyTavern is listening on: http://0.0.0.0:8000/

0.0.0.0 means SillyTavern is listening on all network interfaces (Wi-Fi, LAN, localhost). If you want to limit it only to internal localhost (127.0.0.1), change the setting in config.conf to “listen=false”

**Desktop (please complete the following information):**
 - OS/Device: Windows 10
 - Environment: local
 - Node.js version (if applicable): v18.16.0
 - Browser Firefox 114
 - Generation API oobabooga
 - Branch main
 - Model Imablank_P1GM4L10N-7B-MERGED_WEIGHTS

**Additional context**

**Comment by Woisek** [comment]
There you go ...

![Zwischenablagebild (2)](https://github.com/SillyTavern/SillyTavern/assets/122026301/a3251dbb-acad-411c-b785-427176fa01c9)

Thanks for looking into it.

**Comment by Woisek** [comment]
Aah ... sorry, I totally missed that. It's right at the beginning. 🙄
Thanks for giving me the right direction. 👍

**Comment by aubisoka-solutions** [comment]
I also cannot connect,..... the checkbox from the screenshot is not visible in my case and I cannot select Text Gen. If I select the default, I need to provide an API Key from oobaboooga.... but there is no API key.....

**Comment by Cohee1207** [comment]
The API key is not required for ooba, it even says (optional). The screenshot is outdated due to the API being rewritten and transformed into Text Completion type, with Default being the ooba option.
