### ISSUE TITLE
[Feature Request] GPT4All API

### ISSUE THREAD

**Issue by larry743223** [SillyTavern/SillyTavern#592]
Add this https://github.com/nomic-ai/gpt4all as an API.

**Comment by Yama-K** [comment]
Any progress on this?

**Comment by Yama-K** [comment]
I don't know, it's local, the only reason really

**Comment by Teashrock** [comment]
@Cohee1207 
The official website says it uses CPU instead of GPU or Internet. I don't know how is this possible, it just says so.
