### ISSUE TITLE
[BUG] /getstatus returning invalid response while using KoboldCPP

### ISSUE THREAD

**Issue by duncannah** [SillyTavern/SillyTavern#595]
**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
While using KoboldCPP, sometimes when the ST client checks for the status using the `/getstatus` endpoint, the ST server returns an invalid response (HTTP headers included in response body):
![image](https://github.com/SillyTavern/SillyTavern/assets/38371914/06dbc0ae-47a1-446c-ae19-81d0ab6cda96)
Since this invalidates the saved KoboldCPP version, it disables the token streaming.

**To Reproduce**
1. Connect to a KoboldCPP API
2. Wait a while until the client checks for the status (I think 5 minutes, looking into the code)
3. The client thinks that the Kobold API doesn't support token streaming

**Expected behavior**
The endpoint to serve a valid JSON response.

**Screenshots**
Check above.

**Logs**

![image](https://github.com/SillyTavern/SillyTavern/assets/38371914/638a9f97-708b-4daf-9dac-c77027693520)

**Desktop (please complete the following information):**
 - OS/Device: Docker on Ubuntu 20.04 (using the [Dockerfile](https://github.com/SillyTavern/SillyTavern/blob/main/Dockerfile) in repo)
 - Environment: local
 - Node.js version (if applicable): 19.1.0
 - Browser: Chrome
 - Generation API: KoboldCPP
 - Branch: dev
 - Model: Chronos-Hermes 13B

**Comment by BlipRanger** [comment]
Attempted with Docker ST + KoboldCPP on the latest version and could not recreate the issue. What version of KoboldCPP are you running?
![image](https://github.com/SillyTavern/SillyTavern/assets/1860540/46461830-d557-4b4e-ae8e-b1dc0ddd5ef6)

**Comment by duncannah** [comment]
Seems to be a KoboldCPP issue, replicated using a REST API debugger against its own API
