### ISSUE TITLE
[Feature Request]: Translate current text in chat bar

### ISSUE THREAD

**Issue by Woisek** [SillyTavern/SillyTavern#603]
I have notice how useful the chat translation is.
But more often now, I find myself doing cumbersome swapping between ST and the deepl website. Because English is not my first language, I have to sometimes translate what I want to chat. Tat means I have to switch to deepl, enter text and translate it and copy, then switch back to ST and paste it.
I think it would be very convenient, if we had an additional entry under the extensions icon like 'translate (current) message'.
It then would translate the entered text to English and we then only need to send it.

I know about the translation extension but somehow, I'm not sure if it does that how I mean it should do it. It's not working right for me.

I hope this is worth considering. 🙂

**Comment by Woisek** [comment]
@Cohee1207 Thanks, I pointed out that I have seen this. 

>It will be sent to AI in English while displayed in your native language.

That's exactly why I don't like this for two reasons:
1. The text stays at is (i.e., German) and makes the chat inconsistent (what happens when such language mix chat this is ex- and re-imported?) 
2. I have no control if the translation was correct or used the right words.

I thought, if the option "Translate chat" is there, we could have the option "Translate chat bar" where the inputted gets translated, and then replaced by the translated text. This way we can see how it was translated and could edit it in case it is needed, before sent to the chat.

It's a bit like the same idea like my feature request for SD refined prompts (which, I think, nobody has looked at it so far).

**Comment by Wolfsblvt** [comment]
This request was implemented in April by #2150 and can be closed.
