### ISSUE TITLE
[Feature Request] Multiplayer similar to AI Dungeon

### ISSUE THREAD

**Issue by Kikasuru** [SillyTavern/SillyTavern#614]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
Not particularly a problem persay, but I was thinking it'd be fun to have more than just AI characters in a group, another player that can play with you!

**Describe the solution you'd like**
All AI prompts will be calculated on the main server where the owner of the group is.  The server can generate a room with something like WebRTC and send the code to a friend.  Said friend can chat with their name, set in User Settings (It's recommended to set both players to something other than "You", though it could work similarly in second person where the server player is "You" and the other player is another character.) and prompt an AI in the group, 

**Additional context**
[Multiplayer (AI Dungeon Wiki)](https://wiki.aidungeon.io/wiki/Multiplayer)

**Comment by erasmus74** [comment]
Hi, I would like to see if this can be revisted. Most specifically, I'd like to understand what the limits are here and if there is things I can contribute.

I see STMP exists which seems like a very slimmed down version of ST, Ideally, I think the most simplified way to make this work would be allow a person to join the chat AS a specific character card, and then simply change the functions that generate for that card (in groups maybe idk), to just allow the user to provide input. This can then be fed to the LLM, vectorized, etc.

I'm happy to code and contribute or test and build, or if its considered Out of scope still, strike the challenge on my own. Thanks in advance!
