### ISSUE TITLE
[Feature Request] Profiles for settings to hotswap

### ISSUE THREAD

**Issue by 7erminalVelociraptor** [SillyTavern/SillyTavern#644]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
As someone who experiments a lot with different models and also likes to hotswap models during chats, every time I swap a model I need to check if it uses an instruct prompt and what style and set it, adjust the generator / temp settings too, and with superhot models now I need to switch between context sizes too. Switching models in kobold.cpp takes me almost zero effort, but re-configuring ST is annoying and especially the need to look up the settings wheter online or written down is also a nuisance.

**Describe the solution you'd like**
A bunch of named buttons or dropdown list that lets you hotswap between settings profiles with only one click.

**Describe alternatives you've considered**
Writing jsons for different prompt styles when needed, input settings by hand

**Additional context**
Being able to easily swap generator related setting profiles is a good stepping stone for further automation, for example in the future having api's send the model id which ST can use to switch to a set model profile without active user intervetion.

**Comment by powellnorma** [comment]
Agree, this seems like an essential feature to me. Every model comes with its own unique set of configs (Recommended Samplers, Stopping Strings, Prompting Template, Basic Roleplay System Prompt, ...).

It can take quite some time to figure out the "perfect settings" for a given model. It looks like currently there is no way to "remember" those settings, when we move on to a new model? Or am I missing something?

**Comment by Cohee1207** [comment]
Quick switching prompt formatting and settings is possible using STscript and Quick Replies. There's a set of commands for `/context`, `/instruct`, `/preset`, etc.
