### ISSUE TITLE
[BUG] The small error in one default background image

### ISSUE THREAD

**Issue by ZhouZhengDao** [SillyTavern/SillyTavern#645]
**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes, I searched for issues related to the background and did not find any relevant reports.

**Describe the bug**
This is merely an inconsequential detail, hardly worth considering as a bug. Among the background images provided by default, there is one labeled 'japan university,' but in that particular image, the signage on the wall (pillar?) is actually written in Korean.

**To Reproduce**
1. Go to 'Change Background Image'
2. Click on 'japan university'
3. Voilà! Korean has appeared.

**Expected behavior**
It seems that the Korean text in the picture actually means 'SillyTavern,' so if we were to express it in Japanese, perhaps 'バカバカしい酒場' would be more appropriate. (This is just a personal translation, as I only knowing a little Korean and Japanese.)

**Screenshots**
![20230706210056](https://github.com/SillyTavern/SillyTavern/assets/138819540/89616640-c321-4bde-ac93-255ddcbeae86)

**Logs**

I believe that logs and configurations are not necessary in this bug report.

**Desktop (please complete the following information):**
 - OS/Device: 
 - Environment: 
 - Node.js version (if applicable): 
 - Browser
 - Generation API
 - Branch
 - Model

**Additional context**
This is just a minor issue I noticed while waiting for the model to load and randomly changing backgrounds. I want to express my sincere gratitude to every member of the SillyTavern team for their hard work. You all have done an amazing job!

**Comment by RossAscends** [comment]
easter egg finally unlocked.

**Comment by AyaAyaYoshikawa** [comment]
HAVE NOT BEEN CORRECTED yet, so this ticket should be turned to open. 
If this school is that of Japan, the plate should be written in Japanese, and if that of Korean, the photo title must be changed to Korean University.
This may relate to someone's political aim, so should be corrected immediately.
