### ISSUE TITLE
[Feature Request] Regexp ergonomic

### ISSUE THREAD

**Issue by valden80** [SillyTavern/SillyTavern#659]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes.

**Is your feature request related to a problem? Please describe.**
With regexp testing I come to this fact:  various local models typically can have most benefits with different regexp sets. Right now there is no possibility to change set of working regexps quick - possible only to create and delete them.

**Describe the solution you'd like**
Option to "pause" regexps individually. As a checkboxes near the create and delete options in the list of regexps. To pause them without need to remove and recreate.

**Describe alternatives you've considered**
Profile switch system to change active regexp sets at once.

**Additional context**
None.

**Comment by valden80** [comment]
@bdashore3 Thanks, I missed it.

Please, also explain what is "Only Format Display" and "Subtitute Regex" do exactly? For me they are not intuitive...

**Comment by IkariDevGIT** [comment]
sorry for the tag @bdashore3, i dont know if its worth opening another feature request issue.
Could you please add an option to re-arrange the regex "scripts", as i need to run some scripts before others. and if i need to add one that needs to be run at the start.. well.. i need to change all of them up.
