### ISSUE TITLE
[Feature Request] Easy Persona switch, leads to play as multiple characters (with a concept)

### ISSUE THREAD

**Issue by lorffine** [SillyTavern/SillyTavern#668]
I suggest a quick button switch between each persona, here is a quick concept i made:
![gzegez](https://github.com/SillyTavern/SillyTavern/assets/31710770/437c6cf8-b018-46a6-b0f3-6b1500068c84)

___________________________________________________________________________________________________________________________________________
And to make what persona you're using right now more obvious:
![vivaldi_VHBcIk35q2](https://github.com/SillyTavern/SillyTavern/assets/31710770/0cae245e-1daf-44f8-817c-ae90751a1d8b)

This feature add the ability to play as multiple characters at the same time, similar to group chat, but as (you)
Hope you like it <3

**Comment by aetherwu** [comment]
I remember that orginal TavernAI applies similar flow. You can click an avatar on the right, then talk to him/her directly in current converstaion window and its avatar.

**Comment by ahmed-elj** [comment]
@aetherwu do you mean the one in a "room"? because i think you misunderstood my concept. i am thinking of an easy name switch so that in the input of the prompt will be like
```
(you) | persona1: ...
(AI)  | character: ...
(you) | persona2: ...
```
so you play as multiple character while the real {{user}} stay Persona1 your main one, selected in the persona tab.

**Comment by aetherwu** [comment]
> @aetherwu do you mean the one in a "room"? because i think you misunderstood my concept. i am thinking of an easy name switch so that in the input of the prompt will be like
> 
> ```
> (you) | persona1: ...
> (AI)  | character: ...
> (you) | persona2: ...
> ```
> 
> so you play as multiple character while the real {{user}} stay Persona1 your main one, selected in the persona tab.

No. It's TavernAI but not SillyTavern. 

You can try it here:
https://colab.research.google.com/github/TavernAI/TavernAI/blob/main/colab/GPU.ipynb

You don't need to create a room to switch characters you are talking to mentioning at. It brings flexibility but may also be confusing for new users (to control the storyline.)

**Comment by ahmed-elj** [comment]
@aetherwu yeah, that make sense, i didn't notice that before

**Comment by Cohee1207** [comment]
I made an extension that does that. Sorry it took only half a year lol
https://github.com/SillyTavern/Extension-QuickPersona

**Comment by ahmed-elj** [comment]
@Cohee1207 oh wow, you actually did it
Thank you for listening

**Comment by aetherwu** [comment]
> @aetherwu do you mean the one in a "room"? because i think you misunderstood my concept. i am thinking of an easy name switch so that in the input of the prompt will be like
> 
> ```
> (you) | persona1: ...
> (AI)  | character: ...
> (you) | persona2: ...
> ```
> 
> so you play as multiple character while the real {{user}} stay Persona1 your main one, selected in the persona tab.

O I see. I thought you want to change "The AI char instantly without change current timeline." which brings more flexbility.
It affects the current structure (timeline vs groupchat) and not easy to implement.
