### ISSUE TITLE
[BUG] Objective extension not working as expected

### ISSUE THREAD

**Issue by Proxeimity** [SillyTavern/SillyTavern#677]
**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes, But it seems to be that this is the first it broke.

**Describe the bug**
I've created a new chat with a character and tried to set an objective using the "Auto-Generate Tasks" function, but instead of creating a list of tasks, it came back with a "0 Task Generated".

**To Reproduce**
	1. Set API to Poe.
	2. Start a new chat
	3. Go to Extensions
	4. Scroll to Objective
	5. Create an objective
	6. Press Auto-Generate Tasks

**Expected behavior**
Create a list of tasks.

**Screenshots**
![Screenshot (4)](https://github.com/SillyTavern/SillyTavern/assets/119641150/0a9a3ead-85dd-4a77-86df-d2d7a11d0f78)
![Screenshot (5)](https://github.com/SillyTavern/SillyTavern/assets/119641150/247db44e-cc8f-4068-aa9b-d071fb01459b)

**Logs**
No error was found in the log, only incorrect behavior.

**Desktop (please complete the following information):**
 - OS/Device: windows 10 & 11
 - Environment: local
 - Node.js version: v20.3.1
 - Browser: chrome, firefox
 - Generation API: POE, Kobold-Horde
 - Branch: dev
 - Commit: 3548f467
 - Model: ChatGPT-3.5, Claude-instant

**Additional context**
Upon monitoring the activity from the terminal. A usual command is not sent to notify the AI to stop and give an example of how to create the list of tasks, specifically the command below:

---
Then the roleplay chat between USER and CHARACTER begins.
CHARACTER: First message or Last message.
USER: Pause your roleplay and generate a list of tasks to complete an objective. Your next response must be formatted as a numbered list of plain text entries. Do not include anything but the numbered list. The list must be prioritized in the order that tasks must be completed.

    The objective that you must make a numbered task list for is: [YOUR OBJECTIVE].
    The tasks created should take into account the character traits of CHARACTER. These tasks may or may not involve USER directly. Be sure to include the objective as the final task.

    Given an example objective of 'Make me a four course dinner', here is an example output:
    1. Determine what the courses will be
    2. Find recipes for each course
    3. Go shopping for supplies with USER
    4. Cook the food
    8. Get USER to set the table
    9. Serve the food
    10. Enjoy eating the meal with USER
---

Since the command was not inserted, it auto-generates the conversion instead.

**Comment by Woisek** [comment]
I experienced this problem a longer time ago. I created an object (the example from the docs) and no tasks where created.
I use ooba as api.
