### ISSUE TITLE
[Feature Request] Reference WI from character description

### ISSUE THREAD

**Issue by Teashrock** [SillyTavern/SillyTavern#682]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
It's a bit strange that I can reference world info only in written text, but not in character descriptions.

**Describe the solution you'd like**
Maybe it would be useful to implement world info toggle option "Lookup WI entries in character sheet"? It would really help to extend world info for characters.

**Describe alternatives you've considered**
An alternative would be implementing this option in character file itself.

**Additional context**
None.

**Comment by 7erminalVelociraptor** [comment]
Just speaking for myself, I'm not sure if that would be a very helpful feature. It only saves you the effort of copy pasting info once, while any keyword in char description will *always* get triggered and eat up tokens, while not necesarily what the user wants. 

Imo I'm not seeing a huge usability benefit and imo context control > convenience.

**Comment by Teashrock** [comment]
@Cohee1207 
@7erminalVelociraptor 
The idea is making character description able to depend on WI, if the author wants this, or uses multiple characters in their own world unrelated to known media.

**Comment by Teashrock** [comment]
@Cohee1207 
I meat being able to access WI directly from character description.
Like: There is a world entry with a word "Stalburg mushrrom". And you are making a character who likes to eat Stalburg mushrooms. But there's an inconvenience: even if you specify "Stalburg mushroom" in character description, ST will not catch it up, so the AI won't know what this is, and will just make the answer up. To avoid this, you need either mention the word directly in a reply or AN (which goes a bit beyond character creation), or go to WI and enable constant insertion of the needed info. It's not convenient if, for example, you're playing in a group chat with characters using the same lore. Then you will need to enable entries for every character in the chat! It's not very convenient. That's why I imagined this option.

**Comment by Cohee1207** [comment]
Your WI can now access the author's note during scanning (if enabled).
https://github.com/SillyTavern/SillyTavern/pull/1239

**Comment by Teashrock** [comment]
@Cohee1207 
Closing this, as Character's Note can now achieve what I needed. Thank you for implementing it, and for your hard work.
