### ISSUE TITLE
[Feature Request] Allow pictures for world info entries

### ISSUE THREAD

**Issue by Culpeo** [SillyTavern/SillyTavern#723]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
While using SillyTavern I'm creating a lot of characters, locations, etc. that I'm keeping track of in the lorebook. I'm also using Stable Diffusion to create matching pictures. It would be great if these pictures could be attached to the lorebook.

**Describe the solution you'd like**
It should be possible to attach one picture per world editor entry. You can do this by clicking on a button that allows you to upload a picture from your computer.

**Describe alternatives you've considered**

**Additional context**
The new Kobold AI UI has this feature, something similar might work in SillyTavern as well.

![image](https://github.com/SillyTavern/SillyTavern/assets/8376959/f7c70a0e-b1a8-41fa-94f3-8f60eb898c9a)

**Comment by coupdegracie** [comment]
Seconded, this would be a really useful feature.

**Comment by MerijnHendriks** [comment]
Sorry for replying to a closed issue. I would really love to have this! That way when sharing characters online, one could get images that explain things that are very hard to explain in words.
