### ISSUE TITLE
[BUG] Samplers order can't be changed in any mobile browser

### ISSUE THREAD

**Issue by Zerogoki00** [SillyTavern/SillyTavern#724]
> **Warning**. Complete **all** the fields below. Otherwise your bug report will be **ignored**!

**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
It's impossible to change the samplers order on mobile browser. The samplers can't be dragged unless you have a mouse cursor. I had to connect a mouse using OTG cable to drag them

**To Reproduce**
1. Open SillyTavern UI on mobile browser (same with Chrome and Firefox)
2. Open settings
3. Try to change the samplers order

**Expected behavior**
It should be possible to change samplers orders on any device

**Screenshots**
screen recording: [YouTube](https://www.youtube.com/watch?v=jK2hNXZd1l4)
screenshot after connecting mouse: [imgur](https://i.imgur.io/wjIHmka_d.webp?maxwidth=640&shape=thumb&fidelity=medium)

**Logs**

Can't take logs from mobile browser because there is no console

**Desktop (please complete the following information):**
 - OS/Device: Android 13, Google Pixel 7 Pro
 - Environment: local
 - Node.js version (if applicable):v19.1.0
 - Browser: Firefox Nightly 117.0a1 mobile, Google Chrome 114.0.6735.196 mobile
 - Generation API koboldcpp
 - Branch main
 - Model airoboros-33b-gpt4-1.4-superhot-8k

**Comment by Cohee1207** [comment]
Should be fixed now in new branches

**Comment by Zerogoki00** [comment]
Thanks, now it works
