### ISSUE TITLE
[BUG] Poe.com is broken in main branch

### ISSUE THREAD

**Issue by Cohee1207** [SillyTavern/SillyTavern#74]
### [BUG] Poe.com is broken in main branch
Switch to dev branch if you use that. Thanks.

**Comment by BannedMan** [comment]
what and how to do that?

**Comment by Sydero** [comment]
> Poe added a new header requirement that breaks reversed client.
> 
> Do `git clone` with `--branch dev` argument (recommended). Or switch repo branch to dev and download ZIP (less recommended)

How do you do that on mobile? (for colab)

**Comment by RossAscends** [comment]
There currently is no colab for dev branch.

**Comment by Sydero** [comment]
im not understanding where to place the --branch dev on the git clone line.

**Comment by Vantagevoin** [comment]
Is Poe.com broken again? It's throwing the error again even on the dev branch.

**Comment by daiikichiii** [comment]
I feel bad for you bro, because is not working again...

**Comment by Sydero** [comment]
yeah it's not working on the main or dev branch 💀

**Comment by RayDiValentino** [comment]
can confirm, dev branch poe is dead, thought it was just me for a hot minute-

thanks for all your hard work though. we all really appreciate it.

**Comment by BannedMan** [comment]
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF*CK

**Comment by BannedMan** [comment]
now I have to learn to use it on some google colab
