### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mistyyk** [SillyTavern/SillyTavern#740]
Well, I'm going to use Google translate as my English isn't the best.  My problem is the following, I've been trying to crash the API for a day or two, but I can't, I'm using Poe.com in the Kiwi Browser, but every time I change the API it says "Token expired or invalid", which what I do?
thanks for reading

**Comment by unstablefreak** [comment]
man i thought I'm the only one who got that bug:/

**Comment by Cohee1207** [comment]
Poe is no longer supported.
