### ISSUE TITLE
[BUG] Horde error in terminal, no generation, logs in post

### ISSUE THREAD

**Issue by SAWSYSTEM** [SillyTavern/SillyTavern#743]
**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
No responses from Horde API

**To Reproduce**
1. Go to API window in ST.
2. Click on 'KoboldAI Horde'
3. Pick a model.
4. Type and send a message.
5. See error in terminal.

**Expected behavior**
A response from Horde.

**Screenshots**
![image](https://github.com/SillyTavern/SillyTavern/assets/132638464/077789ea-2d85-4292-ae45-b16274d758a0)

**Logs**
In screenshot above.

**Desktop (please complete the following information):**
 - OS/Device: [Windows 10]
 - Environment: [local]
 - Node.js version (if applicable): [V19.1.0]
 - Browser [Chrome]
 - Generation API [KoboldAI Horde]
 - Branch [main]
 - Model [Any]

**Additional context**
Been having this error for a little while now, maybe less than a week?

**Comment by Cohee1207** [comment]
Not reproduced for me. Make sure you input the correct API key for Horde.

**Comment by Cohee1207** [comment]
Stale issue.
