### ISSUE TITLE
[BUG] Poe.com fetch failed

### ISSUE THREAD

**Issue by 0mniSci** [SillyTavern/SillyTavern#744]
> **Warning**. Complete **all** the fields below. Otherwise your bug report will be **ignored**!

**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
Whenever you try to regenerate a new response, or type a new message, it generates a fetch failed error in the console.

**To Reproduce**
1. Click on 'Regenerate Response' or 'Send a new message'
2. See error

**Expected behavior**
Whenever you click on regenerate response or send a new message, it is supposed to generate a new message.

**Logs**

  method: 'POST',
  body: '{"variables":{"count":5,"cursor":null,"id":"Q2hhdDoxMTI4MDI5MA=="},"queryName":"ChatListPaginationQuery","extensions":{"hash":"1ba2ab6a4d133b585a848f04bcb10a6bf33c0bf7f07a86aa2970b88900d82ed6"}}',
  headers: {
    'poe-formkey': '8468132653ed64257a18c0f5d57ba075',
    'poe-tchannel': 'poe-chan58-8888-qojqewiiiiqyutvhusng',
    Cookie: 'hidden',
    'poe-tag-id': '563bfd6b508a46509c58c95271ab915f',
    'content-type': 'application/json'
  }
} fetch: https://poe.com/api/gql_POST, options:
        fetch failed: https://poe.com/api/gql_POST, 403, Forbidden
retrying https://poe.com/api/gql_POST, 1/20
        fetch failed: https://poe.com/api/gql_POST, 403, Forbidden
retrying https://poe.com/api/gql_POST, 2/20
        fetch failed: https://poe.com/api/gql_POST, 403, Forbidden
retrying https://poe.com/api/gql_POST, 3/20
        fetch failed: https://poe.com/api/gql_POST, 403, Forbidden
retrying https://poe.com/api/gql_POST, 4/20
        fetch failed: https://poe.com/api/gql_POST, 403, Forbidden
retrying https://poe.com/api/gql_POST, 5/20
        fetch failed: https://poe.com/api/gql_POST, 403, Forbidden
retrying https://poe.com/api/gql_POST, 6/20
        fetch failed: https://poe.com/api/gql_POST, 403, Forbidden
retrying https://poe.com/api/gql_POST, 7/20
        fetch failed: https://poe.com/api/gql_POST, 403, Forbidden
retrying https://poe.com/api/gql_POST, 8/20
        fetch failed: https://poe.com/api/gql_POST, 403, Forbidden
retrying https://poe.com/api/gql_POST, 9/20
        fetch failed: https://poe.com/api/gql_POST, 403, Forbidden
retrying https://poe.com/api/gql_POST, 10/20
        fetch failed: https://poe.com/api/gql_POST, 403, Forbidden
retrying https://poe.com/api/gql_POST, 11/20
        fetch failed: https://poe.com/api/gql_POST, 403, Forbidden
retrying https://poe.com/api/gql_POST, 12/20
        fetch failed: https://poe.com/api/gql_POST, 403, Forbidden
retrying https://poe.com/api/gql_POST, 13/20
        fetch failed: https://poe.com/api/gql_POST, 403, Forbidden
retrying https://poe.com/api/gql_POST, 14/20
        fetch failed: https://poe.com/api/gql_POST, 403, Forbidden
retrying https://poe.com/api/gql_POST, 15/20
        fetch failed: https://poe.com/api/gql_POST, 403, Forbidden
retrying https://poe.com/api/gql_POST, 16/20
        fetch failed: https://poe.com/api/gql_POST, 403, Forbidden
retrying https://poe.com/api/gql_POST, 17/20
        fetch failed: https://poe.com/api/gql_POST, 403, Forbidden
retrying https://poe.com/api/gql_POST, 18/20
        fetch failed: https://poe.com/api/gql_POST, 403, Forbidden
retrying https://poe.com/api/gql_POST, 19/20
        fetch failed: https://poe.com/api/gql_POST, 403, Forbidden
retrying https://poe.com/api/gql_POST, 20/20
        fetch failed: https://poe.com/api/gql_POST, 403, Forbidden
Error: Failed to fetch https://poe.com/api/gql_POST after 20 retries
    at C:\Users\chazb\Downloads\SillyTavern-dev\SillyTavern-dev\src\poe-client.js:405:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Desktop (please complete the following information):**
 - OS/Device: Windows 11
 - Environment: local
 - Node.js version: 19.6.0
 - Browser:  Chrome
 - Generation API: Poe
 - Branch: dev (same error on main)
 - Model: Same with every model

**Comment by Cohee1207** [comment]
I currently do not have a solution for this

**Comment by Woisek** [comment]
Too bad. Good luck in getting an idea and finding a solution. We all are hoping. 🙂👍
And many thanks for your effort.

**Comment by lanmaster2407** [comment]
Si a mi también me da ese error, tenemos que pensar en una solución, entre todos, pero por ahora no podemos hacer nada...alguna sugerencia?,lo unico que puedo aportar es que Poe esta o baneando las cuentas o limitando los mensajes en sus bots gratuitos y tengo 2 cuentas que estan asi y por prueba, asi que hay que averiguar porque estan haciendo eso.

Inglish:
If I also make that mistake, we have to think of a solution, among all, but for now we can not do anything ... any suggestion?, the only thing I can contribute is that Poe is either banning the accounts or limiting the messages in their free bots and I have 2 accounts that are so and by test, so you have to find out why they are doing that.

**Comment by MPerorI** [comment]
Looks like Poe keeps changing the p-b cookies when I clear the site's data. It's supposed to hold the same Cookies for every single account. I'm not sure but it doesn't allow all users to connect to Poe.

**Comment by Cohee1207** [comment]
Poe is no longer supported. We give up on it.

**Comment by 0mniSci** [comment]
rip
