### ISSUE TITLE
[Feature Request] save preset buttons

### ISSUE THREAD

**Issue by IkariDevGIT** [SillyTavern/SillyTavern#746]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
Hey, everytime i get good results with settings, but i wanna try different ones the ones that i just used get deleted(yes you can screenshot them but that is pretty annoying)

**Describe the solution you'd like**
I would like a "save" or "save to preset" button on the generation settings tab, and for the instruct mode tab, when you click the button a text box should appear where you can name the preset.

**Describe alternatives you've considered**
you can screenshot them, but as i said, that annoying

**Comment by Cohee1207** [comment]
Added to the staging branch.

**Comment by Cohee1207** [comment]
Released.
