### ISSUE TITLE
[Feature Request] Alternative approach to Poe

### ISSUE THREAD

**Issue by vfnm** [SillyTavern/SillyTavern#748]
Perhaps Poe support could be moved from SillyTavern to SillyTavern-extras and instead of trying to replicate the http communication on a low level, it could use something like this:

```
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import time

driver = webdriver.Firefox()

driver.get("https://poe.com")

driver.add_cookie({"name": "p-b", "value": ""})

driver.get("https://poe.com/Assistant")

time.sleep(5)

messages = driver.find_elements(By.CLASS_NAME, "Markdown_markdownContainer__UyYrv")
most_recent_message = messages[-1].text
print(most_recent_message)

text_area = driver.find_element(By.CLASS_NAME, "GrowingTextArea_textArea__eadlu")
text_area.send_keys("My message")
text_area.send_keys(Keys.RETURN)
time.sleep(2)

driver.quit()
```

**Comment by Cohee1207** [comment]
You can start your own project to wrap this into an OpenAI proxy interface.

**Comment by vfnm** [comment]
Can you test the use of this API (https://github.com/vfnm/Poe-API-Server) in SillyTavern? It can run alongside the regular SillyTavern and be accessed as an external service.

**Comment by Cohee1207** [comment]
To make it usable as a drop-in replacement, you need to wrap your API into one of the interfaces supported by ST: KoboldAI-like API or OpenAI-like API.
