### ISSUE TITLE
[Feature Request] TikTok tts

### ISSUE THREAD

**Issue by IkariDevGIT** [SillyTavern/SillyTavern#749]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
I know this may sound dumb, but the tik tok voices are pretty high quality.

**Describe the solution you'd like**
I would like the tik tok voices to be included inside of the tts extension.

**Describe alternatives you've considered**
No alternatives

**Additional context**
 you can access the api like this:
```js
import axios from "axios";
import fs from "fs";

const ENDPOINT = "https://tiktok-tts.weilnet.workers.dev";
const text = "hello, whats up?";
const voice = "en_us_ghostface";

axios({
  method: "post",
  url: `${ENDPOINT}/api/generation`,
  data: { text, voice },
  headers: {
    "Content-Type": "application/json",
  },
})
  .then((response) => {
    const { data } = response.data;
    const buffer = Buffer.from(data, "base64");
    fs.writeFileSync("./audio.mp3", buffer);
  })
  .catch((error) => {
    console.error(error);
  });
```
it has a web interface(https://weilbyte.github.io/tiktok-tts/) which i found a while ago, then i found that it had an api by accident. Here is the direct link for the project: https://github.com/Weilbyte/tiktok-tts

**Comment by maxime-fleury** [comment]
I made a plugin for piper tts, maybe you can easly fork it to add the tiktok tts, if I have time I'll do it myself, seems easy https://github.com/maxime-fleury/SillyTavern-Piper-TTS
