### ISSUE TITLE
Chat formatting breaking

### ISSUE THREAD

**Issue by Enferlain** [SillyTavern/SillyTavern#750]
This has been happening for a few weeks now but most of the time, basically the *text* and spaces are broken for some reason, meaning all of the replies are messed up, like dialogue and *dfsgfhf* are swapped and paragraphs are mashed together. My own text is properly formatted, so I don't know where the ai is taking it from, and it happens on every model. I use the updateandstart.bat so I should be up to date.

Any idea what causes this?

**Comment by Cohee1207** [comment]
Please provide all the information regarding your setup, including formatting settings, prompts, characters, APIs.
