### ISSUE TITLE
[Feature Request] Auto update Poe API Wrapper

### ISSUE THREAD

**Issue by ProjCRys** [SillyTavern/SillyTavern#751]
I've been using this for quite some time and mostly using poe as an API. There were some issues with poe were somtimes my pb-cookies aren't working, even with new pb-cookies, though when I tested it through my project (A game where it checks the github repo of the poe wrapper, specifically the python version one, and updates it when neccessary) it works just fine.

Here's the repo I've been using:
https://github.com/ading2210/poe-api.git

This is just my suggestion, though I'm not really that good at programming yet but and know how SillyTavern works since I the only programming language I'm good at is Java, I just want to share my idea hoping this could be helpful.

**Comment by Cohee1207** [comment]
We can't use Python libraries. Our client was a port of this library, but it is too cumbersome to support. 
See this project: https://github.com/juzeon/poe-openai-proxy
