### ISSUE TITLE
[BUG] Sillytavern doesn't launch anymore since 1.9.0 update, on Mac

### ISSUE THREAD

**Issue by elouannd** [SillyTavern/SillyTavern#752]
> **Warning**. Complete **all** the fields below. Otherwise your bug report will be **ignored**!

**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
Sillytavern doesn't launch anymore since 1.9.0 update, on Mac 
**To Reproduce**
I updated using git pull https://github.com/SillyTavern/SillyTavern.git
and since that It wont launch and giving error (see log)
**Expected behavior**
Sillytavern should launch and open a Safari tab  
**Screenshots**
none 
**Logs**
`Running from source
/Users/elouanndomenech/SillyTavern/server.js:44
const open = require('open');
             ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/elouanndomenech/node_modules/open/index.js from /Users/elouanndomenech/SillyTavern/server.js not supported.
Instead change the require of index.js in /Users/elouanndomenech/SillyTavern/server.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/elouanndomenech/SillyTavern/server.js:44:14) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.4.0`

**Desktop (please complete the following information):**
 - OS/Device: MacBook Air M1 on MacOS Ventura 13.4
 - Environment: Local
 - Node.js version (if applicable):  v20.4.0
 - Browser: Safari
 - Generation API OpenAI
 - Branch Main
 - Model OpenAI ChatGPT Turbo

**Comment by Cohee1207** [comment]
Changed package type to commonjs, git pull and test, please
Works for me on node 20.5.0

**Comment by elouannd** [comment]
work great now. Thanks

**Comment by arpitingle** [comment]
having this same problem with launching on my mac 
node - v21.3.0
