### ISSUE TITLE
[Feature Request] API and hyperparameters per character

### ISSUE THREAD

**Issue by lee-b** [SillyTavern/SillyTavern#753]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**

Yes.  Characters all share one model, and one set of hyperparameters.  This is inflexible, and doesn't fit the idea of separate characters with their own personalities.

**Describe the solution you'd like**

The hyperparameters, and the AI model endpoint, should be customizable/overridable on a per-character basis.

For example, I'd like to be able to simultaneously set up:

- a few general characters, such as philosophers or historians, which each have their own personalities, including temperatures, top_k, etc. to add to their uniqueness.

- a coder character, which has a very low temperature, and uses a text-generation-webui/koboldai endpoint that has a coding-specific model (such as wizardcoder) loaded.

- a lawyer character, which also has a low temperature, and its own law-based model

- a scientist, which has a low-temperature, and a science-based model

**Describe alternatives you've considered**

**Additional context**

I know that sillytavern is meant to be "silly", but my goal here is to create a mostly serious "council" of sorts, and I think that ST is quite suited to this.

I'm aware of the additional GPU/CPU/RAM/VRAM resources required for this kind of setup, but I think the flexibility described here would let me create around twelve characters, mostly sharing one general model, while the characters that need to be precise, like medical/law characters, could use dedicated models, trained for exactly that.

About hyperparameters at the character level... this just seems to be the right place to put them.  They belong with the character, not with the global settings, as they inform the character's "personality".  Though, it would be good to be able to set them globally and then override at the character level.

**Comment by IkariDevGIT** [comment]
i think one approach may be to add a simple button to the menu for parameters and api selection that just locks its state/settings to the current character.

**Comment by Cohee1207** [comment]
This is already done but only for chat completions API. You use oobabooga mainly, right?

**Comment by Cohee1207** [comment]
API settings preset to character name binding was released to staging.
