### ISSUE TITLE
[BUG] Everytime I put poe cookies it says that its expired or out of tokens.

### ISSUE THREAD

**Issue by RandomUser1017** [SillyTavern/SillyTavern#761]
> **Warning**. Complete **all** the fields below. Otherwise your bug report will be **ignored**!

**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
It says that its invalid/out of tokens.

**To Reproduce**

1. Go to 'poe.com'
2. Click on 'F12, then "Application", then copy the value. After that, enter it into the SillyTavern poe.com API'
3. See error

**Expected behavior**
As soon as I enter the cookies it should've worked and im able to use it.

**Screenshots**
![image](https://github.com/SillyTavern/SillyTavern/assets/138387006/85217cef-b56a-4ed2-a401-2b0c45b50669)

**Logs**

![image](https://github.com/SillyTavern/SillyTavern/assets/138387006/94c53887-817c-44e0-bc16-5fb03326687a)

**Desktop (please complete the following information):**
 - OS/Device: [Windows 10]
 - Environment: [cloud]
 - Node.js version [19.1.0]
 - Browser [chrome]
 - Generation API [OpenAI]
 - Branch [main]
 - Model [Pygmalion 6b]

**Additional context**
What should I do? I've been trying for a couple days.

**Comment by IkariDevGIT** [comment]
poe is not supported anymore by sillytavern, update your sillytavern(optional of course) and use a different API

**Comment by RandomUser1017** [comment]
> poe is not supported anymore by sillytavern, update your sillytavern(optional of course) and use a different API

Can you tell me how to, please? I forgot.

**Comment by RandomUser1017** [comment]
I've tried updating it and changing the cookie many times and it still fails for both mobile and PC.

**Comment by RandomUser1017** [comment]
> poe is not supported anymore by sillytavern, update your sillytavern(optional of course) and use a different API

I've updated and change cookie but still cant.

**Comment by Woisek** [comment]
>my ST is at the newest version.

It is not, if you have poe in your api selections

**Comment by RandomUser1017** [comment]
> > my ST is at the newest version.
> 
> It is not, if you have poe in your api selections

Oh well nevermind, I wonder why they remove poe tho.

**Comment by IkariDevGIT** [comment]
@RandomUser1017 because it was too time-consuming to maintain

**Comment by RandomUser1017** [comment]
> @RandomUser1017 because it was too time-consuming to maintain

Oh, RIP, I hope it gets re-added, its a good bot.
