### ISSUE TITLE
[BUG] {{original}} tag no longer seems to replace prompt text within Prompt Overrides: Jailbreak

### ISSUE THREAD

**Issue by Kenneth-Baker** [SillyTavern/SillyTavern#762]
**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aopen+jailbreak)?**
Yes

**Describe the bug**
Inserting {{original}} into the Prompt Overrides boxes should insert the original jailbreak text into the override jailbreak, but doesn't.

**To Reproduce**
1. tick send jailbreak
2. Add a jailbreak text in your prompt settings. We will call this jbText
3. Use a character that has an {{original}} tag within the prompt override like so: 
    {{original}} additionalJBText
4. Enable "Prefer Char. JB" in settings
5. generate a reply

**Expected behavior**
{{original}} should be replaced by jbText, making the JB: jbText additionalJBText

**Actual behavior**
{{original}} is replaced by blank text, making the JB: additionalJBText

**Screenshots**
Sample Prompt settings
![image](https://github.com/SillyTavern/SillyTavern/assets/134729210/4c3c9596-0e34-4719-8959-6e7ae71bfdb2)

when "Prefer Char. JB" is disabled
![image](https://github.com/SillyTavern/SillyTavern/assets/134729210/c6ba7c5c-4dee-4469-8f8c-25c57e66fa63)

when "Prefer Char. JB" is enabled
![image](https://github.com/SillyTavern/SillyTavern/assets/134729210/e50aec4f-d475-4489-98a6-1800ddef157a)

**Desktop (please complete the following information):**
 - OS/Device: Windows 10
 - Environment: local
 - Node.js version (if applicable): v18.17.0
 - Browser: Chrome
 - Generation API: Claude
 - Branch: release
 - Model: Claude 2.0

Additional Details:
Not tested for main prompt because I do not use that feature.

**Comment by Cohee1207** [comment]
Fixed here: https://github.com/SillyTavern/SillyTavern/commit/212e98302a9a3d7af86fce6980430d67edf82792

**Comment by Kenneth-Baker** [comment]
Ah, sorry, I thought I updated it but it seems I didn't pull the most recent one
