### ISSUE TITLE
[BUG] Press "Send" to continue isn't functioning as it should.

### ISSUE THREAD

**Issue by heffke** [SillyTavern/SillyTavern#763]
> **Warning**. Complete **all** the fields below. Otherwise your bug report will be **ignored**!

**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
When using the `Press "Send" to continue` option, the continuation *replaces* the original message instead of adding to it. The `Continue` button in the burger menu works as intended.

**To Reproduce**
1. Turn on `Press "Send" to continue` option.
2. Click on the `Send` icon or press Enter on an empty input box.
3. Watch the original response be overwritten by the continuation.

**Expected behavior**
The behavior should match that of the `Continue` button in the burger menu.

**Desktop (please complete the following information):**
 - OS/Device: Windows 10
 - Environment: local
 - Node.js version (if applicable): v18.14.2
 - Browser: Firefox
 - Generation API: Ooba (via simple-proxy, but it also happens without)
 - Branch: `staging`
 - Model: LLaMA2-13B

**Comment by Cohee1207** [comment]
You're right, sorry. Should be fixed now

**Comment by heffke** [comment]
Yep, works! Thanks!
