### ISSUE TITLE
[BUG] Failed to build container image due to relocation of settings.json file from /public to /default.

### ISSUE THREAD

**Issue by hongyanca** [SillyTavern/SillyTavern#765]
**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
Failed to build container image due to **relocation of settings.json file from /public to /default**.

**To Reproduce**
1. Clone the repo
2. Run docker build
3. Get an error message
```
RUN   IFS="," RESOURCES="characters,chats,groups,group chats,User Avatars,worlds,settings.json" &&     echo "*** Store default $RESOURCES in <folder>.default ***" &&   for R in $RESOURCES; do mv "public/$R" "public/$R.default"; done &&     echo "*** Create symbolic links to config directory ***" &&   for R in $RESOURCES; do ln -s "../config/$R" "public/$R"; done &&   mkdir "config":
0.307 *** Store default characters,chats,groups,group chats,User Avatars,worlds,settings.json in <folder>.default ***
0.312 mv: can't rename 'public/settings.json': No such file or directory
```

**Expected behavior**
Successful build of docker container image.

**Comment by Cohee1207** [comment]
Sorry, it took me some time to unwrap the Docker volumes logic. It should work now, but only with manual changes to config.conf due to whitelist issues. Let me know if you'd prefer to have the whitelist disabled for Docker (since it uses the internal Docker IPs).

**Comment by hongyanca** [comment]
For the time being, I'm satisfied with the workaround by manually modifying the config.conf file to bypass the Docker volumes whitelist issues.
