### ISSUE TITLE
[BUG] No jailbreak in 1.9.2

### ISSUE THREAD

**Issue by GitGraxy** [SillyTavern/SillyTavern#766]
> **Warning**. Complete **all** the fields below. Otherwise your bug report will be **ignored**!

**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
For some reason, after 1.9.1 the openrouter's API can't be used properly. Everytime I try to engage NSFW content, the API says: "I'm sorry, I can't generate that story for you" Or such. (Using GPT 3.5 Turbo.)

I still have the 1.9.0 version on my PC, and in that version everything flows normally. 

(btw, same prompts on both versions are being used.)

**To Reproduce**
1. Install 1.9.0 and  1.9.1/1.9.2. 
2. Just try to engage NSFW on both of them using Openrouter's API.
3. 1.9.1/1.9.2 will always refuse or act against the content, while on 1.9.0 everything works.

**Expected behavior**
It should be the same, even if openrouter's settings changed between theese versions.

**Screenshots**
Not sure if I can send NSFW stuff here, I'm new to git.

**Logs**

The logs are the same, it's just the API behaving differently on the versions without any trace of log.

**Desktop (please complete the following information):**
 - OS/Device: Android (termux) and PC
 - Environment: [Cloud]
 - Browser [Opera]
 - Generation API [OpenAI (through openrouter)]
 - Branch [main]
 - Model [GPT 3.5 turbo]

**Additional context**
This was tested by two different people with two different paid openrouter accounts. No other person in the community (that I searched for) ever complained about this.

**Comment by Cohee1207** [comment]
Do you perhaps use a character with an embedded jailbreak prompt that uses {{original}} 1.9.1 had a bug that did not insert the original JB. 

Compare prompts and settings that go out line by line. They are logged in the console window.

**Comment by Cohee1207** [comment]
To provide you help I need to see your console logs or get the references to character cards you use

**Comment by GitGraxy** [comment]
> To provide you help I need to see your console logs or get the references to character cards you use

Sorry for leaving this opened, I'm not used to github. The issue sorted it out by itself using other characters and the dev version of the application. Don't know which one of the two fixed it honestly.
