### ISSUE TITLE
[Feature Request] Improve editing for single-document mode

### ISSUE THREAD

**Issue by anonymous721** [SillyTavern/SillyTavern#767]
**Is your feature request related to a problem? Please describe.**
Editing generations is pretty cumbersome for how common it is. In a story-type session, there's more basis for the writing from the user and the AI to be intermingled and collaborative, compared to a well defined back-and-forth chat-type session where the AI's generations are what "someone else" is saying. At least for me, I end up adjusting the AI's output extremely often to help guide things in the right direction. 

**Describe the solution you'd like**
- Make double-clicking a generation open it for editing. This is a very fast and natural way to do it, and much more convenient than clicking the tiny pencil icon.
- Allow editing generations other than the most recent. It's really annoying to do the juggle of shifting around the various lines to get the one you want at the bottom, editing it, and then shifting them all back into place. Retcons are a valuable tool.

Incidentally, it appears that some hotkeys listed in the docs aren't available in single-document mode, but Ctrl-Enter works. Not sure if the others are a bug or by design.

**Comment by Cohee1207** [comment]
Fixed in release. Click on messages to edit them.
