### ISSUE TITLE
[BUG/ISSUE] [Dev Branch] When generating a new post through Horde.

### ISSUE THREAD

**Issue by Mr-Firesign** [SillyTavern/SillyTavern#771]
> **Warning**. Complete **all** the fields below. Otherwise your bug report will be **ignored**!

**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
*When generating a new response from an ai module through horde, with any of the modules connected to the koboldai horde the following message appears almost instantly on the Windows PowerShell command prompt while causing the request not to send or receive.

**To Reproduce**
1. Go to 'API'
2. Click on 'KoboldAI Horde'
3. Select 'Any available module on the module list provided'
4. Generate a new response 'Either through swipes or sending a new message'

**Expected behavior**
A new response to be sent through the Module selected.

**Logs**

Providing the logs from the browser DevTools console (opened by pressing the F12 key) or SillyTavern command line window will be highly appreciated.

FetchError: request to https://horde.koboldai.net/api/v2/generate/text/async failed, reason: connect ETIMEDOUT
    at ClientRequest.<anonymous> (E:\AISILLYTAV\SillyTavern-main\SillyTavern-dev\SillyTavern-dev\node_modules\node-fetch\lib\index.js:1505:11)
    at ClientRequest.emit (node:events:511:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:511:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'

**Desktop (please complete the following information):**
 - OS/Device: [Windows 11]
 - Environment: [local]
 - Node.js version (if applicable): [v20.3.0]
 - Browser [Opera GX]
 - Generation API [KoboldAI Horde]
 - Branch [dev]
 - Model [All available]

**Comment by Cohee1207** [comment]
Can you ping the horde.koboldai.net host? Is it available through your network? Try with a VPN

**Comment by Mr-Firesign** [comment]
> Can you ping the horde.koboldai.net host? Is it available through your network? Try with a VPN

I didn't think about pinging. I just did it though, and the pings timed out, even though I can connect to the site. I don't really know how to ping properly, every site I try pinging through command prompt shows the same thing. I don't know how to change that to make it send properly.
 Packets: Sent = 4, Received = 0, Lost = 4 (100% loss)
 
 I'm able to get responses through https://lite.koboldai.net 
 
![image_2023-07-24_130544713](https://github.com/SillyTavern/SillyTavern/assets/140429580/fe387ce7-b35a-4e2d-a8ea-f13c0970d885)
![image_2023-07-24_130832655](https://github.com/SillyTavern/SillyTavern/assets/140429580/c9fe7c74-dcbc-466c-9acc-1b4e8ee34c96)

**Comment by db0** [comment]
Can you try using aihorde.net? If that doesn't work still, try stablehorde.net

**Comment by Mr-Firesign** [comment]
I figured it out. It was definitely a me problem. I restarted my PC and it's working again. The ping thing that was originally recommended is working as well.
