### ISSUE TITLE
[Feature Request] Multiple UI colors With Slider Selector

### ISSUE THREAD

**Issue by SeviantSevi** [SillyTavern/SillyTavern#772]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
No

**Is your feature request related to a problem? Please describe.**
I kind of really thought that it was a hassle changing the UI colors each time if you want it to match it with the bg or the character theme. it would pretty much be an inconvenience in changing the colors everytime.

**Describe the solution you'd like**
It would be much better if we can have UI colors presets and select them via like the lorebooks, for easy switching.

**Additional**
If this is possible, then maybe you can also link the UI colors into the Character cards

**Comment by Cohee1207** [comment]
That's already available. Theme presets are right below the color selector

**Comment by SeviantSevi** [comment]
I can see that.. but linking Theme presets to Character cards like you did with lorebooks is possible right? or is that already available?

**Comment by Cohee1207** [comment]
The link between characters/themes is currently not available. You can bind a background image to a chat using the Characters Backgrounds extension.

**Comment by Cohee1207** [comment]
Now doable with STscript auto-execution on chat opening and using a /theme command.
https://docs.sillytavern.app/usage/st-script/
