### ISSUE TITLE
Im getting error while executing start.bas file to run the server  

### ISSUE THREAD

**Issue by ALDRIN2003** [SillyTavern/SillyTavern#777]
Im using windows 7 and node js version 13.14.0 x64. I tried every method but it gives the same error no matter what, Here's the error.
 
![error](https://github.com/SillyTavern/SillyTavern/assets/123755175/e560b697-b9b7-4182-956f-26f64746370e)

Its happening with bash file and also same with update and run
--->
G:\Ai text folder\SillyTavern>pushd G:\Ai text folder\SillyTavern\

G:\Ai text folder\SillyTavern>call npm install --no-audit
npm WARN sillytavern@1.9.2 No description

up to date in 1.866s

39 packages are looking for funding
  run `npm fund` for details

G:\Ai text folder\SillyTavern\server.js:124
    client_agent: getVersion()?.agent || 'SillyTavern:UNKNOWN:Cohee#1207',
                               ^

SyntaxError: Unexpected token '.'
←[90m    at Object.compileFunction (vm.js:344:18)←[39m
←[90m    at wrapSafe (internal/modules/cjs/loader.js:1048:15)←[39m
←[90m    at Module._compile (internal/modules/cjs/loader.js:1082:27)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:1
0)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:982:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:875:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_ma
in.js:71:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m
Press any key to continue . . .

**Comment by Cohee1207** [comment]
We require Node 18, which Windows 7 does not support.
