### ISSUE TITLE
[Feature Request] Don't reply command

### ISSUE THREAD

**Issue by LeoStark84** [SillyTavern/SillyTavern#778]
So I've been recently making extensive use of the continue feature to guide AI's answers. Basically, I need to delete the last reply, use /sendas to make the AI character 'say' an incomplete phrase then use continue. It is really helpful with low-power LLMs. The downside being that I have to wait for an answer (and paying in kudos or real money, depending on the API) that I know beforehand I'm going to delete. An awkward altwrnative would be to disconnect from the API, causing the text generation to fail, then reconnecting.

So I was thinking it might be a good idea to add a slash command to let the user post without triggering an AI response. Also useful if the user would want to set a sys dialog or character bias after talking.

For the particular usage case of guiding the AI answer, a second 'start reply with' bar could be implemented, oobabooga style, but I think it would look too invasive, not to mention, chewing up a lot of space on mobile.

Another really counter-intuitive alternative would be to let the /sendas command to send a reply as the user (which currently doesn't) as this command does not trigger an AI reply.

A third option would be to let the user append a /sendas command at the end of his/her own reply, although I have the hunch that would be a pain in the ass to implement.

**Comment by Cohee1207** [comment]
Command something like /send seems possible and easy to do. Planned.

**Comment by aetherwu** [comment]
> Command something like /send seems possible and easy to do. Planned.

It feels like a temporary Auther's note as it is in extras? It is good for narrative.

**Comment by Cohee1207** [comment]
Released.
