### ISSUE TITLE
How to remove /nYou stop sequence globally?

### ISSUE THREAD

**Issue by bucketcat** [SillyTavern/SillyTavern#781]
This addition has completely destroyed my workflow, I would like to completely remove /nYou as a stop sequence. It's not a character, it only aborts generation on anything descriptive, such as actions or thoughts. I usually use *markdown* second person to describe actions and thoughts from the point of view of a character after dialogue, and it has always worked well in every generative NLP model since GPT-2 for me.

This, is no longer the case. I have looked through every possible config, the documentation etc. Most of my usage is highly verbose with long text, but I am now limited to one-liners, and I don't want an SMS simulator, but a narrative and linguistically complex story. I used to be able to prompt a chat into this before this addition.

If this is not a possibility, which commit was the last before "You" was included as a forced stop sequence?

Edit: This seems to only be an issue when using Koboldcpp, for some reason.

Edit 2:

As an example, how I would normally write dynamic dialog. 

Message 1 > Character X: "Bla bla bla bla."
*You frown as X continues his perpetual babbling.*
"Bla bla bla bla!" *X says, growing frustrated by your appearant lack of enthusiasim for what he's trying to convey.*

Message 2 > Char Y (You, currently):
"Blaaaaa?! Bla bla bla, bla bla?" *You blurt out, before storming off and shutting the door in X's face.

X is left flabbergasted, as you move on with your day.*

In this example, you can be replaced with Y. 

This would trigger it twice, either way, but without /nYou you could at least work your way around it. Now it's just awful, railroading you into a workflow that is less interesting in every way. I generally do not want name stop sequences either, as it's easier to manually edit in the start, and then prompt the story so that it follows your style. You can achieve a 'chat' using just a blank slate and any Llama model by simply prompting the names, referring to the other person when one speaks up. This hardcoded strangeness is really hampering the possibilities as it forces you into a static, ping-pong sequence of non-reactive back and forth messages. Like with an email conversation, it's not organic.

**Comment by Cohee1207** [comment]
This stop string was a forced guard rail for Pygmalion models. Should be safe to remove it now. Planned.

**Comment by Cohee1207** [comment]
Released.
