### ISSUE TITLE
[Feature Request] LibreTranslate locally

### ISSUE THREAD

**Issue by BahamutRU** [SillyTavern/SillyTavern#782]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I translate in the cloud.

**Describe the solution you'd like**
IP and port for local LibreTranslate in Modules.

**Describe alternatives you've considered**
I don't know alternatives. =(

**Additional context**
For starters, just the fields for entering the LibreTranslate API would be enough. In a good way, it can be added to SillyTavern Extras, but this is no longer critical.
OR maybe some other translations system, I don't know good alternatives.

**Comment by Bahamut-ru** [comment]
I did it, can someone help me with pull-request? Github doesn't work for me. =') I can't push.
Two files.

**Comment by BahamutRU** [comment]
Done.
