### ISSUE TITLE
[Feature Request] "Story mode" (sort of). Actually "reverse impersonate" option.

### ISSUE THREAD

**Issue by valden80** [SillyTavern/SillyTavern#784]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes, find some mentions, but not exactly this.

**Is your feature request related to a problem? Please describe.**
For the chat ST is already simple the best, IMHO. It's so good, that I want to use it for the writing stories - all these features with WI, regexp, and so on, is very useful for it too. And I found setup and model that actually good working for it. But with minor problem: to be good story writing solution ST missing one feature: Easy way for user to constantly start next message as {{char}} and then continue it. Right now I can do it this way:

1. Setup character "Writer" with the custom Instruction (it told that ASSISTANT continue USER's ideas for the story).
2. /sendas Writer 
    Once upon a time there is
3. Press "continue"

With option <Press "Send" to continue> it's easy to continue messages, but I still need to start every new message with "/send as Writer" and it's somewhat annoying.

**Describe the solution you'd like**
Option: "Reverse impersonate by default" that will do exactly as "/sendas {{char}}" only by default - on every new user's message. Preferably with another command like /trp to work as it's trigger for this mode.

**Describe alternatives you've considered**
If regexp replacements can be triggered as /command, I can setup regexp to simplify prefix. ( @w -> /sendas Writer ), right now it's don't work, replaced command will not trigger.

**Additional context**
None.

**Comment by Akagicvn** [comment]
Instead of adding the story mode, I don’t know if you have considered a mode similar to ai dungeon, allowing users to choose their own characters and go on adventures rather than just chatting with ai characters.

**Comment by valden80** [comment]
Right now it's already possible with the right character card and model. 
Just define character as Narrator (or DM, or Game Master), with describing the setting, and use model like airoboros or guanaco with the suitable Instruct prompt. And you can go on adventure. The special mode for it no really needed.

**Comment by Akagicvn** [comment]
That's what I meant. If we use a card or define a character, then it is still in the chat-oriented mode. Imagine this, what if we can play a real adventure with multiple characters and each character has its own API, which will be more like a real-world thing. I remember I have seen someone request for this feature to provide API for each character.

**Comment by valden80** [comment]
>That's what I meant. If we use a card or define a character, then it is still in the chat-oriented mode. 

Only technically. In fact, such Narrator responding not as personage, but as a game system. This is based on model, but with right one (like airoboros) it can play for all other encountered characters too (minor characters, they will be forgotten with inactivity, as context size limitation). But if you want permanent detailed characters - it can be done too. Through WI, or Group Chat mode for maximum control.
All of it allow to make such adventure, with only one exception - multiple API for different characters. 
Otherwise, multiple character cards and WI (global and local) is enough to make it work. It possible even to make custom Instruction Prompts for every character, that make dramatic difference in their reactions, on the same model and settings.

**Comment by Akagicvn** [comment]
I know group chat, but can you tell me more about that WI? Is that parts of Worlds/Lorebooks?

**Comment by valden80** [comment]
"WI" is short for World Info/Lorebook.
It can be used to make anything "persistent", by describing it, and make this WI not constant or using the right keys.
https://docs.sillytavern.app/usage/core-concepts/worldinfo/

**Comment by Akagicvn** [comment]
That's my alternative solution for now, using Worlds/Lorebooks and group chats. To be honest, the result was not as good as I expected.

**Comment by valden80** [comment]
Result is greatly depended on used model and instruct prompt. You need a model that have roleplay sessions in dataset (not just simple chat), like a Guanaco and Airoboros. I using 13B versions with good results.

**Comment by Akagicvn** [comment]
Thanks for your advice, I will try guanaco later. I used GPT4 and the results are really not ideal.

**Comment by valden80** [comment]
I using only local models, so I can't suggest anything about cloud services...
