### ISSUE TITLE
[Feature Request] advanced character search

### ISSUE THREAD

**Issue by CuddleBear92** [SillyTavern/SillyTavern#786]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
There is no way to find character details with search.

**Describe the solution you'd like**
The Character search bar should search all fields for words, not just the character name which seems to be the case now.
It should be able to search the description, first message, creator name, tags embedded, personality summary, example dialogue and also ST tags. 

The search filed could also replace the tag filtering currently in the UI by copying search styles from boorus such as danbooru.

**Additional context**
for example. 
![image](https://github.com/SillyTavern/SillyTavern/assets/8496821/a2773c8e-10ca-4730-a0f8-b798a18d9109)

not 100% sure about the commas, just spaces feels more natural but that might get messy with spaces in the content that is searched. maybe doing quotes for when a string is containing spaces might be needed.

**Comment by Cohee1207** [comment]
I don't think that the tags should be replaced by textual search, it's less convenient cause it requires typing, and provides less visual feedback. Advanced search by other fields (fuzzy search) is a nice idea, however.

**Comment by Woisek** [comment]
> I don't think that the tags should be replaced by textual search,

I think it shouldn't be a replacement. Just a additional possibility. 🙂

> it's less convenient cause it requires typing, and provides less visual feedback.

Is typing a problem? 🤔 And depending on the number of tags, the visual feedback is also limited if you only see a few bots out of e.g. 60. Plus, if single bots then maybe also have 10+ tags ... 🤪

> Advanced search by other fields (fuzzy search) is a nice idea, however.

Yeah ... but then, you could also include all fields ... 😁

**Comment by Cohee1207** [comment]
It was added and released, except for search by visual tags (creator tags are fine)
