### ISSUE TITLE
[Feature Request] display version value of characters in gallery

### ISSUE THREAD

**Issue by CuddleBear92** [SillyTavern/SillyTavern#787]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
there is no easy way to see what version of a character is what without clicking a few times on each character. This is esp slow when you have duplicates imported in bulk for whatever reason. 

**Describe the solution you'd like**
The version value should be displayed after the character name in the gallery. 

**Additional context**
For example: 
![image](https://github.com/SillyTavern/SillyTavern/assets/8496821/5a7fe5a8-13e3-4b76-a121-e8c8d117ecb5)

**Comment by Cohee1207** [comment]
Added to staging branch.

**Comment by Cohee1207** [comment]
Released.
