### ISSUE TITLE
[BUG] Incorrect labeling of NovelAI tokenizers

### ISSUE THREAD

**Issue by zkandell** [SillyTavern/SillyTavern#788]
> **Warning**. Complete **all** the fields below. Otherwise your bug report will be **ignored**!

**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
The tokenizers listed for NovelAI are incorrect. 

**To Reproduce**
1. Go to Advanced Formatting
2. Click on Tokenizer
3. SillyTavern lists the wrong tokenizers for the NovelAI models:
NerdStash (NovelAI Krake)
NerdStash v2 (NovelAI Clio)

**Expected behavior**
Actual usage, according to NovelAI:
Pile Tokenizer (Krake)
NerdStash Tokenizer (Clio)
NerdStash Tokenizer v2 (Currently unreleased next model)

**Screenshots**

![SillyTavern](https://github.com/SillyTavern/SillyTavern/assets/55552572/35d17b82-6fb6-443c-a6c4-39edf6f5ae98)
![NAI Tokenizer Clio](https://github.com/SillyTavern/SillyTavern/assets/55552572/a91cbf30-6fae-4077-9548-71ac80efcfda)
![NAI Tokenizer Krake](https://github.com/SillyTavern/SillyTavern/assets/55552572/c9bfeacc-9b88-4be1-b13c-b7010c9d82c1)

**Logs**

Not Applicable

**Desktop (please complete the following information):**
 - OS/Device: All? (Tested on Windows, Mac, Android)
 - Environment: Local (though I assume it is present on cloud as well)
 - Browser: All
 - Generation API: N/A
 - Branch: Dev
 - Model: N/A

**Additional context**

**Comment by Cohee1207** [comment]
Fixed in staging (dev is not updated anymore).

**Comment by zkandell** [comment]
Sorry about the confusion on the dev/staging branches - I wrote this before the changeover but forgot to submit it at the time.
