### ISSUE TITLE
[Feature Request] Characters Sort By Tokens.

### ISSUE THREAD

**Issue by Kovannn** [SillyTavern/SillyTavern#789]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
Well, I have many characters downloaded, sometimes I don't want to spend so many tokens, so I search one by one which of all my characters has the least tokens possible, the problem that comes now is the tedious time I spend from chat to chat until I find the one that suits my preferences.

**Describe the solution you'd like**
![image](https://github.com/SillyTavern/SillyTavern/assets/126032126/e70b6d2c-7cf8-4850-94d9-00a57ffafb8d)

Like this.

**Describe alternatives you've considered**
I do not consider another alternatives.

**Comment by Cohee1207** [comment]
Added to staging. But it won't show the most accurate results (if you aren't using the "None" tokenizer) cause sorting is done solely on a string lengths basis, so list loading won't lag too much.

**Comment by Cohee1207** [comment]
Released.
