### ISSUE TITLE
[Feature Request] Add support for templating and scripting in the main prompt, story prompt and jailbreak prompt

### ISSUE THREAD

**Issue by pyonpyondev** [SillyTavern/SillyTavern#790]
# Feature Proposal
Add support for templating and scripting in the main prompt, story prompt and jailbreak prompt. This could be executed using handlebars.js and custom helpers.

## Potential Use Case
Let's say we add a jailbreak prompt asking the LLM to include specific information in each response:
```
<Datetime>2023-07-27 17:00</Datetime>
<Location>Mio's bedroom, Tokyo, Japan</Location>
<DateCheck1>n<DateCheck1>
```

When criteria are met, we can add more directives to the main prompt within a handlebars.js '#if' condition:
```
{{#if (match (index (matchmes \s*<DateCheck1>([\s\S]*?)</DateCheck1>\s*) 1) \s*[yY]\s*)}}
	{{! This sends a message as system to record a permanent memory. Memories are not sent to the LLM.}}
	{{#if (not (matchmemory <DateCheck1>[yY]</DateCheck1>))}}
	{{setmemory <DateCheck1>y<DateCheck1>}}
	{{/if}}
Instructions to direct the bot to advance the plotline e.g. Mio's foster parents decided to take a trip.
{{/if}}
```

We can use permanent memories to alter jailbreak directions for output like so:
```
{{#if (not (matchmemory <DateCheck1>[yY]</DateCheck1>))}}
Do DateCheck1.
{{else}}
Do EventCheck2.
{{/if}}
```

By doing this, we can create simple logic based on in-story events to help advance predetermined branching narratives.

## Why choose handlebars.js?
It's simple, widely used, and most importantly, secure, even for user-defined templates. It also matches the format of available placeholders i.e. {{user}}, {{char}}...

## Custom handlebars.js helpers
The above example uses the following custom handlebars.js helpers: match, index, matchmes, matchmemory, setmemory, not. Implementing custom helpers is easy enough:
```
// Handlebars helpers
Handlebars.registerHelper({
	not: (v1) => !v1,
	eq: (v1, v2) => v1 === v2,
	ne: (v1, v2) => v1 !== v2,
	lt: (v1, v2) => v1 < v2,
	gt: (v1, v2) => v1 > v2,
	lte: (v1, v2) => v1 <= v2,
	gte: (v1, v2) => v1 >= v2,
	and() {
		return Array.prototype.every.call(arguments, Boolean);
	},
	or() {
		return Array.prototype.slice.call(arguments, 0, -1).some(Boolean);
	}
});
```

## Comments
There are more user-friendly templating libraries and languages like Nunjucks. The only reason I propose handlebars.js here is due to security concerns with downloadable cards.

**Hop, hop! Let's bob our way over to the exciting world of trade-offs, potential implementations and explore deeper into those tiny intricate details~! What do you say, my carrot-munching friends?**

**Comment by Cohee1207** [comment]
Recent updates in our friend frontends (Risu, Agnai) include similar features, so it really would be a good parity update. I will consider this for future releases.

**Comment by KRISPYMOLE** [comment]
This idea seriously revolutionizes conversations, since a lot of important data is lost between messages, a great idea.

**Comment by lejebokaet** [comment]
We really need this feature!

**Comment by nothingsuspiciousright** [comment]
Please do~!

**Comment by SnigirevDmitri** [comment]
We need this!

**Comment by Brumbirbuss** [comment]
Please add this feature!

**Comment by likko7** [comment]
Add this please~♥!

**Comment by 01Vergil** [comment]
Support this!
