### ISSUE TITLE
[Feature Request] Character rename should effect all previous transcripts.

### ISSUE THREAD

**Issue by aetherwu** [SillyTavern/SillyTavern#793]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
Used name in previous trranscripts did not change after rename.

**Describe the solution you'd like**
All used name in previous should be replaced accordingly.

**Comment by Cohee1207** [comment]
You can force updating the name in the message title after a rename. Since all the grammar implications, making an update inside of the message text makes little to no sense.

**Comment by aetherwu** [comment]
Strange, I did click yes but it did not work. I've tried it again and it worked fine...
