### ISSUE TITLE
[Feature Request] Connect SillyTavern using http://127.0.0.1:5100/api/ on sever's local network.

### ISSUE THREAD

**Issue by aetherwu** [SillyTavern/SillyTavern#794]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**

For instance, I usually run text-generation-webui and SillyTavern on the same sever.
I apply http://127.0.0.1:5000/api to SillyTarvern API and it works fine. But similar setting won't work for extras.

I can see request below in Network debug console:
Request URL: http://127.0.0.1:5100/api/modules

It means SillyTavern won't connect to the actual extras server that runs on the same local machine.
Instead, it tries to connect sever on user's network via browser.

**Describe the solution you'd like**
It confused me. I suppose that the extras sever should not run on user's end (where browser is used) since it could be a mobile phone.
I am not sure it was intended, but I hope that I can connect the SillyTavern-extras using localhost:5100 *without expose my local port to others*.

**Comment by Cohee1207** [comment]
You need to run extras with the --listen flag, so your other devices could connect to it. Yes, it needs to be accessible to the browser because the backend does not route/proxy the extras request. This is only true for main API connections.

**Comment by aetherwu** [comment]
> You need to run extras with the --listen flag, so your other devices could connect to it. Yes, it needs to be accessible to the browser because the backend does not route/proxy the extras request. This is only true for main API connections.

Would you mind I fork the repo and PR an opinion for this setting?

**Comment by Cohee1207** [comment]
I don't mind.

**Comment by mashwell** [comment]
> You need to run extras with the --listen flag, so your other devices could connect to it. Yes, it needs to be accessible to the browser because the backend does not route/proxy the extras request. This is only true for main API connections.

Huh, I was wondering why my SillyTavern-extras server was only accessible using the Cloudflare proxy, not locally. The extras API endpoint being accessed by the browser instead of the backend makes sense. I pointed the API URL to the local network IP instead of localhost and it works now.

This probably needs additional clarification in SillyTavern-extras' README.md unless I'm missing something there?

**Comment by aetherwu** [comment]
> > You need to run extras with the --listen flag, so your other devices could connect to it. Yes, it needs to be accessible to the browser because the backend does not route/proxy the extras request. This is only true for main API connections.
> 
> Huh, I was wondering why my SillyTavern-extras server was only accessible using the Cloudflare proxy, not locally. The extras API endpoint being accessed by the browser instead of the backend makes sense. I pointed the API URL to the local network IP instead of localhost and it works now.

I added the --listen flag to it, but I am running it on a cloud server and accessing it through my local mobile browser. I don't want to expose more ports to the public.

I also tried a local network IP, but it didn't work because my local browser was not connected to the same network.

It feels natural if it works the same way as the Main API, by looking for a local port first before checking others.

**Comment by Cohee1207** [comment]
Extras are discontinued.
