### ISSUE TITLE
[BUG] Stable Diffusion refuses to generate character's face

### ISSUE THREAD

**Issue by Teashrock** [SillyTavern/SillyTavern#796]
**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
When using "Your face" option in SD generation, it complains about 'params.height': '1248 is not a multiple of 64'.

**To Reproduce**
1. Open any character chat
2. Click on magic wand icon.
3. Select "Stable Diffusion" -> "Send me a picture of: Your face".
4. Edit prompt, press "Generate".
5. Get the error and the notification "Image generation has failed, please try again".

**Expected behavior**
Generating image upon the button being pressed, as it should.

**Screenshots**
![Screenshot_20230727_214524_Termux](https://github.com/SillyTavern/SillyTavern/assets/12483854/eeaa2a81-e671-4022-92c1-69e85dae989d)

**Logs**
On the screenshot above.

**Tablet:**
 - OS/Device: Android 13, Samsung Galaxy Tab S6 Lite
 - Environment: local
 - Node.js version (if applicable): v19.9.0
 - Browser: Chrome
 - Generation API: OpenAI
 - Branch: release 1.9.2
 - Model: gpt-3.5-turbo-0301

**Additional context**

**Comment by Cohee1207** [comment]
Pay close attention to the message and set other image height/width

**Comment by Teashrock** [comment]
@Cohee1207 
I should have mentioned I already did this. It just substitutes user-defined height value with 1248, which it shouldn't do. Also, the slider allows the user to set only multiples of 64, so there's literally **no** 1264. It can't be set by user, but for some reason, this value passes when generating the image.

Here are my values:
![Screenshot_20230727_233426_Chrome](https://github.com/SillyTavern/SillyTavern/assets/12483854/0967b0fb-3674-48ad-a16d-f2141d97f17b)

**Comment by Cohee1207** [comment]
Never mind, I see the reason now

**Comment by Cohee1207** [comment]
Bug fix released.
