### ISSUE TITLE
[BUG] adjustable text box does not adjust in narrow widths

### ISSUE THREAD

**Issue by CuddleBear92** [SillyTavern/SillyTavern#799]
> **Warning**. Complete **all** the fields below. Otherwise your bug report will be **ignored**!

**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
the adjustable textboxes used in for example the character editor pages are not adjustable when using a narrow window/browser size.

**To Reproduce**
1. Make the bowser window narrow enough to use the mobile mode.
2. Try to grab the adjustment box in the character editor
3. See it doesn't adjust like normal

**Expected behavior**
I expect this to be adjustable even when its in the phone mode as only a handful of lines doesn't use a quarter of the screen depending on the users setup. 

**Screenshots**
![image](https://github.com/SillyTavern/SillyTavern/assets/8496821/9211372d-33e0-4632-ab71-cfbca50b2691)

**Desktop (please complete the following information):**
 - OS/Device: Windows 11,
 - Environment: local
 - Browser: edge, chrome, safari (iOS)
 - Branch: main

**Additional context**
Note that you can adjust it in a wider view then adjust it back down again and the size is kept. Also its not adjustable at all on say Safari, Chrome or Edge on iOS (guess cause its all really safari underneath) even in "desktop mode"

**Comment by Cohee1207** [comment]
Fixed and released.
