### ISSUE TITLE
[Feature Request] update existing character on new import/download

### ISSUE THREAD

**Issue by CuddleBear92** [SillyTavern/SillyTavern#800]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
I think the characters should be updated when certain criteria is met and ask the user in what they want to do. 

**Describe the solution you'd like**
For example if the name+creator is the same then its the same character and will ask the user if they want to update and replace.
 
When the system think its an update then it will ask if the user want to replace or add as a alternative version/dupe. This should probably be listed in a single list with buttons for each so its easy to sort through with bulk imports.

**Describe alternatives you've considered**
Using saved URL's from character downloads would make sense.
If the download url is saved when a download from say chub is triggered then it can use that with matching.

**Additional context**
This can in the future be re-used for an update button.

**Comment by Woisek** [comment]
> Using saved URL's from character downloads would make sense.

Not every card has a URL. Not everyone uses chub.ai. I personally create my own characters, there is no URL. 🙂

**Comment by CuddleBear92** [comment]
> > Using saved URL's from character downloads would make sense.
> 
> Not every card has a URL. Not everyone uses chub.ai. I personally create my own characters, there is no URL. 🙂

while that is also true. many use editors to make and update their characters outside of ST! its not specifically for chub at all in anyway. its to update the character which is the main point. not creating a new duplicate but rather replace what you have.

**Comment by Woisek** [comment]
Sure, but when I have a card that I want to edit/update, I use AI Character Editor for that. It's too cumbersome for me to edit in ST. Also, I store all my characters in one place, (because I also use ooba) so I update it there and re-import then.

**Comment by WolframRavenwolf** [comment]
I'd like an Update Existing Character feature, too! 👍 I create my chars with AI Character Editor as well and when I want to update, I have to select the current version, delete it, be VERY careful not to delete the chat history (since that option is always preselected!), then import the new one, and mark it as favorite again. Would be much easier to simply import the file and get a dialog box, asking if I want to replace or duplicate the existing one, and no way to forget unselecting the chat log deletion option and risk data loss.

**Comment by drago87** [comment]
Getting a question to update an existing character would be good the have

**Comment by Cohee1207** [comment]
I released this feature in 1.10.6
<img width="316" alt="image" src="https://github.com/SillyTavern/SillyTavern/assets/18619528/ba707929-7248-4505-aaa0-a10553badb91">
