### ISSUE TITLE
[Feature Request] character search field should accept and trigger urls for downloads

### ISSUE THREAD

**Issue by CuddleBear92** [SillyTavern/SillyTavern#801]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
The search field for the character page should accept urls for downloads, no need to have its own button and pop-up.

**Describe the solution you'd like**
You paste in an url into the search field for the characters and press enter and it will trigger a download. no need to click the download button then click the field and paste it in and all that.

**Additional context**
![image](https://github.com/SillyTavern/SillyTavern/assets/8496821/3b9ccda8-799d-4081-bb59-6bea0afadca1)

**Comment by Woisek** [comment]
And what happens if a manipulated card is downloaded ... ?
I mean, I don't know if this is even possible, but if so, then I personally see this as a security issue.

**Comment by CuddleBear92** [comment]
downloading is already in place. the only difference is where you past in the url. and security? really? just have it whitelist the sites if that's a worry.

**Comment by Woisek** [comment]
I meant 'possible' in the means of harmed via a manipulated card. The same topic with SD and ckpt vs safetensors.
But that's something the devs have to judge.

**Comment by Cohee1207** [comment]
Sorry, I can't say I like the idea. I don't want to let arbitrary downloads by URL happen, especially like this. You can drag and drop a card between browser tabs to make it import.
