### ISSUE TITLE
[Feature Request] Disable the auto connect on changing prompt preset (major security issue)

### ISSUE THREAD

**Issue by ahmed-elj** [SillyTavern/SillyTavern#803]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
YES

the problem:
upon changing the prompt preset and if the openai key field is filled, it automatically connect, that leads to sending your key to the saved proxy on that prompt preset, while the checkbox for auto connect is disabled,

this cause the leak of your key.

**Describe the solution you'd like**
Remove the auto connect on preset change

**Comment by Cohee1207** [comment]
Although we don't recommend using proxies, especially with your real key saved, I added a dedicated field for proxy passwords.

**Comment by ahmed-elj** [comment]
good job thanks for the feature, 

now you can remove the sign above the proxy url

```
Remove your real OAI API Key from the API panel BEFORE typing anything into this box.
We cannot provide support for problems encountered while using an unofficial OpenAI proxy.
```

**Comment by Cohee1207** [comment]
Released, so closing now.

> We cannot provide support for problems encountered while using an unofficial OpenAI proxy.

Sorry, but this stays. We need to be clear that using proxies voids your warranty.
