### ISSUE TITLE
[Feature Request] New NovelAI model

### ISSUE THREAD

**Issue by zkandell** [SillyTavern/SillyTavern#804]
[Feature Request] New NovelAI model

**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
New NovelAI model, Kayra, has been released (currently only for top tier Opus subscribers), option to use it should be added. 
String to call it through the API: "kayra-v1"
Uses the NerdStash v2 tokenizer

**Describe alternatives you've considered**
N/A

**Additional context**
Screenshot from API documentation (https://api.novelai.net/docs/):
![image](https://github.com/SillyTavern/SillyTavern/assets/55552572/cd1adacd-4057-4ead-93d2-6c50001376b7)

**Comment by Cohee1207** [comment]
Added to staging

**Comment by zkandell** [comment]
Looks good, thank you for getting that added so quickly
