### ISSUE TITLE
[Feature Request/Bug]  <!-- Allow Invisible Markdown Comments -->

### ISSUE THREAD

**Issue by ZobrMitwaset** [SillyTavern/SillyTavern#805]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
It can be useful for consistency to prompt the AI to recall some essential details at the start of a response. Doing this invisibly can be valuable for certain applications (e.g. hidden attributes in text adventure games). Markdown comments  do not render text which would enable this capability. In short, I want the AI to remember stuff but keep it secret from me.

**Describe the solution you'd like**
The offending code is here: https://github.com/SillyTavern/SillyTavern/blob/ccf54547501c5f36490563a5c4b7c0124e135b26/public/script.js#L1171-L1172

I don't know what benefit it has. The comment says something about a welcome message. Substituting <,> prevents the Markdown interpreter from working with comments. If this code is some old holdout it could simply be removed, else some exception written in.

**Describe alternatives you've considered**
There are other ways to generate invisible text in markdown, but they are less token economical for multiline comments, and more hacky, hence less consistent.

**Comment by IkariDevGIT** [comment]
you can already do this with regex

**Comment by ZobrMitwaset** [comment]
I'm not quite sure what you mean to be honest. Regardless, I would like to share bots with relatively complex reply formats for which this would be useful without having to carefully instruct people on how to get the formatting working right.

**Comment by Cohee1207** [comment]
Fixed and released.
