### ISSUE TITLE
[BUG] NAI API is inconsistent in group chats.

### ISSUE THREAD

**Issue by TheZennou** [SillyTavern/SillyTavern#811]
> **Warning**. Complete **all** the fields below. Otherwise your bug report will be **ignored**!

**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
When using the NAI API (any model) it behaves weirdly in a group chat. Namely, giving blank outputs, about 90% of the time. With streaming off or on.
I've also tried doing this on a fresh installation.
Turning down the context will make messages reappear, but they will be broken, with too many asterisks, and trimmed starting sentences. The streaming animation also breaks, appearing for a split second then disappearing, and then the completed message shows up a few seconds later.
The most consistent way to get messages to appear, is a turned down context, and streaming off.

**To Reproduce**
1. Connect to NAI API
2. Enter a long enough group chat.
3. Try chatting, low context, high context, with and without streaming
4. See the inconsistencies for yourself. 

**Expected behavior**
A useable group chat in a supported API. 

**Screenshots**
N/A, doesn't really help here.

**Logs**
N/A, no error is given.

**Desktop (please complete the following information):**
 - OS/Device: Windows 10
 - Environment: Local
 - Node.js version: v20.3.1
 - Browser: Chrome
 - Generation API: NAI
 - Branch: Staging
 - Model: All of them.

**Additional context**
Hi Cohee ;)

**Comment by The-Noble** [comment]
![image](https://github.com/SillyTavern/SillyTavern/assets/75322663/15d9396c-eead-4a05-994d-acb98a5bb3ff)
Checking these fixes these issues, it seems to be some kind of trimming problem, would like to see it be made more clear.
Will leave this as unresolved.

**Comment by TheZennou** [comment]
This can be fixed by setting "start reply with" to the character's name.
This is actually an issue with the model generating the wrong name at the start of a message and SillyTavern cutting it off. If you force it to generate the correct name it's no longer an issue.
![image](https://github.com/SillyTavern/SillyTavern/assets/75322663/6b582ba2-c6de-4821-9f02-c53a12c249e2)
I would just suggest an option to force this behavior, but that would conflict with the continue generating feature so...
