### ISSUE TITLE
[Feature Request] Hide ST icons with a lock/unlock button

### ISSUE THREAD

**Issue by fleroviumcynide** [SillyTavern/SillyTavern#813]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
No

**Is your feature request related to a problem? Please describe.**
This isn't literally like a problem for me.. but ST icons are basically the fundamentals on how you use SillyTavern.. but it would really be best if the chats are seamless in view and the icons are hidden..

**Describe the solution you'd like**
I suggest that putting a lock option to hide the ST icons could really help in the UI if the users want only the chats.. pretty much I got the idea of this like the Netflix screen lock..

**Describe alternatives you've considered**
It can be either a lock or toggle button, devs can come up to something related to that, if the lock toggle isn't ideal

**Comment by Cohee1207** [comment]
What are the icons you mention? Character/user avatars? You can disabled them in chat by using "single document" style

**Comment by fleroviumcynide** [comment]
![IMG_1710](https://github.com/SillyTavern/SillyTavern/assets/140582865/0590d387-bbcd-4d0a-ba9e-b8f455c04fc7)

Nope, I was saying the ST icons.. such as Api Settings, Ui settings, Persona management, Character descriptions settings etc.. are they possible to hide and unhide?

**Comment by Cohee1207** [comment]
Added in staging branch. Select "Toggle Panels" option in the lower-left menu.
