### ISSUE TITLE
missing module?

### ISSUE THREAD

**Issue by Tarcaxoxide** [SillyTavern/SillyTavern#814]
> **Warning**. Complete **all** the fields below. Otherwise your bug report will be **ignored**!

**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
I tried to run it but it complains about a missing module, i'm not entirely sure how to acquire said module.

**To Reproduce**
1. git clone the repository.
2. git pull'd just to be sure.
3. run ./start.sh 

**Expected behavior**
it starts up just like the tavernAI does (which i already had working but wanted to try this)

**Screenshots**
**Logs**
I'm not going to bother screenshoting text so i'll just copy and past it here...
``` bash
logan@logan ~/prg/SillyTavern $ ./start.sh 
Installing Node Modules...

up to date in 305ms

39 packages are looking for funding
  run `npm fund` for details
Entering SillyTavern...
Running from source
node:internal/modules/cjs/loader:446
      throw err;
      ^

Error: Cannot find module '/home/logan/prg/SillyTavern/node_modules/device-detector-js/dist/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:438:19)
    at Module._findPath (node:internal/modules/cjs/loader:687:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1056:27)
    at Module._load (node:internal/modules/cjs/loader:923:27)
    at Module.require (node:internal/modules/cjs/loader:1137:19)
    at require (node:internal/modules/helpers:121:18)
    at Object.<anonymous> (/home/logan/prg/SillyTavern/server.js:90:24)
    at Module._compile (node:internal/modules/cjs/loader:1255:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1309:10)
    at Module.load (node:internal/modules/cjs/loader:1113:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/logan/prg/SillyTavern/node_modules/device-detector-js/package.json',
  requestPath: 'device-detector-js'
}

Node.js v20.2.0
```

**Desktop (please complete the following information):**
 - Hardware/Software: 
 - - OS: Gentoo Linux x86_64
 - - GPU: AMD ATI 03:00.0 Barcelo
 - - AMD Ryzen 5 5600U (12) @ 2.300GHz
 - - Kernel: 6.1.22-gentoo-dist
 - - Shell: bash 5.1.16 
 - - WM: i3
 - - Storage: 1x512GB SSD internal, 1x8TB HDD external.
 - - network: ethernet connect, DSL modem.
 - Environment: local
 - Node.js version (if applicable): v20.2.0
 - Browser: it never got to that point but i use firefox, current version `102.13.0esr (64-bit)`
 - Generation API: KoboldAI
 - Branch: "release" (ccf54547501c5f36490563a5c4b7c0124e135b26)
 - Model: erebus 6.7B (NSFW)

**Additional context**

**Comment by Cohee1207** [comment]
Try running `npm install` in your installation folder

**Comment by Cohee1207** [comment]
If that doesn't help - `rm -rf node_modules` and `npm cache clean --force` then `npm install`

**Comment by Tarcaxoxide** [comment]
> If that doesn't help - rm -rf node_modules and npm cache clean --force then npm install

that worked, thanks.

**Comment by Manofthechicken** [comment]
This didn't work for me. I'm still getting errors.

**Comment by Manofthechicken** [comment]
![Image](https://github.com/user-attachments/assets/69814718-7d48-4b36-8bfc-35de846831dc)

![Image](https://github.com/user-attachments/assets/281bdbdb-5f8e-4f17-9f7b-496f1140c2e0)

Here's some pictures of the problem.
