### ISSUE TITLE
[BUG][Claude] "Assistant:" added after AI Reply Prefix

### ISSUE THREAD

**Issue by SparkyFluffbutt** [SillyTavern/SillyTavern#815]
> **Warning**. Complete **all** the fields below. Otherwise your bug report will be **ignored**!

**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
When using the AI Reply Prefix option and Claude, a new line containing "Assistant:" is added to the end of the prompt after the user defined Prefix.

**To Reproduce**
1. Use a Claude model with the AI reply Prefix.

**Expected behavior**
The AI Reply Prefix would be the last part of the text sent to the model to be used for prefilled responses.

**Additional context**
it looks like this is from server.js line 3009 , assistantpostfix always = true.

**Comment by Cohee1207** [comment]
This feature in Chat Completion works like an extra note, not a real prefix.
Also, related  to #798

**Comment by SparkyFluffbutt** [comment]
The name is misleading then. A real prefilling option would be incredibly useful.

**Comment by Cohee1207** [comment]
Added in #798 for the staging branch.
