### ISSUE TITLE
[BUG] MODULE_NOT_FOUND error in terminal

### ISSUE THREAD

**Issue by 0mniSci** [SillyTavern/SillyTavern#820]
> **Warning**. Complete **all** the fields below. Otherwise your bug report will be **ignored**!

**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
Everytime I run Start.bat I get the error MODULE_NOT_FOUND

**To Reproduce**
1. Go to the SillyTavern folder
2. Click on Start.bat
3. See error.

**Expected behavior**
Clicking Start.bat should load SillyTavern and open it in a new tab.

![image](https://github.com/SillyTavern/SillyTavern/assets/92959011/82a6465b-1e58-4115-b7a8-d70ef0261c72)

**Desktop (please complete the following information):**
 - OS/Device: Windows 11
 - Environment: [cloud, local]
 - Node.js version: 20.5.0
 - Browser: OperaGX
 - Generation API: Proxy
 - Branch: release
 - Model: N/A

**Comment by Cohee1207** [comment]
Remove node_modules folder and restart the server

**Comment by Cohee1207** [comment]
If that didn't help - `npm cache clean --force`

**Comment by 0mniSci** [comment]
Removing node_modules worked! Thanks.
