### ISSUE TITLE
[BUG] Emoticons used by the AI aren't being displayed in SillyTavern's chat

### ISSUE THREAD

**Issue by WolframRavenwolf** [SillyTavern/SillyTavern#821]
**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
Emoticons used by the AI aren't being displayed in SillyTavern's chat.

**To Reproduce**
1. Have the AI send emoticons, either by asking for it or using examples messages with emoticons for the AI to mimic.
2. Check koboldcpp command line window and see that the output includes emoticons.
3. SillyTavern's chat doesn't show the emoticons, though.

**Expected behavior**
I expect the output to be displayed properly, including emoticons.

**Screenshots**
n/a

**Logs**
n/a

**Desktop (please complete the following information):**
 - OS/Device: Windows 11
 - Environment: local
 - Node.js version (if applicable): v18.17.0
 - Browser: Firefox, Chrome (tested with both)
 - Generation API: KoboldAI (koboldcpp 1.37.1a)
 - Branch: main (1.9.3)
 - Model: any (LLaMA / Llama 2)

**Additional context**
*Not* using simple-proxy-for-tavern anymore. It's just SillyTavern directly in front of koboldcpp.

**Comment by Cohee1207** [comment]
Koboldcpp problem, not ours. Emojis are usually two tokens, but they are being streamed as two separate decoded pieces of text which mess the formatting. Report this to koboldcpp, we have nothing to do with this. Oobabooga does this correctly, so there's no way this is my problem.

**Comment by WolframRavenwolf** [comment]
Thanks for the explanation. I opened a bug report for KoboldCpp. Closing this here.

[[User] Emoticons used by the AI aren't being streamed correctly · Issue #353 · LostRuins/koboldcpp](https://github.com/LostRuins/koboldcpp/issues/353)
