### ISSUE TITLE
[BUG] Linebreak missing before Custom Chat Separator / Newlines escaped instead of interpreted

### ISSUE THREAD

**Issue by WolframRavenwolf** [SillyTavern/SillyTavern#823]
**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
If there's no "Custom Chat Separator" and "Disable chat start formatting" is on, the greeting message follows immediately the preceding text without any whitespace, messing up the context that way.
If there's a "Custom Chat Separator", there's no linebreak in front of it, even with "Wrap Sequences with Newline" enabled (which probably applies only to Instruct mode fields anyway), messing up the context that way.
And a `\n` in the "Custom Chat Separator" field becomes `\\n` instead of a newline (this should IMHO always be interpreted as a newline, also in Instruct mode fields, and never get escaped automatically!) so you can't insert newlines yourself to work around this issue.

**To Reproduce**
1. "Disable chat start formatting" off, "Custom Chat Separator" empty, check prompt in console window: It now includes "\nThen the roleplay chat between {{user}} and {{char}} begins.\n" as usual.
2. "Disable chat start formatting" on, "Custom Chat Separator" empty, check prompt in console window: It now concatenates preceding and succeeding prompt parts without any whitespace/newlines, messing up the prompt.
3. "Disable chat start formatting" on, "Custom Chat Separator" anything, check prompt in console window: It now concatenates the preceding prompt part with your custom chat separator, without any whitespace/newlines, messing up the prompt.
4. "Disable chat start formatting" on, use `\n` in "Custom Chat Separator" to work around the unwanted and prompt-breaking concatenation, check prompt in console window: The newline gets escaped as `\\n` so can't be used as a workaround.

**Expected behavior**
The Custom Chat Separator should be properly separated from the preceding prompt part. And: `\n` in all text boxes should be interpreted as a newline instead of getting automatically escaped as `\\n`! This would give the user full control over how separation is handled (in case they don't want an automatically inserted newline).

**Screenshots**
n/a

**Logs**
n/a

**Desktop (please complete the following information):**
 - OS/Device: Windows 11
 - Environment: local
 - Node.js version: v18.17.0
 - Browser: Firefox
 - Generation API: KoboldAI (koboldcpp 1.37.1a)
 - Branch: main (1.9.3)
 - Model: any (LLaMA / Llama 2)

**Additional context**
*Not* using simple-proxy-for-tavern anymore. It's just SillyTavern directly in front of koboldcpp.

**Workaround:**
I'm currently working around this issue by setting "Custom Chat Separator" to "." (just a period) and removing the ending period from my Persona Description. Since there's no whitespace/newline being inserted before, the period is added to the Persona Description and since the custom chat separator isn't empty, a newline is added afterwards, properly separating the Persona Description from the Greeting Message.

**Comment by WolframRavenwolf** [comment]
Fixed the bug myself and provided a Pull Request: [Fixed persona_description linebreak by StefanDanielSchwarz · Pull Request #842 · SillyTavern/SillyTavern](https://github.com/SillyTavern/SillyTavern/pull/842)

The actual bug was that the linebreak in function getPersonaDescription was before instead of after the persona description when it's positioned after character card, resulting in double linebreaks before and none after the persona description. I fixed it by simply moving the linebreak to the correct position.

**Comment by Cohee1207** [comment]
Is the ability to add voluntary linebreaks in the custom separator still relevant for you? I could make it a textarea instead of input to allow it, instead of decoding backslash-escaped entities.

**Comment by WolframRavenwolf** [comment]
@Cohee1207 With this bugfix, I don't need a linebreak in the custom separator anymore.

But being able to use linebreaks in general would be useful for better prompt control, and that would apply to all the Sequence input fields of Instruct Mode as well. So I think they should be textareas just like the System Prompt already is (one line height by default but expandable would be best for these).

**Comment by Cohee1207** [comment]
Added to staging.
