### ISSUE TITLE
[BUG] Objective Task Check running unexpectedly, even without any tasks

### ISSUE THREAD

**Issue by WolframRavenwolf** [SillyTavern/SillyTavern#824]
**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
Although not using the Objective extension, Task Checks are running regularly.
And even though I set Task Check Frequency from default 3 to 0 to stop that, it reverted automatically after restarting.
I had to disable the Objective extension completely to prevent the unexpected and unwanted runs.

**To Reproduce**
1. Chat with the AI and after three messages (it even counts regenerations of a single message!), the Task Check inference will run in the background, even without any tasks specified.
2. Set Task Check Frequency to 0, quit and restart SillyTavern completely, and it's back at 3.
3. Disable the Objective extension as that's the only way to stop this unexpected and unwanted behavior.

**Expected behavior**
If there are no tasks, there's no point in checking for completed tasks, so the check shouldn't run even if a Task Check Frequency is set.
And if I set Task Check Frequency manually to 0, I expect that setting to be saved and honored permanently.

**Screenshots**
n/a

**Logs**
n/a

**Desktop (please complete the following information):**
 - OS/Device: Windows 11
 - Environment: local
 - Node.js version: v18.17.0
 - Browser: Firefox
 - Generation API: KoboldAI (koboldcpp 1.37.1a)
 - Branch: main (1.9.3)
 - Model: any (LLaMA / Llama 2)

**Additional context**
*Not* using simple-proxy-for-tavern anymore. It's just SillyTavern directly in front of koboldcpp.

**Comment by Cohee1207** [comment]
@ouoertheo please take a look

**Comment by ouoertheo** [comment]
I realized the same this morning 🤦, have a fix ready in this PR https://github.com/SillyTavern/SillyTavern/pull/828

**Comment by ouoertheo** [comment]
The task check running with the config at 0 is worrisome tho. That's not part of the bug fix. Gonna try and repro that by reverting my fix locally. 

Another thing to wonder about - the setting is stored per chat, so @StefanDanielSchwarz , when you see it reset to the default setting of 3, is that specifically on a new chat? It should load your last setting for existing chats.

**Comment by WolframRavenwolf** [comment]
@ouoertheo Ah, stored per chat, that explains the behavior I was seeing. Either I started a new chat and it reverted to the default of 3, or I had changed the default to 0 and went back to an old chat where it was still 3.

Something seems to have changed with restarting and reloading, too, since when I quit and restart SillyTavern, I don't get back to the previously open chat, instead it loads an older one. Probably that caused the setting to change unexpectedly.

**Comment by ouoertheo** [comment]
Ok, thanks for the details @StefanDanielSchwarz.

I noticed that I have a catch in the function call to have the ai check status:
https://github.com/SillyTavern/SillyTavern/blob/41a08fed2b162a8fd944963331a5b3a6b87010c8/public/scripts/extensions/objective/index.js#L106 

I was originally protecting from this condition before the fix, and can't repro your issue after reverting my recent fixes locally. My bug fix was really focused on just the counter decrementing infinitely, but in my testing just now, the function bails as expected because currentTask is empty.

If you can get this to repro before pulling the fix in, can you repro and run in the browser console the below command and hook me up with the output? `debugObjectiveExtension()`

**Comment by ouoertheo** [comment]
I also did some testing with "Auto-load last chat" enabled, sounds like you have that set. Still unable to repro the issue. Will need more details to chase this. Definitely of concern since if there's a chance this is happening on a wider scale, that's charging folks who are using paid services money for no reason.

**Comment by WolframRavenwolf** [comment]
@ouoertheo OK, done:

- Re-enabled Objective extension
- Loaded old chat, checked settings, boxes empty
- Started a new chat, checked settings, Position in Chat 2 and Task Check Frequency 3 are set, Objective box empty
- Sent a message, regenerated the response, regenerated it again
- Task check runs ("Pause your roleplay. Determine if this task is completed: [].\nTo do this, examine the most recent messages. Your response must only contain either true or false, nothing other words.\nExample output:\ntrue\n    \n\n")
- Browser console: `debugObjectiveExtension()`

```
{
  "currentTask": {},
  "currentObjective": {
    "id": 0,
    "description": "",
    "completed": true,
    "parentId": "",
    "children": []
  },
  "taskTree": {
    "id": 0,
    "description": "",
    "completed": true,
    "parentId": "",
    "children": []
  },
  "chat_metadata": {
    "currentObjectiveId": 0,
    "taskTree": {
      "id": 0,
      "description": "",
      "completed": true,
      "parentId": "",
      "children": []
    },
    "checkFrequency": "3",
    "chatDepth": "2",
    "hideTasks": false,
    "prompts": {
      "createTask": "Pause your roleplay and generate a list of tasks to complete an objective. Your next response must be formatted as a numbered list of plain text entries. Do not include anything but the numbered list. The list must be prioritized in the order that tasks must be completed.\n\nThe objective that you must make a numbered task list for is: [{{objective}}].\nThe tasks created should take into account the character traits of {{char}}. These tasks may or may not involve {{user}} directly. Be sure to include the objective as the final task.\n\nGiven an example objective of 'Make me a four course dinner', here is an example output:\n1. Determine what the courses will be\n2. Find recipes for each course\n3. Go shopping for supplies with {{user}}\n4. Cook the food\n5. Get {{user}} to set the table\n6. Serve the food\n7. Enjoy eating the meal with {{user}}\n    ",
      "checkTaskCompleted": "Pause your roleplay. Determine if this task is completed: [{{task}}].\nTo do this, examine the most recent messages. Your response must only contain either true or false, nothing other words.\nExample output:\ntrue\n    ",
      "currentTask": "Your current task is [{{task}}]. Balance existing roleplay with completing this task."
    }
  },
  "extension_settings": {
    "customPrompts": {
      "default": {
        "createTask": "Pause your roleplay and generate a list of tasks to complete an objective. Your next response must be formatted as a numbered list of plain text entries. Do not include anything but the numbered list. The list must be prioritized in the order that tasks must be completed.\n\nThe objective that you must make a numbered task list for is: [{{objective}}].\nThe tasks created should take into account the character traits of {{char}}. These tasks may or may not involve {{user}} directly. Be sure to include the objective as the final task.\n\nGiven an example objective of 'Make me a four course dinner', here is an example output:\n1. Determine what the courses will be\n2. Find recipes for each course\n3. Go shopping for supplies with {{user}}\n4. Cook the food\n5. Get {{user}} to set the table\n6. Serve the food\n7. Enjoy eating the meal with {{user}}\n    ",
        "checkTaskCompleted": "Pause your roleplay. Determine if this task is completed: [{{task}}].\nTo do this, examine the most recent messages. Your response must only contain either true or false, nothing other words.\nExample output:\ntrue\n    ",
        "currentTask": "Your current task is [{{task}}]. Balance existing roleplay with completing this task."
      }
    }
  },
  "prompts": {
    "createTask": "Pause your roleplay and generate a list of tasks to complete an objective. Your next response must be formatted as a numbered list of plain text entries. Do not include anything but the numbered list. The list must be prioritized in the order that tasks must be completed.\n\nThe objective that you must make a numbered task list for is: [{{objective}}].\nThe tasks created should take into account the character traits of {{char}}. These tasks may or may not involve {{user}} directly. Be sure to include the objective as the final task.\n\nGiven an example objective of 'Make me a four course dinner', here is an example output:\n1. Determine what the courses will be\n2. Find recipes for each course\n3. Go shopping for supplies with {{user}}\n4. Cook the food\n5. Get {{user}} to set the table\n6. Serve the food\n7. Enjoy eating the meal with {{user}}\n    ",
    "checkTaskCompleted": "Pause your roleplay. Determine if this task is completed: [{{task}}].\nTo do this, examine the most recent messages. Your response must only contain either true or false, nothing other words.\nExample output:\ntrue\n    ",
    "currentTask": "Your current task is [{{task}}]. Balance existing roleplay with completing this task."
  }
} index.js:513:13
```

**Comment by ouoertheo** [comment]
That's definitely unexpected. `currentTask": {}` should have evaluated to true with this `jQuery.isEmptyObject(currentTask)` and returned without running the rest of the function.

Not sure how well versed in debugging you are, but if possible can you open the debugger in the browser tools, navigate to the index.html under scripts/extensions/objective/index.js in the sidebar and find the line that has this code:
```
    if (jQuery.isEmptyObject(currentTask)) {
```
![image](https://github.com/SillyTavern/SillyTavern/assets/5422109/7be68986-1e74-48b9-a053-4e6a144302ac)

Add a break point by clicking the line number, then repeat that process until the code pauses on the break point.
Then in the console run and provide the output to the following two commands:
`jQuery.isEmptyObject(currentTask)`
`Object.keys(currentTask).length`

Alternatively, I can try and push another fix using a different way to check for empty current task.

**Comment by WolframRavenwolf** [comment]
@ouoertheo OK, here's the output when the breakpoint was reached:

` jQuery.isEmptyObject(currentTask)`

```
false
```

` Object.keys(currentTask).length`

```
10
```

And here's `debugObjectiveExtension()` once more in case that's useful as well:

```
{
  "currentTask": {
    "id": 0,
    "description": "",
    "completed": false,
    "parentId": "",
    "children": []
  },
  "currentObjective": {
    "id": 0,
    "description": "",
    "completed": false,
    "parentId": "",
    "children": []
  },
  "taskTree": {
    "id": 0,
    "description": "",
    "completed": false,
    "parentId": "",
    "children": []
  },
  "chat_metadata": {
    "currentObjectiveId": 0,
    "taskTree": {
      "id": 0,
      "description": "",
      "completed": false,
      "parentId": "",
      "children": []
    },
    "checkFrequency": "3",
    "chatDepth": "2",
    "hideTasks": false,
    "prompts": {
      "createTask": "Pause your roleplay and generate a list of tasks to complete an objective. Your next response must be formatted as a numbered list of plain text entries. Do not include anything but the numbered list. The list must be prioritized in the order that tasks must be completed.\n\nThe objective that you must make a numbered task list for is: [{{objective}}].\nThe tasks created should take into account the character traits of {{char}}. These tasks may or may not involve {{user}} directly. Be sure to include the objective as the final task.\n\nGiven an example objective of 'Make me a four course dinner', here is an example output:\n1. Determine what the courses will be\n2. Find recipes for each course\n3. Go shopping for supplies with {{user}}\n4. Cook the food\n5. Get {{user}} to set the table\n6. Serve the food\n7. Enjoy eating the meal with {{user}}\n    ",
      "checkTaskCompleted": "Pause your roleplay. Determine if this task is completed: [{{task}}].\nTo do this, examine the most recent messages. Your response must only contain either true or false, nothing other words.\nExample output:\ntrue\n    ",
      "currentTask": "Your current task is [{{task}}]. Balance existing roleplay with completing this task."
    }
  },
  "extension_settings": {
    "customPrompts": {
      "default": {
        "createTask": "Pause your roleplay and generate a list of tasks to complete an objective. Your next response must be formatted as a numbered list of plain text entries. Do not include anything but the numbered list. The list must be prioritized in the order that tasks must be completed.\n\nThe objective that you must make a numbered task list for is: [{{objective}}].\nThe tasks created should take into account the character traits of {{char}}. These tasks may or may not involve {{user}} directly. Be sure to include the objective as the final task.\n\nGiven an example objective of 'Make me a four course dinner', here is an example output:\n1. Determine what the courses will be\n2. Find recipes for each course\n3. Go shopping for supplies with {{user}}\n4. Cook the food\n5. Get {{user}} to set the table\n6. Serve the food\n7. Enjoy eating the meal with {{user}}\n    ",
        "checkTaskCompleted": "Pause your roleplay. Determine if this task is completed: [{{task}}].\nTo do this, examine the most recent messages. Your response must only contain either true or false, nothing other words.\nExample output:\ntrue\n    ",
        "currentTask": "Your current task is [{{task}}]. Balance existing roleplay with completing this task."
      }
    }
  },
  "prompts": {
    "createTask": "Pause your roleplay and generate a list of tasks to complete an objective. Your next response must be formatted as a numbered list of plain text entries. Do not include anything but the numbered list. The list must be prioritized in the order that tasks must be completed.\n\nThe objective that you must make a numbered task list for is: [{{objective}}].\nThe tasks created should take into account the character traits of {{char}}. These tasks may or may not involve {{user}} directly. Be sure to include the objective as the final task.\n\nGiven an example objective of 'Make me a four course dinner', here is an example output:\n1. Determine what the courses will be\n2. Find recipes for each course\n3. Go shopping for supplies with {{user}}\n4. Cook the food\n5. Get {{user}} to set the table\n6. Serve the food\n7. Enjoy eating the meal with {{user}}\n    ",
    "checkTaskCompleted": "Pause your roleplay. Determine if this task is completed: [{{task}}].\nTo do this, examine the most recent messages. Your response must only contain either true or false, nothing other words.\nExample output:\ntrue\n    ",
    "currentTask": "Your current task is [{{task}}]. Balance existing roleplay with completing this task."
  }
} index.js:513:13
```

So `currentTask` is now more than just `{}`!

**Comment by ouoertheo** [comment]
Ah, that at least makes sense now and gives me a path forward.

**Comment by ouoertheo** [comment]
Ok. The root task was not excluded from the task selection logic. Added an exclusion for that. Should fix this bug properly.
https://github.com/SillyTavern/SillyTavern/pull/834

**Comment by Cohee1207** [comment]
Bug fix merged and released. Reopen if persists.
