### ISSUE TITLE
[BUG] Temperature can't be set to 0 in the UI

### ISSUE THREAD

**Issue by WolframRavenwolf** [SillyTavern/SillyTavern#825]
**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
KoboldAI API: Kobold Presets (haven't checked if others are affected):
The Temperature slider's minimum value is 0.10. Manually inputting 0 is possible, but although the value is then shown, it still uses the former one and the slider doesn't move.
The only way to set Temperature to 0 is by editing the preset file. Then it loads the 0.0 value and uses it for inference.

**To Reproduce**
1. Move Temperature slider to its leftmost position, it's 0.10 instead of 0.00.
2. Enter 0 manually. The value is displayed, but the slider doesn't move.
3. Chat with the AI and check the koboldcpp console window to see it's still using the previous value.
4. Save and edit a preset in a texteditor, set temperature 0, and load it. Now it works.

**Expected behavior**
I want to set Temperature to 0 for a fully deterministic preset (I just want to use Top K 1 to always get the most probable token), so the UI should allow me to configure a preset that way without resorting to texteditor workarounds.

**Screenshots**
n/a

**Logs**
n/a

**Desktop (please complete the following information):**
 - OS/Device: Windows 11
 - Environment: local
 - Node.js version: v18.17.0
 - Browser: Firefox
 - Generation API: KoboldAI (koboldcpp 1.37.1a)
 - Branch: main (1.9.3)
 - Model: any (LLaMA / Llama 2)

**Additional context**
*Not* using simple-proxy-for-tavern anymore. It's just SillyTavern directly in front of koboldcpp.

**Comment by Cohee1207** [comment]
Done.

**Comment by WolframRavenwolf** [comment]
Thanks for the super quick commit!
