### ISSUE TITLE
[Feature Request] Support Petals Chat API

### ISSUE THREAD

**Issue by WolframRavenwolf** [SillyTavern/SillyTavern#826]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
Petals (https://petals.dev/) does LLM inference over a BitTorrent‑style network, allowing you to use e. g. Llama 2 70B without running it yourself, so it can be compared to KoboldAI Horde. Having this supported inside SillyTavern would open up Llama 2 and other big LLMs to users lacking the systems to run them, and support a new approach to distributed LLM usage.

**Describe the solution you'd like**
The API is documented here: https://github.com/petals-infra/chat.petals.dev - maybe someone can implement it for SillyTavern.

**Describe alternatives you've considered**
I tried connecting to the Petal Chat endpoints using the Text Completion API, in case it might already work out of the box, but couldn't get it to connect.

**Additional context**
I can only run Llama 2 70B q2_K with about 0.4T/s on my system, so I'm limited to smaller models. With a distributed inference network like Petals, users like me could use the biggest models in SillyTavern without being locked into proprietary vendors like ~Open~ClosedAI or setting up cloud servers.

**Comment by Cohee1207** [comment]
Not possible in the current state. They don't provide a way to use it like a normal API, they require Python and a proper model tokenizer to function. As I have stated numerous times, it's better to have it implemented on Kobold or oobabooga side, they both run Python.

**Comment by WolframRavenwolf** [comment]
Thanks for the quick response. Searched for "Petals" but didn't find your statements. Will close this issue then.
