### ISSUE TITLE
[Feature Request] Close a chat without to have starting a new one

### ISSUE THREAD

**Issue by Woisek** [SillyTavern/SillyTavern#829]
In the title. When I feel a session has come to an end, I would like to close the chat, but without starting a new one.
First, because I mostly use another character and secondly it generates an empty chat log file.

Any chance we get a "Close Chat" button/entry that closes the chat (file) and takes us to the main/start page? 🤔

**Comment by aetherwu** [comment]
That defenintely needs a second confirm dialog X-D

**Comment by Cohee1207** [comment]
@aetherwu why? It is hidden deep enough to prevent accidental clicks.

**Comment by Cohee1207** [comment]
In contrary, switching characters does not need confirmation. It is similar action, but switching to "undefined" character instead.

**Comment by Woisek** [comment]
Thanks! 👍🎉🎉

**Comment by Woisek** [comment]
Just noticed now, that "Close chat" is not available anymore ... ?! 🤔
SillyTavern 1.9.7 'release'(5ccbbe23)

What happened?

**Comment by Cohee1207** [comment]
It was moved to a slash command `/closechat`
There wasn't an appropriate place for it in the UI, as the initially chosen menu confused some users.

**Comment by Woisek** [comment]
>There wasn't an appropriate place for it in the UI, as the initially chosen menu confused some users.

Well, I personally would not have placed it where it was, but between "Start new chat" and "View past chats". 
But to remove the entry completely I find a bit exaggerated. What is confusing about "Close chat"? 🤔

**Comment by Cohee1207** [comment]
Makes sense, thanks. I returned it to the position you proposed. Will be coming back next release. If you want it now - cherry-pick this commit to your release branch: https://github.com/SillyTavern/SillyTavern/commit/9f49a2612cc8da1f8a753632730383def12f0502

**Comment by aetherwu** [comment]
Users are always greedy. Haaa.

Look at the menus in the pop-up panel, there were already too many options. Each one of them is an extra burden and digests an extra cognitive resource in the user's mind - which the user is usually not aware of. 

It also confuses new users: "I haven't even started yet, what's this 'close' button for?" 

The more stuiation appears to the user, the harder it is for the new user to learn and remember all these settings.
I understand this is a 'pro' version for the power user, but it should be kept as simple as possible.

It's always easy to add one thing and never remove it from the product. It's a long term view of what it should be.

However, a 'close' button in the right or left corner of the chat window seems to be a reasonable idea in practice, which leads to other conflicts...



BY THE WAY. I saw a new 'back to parent chat' button there, but it did nothing when I clicked it. Does anyone know what it is for?

**Comment by Woisek** [comment]
> Makes sense, thanks. I returned it to the position you proposed. Will be coming back next release. If you want it now - cherry-pick this commit to your release branch: [9f49a26](https://github.com/SillyTavern/SillyTavern/commit/9f49a2612cc8da1f8a753632730383def12f0502)

Thanks, great to read. 🙂

**Comment by Woisek** [comment]
@aetherwu 
The thing is, it depends on the option and what it does. And a simple "closing" of something isn't really a highly complex option.
People use MS Excel ... they will understand ST ... 🤪
