### ISSUE TITLE
[Feature Request] storyteller mode

### ISSUE THREAD

**Issue by aetherwu** [SillyTavern/SillyTavern#836]
**Have you searched for similar [requests]
Yes

**Is your feature request related to a problem? Please describe.**
Now storytelling is intergrated in converstion. It mixes the experience of character and story together.

**Describe the solution you'd like**
```
{{char}}: doing sth.
*story ... (manually or automaticially by specific prompt.)*
{{user}}:
```

**Describe alternatives you've considered**
It is possible to use a group chat, but the setting are complex.
It would be easy to just setup a storyteller (or come from Auther's notes), and let it speard out or push the story into next statge. 
User can also insert story manually right after a certain converstaion.
All these stories are isolated from converstaion between characters.

**Comment by Cohee1207** [comment]
Using /sys slash command allows you to add messages without character attribution

**Comment by aetherwu** [comment]
Thanks a lot. I tested and it works as I mentions above.
But in terms of experience, /sys commond and it form
```
System August 1, 2023 1:57 
Fire alarm approching.
```
did not help a lot. At least the name 'Storyteller' could help a bit in conversation instead of a 'System' prompt emerges.

May be an alternative way is to apply a different UI present, without any avatar or name or timestamp. Just pure prompt there, so it feels like you are reading a book, switch between story and user's converstaion seamlessly.

Just suggestion there. I am still on my way to go through the project setting and code inside. It might takes some time until I can contribute some minor work.

**Comment by Cohee1207** [comment]
"System narrator message" is purely cosmetic, its name and avatar are not utilized. Though the possibility to hide name/avatars exists, there's just no way to trigger it.

**Comment by Cohee1207** [comment]
"Story" context template + "Single document" mode should cover this request.

**Comment by aetherwu** [comment]
I'm going to try this! Cool!
