### ISSUE TITLE
[BUG] Objective plugin blocks generation in group chat.

### ISSUE THREAD

**Issue by ghost** [SillyTavern/SillyTavern#843]
> **Warning**. Complete **all** the fields below. Otherwise your bug report will be **ignored**!

**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
In a group chat if a) The Objective plugin does completion check and b) another character is triggered to reply, what happens is that the second character's prompt gets refused by API (ex. kobold.cpp returns service unavailable.). Eventually completion check gets returns but Sillytavern still keeps waiting for a response for the second character which never comes, derailing the program and blocking further generation and unable to cancel. Only refreshing the browser tab gets back to generation again.

**Expected behavior**
Waiting on task check to complete before triggering / sending prompt of second character.

**Desktop (please complete the following information):**
 - OS/Device: [linux (arch)]
 - Environment: [local over lan]
 - Node.js version (if applicable): [v20.4.0]
 - Browser [ chromium, firefox]
 - Generation API [kobold.cpp]
 - Branch: [dev]
 - Model [various llama based

**Comment by Cohee1207** [comment]
Thanks, should be fixed now

**Comment by ghost** [comment]
Not in a position to check rn, but thanks for the quick response.

**Comment by Cohee1207** [comment]
Fixed and released.
