### ISSUE TITLE
[Feature Request] Proper Kobold error handling

### ISSUE THREAD

**Issue by wereretot** [SillyTavern/SillyTavern#844]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
**Yes**/No

**Is your feature request related to a problem? Please describe.**

Yes, when VRAM runs low and a CUDA error occurs with KoboldAI API, it prints an error in console but doesn't show it in the UI leaving me confused when no responses are coming through.

**Describe the solution you'd like**
I would like an error message to be printed when CUDA runs into an issue like OUT OF MEMORY or other errors.

**Describe alternatives you've considered**
Manually checking consoles takes time away from gameplay.
**Additional context**

**Comment by Cohee1207** [comment]
Pushed to staging

**Comment by Cohee1207** [comment]
Fixed and released.
