### ISSUE TITLE
[Feature Request] HTTPS/SSL network traffic encryption enabled by default

### ISSUE THREAD

**Issue by 2good4hisowngood** [SillyTavern/SillyTavern#854]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes, and while I see in the Readme to only use http, and I've seen mentions that https would need to be done separately, I don't see any instructions to enable this. 

**Is your feature request related to a problem? Please describe.**
This is a security concern, unencrypted traffic could be snooped on across the network. I'd imagine some of the primary audiences of this platform would not want their traffic being sniffed and stored to be used against them later.

**Describe the solution you'd like**
I would like to see https enabled by default, even if it's a self-signed cert. It'd provide the means for you to encrypt your traffic to the endpoint, and make it more reasonable to host in a way that makes it more externally accessible.

**Describe alternatives you've considered**
The main benefit of SillyTavern to me is the local hosted functionality, I can launch it on a server with a gpu and TextGenUI, have them talk locally on the machine, and then access it on my local network. When I get outside of my local network I can't use it without disclosing my (to my knowledge) unencrypted traffic to whatever networks I'm accessing over.

**Additional context**
A self-signing cert could eliminate this concern as a short term bandaid, it would throw the annoying "This site is not trusted, are you sure you want to proceed" kind of warning, and you could have a flag like -no_https to allow people to launch it without that warning if it bothers them or their users. It'd allow Day1 network encryption and protect your users, with the possibility to put other more sophisticated protections in place later.

**Comment by Cohee1207** [comment]
By enabling a connection from another machines by either whitelisting IPs or enabling listen mode you take the full responsibility for configuring your instance for privacy and security, as we do not optimize the app to be used over public networks. I can't imagine self-signed certs being a strict requirement. Configuring this on your end is a one-time action.

**Comment by 2good4hisowngood** [comment]
To be clear, that's a 'Won't fix' response not a can't happen response right? I don't think that adding partial measures along the lines of this capability in any way makes the repo organizers more responsible for the privacy/security. Could you point me to the relevant files I would need to pay attention to, to understand the http listening endpoint? I don't know javascript, but perhaps I could look around a bit and see if there's a solution I might be able to suggest? It's not so much that it must have a self-signed cert, just that there should be some kind of basic level encryption between the app and agents talking to it on the network.

**Comment by Cohee1207** [comment]
server.js file is responsible for setting up HTTP listeners.

**Comment by WolframRavenwolf** [comment]
Here's how the same feature request was handled by KoboldCpp:

[Is it possible to use https instead of http? · Issue #335 · LostRuins/koboldcpp](https://github.com/LostRuins/koboldcpp/issues/335)

This includes simple instructions how to set up a reverse proxy (Caddy) that would work just as well with SillyTavern.

It also mentions their simple two-liner batch script which creates a Cloudflare tunnel: [Remote-Link.cmd](https://github.com/LostRuins/koboldcpp/blob/concedo/Remote-Link.cmd) - we'd just have to change the port number to 8000.

> [Remote-Link.cmd to set up a cloudflare tunnel by StefanDanielSchwarz · Pull Request #864 · SillyTavern/SillyTavern](https://github.com/SillyTavern/SillyTavern/pull/864)

Finally, we have a [Docker Composefile](https://github.com/SillyTavern/SillyTavern/blob/release/docker/docker-compose.yml) that could easily be extended with an nginx-proxy. If there's interest in that, I'd add it and create a Pull Request.

**Comment by 2good4hisowngood** [comment]
@StefanDanielSchwarz, I think that'd be great, I could then use docker to spin up instances that have back-end access to the LLM and route to them publicly more securely.
