### ISSUE TITLE
[BUG] SillyTavern aborts the message generation process when the browser window is inactive

### ISSUE THREAD

**Issue by vfnm** [SillyTavern/SillyTavern#855]
> **Warning**. Complete **all** the fields below. Otherwise your bug report will be **ignored**!

**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
I use ST with my Poe API Server for story writing and when I use a very high context size, the message can take quite some time, which is why I leave the browser app (when using ST on my smartphone). Often times ST then cancels the current message generation process and the message gets lost.

**Expected behavior**
I would expect that the message generation would still happen in the background.

**Desktop (please complete the following information):**
 - OS/Device: Android when using ST, while the server itself is hosted on a Docker instance
 - Browser Chrome

**Comment by submaroon** [comment]
Same trouble.
If I open SillyTavern at remote device (PC or Laptop) I have same problem if I switch to another window or tab

**Comment by Cohee1207** [comment]
@SubMaroon 
Need more info about your API/model and setup.

**Comment by submaroon** [comment]
> @SubMaroon Need more info about your API/model and setup.

The last SillyTavern and oogabooga web-ui
SillyTavern looks into the internet via keenetic DDNS/ Remote hosts - Ubuntu and Android
70% - abort
It's strange behavior. Is SillyTavern connect to web-ui permanently or when it POST and GET a queries only?

**Comment by Cohee1207** [comment]
Not permanently, only on requests to generation, and your tunneling method could interrupt long-running connections to oobabooga. There's no timeout for requests that ST makes to oobabooga, but there were numerous cases of remote hosts abrupting connections that take longer than 30 seconds. There's nothing we can do from the ST side regarding that, please look at the configuration of your remote connections.

**Comment by submaroon** [comment]
Thanks! I'll think to resolve a trouble
