### ISSUE TITLE
[BUG] Markdown star *text* is not being rendered correctly or predicatably.

### ISSUE THREAD

**Issue by imesha10** [SillyTavern/SillyTavern#857]
> **Warning**. Complete **all** the fields below. Otherwise your bug report will be **ignored**!

**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes. Serached for * and star and nothing came up on this github repo issue trackers.

**Describe the bug**
The starred * *text* * is not being rendered correctly in the output. See visual examples below.

**To Reproduce**
1. Go to silly tavern and select any character text box and press edit.
2. Type in "* text*" without the quotes.
3. Press the green checkmark to save it.

**Expected behavior**
It fails on multiple ways. I will show with screen shots.

The first one is an error that happens when it's in front.
1st Input:
![image](https://github.com/SillyTavern/SillyTavern/assets/16441743/569f2591-b84b-491e-b5de-4cd419cfe316)
1st Output:
![image](https://github.com/SillyTavern/SillyTavern/assets/16441743/e1cfa9c9-5dea-469c-bf67-d09f023ce73b)
1st Expected Output:
![image](https://github.com/SillyTavern/SillyTavern/assets/16441743/8211a3e7-dabe-47db-94f2-94beba000726)

The second one is what happens when there is a space in front of the *.
2nd Input:
![image](https://github.com/SillyTavern/SillyTavern/assets/16441743/af52bf2c-151c-47da-8058-3315a8e7a283)
2nd Output:
![image](https://github.com/SillyTavern/SillyTavern/assets/16441743/07274035-caa8-4e10-9caa-8f738a00051b)
2nd Expected Output:
![image](https://github.com/SillyTavern/SillyTavern/assets/16441743/178e8ce3-9052-4029-be07-13c048a75691)

The third one is what happens when there is a space before the closing of the *.
3rd Input:
![image](https://github.com/SillyTavern/SillyTavern/assets/16441743/8a1f90b6-669d-4760-86d3-5ab0942d739e)
3rd Output:
![image](https://github.com/SillyTavern/SillyTavern/assets/16441743/6886ebd3-dc81-4179-b2a6-86fb256e5e49)
3rd Expected Output:
![image](https://github.com/SillyTavern/SillyTavern/assets/16441743/65630314-4670-42b9-87c6-e285ed296e79)

The fourth one is what happens when there is a space between both ends.
4th Input:
![image](https://github.com/SillyTavern/SillyTavern/assets/16441743/851d01ef-a57b-4450-9ad6-d944a3eaefde)
4th output:
![image](https://github.com/SillyTavern/SillyTavern/assets/16441743/e1434234-e4f3-44a2-85cb-b09151b432f9)
4th Expected Output:
![image](https://github.com/SillyTavern/SillyTavern/assets/16441743/65630314-4670-42b9-87c6-e285ed296e79)

**Logs**
Ask if needed, probably don't need it.

**Desktop (please complete the following information):**
 - OS/Device: Wndows 11
 - Environment: local
 - Node.js version (if applicable):  v18.15.0
 - Browser [e.g. chrome, safari]: Chrome
 - Generation API [e.g. KoboldAI, OpenAI]: Not relevant but claude via poe via openai custom proxy
 - Branch: dev
 - Model [e.g. Pygmalion 6b, LLaMa 13b]: claude/openai

**Comment by 50h100a** [comment]
Is this box checked User Settings?
![firefox_U5JpsiIMyy](https://github.com/SillyTavern/SillyTavern/assets/136940546/329aed51-50b5-4139-894d-99be9daed498)

**Comment by Cohee1207** [comment]
`*this *` is not a valid Markdown
`* this*` denotes an unordered list

If your model can't produce a valid Markdown, switch to novel formatting. Quotes for speech, plain text for others. Or try "autofix" option as mentioned above.

**Comment by imesha10** [comment]
Thank you, @50h100a and @Cohee1207, the Auto fix markdown fixed the issue.
