### ISSUE TITLE
[BUG / Wrong behavior] Summarize plugin messing up the group chats.

### ISSUE THREAD

**Issue by valden80** [SillyTavern/SillyTavern#866]
**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
In the group chat Summarize plugin don't switch what is it injecting between talking characters. This is cause huge mess sometimes, when summary catching some facts about one character, but currently talking/acting is another.
(Actually I spent more then a day to get it - why in group chat some characters suddenly starting behave so wrong, while in single chat - they excellent.)

**To Reproduce**
1. Start group chat.
2. Add two or more characters.
3. Chat with characters enough to activate Summarize.
4. See in the console of backend what is injected.

**Expected behavior**
Change of injecting data from Summarize so they are personal for every characters. Ss if the single character chats switching - different summary catching and injecting for different characters. (Catching the summary only right after the current character talking, injecting - only for it.)
Or, if this is impossible to implement - option to auto disable Summarize for group chats. At least it will not mess it then.
Or, option to disable summary injection for all group chat character otherwise then first/main character (selected as main).

**Screenshots**
None, it's text console data.

**Logs**
No errors, just wrong behavior.

**Desktop (please complete the following information):**
 - OS/Device: Manjaro Linux
 - Environment: local
 - Node.js: version 20.2.0
 - Browser: Firefox
 - Generation API: Oobaboga
 - Branch: dev
 - Model: any

**Additional context**
None.

**Comment by Cohee1207** [comment]
Related, #843

**Comment by valden80** [comment]
Commit about different problem, though slightly similar. 
With group chat Summarize need mechanic to separate summary data between characters, or summary might be wrong and make wrong context. Right now it's simply inject one summary for all characters. This is logically wrong as summary can contain personal data strictly related for one and single character. Something like "He has wing able to fly high." As it get in context of different character - it's mess him.

**Comment by Cohee1207** [comment]
Okay, then it's not a bug, but rather a feature request. Cause summaries are hard tied to chats, not the characters.
