### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by R-o-m-a-ntic** [SillyTavern/SillyTavern#870]
> **Warning**. Complete **all** the fields below. Otherwise, your bug report will be **ignored**!

**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
prompt-manager-cherrypicked is unable to use Claude.

**To Reproduce**
1. Clone latest prompt-manager-cherrypicked
2. Choose "Chat Completions" in API Connections
3. Select "Claude" in Chat Completions Source
4. Insert Claude Source
5. Click "Test Message"
6. The interface notifies that there's an error but no error message appears in Powershell; connections have not been established and no messages can be sent to the LLM.

**Expected behavior**
For branch prompt-manager-cherrypicked to be able to send messages to Claude as it can with OAI and other LLMs.

**Screenshots**

**Logs**

Providing the logs from the browser DevTools console (opened by pressing the F12 key) or SillyTavern command line window will be highly appreciated.

**Desktop (please complete the following information):**
 - Windows 11
 - local
 - v18.16.0
 - Firefox, Vivaldi (tested on both)
 - Claude
 - prompt-manager-cherrypicked
 - Claude 2.0

**Additional context**

**Comment by Cohee1207** [comment]
Ok, I think I got this
