### ISSUE TITLE
[Feature Request] Multiple Chrome Tab Usage

### ISSUE THREAD

**Issue by Tgh3iyo** [SillyTavern/SillyTavern#883]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
The reason why I suggest this was cause somewhere around SillyTavern 1.4.0, the usage of using multiple chrome tabs for different chatbot characters was quick and multitasking to do since OpenAI was the only API that could make it happen. Personally, it was discovered by accident by me, yet it worked quite well. All you had to do was just press send twice and it would work.

![2](https://github.com/SillyTavern/SillyTavern/assets/64932563/56df8e04-0c27-424d-9c8d-5e1852ade0fe)

**Describe the solution you'd like**
That when you do multiply a SillyTavern tab, it'll work well. Characters are still usable, multitasking is alright. Hopefully, I'd like for the usage of this to be brought back, or modified to where it could somehow be used for even OpenRouter, Window, etc. 

**Describe alternatives you've considered**
There could be a little checkbox option to on if you'd like for SillyTavern to be Multi Tab functional. Not to have it be just something to stumble by or be an error, but more apart of an cool little feature.

**Additional context**

Even if group chat is mentioned, its completely different to that than being able to talk with two characters separately, yet still there, as to get things done quicker and whatnot. Here's just a little, simple screenshot of what I do mean.

![1](https://github.com/SillyTavern/SillyTavern/assets/64932563/146ec39d-dce0-4cc1-a091-5f06c632b0e8)

**Comment by Cohee1207** [comment]
Added ability to disable CSRF tokens with `--disableCsrf` console flag or `npm run start-multi` 
Make sure to apply adequate protection measures as it will make your installation vulnerable to cross-site scripting.

**Comment by ghost** [comment]
For everyone who uses this feature: CSRF also protected you from overwriting newer data in the backend with stale data from older tabs after you opened a new one, used it for a while and then switched back to the old tab.

With `--disableCsrf` specified it is possible to lose chat messages and setting changes by switching to older tabs.

**Comment by Tgh3iyo** [comment]
Oh, does this mean that it can work now? Sorry that I'm a little uneducated about this stuff. Would I now have to download the latest SillyTavern update again to see this change?

**Comment by Tgh3iyo** [comment]
Oh, does this mean that it can work now? Sorry that I'm a little uneducated about this stuff. Would I now have to download the latest SillyTavern update again to see this change?

Also I just accidentally closed this as complete. sorry.

**Comment by Cohee1207** [comment]
This was just released. Update to use the new option.
