### ISSUE TITLE
[Feature Request] Real live2d implementation

### ISSUE THREAD

**Issue by IkariDevGIT** [SillyTavern/SillyTavern#887]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
I like the one that currently exists, but i have a live2d model of my char i wanna use

**Describe the solution you'd like**
I would like so that you can import a live2d model and set expression or whatnot triggers from the char to one of the expressions

**Describe alternatives you've considered**
Obv you could use the png "live2d" thing, but that uses too much resources, is laggy and you need sillytavern-extras

**Comment by Cohee1207** [comment]
Someone was interested in implementing this. Meanwhile, faux live2d was renamed to talkinghead not to confuse the users.

**Comment by Cohee1207** [comment]
"Real live2d" is now a downloadable plugin.
