### ISSUE TITLE
[Feature Request] Classifier Free Guidance (CFG)

### ISSUE THREAD

**Issue by IPopovSci** [SillyTavern/SillyTavern#888]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add support for Classifier Free Guidance (CFG) for oobabooga api. This will introduce a negative prompt option, which might improve writing outcomes.
Relevant PR:
https://github.com/oobabooga/text-generation-webui/pull/3325

**Describe alternatives you've considered**
Currently just hard-coding the values into ooba API files.

**Additional context**
Thank you.

**Comment by sandwichdoge** [comment]
Unrelated note, more built-in control for local model prompting would be great. Currently I'm using [simple-proxy-for-tavern](https://github.com/anon998/simple-proxy-for-tavern) and the idea of running a proxy for a proxy is absurd.

**Comment by Cohee1207** [comment]
Be more precise. What **exactly** do you need from proxy?

**Comment by IPopovSci** [comment]
> Unrelated note, more built-in control for local model prompting would be great. Currently I'm using [simple-proxy-for-tavern](https://github.com/anon998/simple-proxy-for-tavern) and the idea of running a proxy for a proxy is absurd.

Please see: https://github.com/SillyTavern/SillyTavern/issues/831



> Be more precise. What **exactly** do you need from proxy?

Any question about the CFG? It should be just a window for negative prompt and a slider for guidance scale. Examining util.py in ooba it seems like it will pick up both on lines 46-47 automatically, as long as tavern sends it in the body.

**Comment by Cohee1207** [comment]
Sorry @IPopovSci , I was talking to a guy who highjacked your issue. CFG scale for ST has open PR #889 , we're working on it
