### ISSUE TITLE
[BUG] Author's Note UI is below AI Response Configuration Tab (quick fix)

### ISSUE THREAD

**Issue by R-o-m-a-ntic** [SillyTavern/SillyTavern#891]
> **Warning**. Complete **all** the fields below. Otherwise, your bug report will be **ignored**!

**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
Author's Note does not show up on top of the Response Configuration UI when the latter is locked.

**To Reproduce**
1. Boot up any latest branch of ST (I did a fresh install of Staging, no importing old settings)
2. Open the AI Response Configuration Tab
3. Click on "Author's Note" in any chat
4. The Author's Note popup is hidden.

**Expected behavior**
Author's Note does shows up on top of the Response Configuration UI when the latter is locked.

**Screenshots**
-

**Logs**

Providing the logs from the browser DevTools console (opened by pressing the F12 key) or SillyTavern command line window will be highly appreciated.

**Desktop (please complete the following information):**
 - Win11
 - Local
 - v18.16.0
 - Vivaldi
 - Claude
 - Tested on Staging and Prompt-Manager-Cherrypicked, assumed to be a persisting issue across branches
 - Claude 2.0

**Additional context**
-

**Comment by Cohee1207** [comment]
It was a deliberate change. Previously it behaved exactly like you described, but was changed per the exact opposite request.
