### ISSUE TITLE
[Feature Request] WI for player Avatars.

### ISSUE THREAD

**Issue by valden80** [SillyTavern/SillyTavern#893]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes.
Found only https://github.com/SillyTavern/SillyTavern/issues/215 related request, but without details.

**Is your feature request related to a problem? Please describe.**
I played with several avatars now, and feel like there is lacks control about their persona's. So I went to the WI again. Worked perfectly, only with the minor issue - need to manually change of active WI books for avatars. So: 

**Describe the solution you'd like**
Why not to allow to tie WI books to player avatars the same way as for characters cards?

**Describe alternatives you've considered**
None.

**Additional context**
Low priority, though maybe it's relatively simple to implements.

**Comment by Wolfsblvt** [comment]
Fyi, this was also requested in #3131 and done in #3146
