### ISSUE TITLE
[Feature Request] Introduce settings from #831 Issue as replacement for tavern proxy

### ISSUE THREAD

**Issue by IPopovSci** [SillyTavern/SillyTavern#894]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
People keep asking for proxy-for-tavern functionality.

**Describe the solution you'd like**
Introduce a preset/setting that will set the formatting as described in https://github.com/SillyTavern/SillyTavern/issues/831
It can be named tavern-proxy-settings or similar. This (hopefully) will stop people asking for merging tavern proxy, since it seems like no-one can actually describe what it does, and discussion in #831 concludes that these settings offer same, or very similar outcomes as running the proxy itself.

**Describe alternatives you've considered**
To suffer requests for implementing proxy-for-tavern functionality without being able to describe what it actually does.

**Additional context**
Screenshot of settings in question: [Link](https://user-images.githubusercontent.com/137501172/257326948-214af7ec-ae62-421f-a1c1-21495666a2db.png)

**Comment by Cohee1207** [comment]
Thanks, that is already done in the staging branch by our contributors. You can check it out before the release by downloading the preset files from the other branch.
