### ISSUE TITLE
[BUG] Do not establish internet connections that are not required

### ISSUE THREAD

**Issue by SD-fan** [SillyTavern/SillyTavern#895]
**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?**
Yes

**Describe the bug**
I run SillyTavern 1.9.4 'release' (249ab710) branch on Win connected to a local ooba instance. As I'm behind a firewall with a self signed certificate this causes two errors to appear (that were not present in the last main branch btw):

 `Error: self-signed certificate in certificate chain
    at TLSSocket.onConnectSecure (node:_tls_wrap:1550:34)
    at TLSSocket.emit (node:events:514:28)
    at TLSSocket._finishInit (node:_tls_wrap:967:8)
    at ssl.onhandshakedone (node:_tls_wrap:743:12) {
  code: 'SELF_SIGNED_CERT_IN_CHAIN'
}`

`ForbiddenError: invalid csrf token
    at doubleCsrf (C:\ML\SillyTavern-release\node_modules\csrf-csrf\lib\cjs\index.cjs:18:61)
    at Object.<anonymous> (C:\ML\SillyTavern-release\server.js:302:49)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47`

To mitigate the issue I've tried to:

1. set NODE_TLS_REJECT_UNAUTHORIZED=0 
2. npm config set strict-ssl=false
3. In config.conf: const securityOverride = true;

All to no avail. Nevertheless SillyTavern seems to run OK.

The Firewall shows connection attempts to 
1. aihorde.net
2. x1.c.lencr.org (=letsencrypt)

**To Reproduce**
1. Install a firewall/proxy using a self signed certificate to monitor outbound SSL connections
2. Start SillyTavern server.bat

**Expected behavior**
I'd expect **no** external connections are made if running local - unless absolutely necessary. All unnecessary external connections cause tracking and security risks btw.

Alternatively I'd be happy for a clue to either
1. Disable the SSL check properly
2. A hint how to add the self signed cert to the keychain (the cert is in the windows keychain already)

**Comment by Cohee1207** [comment]
Moved AI Horde initialization to related endpoints in staging. But if you use the SD plugin with Horde, it will still appear. 

This one relates to CSRF only, and usually appears when you open two tabs at once: `ForbiddenError: invalid csrf token at doubleCsrf`

**Comment by SD-fan** [comment]
@Cohee1207 Thanks for the quick reply and fixing this in future. 

To other readers: I found the proper way how to add individual root certificates (contained in file certs.pem) to node.js:
`set NODE_EXTRA_CA_CERTS=certs.pem`

Problem mitigated.👍

**Comment by Cohee1207** [comment]
Resolved.

**Comment by sais-github** [comment]
If anybody ends up here for the same reason i did (`DEPTH_ZERO_SELF_SIGNED_CERT` then `ERR_TLS_CERT_ALTNAME_INVALID` ), when trying to connect ST to a https backend running on another pc within your network, make sure you set `X509v3 Subject Alternative Name: IP Address:<other-local-pcs-ip>` and `Issuer: CN = <other-local-pcs-ip>` in your cert file with `-subj "/CN=<other-local-pcs-ip>" -addext "subjectAltName=IP:<other-local-pcs-ip>"` on creation

If you're on windows using git bash you may need to use `-subj "//CN=<other-local-pcs-ip>" -addext "subjectAltName=IP:<other-local-pcs-ip>"`

Then set `NODE_EXTRA_CA_CERTS=/path-to/cert.pem` using the same cert file from the other pc you are launching your backend with, that's it :3

`npm config set strict-ssl false` works too, but throws security out the window

End result: 
![Image](https://github.com/user-attachments/assets/d806d575-c941-4e8a-8301-e522d01dd38d)

**Comment by Cohee1207** [comment]
> npm config set strict-ssl false works too, but throws security out the window

To be fair, you're not gaining that much security from self-signed cerificates either.
