### ISSUE TITLE
Which is the best preset for TPU Erebus?

### ISSUE THREAD

**Issue by JunkOsD** [SillyTavern/SillyTavern#897]
I decided to use this model for now, but I don't know which preset would be the best to use with Erebus (OPT-13B-Erebus to be more specific) or maybe which settings are the best to have a good experience with it.

**Comment by Cohee1207** [comment]
There is no such thing as "the best preset". It wildly depends on your personal preferences, prompts backend and model quirks, and other factors.
Try some of the community favorites:
1. Pro Writer
2. Storywriter
3. Ouroboros
4. Best Guess
