### ISSUE TITLE
[Feature Request] Automatic SD picture generation triggered by keywords

### ISSUE THREAD

**Issue by SD-fan** [SillyTavern/SillyTavern#898]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
First of all: SillyTavern is great. I've connected it to a local Stable Diffusion instance and it works as described. 

Unfortunately picture generation is all **manual** via /sd ... commands only. Even if the char is sending a picture or describing a scene pretty well, it turns out that the 'last' summary generates a messed up pic (that has nothing much to do with the response).

**Describe the solution you'd like**
In ooba's SD solution one can choose manual/interactive/automatic for picture generation, where interactive is triggered by keywords. I wish this was possible in in ST where the pic generation is triggered by (configurable) keywords said by the char. For instance the char says "Char sends a picture that contains:..." then everything after "contains" should be send to SD without manual user interaction.

**Describe alternatives you've considered**
Alternatively the exact behavior from ooba SD connection using "Picturebook/Adventure" would be great which simply generates a pic after each char response without manual commands.

**Additional context**
I'm happy to add screenshots later if case is not clear.

Thanks much!

**Comment by Woisek** [comment]
Altough I personally understand your idea ... you say that the images are messed up. With your feature, you get 'automatically' this messed up image. It doesn't change the fact, that one has to edit the prompt 99% before sending to SD. A reason, why I wished for the prompt editing we have now when using the brush icon.

**Comment by Cohee1207** [comment]
There are two modes of "generate from message" aka "last". One raw just takes the text and tries to make an image from it unaltered. The other uses an AI to summarize the image. Doing an auto-mode with raw will essentially produce suboptimal images as @/Woisek mentioned above, and the other option will double your AI calls and waiting time for every message.

**Comment by SD-fan** [comment]
Sorry if I didn't make the point clear. See this chat:
![IMG_7045](https://github.com/SillyTavern/SillyTavern/assets/129314651/6aaf3028-efe8-4e2c-ae5e-e1b51ebff8cc)

I'm getting **lot's** of "sends a picture" with a good description from my chars. In the example above: "Luke and the fuzzy alien...". This description could be used straight away as prompt in SD. Unfortunately today the resulting SD summary is messed up (as in the example above). Prompt editing makes not much sense for me as generation only takes 5 sec and I rather hit "generate" or "paintbrush" again.  

**Here is what I propose in detail:** 
If ST could be triggered to take everything after a trigger string, say "send a pic | shows a picture | ..." until it reaches  a stop word, say ". | \n | ] | ..." and then passes this string to SD: done. This would for sure end up with better results without time consuming prompt editing.

**Comment by Cohee1207** [comment]
That "sends pic" is probably a side effect of having the prompt visible to AI for future gens. I actually propose the opposite: add an option to hide the prompts from the internal chat for future gens so it won't be able to mimic the "sends picture" behavior without actually doing it.

**Comment by SD-fan** [comment]
Well, if it's a side effect, it would work great for SD prompt generation - and much better than the current summary.
Maybe then turn the side effect into a feature: hide the string and use it rather for SD. 👍
