### ISSUE TITLE
[Feature Request] Automated optimization of sampler order.

### ISSUE THREAD

**Issue by SabinStargem** [SillyTavern/SillyTavern#903]
Dunno if it would actually improve the effectiveness of AI or grant a speedup, but having Simple Tavern have a toggle to adjust the sampler order automatically would be nice.  The current setup is a bit inconvenient to reorder into the recommended configuration.

**Comment by Cohee1207** [comment]
What do you mean by "automatic"? What's the desired workflow? Sampler order can be a part of a preset.

**Comment by SabinStargem** [comment]
Each preset has its own sampler order, but Kobold's terminal says that anything other than [6,0,1,3,4,2,5] could produce unoptimal results.  I have no way of objectively verifying whether this is true, so I just use that sampler order by manually pasting it in.  That is more difficult in Silly Tavern, because the GUI doesn't show what # the sampler parameters are associated with, and requires dragging & dropping the parameters.

Manually arranging the sampler order within Silly takes awhile and requires constantly checking between the GUI and the terminals.   Right now, the fastest way to handle things is to go into the folder containing the Kobold presets, and then replace the sampler order.

It would be nice to have a toggle or button within the Silly GUI that punches in Kobold's recommendation, automatically.

**Comment by Cohee1207** [comment]
So basically "reset to recommended" button?

**Comment by Cohee1207** [comment]
I called the button "load koboldcpp order" to emphasize it's not "the best" order and not recommended or optimal, just suggested by koboldcpp and only it. Also made sampler numbers visible

**Comment by SabinStargem** [comment]
That is an ideal way to do it.  Thank you.  :)
