### ISSUE TITLE
[BUG] Where is CSFR feature??

### ISSUE THREAD

**Issue by Tgh3iyo** [SillyTavern/SillyTavern#904]
**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
I cant find CSFR option, or button.

**To Reproduce**
1. Go to Silly Tavern
2. Check all around, look at options.
3. See error

**Expected behavior**
To see the option.

**Screenshots**
![1](https://github.com/SillyTavern/SillyTavern/assets/64932563/3a167563-cb36-4359-b780-9fd5961d0076)

![2](https://github.com/SillyTavern/SillyTavern/assets/64932563/867cc207-ffb1-42d5-9da2-bf9077e1ad9d)

**Logs**

I can provide if necessary.

**Desktop (please complete the following information):**
 - OS/Device: Windows 10
 - Environment: local
 - Node.js version (if applicable): run `node --version` in cmd
 - Browser:  Chrome
 - Generation API: OpenRouter
 - Branch: release
 - Model: chatgpt3-16k

**Additional context**
None.

**Comment by ghost** [comment]
This non-feature is a command line option, see https://github.com/SillyTavern/SillyTavern/issues/883#issuecomment-1666865132.

This is not meant to be easily accessible as it will enable overwriting newer data (chats/settings/cards/etc) with older data when switching back to an old tab. The CSRF check prevents this from happening. If you turn this check off, you are responsible for all bad things that can happen.

Disabling CSRF checks also opens SillyTavern to [cross-site scripting attacks](https://en.wikipedia.org/wiki/Cross-site_request_forgery), you have to keep this in mind when you run ST with those protections disabled.

**Comment by Tgh3iyo** [comment]
Oooh, now I got it, thank you 👍

**Comment by Cohee1207** [comment]
Thanks, closing now.
