### ISSUE TITLE
[Feature Request] Can we please have <xml_tags> visibility back?

### ISSUE THREAD

**Issue by nothingsuspiciousright** [SillyTavern/SillyTavern#907]
Or make it toggable.
Just... maan. I need it to be shown when i test my prompts and jailbreaks.
That's it. And not only me.

Thank you for your attention.

**Comment by Cohee1207** [comment]
Regex plugin. Replace < with `&lt;` and > with `&gt;`

**Comment by Cohee1207** [comment]
Done. A new setting to show tags is added.
