### ISSUE TITLE
[Feature Request] prompt-manager-cherrypicked will get the prompt ordering table of the prompt-manager branch?

### ISSUE THREAD

**Issue by ahmed-elj** [SillyTavern/SillyTavern#908]
is maver is going to add the prompt ordering table from `prompt-manager` to `prompt-manager-cherrypicked` branch?

and is this even planned to be added to `staging` anytime soon?

loved the feature btw

**Comment by Cohee1207** [comment]
What is a prompt ordering table you are referring to?  Prompts list is a part of the cherry-picked branch, and it is reorderable. Inclusion in staging will be done as soon as we resolve all the migration issues

**Comment by ahmed-elj** [comment]
![vivaldi_ucZABNOg42](https://github.com/SillyTavern/SillyTavern/assets/31710770/91adc3a7-997b-4de3-b065-37b1203b5afb)
 
 yes, the prompt list is only in the outdated `prompt-manager` branch, I was asking if it is getting pushed to the updated `prompt-manager-cherrypicked` branch, or is it canceled?

**Comment by Cohee1207** [comment]
No, it is there. You may have a corrupted branch or something.
Cherry-picked is based on staging, so you need to migrate according to docs: https://docs.sillytavern.app/usage/branches/

**Comment by ahmed-elj** [comment]
I don't know what i am doing wrong here, i clone the repo using : 
`git clone https://github.com/SillyTavern/SillyTavern.git -b prompt-manager-cherrypicked` 
I opened it up and i still can't find the prompt list.

**Comment by Cohee1207** [comment]
Do you start from scratch or migrate your data by copying an entire public folder? Because in the second case, you're corrupting your installation.

**Comment by ahmed-elj** [comment]
No, I just cloned the repo in an empty folder and started run.bat, didn't modify a single file.

**Comment by Cohee1207** [comment]
Interesting. Can I see some screenshots perhaps?

**Comment by ahmed-elj** [comment]
![vivaldi_91SUM3PH0V](https://github.com/SillyTavern/SillyTavern/assets/31710770/3406cf17-7b71-400e-bee7-67e1a5825d01)
![vivaldi_m4QepXvWRB](https://github.com/SillyTavern/SillyTavern/assets/31710770/a6000e8d-24e8-4880-979e-24d0ec702c16)
![vivaldi_sMSRXtop0R](https://github.com/SillyTavern/SillyTavern/assets/31710770/87424d6e-106f-4fed-a6b9-ccf209461518)

this is `prompt-manager-cherrypicked` branch I cloned recently, all defaults

**Comment by Cohee1207** [comment]
Even more interesting. Could you open an F12 console and see for any logs or errors there?

**Comment by ahmed-elj** [comment]
no, I don't see any errors, just one thing says: 
`Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform`
 I don't think it's related...

**Comment by Cohee1207** [comment]
@artisticMink any ideas maybe?

**Comment by artisticMink** [comment]
This looks like the render function never ran. 

@lorffine 
The prompt manager only shows up after you selected a character or a group. Did you do that?
If yes and it did not show up,  please go into STs user settings and enable 'Log prompts to console', then select a character and share a screenshot of your F12 console after selecting a character.
Did you continue you to use old configuration files? (settings.conf, presets...) by copying them into the newly cloned folder?

**Comment by ahmed-elj** [comment]
Yes, indeed, my bad for not looking thoroughly. 
But why each character have a separate preset though? why not having a general saved preset, and then you can edit it for each character?

**Comment by artisticMink** [comment]
This is pretty much how it works under the hood. You can edit the predefined order in scripts/PromptManager.js:promptManagerDefaultPromptOrder. 

Having a editable preset  would mean one more location to show it, another interface to edit it, another save location to save your custom default, ui changes to apply it ...
