### ISSUE TITLE
[Feature Request] Show API costs

### ISSUE THREAD

**Issue by ghost** [SillyTavern/SillyTavern#909]
Since OpenRouter distributes its prices via API (-> https://openrouter.ai/api/v1/models), it could be possible to calculate costs for requests and accumulate (probably a bit work, BetterChatGPT does this btw), or at least show the current price per token somewhere (rather easy?).

This would help if a price for an OpenRouter model suddenly changes, as it happened with Google Palm2, from 0 to more than GPT-3.5-turbo recently.

Comment from Cohee:

> I usually against building something so specific for one API
> Pulling a list and displaying it in a popup table is okay
> Maybe something simple like small text: max price per prompt based on context size and response size set in the UI

**Comment by Cohee1207** [comment]
Done.
