### ISSUE TITLE
[BUG] Sillytavern drops outputs/generations when tavernAI is not focused on firefox browser

### ISSUE THREAD

**Issue by rsmyst** [SillyTavern/SillyTavern#91]
**Describe the bug**
When setting a prompt for generation and then making the tab inactive i.e. moving to another tab and browsing, more often than not, sillytavern receives the output from whatever model i was using but simply doesn't update teh UI with it. so when i return to the tavernAI UI in teh firefox browser, another generation gets requested for no reason so i have to wait again for another generation with no way to recover the old wasted generation.

**Additional contect**
Firefox browser
windows 10
silly tavern latest
using openAI proxies (any proxy has this problem. even turbo or gpt4)

**Comment by RossAscends** [comment]
try it without a proxy
try it in a different browser

let us know if it persists

**Comment by RossAscends** [comment]
2 month old issue, no response.
