### ISSUE TITLE
[BUG] SD UI broken after SillyTavern API call

### ISSUE THREAD

**Issue by wereretot** [SillyTavern/SillyTavern#910]
> **Warning**. Complete **all** the fields below. Otherwise, your bug report will be **ignored**!

**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
**Yes**/No

**Describe the bug**
When generating a picture via SD Auto1111 API, SD never "completes" the generation but sends it to ST. This breaks the SD UI as any command will say 'waiting'.

**To Reproduce**
1. Run an SD prompt via Silly Tavern Extras
2. Open SD UI, try to generate a picture from it.
4. wait endlessly

**Expected behavior**
I expect the generation to complete and SD UI to run normally after it.

**Screenshots**
![image](https://github.com/SillyTavern/SillyTavern/assets/28990565/5d4b1928-159a-494f-b0fb-c37ebf641ed8)
**Logs**

Providing the logs from the browser DevTools console (opened by pressing the F12 key) or SillyTavern command line window will be highly appreciated.

**Desktop (please complete the following information):**
 - OS/Device: Manjaro
 - Environment: Local
 - Node.js version (if applicable): v20.4.0
 - Browser Firefox
 - Generation API: KoboldAI
 - Branch: staging
 - Model: GPlatty 30B GPTQ

**Additional context**

**Comment by Cohee1207** [comment]
On the latest pull of extras, ST and AUTO 1111 I wasn't able to reproduce this. Both images via API and SD UI generate fine one after another.
