### ISSUE TITLE
[BUG] Expressions broken since yesterday's update

### ISSUE THREAD

**Issue by FranciscoFornell** [SillyTavern/SillyTavern#911]
> **Warning**. Complete **all** the fields below. Otherwise, your bug report will be **ignored**!

**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
Yesterday evening I found this and saved the info and screenshots to report it, so here we go:
Character expressions are broken since yesterday's update. There are't any errors logged. I was debugging and the expressions are loaded, but the setExpression function is trying to use live2D even when the option is unchecked. SillyTavernExtras seems to be returninng the classification output just fine.

I actually found the problem after debugging a little bit: 
The problem is in [this line](https://github.com/SillyTavern/SillyTavern/blob/4fd042b9a5e0deb32be3186a1f6ba2a58f1ad80f/public/scripts/extensions/expressions/index.js#L870): `extension_settings.expressions.live2d == false` is not a good way to evaluate a boolean in javascript.
In JS you should use === instead of == in most of evaluations, but in this case live2d is not false but undefined, and those are evaluated differently even with the non strict comparison. The fix is as simple as replacing `extension_settings.expressions.live2d == false` with `!extension_settings.expressions.live2d`. The negation will automatically cast the variable as a boolean and evaluated correctly, as undefined is a falsy value. Tested that fix on my computer and it worked.

I hope it helps! :)

**To Reproduce**
Just open any chat with a character that has expressions set and see no expressions at all.

**Expected behavior**
The expressions should show

**Screenshots**
Expressions are set and live2D is unchecked:
![image](https://github.com/SillyTavern/SillyTavern/assets/13016901/33d51237-9726-4af1-861f-50a49c7148fe)
But live2d is undefined, and thus, that condition is not evaluated correctly:
![image](https://github.com/SillyTavern/SillyTavern/assets/13016901/69aa3b25-5cb4-4a8b-aebc-7ec65cd6deed)
![image](https://github.com/SillyTavern/SillyTavern/assets/13016901/ac4d51c0-d720-4926-9cfb-799bf092e9c1)

**Logs**
There are no errors on the logs

Providing the logs from the browser DevTools console (opened by pressing the F12 key) or SillyTavern command line window will be highly appreciated.

**Desktop (please complete the following information):**
 - OS/Device: Windows 11
 - Environment: local
 - Node.js version (if applicable): v18.16.1
 - Browser: Checked in Chrome, Edge and Firefox
 - Generation API: Oobabooga
 - Branch: release
 - Model: LLaMa2 13b

**Additional context**

**Comment by Cohee1207** [comment]
Thank you, I applied your fix and it worked great. Releasing it now.
