### ISSUE TITLE
[BUG] Prefill causes issues with summarization

### ISSUE THREAD

**Issue by Torel87** [SillyTavern/SillyTavern#917]
> **Warning**. Complete **all** the fields below. Otherwise, your bug report will be **ignored**!

**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
The prefill is sent after the summarization prompt, causing it to generate a normal message in the summary box.

**To Reproduce**
1. Use a prefill
2. Using Main API generate a summary

**Expected behavior**
A clear and concise description of what you expected to happen. I expected the prefill to be sent before the prompt or ignored.

**Screenshots**
https://files.catbox.moe/sbjlas.jpg

**Logs**

Providing the logs from the browser DevTools console (opened by pressing the F12 key) or SillyTavern command line window will be highly appreciated.

**Desktop (please complete the following information):**
 - OS/Device: Android 13
 - Environment: local (termux)
 - Node.js version (if applicable): [run `node --version` in cmd]
 - Browser: Chrome
 - Generation API: Claude
 - Branch: staging
 - Model: Claude-2.0

**Additional context**

**Comment by Cohee1207** [comment]
Ignoring the prefill on generations like summary or SD prompt now.

**Comment by Cohee1207** [comment]
Bugfix released.
