### ISSUE TITLE
[Feature Request] Author's note presets

### ISSUE THREAD

**Issue by Torel87** [SillyTavern/SillyTavern#918]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
Many new claude prompts use Author's Note, but to my knowledge there is no easy way to switch between different notes. There's also no way to keep a default insertion strategy between chats.

**Describe the solution you'd like**
Link Author's Note to presets, add a way to save the injection strategy.

**Describe alternatives you've considered**
Add a separate preset system just for Author's Note. 

**Additional context**
An example of a prompt that uses Author's Note:
https://rentry.co/CharacterProvider

**Comment by ghost** [comment]
Note that you can set the Author's Note via a [slash command](https://docs.sillytavern.app/usage/core-concepts/slashcommands/#slash-commands) `/note <text>`

With the extension 'Quick Reply' you can put different `/note` commands into different quick reply buttons to switch between Author's Notes. This should be equivalent to presets for A/N, as a stop gap measure.

**Comment by Cohee1207** [comment]
Added ability to set default depth/position. Also as @spacegeek69 mentioned, you can use quick replies for quickly setting A/N. Quick replies themselves support presets.
