### ISSUE TITLE
[BUG] Group chat scenario override is broken?

### ISSUE THREAD

**Issue by valden80** [SillyTavern/SillyTavern#919]
**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes. And it's not the previous issue with group chat that I reported, different behavior.

**Describe the bug**
Right now, when I create group chat, add characters and try to set up scenario override it's not saving at all. 

**To Reproduce**
1. Create group chat.
2. Add characters.
3. Click on 'Scenario override', enter some text in opened window.
4. Click 'ok' - text not saved anywhere. If you click 'Scenario override' again - it's empty.

**Expected behavior**
Saving the text entered in the 'Scenario override', and using it for at least current group chat session. (Though logical will be if it's saved for the whole group chat, new sessions too.)

**Screenshots**
Empty window is not informative...

**Logs**
No errors in logs or console, just not saving text.

**Desktop (please complete the following information):**
 - OS/Device: Manjaro Linux
 - Environment: local
 - Node.js: version 20.2.0
 - Browser: Firefox
 - Generation API: Oobaboga
 - Branch: staging
 - Model: any local

**Additional context**
SillyTavern 1.9.7 'staging'(166404d8)

**Comment by Cohee1207** [comment]
Sorry, but I can't reproduce this using your steps.

**Comment by valden80** [comment]
@Cohee1207 
I tested it again. Error is partially browser specific.
On Chromium and Vivaldi scenario override is saved (showed again in edit override pop-up window), on Firefox - no. 
(Also, on Vivaldi character's tab width get to the screen width, hiding all other interface below it, as if on mobile.)

But on all browsers group chat override text do not replace individual greetings of characters in the chat. Even if I manually remove individual character's greetings, it is do not showed in chat. Not on current session, not on new.

Also I tested with default characters - Serafina and Flux the Cat. The same behavior, it's not character specific.

**Comment by Cohee1207** [comment]
Sorry, but I don't get your expected behavior. What do you mean by member greetings? The first message they send on creation of group? That one is not going to get overridden by scenario. Only the "scenario" field from advanced definitions will be affected and replaced by override value.

**Comment by valden80** [comment]
@Cohee1207 
My sorry, I feeling dumb now. Yes, I expected Scenario Override to replace the individual characters greetings (first messages) for the group chat. Sorry.

(In my native language word "scenario" have more wide sense by default, and also has meaning "all setup related to the situation/scene", so greetings is naturally a part of it with this meaning. My bad, sorry.)

Thought this can be a feature ("greeting override"?) - individual first greeting messages may not a have sense in group chat - other situations, and characters should be aware about each others. First message of group chat is good place to setup it...

**Comment by Cohee1207** [comment]
You can delete all group start messages and establish the scene in "/sys" slash command message. It will send a neutral narrator message. Or /sendas to send a message impersonating an AI character

**Comment by valden80** [comment]
Yes I done it this way, so it's not really priority, just possible "quality of life" improvement.

Also, primary issue - not saving data in firefox is fixed now, thanks.
