### ISSUE TITLE
[BUG] Multigen conflicts with "start response with"

### ISSUE THREAD

**Issue by IkariDevGIT** [SillyTavern/SillyTavern#921]
> **Warning**. Complete **all** the fields below. Otherwise, your bug report will be **ignored**!

**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
When you enable both "start response with" and multigen, "start response with" will only appear for the first gen.

**To Reproduce**
1. Enable both "start response with" and Multigen
2. generate response
3. see that "start response with" will only appear for the first gen

**Expected behavior**
"start response with" should be there for any generation

**Desktop (please complete the following information):**
 - OS/Device: Windows 10
 - Environment: local
 - Node.js version (if applicable): v18.15.0
 - Browser: firefox
 - Generation API: ooba/textgen
 - Branch: staging
 - Model: Mythomax

**Comment by Cohee1207** [comment]
Multigen and prompt prefix are problematic when mixed together. It was disabled purposefully.
Unrelated but what are your considerations for using multigen? I consider it an outdated feature worth removing as it is too difficult to support.

**Comment by IkariDevGIT** [comment]
i dont think its really outdated, i use it because it gives way different results than normal generation sometimes, so i personally think its worth keeping

**Comment by Cohee1207** [comment]
Multigen is dead.
