### ISSUE TITLE
[BUG] Smart Context "Last message only" doesn't work anymore (+ related feature request)

### ISSUE THREAD

**Issue by Sekoya78** [SillyTavern/SillyTavern#923]
**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**

Yes, and I found some related to the system at large, but not to this particular problem. Plus, I have a couple suggestions.

**Describe the bug**

Okay, Right now the main bug, using the staging branch from a few days ago (I can't really pin point when it started fucking up, but it's relatively recent, like after you switched your old branches to the new system), is that the checkbox "Query last message only" is non functional. No matter if checked or not, it'll use the whole context. More to the point, and contrary to all other settings, it doesn't even save the checkbox status. It get reset to "unchecked" when you F5 or reload ST.

**To Reproduce**

More or less what I explained before. Load a character with a very long chat history. Check "last message only", generate response. Check what's sent to textgen-webui. Repeat while unchecked, get roughly same result between the two. F5 or reload to verify that the setting ain't being saved at all.

**Expected behavior**

I expect it to work :)

**Screenshots (+ related comments about settings you didn't ask for)**

Here's my settings:
![brave_i1sodCpX6M](https://github.com/SillyTavern/SillyTavern/assets/130620848/b9ea71ed-ba88-4c2a-9cff-cac6598efe02)

This reliably add 5 lines of "memories" at the end of the character/scenario sheets.

Note that there are a metric ton of settings which won't do anything because they are too broad and self contradictory. I'm not sure the before/after AN ever worked either. While I love the power user side of it, I have to admit that most people will be completely lost looking at the menu for this extension, which is a bit sad, because when it works, it works incredibly well, turbo boosting the LLM's capacities. I'd humbly suggest my current settings (or something close enough) as the default instead of the current ones. 

(edit) Oh, I'm also pretty sure that the % strategy doesn't work properly either anymore, at least under some conditions (this thing is incredibly tedious to test when you can't touch the code itself), while it used to before the switch. My previous settings were to keep 95% of the chat, which ended up with roughly the same result as my current setup, but now, it seems like the % detection is borked and it'll post way too many memories. 

The settings for this module should probably be "dumbed down" to make that easier both to debug and for the end user to tweak, I think.

**Logs**

Textgen-webUI logs show what i explained. Silly-Extra doesn't seem to log anything relevant, unless I missed it somehow? End result of the settings is that it adds 5 formatted context lines grabbed from the DB. The issue being that it's not grabbing what the checkbox is asking for.

**Desktop (please complete the following information):**
 - OS/Device: Win11 (natively for everything)
 - Environment: Local
 - Node.js version (if applicable): N/A
 - Browser: Chrome, Brave, Firefox
 - Generation API: Textgen-WebUI (ooba, latest main) 
 - Branch: staging (d18bd20d)
 - Model: Currently on MythoMaxL2 (LLama 2), but same issue everywhere, ofc.

**Additional context**

Speaking of this extension, with 4K context being the norm nowadays (and it's going to grow bigger), it would be incredibly sweet if we could pick something else than just "all context" or just "last post". "All context" worked well enough in 2K, but now, it's practically useless, if not detrimental, while "only last query" is a bit too tight. The ability to use like the X last messages, including the ones from the character, would be a lot more potent.

**Comment by Cohee1207** [comment]
Fixed the checkbox state not saving.
As for the rest of the suggestions, first of all, thanks for putting some thought into it, but unfortunately, I'm not a big fan of ChromaDB as a whole. I heard some people like it, but from the development side, it is very tedious to work with, so I'm not sure I want to invest too much time into it.

**Comment by Sekoya78** [comment]
It's fine, I understand your point of view. 

I've quickly looked at the code before posting the issue, and yeah, it doesn't look like a very friendly system to implement properly (sorta why I suggested to 'dumb down' the settings). If I manage to get over my irrational hate of JS, I will look into it myself, either as a patch or replacement for the module, no promise though.

Just to clarify, when you say "Fixed the checkbox state not saving.", I assume that you mean both the checkbox's state is saved and that the setting itself is functional again, right?  (if so, feel free to close the issue, I'm not in a position to check myself rn)

Again, thanks for your work :)

**Comment by Sekoya78** [comment]
Tested, working. Thank you!
