### ISSUE TITLE
[BUG] Where is Mancer API?

### ISSUE THREAD

**Issue by Teashrock** [SillyTavern/SillyTavern#925]
**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
Update 1.9.5 says Mancer API was added, but it's actually nowhere to be found.

**To Reproduce**
1. Open ST.
2. Open API selection.
3. Try to find Mancer API.
4. See anything but.

**Expected behavior**
Mancer API being available to be selected.

**Screenshots**
![Screenshot_20230812_162015_Chrome](https://github.com/SillyTavern/SillyTavern/assets/12483854/38bc7304-f749-43ee-8314-b8895ed616d6)
![Screenshot_20230812_162118_Chrome](https://github.com/SillyTavern/SillyTavern/assets/12483854/7c91a953-a906-449f-a52c-16252da87886)

**Tablet:**
 - OS/Device: Android 13, Samsung Galaxy Tab S6 Lite
 - Environment: local
 - Node.js version: v19.9.0
 - Browser: Chrome
 - Generation API: Mancer (would be if it were present)
 - Branch: release, 1.9.7
 - Model: None

**Comment by Cohee1207** [comment]
It is under oobabooga's option
Probably should update that option label to reflect it

**Comment by Teashrock** [comment]
@Cohee1207 
Aah, understand. And, yes, it should be updated so users can find it.

**Comment by Cohee1207** [comment]
Added.
