### ISSUE TITLE
[Feature Request] Can silly tavern support rwkv runner?

### ISSUE THREAD

**Issue by KaJ1L** [SillyTavern/SillyTavern#926]
I was able to support rwkv runner using risuai. But the same method fails in silly tavern. Can silly tavern support rwkv runner?

**Comment by Cohee1207** [comment]
Can you please elaborate on what is a rwkv runner and how it affects being able to run SillyTavern? 
I see from their GitHub that it provides an OpenAI-compatible endpoint, so you should use Chat Completions provider in OpenAI source with the reverse proxy URL set. Have you tried that?

**Comment by Sekoya78** [comment]
I thought I'd help a bit here. RWKV is a specific kind of LLM using a [different system](https://github.com/BlinkDL/RWKV-LM) than the usual. From a scientific perspective, it's a fascinating kind of LLM. From an user POV, it's very sub-par outside of very specific tasks (and having variants for other languages). 

In any case, it's handled by Textgen-webUI (with very specific settings which are detailed in their [documentation](https://github.com/oobabooga/text-generation-webui/blob/main/docs/RWKV-model.md)). Assuming it's loaded correctly in this environment, there's nothing more you can do here.

(in short, I think the OP didn't get that ST is just a front-end)

**Comment by KaJ1L** [comment]
> Can you please elaborate on what is a rwkv runner and how it affects being able to run SillyTavern? I see from their GitHub that it provides an OpenAI-compatible endpoint, so you should use Chat Completions provider in OpenAI source with the reverse proxy URL set. Have you tried that?

OK，I find a fork is "https://github.com/xiaol/SillyTavern-RWKV". it can work.

**Comment by Cohee1207** [comment]
I can't support you with forks, but if it works for you, it's good.

**Comment by Whale-Splas** [comment]
> Can you please elaborate on what is a rwkv runner and how it affects being able to run SillyTavern? I see from their GitHub that it provides an OpenAI-compatible endpoint, so you should use Chat Completions provider in OpenAI source with the reverse proxy URL set. Have you tried that?

I tried,but failed,problem is that the request will have a mysterious double slash like "POST //chat/completions HTTP/1.1",not"POST /chat/completions HTTP/1.1",which makes a 404 error

**Comment by Whale-Splas** [comment]
> > Can you please elaborate on what is a rwkv runner and how it affects being able to run SillyTavern? I see from their GitHub that it provides an OpenAI-compatible endpoint, so you should use Chat Completions provider in OpenAI source with the reverse proxy URL set. Have you tried that?
> 
> I tried,but failed,problem is that the request will have a mysterious double slash like "POST //chat/completions HTTP/1.1",not"POST /chat/completions HTTP/1.1",which makes a 404 error

By just deleting the extra slash at line 3306 of the server.js its working now
