### ISSUE TITLE
[Feature Request] Ability to link a LLM name to a specific instruct preset

### ISSUE THREAD

**Issue by Sekoya78** [SillyTavern/SillyTavern#927]
(sorry, it's me again)

**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**

I did, didn't find anything relevant, but I might have missed it, it's a bit hit and miss to reliably look for. 

**Is your feature request related to a problem? Please describe.**

I test and evaluate LLMs for a future project of mine. I spend an embarrassing amount of time switching between various models to evaluate them, and, as you know, each LLM use a slightly different Instruct format (the usefulness of the formatting itself is debatable, even more so when people are ignoring L2's native instruct model because they are too lazy to edit their database to feed into what's already there, but I digress). At some point, it gets very tedious to manually switch between formats, and it's prone to human error.

**Describe the solution you'd like**

Option 1 (user friendly but annoying):
- Assume having a new config file formatted with a list of "model-name: [model_name]; instruct: [/public/instruct/associated_preset_file]"
- When a model is loaded, check file, and if the model file is in the list, set the instruct preset accordingly (just that, no need to forcefully tweak the enable/disable instruct setting)
- Add a menu to allow the user to link a model to an instruct preset and save into that file. (optional)

Option 2 (fire & forget):

Alternatively, assuming there's a public/instruct/ file with the exact same filename as the model being loaded, automatically load that one. It's a lot easier to code and maintain (and there's no need to add more menus to the UI). 

**Describe alternatives you've considered**

Doing it manually and going crazy because I forgot what specific stupid format was suggested by a particular L2 variant. ;)

**Additional context**

I do understand the overwhelming majority of your user base doesn't switch model regularly and that you may not want to waste time on this feature. Again, that's fine by me.

**Comment by ghost** [comment]
I think I may have suggested something like this a while back, but this is really a feature I'd like to see for similar reasons as OP. Firing up a different model in the loader is super easy, but switching between all the various settings and instruct styles is such a hassle. Just this one change makes it so much less annoying.

**Comment by Cohee1207** [comment]
This is done in staging via assigning activation regex to preset names

**Comment by Cohee1207** [comment]
Released to stable.
