### ISSUE TITLE
[Feature Request] Missing generation settings from NAI

### ISSUE THREAD

**Issue by TheZennou** [SillyTavern/SillyTavern#928]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

There are a small list of different settings from NAI that massively affect how good a model like Kayra can perform, especially in chat. If these are not available on the API, please inform me so I stop begging.

**Describe the solution you'd like**
For these to be added, I don't expect it to be done quickly, as I know NAI just loves dropping massive walls of new features all at once. 
Listed in order of how important I feel they are to wrangling Kayra.
~~-Manual Model Switching~~ done!
~~-Phrase Bias~~ Done!
~~-CFG Opposing Prompt~~ done!
~~-Banned Tokens~~ Done!
~~-Top G~~ done!
~~-Mirostat~~ done!

**Describe alternatives you've considered**
don't add them I guess? uhh that would suck though.

**Comment by Cohee1207** [comment]
CFG Opposing Prompt was added today.
The rest are going to be painful, but I hope to add them eventually.

**Comment by Cohee1207** [comment]
Banned Tokens - done

**Comment by Cohee1207** [comment]
Phrase Bias - done
