### ISSUE TITLE
ChromaDB needless database rebuilds

### ISSUE THREAD

**Issue by ghost** [SillyTavern/SillyTavern#929]
**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
ChromaDB rebuilds the entire database for each new client connecting to the SillyTavern server, even though the database is stored on the server itself. It takes very long to do that on longer chats.

**To Reproduce**
1. Access the SillyTavern web interface through the local network from a new client.
2. Open any longer Chat that was created from a different client.
3. Regenerate the last message or write a new one.

**Expected behavior**
SillyTavern should just use the existing chromaDB to generate the next message from any new client, as the client is only sending the instructions through the web interface, and both the SillyTavern and chromaDB server are not running on the client itself.

**Desktop (please complete the following information):**
 - OS/Device: Multi Device, Linux Server, Windows/Android/Linux Clients.
 - Environment: Local
 - Generation API Any
 - Branch: Release
 - Model: Any

**Comment by Cohee1207** [comment]
Chat synchronization state is stored in IndexedDB on the client side. So different clients would need to keep a synchronization state on their own.
