### ISSUE TITLE
[BUG] Negative prompt always empty (Oobaboga backend)

### ISSUE THREAD

**Issue by valden80** [SillyTavern/SillyTavern#933]
**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
Maybe I reporting too early and this feature not finished, but right now Negative Promt in the console of the ST always empty. From the log:
```
  early_stopping: false,
  guidance_scale: 1,
  negative_prompt: '',
  seed: -1,
  add_bos_token: true,
  stopping_strings: [ '\nAuthor:', '\n### Response: ' ],
  truncation_length: 4096,
```

**To Reproduce**
1. Add some negative prompt in CFG.
2. Send.
3. See console output.

**Expected behavior**
Negative prompt in  `negative_prompt: '',` string.

**Screenshots**
None.

**Logs**
No error in logs, console output above.

**Desktop (please complete the following information):**
 - OS/Device: Manjaro Linux
 - Environment: local
 - Node.js: version 20.2.0
 - Browser: Firefox
 - Generation API: **Oobaboga**, last - updated right now.
 - Branch: staging
 - Model: any local

**Additional context**
none

**Comment by Cohee1207** [comment]
What is the guidance value you set? For negative prompt to work it needs to be not equal to 1. Probably needs to be specified in the UI

**Comment by valden80** [comment]
Yes this is the case. It's been set to 1.0

**Comment by valden80** [comment]
Yes it been set to 1.0.
But now another problem, after I set it to 1.1 generation completely broken with error:
```
Traceback (most recent call last):
  File "/home/AI/Oobabooga/text-generation-webui/modules/text_generation.py", line 344, in generate_reply_custom
    for reply in shared.model.generate_with_streaming(question, state):
  File "/home/AI/Oobabooga/text-generation-webui/modules/exllama.py", line 92, in generate_with_streaming
    if self.cache.batch_size == 1:
AttributeError: 'ExllamaModel' object has no attribute 'cache'
```
This is from Ooba's console, so it's should be reported to Ooba's github, right?

**Comment by Cohee1207** [comment]
First try to update ooba with reinstalling requirements (just git pull for ooba may not always work). If that doesn't help - report it to ooba. In any case doesn't look like ST issue

**Comment by valden80** [comment]
Yes, it's throw error even with generation is Ooba's UI directly, if I set negative in it...

**Comment by Cohee1207** [comment]
Added own CFG settings to oobabooga if you don't want to use a separate menu or overrides. Also specified that 1 == disabled.
As for the issue, reopen if you find any problems with ST itself.
