### ISSUE TITLE
[Feature Request] Generating background on the fly

### ISSUE THREAD

**Issue by Woisek** [SillyTavern/SillyTavern#937]
With the possibility to use Stable Diffusion in ST it would also be nice if we had some possibility to generate backgrounds on the fly that then is set automatically as a full background..
I can imagine either a button or a / command for this.

Like:
Press button/enter / command -> prompt typing: "image of a dark alleyway in the night, moon, lit street lamps, .." -> generate -> fade in as full background.

Would be awesome. 🙂

**Comment by Cohee1207** [comment]
Can do eventually. Just needs some thought on prompts and BG saving (may it be saved to chat metadata or not).

**Comment by Woisek** [comment]
Regarding saving, I can imagine either a direct save to public/backgrounds folder for later use in other scenarios or saved as a chat linked file, maybe in a new folder, i.e. public/chat backgrounds, only for this specific chat.

**Comment by Cohee1207** [comment]
Added `/sd background` mode.
It will generate an image and set it as a chat background (and also shows it in chat).

**Comment by Woisek** [comment]
@Cohee1207 Can we edit the prompt that is used for the generation? 🤔

**Comment by Cohee1207** [comment]
Yes, you can edit all the prompts. Check out the extension settings, "SD Prompt Templates" section

**Comment by Woisek** [comment]
Please forgive me my dumb question, but when is it active? The last update was 3 days ago and I see this section not in the SD prompts templates part.
And before I even know how it works, your answer suggest, that we have to set up a (fixed) template for the background?
Not like:
/sd background "an image of an dark alleyway at night, lit street lamps, moonshine, rain, ..." ? 🤔
Sorry again for my confusion. 😐

**Comment by Cohee1207** [comment]
It is in the staging branch for now. And it works similarly to other modes - lets AI generate a prompt.
![image](https://github.com/SillyTavern/SillyTavern/assets/18619528/73ce003a-d78f-43f2-b844-d9a27b3aa352)

**Comment by Woisek** [comment]
Ah, staging, okay ...
So, we don't have full control over a defined selfmade prompt like the brush icon ... again?! 😐

**Comment by Cohee1207** [comment]
Released to stable.

**Comment by Woisek** [comment]
Now that this feature is in main implemented ... I noticed, it's not working as I had hoped.
It generates an image, yes, but it's not set as a background in the browser. What do I miss here? 🤔

**Comment by Cohee1207** [comment]
For me, it works exactly like you'd describe.
![image](https://github.com/SillyTavern/SillyTavern/assets/18619528/eb22a47c-cfa9-416f-b12c-fc78eeaaec18)

**Comment by Woisek** [comment]
That's strange ... 🤔 Did you defined another folder where the images are saved so I can see?
On my end, it generates the image but it's not displayed in the browser like in you screenshot. Do we have to set something special in the change background tab?

**Comment by Cohee1207** [comment]
No, I don't. The generated images are now saved to /public/user/images
Previously they were base64'd into the chat file (slow and ugly approach)

**Comment by Woisek** [comment]
Okay, I can see the generated images in this folder. But that doesn't explain why they are not displayed.
![Zwischenablagebild](https://github.com/SillyTavern/SillyTavern/assets/122026301/453a8620-9315-478e-9792-449cd7b7f6f9)

And there, where I think should be the background inserted, is nothing:
![Zwischenablagebild (2)](https://github.com/SillyTavern/SillyTavern/assets/122026301/2f8c06b7-90a1-447f-9450-b918c021a95c)

Any suggestions? 🤔

**Comment by Cohee1207** [comment]
Hmm, make sure you have the default "Chat Backgrounds" extension enabled. Setting SD gens to a chat BG was built upon it.

**Comment by Woisek** [comment]
They are ...
![Zwischenablagebild (3)](https://github.com/SillyTavern/SillyTavern/assets/122026301/f65a9f64-f18a-4ba4-92fe-e2dca63a62cf)

**Comment by Woisek** [comment]
Anything new on this? 🤔 I noticed, that on the release branch it also doesn't work for me. 😥

**Comment by Cohee1207** [comment]
Could not repro. No idea why it happens for you only.

**Comment by Woisek** [comment]
The only observation I can add is, when I manually add the background, it will be overwritten by 'none' after 1 or 2 seconds. So I suppose there is a script checking and editing the background property.
Maybe this helps to search for the cause. 🤔

**Comment by Cohee1207** [comment]
Does this happen for all chats, old chats, or new only? Do you have the ability to test in other browsers or on a fresh install?

**Comment by Woisek** [comment]
It happens to all chats as far as I have tested. I don't have currently another browser installed, but I use a dedicated profile on FF with only 3 ad related extensions, otherwise "pure" and only for Stable Diffusion and Text Generation.

**Comment by Cohee1207** [comment]
I tried it on Firefox 3 days ago and it was fine.

**Comment by Woisek** [comment]
What version is your FF?

Edit: I tried in Opera latest and it's the same. The background is not set. 😔

Update: After direct communication with @Cohee1207 this is now working as intended. Thanks again. 👍
