### ISSUE TITLE
[Feature Request] Add used model to chat log

### ISSUE THREAD

**Issue by Woisek** [SillyTavern/SillyTavern#942]
A simple one, in the title.
Is it possible, to have the model used for chatting, somehow noted in the chat log, txt and json?
It would help to compare what model gave more/better responses on what character used. 🙂

**Comment by Cohee1207** [comment]
Enable timestamps in user settings and hover a mouse over it.
We really didn't find any other place to display this info, so it's well hidden. But it is being recorded for quite some time already.

**Comment by Woisek** [comment]
Thanks for the info but ... I don't find it? 🤔
I had timestamps enabled (Chat Timestamps) but where to hover? Hovering over the panels in the 'View past chats' don't show me anything about what model was used for the chat.
What do I miss here? 🤔
And yes, I can see the model saved in the jsonl <- ? file at the end of the file, thanks.

**Comment by NeoTU** [comment]
> Enable timestamps in user settings and hover a mouse over it. We really didn't find any other place to display this info, so it's well hidden. But it is being recorded for quite some time already.

I'm using mythomax-l2-13b in koboldcpp yet this what hovering over the time stamp shows and in saved jsonl file.

![Untitled](https://github.com/SillyTavern/SillyTavern/assets/11801357/f0f47253-faec-496b-9229-da999ddba8b3)

![Untitled 2](https://github.com/SillyTavern/SillyTavern/assets/11801357/5d639776-3cb0-4f5f-a7ef-7ed0f9cf4cac)

Can it show (e.g mythomax-l2-13b) and not "concedo/koboldcpp" which is not helpful for when I forget which models was used.

**Comment by Woisek** [comment]
When I hover over this part, nothing shows up. 😕
This element has no tool tip or such.

**Comment by Cohee1207** [comment]
It should look like this (assume my mouse cursor is above the timestamp)
<img width="385" alt="image" src="https://github.com/SillyTavern/SillyTavern/assets/18619528/37b7ea38-abd5-4d86-8ba2-1a548f78fe0b">

**Comment by Woisek** [comment]
@Cohee1207 Okay, in the chat I see the tool tip with the model name.
So ... what does that mean now? 🤔

**Comment by Cohee1207** [comment]
Since you can see the model used to generate the message, it looks like your request is already implemented.
But you're free to disagree if I misunderstood this entirely.

**Comment by Woisek** [comment]
> Since you can see the model used to generate the message, it looks like your request is already implemented.

Yes, thanks on that. But I meant, why can I see it in the chat but not on the chat panels where it (also) supposed to be?

**Comment by Cohee1207** [comment]
Could you mock-up how you imagine it exactly?

**Comment by Woisek** [comment]
Uhm ... okay, it seems there is some misunderstanding going on here. When you wrote 'Enable timestamps in user settings and hover a mouse over it.' then you were referring to the chat itself ... ?

**Comment by Cohee1207** [comment]
Enabling timestamps is a setting that affects chats. It also allows the viewing model used by hovering over a timestamp. That's what I meant.

**Comment by Woisek** [comment]
Okay. And I thought it's the panels seen when opening "View past chats". But maybe you could incorporate that info there, too? 🤔 Or is it not useful because models could be changed mid chat?

**Comment by Cohee1207** [comment]
Yes, showing it just for the last message won't be very useful. Ofc it is possible to aggregate the data, but I'm not sure.
