### ISSUE TITLE
[Feature Request] Group chat Worlds/Lorebooks

### ISSUE THREAD

**Issue by toby3d** [SillyTavern/SillyTavern#943]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
Worlds/Lorebooks can be enabled individually for specific characters and globally for all chats via the appropriate menu. But I haven't found a way to include world information for group chats. It would be great to be able to include one or more worlds and Lorebooks for group chat as with a group scenario that overrides character scenarios.

**Describe the solution you'd like**
Same or similar mechanisms for adding lore for group chat as in individual character settings. Perhaps with a parameter that would indicate how group lore affects members lore: overwrite completely or include as additional.

**Describe alternatives you've considered**
Adding lore as a script or Authors Note is quite expensive for the token budget, as all items are included in the prompt permanently rather than contextually through the use of keywords/tags.

**Additional context**
I'm not sure if individual character lore is used in groups, from my tests it looks like it is, but this mechanism is opaque. Plus there are situations where lore may be useless for characters individually and only make sense in groups. Plus, reassigning lore for group chats with large numbers of participants can be quite painful and a group option would be handy here.

**Comment by Cohee1207** [comment]
World Info bound to specific chat can be considered. Not only for groups, but maybe individuals as well.

**Comment by valden80** [comment]
I humbly leaving here notice to the this request, as it about very similar feature and maybe can be done together: https://github.com/SillyTavern/SillyTavern/issues/893

**Comment by Cohee1207** [comment]
Implemented by chat-bound lorebooks.
