### ISSUE TITLE
[Feature Request] (v1.3.9+) - Nesting world info would be handy.

### ISSUE THREAD

**Issue by SabinStargem** [SillyTavern/SillyTavern#945]
I have been making world info to create a setting.  Unfortunately, this clutters up the WI interface, because I have been placing my info into categories.  It looks something like this right now.

![image](https://github.com/SillyTavern/SillyTavern/assets/38871546/42d468e4-ce7e-4406-ade7-e21b4346bff0)

I think it would less clunky if these categories could be nested into an expandable/collapsible structure.  Something like:

EROBIA

->Locations
--->Styoja Leir
------> Shrine of Origin
------> Meadhouse of Champions
------> Hunter's Woods
---------> Pristine Waterfall
-------------> Hidden Cave
---------> Corrupted Clearing
-------------> Fell Tomb
----------------> Sepulcher of Hrungnir

--->Bluehaven
------> Chuch of Tyria, Bluehaven Chapter
---------> Confessional Booth
---------> Nadia's bedroom
---------> Kitchen
---------> Chapel
--------------> Alter
-------------------->  Hidden Chamber

->Setting
-----> Humanity
--------> Demifolk
------------> Dwarves
--------> Monsterfolk
------------> Arachne
------------> Lamia

...And so on.  This would allow me to package my world info into a single container for distribution, while keeping things easy for toggling or editing individual parts.

**Comment by stho90** [comment]
Maybe related to #1227 ?
Or is this just a change of the GUI ?
