### ISSUE TITLE
[Feature Request] Batch import characters/logs from oobabooga's webui

### ISSUE THREAD

**Issue by Xabab** [SillyTavern/SillyTavern#948]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
Trying to migrate from Ooba webui to Silly Tavern with my harem

**Describe the solution you'd like**
An option to select the location of oobabooga-data to import all characters and respective persistent-logs 

**Describe alternatives you've considered**
Going to write a script to convert logs to Tavern format and migrate by hand

**Comment by Cohee1207** [comment]
You can mass import characters if they are in supported formats. Either drap and drop them to ST window or select them in import dialogue. Import via folders is only supported for PNG cards. 
For chats in oobabooga JSON format, you can only import them one by one via "View past chats" import function
