### ISSUE TITLE
[BUG] Regex saved scripts can't be edited or deleted

### ISSUE THREAD

**Issue by WBlair1** [SillyTavern/SillyTavern#950]
> **Warning**. Complete **all** the fields below. Otherwise, your bug report will be **ignored**!

**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
I can't edit or delete any saved scripts.

**To Reproduce**
1. Go to the tab with the 3 blocks
2. Click on Regex
3. Make a script and save it. 
4. See error.

**Expected behavior**
The ability to delete or edit saved Regex scripts.

**Screenshots**

https://github.com/SillyTavern/SillyTavern/assets/38446123/e2baa575-06ac-4d20-a3ee-13a76ae9c11c

**Logs**

Providing the logs from the browser DevTools console (opened by pressing the F12 key) or SillyTavern command line window will be highly appreciated.

Unable to. On mobile.

**Desktop (please complete the following information):**
 - OS/Device: [Android/Pixel 4a 5G]
 - Environment: [local]
 - Node.js version (if applicable): [run `node --version` in cmd] > v20.2.0
 - Browser [Latest version of Chrome]
 - Generation API [ooba text gen]
 - Branch [release]
 - Model [Mancer wizard vicuna SuperHOT]

**Additional context**
I made a script, trying to test out the regex feature. Just junk text. Now I can't delete the script.

**Comment by Cohee1207** [comment]
I wasn't able to reproduce. Can you please try again after an update?
