### ISSUE TITLE
[Feature Request] Integrate Writing Assistant and AI Dungeon-Like Features for an Ultimate LLM Playground Experience

### ISSUE THREAD

**Issue by imakesound** [SillyTavern/SillyTavern#960]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
Not necessarily a problem, but I see a potential for SillyTavern to become a comprehensive playground for language models. Currently, there are tools like NovelAI and AiDungeon that offer certain functionalities, but it would be great to have everything consolidated into SillyTavern.

**Describe the solution you'd like**
I propose adding a writing assistant feature similar to the one in NovelAI where a user can write a few sentences and the LLM will continue writing for them. This feature can be accessed through a dedicated tab in the UI. In addition, I suggest adding an AI Dungeon-like experience where users can download and play through worlds and scenarios created by others. This feature can also have its own tab in the UI.

**Describe alternatives you've considered**
I have considered using separate tools like koboldai and text gen web ui for writing assistance as they already have a similar feature built in, i have not found a local alternative to aidungeon although i believe it would be possible with character cards i just feel that the experience could be a little more polished. However, it would be more convenient and user-friendly to have all these features consolidated within SillyTavern, which I'm already excited about.

**Additional context**
SillyTavern has the potential to be the ultimate LLM playground and tool, and I think these features would help make that a reality. With the already growing user base and interest, having these features would further solidify its position as a premier destination for LLM enthusiasts and creators. im just really excited about SillyTavern and all its potential.

**Comment by MaterialMiko** [comment]
I would like to add, regarding dungeon-like experiences: Having a tool that ensures the AI will strictly follow a suggested template, would be highly useful. Keeping track of HP, stats, status effect, time, floor depth, and other variables. Like, randomly generated names and fictive attributes (country, type of weapon used and description of the weapon, or anything more creative and verbal) would be very important for dungeon-like experiences.

A template to make orders such as "At the end every reply, follow this given template: ```{{char}}'s thoughts: {description of their thoughts and reactions to the environment around them}```
would be very useful for a very wide variety of cards, and help balance/overcome the limitations of some models who struggle with instructions such as "only one reply, do not speak for user, always follow the following syntax: descriptions wrapped in asterisks, spoken dialogue wrapped in quotes" and the likes.

Edit: As for the issue with current LLM struggling with math: Would it be possible to integrate a simple calculator tool that can define variables like "number of HP", conditions (time passing if this or that action is chosen), and handle the math side for the LLM so it can simply use the variables? I have no idea how complex or realistic using a form of calculator tool external to the LLM to handle variables sometimes, could be.

**Comment by Cohee1207** [comment]
Pretty much everything you describe is already possible and being practiced by other users. It is possible to create a narrator/scenario card that would track your stats. I see no reason to set it on some kind of guardrails, not every model can precisely follow patterns.
