### ISSUE TITLE
[BUG] Typing is missing letters when editing the WI

### ISSUE THREAD

**Issue by valden80** [SillyTavern/SillyTavern#964]
**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes.

**Describe the bug**
There is slightly hard to describe it clear but I will try:
When I editing WI, when I typing on keyboard some letters randomly don't reach the field. It's just gulp them without any other effects, as if keyboard is broken with half-working keys.
But this effect present ONLY in the WI editing, and no where else so far. I'm completely sure that it's NOT the hardware problem with keyboard.

**To Reproduce**
1. Start editing WI
2. Experience effect.

**Expected behavior**
No missing letter when typing on keyboard.

**Screenshots**
I don't know what to add - there is no errors or anything. Even on screenshots it can't be shown. Video? Not sure, but if you insist...

**Logs**
None.

**Desktop (please complete the following information):**
 - OS/Device: Manjaro Linux
 - Environment: local
 - Node.js: version 20.2.0
 - Browser: Firefox
 - Generation API: Oobaboga
 - Branch: staging
 - Model: any

**Additional context**
This is start happening only for 2-3 days (today is counting) and for first I think that it's something with my keyboard. But then seen regularity in it - only on WI edit, not in the chat or outside of ST.
Maybe this is browser specific, I do not tested it with other browsers. 
Also I think, that I seen the small freezes now as reaction on all typing in the WI textfields. It's subjective, but for me it's felt like something being done on every typing there. Some sort of input checking or something.

**Comment by Cohee1207** [comment]
How big is your WI file? Do you experience any UI lags when loading it and not editing it?

**Comment by valden80** [comment]
This issue existing on any WI file, even empty, newly created, and starting the first record.

Also, I already have many WI files - like 20-30 or so. From them I have 3-4 active as the global WI always. And more - usually I have additional 1-3 tied to the character. 
In summary they can have up to 30-40 WI records together, though no more then 50-100 tokens each.

Also, it's looking like there is bigger chance to gulp letter when I typing more slowly and with irregular intervals. 

When I only load WI file (select it in the WI editor) I don't see any significant lags, no matter the records count in the file.

**Comment by Cohee1207** [comment]
I wasn't able to reproduce this bug in any of the browsers, but for performance's sake, I'm starting to work on pagination for WI entries as we did for characters and group members previously on staging. Maybe that would help you.

**Comment by valden80** [comment]
Not been here for 2 days, updated today, and it's looks like issue is gone now.

**Comment by Cohee1207** [comment]
Nice. Let me know if persists. As a bonus, you can now search for entries in the WI book.
