### ISSUE TITLE
[Feature Request] Swipe/regenerate to "continue" feature

### ISSUE THREAD

**Issue by equivalentx** [SillyTavern/SillyTavern#973]
can you please add swipe/regenerate option for this "continue" feature? i know it has to regenerate only part of the message instead of all of it so i'd be harder to implement than normal swipes but i'd be nice if you could do that. when you don't like the response it's not very convenient to edit message - remove new part - press ok - press "continue" again.
![image](https://github.com/SillyTavern/SillyTavern/assets/127750474/e07f6ca0-b497-4451-81f3-afd3a197a585)

**Comment by aetherwu** [comment]
Sounds like a good idea to ‘Swipe to continue' than to 'Generate it again.' 
It feels like 'Swipe page to continue reading'.

**Comment by Cohee1207** [comment]
Use this extension: https://github.com/LenAnderson/SillyTavern-MoreFlexibleContinues/
