### ISSUE TITLE
[BUG] Elevenlabs TTS error "API key is invalid"

### ISSUE THREAD

**Issue by DontDeleteTim** [SillyTavern/SillyTavern#988]
> **Warning**. Complete **all** the fields below. Otherwise, your bug report will be **ignored**!

**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes, as far as I can find, extensively

**Describe the bug**
When i try to use ElevenLabs TTS with extensions properly set up, I get an error as though my API key is invalid.

**To Reproduce**
1. Have extensions running locally via conda
2. Run ST, launch in CHROME
3. Set TTS to ElevenLabs
4. (Any checkbox setting, reproduced with every combo - yes)
5. Paste API key from EL/11L and have something like "Seraphina:Bella,You:Dave" in VoiceMap or it'll just throw invalid voicemap error
6. >Apply
7. TypeError: Cannot set properties of undefined (setting 'apiKey')
7b. In Chrome and Opera, it's the above. In Firefox, it's "TypeError: this.settings is undefined."

**Expected behavior**
Setting should run successfully, resulting in TTS service running.

**Screenshots**

**Logs**
TypeError: this.settings is undefined
    updateApiKey http://127.0.0.1:8000/scripts/extensions/tts/elevenlabs.js:82
    onApplyClick http://127.0.0.1:8000/scripts/extensions/tts/elevenlabs.js:74
    onApplyClick http://127.0.0.1:8000/scripts/extensions/tts/index.js:549
    jQuery 2
[index.js:557:17](http://127.0.0.1:8000/scripts/extensions/tts/index.js)
    onApplyClick http://127.0.0.1:8000/scripts/extensions/tts/index.js:557

Providing the logs from the browser DevTools console (opened by pressing the F12 key) or SillyTavern command line window will be highly appreciated.

**Desktop (please complete the following information):**
 - OS/Device: Windows 10
 - Environment: local
 - Node.js version (if applicable): v18.17.1
 - Browser: Chrome, Firefox, Opera
 - Generation API: OpenRouter
 - Branch: release
 - Model: gryphe/mythopmax-L2-13B

**Additional context**
I've tried 3 different API keys.
I've tried several different voices, but chose those defaults in case it matters based on 11L's own list of voices available as searchable in the API.
Probably unrelated, but no TTS works for me in Chrome. Have gotten Edge to work in Firefox.
I've reinstalled Conda 2-3x, as well as almost all of the extensions, and done the fix with ChromaDB to get it installed properly.

**Comment by Cohee1207** [comment]
I wasn't able to reproduce it on Chrome or Firefox, but I put an experimental fix to the release branch, covering some places that could be causing this. Pull the latest commit and try again, please. If that would not help - you could reset your TTS extension settings by opening the public/settings.json file with a text editor and removing the section for ElevenLabs from it, then saving and reloading the page. See below:


        "tts": {
            "voiceMap": "",
            "ttsEnabled": false,
            "currentProvider": "ElevenLabs",
            "auto_generation": true,
            // ** REMOVE THE OBJECT BELOW THIS LINE **
            "ElevenLabs": {
                "stability": "0.75",
                "similarity_boost": "0.75",
                "apiKey": "X-KEY-HERE",
                "multilingual": false,
                "voiceMap": "Blaze Fielding:Mimi"
            },
            // ** STOP HERE **
            "System": {},
            "enabled": true
        },

**Comment by DontDeleteTim** [comment]
Incidentally, I moved to a new PC and did a clean install of Python etc and all ST-related things (I didn't move any profiles or anything over from the old drive). This was also a Windows 10 to 11 move.

I've yet to run into the bug I reported myself again on this device, and I am unable to use the old device at the moment.

I have a feeling, judging by the command prompt logs, it was an issue with the Python install or the overall setup, and probably didn't come down to one file -- really a one-off case.

That said, please allow me the next few days (through the weekend) when I have more time to see if I run into it again while this item is still open, and so I can respond to your fix or conclude it was a one-off user system issue that theoretically can be resolved with clean installs.

**Comment by jasonmansfield86** [comment]
In my case, the issue was that I didn't see that there was a "Connect" button hiding in the configuration UI, just below the API Key and Model inputs.

You have to click this at least once in order for the API key to actually be saved, otherwise SillyTavern will keep sending your requests without the API key included, thus generating these errors.
