### ISSUE TITLE
[BUG] Start New Chat Issue

### ISSUE THREAD

**Issue by Th2316** [SillyTavern/SillyTavern#989]
Hi, i'm using SillyTavern on android with termux. Everytime i'm using start new chat option with a character when the page was refreshed my old chat always reappear. How that is possible? There is a fix for this? Thanks.

**Comment by Cohee1207** [comment]
Please fill out the bug report template: https://github.com/SillyTavern/SillyTavern/blob/release/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by Cohee1207** [comment]
Fixed in staging. https://github.com/SillyTavern/SillyTavern/commit/d64c5880c819e8947062591c88af84e009dfc9b5
