### ISSUE TITLE
[Feature Request]  Analyse user preferences

### ISSUE THREAD

**Issue by Torel87** [SillyTavern/SillyTavern#990]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
Sort of. I have over 1000 saved characters, too many to actually try them all. I've seen other users complain about similar issues.

**Describe the solution you'd like**
A feature that analyses the user's most chatted bots and suggests others that might match their preferences. I imagine it would use the main API just like summarization.

**Comment by Cohee1207** [comment]
I'm not sure it is something that we should change in the scope of the app if it's just a bad user habit to hoard characters they are never going to play with (if it's not a performance concern, which has been greatly improved lately). You can try using the "Advanced character search" function to filter characters by vague terms like "Fantasy" or "Fighter".

**Comment by Namakamoto** [comment]
How about a sort of archive folder accessible from the site alternatively, to keep the unused characters on disc but not loaded in the Character Manager (That said I think the character pages did a lot in that regard)
