### ISSUE TITLE
[Feature Request] An option to toggle off or increase the interval of "Horde request timed out"

### ISSUE THREAD

**Issue by Teashrock** [SillyTavern/SillyTavern#991]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
With Poe moving away from ST, many people moved away to KoboldAI or KoboldAI Horde. Both are able to be used from ST directly. But there's an issue: when the queue is too long (and you're not using any kudos), ST decides that the AI chosen is unreachable, thus dropping the connection with "Horde request timed out" message. The truth is the AI chosen **_is_** actually reachable, just taking too long to generate (5 minutes, 10 minutes, but they still generate). So the only way now to avoid getting "Horde request time out" is to connect your Horde API key with many kudos on it, then it will manage to pass the queue and generate a response **_in time_** before ST drops the connection. So it just means ST implicitly forces users to spend kudos if they want to get any resonse with highly-queued models, when on koboldai.net "Horde request timed out" is absent, and everything works fine there.

**Describe the solution you'd like**
May you please add an option to enable/disable the time out or at leastvjust extend the amount of time ST should wait before disconnecting? It would be very convenient for anyone using anonymous mode or just not having any kudos.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Cohee1207** [comment]
The default timeout increased to almost 17 minutes.

**Comment by Teashrock** [comment]
@Cohee1207 
For everyone reading: here's an alternative solution for this:
1. Make a backup of the existing SillyTavern instance into the one with whatever name (for example, ST-ForTheHorde).
1.
```Bash
cd ST-ForTheHorde
vim public/scripts/horde.js
```
2. Find the line saying "const MAX_RETRIES = 100;".
3. Change it to "const MAX_RETRIES = 65535;".
4. Save the file.
5. Start ST-ForTheHorde version of SillyTavern.
6. Enjoy the anonymous ride on KoboldAI Horde.

**Comment by Teashrock** [comment]
Didn't have any problems with this anymore, even without my hack above. Closing as unable to reproduce anymore.

**Comment by Cohee1207** [comment]
By the way, the max timeout is 20 minutes in Horde, there's no reason to increase it further as older unfulfilled requests get killed by the Horde.

**Comment by Teashrock** [comment]
@Cohee1207 
Ah, didn't know this. It means the above hack was garbage from the start, lol.
