### ISSUE TITLE
[Feature Request] window overlapping

### ISSUE THREAD

**Issue by equivalentx** [SillyTavern/SillyTavern#995]
so ai response configuration window where you set main prompt, preset etc opens to the left side, as well as author's notes. usually i keep configuration window always open while author's notes only sometimes, but they overlay on the left side with notes being behind. so can you either make notes appear above configuration window, or make the latest opened on top, like browser windows or something.

**Comment by Cohee1207** [comment]
You can enable movable UI and move the notes window wherever you like. As well as reduce the height of AI configuration and make it even with the notes
