### ISSUE TITLE
[Feature Request] Dialogue blip-like talking

### ISSUE THREAD

**Issue by IkariDevGIT** [SillyTavern/SillyTavern#998]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
I like the tts, but it just seems off somehow. It also requires money and enough computing power. It also seems kinda "fabricated", while the "Dialogue blip" style voice seems like a good visual novel.

**Describe the solution you'd like**
I would like a feature where the chars talk like in animal crossing or other games with that style, it would fit perfectly with the new background music feature. I would like a slider to adjust pitch and speed, and i would like to change the audio itself.

I think this would be a great addition to ST, especially for those who dont have the computing power or the money for tts.

**Describe alternatives you've considered**
nothing

**Additional context**
Here are some examples of what i mean: https://forums.rpgmakerweb.com/index.php?threads/what-are-your-thoughts-about-dialogue-blips-when-a-character-speaks.82886/
https://www.youtube.com/watch?v=5QPp1MZvkl0&t=941s

**Comment by Dampfinchen** [comment]
Yes I think that would be quite cool. You could also have character's mouth animated as soon as quotes are detected when streaming the tokens. Like in Phoenix Wright, you could have two sets of the same sprite, talking and idle.

https://static.wikia.nocookie.net/aceattorney/images/c/cf/Phoenix_Thinking_2.gif when quotes are detected
https://static.wikia.nocookie.net/aceattorney/images/7/79/Phoenix_Thinking_1.gif no quotes/inference stopped

**Comment by IkariDevGIT** [comment]
i know this is low-priority, but i think many would really enjoy this feature(as suggested by all the thumbs up)

**Comment by Gryphe** [comment]
This would be a truly awesome feature to have. The effect might be small but its impact would be big, taking another step towards a true visual novel.

**Comment by IkariDevGIT** [comment]
this could be implemented as kind of an internal(directly built into the tts extension) provider(not really but you get what i mean).
